;;;; A small data-only API. No form, callback, file path, or shell command is accepted.
(in-package #:ataxia.computer-use)

(defparameter +computer-request-fields+
  '(:op :token :sequence :name :purpose :output :x :y :duration :button :state
    :key :modifiers :text :window :application :actions :capture :title :app-id
    :timeout :focus :mode :settle :format :revision :operations :action :group :workspace
    :dx :dy :zoom :rotation :width :height :padding))
(defun bounded-string (value maximum field &optional (empty-p nil))
  (unless (and (stringp value) (<= (if empty-p 0 1) (length value) maximum))
    (%computer-reject "invalid-argument" (format nil "~A must be a string of at most ~D characters." field maximum)))
  value)
(defun bounded-number (value low high field)
  (unless (and (realp value) (<= low value high))
    (%computer-reject "invalid-argument" (format nil "~A is outside its allowed range." field)))
  value)
(defun %computer-session-by-token (controller token)
  (bounded-string token 64 "token")
  (or (find token (computer-controller-sessions controller) :key #'computer-session-token :test #'equal)
      (%computer-reject "unknown-session" "This session does not exist in the current World.")))
(defun %computer-session-data (session)
  (let ((state (%computer-seat-state session)) (view (computer-session-view session)))
    (list :id (computer-session-id session) :name (computer-session-name session)
          :state (string-downcase (symbol-name (computer-session-state session)))
          :sequence (computer-session-sequence session)
          :busy (if (or (computer-session-action session) (computer-session-batch session) (computer-session-capture session)) t :false)
          :message (computer-session-message session) :output (ataxia.kernel:object-id (computer-session-output session))
          :view (string-downcase (symbol-name (computer-view-mode view)))
          :window (when (computer-view-window view) (ataxia.kernel:object-id (window-application (computer-view-window view))))
          :x (if state (nth-value 0 (%computer-pointer-position session)) 0d0)
          :y (if state (nth-value 1 (%computer-pointer-position session)) 0d0)
          :focused-window (let ((focused (and state (computer-input-state-focused state))))
                            (when (window-application focused) (ataxia.kernel:object-id (window-application focused)))))))
(defun %computer-outputs (world)
  (coerce (loop for output in (world-outputs world) collect
                (multiple-value-bind (width height) (output-logical-size output)
                  (list :id (ataxia.kernel:object-id output) :name (ataxia.kernel:output-name output)
                        :width width :height height :scale (ataxia.kernel:output-scale output)))) 'vector))
(defun %computer-application-pid (app)
  (when (typep app 'ataxia.kernel:wayland-application)
    (let ((root (ataxia.kernel:application-root-surface app)))
      (when root (surface-client-pid (ataxia.kernel:surface-runtime-object root))))))
(defun %computer-windows (session &optional (mode (computer-view-mode (computer-session-view session))))
  (when (eq mode :window)
    (return-from %computer-windows
      (coerce (loop for window in (world-windows (computer-session-world session))
                    for application = (window-application window)
                    when (and application (eq :live (ataxia.kernel:object-state application))
                              (ataxia.kernel:application-mapped-p application)) collect
                    (let ((app (window-application window)) (bounds (%computer-window-bounds window)))
                      (list :id (ataxia.kernel:object-id app) :pid (%computer-application-pid app) :title (or (ataxia.kernel:application-title app) "")
                            :app-id (or (ataxia.kernel:application-app-id app) "")
                            :coordinate-space "window-local"
                            :available (if (world-window-visible-p (computer-session-world session) window) t :false)
                            :x 0 :y 0 :origin-x (first bounds) :origin-y (second bounds) :width (third bounds) :height (fourth bounds)
                            :selected (if (eq window (computer-view-window (computer-session-view session))) t :false)
                            :on-output (if (%computer-window-on-output-p session window) t :false)
                            :input (%computer-window-input-data session window)))) 'vector)))
  (let ((world (computer-session-world session)) (output (computer-session-output session)))
    (coerce (loop for window in (world-windows world)
                  when (%computer-window-on-output-p session window) collect
                  (multiple-value-bind (x y width height) (window-output-bounds world window output)
                    (let ((app (window-application window)))
                      (list :id (ataxia.kernel:object-id app) :pid (%computer-application-pid app) :title (or (ataxia.kernel:application-title app) "")
                            :app-id (or (ataxia.kernel:application-app-id app) "")
                            :x x :y y :width width :height height
                            :input (%computer-window-input-data session window))))) 'vector)))
(defun %computer-connect (world request)
  (let* ((controller (%computer-controller world))
         (name (bounded-string (getf request :name) 40 "name"))
         (purpose (bounded-string (getf request :purpose) 160 "purpose"))
         (mode (%computer-view-mode (getf request :mode "window")))
         (output (if (getf request :output)
                     (find (getf request :output) (world-outputs world) :key #'ataxia.kernel:object-id)
                     (first (world-outputs world)))))
    (unless output (%computer-reject "invalid-output" "Choose a connected output."))
    (when (>= (count-if (lambda (s) (not (eq :closed (computer-session-state s)))) (computer-controller-sessions controller)) 4)
      (%computer-reject "session-limit" "At most four sessions can be connected."))
    (setf (computer-controller-sessions controller)
          (remove-if (lambda (s) (eq :closed (computer-session-state s))) (computer-controller-sessions controller)))
    (let ((session (%make-computer-session :id (incf (computer-controller-next-id controller)) :token (random-token)
                                           :world world :output output :name name :purpose purpose :expires (+ (monotonic-time) 60d0)
                                           :view (make-computer-view :mode mode))))
      (setf (computer-controller-sessions controller) (append (computer-controller-sessions controller) (list session)))
      (activate-session session)
      (unless (eq :active (computer-session-state session))
        (%computer-reject "connection-failed" "Could not start this computer-use session."))
      (list :ok t :token (computer-session-token session) :session (%computer-session-data session)))))
(defun %computer-validate-request (request)
  (unless (and (listp request) (evenp (length request)) (<= (length request) 48)) (%computer-reject "invalid-request" "Expected a bounded request object."))
  (loop for key in request by #'cddr do
        (unless (member key +computer-request-fields+)
          (%computer-reject "unknown-field" "Unrecognized request field."))))
(defun request-on-owner (world request)
  (%computer-validate-request request)
  (let ((op (bounded-string (getf request :op) 20 "op")))
    (%computer-controller world)
    (when (equal op "capabilities")
      (return-from request-on-owner
        (list :ok t :features #("window-pid" "target-guard" "batch" "settle" "isolated-seat" "paste" "desktop")
              :desktop (%computer-desktop-capabilities world)
              :paste-formats #("text" "md" "html") :max-text 256 :max-paste 16000)))
    (when (equal op "outputs") (return-from request-on-owner (list :ok t :outputs (%computer-outputs world))))
    (when (equal op "connect") (return-from request-on-owner (%computer-connect world request)))
    (let* ((controller (%computer-controller world)) (session (%computer-session-by-token controller (getf request :token)))
           (state (%computer-seat-state session)))
      (when (> (- (monotonic-time) (computer-session-request-window session)) 1d0)
        (setf (computer-session-request-window session) (monotonic-time) (computer-session-requests session) 0))
      (when (> (incf (computer-session-requests session)) 100) (%computer-reject "rate-limited" "Slow down and retry shortly."))
      (when (and (not (eq :closed (computer-session-state session))) (>= (monotonic-time) (computer-session-expires session)))
        (close-session session "Session expired"))
      (when (eq :active (computer-session-state session))
        (setf (computer-session-expires session) (+ (monotonic-time) 120d0)) (%computer-schedule controller))
      (when (equal op "status") (return-from request-on-owner (list :ok t :session (%computer-session-data session))))
      (unless (or (equal op "disconnect") (eq :active (computer-session-state session)))
        (%computer-reject "not-active" (if (eq :paused (computer-session-state session))
                                          "This session is paused. Resume it in Agent sessions."
                                          "This session is closed.")))
      (when (equal op "desktop")
        (return-from request-on-owner
          (list :ok t :session (%computer-session-data session) :desktop (%computer-desktop-snapshot session))))
      (when (equal op "observe")
        (return-from request-on-owner
          (list :ok t :session (%computer-session-data session)
                :windows (%computer-windows session
                           (if (getf request :mode) (%computer-view-mode (getf request :mode))
                               (computer-view-mode (computer-session-view session))))
                :applications (coerce (mapcar (lambda (entry) (list :id (getf entry :id) :name (getf entry :name)))
                                              (world-application-catalog world (computer-session-output session))) 'vector))))
      (when (equal op "target")
        (let* ((window (%computer-require-window session))
               (id (ataxia.kernel:object-id (window-application window))))
          (unless (eql id (getf request :window))
            (%computer-reject "target-changed" "Select this target again before using its accessibility tree."))
          (return-from request-on-owner
            (list :ok t :session (%computer-session-data session)
                  :window (find id (%computer-windows session) :key (lambda (entry) (getf entry :id)))))))
      (unless (and (integerp (getf request :sequence)) (= (getf request :sequence) (1+ (computer-session-sequence session))))
        (%computer-reject "sequence-mismatch" "Use exactly the next sequence number returned by status."))
      (when (and (or (computer-session-action session) (computer-session-capture session)
                     (and (computer-session-batch session)
                          (not (eq (computer-session-batch session) *computer-running-batch*))))
                 (not (equal op "disconnect")))
        (%computer-reject "busy" "Wait for the current action to finish."))
      (when (member op '("arrange" "window" "viewport") :test #'equal)
        ;; Consume even a failed attempt; the client reconciles status without replay.
        (incf (computer-session-sequence session))
        (let ((result (%computer-desktop-action session op request)))
          (return-from request-on-owner
            (list* :ok t :session (%computer-session-data session) result))))
      (when (equal op "batch")
        (let ((batch (%computer-start-batch world session request)))
          (incf (computer-session-sequence session))
          (return-from request-on-owner batch)))
      (cond
        ((equal op "disconnect") (close-session session "Agent disconnected"))
        ((equal op "view") (change-session-view session (%computer-view-mode (getf request :mode)) (getf request :window)))
        ((equal op "move")
         (multiple-value-bind (width height) (%computer-coordinate-size session)
           (when (%computer-window-view-p session)
             (%computer-require-input-ready session (%computer-require-window session) :pointer))
           (let ((x (bounded-number (getf request :x) 0 (1- width) "x"))
                 (y (bounded-number (getf request :y) 0 (1- height) "y"))
                 (duration (bounded-number (getf request :duration .25d0) .016d0 2d0 "duration")))
             (setf (computer-session-action session) (list :kind :move :start (monotonic-time) :duration duration
                                                           :x0 (nth-value 0 (%computer-pointer-position session)) :y0 (nth-value 1 (%computer-pointer-position session))
                                                           :x x :y y :finished "Cursor ready" :completion (sb-thread:make-semaphore :count 0)))
             (%computer-log session "Moving cursor"))))
        ((equal op "button")
         (let* ((button (getf request :button "left"))
                (code (cdr (assoc button '(("left" . 272) ("right" . 273) ("middle" . 274)) :test #'equal)))
                (mode (getf request :state "click")) (held (gethash code (computer-input-state-buttons state))))
           (unless (and code (member mode '("click" "down" "up") :test #'equal)) (%computer-reject "invalid-button" "Use left/right/middle and click/down/up."))
           (when (if (equal mode "up") (null held) held) (%computer-reject "button-state" "Button state does not match this action."))
           (unless (equal mode "up")
             (let ((target (%computer-point-target session)))
               (when target (%computer-require-input-ready session target :pointer))))
           (unless (equal mode "up") (%computer-button session code t))
           (unless (equal mode "down") (%computer-button session code nil))
           (ataxia.world.web.ui:set-ui-class (overlay-component (computer-session-cursor session)) "tag" "clicked" t)
           (%computer-log session (format nil "~A button · ~A" (string-capitalize button) mode))))
        ((equal op "scroll")
         (unless (%computer-point-target session) (%computer-reject "target-blocked" "Point at an application before scrolling."))
         (%computer-require-input-ready session (%computer-point-target session) :pointer)
         (let ((x (bounded-number (getf request :x 0) -1000 1000 "x")) (y (bounded-number (getf request :y 0) -1000 1000 "y")))
           (dolist (axis (list (cons :horizontal x) (cons :vertical y)))
             (unless (zerop (cdr axis))
               (ataxia.kernel:world-cursor-axis world (computer-session-seat session)
                                                (ataxia.kernel:make-cursor-axis-input :device (computer-session-pointer-device session) :time-msec (%computer-time)
                                                                                      :orientation (car axis) :source :wheel :relative-direction :identical :delta (coerce (cdr axis) 'double-float)
                                                                                      :discrete-delta (round (* 120 (/ (cdr axis) 15)))))))
           (ataxia.runtime:seat-pointer-notify-frame (ataxia.kernel:seat-runtime-object (computer-session-seat session)))
           (%computer-log session "Scrolled application")))
        ((equal op "focus")
         (let ((window (find (getf request :window) (world-windows world) :key (lambda (w) (ataxia.kernel:object-id (window-application w))))))
           (unless (%computer-window-allowed-p session window)
             (%computer-reject "target-blocked" "Window is unavailable in this view. Inspect getWorld() for its state."))
           (%computer-focus session window) (%computer-log session "Focused application")))
        ((equal op "key")
         (unless (%computer-window-allowed-p session (computer-input-state-focused state)) (%computer-reject "no-focus" "Focus or click an application first."))
         (unless (equal (getf request :state) "up")
           (%computer-require-input-ready session (computer-input-state-focused state) :keyboard))
         (let* ((name (bounded-string (getf request :key) 80 "key"))
                (code (ataxia.world.synthetic-input:synthetic-keycode (computer-session-keyboard session) name))
                (mode (getf request :state "tap")) (modifiers (getf request :modifiers))
                (held (member code (computer-session-keys session))))
           (unless (and (<= 0 code 247) (member mode '("down" "up" "tap") :test #'equal)) (%computer-reject "invalid-key" "Use an XKB base key name, or type for text."))
           (unless (and (listp modifiers) (<= (length modifiers) 4)
                        (every (lambda (m) (member m '("Control_L" "Shift_L" "Alt_L" "Super_L") :test #'equal)) modifiers))
             (%computer-reject "invalid-modifiers" "Use Control_L, Shift_L, Alt_L, or Super_L."))
           (when (and modifiers (or (not (equal mode "tap")) (computer-session-keys session))) (%computer-reject "key-state" "Modifier chords require no held keys and state tap."))
           (when (if (equal mode "up") (null held) held) (%computer-reject "key-state" "Key state does not match this action."))
           (let ((mods (mapcar (lambda (m) (ataxia.world.synthetic-input:synthetic-keycode (computer-session-keyboard session) m)) (remove-duplicates modifiers :test #'equal))))
             (when (member code mods) (%computer-reject "invalid-modifiers" "The main key cannot also be a chord modifier."))
             (dolist (modifier mods) (%computer-key session modifier t))
             (unless (equal mode "up") (%computer-key session code t))
             (unless (equal mode "down") (%computer-key session code nil))
             (dolist (modifier (reverse mods)) (%computer-key session modifier nil)))
           (%computer-log session "Sent keyboard input")))
        ((equal op "type")
         (unless (%computer-window-allowed-p session (computer-input-state-focused state)) (%computer-reject "no-focus" "Focus or click an application first."))
         (%computer-require-input-ready session (computer-input-state-focused state) :keyboard)
         (when (computer-session-keys session) (%computer-reject "keys-held" "Release held keys before typing text."))
         (let ((text (bounded-string (getf request :text) 256 "text")))
           (unless (every (lambda (c) (let ((n (char-code c))) (or (member n '(9 10)) (and (>= n 32) (not (<= #xd800 n #xdfff)))))) text)
             (%computer-reject "invalid-text" "Text contains unsupported control characters."))
           (multiple-value-bind (keymap codes) (%computer-text-keymap text)
             (ataxia.world.synthetic-input:set-keyboard-keymap-from-string (computer-session-keyboard session) keymap)
             (setf (computer-session-action session) (list :kind :text :codes codes :finished (format nil "Typed ~D characters" (length text)) :completion (sb-thread:make-semaphore :count 0)))
             (%computer-log session (format nil "Typing ~D characters" (length text))))))
        ((equal op "paste")
         (unless (%computer-window-allowed-p session (computer-input-state-focused state))
           (%computer-reject "no-focus" "Focus an application before pasting."))
         (%computer-require-input-ready session (computer-input-state-focused state) :keyboard)
         (when (computer-session-keys session) (%computer-reject "keys-held" "Release held keys before pasting."))
         (let ((text (bounded-string (getf request :text) 16000 "text" t))
               (format (getf request :format "text")))
           (unless (member format '("text" "md" "html") :test #'equal)
             (%computer-reject "invalid-format" "Use text, md or html."))
           (let* ((keyboard (computer-session-keyboard session))
                  (control (ataxia.world.synthetic-input:synthetic-keycode keyboard "Control_L"))
                  (key (ataxia.world.synthetic-input:synthetic-keycode keyboard "v")))
             (unless (and (<= 0 control 247) (<= 0 key 247))
               (%computer-reject "invalid-key" "The keyboard does not support a paste chord."))
             (seat-set-clipboard-content
              (ataxia.kernel:seat-runtime-object (computer-session-seat session)) text format)
             (%computer-key session control t)
             (%computer-key session key t) (%computer-key session key nil)
             (%computer-key session control nil))
           (%computer-log session (format nil "Pasted ~D characters on the agent seat" (length text)))))
        ((equal op "launch")
         (let ((entry (find (getf request :application) (world-application-catalog world (computer-session-output session)) :key (lambda (entry) (getf entry :id)) :test #'equal)))
           (unless entry (%computer-reject "unknown-application" "Choose an application id returned by observe."))
           (launch-world-application world (computer-session-output session) (getf entry :id)) (%computer-log session (format nil "Launch requested · ~A" (getf entry :name)))))
        ((equal op "capture")
         (when (computer-session-capture session) (%computer-reject "capture-busy" "A capture is already in progress."))
         (let ((ticket (%computer-request-capture session)))
           (unless *computer-running-batch* (incf (computer-session-sequence session)))
           (return-from request-on-owner ticket)))
        (t (%computer-reject "unknown-operation" "This operation is not part of the computer-use API.")))
      (unless *computer-running-batch* (incf (computer-session-sequence session)))
      (%computer-schedule controller)
      (list :ok t :session (%computer-session-data session)))))

(defun %computer-json (value)
  (ataxia.computer-use.wire:encode value))
(defun %request (request &key expected-world expected-generation expected-server)
  "Run validated data on the owner thread; wait only on the calling worker."
  (handler-case
      (let ((result (ataxia.sly-control:agent-inspect
                     (lambda (kernel world)
                       (declare (ignore kernel))
                       (when (and expected-world (not (eq world expected-world)))
                         (%computer-reject "disabled" "This computer-use listener has stopped."))
                       (when (and expected-server
                                  (not (eq expected-server
                                           (computer-controller-server
                                            (%computer-controller world)))))
                         (%computer-reject "disabled" "This computer-use listener has stopped."))
                       (request-on-owner world request))
                     :expected-generation (or expected-generation
                                              (ataxia.kernel:kernel-world-generation (ataxia.sly-control:current-kernel)))
                     :timeout 5d0)))
        (finish-request result))
    (computer-use-rejected (cause)
      (list :ok :false :error (%computer-error-code cause) :message (%computer-error-message cause)))
    (error (cause) (list :ok :false :error "request-failed" :message (princ-to-string cause)))))
(defun request-json (request)
  "Data-only entry point. Human pause and disconnect controls remain authoritative."
  (%computer-json (%request request)))

(defun connect-session (world name purpose output)
  "Create and activate a session on the owner thread."
  (let ((reply (%computer-connect world (list :name name :purpose purpose :mode "window"
                                             :output (ataxia.kernel:object-id output)))))
    (%computer-session-by-token (%computer-controller world) (getf reply :token))))

(defun finish-request (result)
  "Wait for a REQUEST-ON-OWNER result on the calling worker, never the owner thread."
  (typecase result
    (computer-capture (%computer-finish-capture result))
    (computer-batch (%computer-finish-batch result))
    (t result)))
