;;;; Capture only while World holds the frame lease; encode on the control worker.
(in-package #:ataxia.computer-use)
(eval-when (:compile-toplevel :load-toplevel :execute) (require :sb-posix))
(defstruct computer-capture session semaphore pixels width height logical-width logical-height transform path error timestamp
           mode window bounds root-bounds primed-p)
(defun %computer-request-capture (session)
  (when (%computer-window-view-p session) (%computer-require-window session))
  (let* ((world (computer-session-world session)) (controller (%computer-controller world))
         (directory (or (computer-controller-directory controller)
                        (setf (computer-controller-directory controller)
                              (merge-pathnames (format nil "ataxia-agent-~A/" (random-token))
                                               (uiop:ensure-directory-pathname (or (uiop:getenv "XDG_RUNTIME_DIR") (namestring (uiop:temporary-directory)))))))))
    (unless (probe-file directory) (sb-posix:mkdir directory #o700))
    (let ((ticket (make-computer-capture :session session :semaphore (sb-thread:make-semaphore :count 0)
                                         :mode (computer-view-mode (computer-session-view session))
                                         :window (when (%computer-window-view-p session) (computer-view-window (computer-session-view session)))
                                         :path (merge-pathnames (format nil "~D-~D.png" (computer-session-id session) (incf (computer-session-capture-number session))) directory))))
      (setf (computer-session-capture session) ticket)
      (request-world-capture world (computer-session-output session))
      ticket)))
(defun %computer-cancel-capture (session)
  (let ((ticket (computer-session-capture session)))
    (when ticket
      (setf (computer-capture-error ticket) "Capture cancelled")
      (sb-thread:signal-semaphore (computer-capture-semaphore ticket))
      (setf (computer-session-capture session) nil))))
(defun %computer-read-frame (ticket output lease)
  (handler-case
      (let* ((width (ataxia.kernel:frame-width lease)) (height (ataxia.kernel:frame-height lease))
             (pixels (when (<= (* width height) 16777216) (make-array (* width height 4) :element-type '(unsigned-byte 8)))))
        (unless pixels (error "Output is too large for a bounded capture."))
        (cffi:with-foreign-objects ((pack :int) (alignment :int) (row :int) (skip-x :int) (skip-y :int))
          (flet ((read-state (name ptr) (cffi:foreign-funcall "glGetIntegerv" :uint name :pointer ptr :void))
                 (set-store (name value) (cffi:foreign-funcall "glPixelStorei" :uint name :int value :void)))
            (read-state #x88ED pack) (read-state #x0D05 alignment) (read-state #x0D02 row) (read-state #x0D04 skip-x) (read-state #x0D03 skip-y)
            (unwind-protect
                 (progn
                   (cffi:foreign-funcall "glBindBuffer" :uint #x88EB :uint 0 :void)
                   (set-store #x0D05 1) (set-store #x0D02 0) (set-store #x0D04 0) (set-store #x0D03 0)
                   (sb-sys:with-pinned-objects (pixels)
                     (cffi:foreign-funcall "glReadPixels" :int 0 :int 0 :int width :int height :uint #x1908 :uint #x1401 :pointer (sb-sys:vector-sap pixels) :void))
                   (ataxia.world.gles:gles-check-error "agent frame capture"))
              (cffi:foreign-funcall "glBindBuffer" :uint #x88EB :uint (cffi:mem-ref pack :int) :void)
              (set-store #x0D05 (cffi:mem-ref alignment :int)) (set-store #x0D02 (cffi:mem-ref row :int))
              (set-store #x0D04 (cffi:mem-ref skip-x :int)) (set-store #x0D03 (cffi:mem-ref skip-y :int)))))
        (multiple-value-bind (lw lh) (output-logical-size output)
          (setf (computer-capture-pixels ticket) pixels (computer-capture-width ticket) width (computer-capture-height ticket) height
                (computer-capture-logical-width ticket) lw (computer-capture-logical-height ticket) lh
                (computer-capture-transform ticket) (ataxia.kernel:output-transform output) (computer-capture-timestamp ticket) (monotonic-time))))
    (error (cause) (setf (computer-capture-error ticket) (princ-to-string cause))))
  (sb-thread:signal-semaphore (computer-capture-semaphore ticket)))
(defun %computer-complete-window-frames (window)
  (loop for surface across (ataxia.kernel:drawable-surfaces (window-application window))
        for token = (ataxia.kernel:drawable-surface-presentation-token surface)
        when token do (ataxia.kernel:complete-wayland-surface-frame token)))


(defun %computer-read-window (ticket world)
  (handler-case
      (let* ((window (computer-capture-window ticket))
             (bounds (%computer-window-bounds window))
             (lw (third bounds)) (lh (fourth bounds))
             (factor (min 1d0 (/ 1280d0 lw) (/ 960d0 lh)))
             (width (max 1 (round (* lw factor)))) (height (max 1 (round (* lh factor))))
             (pixels (make-array (* width height 4) :element-type '(unsigned-byte 8))))
        (capture-window-pixels world window bounds width height pixels)
        (setf (computer-capture-pixels ticket) pixels
              (computer-capture-width ticket) width (computer-capture-height ticket) height
              (computer-capture-logical-width ticket) lw (computer-capture-logical-height ticket) lh
              (computer-capture-transform ticket) 0 (computer-capture-timestamp ticket) (monotonic-time)
              (computer-capture-bounds ticket) bounds
              (computer-capture-root-bounds ticket) (%computer-root-bounds window))
        (%computer-complete-window-frames window))
    (error (cause) (setf (computer-capture-error ticket) (princ-to-string cause))))
  (sb-thread:signal-semaphore (computer-capture-semaphore ticket)))
(defmethod service-before-render ((controller computer-controller) world lease)
  (declare (ignore world lease))
  (dolist (session (computer-controller-sessions controller)) (%computer-sync-projection session)))

(defmethod service-after-render ((controller computer-controller) world lease)
  (dolist (session (computer-controller-sessions controller))
    (let ((ticket (computer-session-capture session)))
      (when (and ticket (eq :active (computer-session-state session))
                 (null (computer-capture-pixels ticket)) (null (computer-capture-error ticket))
                 (eq (computer-session-output session) (ataxia.kernel:frame-output lease)))
        (cond
          ((eq :desktop (computer-capture-mode ticket))
           (%computer-read-frame ticket (ataxia.kernel:frame-output lease) lease))
          ((computer-capture-primed-p ticket) (%computer-read-window ticket world))
          (t
           ;; Give a frame-throttled offscreen client one event-loop turn to repaint.
           (handler-case (%computer-complete-window-frames (computer-capture-window ticket))
             (error (cause)
               (setf (computer-capture-error ticket) (princ-to-string cause))
               (sb-thread:signal-semaphore (computer-capture-semaphore ticket))))
           (setf (computer-capture-primed-p ticket) t)
           (request-world-capture world (ataxia.kernel:frame-output lease))))))))
(defvar *computer-zlib* nil)
(defun %computer-u32 (number)
  (make-array 4 :element-type '(unsigned-byte 8) :initial-contents
              (loop for shift from 24 downto 0 by 8 collect (ldb (byte 8 shift) number))))
(defun %computer-png-chunk (stream type data)
  (let ((body (concatenate '(simple-array (unsigned-byte 8) (*)) (map 'vector #'char-code type) data)))
    (write-sequence (%computer-u32 (length data)) stream) (write-sequence body stream)
    (sb-sys:with-pinned-objects (body)
      (write-sequence (%computer-u32 (cffi:foreign-funcall "crc32" :ulong 0 :pointer (sb-sys:vector-sap body) :uint (length body) :ulong)) stream))))
(defun %computer-write-png (ticket)
  (unless *computer-zlib* (setf *computer-zlib* (cffi:load-foreign-library "libz.so.1")))
  (let* ((lw (computer-capture-logical-width ticket)) (lh (computer-capture-logical-height ticket))
         (factor (min 1d0 (/ 1280d0 lw) (/ 960d0 lh)))
         (width (max 1 (round (* lw factor)))) (height (max 1 (round (* lh factor))))
         (bw (computer-capture-width ticket)) (bh (computer-capture-height ticket))
         (source (computer-capture-pixels ticket))
         (rows (make-array (* height (1+ (* width 4))) :element-type '(unsigned-byte 8) :initial-element 0)))
    (declare (type (simple-array (unsigned-byte 8) (*)) source rows))
    (if (and (zerop (computer-capture-transform ticket)) (= width bw) (= height bh))
        ;; Window capture already renders at the final image size. Copy rows
        ;; without allocating coordinate floats for every unchanged pixel.
        (let ((stride (* width 4)))
          (dotimes (y height)
            (replace rows source :start1 (1+ (* y (1+ stride)))
                                 :start2 (* y stride) :end2 (* (1+ y) stride))))
        ;; Desktop captures can need scaling, rotation, or reflection.
        (dotimes (y height)
          (dotimes (x width)
            (multiple-value-bind (u v) (transform-normalized-point (computer-capture-transform ticket) (/ (+ x .5d0) width) (/ (+ y .5d0) height))
              (let ((from (* 4 (+ (min (1- bw) (max 0 (floor (* u bw)))) (* bw (min (1- bh) (max 0 (floor (* v bh))))))))
                    (to (+ 1 (* y (1+ (* width 4))) (* x 4))))
                (dotimes (i 4) (setf (aref rows (+ to i)) (aref source (+ from i)))))))))
    (let* ((bound (cffi:foreign-funcall "compressBound" :ulong (length rows) :ulong))
           (compressed (make-array bound :element-type '(unsigned-byte 8))))
      (cffi:with-foreign-object (size :ulong)
        (setf (cffi:mem-ref size :ulong) bound)
        (sb-sys:with-pinned-objects (rows compressed)
          (unless (zerop (cffi:foreign-funcall "compress2" :pointer (sb-sys:vector-sap compressed) :pointer size :pointer (sb-sys:vector-sap rows) :ulong (length rows) :int 3 :int))
            (error "PNG compression failed.")))
        (with-open-file (stream (computer-capture-path ticket) :direction :output :element-type '(unsigned-byte 8) :if-exists :error)
          (write-sequence #(137 80 78 71 13 10 26 10) stream)
          (%computer-png-chunk stream "IHDR" (concatenate 'vector (%computer-u32 width) (%computer-u32 height) #(8 6 0 0 0)))
          (%computer-png-chunk stream "IDAT" (subseq compressed 0 (cffi:mem-ref size :ulong)))
          (%computer-png-chunk stream "IEND" #()))))
    (list :path (namestring (computer-capture-path ticket)) :width width :height height
          :coordinate-width lw :coordinate-height lh :timestamp (computer-capture-timestamp ticket)
          :view (string-downcase (symbol-name (computer-capture-mode ticket)))
          :window (when (computer-capture-window ticket) (ataxia.kernel:object-id (window-application (computer-capture-window ticket)))))))
(defun %computer-finish-capture (ticket)
  (let ((image nil) (accepted nil))
    (unwind-protect
         (progn
           (unless (sb-thread:wait-on-semaphore (computer-capture-semaphore ticket) :timeout 3d0)
             (%computer-reject "capture-timeout" "No frame arrived for this output."))
           (when (computer-capture-error ticket) (%computer-reject "capture-failed" (computer-capture-error ticket)))
           (setf image (%computer-write-png ticket))
           (ataxia.sly-control:agent-inspect
            (lambda (kernel world)
              (declare (ignore kernel))
              (let ((session (computer-capture-session ticket)))
                (unless (and (eq world (computer-session-world session)) (eq :active (computer-session-state session))
                             (eq ticket (computer-session-capture session)))
                  (%computer-reject "capture-revoked" "The session was paused or disconnected during capture."))
                (when (eq :window (computer-capture-mode ticket))
                  (unless (equalp (computer-capture-root-bounds ticket) (%computer-root-bounds (computer-capture-window ticket)))
                    (%computer-reject "window-resized" "Window resized during capture; capture it again."))
                  (%computer-set-basis session (computer-capture-bounds ticket) (computer-capture-root-bounds ticket))
                  (%computer-sync-projection session))
                (let ((old (computer-session-image-path session))) (when (and old (probe-file old)) (delete-file old)))
                (setf (computer-session-image-path session) (computer-capture-path ticket)
                      (computer-session-capture session) nil accepted t)
                (list :ok t :session (%computer-session-data session) :image image))) :timeout 5d0))
      (setf (computer-capture-pixels ticket) nil)
      (unless accepted
        (when (probe-file (computer-capture-path ticket)) (delete-file (computer-capture-path ticket)))
        (ignore-errors (sb-posix:rmdir (uiop:pathname-directory-pathname (computer-capture-path ticket))))
        (ignore-errors (ataxia.sly-control:agent-inspect
                        (lambda (kernel world) (declare (ignore kernel world))
                          (let ((session (computer-capture-session ticket)))
                            (when (eq ticket (computer-session-capture session)) (setf (computer-session-capture session) nil)))) :timeout 2d0))))))
