;;;; Data-only desktop operations share the native session's pause/expiry/sequence gate.
(in-package #:ataxia.computer-use)

(defun %computer-desktop-control (session id action)
  (let* ((world (computer-session-world session)) (window (find-world-window world id)))
    (unless window (%computer-reject "window-not-found" "That desktop window no longer exists."))
    (control-world-window world window action (computer-session-output session))))
(defun %computer-desktop-memory (session)
  (let ((memory (or (computer-session-desktop-state session)
                    (setf (computer-session-desktop-state session)
                          (make-computer-desktop-state)))))
    (maphash (lambda (id plan)
               (when (>= (monotonic-time) (getf plan :expires))
                 (remhash id (computer-desktop-state-plans memory))))
             (computer-desktop-state-plans memory))
    (let ((undo (computer-desktop-state-undo memory)))
      (when (and undo (>= (monotonic-time) (getf undo :expires)))
        (setf (computer-desktop-state-undo memory) nil)))
    memory))

(defun %computer-validate-layout (world operations ids)
  (handler-case (validate-world-layout world operations ids)
    (error (cause) (%computer-reject "invalid-layout" (princ-to-string cause)))))

(defun %computer-desktop-capabilities (world)
  (list :snapshot (if (world-supports-p world :desktop) t :false)
        :layout (if (world-supports-p world :layout) t :false)
        :navigation (if (world-supports-p world :shell-navigation) t :false)
        :scope "world" :native-shortcuts :false
        :window-actions #("close" "minimize" "restore" "maximize" "fullscreen")))
(defun %computer-desktop-snapshot (session)
  (%computer-desktop-require session :desktop)
  (let* ((world (computer-session-world session))
         (memory (%computer-desktop-memory session))
         (state (world-desktop-state world))
         (semantic (copy-list state)))
    ;; Titles and transient visible state do not invalidate a layout while an app
    ;; animates. Geometry in a World snapshot is the intended placement.
    (setf (getf semantic :windows)
          (map 'vector (lambda (window)
                         (let ((copy (copy-list window)))
                           (dolist (field '(:title :visible :available :on-outputs)) (remf copy field))
                           copy))
               (getf state :windows)))
    (let ((fingerprint (ataxia.computer-use.wire:encode semantic)))
      (unless (equal fingerprint (computer-desktop-state-fingerprint memory))
        (incf (computer-desktop-state-revision memory))
        (setf (computer-desktop-state-fingerprint memory) fingerprint)))
    (multiple-value-bind (schema description) (world-layout-schema world)
      (list* :revision (computer-desktop-state-revision memory)
             :generation (ataxia.kernel:kernel-world-generation (ataxia.kernel:world-kernel world))
             :world (string-downcase (symbol-name (class-name (class-of world))))
             :output (ataxia.kernel:object-id (computer-session-output session))
             :capabilities (%computer-desktop-capabilities world)
             :layout-schema schema :layout-description description state))))
(defun %computer-desktop-check-revision (session request)
  (let ((snapshot (%computer-desktop-snapshot session)))
    (unless (and (integerp (getf request :revision))
                 (= (getf request :revision) (getf snapshot :revision)))
      (%computer-reject "desktop-changed" "The World changed. Read getWorld() and replan before acting."))
    snapshot))
(defun %computer-desktop-require (session capability)
  (unless (world-supports-p (computer-session-world session) capability)
    (%computer-reject "unsupported-operation" "This World does not provide that desktop operation.")))
(defun %computer-desktop-idle (session)
  (when (world-active-operation-p (computer-session-world session))
    (%computer-reject "desktop-busy" "A human is moving the desktop. Observe again when the drag ends."))
  (when (or (computer-session-keys session)
            (plusp (hash-table-count (computer-input-state-buttons (%computer-seat-state session)))))
    (%computer-reject "input-held" "Release held input before changing the desktop.")))
(defun %computer-desktop-operations (operations)
  (unless (and (vectorp operations) (not (stringp operations)) (<= 1 (length operations) 64))
    (%computer-reject "invalid-layout" "Supply one to 64 layout operations."))
  (loop for operation across operations do
    (unless (and (hash-table-p operation) (<= 1 (hash-table-count operation) 14))
      (%computer-reject "invalid-layout" "Each layout operation must be a bounded object."))
    (maphash (lambda (key value)
               (unless (and (stringp key) (or (stringp value) (numberp value) (member value '(nil t :false))))
                 (%computer-reject "invalid-layout" "Layout fields must contain scalar data."))) operation))
  operations)
(defun %computer-desktop-preview (session request)
  (%computer-desktop-require session :layout)
  (let* ((snapshot (%computer-desktop-check-revision session request))
         (operations (%computer-desktop-operations (getf request :operations)))
         (ids (map 'list (lambda (window) (getf window :id)) (getf snapshot :windows)))
         (memory (%computer-desktop-memory session)) (plans (computer-desktop-state-plans memory)))
    (%computer-validate-layout (computer-session-world session) operations ids)
    (when (>= (hash-table-count plans) 8)
      (%computer-reject "plan-limit" "At most eight unexpired layout plans may be retained per session."))
    (let ((id (random-token)))
      (setf (gethash id plans) (list :revision (getf snapshot :revision) :operations operations
                                    :ids ids :expires (+ (monotonic-time) 120d0)))
      (list :plan id :revision (getf snapshot :revision) :operations operations))))
(defun %computer-desktop-apply-plan (session request)
  (%computer-desktop-require session :layout)
  (let* ((memory (%computer-desktop-memory session)) (plans (computer-desktop-state-plans memory))
         (id (bounded-string (getf request :plan) 64 "plan")) (plan (gethash id plans))
         (world (computer-session-world session)))
    (unless plan (%computer-reject "plan-expired" "This plan expired, was applied, or belongs to another session."))
    (%computer-desktop-check-revision session (list :revision (getf plan :revision)))
    (%computer-validate-layout world (getf plan :operations) (getf plan :ids))
    (let ((saved (capture-world-layout world)))
      (remhash id plans)
      (handler-case
          (progn
            (apply-world-layout world (getf plan :operations) (getf plan :ids))
            (%computer-log session "Arranged desktop")
            (let ((snapshot (%computer-desktop-snapshot session)) (undo (random-token)))
              (setf (computer-desktop-state-undo memory) (list :token undo :saved saved :revision (getf snapshot :revision)
                                             :expires (+ (monotonic-time) 120d0)))
              (list :undo undo :desktop snapshot)))
        (error (cause)
          (restore-world-layout world saved)
          (error cause))))))
(defun %computer-desktop-undo (session request)
  (%computer-desktop-require session :layout)
  (let* ((memory (%computer-desktop-memory session)) (undo (computer-desktop-state-undo memory)))
    (unless (and undo (equal (getf request :undo) (getf undo :token)))
      (%computer-reject "undo-unavailable" "No matching unexpired Undo exists for this session."))
    (%computer-desktop-check-revision session (list :revision (getf undo :revision)))
    (restore-world-layout (computer-session-world session) (getf undo :saved))
    (setf (computer-desktop-state-undo memory) nil)
    (%computer-log session "Restored desktop arrangement")
    (list :desktop (%computer-desktop-snapshot session))))
(defun %computer-desktop-action (session op request)
  (%computer-desktop-idle session)
  (cond
    ((equal op "layout-preview") (%computer-desktop-preview session request))
    ((equal op "layout-apply") (%computer-desktop-apply-plan session request))
    ((equal op "layout-undo") (%computer-desktop-undo session request))
    ((equal op "window")
     (let* ((snapshot (%computer-desktop-check-revision session request))
            (id (getf request :window))
            (action (cdr (assoc (getf request :action)
                               '(("close" . :close) ("minimize" . :minimize) ("restore" . :restore)
                                 ("maximize" . :maximize) ("fullscreen" . :fullscreen)) :test #'equal))))
       (unless action (%computer-reject "invalid-action" "Use close, minimize, restore, maximize or fullscreen."))
       (unless (and (integerp id) (find id (getf snapshot :windows) :key (lambda (window) (getf window :id))))
         (%computer-reject "window-not-found" "Choose a window ID from getWorld()."))
       (%computer-desktop-control session id action)
       (let ((memory (%computer-desktop-memory session)))
         (clrhash (computer-desktop-state-plans memory)) (setf (computer-desktop-state-undo memory) nil))
       (%computer-log session (format nil "Window ~D · ~A" id (getf request :action)))
       (list :desktop (%computer-desktop-snapshot session))))
    ((equal op "navigate")
     (%computer-desktop-require session :shell-navigation)
     (%computer-desktop-check-revision session request)
     (let ((action (cdr (assoc (getf request :action)
                              '(("workspace" . :workspace) ("overview" . :overview))
                              :test #'equal))))
       (unless action (%computer-reject "invalid-action" "Use workspace or overview."))
       (handler-case
           (navigate-world-desktop (computer-session-world session)
                                   (computer-session-output session) action
                                   :group (getf request :group) :workspace (getf request :workspace))
         (error (cause) (%computer-reject "invalid-navigation" (princ-to-string cause))))
       (%computer-log session "Navigated desktop")
       (list :desktop (%computer-desktop-snapshot session))))
    (t (%computer-reject "unknown-operation" "Unknown desktop operation."))))
