;;;; Data-only desktop operations share the native session's pause/expiry/sequence gate.
(in-package #:ataxia.computer-use)

(defun %computer-desktop-control (session id action)
  (let* ((world (computer-session-world session)) (window (find-world-window world id)))
    (unless window (%computer-reject "window-not-found" "That desktop window no longer exists."))
    (control-world-window world window action (computer-session-output session))))
(defun %computer-desktop-memory (session)
  (or (computer-session-desktop-state session)
      (setf (computer-session-desktop-state session) (make-computer-desktop-state))))

(defun %computer-desktop-capabilities (world)
  (list :snapshot (if (world-supports-p world :desktop) t :false)
        :layout (if (world-supports-p world :layout) t :false)
        :navigation (if (world-supports-p world :viewport-navigation) t :false)
        :scope "world" :native-shortcuts :false
        :window-actions #("close" "minimize" "restore" "maximize" "fullscreen")))
(defun %computer-desktop-snapshot (session)
  (%computer-desktop-require session :desktop)
  (let* ((world (computer-session-world session))
         (memory (%computer-desktop-memory session))
         (state (world-desktop-state world))
         (semantic (copy-list state)))
    ;; Titles and transient visible state do not invalidate a layout while an app
    ;; animates. Geometry in a World snapshot is the intended placement.
    (setf (getf semantic :windows)
          (map 'vector (lambda (window)
                         (let ((copy (copy-list window)))
                           (dolist (field '(:title :visible :available :on-outputs)) (remf copy field))
                           copy))
               (getf state :windows)))
    (let ((fingerprint (ataxia.world.wire:encode semantic)))
      (unless (equal fingerprint (computer-desktop-state-fingerprint memory))
        (incf (computer-desktop-state-revision memory))
        (setf (computer-desktop-state-fingerprint memory) fingerprint)))
    (multiple-value-bind (schema description) (world-layout-schema world)
      (list* :revision (computer-desktop-state-revision memory)
             :generation (ataxia.kernel:kernel-world-generation (ataxia.kernel:world-kernel world))
             :world (string-downcase (symbol-name (class-name (class-of world))))
             :output (ataxia.kernel:object-id (computer-session-output session))
             :capabilities (%computer-desktop-capabilities world)
             :layout-schema schema :layout-description description state))))
(defun %computer-desktop-check-revision (session request)
  (let ((snapshot (%computer-desktop-snapshot session)))
    (unless (and (integerp (getf request :revision))
                 (= (getf request :revision) (getf snapshot :revision)))
      (%computer-reject "desktop-changed" "The World changed. Read its desktop state and replan before acting."))
    snapshot))
(defun %computer-desktop-require (session capability)
  (unless (world-supports-p (computer-session-world session) capability)
    (%computer-reject "unsupported-operation" "This World does not provide that desktop operation.")))
(defun %computer-desktop-idle (session)
  (when (world-active-operation-p (computer-session-world session))
    (%computer-reject "desktop-busy" "A human is moving the desktop. Observe again when the drag ends."))
  (when (or (computer-session-keys session)
            (plusp (hash-table-count (computer-input-state-buttons (%computer-seat-state session)))))
    (%computer-reject "input-held" "Release held input before changing the desktop.")))
(defun %computer-desktop-operations (operations)
  (unless (and (vectorp operations) (not (stringp operations)) (<= 1 (length operations) 64))
    (%computer-reject "invalid-layout" "Supply one to 64 layout operations."))
  (loop for operation across operations do
    (unless (and (hash-table-p operation) (<= 1 (hash-table-count operation) 14))
      (%computer-reject "invalid-layout" "Each layout operation must be a bounded object."))
    (maphash (lambda (key value)
               (unless (and (stringp key) (or (stringp value) (numberp value) (member value '(nil t :false))))
                 (%computer-reject "invalid-layout" "Layout fields must contain scalar data."))) operation))
  operations)
(defun %computer-desktop-arrange (session request)
  (%computer-desktop-require session :layout)
  (%computer-desktop-check-revision session request)
  (let ((operations (%computer-desktop-operations (getf request :operations))))
    (handler-case (apply-world-layout (computer-session-world session) operations)
      (error (cause) (%computer-reject "invalid-layout" (princ-to-string cause)))))
  (%computer-log session "Arranged desktop")
  (list :desktop (%computer-desktop-snapshot session)))
(defun %computer-desktop-action (session op request)
  (%computer-desktop-idle session)
  (cond
    ((equal op "arrange") (%computer-desktop-arrange session request))
    ((equal op "window")
     (let* ((snapshot (%computer-desktop-check-revision session request))
            (id (getf request :window))
            (action (cdr (assoc (getf request :action)
                               '(("close" . :close) ("minimize" . :minimize) ("restore" . :restore)
                                 ("maximize" . :maximize) ("fullscreen" . :fullscreen)) :test #'equal))))
       (unless action (%computer-reject "invalid-action" "Use close, minimize, restore, maximize or fullscreen."))
       (unless (and (integerp id) (find id (getf snapshot :windows) :key (lambda (window) (getf window :id))))
         (%computer-reject "window-not-found" "Choose a window ID from the desktop state."))
       (%computer-desktop-control session id action)
       (%computer-log session (format nil "Window ~D · ~A" id (getf request :action)))
       (list :desktop (%computer-desktop-snapshot session))))
    ((equal op "viewport")
     (%computer-desktop-require session :viewport-navigation)
     (%computer-desktop-check-revision session request)
     (let* ((world (computer-session-world session))
            (output (and (integerp (getf request :output))
                         (find (getf request :output) (world-outputs world) :key #'ataxia.kernel:object-id)))
            (action (cdr (assoc (getf request :action)
                               '(("set" . :set) ("pan" . :pan) ("frame-window" . :frame-window)
                                 ("frame-region" . :frame-region)) :test #'equal))))
       (unless output (%computer-reject "invalid-output" "Choose an explicit connected output ID from the desktop state."))
       (unless action (%computer-reject "invalid-action" "Use set, pan, frame-window or frame-region."))
       (let ((fields (case action (:set '(:x :y :zoom :rotation)) (:pan '(:dx :dy))
                      (:frame-window '(:window :rotation :padding))
                      (:frame-region '(:x :y :width :height :rotation :padding)))))
         (loop for key in '(:x :y :dx :dy :zoom :rotation :width :height :window :padding :group :workspace)
               when (and (member key request) (not (member key fields))) do
                 (%computer-reject "invalid-argument" "Field does not apply to this viewport action."))
         (handler-case
             (apply #'navigate-world-viewport world output action
                    (loop for key in fields when (member key request) append (list key (getf request key))))
           (error (cause) (%computer-reject "invalid-navigation" (princ-to-string cause)))))
       (%computer-log session (format nil "Updated viewport ~D" (ataxia.kernel:object-id output)))
       (list :desktop (%computer-desktop-snapshot session))))
    (t (%computer-reject "unknown-operation" "Unknown desktop operation."))))
