;;;; Agent input owns its grabs and coordinates; World owns placement and focus.
(in-package #:ataxia.computer-use)

(defmethod seat-focus-allowed-p ((seat computer-seat) target)
  ;; Mapping an unrelated window must not redirect an agent's pending text.
  (or (null target) *computer-internal-input*))

(defun %computer-focus (session target)
  (when target
    (unless (%computer-window-allowed-p session target)
      (%computer-reject "target-blocked" "Window is unavailable in this view. Inspect getWorld() for its state."))
    (let ((view (computer-session-view session)))
      (unless (eq target (computer-view-window view))
        (when (or (computer-session-keys session)
                  (plusp (hash-table-count (computer-input-state-buttons (%computer-seat-state session)))))
          (%computer-reject "input-held" "Release held input before selecting another window."))
        (%computer-set-basis session (%computer-window-bounds target) (%computer-root-bounds target) t)
        (setf (computer-view-window view) target))))
  (let ((*computer-internal-input* t))
    (focus-world-target (computer-session-world session) (computer-session-seat session) target)
    (setf (computer-input-state-focused (%computer-seat-state session)) target))
  (%computer-sync-projection session))

(defun %computer-time () (mod (floor (* 1000 (monotonic-time))) (expt 2 32)))
(defun %computer-point-target (session)
  (when (%computer-window-view-p session)
    (let ((window (%computer-require-window session (not *computer-internal-input*))))
      (return-from %computer-point-target
        (when (or (%computer-captured-target (%computer-seat-state session))
                  (multiple-value-bind (x y) (%computer-local-position session window)
                    (ataxia.kernel:interactable-hit-test
                     (window-application window) (computer-session-world session) x y)))
          window))))
  (let* ((state (%computer-seat-state session))
         (target (or (%computer-captured-target state)
                     (world-target-at (computer-session-world session) (computer-session-output session)
                                      (computer-input-state-x state) (computer-input-state-y state)))))
    (when (%computer-window-allowed-p session target) target)))
(defun %computer-live-input-p (session)
  (or *computer-internal-input* (eq :active (computer-session-state session))))
(defun %computer-move (session x y)
  (multiple-value-bind (width height) (%computer-coordinate-size session)
    (ataxia.kernel:world-cursor-motion
     (computer-session-world session) (computer-session-seat session)
     (ataxia.kernel:make-cursor-motion-input
      :device (computer-session-pointer-device session) :time-msec (%computer-time)
      :absolute-p t :x (coerce (/ x width) 'double-float) :y (coerce (/ y height) 'double-float))))
  (ataxia.runtime:seat-pointer-notify-frame
   (ataxia.kernel:seat-runtime-object (computer-session-seat session))))

(defmethod ataxia.kernel:world-cursor-motion :around
    ((world ataxia.kernel:world) (seat computer-seat) input)
  (let* ((session (%computer-seat-session seat)) (state (%computer-seat-state session)))
    (when (and state (%computer-live-input-p session))
      (multiple-value-bind (width height) (%computer-coordinate-size session)
        (if (%computer-window-view-p session)
            (let ((view (computer-session-view session)))
              (setf (computer-view-x view) (* width (ataxia.kernel:cursor-motion-input-x input))
                    (computer-view-y view) (* height (ataxia.kernel:cursor-motion-input-y input)))
              (%computer-sync-projection session))
            (setf (computer-input-state-x state) (* width (ataxia.kernel:cursor-motion-input-x input))
                  (computer-input-state-y state) (* height (ataxia.kernel:cursor-motion-input-y input)))))
      (let ((target (%computer-point-target session)))
        (unless (eq target (computer-input-state-hovered state))
          (when (computer-input-state-hovered state)
            (ataxia.kernel:interactable-pointer-leave
             (window-application (computer-input-state-hovered state)) world seat))
          (setf (computer-input-state-hovered state) target))
        (if target
            (multiple-value-bind (x y) (%computer-local-position session target)
              (ataxia.kernel:interactable-pointer-motion (window-application target) world seat x y input))
            (ataxia.kernel:clear-wayland-focus seat :pointer t)))
      (%computer-update-cursor session)))
  input)

(defun %computer-button (session code pressed)
  (let* ((world (computer-session-world session)) (seat (computer-session-seat session))
         (runtime-seat (ataxia.kernel:seat-runtime-object seat))
         (count (ataxia.runtime:seat-pointer-button-press-count runtime-seat code))
         (time (%computer-time)))
    (ataxia.kernel:world-cursor-button
     world seat (ataxia.kernel:make-cursor-button-input
                 :device (computer-session-pointer-device session) :time-msec time
                 :code code :state (if pressed :pressed :released)))
    ;; Release a protocol grab even if the captured surface vanished during a drag.
    (when (and (not pressed) (plusp count)
               (= count (ataxia.runtime:seat-pointer-button-press-count runtime-seat code)))
      (ataxia.runtime:seat-pointer-notify-button runtime-seat time code :released))
    (ataxia.runtime:seat-pointer-notify-frame runtime-seat)
    (%computer-held-deadline session)))

(defun %computer-deliver-button (session target input &key clamp)
  (multiple-value-bind (x y) (%computer-local-position session target)
    (when clamp
      (destructuring-bind (left top width height) (%computer-root-bounds target)
        (setf x (max left (min (- (+ left width) least-positive-double-float) x))
              y (max top (min (- (+ top height) least-positive-double-float) y)))))
    (ataxia.kernel:interactable-pointer-button
     (window-application target) (computer-session-world session) (computer-session-seat session) x y input)))

(defmethod ataxia.kernel:world-cursor-button :around
    ((world ataxia.kernel:world) (seat computer-seat) input)
  (let* ((session (%computer-seat-session seat)) (state (%computer-seat-state session))
         (code (ataxia.kernel:cursor-button-input-code input))
         (pressed (eq :pressed (ataxia.kernel:cursor-button-input-state input))))
    (when (and state (%computer-live-input-p session))
      (if pressed
          (let ((target (%computer-point-target session)))
            (unless target
              (%computer-reject "target-blocked" "Point at an application. Agent input cannot operate shell controls."))
            (%computer-focus session target)
            (setf (gethash code (computer-input-state-buttons state)) target)
            (%computer-deliver-button session target input))
          (let ((target (gethash code (computer-input-state-buttons state))))
            (when (%computer-window-allowed-p session target)
              (%computer-deliver-button session target input :clamp (not (%computer-window-view-p session))))
            (remhash code (computer-input-state-buttons state))))))
  input)
(defmethod ataxia.kernel:world-cursor-axis :around
    ((world ataxia.kernel:world) (seat computer-seat) input)
  (let* ((session (%computer-seat-session seat))
         (target (and (%computer-seat-state session) (%computer-point-target session))))
    (when (and target (%computer-live-input-p session))
      (multiple-value-bind (x y) (%computer-local-position session target)
        (ataxia.kernel:interactable-pointer-axis (window-application target) world seat x y input))))
  input)
(defun %computer-held-deadline (session)
  (let ((state (%computer-seat-state session)))
    (if (or (computer-session-keys session)
            (and state (plusp (hash-table-count (computer-input-state-buttons state)))))
        (unless (computer-session-held-since session)
          (setf (computer-session-held-since session) (monotonic-time)))
        (setf (computer-session-held-since session) nil))))
(defun %computer-key (session code pressed)
  (if pressed (pushnew code (computer-session-keys session))
      (setf (computer-session-keys session) (remove code (computer-session-keys session))))
  (ataxia.world.synthetic-input:synthetic-key (computer-session-keyboard session) code pressed (%computer-time))
  (%computer-held-deadline session))
(defmethod ataxia.kernel:world-key-event :around
    ((world ataxia.kernel:world) (seat computer-seat) input)
  (let* ((session (%computer-seat-session seat)) (state (%computer-seat-state session))
         (target (and state (computer-input-state-focused state))))
    (when (and (%computer-live-input-p session)
               (or (%computer-window-allowed-p session target)
                   (and *computer-internal-input* (window-application target)
                        (eq :live (ataxia.kernel:object-state (window-application target))))))
      ;; Application input only: synthetic seats cannot execute World shortcuts.
      (ataxia.kernel:interactable-key-event (window-application target) world seat input)))
  input)
(defun %computer-pause-for-human (world target &optional (reason "Paused · you took control of this application"))
  (let ((controller (world-service world :computer-use)))
    (when controller
      (dolist (session (computer-controller-sessions controller))
        (let ((state (%computer-seat-state session)))
          (when (and (eq :active (computer-session-state session)) target state
                     (or (eq target (computer-input-state-focused state))
                         (eq target (%computer-captured-target state))
                         (and (%computer-window-view-p session)
                              (eq target (computer-view-window (computer-session-view session))))))
            (pause-session session reason)))))))
(defmethod service-pointer-button ((controller computer-controller) world seat input)
  (when (eq :pressed (ataxia.kernel:cursor-button-input-state input))
    (multiple-value-bind (x y) (world-pointer-position world seat)
      (let ((output (world-seat-output world seat)))
        (when (and output x y)
          (%computer-pause-for-human world (world-target-at world output x y)))))))
(defgeneric emergency-stop (world))
(defmethod emergency-stop ((world ataxia.kernel:world)) nil)
(defmethod service-key-event ((controller computer-controller) world seat input)
  (when (and (typep input 'ataxia.kernel:key-input)
             (eq :pressed (ataxia.kernel:key-input-state input)))
    (if (and (member :control (ataxia.kernel:key-input-modifiers input))
             (member :alt (ataxia.kernel:key-input-modifiers input))
             (find "Escape" (ataxia.kernel:key-input-keysyms input) :test #'equal))
        (progn
          (dolist (session (computer-controller-sessions controller))
            (pause-session session "Paused · emergency shortcut"))
          (emergency-stop world)
          t)
        (progn (%computer-pause-for-human world (world-seat-focus world seat)) nil))))

(defun %computer-text-keymap (text)
  (let ((characters (remove-duplicates (coerce text 'list))))
    (when (> (length characters) 200) (%computer-reject "text-too-varied" "Use at most 200 distinct characters per text action."))
    (values
     (with-output-to-string (out)
       (write-string "xkb_keymap { xkb_keycodes { minimum=8; maximum=255; " out)
       (loop for character in characters for i from 0 do (format out "<T~3,'0D>=~D; " i (+ i 9)))
       (write-string "}; xkb_types { type \"ONE_LEVEL\" { modifiers=None; map[None]=Level1; }; }; xkb_compatibility {}; xkb_symbols { " out)
       (loop for character in characters for i from 0 do
             (format out "key <T~3,'0D> { type=\"ONE_LEVEL\", [~A] }; " i
                     (case (char-code character) (10 "Return") (9 "Tab")
                           (otherwise (format nil "U~4,'0X" (char-code character))))))
       (write-string "}; };" out))
     (loop for character across text collect (1+ (position character characters))))))
(defun %computer-step (session)
  (let* ((state (%computer-seat-state session))
         (target (or (%computer-captured-target state) (computer-input-state-focused state))))
    (when (and target (not (%computer-window-allowed-p session target)))
      (pause-session session "Paused · application left the approved output")
      (return-from %computer-step nil)))
  (let* ((action (computer-session-action session)) (kind (getf action :kind)) (done nil))
    (case kind
      (:move
       (let* ((progress (min 1d0 (/ (- (monotonic-time) (getf action :start)) (getf action :duration))))
              (eased (ataxia.world:ease-in-out-cubic progress)))
         (%computer-move session (+ (getf action :x0) (* eased (- (getf action :x) (getf action :x0))))
                         (+ (getf action :y0) (* eased (- (getf action :y) (getf action :y0)))))
         (setf done (= progress 1d0))))
      (:text
       (let ((code (pop (getf action :codes))))
         (when code (%computer-key session code t) (%computer-key session code nil))
         (setf done (null (getf action :codes)))
         (when done (ataxia.runtime:set-keyboard-keymap-from-names (computer-session-keyboard session) :layout "us")))))
    (when done
      (setf (computer-session-action session) nil)
      (%computer-log session (getf action :finished))
      (when (getf action :completion) (sb-thread:signal-semaphore (getf action :completion))))))

(defun %computer-window-unavailable (world application)
  (let* ((controller (world-service world :computer-use))
         (window (and controller (find application (world-windows world) :key #'window-application))))
    (when (and window controller)
      (dolist (session (computer-controller-sessions controller))
        (let ((state (%computer-seat-state session)) (view (computer-session-view session)))
          (when (and state (not (eq :closed (computer-session-state session)))
                     (or (eq window (computer-view-window view))
                         (eq window (computer-input-state-focused state))
                         (eq window (%computer-captured-target state))))
            ;; Closing a file dialog is an ordinary workflow transition. Keep
            ;; approval, but never infer a replacement target. An interrupted
            ;; stream or held input still pauses and stops the remaining batch.
            (if (or (computer-session-action session) (computer-session-keys session)
                    (plusp (hash-table-count (computer-input-state-buttons state))))
                (pause-session session "Paused · application closed during input")
                (%computer-release session))
            (%computer-cancel-capture session)
            (when (computer-session-image-path session)
              (ignore-errors (delete-file (computer-session-image-path session)))
              (setf (computer-session-image-path session) nil))
            (setf (computer-view-window view) nil (computer-view-bounds view) nil
                  (computer-view-root-bounds view) nil
                  (computer-view-x view) 0d0 (computer-view-y view) 0d0)
            (%computer-sync-projection session)
            (when (eq :active (computer-session-state session))
              (%computer-log session "Application closed · select another window"))))))))
(defmethod service-object-removing
    ((controller computer-controller) world (application ataxia.kernel:wayland-application) reason)
  (declare (ignore reason))
  (%computer-window-unavailable world application))
(defmethod service-object-changed
    ((controller computer-controller) world (application ataxia.kernel:wayland-application) change)
  (when (and (eq :mapped (ataxia.kernel:object-change-kind change))
             (null (ataxia.kernel:object-change-value change)))
    (%computer-window-unavailable world application)))
