;;;; Session state, held input and deadlines; service.lisp owns attachment.
(in-package #:ataxia.computer-use)
(eval-when (:compile-toplevel :load-toplevel :execute) (require :sb-posix))
(defstruct computer-input-state
  (x 0d0) (y 0d0) (buttons (make-hash-table)) focused hovered)
(defstruct computer-view (mode :window) window bounds root-bounds
  (x 0d0) (y 0d0) visible-p)
(defstruct computer-desktop-state
  (revision 0) fingerprint)
(defstruct (computer-session (:constructor %make-computer-session))
  id token name purpose output world
  (state :pending) (sequence 0) (expires 0d0)
  (requests 0) (request-window 0d0)
  seat input-state keyboard pointer keyboard-device pointer-device cursor
  (keys nil) (held-since nil) action
  (message "Connecting")
  capture image-path (capture-number 0) batch (view (make-computer-view)) desktop-state)
(defstruct computer-batch session actions capture-p generation (completed 0) (settle .15d0))
(defvar *computer-running-batch* nil)
(defstruct (computer-controller (:constructor %make-computer-controller))
  world (sessions nil) (next-id 0) timer (panels nil) directory)
(defclass computer-seat (ataxia.kernel:logical-seat)
  ((session :initarg :session :reader %computer-seat-session)))
(defvar *computer-internal-input* nil)
(define-condition computer-use-rejected (error)
  ((code :initarg :code :reader %computer-error-code)
   (message :initarg :message :reader %computer-error-message))
  (:report (lambda (condition stream) (princ (%computer-error-message condition) stream))))
(defun %computer-reject (code message)
  (error 'computer-use-rejected :code code :message message))
(defun %computer-controller (world)
  (or (world-service world :computer-use) (%computer-reject "disabled" "Computer use is not enabled in this World.")))
(defun random-token ()
  (with-open-file (stream #P"/dev/urandom" :element-type '(unsigned-byte 8))
    (format nil "~(~{~2,'0X~}~)" (loop repeat 32 collect (read-byte stream)))))
(defun %computer-log (session message)
  (setf (computer-session-message session) message)
  (%computer-refresh-ui (computer-session-world session))
  session)
(defun %computer-schedule (controller)
  (let ((now (monotonic-time)) (delay nil))
    (dolist (session (computer-controller-sessions controller))
      (unless (eq :closed (computer-session-state session))
        (let ((next (if (computer-session-action session) 16d0
                        (* 1000 (max .001d0 (- (computer-session-expires session) now))))))
          (when (computer-session-held-since session)
            (setf next (min next (* 1000 (max .001d0 (- (+ 5d0 (computer-session-held-since session)) now))))))
          (setf delay (if delay (min delay next) next)))))
    (when (computer-controller-timer controller)
      (ataxia.runtime:update-event-loop-timer (computer-controller-timer controller)
                                              (if delay (max 1 (ceiling delay)) 0)))))
(defun %computer-release (session)
  (let* ((action (computer-session-action session))
         (text-p (eq :text (getf action :kind))))
    (setf (computer-session-action session) nil)
    (when (getf action :completion) (sb-thread:signal-semaphore (getf action :completion)))
    (when (and text-p (computer-session-keyboard session) (ataxia.runtime:native-object-live-p (computer-session-keyboard session)))
      (ataxia.runtime:set-keyboard-keymap-from-names (computer-session-keyboard session) :layout "us")))
  (when (computer-session-seat session)
    (let* ((seat (computer-session-seat session))
           (state (%computer-seat-state session))
           (*computer-internal-input* t))
      (dolist (code (copy-list (computer-session-keys session)))
        (%computer-key session code nil))
      (when state
        (dolist (code (loop for code being the hash-keys of (computer-input-state-buttons state) collect code))
          (%computer-button session code nil))
        (%computer-focus session nil)
        (ataxia.kernel:clear-wayland-focus seat :pointer t)
        (setf (computer-input-state-hovered state) nil))))
  (setf (computer-session-keys session) nil (computer-session-held-since session) nil))
(defgeneric session-state-changed (session))
(defmethod session-state-changed ((session computer-session)) nil)
(defun pause-session (session &optional (reason "Paused by you"))
  (when (eq :active (computer-session-state session))
    (%computer-release session)
    (setf (computer-session-state session) :paused
          (computer-session-expires session) (+ (monotonic-time) 600d0))
    (%computer-cancel-capture session)
    (when (computer-session-image-path session)
      (ignore-errors (delete-file (computer-session-image-path session)))
      (setf (computer-session-image-path session) nil))
    (%computer-log session reason)
    (%computer-schedule (%computer-controller (computer-session-world session)))
    (session-state-changed session)))
(defun close-session (session &optional (reason "Disconnected"))
  (unless (eq :closed (computer-session-state session))
    (setf (computer-session-desktop-state session) nil)
    (%computer-release session)
    (setf (computer-session-state session) :closed)
    (%computer-cancel-capture session)
    (when (computer-session-image-path session)
      (ignore-errors (delete-file (computer-session-image-path session)))
      (setf (computer-session-image-path session) nil))
    (when (computer-session-cursor session)
      (remove-agent-widget (computer-session-world session) (computer-session-cursor session))
      (setf (computer-session-cursor session) nil))
    (when (computer-session-keyboard session)
      (ataxia.world.synthetic-input:destroy-synthetic-input (computer-session-keyboard session)))
    (when (computer-session-pointer session)
      (ataxia.world.synthetic-input:destroy-synthetic-input (computer-session-pointer session)))
    (when (computer-session-seat session)
      (present-agent-cursor (computer-session-world session) (computer-session-seat session)
                            (computer-session-output session) -100000d0 -100000d0 nil)
      (ataxia.kernel:destroy-logical-seat (computer-session-seat session)))
    (setf (computer-session-seat session) nil)
    (%computer-log session reason)
    (%computer-schedule (%computer-controller (computer-session-world session)))
    (session-state-changed session)))
(defun activate-session (session)
  "Activate a new session or resume it from the human UI."
  (unless (member (computer-session-state session) '(:pending :paused)) (return-from activate-session nil))
  (let* ((world (computer-session-world session))
         (kernel (ataxia.kernel:world-kernel world))
         (runtime (ataxia.kernel:kernel-runtime kernel)))
    (unless (member (computer-session-output session) (world-outputs world))
      (close-session session "Output disconnected") (return-from activate-session nil))
    (handler-case
        (progn
          (unless (computer-session-seat session)
            (let ((seat (ataxia.kernel:create-logical-seat kernel (format nil "agent-~D" (computer-session-id session)))))
              (change-class seat 'computer-seat :session session)
              (setf (computer-session-seat session) seat
                    (computer-session-input-state session) (make-computer-input-state))
              (setf (computer-session-pointer session) (ataxia.world.synthetic-input:create-synthetic-input runtime :pointer "Agent pointer")
                    (computer-session-pointer-device session) (ataxia.kernel:register-input-device kernel (computer-session-pointer session) :seat seat)
                    (computer-session-keyboard session) (ataxia.world.synthetic-input:create-synthetic-input runtime :keyboard "Agent keyboard")
                    (computer-session-keyboard-device session) (ataxia.kernel:register-input-device kernel (computer-session-keyboard session) :seat seat))
              (ataxia.runtime:set-keyboard-keymap-from-names (computer-session-keyboard session) :layout "us")
              (ataxia.runtime:set-keyboard-repeat-info (computer-session-keyboard session) 0 0)
              (%computer-create-cursor session)))
          (setf (computer-session-state session) :active (computer-session-expires session) (+ (monotonic-time) 120d0))
          (%computer-log session "Connected · ready")
          (%computer-schedule (%computer-controller world)))
      (error (cause)
        (close-session session "Connection failed")
        (format *error-output* "[computer-use] Seat creation failed: ~A~%" cause)))))
(defun %computer-tick (controller)
  (dolist (session (copy-list (computer-controller-sessions controller)))
    (handler-case
        (cond
          ((eq :closed (computer-session-state session)))
          ((>= (monotonic-time) (computer-session-expires session)) (close-session session "Session expired"))
          ((and (computer-session-held-since session) (>= (- (monotonic-time) (computer-session-held-since session)) 5d0))
           (pause-session session "Paused · held input timed out"))
          ((computer-session-action session) (%computer-step session)))
      (error (cause)
        (pause-session session "Paused · input failed")
        (format *error-output* "[computer-use] Input failed: ~A~%" cause))))
  (%computer-schedule controller)
  0)
(defmethod agent-seat-p ((seat computer-seat)) t)
(defun %computer-seat-state (session)
  (when (computer-session-seat session) (computer-session-input-state session)))
(defun %computer-captured-target (state)
  (when state
    (loop for target being the hash-values of (computer-input-state-buttons state)
          when target return target)))
