(in-package #:ataxia.computer-use)
(defclass computer-panel (rmlui-widget)
  ((sessions :initform nil :accessor %computer-panel-sessions)))
(defclass computer-cursor-label (rmlui-widget) ())
(defmethod overlay-input-enabled-p ((widget computer-cursor-label)) nil)
(defparameter +computer-colors+ '("#365dc0" "#35664f" "#9a651b" "#99517a"))
(defparameter +computer-tints+ '((.21d0 .36d0 .75d0 1d0) (.21d0 .40d0 .31d0 1d0) (.60d0 .40d0 .11d0 1d0) (.60d0 .32d0 .48d0 1d0)))
(defun %computer-color (session) (nth (mod (1- (computer-session-id session)) 4) +computer-colors+))
(defun %computer-widget (class world file output width height layer)
  (let ((path (asdf:system-relative-pathname "ataxia-computer-use" (concatenate 'string "src/world/computer-use/" file))))
    (create-agent-widget class world (uiop:read-file-string path)
                          :source-path (namestring path) :output output :component-factory #'ataxia.world.rmlui:make-rmlui-component
                          :width width :height height :layer layer)))
(defun %computer-create-panel (world output)
  (let* ((controller (%computer-controller world))
         (panel (%computer-widget 'computer-panel world "panel.rml" output 380d0 110d0 1450)))
    (push panel (computer-controller-panels controller))
    (bind-agent-widget-event panel "pause-all"
                             (lambda (widget event) (declare (ignore widget event))
                               (dolist (session (computer-controller-sessions controller)) (pause-session session))))
    (loop for i below 4 do
          (let ((index i))
            (dolist (action '("resume" "pause" "stop"))
              (let ((operation action))
                (bind-agent-widget-event panel (format nil "~A~D" action index)
                                         (lambda (widget event)
                                           (declare (ignore event))
                                           (let ((session (nth index (%computer-panel-sessions widget))))
                                             (when session
                                               (cond ((equal operation "resume") (activate-session session))
                                                     ((equal operation "pause") (pause-session session))
                                                     (t (close-session session "Disconnected by you")))))))))))
    panel))
(defun %computer-create-panels (world)
  (dolist (output (world-outputs world)) (%computer-create-panel world output))
  (%computer-refresh-ui world))
(defun %computer-refresh-ui (world)
  (let ((controller (world-service world :computer-use)))
    (when controller
      (dolist (panel (computer-controller-panels controller))
        (let* ((output (find (overlay-output panel) (world-outputs world)))
               (sessions (remove-if-not (lambda (session)
                                          (and (not (eq :closed (computer-session-state session)))
                                               (eq (overlay-output panel) (computer-session-output session))))
                                        (computer-controller-sessions controller))))
          (setf (%computer-panel-sessions panel) sessions)
          (if sessions (show-overlay world panel) (hide-overlay world panel))
          (when output
            (multiple-value-bind (width height) (output-logical-size output)
              (position-widget world panel (max 0d0 (- width 396d0)) 12d0 (max 1d0 (min 380d0 (- width 16d0)))
                                   (max 1d0 (min (- height 32d0)
                                                 (if sessions
                                                     (+ 120d0 (* 125d0 (length sessions)))
                                                     140d0)))))
            (set-widget-style panel "panel" "width" (format nil "~Fdp" (overlay-width panel)))
            (set-widget-style panel "panel" "height" (format nil "~Fdp" (overlay-height panel))))
          (set-widget-style panel "empty" "display" (if sessions "none" "block"))
          (loop for i below 4 for session = (nth i sessions) do
                (set-widget-style panel (format nil "card~D" i) "display" (if session "block" "none"))
                (when session
                  (set-widget-text panel (format nil "name~D" i) (short-ui-text (computer-session-name session) 24))
                  (set-widget-text panel (format nil "state~D" i) (string-upcase (symbol-name (computer-session-state session))))
                  (set-widget-text panel (format nil "detail~D" i)
                             (computer-session-message session))
                  (set-widget-text panel (format nil "scope~D" i)
                             (format nil "~A · ~A" (ataxia.kernel:output-name (computer-session-output session))
                                     (if (%computer-window-view-p session)
                                         (let ((window (computer-view-window (computer-session-view session))))
                                           (if window (short-ui-text (or (ataxia.kernel:application-title (window-application window)) "Window view") 28)
                                               "Window view · select an app"))
                                         "Desktop view")))
                  (set-widget-style panel (format nil "dot~D" i) "background-color" (%computer-color session))
                  (set-widget-style panel (format nil "resume~D" i) "display" (if (eq :paused (computer-session-state session)) "block" "none"))
                  (set-widget-text panel (format nil "resume~D" i) "Resume")
                  (set-widget-style panel (format nil "pause~D" i) "display" (if (eq :active (computer-session-state session)) "block" "none"))
                  (set-widget-text panel (format nil "stop~D" i) "Disconnect")
                  (%computer-update-cursor session))))))))
(defun %computer-create-cursor (session)
  (let ((cursor (%computer-widget 'computer-cursor-label (computer-session-world session) "cursor.rml"
                                  (computer-session-output session) 180d0 46d0 1500)))
    (setf (computer-session-cursor session) cursor)
    (set-widget-style cursor "" "--accent" (%computer-color session))
    (set-widget-text cursor "name" (short-ui-text (computer-session-name session) 24))
    (bind-agent-widget-event cursor "tag:animationend"
                             (lambda (widget event) (declare (ignore event))
                               (ataxia.world.rmlui:set-rmlui-class (overlay-component widget) "tag" "clicked" nil)))
    (%computer-update-cursor session)))
(defun %computer-update-cursor (session)
  (let* ((world (computer-session-world session)) (state (%computer-seat-state session))
         (cursor (computer-session-cursor session)) (output (computer-session-output session)))
    (when (and cursor state)
      (let ((visible (or (not (%computer-window-view-p session))
                         (computer-view-visible-p (computer-session-view session)))))
        (if visible (show-overlay world cursor) (hide-overlay world cursor)))
      (present-agent-cursor
       world (computer-session-seat session) output
       (computer-input-state-x state) (computer-input-state-y state)
       (if (eq :paused (computer-session-state session)) '(.6d0 .65d0 .72d0 1d0)
           (nth (mod (1- (computer-session-id session)) 4) +computer-tints+)))
      (multiple-value-bind (width height) (output-logical-size output)
        (position-widget world cursor
                         (max 0d0 (min (+ 18d0 (computer-input-state-x state)) (- width 180d0)))
                         (max 0d0 (min (+ 20d0 (computer-input-state-y state)) (- height 46d0)))
                         180d0 46d0))
      (set-widget-text cursor "state"
                       (if (eq :paused (computer-session-state session)) "Paused · waiting for you"
                           (short-ui-text (computer-session-message session) 30))))))
(defmethod service-output-added ((controller computer-controller) world output)
  (when (world-service world :computer-use) (%computer-create-panel world output) (%computer-refresh-ui world)))
(defmethod service-output-changed ((controller computer-controller) world output change)
  (declare (ignore output))
  (unless (eq :backend-damage (ataxia.kernel:object-change-kind change)) (%computer-refresh-ui world)))
