;;;; Window-local observations and input; desktop geometry is an explicit view.
(in-package #:ataxia.computer-use)

(defun %computer-window-view-p (session)
  (eq :window (computer-view-mode (computer-session-view session))))
(defun %computer-view-mode (name)
  (cond ((equal name "window") :window) ((equal name "desktop") :desktop)
        (t (%computer-reject "invalid-view" "Use window or desktop mode."))))
(defmethod ataxia.world:seat-raises-focused-window-p ((seat computer-seat))
  (not (%computer-window-view-p (%computer-seat-session seat))))
(defun %computer-window-on-output-p (session window)
  (world-window-visible-p (computer-session-world session) window
                          (computer-session-output session)))
(defun %computer-window-allowed-p (session window)
  (and (world-window-visible-p (computer-session-world session) window)
       (or (%computer-window-view-p session)
           (%computer-window-on-output-p session window))))
(defun %computer-root-bounds (window)
  (multiple-value-list (ataxia.kernel:drawable-local-bounds (window-application window))))
(defun %computer-input-capabilities (session window)
  (when (world-window-visible-p (computer-session-world session) window)
    (ataxia.computer-use::application-seat-input-capabilities
     (window-application window) (computer-session-seat session))))
(defun %computer-window-input-data (session window)
  (let ((capabilities (%computer-input-capabilities session window)))
    (list :keyboard (if (member :keyboard capabilities) t :false)
          :pointer (if (member :pointer capabilities) t :false))))
(defun %computer-require-input-ready (session window kind)
  (unless (member kind (%computer-input-capabilities session window))
    (%computer-reject "input-not-ready"
                      (format nil "The application has not bound this agent's ~A. Some clients require a new application process after connecting."
                              (string-downcase (symbol-name kind))))))
(defun %computer-window-bounds (window)
  (destructuring-bind (x y width height) (%computer-root-bounds window)
    (let ((left x) (top y) (right (+ x width)) (bottom (+ y height)))
      (loop for surface across (ataxia.kernel:drawable-surfaces (window-application window)) do
            (setf left (min left (ataxia.kernel:drawable-surface-local-x surface))
                  top (min top (ataxia.kernel:drawable-surface-local-y surface))
                  right (max right (+ (ataxia.kernel:drawable-surface-local-x surface) (ataxia.kernel:drawable-surface-width surface)))
                  bottom (max bottom (+ (ataxia.kernel:drawable-surface-local-y surface) (ataxia.kernel:drawable-surface-height surface)))))
      (let ((bounds (list (floor left) (floor top) (- (ceiling right) (floor left)) (- (ceiling bottom) (floor top)))))
        (unless (and (plusp (third bounds)) (plusp (fourth bounds)) (<= (* (third bounds) (fourth bounds)) 16777216))
          (%computer-reject "invalid-window-size" "Window is empty or too large for a bounded capture."))
        bounds))))
(defun %computer-set-basis (session bounds root-bounds &optional reset)
  (let* ((view (computer-session-view session)) (old (computer-view-bounds view)))
    (setf (computer-view-x view) (if (or reset (null old)) (/ (third bounds) 2d0)
                                     (max 0d0 (min (1- (third bounds)) (+ (computer-view-x view) (first old) (- (first bounds))))))
          (computer-view-y view) (if (or reset (null old)) (/ (fourth bounds) 2d0)
                                     (max 0d0 (min (1- (fourth bounds)) (+ (computer-view-y view) (second old) (- (second bounds))))))
          (computer-view-bounds view) bounds (computer-view-root-bounds view) root-bounds)))
(defun %computer-require-window (session &optional check-size)
  (let* ((view (computer-session-view session)) (window (computer-view-window view)))
    (unless (%computer-window-allowed-p session window)
      (%computer-reject "window-required" "Select an application with focus before using window view."))
    (when (and check-size (not (equalp (%computer-root-bounds window) (computer-view-root-bounds view))))
      (%computer-reject "window-resized" "The window resized. Capture it again before pointer input."))
    window))
(defun %computer-pointer-position (session)
  (if (%computer-window-view-p session)
      (let ((view (computer-session-view session))) (values (computer-view-x view) (computer-view-y view)))
      (let ((state (%computer-seat-state session))) (values (computer-input-state-x state) (computer-input-state-y state)))))
(defun %computer-coordinate-size (session)
  (if (%computer-window-view-p session)
      (progn (%computer-require-window session t)
             (let ((bounds (computer-view-bounds (computer-session-view session)))) (values (third bounds) (fourth bounds))))
      (output-logical-size (computer-session-output session))))
(defun %computer-local-position (session target)
  (if (%computer-window-view-p session)
      (let* ((view (computer-session-view session)) (bounds (computer-view-bounds view)))
        (values (+ (first bounds) (computer-view-x view)) (+ (second bounds) (computer-view-y view))))
      (let ((state (%computer-seat-state session)))
        (output-to-window-local (computer-session-world session) target (computer-session-output session)
                                (computer-input-state-x state) (computer-input-state-y state)))))
(defun %computer-sync-projection (session)
  ;; Only show an agent cursor where its application is actually visible.
  (when (%computer-window-view-p session)
    (let* ((view (computer-session-view session)) (window (computer-view-window view))
           (world (computer-session-world session)) (state (%computer-seat-state session))
           (output (computer-session-output session))
           (x -100000d0) (y -100000d0) (visible nil))
      (when (and state (%computer-window-allowed-p session window) (computer-view-bounds view))
        (multiple-value-bind (local-x local-y) (%computer-local-position session window)
          (multiple-value-bind (sx sy) (window-local-to-output world window output local-x local-y)
            (multiple-value-bind (width height) (output-logical-size output)
              (when (and (<= 0 sx) (< sx width) (<= 0 sy) (< sy height)
                         (eq window (world-target-at world output sx sy)))
                (setf x sx y sy visible t))))))
      (when (and state (or (/= x (computer-input-state-x state))
                           (/= y (computer-input-state-y state))
                           (not (eq visible (computer-view-visible-p view)))))
        (setf (computer-input-state-x state) x (computer-input-state-y state) y
              (computer-view-visible-p view) visible)
        (%computer-update-cursor session)))))
(defun change-session-view (session mode window-id)
  (let* ((view (computer-session-view session)) (world (computer-session-world session))
         (state (%computer-seat-state session))
         (window (if window-id (find window-id (world-windows world) :key (lambda (w) (ataxia.kernel:object-id (window-application w))))
                     (computer-view-window view))))
    (when (and (or (not (eq mode (computer-view-mode view)))
                   (and window-id (not (eq window (computer-view-window view)))))
               (or (computer-session-keys session) (plusp (hash-table-count (computer-input-state-buttons state)))))
      (%computer-reject "input-held" "Release held input before changing view."))
    ;; Validate against the requested view, before changing focus or held input.
    (when (and window-id
               (not (and (world-window-visible-p world window)
                         (or (eq mode :window) (%computer-window-on-output-p session window)))))
      (%computer-reject "target-blocked" "Window is unavailable in this view. Inspect the World's desktop state."))
    (when (not (eq mode (computer-view-mode view)))
      (%computer-release session)
      (setf (computer-view-mode view) mode)
      (when (eq mode :desktop)
        (multiple-value-bind (w h) (output-logical-size (computer-session-output session))
          (setf (computer-input-state-x state) (/ w 2d0) (computer-input-state-y state) (/ h 2d0)))))
    (when (and window (%computer-window-allowed-p session window)) (%computer-focus session window))
    (%computer-sync-projection session)
    (%computer-update-cursor session)
    (%computer-log session (if (eq mode :window) "Window view" "Desktop view"))))
