(in-package #:ataxia.infinite-world)

(defstruct canvas-gesture device kind fingers state owner axis anchor-x anchor-y
  (pending-dx 0d0) (pending-dy 0d0)
  (scale 1d0) (zoom 1d0) (time 0) (vx 0d0) (vy 0d0) (samples 0) (dx 0d0) (dy 0d0))
(defvar *canvas-gestures* (make-hash-table :test #'eq :weakness :key))
(defgeneric %canvas-gesture-owner (world seat))
(defmethod %canvas-gesture-owner ((world infinite-world) seat)
  (declare (ignore seat)) nil)
(defgeneric %canvas-owned-gesture (world seat gesture owner phase input))
(defmethod %canvas-owned-gesture ((world infinite-world) seat gesture owner phase input)
  (declare (ignore seat gesture owner phase input)) nil)
(defgeneric %canvas-gesture-allowed-p (world seat-state))
(defmethod %canvas-gesture-allowed-p ((world infinite-world) seat-state)
  (and (null (%canvas-seat-operation seat-state))
       (zerop (hash-table-count (%canvas-seat-buttons seat-state)))))

(defun %stop-gesture-motion (world state)
  (when state
    (ataxia.world:cancel-animation (%world-animator world) state :touchpad-pan)
    (ataxia.world:cancel-animation (%world-animator world) state :metaworld-camera)))

(defun %gesture-pan (world state dx dy)
  (multiple-value-bind (x y) (%screen-vector-to-canvas state dx dy)
    (pan-output-camera world (%canvas-output-output state)
                       (- (/ x (%canvas-output-zoom state))) (- (/ y (%canvas-output-zoom state))))))

(defun %gesture-coast (world gesture time)
  (let ((state (canvas-gesture-state gesture))
        (vx (canvas-gesture-vx gesture)) (vy (canvas-gesture-vy gesture))
        (previous 0d0))
    (when (and (>= (canvas-gesture-samples gesture) 2)
               (< (mod (- time (canvas-gesture-time gesture)) #x100000000) 70)
               (> (+ (abs vx) (abs vy)) 100d0))
      (ataxia.world:start-animation (%world-animator world) state :touchpad-pan (%now) .24d0
       (lambda (subject progress)
         (when (member subject (%output-states world))
           (let* (;; Integrated smoothstep velocity preserves release speed
                  ;; and settles with zero speed and acceleration.
                  (distance (* .24d0 (+ progress (- (expt progress 3))
                                        (* .5d0 (expt progress 4)))))
                  (delta (- distance previous)))
             (setf previous distance)
             (%gesture-pan world subject (* vx delta) (* vy delta))))))
      (%request-all-frames world))))

(defun %gesture-update (world gesture input)
  (let* ((state (canvas-gesture-state gesture))
         (dx (ataxia.kernel:cursor-gesture-input-dx input))
         (dy (ataxia.kernel:cursor-gesture-input-dy input))
         (time (ataxia.kernel:cursor-gesture-input-time-msec input)))
    (incf (canvas-gesture-dx gesture) dx)
    (incf (canvas-gesture-dy gesture) dy)
    (cond
      ((and (eq (canvas-gesture-kind gesture) :swipe) (= (canvas-gesture-fingers gesture) 3))
       (%gesture-pan world state dx dy)
       (incf (canvas-gesture-pending-dx gesture) dx)
       (incf (canvas-gesture-pending-dy gesture) dy)
       (let ((dt (/ (mod (- time (canvas-gesture-time gesture)) #x100000000) 1000d0)))
         (cond
           ((>= dt .1d0)
            (setf (canvas-gesture-vx gesture) 0d0 (canvas-gesture-vy gesture) 0d0
                  (canvas-gesture-samples gesture) 0))
           ((plusp dt)
            ;; Use elapsed time, not event count, to filter release velocity.
            (flet ((speed (old delta)
                     (+ old (* (- 1d0 (exp (- (/ dt .025d0))))
                               (- (max -2500d0 (min 2500d0 (/ delta dt))) old)))))
              (setf (canvas-gesture-vx gesture)
                    (speed (canvas-gesture-vx gesture) (canvas-gesture-pending-dx gesture))
                    (canvas-gesture-vy gesture)
                    (speed (canvas-gesture-vy gesture) (canvas-gesture-pending-dy gesture))))
            (incf (canvas-gesture-samples gesture))))
         ;; Coalesced events can share a millisecond timestamp. Carry their
         ;; distance into the next measurable interval instead of losing it.
         (when (plusp dt)
           (setf (canvas-gesture-pending-dx gesture) 0d0
                 (canvas-gesture-pending-dy gesture) 0d0))))
      ((eq (canvas-gesture-kind gesture) :pinch)
       (let ((scale (ataxia.kernel:cursor-gesture-input-scale input)))
         (when (and (realp scale) (< .001d0 scale 1000d0))
           (zoom-output-camera world (%canvas-output-output state) (/ (* scale (canvas-gesture-zoom gesture)) (%canvas-output-zoom state))
            :anchor-x (canvas-gesture-anchor-x gesture) :anchor-y (canvas-gesture-anchor-y gesture))
           (setf (canvas-gesture-scale gesture) scale)
           (%gesture-pan world state dx dy)
           (incf (canvas-gesture-anchor-x gesture) dx)
           (incf (canvas-gesture-anchor-y gesture) dy)))))
    (setf (canvas-gesture-time gesture) time)))

(defmethod ataxia.kernel:world-cursor-gesture ((world infinite-world) seat input)
  (let* ((seat-state (gethash seat (%world-seats world)))
         (state (and seat-state (%canvas-seat-output seat-state)))
         (kind (ataxia.kernel:cursor-gesture-input-kind input))
         (phase (ataxia.kernel:cursor-gesture-input-phase input))
         (device (ataxia.kernel:cursor-gesture-input-device input))
         (fingers (ataxia.kernel:cursor-gesture-input-fingers input))
         (time (ataxia.kernel:cursor-gesture-input-time-msec input))
         (gesture (and seat-state (gethash seat-state *canvas-gestures*))))
    (when state
      (cond
        ((eq phase :begin)
         (%cancel-seat-gesture world seat)
         (let ((owner (%canvas-gesture-owner world seat)))
           (when (and (%canvas-gesture-allowed-p world seat-state)
                      (or owner
                          (and (eq kind :swipe) (= fingers 3))
                          (and (eq kind :pinch) (= fingers 2))))
             (setf (gethash seat-state *canvas-gestures*)
                   (make-canvas-gesture
                    :device device :kind kind :fingers fingers :state state
                    :owner owner :time time :zoom (%canvas-output-zoom state)
                    :anchor-x (%canvas-seat-x seat-state) :anchor-y (%canvas-seat-y seat-state))))))
        ((and gesture (eq device (canvas-gesture-device gesture))
              (eq kind (canvas-gesture-kind gesture)))
         (let ((owner (canvas-gesture-owner gesture)))
           (cond
             ((or (and (null owner) (%canvas-gesture-owner world seat))
                  (not (eq state (canvas-gesture-state gesture)))
                  (not (%canvas-gesture-allowed-p world seat-state))
                  (and (eq phase :update) (/= fingers (canvas-gesture-fingers gesture))))
              (%cancel-seat-gesture world seat))
             ((eq phase :end)
              (remhash seat-state *canvas-gestures*)
              (unless (ataxia.kernel:cursor-gesture-input-cancelled-p input)
                (cond (owner (%canvas-owned-gesture world seat gesture owner :end input))
                      ((eq kind :swipe) (%gesture-coast world gesture time)))))
             ((eq phase :update)
              (if owner
                  (%canvas-owned-gesture world seat gesture owner :update input)
                  (%gesture-update world gesture input)))))))))
  input)

(defmethod ataxia.kernel:world-cursor-button :before ((world infinite-world) seat input)
  (declare (ignore input))
  (%cancel-seat-gesture world seat))
(defmethod ataxia.kernel:world-cursor-axis :before ((world infinite-world) seat input)
  (declare (ignore input))
  (%cancel-seat-gesture world seat))
(defmethod ataxia.kernel:world-output-removing :before ((world infinite-world) output)
  (let ((state (gethash output (%world-outputs world))))
    (%stop-gesture-motion world state)
    (dolist (seat (%seat-states world))
      (when (eq state (%canvas-seat-output seat)) (remhash seat *canvas-gestures*)))))
(defmethod ataxia.kernel:world-seat-removing :before ((world infinite-world) seat)
  (%cancel-seat-gesture world seat))
(defmethod ataxia.kernel:world-unregister-object :before ((world infinite-world) object reason)
  (declare (ignore reason))
  (when (typep object 'ataxia.kernel:kernel-input-device)
    (dolist (seat (%seat-states world))
      (%stop-gesture-motion world (%canvas-seat-output seat))))
  (dolist (seat (%seat-states world))
    (let ((gesture (gethash seat *canvas-gestures*)))
      (when (and gesture (eq object (canvas-gesture-device gesture)))
        (%stop-gesture-motion world (canvas-gesture-state gesture))
        (remhash seat *canvas-gestures*)))))

(defun %cancel-seat-gesture (world seat)
  (let ((state (gethash seat (%world-seats world))))
    (when state
      (remhash state *canvas-gestures*)
      (%stop-gesture-motion world (%canvas-seat-output state)))))
(defmethod ataxia.kernel:world-key-event :before ((world infinite-world) seat input)
  (when (or (typep input 'ataxia.kernel:modifiers-input)
            (and (typep input 'ataxia.kernel:key-input)
                 (eq :pressed (ataxia.kernel:key-input-state input))))
    (%cancel-seat-gesture world seat)))
(defmethod ataxia.kernel:world-quiescing :before ((world infinite-world) reason)
  (declare (ignore reason))
  (dolist (state (%seat-states world)) (%cancel-seat-gesture world (%canvas-seat-seat state))))
