;;;; Physical output placement is separate from the cameras on the shared canvas.
(in-package #:ataxia.infinite-world)

(defun %initialize-output-viewport (world state)
  (let ((others (remove state (%output-states world))))
    (when others
      (let ((rightmost (reduce (lambda (a b)
                                (if (> (+ (%canvas-output-layout-x a) (nth-value 0 (%output-logical-size a)))
                                       (+ (%canvas-output-layout-x b) (nth-value 0 (%output-logical-size b)))) a b)) others)))
        (setf (%canvas-output-layout-x state)
              (+ (%canvas-output-layout-x rightmost) (nth-value 0 (%output-logical-size rightmost)))
              (%canvas-output-camera-x state)
              (+ (%canvas-output-camera-x rightmost)
                 (/ (nth-value 0 (%output-logical-size rightmost)) (%canvas-output-zoom rightmost)))
              (%canvas-output-camera-y state) (%canvas-output-camera-y rightmost)
              (%canvas-output-zoom state) (%canvas-output-zoom rightmost)))))
  state)

(defgeneric set-output-position (world output x y))
(defmethod set-output-position ((world infinite-world) output x y)
  "Place an output in logical desktop coordinates without moving its camera."
  (check-type x (real -100000 100000)) (check-type y (real -100000 100000))
  (let ((state (or (gethash output (%world-outputs world)) (error "Unknown output."))))
    (setf (%canvas-output-layout-x state) (coerce x 'double-float)
          (%canvas-output-layout-y state) (coerce y 'double-float)))
  output)

(defun %route-seat-output (seat-state)
  (let* ((old (%canvas-seat-output seat-state)) (world (%canvas-seat-world seat-state))
         (states (if world (%output-states world) (list old)))
         (x (+ (%canvas-output-layout-x old) (%canvas-seat-x seat-state)))
         (y (+ (%canvas-output-layout-y old) (%canvas-seat-y seat-state)))
         (best nil) (best-distance most-positive-double-float) (bx 0d0) (by 0d0))
    (dolist (candidate states)
      (multiple-value-bind (width height) (%output-logical-size candidate)
        (let* ((cx (max 0d0 (min (- width .001d0) (- x (%canvas-output-layout-x candidate)))))
               (cy (max 0d0 (min (- height .001d0) (- y (%canvas-output-layout-y candidate)))))
               (distance (+ (expt (- x (+ (%canvas-output-layout-x candidate) cx)) 2)
                            (expt (- y (+ (%canvas-output-layout-y candidate) cy)) 2))))
          (when (< distance best-distance)
            (setf best candidate best-distance distance bx cx by cy)))))
    (when best
      (setf (%canvas-seat-output seat-state) best (%canvas-seat-x seat-state) bx (%canvas-seat-y seat-state) by)
      (when (and world (not (eq old best)))
        (%update-cursor-membership seat-state)
        (%request-output-state-frame world old)
        (%request-output-state-frame world best)))))
