;;;; Infinite canvas World package.

(defpackage #:ataxia.infinite-world
  (:use #:cl)
  (:import-from #:ataxia.world
   #:ui-host
   #:ui-overlay
   #:make-overlay
   #:overlay-component
   #:overlay-output
   #:overlay-x
   #:overlay-y
   #:overlay-width
   #:overlay-height
   #:overlay-layer
   #:overlay-visible-p
   #:overlay-opacity
   #:overlay-visibility-changed
   #:overlay-output-changed
   #:destroy-overlay
   #:overlay-input-enabled-p
   #:world-outputs
   #:world-overlays
   #:add-overlay
   #:remove-overlay
   #:show-overlay
   #:hide-overlay
   #:damage-overlay
   #:request-overlay-update
   #:monotonic-time
   #:output-logical-size
   #:require-world-output
   #:create-agent-widget
   #:agent-widget
   #:agent-widget-world
   #:agent-widget-id
   #:agent-widget-event
   #:agent-widget-event-sequence
   #:agent-widget-event-name
   #:agent-widget-event-value
   #:agent-widget-event-timestamp
   #:find-agent-widget
   #:list-agent-widgets
   #:remove-agent-widget
   #:configure-agent-widget
   #:set-agent-widget-property
   #:bind-agent-widget-event
   #:agent-widget-events
)
  (:import-from #:ataxia.world.slint #:make-agent-widget #:show-notification)
  (:export
   #:infinite-world
   #:make-infinite-world
   #:run-infinite-compositor
   #:main
   #:canvas-window
   #:canvas-window-application
   #:canvas-window-x
   #:canvas-window-y
   #:canvas-window-width
   #:canvas-window-height
   #:canvas-window-opacity
   #:canvas-window-scale
   #:canvas-window-elevation
   #:canvas-window-effect
   #:canvas-window-animation-hooks
   #:canvas-overlay
   #:make-canvas-overlay
   #:canvas-overlay-component
   #:canvas-overlay-output
   #:canvas-overlay-x
   #:canvas-overlay-y
   #:canvas-overlay-width
   #:canvas-overlay-height
   #:canvas-overlay-layer
   #:canvas-overlay-visible-p
   #:canvas-overlay-opacity
   #:agent-widget
   #:agent-widget-id
   #:agent-widget-event
   #:agent-widget-event-sequence
   #:agent-widget-event-name
   #:agent-widget-event-value
   #:agent-widget-event-timestamp
   #:world-overlays
   #:add-overlay
   #:remove-overlay
   #:show-overlay
   #:hide-overlay
   #:make-agent-widget
   #:find-agent-widget
   #:list-agent-widgets
   #:remove-agent-widget
   #:configure-agent-widget
   #:set-agent-widget-property
   #:bind-agent-widget-event
   #:agent-widget-events
   #:show-notification
   #:toggle-application-launcher
   #:find-canvas-window
   #:set-window-position
   #:set-window-animation-hook
   #:remove-window-animation-hook
   #:run-window-animation-hook
   #:animate-window
   #:set-output-camera
   #:set-output-position
   #:pan-output-camera
   #:zoom-output-camera))
