;;;; Compatibility for the published Infinite World overlay API.
(in-package #:ataxia.infinite-world)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (setf (find-class 'canvas-overlay) (find-class 'ui-overlay))
  (setf (fdefinition 'make-canvas-overlay) (fdefinition 'make-overlay))
  (setf (fdefinition 'canvas-overlay-component) (fdefinition 'overlay-component))
  (setf (fdefinition 'canvas-overlay-output) (fdefinition 'overlay-output))
  (setf (fdefinition '(setf canvas-overlay-output)) (fdefinition '(setf overlay-output)))
  (setf (fdefinition 'canvas-overlay-x) (fdefinition 'overlay-x))
  (setf (fdefinition '(setf canvas-overlay-x)) (fdefinition '(setf overlay-x)))
  (setf (fdefinition 'canvas-overlay-y) (fdefinition 'overlay-y))
  (setf (fdefinition '(setf canvas-overlay-y)) (fdefinition '(setf overlay-y)))
  (setf (fdefinition 'canvas-overlay-width) (fdefinition 'overlay-width))
  (setf (fdefinition '(setf canvas-overlay-width)) (fdefinition '(setf overlay-width)))
  (setf (fdefinition 'canvas-overlay-height) (fdefinition 'overlay-height))
  (setf (fdefinition '(setf canvas-overlay-height)) (fdefinition '(setf overlay-height)))
  (setf (fdefinition 'canvas-overlay-layer) (fdefinition 'overlay-layer))
  (setf (fdefinition '(setf canvas-overlay-layer)) (fdefinition '(setf overlay-layer)))
  (setf (fdefinition 'canvas-overlay-visible-p) (fdefinition 'overlay-visible-p))
  (setf (fdefinition '(setf canvas-overlay-visible-p)) (fdefinition '(setf overlay-visible-p)))
  (setf (fdefinition 'canvas-overlay-opacity) (fdefinition 'overlay-opacity))
  (setf (fdefinition '(setf canvas-overlay-opacity)) (fdefinition '(setf overlay-opacity))))
