;;;; Kernel package boundary.
;;;;
;;;; ATAXIA.KERNEL exports stable compositor objects, the contracts a World
;;;; implements, and the narrow mechanisms a World may invoke. wlroots objects
;;;; remain owned by ATAXIA.RUNTIME.

(defpackage #:ataxia.kernel
  (:use #:cl)
  (:export
   ;; Shared object protocols.
   #:drawable
   #:interactable
   #:render-source
   #:render-source-width
   #:render-source-height
   #:render-source-gles-target
   #:render-source-gles-name
   #:render-source-has-alpha-p
   #:render-source-generation
   #:drawable-surface
   #:drawable-surface-local-x
   #:drawable-surface-local-y
   #:drawable-surface-width
   #:drawable-surface-height
   #:drawable-surface-texture-coordinates
   #:drawable-surface-render-source
   #:drawable-surface-presentation-token
   #:drawable-surfaces
   #:drawable-local-bounds
   #:drawable-attach-graphics
   #:drawable-detach-graphics
   #:drawable-prepare-frame
   #:drawable-active-p
   #:retain-render-source
   #:release-render-source
   #:interaction-result
   #:make-interaction-result
   #:interaction-result-status
   #:interaction-result-object
   #:interaction-result-focus-changed-p
   #:interaction-result-capture-changed-p
   #:object-change
   #:make-object-change
   #:object-change-kind
   #:object-change-value
   #:drawable-invalidation
   #:make-drawable-invalidation
   #:drawable-invalidation-revision
   #:drawable-invalidation-damage
   #:toplevel-configuration
   #:configuration-width
   #:configuration-height
   #:configuration-activated
   #:configuration-resizing
   #:configuration-tiled-edges
   #:configuration-bounds-width
   #:configuration-bounds-height
   #:cursor-motion-input
   #:make-cursor-motion-input
   #:cursor-motion-input-device
   #:cursor-motion-input-time-msec
   #:cursor-motion-input-absolute-p
   #:cursor-motion-input-delta-x
   #:cursor-motion-input-delta-y
   #:cursor-motion-input-unaccelerated-delta-x
   #:cursor-motion-input-unaccelerated-delta-y
   #:cursor-motion-input-x
   #:cursor-motion-input-y
   #:cursor-button-input
   #:make-cursor-button-input
   #:cursor-button-input-device
   #:cursor-button-input-time-msec
   #:cursor-button-input-code
   #:cursor-button-input-state
   #:cursor-axis-input
   #:make-cursor-axis-input
   #:cursor-axis-input-device
   #:cursor-axis-input-time-msec
   #:cursor-axis-input-source
   #:cursor-axis-input-orientation
   #:cursor-axis-input-relative-direction
   #:cursor-axis-input-delta
   #:cursor-axis-input-discrete-delta
   #:key-input
   #:make-key-input
   #:key-input-device
   #:key-input-time-msec
   #:key-input-keycode
   #:key-input-keysyms
   #:key-input-modifiers
   #:key-input-state
   #:key-input-update-state-p
   #:modifiers-input
   #:make-modifiers-input
   #:modifiers-input-device
   #:modifiers-input-depressed
   #:modifiers-input-latched
   #:modifiers-input-locked
   #:modifiers-input-group
   #:modifiers-input-names
   #:interactable-pointer-motion
   #:interactable-hit-test
   #:interactable-pointer-button
   #:interactable-pointer-axis
   #:interactable-pointer-leave
   #:interactable-key-event
   #:interactable-focus
   #:request-object-configuration
   #:request-object-state

   ;; Kernel-owned stable objects.
   #:kernel-object
   #:object-kernel
   #:object-id
   #:object-generation
   #:object-state
   #:kernel-output
   #:output-runtime-object
   #:output-name
   #:output-description
   #:output-width
   #:output-height
   #:output-scale
   #:output-transform
   #:output-enabled-p
   #:kernel-input-device
   #:input-runtime-object
   #:input-name
   #:input-type
   #:input-seat
   #:logical-seat
   #:seat-runtime-object
   #:seat-name
   #:seat-capabilities
   #:seat-input-devices
   #:surface-node
   #:surface-runtime-object
   #:surface-parent
   #:surface-children
   #:surface-local-x
   #:surface-local-y
   #:surface-width
   #:surface-height
   #:surface-mapped-p
   #:surface-commit-sequence
   #:wayland-application
   #:application-toplevel
   #:application-root-surface
   #:application-title
   #:application-app-id
   #:application-mapped-p
   #:client-request
   #:client-request-seat
   #:client-request-serial
   #:move-client-request
   #:resize-client-request
   #:resize-client-request-edges
   #:state-client-request
   #:state-client-request-name
   #:state-client-request-value
   #:fullscreen-client-request
   #:fullscreen-client-request-output
   #:window-menu-client-request
   #:window-menu-client-request-x
   #:window-menu-client-request-y
   #:cursor-surface-request
   #:cursor-surface-request-seat
   #:cursor-surface-request-surface
   #:cursor-surface-request-serial
   #:cursor-surface-request-hotspot-x
   #:cursor-surface-request-hotspot-y

   ;; Kernel/World contract.
   #:world
   #:world-attached
   #:world-kernel
   #:world-quiescing
   #:world-detached
   #:world-register-object
   #:world-unregister-object
   #:world-object-changed
   #:world-object-invalidated
   #:world-output-added
   #:world-output-changed
   #:world-output-removing
   #:world-output-presented
   #:world-seat-added
   #:world-seat-removing
   #:world-cursor-motion
   #:world-cursor-button
   #:world-cursor-axis
   #:world-key-event
   #:world-seat-cursor-request
   #:world-client-request
   #:world-graphics-attached
   #:world-render
   #:world-frame-committed
   #:world-frame-failed
   #:world-graphics-detaching

   ;; Frame boundary.
   #:frame-lease
   #:frame-damage-rectangle
   #:make-frame-damage-rectangle
   #:frame-damage-rectangle-x
   #:frame-damage-rectangle-y
   #:frame-damage-rectangle-width
   #:frame-damage-rectangle-height
   #:frame-output
   #:frame-target-token
   #:frame-framebuffer
   #:frame-width
   #:frame-height
   #:frame-scale
   #:frame-transform
   #:frame-timestamp
   #:frame-generation
   #:frame-lease-valid-p
   #:world-frame-result
   #:frame-result-target-token
   #:frame-result-damage
   #:frame-result-presentation-tokens
   #:frame-result-complete-p
   #:frame-result-world-cookie
   #:output-presentation
   #:output-presentation-commit-sequence
   #:output-presentation-presented-p
   #:output-presentation-seconds
   #:output-presentation-nanoseconds
   #:output-presentation-sequence
   #:output-presentation-refresh-nanoseconds
   #:output-presentation-flags

   ;; Kernel aggregate and mechanisms.
   #:kernel
   #:make-kernel
   #:create-kernel
   #:start-kernel
   #:run-kernel
   #:request-kernel-stop
   #:destroy-kernel
   #:kernel-runtime
   #:kernel-world
   #:kernel-world-status
   #:kernel-world-generation
   #:kernel-world-last-fault
   #:kernel-world-timeout
   #:kernel-state
   #:kernel-outputs
   #:kernel-input-devices
   #:kernel-seats
   #:kernel-applications
   #:find-kernel-object
   #:attach-runtime
   #:detach-runtime
   #:install-world
   #:restart-world
   #:create-logical-seat
   #:destroy-logical-seat
   #:assign-input-device
   #:clear-wayland-focus
   #:request-output-frame
   #:set-wayland-surface-output-membership))
