;;;; X11 application/surface translation. Native transport belongs to Runtime.
(in-package #:ataxia.kernel)
(eval-when (:compile-toplevel :load-toplevel :execute)
  (export '(enable-xwayland disable-xwayland xwayland-display-name xwayland-application)))

(defclass xwayland-server ()
  ((runtime-object :initarg :runtime-object :reader %xserver-runtime)
   (surfaces :initform (make-hash-table :test #'eq) :reader %xserver-surfaces)
   (focused :initform nil :accessor %xserver-focused)))
(defclass xwayland-surface ()
  ((runtime-object :initarg :runtime-object :reader %xsurface-runtime)
   (server :initarg :server :reader %xsurface-server)
   (node :initform nil :accessor %xsurface-node)
   (application :initform nil :accessor %xsurface-application)))
(defclass xwayland-application (wayland-application) ()
  (:documentation
   "X11 protocol adapter for the shared drawable/interactable application contract.
World receives ordinary application objects, drawable records and client requests;
XWM coordinates and native surface selection remain private to this adapter."))
(defvar *xwayland-servers* (make-hash-table :test #'eq))

(defun xwayland-display-name (kernel)
  (let ((server (gethash kernel *xwayland-servers*)))
    (when server (ataxia.runtime:xwayland-display-name (%xserver-runtime server)))))

(defun %x-binding (kernel runtime-surface)
  (let ((server (gethash kernel *xwayland-servers*)))
    (and server (gethash runtime-surface (%xserver-surfaces server)))))

(defun %x-application (surface)
  (and surface
       (or (%xsurface-application surface)
           (let ((node (%xsurface-node surface))) (and node (%surface-tree-application node))))))

(defun %x-position-popup (surface)
  (let* ((node (%xsurface-node surface))
         (application (and node (%surface-tree-application node))))
    (when (and node (surface-parent node) application)
      (let ((child (%xsurface-runtime surface)) (parent (application-toplevel application)))
        (setf (surface-local-x node) (- (ataxia.runtime:xwayland-surface-x child) (ataxia.runtime:xwayland-surface-x parent))
              (surface-local-y node) (- (ataxia.runtime:xwayland-surface-y child) (ataxia.runtime:xwayland-surface-y parent))))
      (%invalidate-application application))))

(defun %x-dissociate (surface)
  (when (%xsurface-application surface)
    (when (eq (%xsurface-application surface) (%xserver-focused (%xsurface-server surface)))
      (setf (%xserver-focused (%xsurface-server surface)) nil))
    (%retire-wayland-application (%xsurface-application surface) :unmapped)
    (setf (%xsurface-application surface) nil))
  (when (%xsurface-node surface)
    (let* ((node (%xsurface-node surface)) (parent (%surface-tree-application node)))
      (%detach-surface-node node)
      (when (and parent (eq (object-state parent) :live)) (%invalidate-application parent)))
    (setf (%xsurface-node surface) nil)))

(defun %x-expose-application (kernel surface root)
  (let* ((runtime-surface (%xsurface-runtime surface))
         (application (make-instance 'xwayland-application
                        :kernel kernel :id (%allocate-object-id kernel) :toplevel runtime-surface
                        :root-surface root :title (ataxia.runtime:xwayland-surface-title runtime-surface)
                        :app-id (ataxia.runtime:xwayland-surface-class runtime-surface) :mapped-p (surface-mapped-p root))))
    (setf (%xsurface-application surface) application (%surface-application root) application
          (gethash runtime-surface (%kernel-toplevel-table kernel)) application)
    (%register-object kernel application :runtime-object runtime-surface)
    (%call-world kernel world-register-object application)
    application))

(defun %x-associate (kernel surface)
  (%x-dissociate surface)
  (let* ((native (%xsurface-runtime surface))
         (root (%ensure-surface-node kernel (ataxia.runtime:xwayland-surface-surface native)))
         (server (%xsurface-server surface))
         (parent (gethash (ataxia.runtime:xwayland-surface-parent native) (%xserver-surfaces server)))
         (parent-app
           (or (%x-application parent) (%xserver-focused server)
               ;; Some override-redirect menus omit WM_TRANSIENT_FOR and may
               ;; appear before a headless seat has activated their parent.
               (loop for candidate being the hash-values of (%xserver-surfaces server)
                     for app = (%xsurface-application candidate)
                     for other = (%xsurface-runtime candidate)
                     when (and app (application-mapped-p app) (not (ataxia.runtime:xwayland-surface-override-redirect-p other))
                               (<= (ataxia.runtime:xwayland-surface-x other) (ataxia.runtime:xwayland-surface-x native)
                                   (+ (ataxia.runtime:xwayland-surface-x other) (ataxia.runtime:xwayland-surface-width other)))
                               (<= (ataxia.runtime:xwayland-surface-y other) (ataxia.runtime:xwayland-surface-y native)
                                   (+ (ataxia.runtime:xwayland-surface-y other) (ataxia.runtime:xwayland-surface-height other))))
                       return app))))
    (setf (%xsurface-node surface) root)
    (when (and (ataxia.runtime:xwayland-surface-override-redirect-p native) parent-app
               (eq :live (object-state parent-app)))
      (%attach-surface-child (application-root-surface parent-app) root 0 0)
      (%x-position-popup surface))
    (ataxia.runtime:xwayland-surface-consider-map native)
    (when (and (surface-mapped-p root) (not (%surface-tree-application root)))
      (%x-expose-application kernel surface root))))

(defun %x-request-state (kernel surface name value)
  (let ((application (%xsurface-application surface)))
    (when application
      (%call-world kernel world-client-request application
                   (make-instance (if (eq name :fullscreen) 'fullscreen-client-request 'state-client-request)
                                  :name name :value value)))))

(defun %x-metadata (kernel runtime-surface kind value)
  (let ((application (%xsurface-application (%x-binding kernel runtime-surface))))
    (when application
      (ecase kind
        (:title (setf (application-title application) value))
        (:app-id (setf (application-app-id application) value)))
      (%call-world kernel world-object-changed application (make-object-change kind value)))))

(defun %x-gesture (kernel runtime-surface kind &optional edges)
  ;; X11 has no Wayland serial. Only a seat already pressing this application
  ;; may request a move/resize gesture; World decides what that request means.
  (let ((application (%xsurface-application (%x-binding kernel runtime-surface))))
    (when application
      (dolist (seat (kernel-seats kernel))
        (when (eq application (getf (%seat-implicit-pointer-grab seat) :application))
          (%call-world kernel world-client-request application
                       (if edges (make-instance kind :seat seat :edges edges)
                           (make-instance kind :seat seat))))))))

(defmethod ataxia.runtime:xwayland-new-surface ((kernel kernel) runtime-server runtime-surface)
  (let ((server (gethash kernel *xwayland-servers*)))
    (assert (eq runtime-server (%xserver-runtime server)))
    (setf (gethash runtime-surface (%xserver-surfaces server))
          (make-instance 'xwayland-surface :runtime-object runtime-surface :server server))))
(defmethod ataxia.runtime:xwayland-surface-associated ((kernel kernel) surface)
  (%x-associate kernel (%x-binding kernel surface)))
(defmethod ataxia.runtime:xwayland-surface-dissociated ((kernel kernel) surface)
  (%x-dissociate (%x-binding kernel surface)))
(defmethod ataxia.runtime:xwayland-surface-destroying ((kernel kernel) surface)
  (let ((binding (%x-binding kernel surface)))
    (when binding
      (%x-dissociate binding)
      (remhash surface (%xserver-surfaces (%xsurface-server binding))))))
(defmethod ataxia.runtime:xwayland-surface-title-changed ((kernel kernel) surface)
  (%x-metadata kernel surface :title (ataxia.runtime:xwayland-surface-title surface)))
(defmethod ataxia.runtime:xwayland-surface-class-changed ((kernel kernel) surface)
  (%x-metadata kernel surface :app-id (ataxia.runtime:xwayland-surface-class surface)))
(defmethod ataxia.runtime:xwayland-surface-geometry-changed ((kernel kernel) surface)
  (%x-position-popup (%x-binding kernel surface)))
(defmethod ataxia.runtime:xwayland-surface-request-configure ((kernel kernel) surface request)
  ;; Mapped managed clients keep their World-assigned size. X11 coordinates
  ;; never encode the unbounded canvas. Copy protocol requests only when unmapped.
  (let* ((application (%xsurface-application (%x-binding kernel surface)))
         (managed (and application (application-mapped-p application)))
         (mask (ataxia.runtime:xwayland-configure-mask request)))
    (flet ((value (requested current bit) (if (and (not managed) (logtest bit mask)) requested current)))
      (ataxia.runtime:xwayland-surface-configure
       surface
       (value (ataxia.runtime:xwayland-configure-x request) (ataxia.runtime:xwayland-surface-x surface) 1)
       (value (ataxia.runtime:xwayland-configure-y request) (ataxia.runtime:xwayland-surface-y surface) 2)
       (max 1 (value (ataxia.runtime:xwayland-configure-width request) (ataxia.runtime:xwayland-surface-width surface) 4))
       (max 1 (value (ataxia.runtime:xwayland-configure-height request) (ataxia.runtime:xwayland-surface-height surface) 8))))))
(defmethod ataxia.runtime:xwayland-surface-request-fullscreen ((kernel kernel) surface value)
  (%x-request-state kernel (%x-binding kernel surface) :fullscreen value))
(defmethod ataxia.runtime:xwayland-surface-request-maximize ((kernel kernel) surface value)
  (%x-request-state kernel (%x-binding kernel surface) :maximized value))
(defmethod ataxia.runtime:xwayland-surface-request-minimize ((kernel kernel) surface value)
  (%x-request-state kernel (%x-binding kernel surface) :minimized value))
(defmethod ataxia.runtime:xwayland-surface-request-move ((kernel kernel) surface)
  (%x-gesture kernel surface 'move-client-request))
(defmethod ataxia.runtime:xwayland-surface-request-resize ((kernel kernel) surface edges)
  (%x-gesture kernel surface 'resize-client-request edges))
(defmethod ataxia.runtime:xwayland-surface-request-activate ((kernel kernel) surface)
  (%x-request-state kernel (%x-binding kernel surface) :activation t))

(defun %x-set-seat (kernel server)
  (let ((seat (first (kernel-seats kernel))))
    (when seat (ataxia.runtime:xwayland-set-seat server (seat-runtime-object seat)))))
(defmethod ataxia.runtime:xwayland-ready ((kernel kernel) server)
  (%x-set-seat kernel server))
(defmethod ataxia.runtime:xwayland-destroying ((kernel kernel) server)
  (let ((binding (gethash kernel *xwayland-servers*)))
    (when (and binding (eq server (%xserver-runtime binding))) (remhash kernel *xwayland-servers*))))
(defun enable-xwayland (kernel &key (lazy t))
  (or (gethash kernel *xwayland-servers*)
      (let* ((native (ataxia.runtime:create-xwayland (kernel-runtime kernel) :lazy lazy))
             (server (make-instance 'xwayland-server :runtime-object native)))
        (setf (gethash kernel *xwayland-servers*) server)
        (%x-set-seat kernel native)
        server)))
(defun disable-xwayland (kernel)
  (let ((server (gethash kernel *xwayland-servers*)))
    (when server (ataxia.runtime:destroy-xwayland (%xserver-runtime server)))))

(defmethod ataxia.runtime:surface-mapped :after ((kernel kernel) runtime-surface)
  (let* ((node (gethash runtime-surface (%kernel-surface-table kernel)))
         (app (and node (%surface-tree-application node))))
    (unless app
      (let* ((server (gethash kernel *xwayland-servers*))
             (surface (and node server (loop for candidate being the hash-values of (%xserver-surfaces server)
                                        when (eq node (%xsurface-node candidate)) return candidate))))
        (when surface (setf app (%x-expose-application kernel surface node)))))
    (when (and (typep app 'xwayland-application) (eq node (application-root-surface app)))
      (setf (application-mapped-p app) t)
      (%call-world kernel world-object-changed app (make-object-change :mapped t))
      (%invalidate-application app))))
(defmethod ataxia.runtime:surface-unmapped :after ((kernel kernel) runtime-surface)
  (let* ((node (gethash runtime-surface (%kernel-surface-table kernel)))
         (app (and node (%surface-tree-application node))))
    (when (and (typep app 'xwayland-application) (eq node (application-root-surface app)))
      (setf (application-mapped-p app) nil)
      (%call-world kernel world-object-changed app (make-object-change :mapped nil)))))
(defmethod drawable-local-bounds ((application xwayland-application))
  (let ((root (application-root-surface application))) (values 0 0 (surface-width root) (surface-height root))))
(defmethod %application-surface-at ((application xwayland-application) x y)
  (let ((nodes nil))
    (%walk-surface-tree (application-root-surface application)
                       (lambda (node dx dy) (push (list node dx dy) nodes)))
    (dolist (entry nodes)
      (destructuring-bind (node dx dy) entry
        (when (surface-mapped-p node)
          (multiple-value-bind (hit sx sy)
              (ataxia.runtime:surface-at (surface-runtime-object node) (- x dx) (- y dy))
            (when hit (return-from %application-surface-at (values hit sx sy)))))))))
(defmethod request-object-configuration ((application xwayland-application) world (configuration toplevel-configuration))
  (let* ((surface (application-toplevel application))
         (width (configuration-width configuration)) (height (configuration-height configuration)))
    (unless (and (eq width :unchanged) (eq height :unchanged))
      (ataxia.runtime:xwayland-surface-configure
       surface (ataxia.runtime:xwayland-surface-x surface) (ataxia.runtime:xwayland-surface-y surface)
       (max 1 (min 65535 (if (eq width :unchanged) (ataxia.runtime:xwayland-surface-width surface) width)))
       (max 1 (min 65535 (if (eq height :unchanged) (ataxia.runtime:xwayland-surface-height surface) height)))))
    (%apply-configuration-field (configuration-activated configuration)
                               (lambda (value) (request-object-state application world :activated value))))
  application)
(defmethod request-object-state ((application xwayland-application) world state value)
  (declare (ignore world))
  (let ((surface (application-toplevel application)))
    (ecase state
      (:activated
       (let ((server (%xsurface-server (%x-binding (object-kernel application) surface))))
         (cond (value (setf (%xserver-focused server) application))
               ((eq application (%xserver-focused server))
                (setf (%xserver-focused server) nil))))
       (ataxia.runtime:xwayland-surface-activate surface value))
      (:fullscreen (ataxia.runtime:xwayland-surface-set-fullscreen surface value))
      (:maximized (ataxia.runtime:xwayland-surface-set-maximized surface value))
      (:minimized (ataxia.runtime:xwayland-surface-set-minimized surface value))
      ;; These are advisory XDG hints without X11 equivalents. In particular,
      ;; suspending offscreen content must not iconify or unmap the window.
      ((:suspended :resizing :constrained) nil)
      (:close (ataxia.runtime:xwayland-surface-close surface))))
  application)
