;;;; Optional XWayland transport. Camera, layout, and focus policy remain in World.
(in-package #:ataxia.kernel)
(eval-when (:compile-toplevel :load-toplevel :execute)
  (export '(enable-xwayland disable-xwayland xwayland-display-name xwayland-application)))
(cffi:defcfun ("wlr_xwayland_create" %xwayland-create) :pointer (display :pointer) (compositor :pointer) (lazy :bool))
(cffi:defcfun ("wlr_xwayland_destroy" %xwayland-destroy) :void (server :pointer))
(cffi:defcfun ("wlr_xwayland_set_seat" %xwayland-set-seat) :void (server :pointer) (seat :pointer))
(cffi:defcfun ("ataxia_xwayland_signal" %xwayland-signal) :pointer (server :pointer) (event :int))
(cffi:defcfun ("ataxia_xwayland_display" %xwayland-display) :string (server :pointer))
(cffi:defcfun ("ataxia_xsurface_signal" %xsurface-signal) :pointer (surface :pointer) (event :int))
(cffi:defcfun ("ataxia_xsurface_surface" %xsurface-surface) :pointer (surface :pointer))
(cffi:defcfun ("ataxia_xsurface_consider_map" %xsurface-consider-map) :void (surface :pointer))
(cffi:defcfun ("ataxia_xsurface_parent" %xsurface-parent) :pointer (surface :pointer))
(cffi:defcfun ("ataxia_xsurface_text" %xsurface-text) :string (surface :pointer) (field :int))
(cffi:defcfun ("ataxia_xsurface_value" %xsurface-value) :int (surface :pointer) (field :int))
(cffi:defcfun ("ataxia_xconfigure_value" %xconfigure-value) :int (event :pointer) (field :int))
(cffi:defcfun ("ataxia_xminimize_value" %xminimize-value) :bool (event :pointer))
(cffi:defcfun ("ataxia_xresize_edges" %xresize-edges) :uint32 (event :pointer))
(cffi:defcfun ("wlr_xwayland_surface_configure" %xsurface-configure) :void (surface :pointer) (x :int16) (y :int16) (width :uint16) (height :uint16))
(cffi:defcfun ("wlr_xwayland_surface_activate" %xsurface-activate) :void (surface :pointer) (active :bool))
(cffi:defcfun ("wlr_xwayland_surface_close" %xsurface-close) :void (surface :pointer))
(cffi:defcfun ("wlr_xwayland_surface_set_fullscreen" %xsurface-fullscreen) :void (surface :pointer) (value :bool))
(cffi:defcfun ("wlr_xwayland_surface_set_maximized" %xsurface-maximized) :void (surface :pointer) (horizontal :bool) (vertical :bool))
(cffi:defcfun ("wlr_xwayland_surface_set_minimized" %xsurface-minimized) :void (surface :pointer) (value :bool))
(cffi:defcfun ("wlr_surface_surface_at" %xsurface-at) :pointer (surface :pointer) (x :double) (y :double) (sx :pointer) (sy :pointer))

(defclass xwayland-server (ataxia.runtime::native-object)
  ((surfaces :initform (make-hash-table) :reader %xserver-surfaces)
   (focused :initform nil :accessor %xserver-focused)))
(defclass xwayland-surface (ataxia.runtime::native-object)
  ((server :initarg :server :reader %xsurface-server)
   (node :initform nil :accessor %xsurface-node)
   (application :initform nil :accessor %xsurface-application)))
(defclass xwayland-application (wayland-application) ())
(defvar *xwayland-servers* (make-hash-table :test #'eq))

(defun xwayland-display-name (kernel)
  (let ((server (gethash kernel *xwayland-servers*)))
    (when server (%xwayland-display (ataxia.runtime::%object-pointer server)))))

(defun %x-application (surface)
  (or (%xsurface-application surface)
      (let ((node (%xsurface-node surface))) (and node (%surface-tree-application node)))))

(defun %x-position-popup (surface)
  (let* ((node (%xsurface-node surface))
         (application (and node (%surface-tree-application node))))
    (when (and node (surface-parent node) application)
      (let ((pointer (ataxia.runtime::%object-pointer surface))
            (parent (ataxia.runtime::%object-pointer (application-toplevel application))))
        (setf (surface-local-x node) (- (%xsurface-value pointer 0) (%xsurface-value parent 0))
              (surface-local-y node) (- (%xsurface-value pointer 1) (%xsurface-value parent 1)))
        (%invalidate-application application)))))

(defun %x-dissociate (surface)
  (when (%xsurface-application surface)
    (when (eq (%xsurface-application surface) (%xserver-focused (%xsurface-server surface)))
      (setf (%xserver-focused (%xsurface-server surface)) nil))
    (%retire-wayland-application (%xsurface-application surface) :unmapped)
    (setf (%xsurface-application surface) nil))
  (when (%xsurface-node surface)
    (let* ((node (%xsurface-node surface)) (parent (%surface-tree-application node)))
      (%detach-surface-node node)
      (when (and parent (eq :live (object-state parent))) (%invalidate-application parent)))
    (setf (%xsurface-node surface) nil)))

(defun %x-expose-application (kernel surface root)
  (let* ((pointer (ataxia.runtime::%object-pointer surface))
         (application (make-instance 'xwayland-application
                        :kernel kernel :id (%allocate-object-id kernel) :toplevel surface
                        :root-surface root :title (%xsurface-text pointer 0)
                        :app-id (%xsurface-text pointer 1) :mapped-p (surface-mapped-p root))))
    (setf (%xsurface-application surface) application (%surface-application root) application
          (gethash surface (%kernel-toplevel-table kernel)) application)
    (%register-object kernel application :runtime-object surface)
    (%call-world kernel world-register-object application)
    application))

(defun %x-associate (kernel surface)
  (%x-dissociate surface)
  (let* ((runtime (kernel-runtime kernel))
         (pointer (ataxia.runtime::%object-pointer surface))
         (native (%xsurface-surface pointer))
         (root (%ensure-surface-node kernel (ataxia.runtime::%adopt-core-surface runtime native)))
         (server (%xsurface-server surface))
         (parent (gethash (cffi:pointer-address (%xsurface-parent pointer)) (%xserver-surfaces server)))
         (parent-app
           (or (and parent (%x-application parent)) (%xserver-focused server)
               ;; Some override-redirect menus omit WM_TRANSIENT_FOR and may
               ;; appear before a headless seat has activated their parent.
               (loop for candidate being the hash-values of (%xserver-surfaces server)
                     for app = (%xsurface-application candidate)
                     for p = (ataxia.runtime::%object-pointer candidate)
                     when (and app (application-mapped-p app) (zerop (%xsurface-value p 4))
                               (<= (%xsurface-value p 0) (%xsurface-value pointer 0)
                                   (+ (%xsurface-value p 0) (%xsurface-value p 2)))
                               (<= (%xsurface-value p 1) (%xsurface-value pointer 1)
                                   (+ (%xsurface-value p 1) (%xsurface-value p 3))))
                       return app))))
    (setf (%xsurface-node surface) root)
    (when (and (not (zerop (%xsurface-value pointer 4))) parent-app
               (eq :live (object-state parent-app)))
      (%attach-surface-child (application-root-surface parent-app) root 0 0)
      (%x-position-popup surface))
    ;; Internal X11 windows may associate without ever committing content.
    ;; Publish an application only when its root actually maps.
    (%xsurface-consider-map pointer)
    (when (and (surface-mapped-p root) (not (%surface-tree-application root)))
      (%x-expose-application kernel surface root))))

(defun %x-request-state (kernel surface name value)
  (let ((application (%xsurface-application surface)))
    (when application
      (%call-world kernel world-client-request application
                   (make-instance (if (eq name :fullscreen) 'fullscreen-client-request 'state-client-request)
                                  :name name :value value)))))

(defun %x-new-surface (kernel server pointer)
  (let* ((runtime (kernel-runtime kernel))
         (surface (make-instance 'xwayland-surface :pointer pointer :runtime runtime :server server))
         (key (cffi:pointer-address pointer)))
    (setf (gethash key (%xserver-surfaces server)) surface)
    (labels ((subscribe (event function)
               (ataxia.runtime::%attach-object-signal surface :xwayland-surface
                 (%xsurface-signal pointer event) function))
             (metadata (field)
               (let ((application (%xsurface-application surface)))
                 (when application
                   (let ((value (%xsurface-text pointer field)))
                     (if (zerop field) (setf (application-title application) value)
                         (setf (application-app-id application) value))
                     (%call-world kernel world-object-changed application
                                  (make-object-change (if (zerop field) :title :app-id) value)))))))
      (subscribe 0 (lambda (data) (declare (ignore data)) (%x-associate kernel surface)))
      (subscribe 1 (lambda (data) (declare (ignore data)) (%x-dissociate surface)))
      (subscribe 2 (lambda (data)
                  (declare (ignore data))
                  (%x-dissociate surface)
                  (ataxia.runtime::%retire-object-listeners surface :immediate-p t)
                  (ataxia.runtime::%invalidate-native-object surface)
                  (remhash key (%xserver-surfaces server))))
      (subscribe 3 (lambda (event)
                  ;; Mapped managed clients keep their World-assigned size.
                  ;; X11 coordinates never encode the unbounded canvas.
                  (let* ((application (%xsurface-application surface))
                         (managed (and application (application-mapped-p application)))
                         (mask (%xconfigure-value event 4)))
                    (flet ((value (field bit)
                             (if (and (not managed) (logtest bit mask))
                                 (%xconfigure-value event field) (%xsurface-value pointer field))))
                      (%xsurface-configure pointer (value 0 1) (value 1 2)
                                           (max 1 (value 2 4)) (max 1 (value 3 8)))))))
      (subscribe 4 (lambda (data) (declare (ignore data)) (metadata 0)))
      (subscribe 5 (lambda (data) (declare (ignore data)) (metadata 1)))
      (subscribe 6 (lambda (data) (declare (ignore data)) (%x-position-popup surface)))
      (subscribe 7 (lambda (data) (declare (ignore data)) (%x-request-state kernel surface :fullscreen (not (zerop (%xsurface-value pointer 5))))))
      (subscribe 8 (lambda (data) (declare (ignore data)) (%x-request-state kernel surface :maximized (not (zerop (%xsurface-value pointer 6))))))
      (subscribe 9 (lambda (data) (%x-request-state kernel surface :minimized (%xminimize-value data))))
      ;; X11 has no Wayland input serial. Only a seat already pressing this
      ;; application may request a move/resize gesture.
      (flet ((gesture (kind &optional edges)
               (let ((application (%xsurface-application surface)))
                 (when application
                   (dolist (seat (kernel-seats kernel))
                     (when (eq application (getf (%seat-implicit-pointer-grab seat) :application))
                       (%call-world kernel world-client-request application
                                    (if edges (make-instance kind :seat seat :edges edges)
                                        (make-instance kind :seat seat)))))))))
        (subscribe 10 (lambda (data) (declare (ignore data)) (gesture 'move-client-request)))
        (subscribe 11 (lambda (data) (gesture 'resize-client-request (%xresize-edges data)))))
      (subscribe 12 (lambda (data) (declare (ignore data)) (%x-request-state kernel surface :activation t))))
    surface))

(defun enable-xwayland (kernel &key (lazy t))
  (or (gethash kernel *xwayland-servers*)
      (let* ((runtime (kernel-runtime kernel))
             (pointer (%xwayland-create
                       (ataxia.runtime::%object-pointer (ataxia.runtime::%runtime-display runtime))
                       (ataxia.runtime::%object-pointer (ataxia.runtime::%runtime-compositor-global runtime)) lazy)))
        (when (cffi:null-pointer-p pointer) (error "Could not create XWayland server."))
        (let ((server (make-instance 'xwayland-server :pointer pointer :runtime runtime)))
          (setf (gethash kernel *xwayland-servers*) server)
          (ataxia.runtime::%attach-object-signal server :xwayland-new-surface (%xwayland-signal pointer 0)
            (lambda (surface) (%x-new-surface kernel server surface)))
          (flet ((set-seat ()
                   (let ((seat (first (kernel-seats kernel))))
                     (when seat (%xwayland-set-seat pointer (ataxia.runtime::%object-pointer (seat-runtime-object seat)))))))
            (set-seat)
            (ataxia.runtime::%attach-object-signal server :xwayland-ready (%xwayland-signal pointer 1)
              (lambda (data) (declare (ignore data)) (set-seat))))
          (ataxia.runtime::%attach-object-signal server :xwayland-destroy (%xwayland-signal pointer 2)
            (lambda (data)
              (declare (ignore data))
              (ataxia.runtime::%retire-object-listeners server :immediate-p t)
              (ataxia.runtime::%invalidate-native-object server)
              (remhash kernel *xwayland-servers*)))
          server))))

(defun disable-xwayland (kernel)
  (let ((server (gethash kernel *xwayland-servers*)))
    (when server (%xwayland-destroy (ataxia.runtime::%object-pointer server)))))

(defmethod ataxia.runtime:runtime-stopping :before ((kernel kernel) runtime reason)
  (declare (ignore runtime reason))
  (disable-xwayland kernel))

(defmethod ataxia.runtime:surface-mapped :after ((kernel kernel) runtime-surface)
  (let* ((node (gethash runtime-surface (%kernel-surface-table kernel)))
         (app (and node (%surface-tree-application node))))
    (unless app
      (let* ((server (gethash kernel *xwayland-servers*))
             (surface (and node server (loop for candidate being the hash-values of (%xserver-surfaces server)
                                        when (eq node (%xsurface-node candidate)) return candidate))))
        (when surface (setf app (%x-expose-application kernel surface node)))))
    (when (and (typep app 'xwayland-application) (eq node (application-root-surface app)))
      (setf (application-mapped-p app) t)
      (%call-world kernel world-object-changed app (make-object-change :mapped t))
      (%invalidate-application app))))

(defmethod ataxia.runtime:surface-unmapped :after ((kernel kernel) runtime-surface)
  (let* ((node (gethash runtime-surface (%kernel-surface-table kernel)))
         (app (and node (%surface-tree-application node))))
    (when (and (typep app 'xwayland-application) (eq node (application-root-surface app)))
      (setf (application-mapped-p app) nil)
      (%call-world kernel world-object-changed app (make-object-change :mapped nil)))))

(defmethod drawable-local-bounds ((application xwayland-application))
  (let ((root (application-root-surface application)))
    (values 0 0 (surface-width root) (surface-height root))))

(defmethod %application-surface-at ((application xwayland-application) x y)
  (let ((runtime (kernel-runtime (object-kernel application))) (nodes nil))
    (%walk-surface-tree (application-root-surface application)
                        (lambda (node dx dy) (push (list node dx dy) nodes)))
    (cffi:with-foreign-objects ((sx :double) (sy :double))
      (dolist (entry nodes)
        (destructuring-bind (node dx dy) entry
          (when (surface-mapped-p node)
            (let ((hit (%xsurface-at (ataxia.runtime::%object-pointer (surface-runtime-object node))
                                    (coerce (- x dx) 'double-float) (coerce (- y dy) 'double-float) sx sy)))
              (unless (cffi:null-pointer-p hit)
                (return-from %application-surface-at
                  (values (ataxia.runtime::%adopt-core-surface runtime hit)
                          (cffi:mem-ref sx :double) (cffi:mem-ref sy :double)))))))))))

(defmethod request-object-configuration ((application xwayland-application) world (configuration toplevel-configuration))
  (let* ((surface (application-toplevel application)) (pointer (ataxia.runtime::%object-pointer surface))
         (width (configuration-width configuration)) (height (configuration-height configuration)))
    (unless (and (eq width :unchanged) (eq height :unchanged))
      (%xsurface-configure pointer (%xsurface-value pointer 0) (%xsurface-value pointer 1)
                           (max 1 (min 65535 (if (eq width :unchanged) (%xsurface-value pointer 2) width)))
                           (max 1 (min 65535 (if (eq height :unchanged) (%xsurface-value pointer 3) height)))))
    (%apply-configuration-field (configuration-activated configuration)
                               (lambda (value) (request-object-state application world :activated value))))
  application)

(defmethod request-object-state ((application xwayland-application) world state value)
  (declare (ignore world))
  (let* ((surface (application-toplevel application)) (pointer (ataxia.runtime::%object-pointer surface)))
    (case state
      (:activated
       (when value (setf (%xserver-focused (%xsurface-server surface)) application))
       (%xsurface-activate pointer (not (null value))))
      (:fullscreen (%xsurface-fullscreen pointer (not (null value))))
      (:maximized (%xsurface-maximized pointer (not (null value)) (not (null value))))
      ((:suspended :minimized) (%xsurface-minimized pointer (not (null value))))
      (:close (%xsurface-close pointer))))
  application)
