(in-package #:ataxia.world.rmlui)
(defmethod ataxia.world:ui-raster-scale ((component rmlui-component))
  (rmlui-component-scale component))
(defmethod ataxia.world:ui-resize ((component rmlui-component) width height
                                  &key (scale (rmlui-component-scale component)))
  (resize-rmlui-component component width height :scale scale))
(defmethod ataxia.world:ui-destroy ((component rmlui-component))
  (destroy-rmlui-component component))
(defmethod ataxia.world:ui-set-invalidator ((component rmlui-component) function)
  (set-rmlui-component-invalidator component function))
(defmethod ataxia.world:ui-set-property ((component rmlui-component) name value)
  (set-rmlui-property component name value))
(defmethod ataxia.world:ui-set-callback ((component rmlui-component) name function)
  (set-rmlui-callback component name function))
(defmethod ataxia.world:ui-next-update-delay ((component rmlui-component))
  (let ((delay (ataxia.world.rmlui.raw::%next-update (%live-native component))))
    (unless (minusp delay) delay)))
