cmake_minimum_required(VERSION 3.19)
if(POLICY CMP0135)
  cmake_policy(SET CMP0135 NEW)
endif()
project(ataxia_rmlui_native LANGUAGES C CXX)
include(FetchContent)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(RMLUI_SAMPLES OFF CACHE BOOL "" FORCE)
set(RMLUI_PRECOMPILED_HEADERS OFF CACHE BOOL "" FORCE)
FetchContent_Declare(rmlui
  URL https://codeload.github.com/mikke89/RmlUi/tar.gz/ba95ffe8bfb6370efb2cdcca927eaad4710c5413
  URL_HASH SHA256=1541ef5577115e9368f8ed389b29f0925ef6572f326a33d378ea16c3cfa2cde8)
FetchContent_MakeAvailable(rmlui)
find_package(PkgConfig REQUIRED)
pkg_check_modules(DEPS REQUIRED IMPORTED_TARGET glesv2 libpng xkbcommon)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
execute_process(COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/adapt-renderer.py
  ${rmlui_SOURCE_DIR}/Backends ${CMAKE_CURRENT_BINARY_DIR}/renderer COMMAND_ERROR_IS_FATAL ANY)
add_library(ataxia-rmlui-native SHARED bridge.cpp ${CMAKE_CURRENT_BINARY_DIR}/renderer/RmlUi_Renderer_GL3.cpp)
target_compile_features(ataxia-rmlui-native PRIVATE cxx_std_17)
target_compile_options(ataxia-rmlui-native PRIVATE -Wall -Wextra -fvisibility=hidden)
target_include_directories(ataxia-rmlui-native PRIVATE ${CMAKE_CURRENT_BINARY_DIR}/renderer)
target_compile_definitions(ataxia-rmlui-native PRIVATE ATAXIA_RMLUI_GLES RMLUI_NUM_MSAA_SAMPLES=0)
target_link_libraries(ataxia-rmlui-native PRIVATE RmlUi::Core PkgConfig::DEPS)
