;;;; The owner never enters Chromium, waits for JavaScript, or polls the browser.
(in-package #:ataxia.world.web)
(defclass web-engine ()
  ((native :initarg :native :reader %engine-native)
   (world :initarg :world :reader %engine-world)
   (components :initform nil :accessor %engine-components)
   (sources :initform nil :accessor %engine-sources)
   (stopped :initform nil :accessor %engine-stopped)))
(defclass web-component (ataxia.kernel:drawable ataxia.kernel:interactable)
  ((native :initarg :native :reader %native)
   (engine :initarg :engine :reader %engine)
   (width :initarg :width :accessor web-component-width)
   (height :initarg :height :accessor web-component-height)
   (scale :initarg :scale :accessor web-component-scale)
   (visible :initform t :accessor %visible)
   (destroyed :initform nil :accessor %destroyed)
   (error :initform nil :accessor web-component-error)
   (invalidator :initarg :invalidator :initform nil :accessor %invalidator)
   (callbacks :initform (make-hash-table :test #'equal) :reader %callbacks)
   (surfaces :initform #() :accessor %surfaces)
   (revision :initform 0 :accessor %revision)
   (temporary-directory :initform nil :accessor %temporary-directory)))
(defun %helper-path ()
  (or (uiop:getenv "ATAXIA_WEB_HELPER")
      (namestring (asdf:system-relative-pathname "ataxia-web" "build/web-native/ataxia-web-helper"))))
(defun %live (component)
  (when (or (%destroyed component) (%engine-stopped (%engine component)))
    (error "The web component is destroyed or its helper stopped."))
  (%native component))
(defun %command (component op &key (a 0) (b 0) (c 0) (d 0) (scale 0d0) (text ""))
  (unless (plusp (ataxia.world.web.raw::%command (%live component) op a b c d (coerce scale 'double-float) text))
    (error "Web UI: ~A" (ataxia.world.web.raw::%error)))
  component)
(defun %notify (component)
  (when (and (not (%destroyed component)) (%invalidator component))
    (funcall (%invalidator component) component)))
(defun %send-ui-command (component op &rest arguments)
  ;; A helper can exit between a visibility/resize event and its EOF callback.
  ;; Keep transport failure inside the optional component, not World policy.
  (handler-case (apply #'%command component op arguments)
    (error (cause) (setf (web-component-error component) (princ-to-string cause)) nil)))
(defgeneric %dispatch-event (component name value)
  (:method ((component web-component) name value)
    (let ((handler (gethash name (%callbacks component))))
      (when handler (funcall handler component value)))))
(defun %poll-events (component)
  (unless (or (%destroyed component) (%engine-stopped (%engine component)))
    ;; Copy before calling Lisp: a callback may remove this or another component.
    (let ((events
            (cffi:with-foreign-objects ((name :char 80) (value :char 8192))
              (loop repeat 32 while (plusp (ataxia.world.web.raw::%event (%native component) name value))
                    collect (cons (cffi:foreign-string-to-lisp name :encoding :utf-8)
                                  (cffi:foreign-string-to-lisp value :encoding :utf-8))))))
      (dolist (event events)
        (unless (%destroyed component)
          (when (equal (car event) "error") (setf (web-component-error component) (cdr event)))
          (%dispatch-event component (car event) (cdr event)))))))
(defun %stop-engine (engine)
  (unless (%engine-stopped engine)
    (setf (%engine-stopped engine) t)
    (dolist (source (%engine-sources engine)) (ataxia.runtime:remove-event-loop-source source))
    (setf (%engine-sources engine) nil)
    (ataxia.world.web.raw::%engine-destroy (%engine-native engine))
    (ataxia.world:detach-world-service (%engine-world engine) :web-ui)))
(defun %ensure-engine (world)
  (or (ataxia.world:world-service world :web-ui)
      (let ((native (ataxia.world.web.raw::%engine-create
                     (%helper-path)
                     (or (ataxia.runtime:runtime-socket-name
                          (ataxia.kernel:kernel-runtime (ataxia.kernel:world-kernel world))) ""))))
        (when (cffi:null-pointer-p native) (error "Web UI: ~A" (ataxia.world.web.raw::%error)))
        (unless (= 2 (ataxia.world.web.raw::%abi)) (error "Unsupported web UI adapter ABI."))
        (let* ((engine (make-instance 'web-engine :world world :native native))
               (kernel (ataxia.kernel:world-kernel world))
               (runtime (ataxia.kernel:kernel-runtime kernel)))
          (handler-case
              (progn
                (ataxia.world:attach-world-service world :web-ui engine)
                (push (ataxia.runtime:add-event-loop-fd
                       runtime (ataxia.world.web.raw::%engine-fd native) ataxia.runtime:+event-readable+
                       (lambda (source fd mask)
                         (declare (ignore source fd mask))
                         (unless (%engine-stopped engine)
                           (ataxia.world.web.raw::%engine-drain native)
                           (%sync-visibility engine)
                           (dolist (component (copy-list (%engine-components engine)))
                             (%poll-events component)
                             (when (and (not (%destroyed component)) (%visible component)
                                        (plusp (ataxia.world.web.raw::%dirty (%native component))))
                               (%notify component)))) 0)) (%engine-sources engine))
                (push (ataxia.runtime:add-event-loop-fd
                       runtime (ataxia.world.web.raw::%engine-socket native) ataxia.runtime:+event-readable+
                       (lambda (source fd mask)
                         (declare (ignore source fd mask))
                         (if (minusp (ataxia.world.web.raw::%engine-receive native))
                             (progn
                               (dolist (component (copy-list (%engine-components engine)))
                                 (setf (web-component-error component)
                                       (format nil "Browser helper exited or its buffer transport failed: ~A" (ataxia.world.web.raw::%error)))
                                 (let ((handler (gethash "error" (%callbacks component))))
                                   (when handler (funcall handler component (web-component-error component)))))
                               (%stop-engine engine))
                             (dolist (component (copy-list (%engine-components engine)))
                               (when (and (%visible component)
                                          (plusp (ataxia.world.web.raw::%dirty (%native component))))
                                 (%notify component)))) 0)) (%engine-sources engine))
                engine)
            (error (e) (%stop-engine engine) (error e)))))))
(defmethod ataxia.world:service-quiescing ((engine web-engine) world reason)
  (declare (ignore world reason)) (%stop-engine engine))
(defmethod ataxia.world:service-before-render ((engine web-engine) world lease)
  (declare (ignore world lease)) (%sync-visibility engine))
(defun web-engine-pid (world)
  (let ((engine (ataxia.world:world-service world :web-ui)))
    (when engine (ataxia.world.web.raw::%engine-pid (%engine-native engine)))))
(defun %validate-size (width height scale)
  (dolist (v (list width height scale)) (check-type v (real (0))))
  (when (or (> width 16384) (> height 16384))
    (error "Web component exceeds the 16384 CSS-pixel viewport limit.")))
(defun make-web-component (&key world source source-path url asset-root component-name
                               (width 640d0) (height 360d0) (scale 1d0) invalidator (component-class 'web-component))
  "Create an ordinary drawable/interactable, asynchronously. Supply URL or HTML SOURCE.
ASSET-ROOT serves a built web app at ataxia://ui/ with normal module/fetch semantics."
  (declare (ignore component-name))
  (check-type world ataxia.kernel:world)
  (%validate-size width height scale)
  (setf scale (min (coerce scale 'double-float) (/ 4095d0 (max (ceiling width) (ceiling height)))))
  (when (> (count-if #'identity (list source source-path url)) 1)
    (error "Supply exactly one of SOURCE, SOURCE-PATH, or URL."))
  (let ((temporary nil) (component nil))
    (unwind-protect
         (progn
           (when source-path
             (setf asset-root (uiop:pathname-directory-pathname (truename source-path))
                   url (format nil "ataxia://ui/~A" (file-namestring source-path))))
           (when source
             (when asset-root (error "Inline SOURCE cannot use ASSET-ROOT; use a file or built app directory."))
             (setf temporary (uiop:ensure-directory-pathname
                              (cffi:with-foreign-string (template "/tmp/ataxia-web-XXXXXX")
                                (let ((p (cffi:foreign-funcall "mkdtemp" :pointer template :pointer)))
                                  (when (cffi:null-pointer-p p) (error "Cannot create HTML asset directory."))
                                  (cffi:foreign-string-to-lisp p))))
                   asset-root temporary url "ataxia://ui/index.html")
             (with-open-file (out (merge-pathnames "index.html" temporary) :direction :output :if-exists :supersede :external-format :utf-8)
               (write-string source out)))
           (unless url (setf url "ataxia://ui/index.html"))
           (when asset-root (setf asset-root (truename (uiop:ensure-directory-pathname asset-root))))
           (let* ((engine (%ensure-engine world))
                  (native (ataxia.world.web.raw::%create
                           (%engine-native engine) (ceiling width) (ceiling height) (coerce scale 'double-float)
                           (format nil "~A~%~A" (if asset-root (namestring asset-root) "") url))))
             (when (cffi:null-pointer-p native) (error "Web UI: ~A" (ataxia.world.web.raw::%error)))
             (setf component (make-instance component-class :engine engine :native native
                                           :width (coerce width 'double-float) :height (coerce height 'double-float)
                                           :scale (coerce scale 'double-float) :invalidator invalidator)
                   (%temporary-directory component) temporary)
             (push component (%engine-components engine))
             component))
      (when (null component)
        (when temporary (uiop:delete-directory-tree temporary :validate t))
        (let ((engine (ataxia.world:world-service world :web-ui)))
          (when (and engine (null (%engine-components engine))) (%stop-engine engine)))))))
(defun destroy-web-component (component)
  (unless (%destroyed component)
    (when (plusp (ataxia.world.web.raw::%texture (%native component)))
      (error "Detach web component graphics before destruction."))
    (let ((engine (%engine component)))
      (ataxia.world.web.raw::%destroy (%native component) (if (%engine-stopped engine) 0 1))
      (setf (%destroyed component) t (%invalidator component) nil
            (%engine-components engine) (remove component (%engine-components engine)))
      (clrhash (%callbacks component))
      (when (%temporary-directory component)
        (uiop:delete-directory-tree (%temporary-directory component) :validate t))
      (unless (%engine-components engine) (%stop-engine engine))))
  nil)
(defun resize-web-component (component width height &key (scale (web-component-scale component)))
  (%validate-size width height scale)
  (setf scale (min (coerce scale 'double-float) (/ 4095d0 (max (ceiling width) (ceiling height)))))
  (unless (and (= width (web-component-width component)) (= height (web-component-height component)) (= scale (web-component-scale component)))
    (unless (%engine-stopped (%engine component))
      (%send-ui-command component 3 :a (ceiling width) :b (ceiling height) :scale scale))
    (setf (web-component-width component) (coerce width 'double-float)
          (web-component-height component) (coerce height 'double-float)
          (web-component-scale component) (coerce scale 'double-float)))
  component)
(defun set-web-visible (component visible)
  (let ((value (not (null visible))))
    (unless (or (%destroyed component) (%engine-stopped (%engine component)) (eql value (%visible component)))
      (%send-ui-command component 4 :a (if value 1 0)) (setf (%visible component) value)))
  component)
(defun evaluate-web-javascript (component code)
  "Queue JavaScript on the browser's main frame; never wait on the World owner."
  (%command component 11 :text code))
(defun navigate-web-component (component url) (%command component 12 :text url))
(defun %json-string (value)
  (with-output-to-string (out)
    (write-char #\" out)
    (loop for ch across value for code = (char-code ch) do
      (case ch (#\" (write-string "\\\"" out)) (#\\ (write-string "\\\\" out))
        (otherwise (if (or (< code 32) (= code #x2028) (= code #x2029))
                       (format out "\\u~4,'0X" code) (write-char ch out)))))
    (write-char #\" out)))
(defun post-web-message (component name json)
  "Dispatch ataxia-message in the page with {name,value}; JSON is parsed in the browser."
  (evaluate-web-javascript component
    (format nil "dispatchEvent(new CustomEvent('ataxia-message',{detail:{name:~A,value:JSON.parse(~A)}}))"
            (%json-string name) (%json-string json))))
(defun web-component-stats (component)
  (let ((native (%live component)))
    (list :paints (ataxia.world.web.raw::%paints native) :uploads (ataxia.world.web.raw::%uploads native)
          :uploaded-bytes (ataxia.world.web.raw::%uploaded-bytes native)
          :transport (if (plusp (ataxia.world.web.raw::%transport native)) :dma-buf :bitmap)
          :gpu-copies (ataxia.world.web.raw::%gpu-copies native)
          :gpu-imports (ataxia.world.web.raw::%gpu-imports native)
          :skipped-frames (ataxia.world.web.raw::%skipped native)
          :dropped-events (ataxia.world.web.raw::%dropped native)
          :visible (%visible component) :error (web-component-error component))))
(defmethod ataxia.world:ui-raster-scale ((c web-component)) (web-component-scale c))
(defmethod ataxia.world:ui-resize ((c web-component) width height &key (scale (web-component-scale c)))
  (resize-web-component c width height :scale scale))
(defmethod ataxia.world:ui-destroy ((c web-component)) (destroy-web-component c))
(defmethod ataxia.world:ui-set-invalidator ((c web-component) function) (setf (%invalidator c) function))
(defmethod ataxia.world:ui-set-callback ((c web-component) name function) (setf (gethash name (%callbacks c)) function))
(defmethod ataxia.world:ui-dispatch-callbacks ((c web-component)) (%poll-events c))
(defmethod ataxia.world:ui-set-property ((c web-component) name value)
  (post-web-message c name
    (etypecase value
      (string (%json-string value)) (boolean (if value "true" "false"))
      (real (format nil "~F" (coerce value 'double-float))))))
