;;;; Only the ordinary copied input contracts cross this adapter.
(in-package #:ataxia.world.web)
(defun %delivered (component)
  (ataxia.kernel:make-interaction-result :status :delivered :object component))
(defmethod ataxia.kernel:interactable-pointer-motion ((c web-component) world seat x y input)
  (declare (ignore world seat input))
  (%command c 6 :a (round x) :b (round y)) (%delivered c))
(defmethod ataxia.kernel:interactable-pointer-button ((c web-component) world seat x y input)
  (declare (ignore world seat))
  (let ((button (case (ataxia.kernel:cursor-button-input-code input) (272 1) (273 2) (274 3))))
    (when button
      (%command c 7 :a (round x) :b (round y) :c button
                   :d (if (eq :pressed (ataxia.kernel:cursor-button-input-state input)) 1 0))))
  (%delivered c))
(defmethod ataxia.kernel:interactable-pointer-axis ((c web-component) world seat x y input)
  (declare (ignore world seat))
  (let* ((delta (round (* (if (eq :inverted (ataxia.kernel:cursor-axis-input-relative-direction input)) 1 -1)
                          (ataxia.kernel:cursor-axis-input-delta input))))
         (horizontal (eq :horizontal (ataxia.kernel:cursor-axis-input-orientation input))))
    (%command c 8 :a (round x) :b (round y) :c (if horizontal delta 0) :d (if horizontal 0 delta)))
  (%delivered c))
(defmethod ataxia.kernel:interactable-pointer-leave ((c web-component) world seat)
  (declare (ignore world seat)) (%command c 6 :c 1) (%delivered c))
(defmethod ataxia.kernel:interactable-focus ((c web-component) world seat kind)
  (declare (ignore world seat)) (%command c 5 :a (if (eq kind :keyboard) 1 0)) (%delivered c))
(defun %modifiers (names)
  (logior (if (member :caps-lock names) 1 0) (if (member :shift names) 2 0)
          (if (member :control names) 4 0) (if (member :alt names) 8 0)
          (if (member :logo names) 128 0) (if (member :num-lock names) 256 0)))
(defun %keysym (symbol)
  (etypecase symbol
    (integer symbol)
    (string (cffi:foreign-funcall "xkb_keysym_from_name" :string symbol :int 0 :uint32))))
(defun %unicode (symbol)
  (cffi:foreign-funcall "xkb_keysym_to_utf32" :uint32 (%keysym symbol) :uint32))
(defparameter +punctuation-keys+
  '((59 . 186) (58 . 186) (61 . 187) (43 . 187) (44 . 188) (60 . 188)
    (45 . 189) (95 . 189) (46 . 190) (62 . 190) (47 . 191) (63 . 191)
    (96 . 192) (126 . 192) (91 . 219) (123 . 219) (92 . 220) (124 . 220)
    (93 . 221) (125 . 221) (39 . 222) (34 . 222)
    (33 . 49) (64 . 50) (35 . 51) (36 . 52) (37 . 53) (94 . 54)
    (38 . 55) (42 . 56) (40 . 57) (41 . 48)))
(defun %virtual-key (symbol)
  (let* ((key (%keysym symbol)) (unicode (%unicode symbol))
         (punctuation (cdr (assoc unicode +punctuation-keys+))))
    (cond (punctuation punctuation) ((<= 97 unicode 122) (- unicode 32)) ((<= 32 unicode 126) unicode)
          ((<= #xffbe key #xffd5) (+ 112 (- key #xffbe)))
          (t (case key (#xff08 8) (#xff09 9) (#xff0d 13) (#xff1b 27)
               (#xffff 46) (#xff50 36) (#xff51 37) (#xff52 38) (#xff53 39) (#xff54 40)
               (#xff55 33) (#xff56 34) (#xff57 35) (#xff63 45)
               ((#xffe1 #xffe2) 16) ((#xffe3 #xffe4) 17) ((#xffe9 #xffea) 18) (otherwise 0))))))
(defmethod ataxia.kernel:interactable-key-event ((c web-component) world seat input)
  (declare (ignore world seat))
  (when (typep input 'ataxia.kernel:modifiers-input)
    (%command c 14 :a (%modifiers (ataxia.kernel:modifiers-input-names input))))
  (when (typep input 'ataxia.kernel:key-input)
    (let ((pressed (eq :pressed (ataxia.kernel:key-input-state input)))
          (names (ataxia.kernel:key-input-modifiers input)))
      (loop for symbol across (ataxia.kernel:key-input-keysyms input) do
        (%command c 9 :a (%virtual-key symbol) :b (if pressed 1 0)
                     :c (+ 8 (ataxia.kernel:key-input-keycode input)) :d (%modifiers names)
                     :text (let ((value (%unicode symbol))) (if (plusp value) (string (code-char value)) "")))
        (when (and pressed (not (intersection names '(:control :alt :logo))))
          (let ((unicode (%unicode symbol)))
            (when (or (>= unicode 32) (member unicode '(9 13)))
              (%command c 10 :text (string (code-char unicode)))))))))
  (%delivered c))
(defmethod ataxia.kernel:request-object-configuration ((c web-component) world configuration)
  (declare (ignore world configuration)) c)
(defmethod ataxia.kernel:request-object-state ((c web-component) world state value)
  (declare (ignore world))
  (when (eq state :visible) (set-web-visible c value)) c)

;; An optional browser process failing must never turn ordinary human input
;; into a World watchdog failure. Explicit authoring API errors still propagate.
(defmacro %contain-input-errors (name arguments)
  `(defmethod ,name :around ((c web-component) ,@arguments)
     (if (or (%destroyed c) (%engine-stopped (%engine c)))
         (ataxia.kernel:make-interaction-result :status :unavailable :object c)
         (handler-case (call-next-method)
           (error (cause)
             (setf (web-component-error c) (princ-to-string cause))
             (ataxia.kernel:make-interaction-result :status :unavailable :object c))))))
(%contain-input-errors ataxia.kernel:interactable-pointer-motion (world seat x y input))
(%contain-input-errors ataxia.kernel:interactable-pointer-button (world seat x y input))
(%contain-input-errors ataxia.kernel:interactable-pointer-axis (world seat x y input))
(%contain-input-errors ataxia.kernel:interactable-pointer-leave (world seat))
(%contain-input-errors ataxia.kernel:interactable-key-event (world seat input))
(%contain-input-errors ataxia.kernel:interactable-focus (world seat kind))
