(in-package #:ataxia.world.web)
(defclass web-render-source (ataxia.kernel:render-source)
  ((texture :initarg :texture :reader %source-texture)
   (width :initarg :width :reader %source-width)
   (height :initarg :height :reader %source-height)
   (generation :initarg :generation :reader %source-generation)))
(defmethod ataxia.kernel:render-source-width ((s web-render-source)) (%source-width s))
(defmethod ataxia.kernel:render-source-height ((s web-render-source)) (%source-height s))
(defmethod ataxia.kernel:render-source-gles-target ((s web-render-source)) #x0de1)
(defmethod ataxia.kernel:render-source-gles-name ((s web-render-source)) (%source-texture s))
(defmethod ataxia.kernel:render-source-has-alpha-p ((s web-render-source)) t)
(defmethod ataxia.kernel:render-source-generation ((s web-render-source)) (%source-generation s))
(defmethod ataxia.kernel:retain-render-source ((s web-render-source)) s)
(defmethod ataxia.kernel:release-render-source ((s web-render-source)) nil)
(defmethod ataxia.kernel:drawable-local-bounds ((c web-component))
  (values 0d0 0d0 (web-component-width c) (web-component-height c)))
(defmethod ataxia.kernel:drawable-surfaces ((c web-component)) (values (%surfaces c) (%revision c)))
(defmethod ataxia.kernel:drawable-active-p ((c web-component))
  (and (not (%destroyed c)) (not (%engine-stopped (%engine c))) (not (web-component-error c)) (%visible c)
       (plusp (ataxia.world.web.raw::%dirty (%native c)))))
(defmethod ataxia.kernel:drawable-attach-graphics ((c web-component))
  ;; No browser or GL allocation until it has produced its first frame.
  (when (or (%destroyed c) (%engine-stopped (%engine c)))
    (return-from ataxia.kernel:drawable-attach-graphics c))
  (cffi:with-foreign-object (major :int)
    (cffi:foreign-funcall "glGetIntegerv" :uint #x821b :pointer major :void)
    (when (< (cffi:mem-ref major :int) 3) (error "Web UI texture uploads require GLES 3.0 or newer."))) c)
(defmethod ataxia.kernel:drawable-detach-graphics ((c web-component))
  (unless (%destroyed c)
    (ataxia.world.web.raw::%detach (%native c)) (setf (%surfaces c) #()))
  c)
(defun %web-surface (c texture width height x y &optional (logical-width (/ width (web-component-scale c))) (logical-height (/ height (web-component-scale c))))
  (make-instance 'ataxia.kernel:drawable-surface
    :local-x x :local-y y :width logical-width :height logical-height
    :texture-coordinates #(0d0 0d0 1d0 0d0 0d0 1d0 1d0 1d0)
    :render-source (make-instance 'web-render-source :texture texture :width width :height height :generation (%revision c))))
(defmethod ataxia.kernel:drawable-prepare-frame ((c web-component))
  (when (or (%destroyed c) (%engine-stopped (%engine c)) (web-component-error c))
    (return-from ataxia.kernel:drawable-prepare-frame (values nil nil)))
  (when (zerop (ataxia.world.web.raw::%texture (%native c)))
    (ataxia.kernel:drawable-attach-graphics c))
  (cffi:with-foreign-object (rect :int 4)
    (let ((result (ataxia.world.web.raw::%upload (%native c) rect)))
      (when (minusp result)
        (setf (web-component-error c) (ataxia.world.web.raw::%error))
        (return-from ataxia.kernel:drawable-prepare-frame (values nil nil)))
      (when (plusp result)
        (incf (%revision c))
        (let* ((native (%native c)) (scale (web-component-scale c))
               (surface (%web-surface c (ataxia.world.web.raw::%texture native)
                                      (ataxia.world.web.raw::%width native) (ataxia.world.web.raw::%height native) 0d0 0d0
                                      (web-component-width c) (web-component-height c)))
               (popup (ataxia.world.web.raw::%popup-texture native)))
          ;; Browser popups are ordinary surfaces on the same drawable; no World
          ;; or renderer knowledge of browser widgets, and no compositing copy.
          (setf (%surfaces c)
                (if (zerop popup) (vector surface)
                    (vector surface (%web-surface c popup (ataxia.world.web.raw::%popup-width native)
                                                   (ataxia.world.web.raw::%popup-height native)
                                                   (/ (ataxia.world.web.raw::%popup-x native) scale)
                                                   (/ (ataxia.world.web.raw::%popup-y native) scale)))))
          (values (list (ataxia.world:make-rectangle
                         (/ (cffi:mem-aref rect :int 0) scale) (/ (cffi:mem-aref rect :int 1) scale)
                         (/ (cffi:mem-aref rect :int 2) scale) (/ (cffi:mem-aref rect :int 3) scale))) nil))))))
