(defpackage #:ataxia.screencast.native (:use #:cl))
(in-package #:ataxia.screencast.native)
(defvar *library* nil)
(defun initialize ()
  (or *library* (setf *library* (cffi:load-foreign-library
                                (asdf:system-relative-pathname "ataxia-screencast" "build/libataxia-screencast.so")))))
(cffi:defcstruct event (kind :uint32) (id :uint32) (types :uint32) (app :char :count 256))
(cffi:defcfun ("ataxia_screencast_create" create) :pointer)
(cffi:defcfun ("ataxia_screencast_destroy" destroy) :void (bridge :pointer))
(cffi:defcfun ("ataxia_screencast_fd" fd) :int (bridge :pointer))
(cffi:defcfun ("ataxia_screencast_next" next) :int (bridge :pointer) (event :pointer))
(cffi:defcfun ("ataxia_screencast_accept" accept-source) :void (bridge :pointer) (id :uint32) (type :uint32) (x :int32) (y :int32) (width :uint32) (height :uint32))
(cffi:defcfun ("ataxia_screencast_close" close-session) :void (bridge :pointer) (id :uint32))
(cffi:defcfun ("ataxia_screencast_submit" submit) :void (bridge :pointer) (id :uint32) (pixels :pointer) (size :size))
