;;;; Public Lisp application functions on plain Infinite World, without an assistant.
(load (merge-pathnames "system-support.lisp" *load-truename*))
(asdf:load-system "ataxia-agent")
(asdf:load-system "ataxia-computer-use/infinite-world")
(in-package #:cl-user)
(let* ((world (ataxia.infinite-world:make-infinite-world))
       (kernel (ataxia.kernel:create-kernel world :backend :headless))
       (control nil) (client nil) (worker nil) (done nil) (failure nil)
       (log (merge-pathnames (format nil "ataxia-lisp-input-~A.log" (ataxia.computer-use:random-token)) (uiop:temporary-directory)))
       (inventory (symbol-function 'ataxia.computer-use::%computer-windows)))
  (labels ((owner (f) (ataxia.sly-control:agent-inspect (lambda (k w) (declare (ignore k w)) (funcall f))))
           (evaluate (code &optional fail)
             (multiple-value-bind (out err status)
                 (uiop:run-program (list (namestring (asdf:system-relative-pathname "ataxia-agent" "scripts/ataxia-eval"))
                                         "--port" "4308" "--agent" "fixture" code)
                                   :output :string :error-output :string :ignore-error-status t)
               (assert (if fail (not (zerop status)) (zerop status)) () "~A~A" out err)
               (if fail err out))))
    (unwind-protect
        (progn
          (ataxia.kernel:start-kernel kernel)
          (setf control (ataxia.sly-control:start-sly-control kernel :port 4308)
                client (uiop:launch-program
                         (list "env" (format nil "WAYLAND_DISPLAY=~A" (ataxia.runtime:runtime-socket-name (ataxia.kernel:kernel-runtime kernel)))
                               (namestring (asdf:system-relative-pathname "ataxia-agent" "build/computer-use-client"))
                               (namestring log)) :output nil :error-output nil))
          (setf worker
            (sb-thread:make-thread
              (lambda ()
                (handler-case
                    (progn
                      (loop repeat 100 until (owner (lambda () (ataxia.world:world-windows world))) do (sleep .02d0)
                            finally (assert (owner (lambda () (ataxia.world:world-windows world)))))
                      (let* ((id (owner (lambda () (ataxia.kernel:object-id (ataxia.world:window-application (first (ataxia.world:world-windows world)))))))
                             (path nil) (session nil))
                        ;; Native Lisp operations must not collect/serialize the inventory.
                        (setf (symbol-function 'ataxia.computer-use::%computer-windows)
                              (lambda (&rest args) (declare (ignore args)) (error "Unexpected inventory construction")))
                        (let* ((*read-eval* nil)
                               (capture (read-from-string (evaluate (format nil "(ataxia.agent:capture-window agent ~D)" id)))))
                          (setf path (getf capture :path))
                          (assert (probe-file path))
                          (assert (= 600 (getf capture :coordinate-width))))
                        (assert (search "T" (evaluate (format nil "(progn (ataxia.agent:click agent ~D 50 50) (ataxia.agent:type-text agent ~D ~S) (ataxia.agent:press-key agent ~D ~S) (ataxia.agent:scroll agent ~D :y 15))" id id "abc" id "Return" id))))
                        (owner (lambda ()
                                 (assert (null (ataxia.world:world-service world :assistant)))
                                 (setf session (ataxia.agent::%named-session world "fixture"))
                                 (assert session)
                                 (ataxia.computer-use:pause-session session "Human takeover")))
                        (assert (search "paused" (evaluate (format nil "(ataxia.agent:press-key agent ~D ~S)" id "Return") t)))
                        (owner (lambda () (assert (eq session (ataxia.agent::%named-session world "fixture")))
                                         (ataxia.computer-use:activate-session session)))
                        (evaluate "(ataxia.agent:disconnect agent)")
                        (assert (not (probe-file path)))
                        ;; Another task causes native closed-record collection;
                        ;; that must not allow this disconnected name to reopen.
                        (evaluate (format nil "(progn (ataxia.agent:capture-window ~S ~D) (ataxia.agent:disconnect ~S))" "another" id "another"))
                        (evaluate (format nil "(ataxia.agent:capture-window agent ~D)" id) t)
                        (owner (lambda ()
                                 (assert (eq :closed (ataxia.computer-use:computer-session-state session)))
                                 (assert (notany #'ataxia.world:agent-seat-p (ataxia.world:world-seats world)))
                                 (assert (eq :running (ataxia.kernel:kernel-world-status kernel))))))
                      (format t "PASS: direct SLY capture/click/type/key/scroll, no assistant or inventories, pause, disconnect and resource cleanup.~%"))
                  (serious-condition (cause) (setf failure cause)))
                (setf done t))))
          (ataxia.kernel:run-kernel kernel :run-for 8d0)
          (assert done) (when failure (error failure)))
      (setf (symbol-function 'ataxia.computer-use::%computer-windows) inventory)
      (when control (ataxia.sly-control:stop-sly-control control))
      (ataxia.kernel:destroy-kernel kernel :test-complete)
      (when (and worker (sb-thread:thread-alive-p worker)) (sb-thread:terminate-thread worker))
      (when client (ignore-errors (uiop:terminate-process client)))
      (when (probe-file log) (delete-file log)))))
