;;;; Live Lisp on a plain Infinite World; no model or external terminal is needed.
(load (merge-pathnames "system-support.lisp" *load-truename*))
(asdf:load-system "ataxia-assistant/infinite-world")
(defpackage #:ataxia.test.assistant-lisp
  (:use #:cl #:ataxia.world)
  (:local-nicknames (#:a #:ataxia.assistant)))
(in-package #:ataxia.test.assistant-lisp)
(let* ((world (ataxia.infinite-world:make-infinite-world))
       (kernel (ataxia.kernel:create-kernel world :backend :headless))
       (control nil) (controller nil) (thread nil) (failure nil) (done nil))
  (labels ((owner (function) (a::%assistant-owner controller function))
           (evaluate (code mode)
             (a::%assistant-run-tool controller "ataxia_lisp" (a::%assistant-object "code" code "mode" mode)))
           (reject (code mode)
             (assert (handler-case (progn (evaluate code mode) nil) (error () t)))))
    (unwind-protect
         (progn
           (ataxia.kernel:start-kernel kernel)
           (setf control (ataxia.sly-control:start-sly-control kernel :port nil)
                 controller (a:enable world :scope :ataxia)
                 (a::assistant-controller-seat controller) (first (world-seats world)))
           (assert (null (a::assistant-controller-worker controller)))
           (assert (find "ataxia_lisp" (a::%assistant-tool-specs world :ataxia)
                         :key (lambda (tool) (gethash "name" tool)) :test #'equal))
           (assert (not (find "ataxia_lisp" (a::%assistant-tool-specs world :desktop)
                              :key (lambda (tool) (gethash "name" tool)) :test #'equal)))
           (setf thread
             (sb-thread:make-thread
               (lambda ()
                 (handler-case
                     (let ((generation (ataxia.kernel:kernel-world-generation kernel)))
                       (reject "(+ 1 2)" "worker")
                       (owner (lambda () (a::%assistant-grant controller)))
                       (assert (search "3" (getf (evaluate "(+ 1 2)" "worker") :output)))
                       (assert (search "T" (getf (evaluate "(typep world 'ataxia.infinite-world:infinite-world)" "inspect") :output)))
                       (assert (search "captured" (getf (evaluate "(progn (write-string \"captured\") :ok)" "apply") :output)))
                       (reject "#.(error \"reader ran\")" "worker")
                       (reject "1 2" "worker")
                       (reject "(error \"contained\")" "apply")
                       (assert (= generation (ataxia.kernel:kernel-world-generation kernel)))
                       (assert (eq world (ataxia.kernel:kernel-world kernel)))
                       (let ((result (evaluate "(dotimes (i 50000) (write-char #\\x))" "worker")))
                         (assert (eq t (getf result :truncated)))
                         (assert (= 16384 (length (getf result :output)))))
                       (owner (lambda () (a:pause world)))
                       (reject "(+ 1 2)" "worker")
                       (owner (lambda ()
                                (setf (a::assistant-controller-scope controller) :desktop)
                                (a::%assistant-grant controller)))
                       (reject "(+ 1 2)" "inspect"))
                   (serious-condition (cause) (setf failure cause)))
                 (setf done t)) :name "Live Lisp test"))
           (ataxia.kernel:run-kernel kernel :run-for 3d0)
           (assert done)
           (when failure (error failure))
           (format t "PASS: portable live Lisp, owner/worker execution, bounded output, reader isolation, error containment and pause/scope revocation.~%"))
      (when controller (a:disable world))
      (when control (ataxia.sly-control:stop-sly-control control))
      (ataxia.kernel:destroy-kernel kernel :test-complete)
      (when (and thread (sb-thread:thread-alive-p thread)) (sb-thread:terminate-thread thread)))))
