(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-assistant/metaworld")
(in-package #:ataxia.infinite-world)
(setf ataxia.assistant::*assistant-preview-error-output* "/tmp/ataxia-preview-host-test.log")
(with-open-file (log ataxia.assistant::*assistant-preview-error-output* :direction :output :if-exists :supersede) (declare (ignorable log)))
(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (project (merge-pathnames (format nil "ataxia-preview-test-~A/" (ataxia.computer-use::random-token)) (uiop:temporary-directory)))
       (control nil) (controller nil) (test-thread nil) (done nil) (failure nil))
  (labels ((owner (f) (ataxia.sly-control:agent-inspect (lambda (k w) (declare (ignore k w)) (funcall f)) :timeout 5d0))
           (document (text) (with-open-file (out (merge-pathnames "app.rml" project) :direction :output :if-exists :supersede) (write-string text out)))
           (bytes (path) (with-open-file (stream path :element-type '(unsigned-byte 8))
                           (let ((data (make-array (file-length stream) :element-type '(unsigned-byte 8))))
                             (read-sequence data stream) data))))
    (unwind-protect
         (progn
           (ensure-directories-exist project)
           (document "<rml><head><style>body { margin:0; width:100%; height:100%; font-family:DejaVu Sans; font-size:24px; color:#24282d; background:#ffffff; } button { position:absolute; left:20px; top:20px; width:140px; height:60px; background:#ddddff; } #counter { position:absolute; left:20px; top:100px; } </style></head><body><button id='increment'>Increment</button><div id='counter'>0</div></body></rml>")
           (ataxia.kernel:start-kernel kernel)
           (setf control (ataxia.sly-control:start-sly-control kernel :port nil))
           (setf controller (ataxia.assistant::%assistant-enable world :project (namestring project))
                 (ataxia.assistant::assistant-controller-scope controller) :project
                 (ataxia.assistant::assistant-controller-seat controller) (%canvas-seat-seat (first (%seat-states world))))
           (ataxia.assistant::%assistant-grant controller)
           (setf test-thread
             (sb-thread:make-thread
              (lambda ()
                (handler-case
                    (let* ((result (ataxia.assistant::%assistant-preview controller (ataxia.assistant::%assistant-object "path" "app.rml" "width" 640 "height" 400)))
                           (id (getf result :preview))
                           (preview (gethash id (ataxia.assistant::assistant-controller-previews controller))))
                      (assert (getf result :window))
                      (assert (getf result :image))
                      (let* ((before (getf (getf result :image) :path))
                             (copy (merge-pathnames "before.png" project)))
                        (uiop:copy-file before copy)
                        (uiop:copy-file before (asdf:system-relative-pathname "ataxia-assistant" "build/assistant-preview-before.png"))
                        (let* ((clicked (ataxia.assistant::%assistant-run-tool controller "ataxia_act"
                                          (ataxia.assistant::%assistant-object "actions" (vector (ataxia.assistant::%assistant-object "op" "move" "x" 80 "y" 50)
                                                                                (ataxia.assistant::%assistant-object "op" "button" "button" "left" "state" "click")))))
                               (after (getf (getf clicked :image) :path)))
                          (assert after)
                          (uiop:copy-file after (asdf:system-relative-pathname "ataxia-assistant" "build/assistant-preview-after.png"))
                          (assert (not (equalp (bytes copy) (bytes after))))))
                      (document "<rml><body><div>broken</body></rml>")
                      (assert (handler-case (progn (ataxia.assistant::%assistant-preview-update controller (ataxia.assistant::%assistant-object "preview" id "path" "app.rml")) nil) (error () t)))
                      (assert (= 1 (ataxia.assistant::assistant-preview-revision preview)))
                      (assert (uiop:process-alive-p (ataxia.assistant::assistant-preview-process preview)))
                      (document "<rml><head><style>body { font-family:DejaVu Sans; background:#eaf0ff; }</style></head><body><div>Updated successfully</div></body></rml>")
                      (let ((updated (ataxia.assistant::%assistant-preview-update controller (ataxia.assistant::%assistant-object "preview" id "path" "app.rml"))))
                        (assert (= 2 (getf updated :revision))) (assert (getf updated :image)))
                      ;; Real mapped window: animated packing must not invalidate its own Undo.
                      (let ((undo nil) (revision nil) (saved nil))
                        (owner (lambda ()
                          (setf (ataxia.assistant::assistant-controller-scope controller) :desktop)
                          (ataxia.assistant::%assistant-grant controller)
                          (setf saved (ataxia.world:world-desktop-state world))
                          (let* ((plan (ataxia.assistant::%assistant-layout-preview controller
                                        (ataxia.assistant::%assistant-object "revision" (ataxia.assistant::%assistant-layout-revision controller)
                                          "operations" (vector
                                            (ataxia.assistant::%assistant-object "op" "create-group" "ref" "test" "name" "Test" "policy" "master" "x" 0 "y" 0)
                                            (ataxia.assistant::%assistant-object "op" "place-window" "window" (getf result :window) "group" "test" "workspace" 2)))))
                                 (applied (ataxia.assistant::%assistant-layout-apply controller (ataxia.assistant::%assistant-object "plan" (getf plan :plan)))))
                            (setf undo (getf applied :undo) revision (getf (getf applied :snapshot) :revision)))))
                        (sleep 1d0)
                        (owner (lambda ()
                          (let ((after (ataxia.assistant::%assistant-layout-revision controller)))
                            (unless (= revision after) (format t "AFTER: ~A~%" (ataxia.assistant::assistant-controller-fingerprint controller)))
                            (assert (= revision after)))
                          (ataxia.assistant::%assistant-layout-undo controller undo)
                          (assert (equalp saved (ataxia.world:world-desktop-state world))))))
                      ;; Removing an occupied sub-world returns the client to the canvas; Undo restores membership.
                      (let ((saved nil) (undo nil) (group nil))
                        (owner (lambda ()
                          (setf group (first (metaworld-subworlds world)))
                          (move-object-to-subworld world (ataxia.world:find-world-window world (getf result :window)) group)
                          (%meta-toggle-fullscreen world (ataxia.world:find-world-window world (getf result :window)) t)
                          (enter-subworld world group (ataxia.assistant::assistant-controller-seat controller))
                          (setf saved (ataxia.world:world-desktop-state world))
                          (let* ((plan (ataxia.assistant::%assistant-layout-preview controller
                                         (ataxia.assistant::%assistant-object "revision" (ataxia.assistant::%assistant-layout-revision controller)
                                           "operations" (vector (ataxia.assistant::%assistant-object "op" "remove-group" "group" (subworld-id group))))))
                                 (applied (ataxia.assistant::%assistant-layout-apply controller (ataxia.assistant::%assistant-object "plan" (getf plan :plan)))))
                            (setf undo (getf applied :undo)))
                          (assert (not (member group (metaworld-subworlds world))))
                          (assert (null (object-subworld world (ataxia.world:find-world-window world (getf result :window)))))))
                        (sleep .4d0)
                        (owner (lambda ()
                          (ataxia.assistant::%assistant-layout-undo controller undo)
                          (assert (equalp saved (ataxia.world:world-desktop-state world)))
                          (assert (eq group (object-subworld world (ataxia.world:find-world-window world (getf result :window)))))))
                        (assert (uiop:process-alive-p (ataxia.assistant::assistant-preview-process preview))))
                      (owner (lambda () (ataxia.assistant::%assistant-disable world)))
                      (setf done t))
                  (error (cause) (setf failure cause done t)))) :name "Preview integration checks"))
           (ataxia.kernel:run-kernel kernel :run-for 20d0)
           (assert done)
           (when failure (error failure))
           (format t "PASS: native preview interaction, update recovery, animated layout transaction and exact Undo, occupied sub-world deletion/Undo without closing the client, cleanup.~%"))
      (when control (ataxia.sly-control:stop-sly-control control))
      (ataxia.kernel:destroy-kernel kernel :assistant-preview-test-complete)
      (when (and test-thread (sb-thread:thread-alive-p test-thread)) (sb-thread:terminate-thread test-thread))
      (uiop:delete-directory-tree project :validate t :if-does-not-exist :ignore))))
