(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-assistant/metaworld")
(in-package #:ataxia.infinite-world)
(load (merge-pathnames "assistant-voice-fixture.lisp" *load-truename*))
(setf ataxia.assistant::*assistant-command* (list "env" "ATAXIA_VOICE_FIXTURE=1" "sbcl" "--noinform" "--disable-debugger" "--script"
                           (namestring (asdf:system-relative-pathname "ataxia-assistant" "tests/assistant-mock-codex.lisp"))))
(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (control nil) (controller nil) (test-thread nil) (done nil) (failure nil))
  (labels ((owner (f) (ataxia.sly-control:agent-inspect (lambda (k w) (declare (ignore k w)) (funcall f)) :timeout 5d0))
           (wait-for (f)
             (loop repeat 160 when (owner f) do (return t) do (sleep .05d0)
                   finally (error "Timed out waiting for assistant. State: ~S / ~A"
                                  (ataxia.assistant::assistant-controller-task controller) (ataxia.assistant::assistant-controller-activity controller)))))
    (unwind-protect
         (progn
           (ataxia.kernel:start-kernel kernel)
           (setf control (ataxia.sly-control:start-sly-control kernel :port nil))
           (ataxia.world.shell:enable-rmlui-status-bar world)
           (setf controller (ataxia.assistant::%assistant-enable world :project (namestring (asdf:system-source-directory "ataxia-assistant"))))
           (ataxia.assistant::%assistant-open controller (%canvas-seat-seat (first (%seat-states world))))
           (assert (null (ataxia.assistant::assistant-controller-worker controller)))
           (assert (eq :off (ataxia.assistant::assistant-controller-microphone controller)))
           (setf test-thread
             (sb-thread:make-thread
              (lambda ()
                (handler-case
                    (progn
                      (sleep .5d0)
                      (owner (lambda () (ataxia.assistant::%assistant-submit controller "Inspect this isolated desktop.")))
                      (wait-for (lambda () (member (ataxia.assistant::assistant-controller-task controller) '(:done :failed))))
                      (owner (lambda ()
                               (assert (eq :done (ataxia.assistant::assistant-controller-task controller)) () "Assistant failed: ~A" (ataxia.assistant::assistant-controller-activity controller))
                               (assert (eq :ready (ataxia.assistant::assistant-controller-connection controller)))
                               (assert (= 1 (hash-table-count (ataxia.assistant::assistant-controller-seen-calls controller))))
                               (assert (search "<b>Safe text</b>" (getf (car (last (ataxia.assistant::assistant-controller-messages controller))) :text)))
                               (assert (null (ataxia.assistant::assistant-controller-session controller)))
                               (ataxia.assistant::%assistant-toggle-talk controller)))
                      (wait-for (lambda () (and (eq :listening (ataxia.assistant::assistant-controller-microphone controller))
                                               (eq :done (ataxia.assistant::assistant-controller-task controller))
                                               (find "Voice fixture task" (ataxia.assistant::assistant-controller-messages controller) :key (lambda (m) (getf m :text)) :test #'equal))))
                      (let* ((host (ataxia.assistant::assistant-controller-audio controller))
                             (process (ataxia.assistant::assistant-voice-host-process host))
                             (thread (ataxia.assistant::assistant-controller-audio-thread controller)))
                        (assert (uiop:process-alive-p process))
                        (owner (lambda () (ataxia.assistant::%assistant-toggle-microphone controller)))
                        (wait-for (lambda () (eq :muted (ataxia.assistant::assistant-controller-microphone controller))))
                        (assert (uiop:process-alive-p process))
                        (owner (lambda () (ataxia.assistant::%assistant-toggle-microphone controller)))
                        (wait-for (lambda () (eq :listening (ataxia.assistant::assistant-controller-microphone controller))))
                        ;; Connected and muted sessions have no metering/poll deadline.
                        (assert (null (ataxia.assistant::%assistant-voice-deadline controller)))
                        (owner (lambda ()
                          (assert (= 2 (ataxia.assistant::assistant-controller-turn-count controller)))
                          (assert (null (ataxia.assistant::assistant-controller-session controller)))
                          (assert (ataxia.assistant::assistant-controller-blocked controller))
                          (assert (= 1 (count "Voice fixture task" (ataxia.assistant::assistant-controller-messages controller)
                                             :key (lambda (m) (getf m :text)) :test #'equal)))
                          (ataxia.assistant::%assistant-close-panel controller)
                          (assert (eq :off (ataxia.assistant::assistant-controller-microphone controller)))))
                        (sb-thread:join-thread thread :timeout 2d0 :default :stuck)
                        (assert (not (sb-thread:thread-alive-p thread)))
                        (assert (not (uiop:process-alive-p process)))
                        (wait-for (lambda () (not (ataxia.assistant::assistant-controller-voice-stopping-p controller))))
                        (owner (lambda ()
                          (ataxia.assistant::%assistant-open controller (%canvas-seat-seat (first (%seat-states world))))
                          (ataxia.assistant::%assistant-toggle-talk controller)))
                        (wait-for (lambda () (eq :listening (ataxia.assistant::assistant-controller-microphone controller))))
                        ;; Late frames/EOF from the previous helper cannot affect the new voice session.
                        (ataxia.assistant::%assistant-queue controller :voice-host (list host nil))
                        (sleep .1d0)
                        (assert (eq :listening (ataxia.assistant::assistant-controller-microphone controller)))
                        (assert (not (eq host (ataxia.assistant::assistant-controller-audio controller))))
                        (let* ((replacement (ataxia.assistant::assistant-controller-audio controller))
                               (child (ataxia.assistant::assistant-voice-host-process replacement)))
                          (uiop:terminate-process child :urgent t)
                          (wait-for (lambda () (and (eq :off (ataxia.assistant::assistant-controller-microphone controller))
                                                   (ataxia.assistant::assistant-controller-voice-error controller))))
                          (assert (eq :ready (ataxia.assistant::assistant-controller-connection controller)))))
                      (wait-for (lambda () (not (ataxia.assistant::assistant-controller-voice-stopping-p controller))))
                      (setf *assistant-test-voice-mode* "mute-timeout")
                      (owner (lambda () (ataxia.assistant::%assistant-toggle-talk controller)))
                      (wait-for (lambda () (eq :listening (ataxia.assistant::assistant-controller-microphone controller))))
                      (let* ((host (ataxia.assistant::assistant-controller-audio controller))
                             (process (ataxia.assistant::assistant-voice-host-process host)))
                        (owner (lambda () (ataxia.assistant::%assistant-toggle-microphone controller)))
                        (sleep .1d0)
                        (assert (eq :muting (ataxia.assistant::assistant-controller-microphone controller)))
                        (wait-for (lambda () (eq :off (ataxia.assistant::assistant-controller-microphone controller))))
                        (assert (search "timed out" (ataxia.assistant::assistant-controller-activity controller)))
                        (assert (eq :ready (ataxia.assistant::assistant-controller-connection controller)))
                        (assert (not (uiop:process-alive-p process))))
                      (owner (lambda () (ataxia.assistant::%assistant-disable world)))
                      (setf done t))
                  (error (cause) (setf failure cause done t)))) :name "Assistant integration checks"))
           (ataxia.kernel:run-kernel kernel :run-for 18d0)
           (assert done)
           (when failure (error failure))
           (format t "PASS: WebRTC framing, negotiated device opening, mute acknowledgements/timeouts, single handoff, stale events, helper failure and immediate cleanup.~%"))
      (when control (ataxia.sly-control:stop-sly-control control))
      (ataxia.kernel:destroy-kernel kernel :assistant-test-complete)
      (when (and test-thread (sb-thread:thread-alive-p test-thread)) (sb-thread:terminate-thread test-thread)))))
