(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-assistant/metaworld")
(in-package #:ataxia.infinite-world)
(setf ataxia.assistant::*assistant-command* (list "env" "ATAXIA_APPROVAL_FIXTURE=1" "sbcl" "--noinform" "--disable-debugger" "--script"
                           (namestring (asdf:system-relative-pathname "ataxia-assistant" "tests/assistant-mock-codex.lisp"))))
(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (control nil) (controller nil) (test-thread nil) (done nil) (failure nil))
  (labels ((owner (f) (ataxia.sly-control:agent-inspect (lambda (k w) (declare (ignore k w)) (funcall f)) :timeout 5d0))
           (wait-for (f)
             (loop repeat 160 when (owner f) do (return t) do (sleep .05d0)
                   finally (error "Timed out waiting for assistant. State: ~S / ~A"
                                  (ataxia.assistant::assistant-controller-task controller) (ataxia.assistant::assistant-controller-activity controller)))))
    (unwind-protect
         (progn
           (ataxia.kernel:start-kernel kernel)
           (setf control (ataxia.sly-control:start-sly-control kernel :port nil))
           (ataxia.world.shell:enable-rmlui-status-bar world)
           (setf controller (ataxia.assistant::%assistant-enable world :project (namestring (asdf:system-source-directory "ataxia-assistant"))))
           (ataxia.assistant::%assistant-open controller (%canvas-seat-seat (first (%seat-states world))))
           (assert (null (ataxia.assistant::assistant-controller-worker controller)))
           (assert (eq :off (ataxia.assistant::assistant-controller-microphone controller)))
           (setf test-thread
             (sb-thread:make-thread
              (lambda ()
                (handler-case
                    (progn
                      (sleep .5d0)
                      (owner (lambda () (ataxia.assistant::%assistant-submit controller "Inspect this isolated desktop.")))
                      (wait-for (lambda () (ataxia.assistant::assistant-controller-request controller)))
                      (owner (lambda ()
                        (assert (eq :needs-input (ataxia.assistant::assistant-controller-task controller)))
                        (assert (equal "Inspect this desktop?" (ataxia.assistant::%assistant-field (ataxia.assistant::%assistant-question (ataxia.assistant::assistant-controller-request controller)) "question")))
                        (ataxia.assistant::%assistant-answer controller "Inspect")))
                      (wait-for (lambda () (member (ataxia.assistant::assistant-controller-task controller) '(:done :failed))))
                      (owner (lambda ()
                               (assert (eq :done (ataxia.assistant::assistant-controller-task controller)) () "Assistant failed: ~A" (ataxia.assistant::assistant-controller-activity controller))
                               (assert (eq :ready (ataxia.assistant::assistant-controller-connection controller)))
                               (assert (= 1 (ataxia.assistant::assistant-controller-tool-count controller)))
                               (assert (= 1 (hash-table-count (ataxia.assistant::assistant-controller-seen-calls controller))))
                               (assert (search "<b>Safe text</b>" (getf (car (last (ataxia.assistant::assistant-controller-messages controller))) :text)))
                               (assert (null (ataxia.assistant::assistant-controller-session controller)))
                               (ataxia.assistant::%assistant-toggle-talk controller)))
                      (wait-for (lambda () (and (eq :off (ataxia.assistant::assistant-controller-microphone controller))
                                                (search "Voice unavailable" (ataxia.assistant::assistant-controller-activity controller)))))
                      (owner (lambda ()
                               (assert (null (ataxia.assistant::assistant-controller-audio controller)))
                               (ataxia.assistant::%assistant-pause controller)
                               (assert (ataxia.assistant::assistant-controller-blocked controller))
                               (ataxia.assistant::%assistant-close-panel controller)
                               (assert (null (ataxia.assistant::assistant-controller-panel controller)))
                               (ataxia.assistant::%assistant-disable world)
                               (assert (null (ataxia.world:world-service world :assistant)))
                               (assert (eq :running (ataxia.kernel:kernel-world-status kernel)))))
                      (setf done t))
                  (error (cause) (setf failure cause done t)))) :name "Assistant integration checks"))
           (ataxia.kernel:run-kernel kernel :run-for 12d0)
           (assert done)
           (when failure (error failure))
           (format t "PASS: question choices, full-access command policy, duplicate call replay, completion and cleanup.~%"))
      (when control (ataxia.sly-control:stop-sly-control control))
      (ataxia.kernel:destroy-kernel kernel :assistant-test-complete)
      (when (and test-thread (sb-thread:thread-alive-p test-thread)) (sb-thread:terminate-thread test-thread)))))
