;;;; Opt-in end-to-end test: a real model closes only a disposable Wayland client.
(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-assistant/metaworld")
(in-package #:ataxia.infinite-world)
(unless (equal "1" (uiop:getenv "ATAXIA_TEST_CODEX"))
  (error "Set ATAXIA_TEST_CODEX=1 to run a real model turn."))
(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (project (merge-pathnames (format nil "ataxia-close-codex-~A/" (ataxia.computer-use::random-token)) (uiop:temporary-directory)))
       (controller nil) (control nil) (worker nil) (done nil) (failure nil))
  (labels ((owner (f)
             (ataxia.sly-control:agent-inspect (lambda (k w) (declare (ignore k w)) (funcall f)) :timeout 5d0)))
    (unwind-protect
         (progn
           (ensure-directories-exist project)
           (with-open-file (out (merge-pathnames "app.rml" project) :direction :output)
             (write-string "<rml><head><title>Disposable close test</title><style>body {font-family:DejaVu Sans;background:white;}</style></head><body>This test window has no unsaved data.</body></rml>" out))
           (ataxia.kernel:start-kernel kernel)
           (setf control (ataxia.sly-control:start-sly-control kernel :port nil)
                 controller (ataxia.assistant::%assistant-enable world :project (namestring project))
                 (ataxia.assistant::assistant-controller-scope controller) :project
                 (ataxia.assistant::assistant-controller-seat controller) (%canvas-seat-seat (first (%seat-states world))))
           (ataxia.assistant::%assistant-grant controller)
           (setf worker
                 (sb-thread:make-thread
                  (lambda ()
                    (handler-case
                        (let* ((result (ataxia.assistant::%assistant-preview controller (ataxia.assistant::%assistant-object "path" "app.rml")))
                               (id (getf result :window))
                               (preview (gethash (getf result :preview) (ataxia.assistant::assistant-controller-previews controller))))
                          (owner (lambda ()
                                   (setf (ataxia.assistant::assistant-controller-scope controller) :desktop)
                                   (ataxia.assistant::%assistant-submit controller
                                     (format nil "Close application window ~D in this isolated test desktop. It is a disposable test client with no unsaved work. Use the native Ataxia tools and verify that its window disappears. Do not run commands, edit files, or use another connection. Finish with one short sentence." id))))
                          (loop repeat 600 do
                            (when (owner (lambda ()
                                           (when (member (ataxia.assistant::assistant-controller-task controller) '(:done :failed :needs-input))
                                             (assert (eq :done (ataxia.assistant::assistant-controller-task controller)) () "Assistant: ~A" (ataxia.assistant::assistant-controller-activity controller))
                                             (assert (not (find id (%world-stacking world)
                                                                :key (lambda (w) (ataxia.kernel:object-id (canvas-window-application w))))))
                                             (assert (not (uiop:process-alive-p (ataxia.assistant::assistant-preview-process preview))))
                                             (assert (>= (ataxia.assistant::assistant-controller-tool-count controller) 2))
                                             (format t "PASS: real Codex used the native tools to close the test application and verify it disappeared.~%")
                                             t)))
                              (setf done t) (return))
                            (sleep .1d0)
                            finally (error "Model close test timed out: ~A" (ataxia.assistant::assistant-controller-activity controller))))
                      (error (cause) (setf failure cause done t))))
                  :name "Real Codex close test"))
           (ataxia.kernel:run-kernel kernel :run-for 75d0)
           (assert done)
           (when failure (error failure)))
      (when controller (ataxia.assistant::%assistant-disable world))
      (when control (ataxia.sly-control:stop-sly-control control))
      (ataxia.kernel:destroy-kernel kernel :assistant-close-codex-test-complete)
      (when (and worker (sb-thread:thread-alive-p worker)) (sb-thread:terminate-thread worker))
      (uiop:delete-directory-tree project :validate t :if-does-not-exist :ignore))))
