;;;; Live Lisp on a plain Infinite World; no model or external terminal is needed.
(load (merge-pathnames "system-support.lisp" *load-truename*))
(asdf:load-system "ataxia-assistant/infinite-world")
(defpackage #:ataxia.test.assistant-lisp
  (:use #:cl #:ataxia.world)
  (:local-nicknames (#:a #:ataxia.assistant)))
(in-package #:ataxia.test.assistant-lisp)
(defvar *expected-owner*)
(defclass owner-print-probe () ())
(defmethod print-object ((value owner-print-probe) stream)
  (assert (eq *expected-owner* sb-thread:*current-thread*))
  (write-string "owner-value" stream))
(let* ((world (ataxia.infinite-world:make-infinite-world))
       (kernel (ataxia.kernel:create-kernel world :backend :headless))
       (control nil) (controller nil) (thread nil) (failure nil) (done nil))
  (labels ((owner (function) (a::%assistant-owner controller function))
           (evaluate (code mode)
             (a::%assistant-run-tool controller "ataxia_lisp" (a::%assistant-object "code" code "mode" mode)))
           (reject (code mode)
             (assert (handler-case (progn (evaluate code mode) nil) (error () t)))))
    (unwind-protect
         (progn
           (ataxia.kernel:start-kernel kernel)
           (setf control (ataxia.sly-control:start-sly-control kernel :port 4307)
                 controller (a:enable world)
                 (a::assistant-controller-seat controller) (first (world-seats world)))
           (setf *expected-owner* sb-thread:*current-thread*)
           (assert (null (a::assistant-controller-worker controller)))
           (assert (find "ataxia_lisp" (a::%assistant-tool-specs world)
                         :key (lambda (tool) (gethash "name" tool)) :test #'equal))
           (setf thread
             (sb-thread:make-thread
               (lambda ()
                 (handler-case
                     (let ((generation (ataxia.kernel:kernel-world-generation kernel)))
                       (uiop:run-program (list "python3" (namestring (asdf:system-relative-pathname "ataxia-assistant" "tests/ataxia-eval.py")) "4307")
                                         :output *standard-output* :error-output *error-output*)
                       (reject "(+ 1 2)" "worker")
                       (owner (lambda () (a::%assistant-start-task controller)
                                       (assert (null (a::assistant-controller-session controller)))
                                       (assert (notany #'agent-seat-p (world-seats world)))))
                       (assert (search "3" (getf (evaluate "(+ 1 2)" "worker") :output)))
                       (assert (search "T" (getf (evaluate "(typep world 'ataxia.infinite-world:infinite-world)" "inspect") :output)))
                       (assert (search "captured" (getf (evaluate "(progn (write-string \"captured\") :ok)" "apply") :output)))
                       (assert (search "owner-value" (getf (evaluate "(make-instance 'ataxia.test.assistant-lisp::owner-print-probe)" "inspect") :output)))
                       ;; Query/act/result in one owner turn; no input seat or CUA snapshot.
                       (assert (search "T" (getf (evaluate "(let ((output (first (ataxia.world:world-outputs world)))) (ataxia.world:navigate-world-viewport world output :pan :dx 120d0 :dy 0d0) (= 1 (length (getf (ataxia.world:world-desktop-state world) :outputs))))" "inspect") :output)))
                       (owner (lambda ()
                                (assert (null (a::assistant-controller-session controller)))
                                (assert (notany #'agent-seat-p (world-seats world)))))
                       (reject "#.(error \"reader ran\")" "worker")
                       (reject "1 2" "worker")
                       (reject "(error \"contained\")" "apply")
                       (assert (= generation (ataxia.kernel:kernel-world-generation kernel)))
                       (assert (eq world (ataxia.kernel:kernel-world kernel)))
                       (let ((result (evaluate "(dotimes (i 50000) (write-char #\\x))" "worker")))
                         (assert (eq t (getf result :truncated)))
                         (assert (= 16384 (length (getf result :output)))))
                       (owner (lambda () (a:pause world)))
                       (reject "(+ 1 2)" "worker")
                       (owner (lambda ()
                                (a::%assistant-start-task controller)))
                       (assert (search "3" (getf (evaluate "(+ 1 2)" "inspect") :output)))
                       ;; Blocking native functions reject owner use without creating a seat.
                       (reject "(ataxia.agent:capture-window agent 999999)" "inspect")
                       (owner (lambda () (assert (null (a::assistant-controller-session controller)))))
                       ;; Even a missing target creates only one seat, reused until Stop.
                       (reject "(ataxia.agent:capture-window agent 999999)" "worker")
                       (let ((session (owner (lambda () (a::assistant-controller-session controller)))))
                         (owner (lambda ()
                                  (assert session)
                                  (assert (= 1 (count-if #'agent-seat-p (world-seats world))))
                                  (a:pause world)))
                         (reject "(+ 1 2)" "inspect")
                         (owner (lambda () (a::%assistant-start-task controller)))
                         (reject "(ataxia.agent:capture-window agent 999999)" "worker")
                         (owner (lambda () (assert (eq session (a::assistant-controller-session controller)))))))
                   (serious-condition (cause) (setf failure cause)))
                 (setf done t)) :name "Live Lisp test"))
           (ataxia.kernel:run-kernel kernel :run-for 6d0)
           (assert done)
           (when failure (error failure))
           (format t "PASS: portable direct World control without a seat, owner-only printing, lazy native input, bounded output, error containment and pause/resume.~%"))
      (when controller (a:disable world))
      (when control (ataxia.sly-control:stop-sly-control control))
      (ataxia.kernel:destroy-kernel kernel :test-complete)
      (when (and thread (sb-thread:thread-alive-p thread)) (sb-thread:terminate-thread thread)))))
