(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-assistant/metaworld")
(in-package #:ataxia.infinite-world)
(setf ataxia.assistant::*assistant-command* (list "env" "ATAXIA_VOICE_FIXTURE=1" "sbcl" "--noinform" "--disable-debugger" "--script"
                           (namestring (asdf:system-relative-pathname "ataxia-assistant" "tests/assistant-mock-codex.lisp")))
      ataxia.assistant::*assistant-record-command* (list "python3" "-u" "tests/assistant-audio-fixture.py" "record")
      ataxia.assistant::*assistant-play-command* (list "python3" "-u" "tests/assistant-audio-fixture.py" "play" "/tmp/ataxia-voice-fixture.pcm"))
(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (control nil) (controller nil) (test-thread nil) (done nil) (failure nil))
  (labels ((owner (f) (ataxia.sly-control:agent-inspect (lambda (k w) (declare (ignore k w)) (funcall f)) :timeout 5d0))
           (wait-for (f)
             (loop repeat 160 when (owner f) do (return t) do (sleep .05d0)
                   finally (error "Timed out waiting for assistant. State: ~S / ~A"
                                  (ataxia.assistant::assistant-controller-task controller) (ataxia.assistant::assistant-controller-activity controller)))))
    (unwind-protect
         (progn
           (ataxia.kernel:start-kernel kernel)
           (setf control (ataxia.sly-control:start-sly-control kernel :port nil))
           (ataxia.world.shell:enable-rmlui-status-bar world)
           (setf controller (ataxia.assistant::%assistant-enable world :project (namestring (asdf:system-source-directory "ataxia-assistant"))))
           (ataxia.assistant::%assistant-open controller (%canvas-seat-seat (first (%seat-states world))))
           (assert (null (ataxia.assistant::assistant-controller-worker controller)))
           (assert (eq :off (ataxia.assistant::assistant-controller-microphone controller)))
           (setf test-thread
             (sb-thread:make-thread
              (lambda ()
                (handler-case
                    (progn
                      (sleep .5d0)
                      (owner (lambda () (ataxia.assistant::%assistant-submit controller "Inspect this isolated desktop.")))
                      (wait-for (lambda () (member (ataxia.assistant::assistant-controller-task controller) '(:done :failed))))
                      (owner (lambda ()
                               (assert (eq :done (ataxia.assistant::assistant-controller-task controller)) () "Assistant failed: ~A" (ataxia.assistant::assistant-controller-activity controller))
                               (assert (eq :ready (ataxia.assistant::assistant-controller-connection controller)))
                               (assert (= 1 (hash-table-count (ataxia.assistant::assistant-controller-seen-calls controller))))
                               (assert (search "<b>Safe text</b>" (getf (car (last (ataxia.assistant::assistant-controller-messages controller))) :text)))
                               (assert (eq :paused (ataxia.computer-use::computer-session-state (ataxia.assistant::assistant-controller-session controller))))
                               (ataxia.assistant::%assistant-toggle-talk controller)))
                      (wait-for (lambda () (and (eq :listening (ataxia.assistant::assistant-controller-microphone controller))
                                               (eq :done (ataxia.assistant::assistant-controller-task controller))
                                               (find "Voice fixture task" (ataxia.assistant::assistant-controller-messages controller) :key (lambda (m) (getf m :text)) :test #'equal))))
                      (sleep .15d0)
                      (let ((record (ataxia.assistant::assistant-controller-audio controller))
                            (play (ataxia.assistant::assistant-controller-audio-player controller)))
                        (owner (lambda () (ataxia.assistant::%assistant-toggle-microphone controller)))
                        (sleep .1d0)
                        (assert (not (uiop:process-alive-p record)))
                        (assert (uiop:process-alive-p play))
                        (assert (eq :muted (ataxia.assistant::assistant-controller-microphone controller)))
                        (owner (lambda () (ataxia.assistant::%assistant-toggle-microphone controller)))
                        (wait-for (lambda () (eq :listening (ataxia.assistant::assistant-controller-microphone controller)))))
                      (let ((record (ataxia.assistant::assistant-controller-audio controller))
                            (play (ataxia.assistant::assistant-controller-audio-player controller))
                            (threads (list (ataxia.assistant::assistant-controller-audio-thread controller)
                                           (ataxia.assistant::assistant-controller-audio-play-thread controller))))
                        (assert (uiop:process-alive-p record)) (assert (uiop:process-alive-p play))
                        (with-open-file (audio "/tmp/ataxia-voice-fixture.pcm" :element-type '(unsigned-byte 8)) (assert (plusp (file-length audio))))
                        (owner (lambda ()
                          ;; Voice was handed off by the server; no second turn/start was sent.
                          (assert (= 2 (ataxia.assistant::assistant-controller-turn-count controller)))
                          (assert (= 1 (count "Voice fixture task" (ataxia.assistant::assistant-controller-messages controller)
                                             :key (lambda (m) (getf m :text)) :test #'equal)))
                          (ataxia.assistant::%assistant-close-panel controller)
                          (assert (eq :off (ataxia.assistant::assistant-controller-microphone controller)))))
                        (sleep .2d0)
                        (assert (not (uiop:process-alive-p record))) (assert (not (uiop:process-alive-p play)))
                        (dolist (thread threads)
                          (sb-thread:join-thread thread :timeout 2d0 :default :stuck)
                          (assert (not (sb-thread:thread-alive-p thread)))))
                      (owner (lambda () (ataxia.assistant::%assistant-disable world)))
                      (setf done t))
                  (error (cause) (setf failure cause done t)))) :name "Assistant integration checks"))
           (ataxia.kernel:run-kernel kernel :run-for 12d0)
           (assert done)
           (when failure (error failure))
           (format t "PASS: negotiated voice with synthetic PCM, listening indicator, playback, single handoff and immediate audio cleanup.~%"))
      (when control (ataxia.sly-control:stop-sly-control control))
      (ataxia.kernel:destroy-kernel kernel :assistant-test-complete)
      (when (and test-thread (sb-thread:thread-alive-p test-thread)) (sb-thread:terminate-thread test-thread)))))
