;;;; Opt-in check of the authoring instructions with a real model and empty project.
(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-assistant/metaworld")
(in-package #:ataxia.infinite-world)
(unless (equal "1" (uiop:getenv "ATAXIA_TEST_CODEX"))
  (error "Set ATAXIA_TEST_CODEX=1 to run a real model turn."))
(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (project (merge-pathnames (format nil "ataxia-ui-codex-~A/" (ataxia.computer-use::random-token)) (uiop:temporary-directory)))
       (controller nil) (control nil) (worker nil) (done nil) (failure nil))
  (unwind-protect
       (progn
         (ensure-directories-exist project)
         (ataxia.kernel:start-kernel kernel)
         (setf control (ataxia.sly-control:start-sly-control kernel :port nil)
               controller (ataxia.assistant::%assistant-enable world :project (namestring project))
               (ataxia.assistant::assistant-controller-scope controller) :project
               (ataxia.assistant::assistant-controller-seat controller) (%canvas-seat-seat (first (%seat-states world))))
         (ataxia.assistant::%assistant-submit controller "Create a simple light-style notepad as notepad.rml in this empty project, using your built-in authoring guide and its shipped starter. Open it in its own separate process and window. Verify that I can type two lines into the editor, clear only your test text, then leave the app open. Do not add saving or other features. Finish with a short sentence.")
         (setf worker
               (sb-thread:make-thread
                (lambda ()
                  (handler-case
                      (loop repeat 1000 do
                        (when (ataxia.sly-control:agent-inspect
                               (lambda (k w)
                                 (declare (ignore k w))
                                 (when (member (ataxia.assistant::assistant-controller-task controller) '(:done :failed :needs-input))
                                   (assert (eq :done (ataxia.assistant::assistant-controller-task controller)) () "Assistant: ~A" (ataxia.assistant::assistant-controller-activity controller))
                                   (assert (probe-file (merge-pathnames "notepad.rml" project)))
                                   (assert (= 1 (hash-table-count (ataxia.assistant::assistant-controller-previews controller))))
                                   (let* ((preview (loop for p being the hash-values of (ataxia.assistant::assistant-controller-previews controller) return p))
                                          (process (ataxia.assistant::assistant-preview-process preview)))
                                     (assert (uiop:process-alive-p process))
                                     (assert (/= (sb-posix:getpid) (uiop:process-info-pid process)))
                                     (assert (find (ataxia.assistant::assistant-preview-app-id preview) (%world-stacking world)
                                                   :key (lambda (window) (ataxia.kernel:application-app-id (canvas-window-application window)))
                                                   :test #'equal)))
                                   (assert (>= (ataxia.assistant::assistant-controller-tool-count controller) 3))
                                   (format t "PASS: real Codex followed the authoring guide, created notepad.rml, opened a separate app process/window and tested it.~%")
                                   t)) :timeout 5d0)
                          (setf done t) (return))
                        (sleep .1d0)
                        finally (error "UI authoring test timed out: ~A" (ataxia.assistant::assistant-controller-activity controller)))
                    (error (cause) (setf failure cause done t))))
                :name "Real Codex UI authoring test"))
         (ataxia.kernel:run-kernel kernel :run-for 115d0)
         (assert done)
         (when failure (error failure)))
    (when controller (ataxia.assistant::%assistant-disable world))
    (when control (ataxia.sly-control:stop-sly-control control))
    (ataxia.kernel:destroy-kernel kernel :assistant-ui-codex-test-complete)
    (when (and worker (sb-thread:thread-alive-p worker)) (sb-thread:terminate-thread worker))
    (uiop:delete-directory-tree project :validate t :if-does-not-exist :ignore)))
