(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-assistant/metaworld")
(load (merge-pathnames "assistant-voice-fixture.lisp" *load-truename*))
(in-package #:ataxia.infinite-world)
(setf ataxia.assistant::*assistant-command* (list "sbcl" "--noinform" "--disable-debugger" "--script"
                           (namestring (asdf:system-relative-pathname "ataxia-assistant" "tests/assistant-mock-codex.lisp"))))
(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (control nil) (controller nil) (test-thread nil) (done nil) (failure nil))
  (labels ((key (symbol modifiers)
             (let ((seat (%canvas-seat-seat (first (%seat-states world)))))
               (dolist (state '(:pressed :released))
                 (ataxia.kernel:world-key-event world seat
                   (ataxia.kernel:make-key-input :keycode 30 :keysyms (vector symbol) :modifiers modifiers :state state)))))
           (owner (f) (ataxia.sly-control:agent-inspect (lambda (k w) (declare (ignore k w)) (funcall f)) :timeout 5d0))
           (wait-for (f)
             (loop repeat 160 when (owner f) do (return t) do (sleep .05d0)
                   finally (error "Timed out waiting for assistant. State: ~S / ~A"
                                  (ataxia.assistant::assistant-controller-task controller) (ataxia.assistant::assistant-controller-activity controller)))))
    (unwind-protect
         (progn
           (ataxia.kernel:start-kernel kernel)
           (setf control (ataxia.sly-control:start-sly-control kernel :port nil))
           (ataxia.world.shell:enable-rmlui-status-bar world)
           (setf controller (ataxia.assistant::%assistant-enable world :project (namestring (asdf:system-source-directory "ataxia-assistant"))))
           (%meta-present-ui world (%meta-toolbar world (%first-output-state world)) t)
           (key "a" '(:logo))
           (assert (ataxia.assistant::assistant-controller-panel controller))
           ;; Escape must win over the existing Metaworld dismiss shortcut.
           (key "Escape" nil)
           (assert (null (ataxia.assistant::assistant-controller-panel controller)))
           (%meta-dismiss-menu world)
           (key "a" '(:logo))
           (assert (null (ataxia.assistant::assistant-controller-worker controller)))
           (assert (eq :off (ataxia.assistant::assistant-controller-microphone controller)))
           (ataxia.world.rmlui:set-rmlui-model (canvas-overlay-component (ataxia.assistant::assistant-controller-panel controller)) "message" "Keep this draft")
           (let ((overlays (length (world-overlays world))))
             (ataxia.assistant::%assistant-open-settings controller)
             (assert (= overlays (length (world-overlays world)))))
           (assert (ataxia.assistant::%assistant-settings-open-p controller))
           (assert (null (ataxia.assistant::assistant-controller-session controller)))
           (assert (eq (%canvas-seat-focused (first (%seat-states world))) (ataxia.assistant::assistant-controller-panel controller)))
           (key "Escape" nil)
           (assert (null (ataxia.assistant::%assistant-settings-open-p controller)))
           (assert (ataxia.assistant::assistant-controller-panel controller))
           (assert (equal "Keep this draft" (ataxia.assistant::%assistant-read-composer controller)))
           (assert (eq (%canvas-seat-focused (first (%seat-states world))) (ataxia.assistant::assistant-controller-panel controller)))
           (setf test-thread
             (sb-thread:make-thread
              (lambda ()
                (handler-case
                    (progn
                      (sleep .5d0)
                      (owner (lambda ()
                               (ataxia.world.rmlui:set-rmlui-model
                                (overlay-component (ataxia.assistant::assistant-controller-panel controller))
                                "message" "Inspect this isolated desktop.")
                               (key "Return" '(:control))
                               (assert (equal "" (ataxia.assistant::%assistant-read-composer controller)))))
                      (wait-for (lambda () (member (ataxia.assistant::assistant-controller-task controller) '(:done :failed))))
                      (owner (lambda ()
                               (assert (eq :done (ataxia.assistant::assistant-controller-task controller)) () "Assistant failed: ~A" (ataxia.assistant::assistant-controller-activity controller))
                               (assert (eq :ready (ataxia.assistant::assistant-controller-connection controller)))
                               (assert (= 1 (hash-table-count (ataxia.assistant::assistant-controller-seen-calls controller))))
                               (assert (search "<b>Safe text</b>" (getf (car (last (ataxia.assistant::assistant-controller-messages controller))) :text)))
                               (assert (eq :paused (ataxia.computer-use::computer-session-state (ataxia.assistant::assistant-controller-session controller))))
                               (assert (= 2 (length (ataxia.assistant::assistant-controller-models controller))))
                               (ataxia.assistant::%assistant-select-model controller "fixture-fast")
                               (ataxia.assistant::%assistant-submit controller "MODEL:fast")))
                      (wait-for (lambda () (member (ataxia.assistant::assistant-controller-task controller) '(:done :failed))))
                      (owner (lambda ()
                               (assert (eq :done (ataxia.assistant::assistant-controller-task controller)))
                               (assert (equal "fixture-fast" (ataxia.assistant::assistant-model-selection-active (ataxia.assistant::assistant-controller-model-selection controller))))
                               (assert (equal "fixture-thread" (ataxia.assistant::assistant-controller-thread-id controller)))
                               (ataxia.assistant::%assistant-select-model controller "")
                               (ataxia.assistant::%assistant-submit controller "MODEL:default")))
                      (wait-for (lambda () (member (ataxia.assistant::assistant-controller-task controller) '(:done :failed))))
                      (owner (lambda ()
                               (assert (eq :done (ataxia.assistant::assistant-controller-task controller)))
                               (assert (equal "fixture-default" (ataxia.assistant::assistant-model-selection-active (ataxia.assistant::assistant-controller-model-selection controller))))
                               (assert (= 3 (ataxia.assistant::assistant-controller-turn-count controller)))
                               (ataxia.assistant::%assistant-select-effort controller "high")
                               (ataxia.assistant::%assistant-toggle-fast controller)
                               (ataxia.assistant::%assistant-submit controller "SETTINGS:high-fast")))
                      (wait-for (lambda () (member (ataxia.assistant::assistant-controller-task controller) '(:done :failed))))
                      (owner (lambda ()
                               (assert (eq :done (ataxia.assistant::assistant-controller-task controller)))
                               (assert (equal "high" (ataxia.assistant::assistant-generation-settings-active-effort (ataxia.assistant::assistant-controller-generation-settings controller))))
                               (assert (equal "priority" (ataxia.assistant::assistant-generation-settings-active-tier (ataxia.assistant::assistant-controller-generation-settings controller))))
                               (ataxia.assistant::%assistant-select-effort controller "")
                               (ataxia.assistant::%assistant-toggle-fast controller)
                               (ataxia.assistant::%assistant-submit controller "SETTINGS:reset")))
                      (wait-for (lambda () (member (ataxia.assistant::assistant-controller-task controller) '(:done :failed))))
                      (owner (lambda ()
                               (assert (eq :done (ataxia.assistant::assistant-controller-task controller)))
                               (assert (equal "medium" (ataxia.assistant::assistant-generation-settings-active-effort (ataxia.assistant::assistant-controller-generation-settings controller))))
                               (assert (equal "default" (ataxia.assistant::assistant-generation-settings-active-tier (ataxia.assistant::assistant-controller-generation-settings controller))))))
                      (let ((worker (ataxia.assistant::assistant-controller-worker controller))
                            (reader (ataxia.assistant::assistant-controller-reader controller))
                            (wake (ataxia.assistant::assistant-controller-wake controller)))
                        (owner (lambda () (ataxia.assistant::%assistant-reset-conversation controller)
                                          (ataxia.assistant::%assistant-connect controller)))
                        (wait-for (lambda () (eq :ready (ataxia.assistant::assistant-controller-connection controller))))
                        (dolist (thread (list worker reader))
                          (sb-thread:join-thread thread :timeout 2d0 :default :stuck)
                          (assert (not (sb-thread:thread-alive-p thread))))
                        (assert (not (eq wake (ataxia.assistant::assistant-controller-wake controller)))))
                      (owner (lambda () (key "A" '(:logo :shift))))
                      (wait-for (lambda () (and (eq :off (ataxia.assistant::assistant-controller-microphone controller))
                                                (search "Voice unavailable" (ataxia.assistant::assistant-controller-activity controller)))))
                      (owner (lambda ()
                               (assert (null (ataxia.assistant::assistant-controller-audio controller)))
                               (ataxia.assistant::%assistant-pause controller)
                               (assert (ataxia.assistant::assistant-controller-blocked controller))
                               (ataxia.assistant::%assistant-open-settings controller)
                               (ataxia.assistant::%assistant-close-panel controller)
                               (assert (null (ataxia.assistant::%assistant-settings-open-p controller)))
                               (assert (null (ataxia.assistant::assistant-controller-panel controller)))
                               (ataxia.assistant::%assistant-disable world)
                               (assert (null (ataxia.world:world-service world :assistant)))
                               (assert (eq :running (ataxia.kernel:kernel-world-status kernel)))))
                      (setf done t))
                  (error (cause) (setf failure cause done t)))) :name "Assistant integration checks"))
           (ataxia.kernel:run-kernel kernel :run-for 12d0)
           (assert done)
           (when failure (error failure))
           (format t "PASS: readable panel, local settings without extra overlays, focus/Escape/draft/cleanup, model/effort/Fast selection and reset, tool, streaming and voice cleanup.~%"))
      (when control (ataxia.sly-control:stop-sly-control control))
      (ataxia.kernel:destroy-kernel kernel :assistant-test-complete)
      (when (and test-thread (sb-thread:thread-alive-p test-thread)) (sb-thread:terminate-thread test-thread)))))
