(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-assistant/metaworld")
(in-package #:ataxia.infinite-world)
(defun assistant-test-rejects (function)
  (assert (handler-case (progn (funcall function) nil) (error () t))))

;; The public computer-use parser retains its original bounds.
(let ((nested "[[[[[[[[[[0]]]]]]]]]]"))
  (assistant-test-rejects (lambda () (ataxia.world.wire:decode nested)))
  (assert (vectorp (ataxia.world.wire:decode nested :max-depth 32))))
(loop for text in '("" "f" "fo" "foo" "foob" "fooba" "foobar")
      for encoded in '("" "Zg==" "Zm8=" "Zm9v" "Zm9vYg==" "Zm9vYmE=" "Zm9vYmFy")
      do (assert (equal encoded (ataxia.assistant::%assistant-base64 (sb-ext:string-to-octets text)))))
(let* ((controller (ataxia.assistant::%make-assistant-controller
                    :models (vector (ataxia.assistant::%assistant-object "model" "fast" "defaultReasoningEffort" "low")
                                    (ataxia.assistant::%assistant-object "model" "hidden" "hidden" t))))
       (state (ataxia.assistant::assistant-controller-model-selection controller)))
  (setf (ataxia.assistant::assistant-model-selection-default state) "configured"
        (ataxia.assistant::assistant-model-selection-default-effort state) "high"
        (ataxia.assistant::assistant-model-selection-active state) "configured")
  (assistant-test-rejects (lambda () (ataxia.assistant::%assistant-select-model controller "hidden")))
  (assistant-test-rejects (lambda () (ataxia.assistant::%assistant-select-model controller "unknown")))
  (ataxia.assistant::%assistant-select-model controller "fast")
  (assert (equal '("fast" "low" t "default") (multiple-value-list (ataxia.assistant::%assistant-model-turn-settings controller))))
  (assert (equal "configured" (ataxia.assistant::assistant-model-selection-active state)))
  (setf (ataxia.assistant::assistant-model-selection-active state) "fast")
  (ataxia.assistant::%assistant-select-model controller "")
  (assert (equal '("configured" "high" t "default") (multiple-value-list (ataxia.assistant::%assistant-model-turn-settings controller)))))
(let* ((controller (ataxia.assistant::%make-assistant-controller
                    :models (vector
                             (ataxia.assistant::%assistant-object "model" "full" "supportedReasoningEfforts" (vector (ataxia.assistant::%assistant-object "reasoningEffort" "ultra"))
                                                "serviceTiers" (vector (ataxia.assistant::%assistant-object "id" "priority" "name" "Fast")))
                             (ataxia.assistant::%assistant-object "model" "small" "defaultReasoningEffort" "low"
                                                "supportedReasoningEfforts" (vector (ataxia.assistant::%assistant-object "reasoningEffort" "low"))))))
       (settings (ataxia.assistant::assistant-controller-generation-settings controller)))
  (ataxia.assistant::%assistant-select-model controller "full")
  (ataxia.assistant::%assistant-select-effort controller "ultra")
  (ataxia.assistant::%assistant-toggle-fast controller)
  (assert (equal "priority" (ataxia.assistant::%assistant-effective-tier controller)))
  (ataxia.assistant::%assistant-select-model controller "small")
  (assert (null (ataxia.assistant::assistant-generation-settings-effort settings)))
  (assert (equal "default" (ataxia.assistant::%assistant-effective-tier controller)))
  (assistant-test-rejects (lambda () (ataxia.assistant::%assistant-select-effort controller "ultra")))
  (assistant-test-rejects (lambda () (ataxia.assistant::%assistant-toggle-fast controller)))
  (ataxia.assistant::%assistant-select-model controller "full")
  (assert (equal "priority" (ataxia.assistant::%assistant-effective-tier controller)))
  (ataxia.assistant::%assistant-toggle-fast controller)
  (assert (equal "default" (ataxia.assistant::%assistant-effective-tier controller))))
(let* ((tools (ataxia.assistant::%assistant-tool-specs (make-metaworld :state-file nil)))
       (decoded (ataxia.world.wire:decode (ataxia.world.wire:encode tools) :max-depth 32)))
  (assert (= 3 (length decoded)))
  (assert (equal '("ataxia_lisp" "ataxia_ui_preview" "ataxia_ui_update")
                 (map 'list (lambda (tool) (gethash "name" tool)) decoded)))
  (loop for tool across decoded do (assert (gethash "inputSchema" tool)) (assert (equal "function" (gethash "type" tool)))))

(let ((controller (ataxia.assistant::%make-assistant-controller :epoch 2 :blocked t)))
  (assistant-test-rejects (lambda () (ataxia.assistant::%assistant-require-task controller)))
  (assert (null (ataxia.assistant::%assistant-queue controller :submit "stale" 5 1)))
  (assert (null (ataxia.assistant::assistant-controller-queue controller))))
(format t "PASS: parser isolation, image encoding, tool schemas, paused task and stale mailbox events.~%")

(let* ((result (ataxia.assistant::%assistant-object "success" t "contentItems"
                 (vector (ataxia.assistant::%assistant-object "type" "inputImage" "imageUrl" "data:image/png;base64,fixture")
                         (ataxia.assistant::%assistant-object "type" "inputText" "text" "completed once"))))
       (cached (ataxia.assistant::%assistant-cache-result result)))
  (assert (= 1 (length (gethash "contentItems" cached))))
  (assert (equal "completed once" (ataxia.assistant::%assistant-field (aref (gethash "contentItems" cached) 0) "text")))
  (assert (= 2 (length (gethash "contentItems" result)))))

;; Layout batches validate before mutation; failures roll back immediately.
(let* ((world (make-metaworld :state-file nil))
       (group (first (metaworld-subworlds world)))
       (delete (ataxia.assistant::%assistant-object "op" "remove-group" "group" (subworld-id group))))
  (dolist (operations (list (vector delete delete)
                           (vector delete (ataxia.assistant::%assistant-object "op" "configure-group" "group" (subworld-id group) "name" "Too late"))
                           (vector (ataxia.assistant::%assistant-object "op" "remove-group"))
                           (vector (ataxia.assistant::%assistant-object "op" "remove-group" "group" 999999))))
    (assistant-test-rejects (lambda () (ataxia.world:apply-world-layout world operations)))
    (assert (member group (metaworld-subworlds world))))
  (setf (%meta-standalone world) :niri)
  (assistant-test-rejects (lambda () (ataxia.world:apply-world-layout world (vector delete))))
  (setf (%meta-standalone world) nil)
  (ataxia.world:apply-world-layout world (vector delete))
  (assert (not (member group (metaworld-subworlds world)))))

(let* ((world (make-metaworld :state-file nil))
       (group (first (metaworld-subworlds world))) (saved (ataxia.world:world-desktop-state world))
       (operations (vector (ataxia.assistant::%assistant-object "op" "remove-group" "group" (subworld-id group))
                           (ataxia.assistant::%assistant-object "op" "create-group" "ref" "failure" "name" "Failure" "policy" "niri")))
       (original (symbol-function '%desktop-apply-operation)))
  (unwind-protect
       (progn
         (setf (symbol-function '%desktop-apply-operation)
               (lambda (target-world operation aliases)
                 (when (equal "create-group" (gethash "op" operation)) (error "Injected transaction failure"))
                 (funcall original target-world operation aliases)))
         (assistant-test-rejects (lambda () (ataxia.world:apply-world-layout world operations))))
    (setf (symbol-function '%desktop-apply-operation) original))
  (assert (equalp saved (ataxia.world:world-desktop-state world))))
(format t "PASS: direct layout changes, complete validation and atomic failure rollback.~%")

(let* ((world (make-metaworld :state-file nil))
       (controller (ataxia.assistant::%make-assistant-controller :world world :messages (list (list :role :you :text "Remove Studio")))))
  (ataxia.assistant::%assistant-refresh-tools controller)
  (assert (equal "Remove Studio" (getf (first (ataxia.assistant::assistant-controller-messages controller)) :text)))
  (assert (search "Remove Studio" (ataxia.assistant::assistant-controller-refresh-context controller)))
  (assert (eq :offline (ataxia.assistant::assistant-controller-connection controller)))
  (ataxia.assistant::%assistant-reset-conversation controller)
  (assert (not (ataxia.assistant::assistant-controller-refresh-context controller))))
