(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-assistant/metaworld")
(in-package #:ataxia.infinite-world)
(defun assistant-test-rejects (function)
  (assert (handler-case (progn (funcall function) nil) (error () t))))

;; The public computer-use parser retains its original bounds.
(let ((nested "[[[[[[[[[[0]]]]]]]]]]"))
  (assistant-test-rejects (lambda () (ataxia.computer-use.wire:decode nested)))
  (assert (vectorp (ataxia.computer-use.wire:decode nested :max-depth 32))))
(loop for text in '("" "f" "fo" "foo" "foob" "fooba" "foobar")
      for encoded in '("" "Zg==" "Zm8=" "Zm9v" "Zm9vYg==" "Zm9vYmE=" "Zm9vYmFy")
      do (assert (equal encoded (ataxia.assistant::%assistant-base64 (sb-ext:string-to-octets text)))))
(let* ((controller (ataxia.assistant::%make-assistant-controller
                    :models (vector (ataxia.assistant::%assistant-object "model" "fast" "defaultReasoningEffort" "low")
                                    (ataxia.assistant::%assistant-object "model" "hidden" "hidden" t))))
       (state (ataxia.assistant::assistant-controller-model-selection controller)))
  (setf (ataxia.assistant::assistant-model-selection-default state) "configured"
        (ataxia.assistant::assistant-model-selection-default-effort state) "high"
        (ataxia.assistant::assistant-model-selection-active state) "configured")
  (assistant-test-rejects (lambda () (ataxia.assistant::%assistant-select-model controller "hidden")))
  (assistant-test-rejects (lambda () (ataxia.assistant::%assistant-select-model controller "unknown")))
  (ataxia.assistant::%assistant-select-model controller "fast")
  (assert (equal '("fast" "low" t "default") (multiple-value-list (ataxia.assistant::%assistant-model-turn-settings controller))))
  (assert (equal "configured" (ataxia.assistant::assistant-model-selection-active state)))
  (setf (ataxia.assistant::assistant-model-selection-active state) "fast")
  (ataxia.assistant::%assistant-select-model controller "")
  (assert (equal '("configured" "high" t "default") (multiple-value-list (ataxia.assistant::%assistant-model-turn-settings controller)))))
(let* ((controller (ataxia.assistant::%make-assistant-controller
                    :models (vector
                             (ataxia.assistant::%assistant-object "model" "full" "supportedReasoningEfforts" (vector (ataxia.assistant::%assistant-object "reasoningEffort" "ultra"))
                                                "serviceTiers" (vector (ataxia.assistant::%assistant-object "id" "priority" "name" "Fast")))
                             (ataxia.assistant::%assistant-object "model" "small" "defaultReasoningEffort" "low"
                                                "supportedReasoningEfforts" (vector (ataxia.assistant::%assistant-object "reasoningEffort" "low"))))))
       (settings (ataxia.assistant::assistant-controller-generation-settings controller)))
  (ataxia.assistant::%assistant-select-model controller "full")
  (ataxia.assistant::%assistant-select-effort controller "ultra")
  (ataxia.assistant::%assistant-toggle-fast controller)
  (assert (equal "priority" (ataxia.assistant::%assistant-effective-tier controller)))
  (ataxia.assistant::%assistant-select-model controller "small")
  (assert (null (ataxia.assistant::assistant-generation-settings-effort settings)))
  (assert (equal "default" (ataxia.assistant::%assistant-effective-tier controller)))
  (assistant-test-rejects (lambda () (ataxia.assistant::%assistant-select-effort controller "ultra")))
  (assistant-test-rejects (lambda () (ataxia.assistant::%assistant-toggle-fast controller)))
  (ataxia.assistant::%assistant-select-model controller "full")
  (assert (equal "priority" (ataxia.assistant::%assistant-effective-tier controller)))
  (ataxia.assistant::%assistant-toggle-fast controller)
  (assert (equal "default" (ataxia.assistant::%assistant-effective-tier controller))))
(let* ((tools (ataxia.assistant::%assistant-tool-specs (make-metaworld :state-file nil)))
       (decoded (ataxia.computer-use.wire:decode (ataxia.computer-use.wire:encode tools) :max-depth 32)))
  (assert (= 10 (length decoded)))
  (loop for tool across decoded do (assert (gethash "inputSchema" tool)) (assert (equal "function" (gethash "type" tool)))))

(let* ((world (make-metaworld :state-file nil))
       (controller (ataxia.assistant::%make-assistant-controller :world world :grant (list :layout t) :blocked nil))
       (group (first (metaworld-subworlds world)))
       (name (subworld-name group))
       (before (ataxia.assistant::%assistant-layout-snapshot controller))
       (op (ataxia.assistant::%assistant-object "op" "configure-group" "group" (subworld-id group) "name" "Test arrangement"))
       (plan (ataxia.assistant::%assistant-layout-preview controller (ataxia.assistant::%assistant-object "revision" (getf before :revision) "operations" (vector op)))))
  (assert (equal name (subworld-name group)))
  (let ((result (ataxia.assistant::%assistant-layout-apply controller (ataxia.assistant::%assistant-object "plan" (getf plan :plan)))))
    (assert (equal "Test arrangement" (subworld-name group)))
    (assert (eq result (ataxia.assistant::%assistant-layout-apply controller (ataxia.assistant::%assistant-object "plan" (getf plan :plan)))))
    (ataxia.assistant::%assistant-layout-undo controller (getf result :undo))
    (assert (equal name (subworld-name group))))
  ;; Preview rejects an intervening edit, and Undo independently does the same.
  (let* ((revision (ataxia.assistant::%assistant-layout-revision controller))
         (plan (ataxia.assistant::%assistant-layout-preview controller (ataxia.assistant::%assistant-object "revision" revision "operations" (vector op)))))
    (setf (subworld-name group) "Human edit")
    (assistant-test-rejects (lambda () (ataxia.assistant::%assistant-layout-apply controller (ataxia.assistant::%assistant-object "plan" (getf plan :plan)))))
    (assert (equal "Human edit" (subworld-name group))))
  (let* ((plan (ataxia.assistant::%assistant-layout-preview controller (ataxia.assistant::%assistant-object "revision" (ataxia.assistant::%assistant-layout-revision controller) "operations" (vector op))))
         (result (ataxia.assistant::%assistant-layout-apply controller (ataxia.assistant::%assistant-object "plan" (getf plan :plan)))))
    (setf (subworld-name group) "Later human edit")
    (assistant-test-rejects (lambda () (ataxia.assistant::%assistant-layout-undo controller (getf result :undo))))
    (assert (equal "Later human edit" (subworld-name group))))
  (setf (ataxia.assistant::assistant-controller-blocked controller) t)
  (assistant-test-rejects (lambda () (ataxia.assistant::%assistant-layout-preview controller (ataxia.assistant::%assistant-object "revision" (ataxia.assistant::%assistant-layout-revision controller) "operations" (vector op)))))
  (setf (ataxia.assistant::assistant-controller-epoch controller) 2)
  (assert (null (ataxia.assistant::%assistant-queue controller :submit "stale" 5 1)))
  (assert (null (ataxia.assistant::assistant-controller-queue controller))))
(format t "PASS: parser isolation, image encoding, tool schemas, preview/apply/Undo revisions, paused grants and stale mailbox events.~%")

;; Model-visible action schemas agree with the executor's distinct fields and
;; seconds-based bounds, rather than suggesting x/y on a button action.
(let* ((world (make-metaworld :state-file nil))
       (schema (ataxia.assistant::%assistant-action-schema world :ataxia))
       (branches (gethash "anyOf" schema)))
  (labels ((branch (op)
             (find op branches :test #'equal
                   :key (lambda (item) (aref (ataxia.assistant::%assistant-field item "properties" "op" "enum") 0)))))
    (assert (= (length branches) (length ataxia.computer-use:+batch-action-fields+)))
    (loop for (op . fields) in ataxia.computer-use:+batch-action-fields+
          for properties = (gethash "properties" (branch op)) do
            (assert (= (hash-table-count properties) (1+ (length fields))))
            (dolist (field fields) (assert (gethash (string-downcase (symbol-name field)) properties))))
    (assert (not (ataxia.assistant::%assistant-field (branch "button") "properties" "x")))
    (assert (= 2 (ataxia.assistant::%assistant-field (branch "wait-stable") "properties" "settle" "maximum")))
    (assert (= 16000 (ataxia.assistant::%assistant-field (branch "paste") "properties" "text" "maxLength")))
    (dolist (scope '(:project :application))
      (assert (not (find "launch" (gethash "anyOf" (ataxia.assistant::%assistant-action-schema world scope))
                         :test #'equal :key (lambda (item) (aref (ataxia.assistant::%assistant-field item "properties" "op" "enum") 0))))))))

(let* ((result (ataxia.assistant::%assistant-object "success" t "contentItems"
                 (vector (ataxia.assistant::%assistant-object "type" "inputImage" "imageUrl" "data:image/png;base64,fixture")
                         (ataxia.assistant::%assistant-object "type" "inputText" "text" "completed once"))))
       (cached (ataxia.assistant::%assistant-cache-result result)))
  (assert (= 1 (length (gethash "contentItems" cached))))
  (assert (equal "completed once" (ataxia.assistant::%assistant-field (aref (gethash "contentItems" cached) 0) "text")))
  (assert (= 2 (length (gethash "contentItems" result)))))

;; Deletion is a validated, reversible layout operation, including empty groups.
(let* ((world (make-metaworld :state-file nil))
       (controller (ataxia.assistant::%make-assistant-controller :world world :grant (list :layout t) :blocked nil))
       (group (first (metaworld-subworlds world))) (saved (ataxia.world:world-desktop-state world))
       (delete (ataxia.assistant::%assistant-object "op" "remove-group" "group" (subworld-id group))))
  (let* ((plan (ataxia.assistant::%assistant-layout-preview controller (ataxia.assistant::%assistant-object "revision" (ataxia.assistant::%assistant-layout-revision controller) "operations" (vector delete))))
         (result (ataxia.assistant::%assistant-layout-apply controller (ataxia.assistant::%assistant-object "plan" (getf plan :plan)))))
    (assert (not (member group (metaworld-subworlds world))))
    (assert (eq result (ataxia.assistant::%assistant-layout-apply controller (ataxia.assistant::%assistant-object "plan" (getf plan :plan)))))
    (ataxia.assistant::%assistant-layout-undo controller (getf result :undo))
    (assert (equalp saved (ataxia.world:world-desktop-state world))))
  (dolist (operations (list (vector delete delete)
                           (vector delete (ataxia.assistant::%assistant-object "op" "configure-group" "group" (subworld-id group) "name" "Too late"))
                           (vector (ataxia.assistant::%assistant-object "op" "remove-group"))
                           (vector (ataxia.assistant::%assistant-object "op" "remove-group" "group" 999999))))
    (assistant-test-rejects (lambda () (ataxia.world:validate-world-layout world operations (getf (ataxia.assistant::assistant-controller-grant controller) :windows)))))
  (setf (%meta-standalone world) :niri)
  (assistant-test-rejects (lambda () (ataxia.world:validate-world-layout world (vector delete) (getf (ataxia.assistant::assistant-controller-grant controller) :windows)))))
(format t "PASS: sub-world deletion, Undo, replay and stale/invalid group references.~%")

;; A failure after removal rolls the entire plan back, including earlier operations.
(let* ((world (make-metaworld :state-file nil))
       (controller (ataxia.assistant::%make-assistant-controller :world world :grant (list :layout t) :blocked nil))
       (group (first (metaworld-subworlds world))) (saved (ataxia.world:world-desktop-state world))
       (plan (ataxia.assistant::%assistant-layout-preview controller (ataxia.assistant::%assistant-object "revision" (ataxia.assistant::%assistant-layout-revision controller)
                 "operations" (vector (ataxia.assistant::%assistant-object "op" "remove-group" "group" (subworld-id group))
                                      (ataxia.assistant::%assistant-object "op" "create-group" "ref" "failure" "name" "Failure" "policy" "niri")))))
       (original (symbol-function '%desktop-apply-operation)))
  (unwind-protect
       (progn
         (setf (symbol-function '%desktop-apply-operation)
               (lambda (target-world operation aliases allowed-window-ids)
                 (when (equal "create-group" (gethash "op" operation)) (error "Injected transaction failure"))
                 (funcall original target-world operation aliases allowed-window-ids)))
         (assistant-test-rejects (lambda () (ataxia.assistant::%assistant-layout-apply controller (ataxia.assistant::%assistant-object "plan" (getf plan :plan))))))
    (setf (symbol-function '%desktop-apply-operation) original))
  (assert (equalp saved (ataxia.world:world-desktop-state world))))

(let* ((world (make-metaworld :state-file nil))
       (controller (ataxia.assistant::%make-assistant-controller :world world :messages (list (list :role :you :text "Remove Studio")))))
  (ataxia.assistant::%assistant-refresh-tools controller)
  (assert (equal "Remove Studio" (getf (first (ataxia.assistant::assistant-controller-messages controller)) :text)))
  (assert (search "Remove Studio" (ataxia.assistant::assistant-controller-refresh-context controller)))
  (assert (eq :offline (ataxia.assistant::assistant-controller-connection controller)))
  (ataxia.assistant::%assistant-reset-conversation controller)
  (assert (not (ataxia.assistant::assistant-controller-refresh-context controller))))
