;;;; Exercise the public window tool against real Wayland clients.
(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-assistant/metaworld")
(in-package #:ataxia.infinite-world)
(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (project (merge-pathnames (format nil "ataxia-window-test-~A/" (ataxia.computer-use::random-token)) (uiop:temporary-directory)))
       (control nil) (controller nil) (worker nil) (done nil) (failure nil))
  (labels ((owner (f)
             (ataxia.sly-control:agent-inspect (lambda (k w) (declare (ignore k w)) (funcall f)) :timeout 5d0))
           (action (id op)
             (ataxia.assistant::%assistant-run-tool controller "ataxia_window" (ataxia.assistant::%assistant-object "window" id "action" op)))
           (rejects (f)
             (assert (handler-case (progn (funcall f) nil) (error () t))))
           (window (id)
             (find id (%world-stacking world) :key (lambda (w) (ataxia.kernel:object-id (canvas-window-application w)))))
           (snapshot-window (result id)
             (find id (getf (getf result :snapshot) :windows) :key (lambda (w) (getf w :id)))))
    (unwind-protect
         (progn
           (ensure-directories-exist project)
           (with-open-file (out (merge-pathnames "app.rml" project) :direction :output)
             (write-string "<rml><head><title>Window controls test</title><style>body {font-family:DejaVu Sans;background:#ffffff;}</style></head><body>Window controls test</body></rml>" out))
           (ataxia.kernel:start-kernel kernel)
           (setf control (ataxia.sly-control:start-sly-control kernel :port nil)
                 controller (ataxia.assistant::%assistant-enable world :project (namestring project))
                 (ataxia.assistant::assistant-controller-scope controller) :project
                 (ataxia.assistant::assistant-controller-seat controller) (%canvas-seat-seat (first (%seat-states world))))
           (ataxia.assistant::%assistant-grant controller)
           (setf worker
                 (sb-thread:make-thread
                  (lambda ()
                    (handler-case
                        (let* ((first (ataxia.assistant::%assistant-preview controller (ataxia.assistant::%assistant-object "path" "app.rml" "width" 640 "height" 400)))
                               (second (ataxia.assistant::%assistant-preview controller (ataxia.assistant::%assistant-object "path" "app.rml" "width" 500 "height" 300)))
                               (id (getf first :window)) (other-id (getf second :window))
                               (preview (gethash (getf first :preview) (ataxia.assistant::assistant-controller-previews controller)))
                               (other (gethash (getf second :preview) (ataxia.assistant::assistant-controller-previews controller))))
                          ;; Project scope cannot control a client it does not own.
                          (rejects (lambda () (ataxia.assistant::%assistant-run-tool controller "ataxia_viewport"
                                                (ataxia.assistant::%assistant-object "output" 1 "action" "pan" "dx" 1 "dy" 0 "revision" 1))))
                          (owner (lambda () (remhash (getf second :preview) (ataxia.assistant::assistant-controller-previews controller))))
                          (rejects (lambda () (action other-id "close")))
                          (owner (lambda () (setf (gethash (getf second :preview) (ataxia.assistant::assistant-controller-previews controller)) other)))
                          (rejects (lambda () (action id "kill")))
                          (rejects (lambda () (action nil "close")))
                          ;; A blocked task cannot close even its own window.
                          (owner (lambda () (setf (ataxia.assistant::assistant-controller-blocked controller) t)))
                          (rejects (lambda () (action id "close")))
                          (owner (lambda () (setf (ataxia.assistant::assistant-controller-blocked controller) nil)))
                          ;; Selected-app scope applies to explicit controls as well as input.
                          (owner (lambda ()
                                   (setf (ataxia.assistant::assistant-controller-scope controller) :application
                                         (getf (ataxia.assistant::assistant-controller-grant controller) :window) id)))
                          (rejects (lambda () (action other-id "close")))
                          (assert (eq t (getf (snapshot-window (action id "minimize") id) :minimized)))
                          (action id "restore")
                          (owner (lambda ()
                                   (setf (ataxia.assistant::assistant-controller-scope controller) :desktop)
                                   (ataxia.assistant::%assistant-grant controller)
                                   (%focus-target world (first (%seat-states world)) (window other-id))))
                          ;; The viewport tool uses assistant revisions and the same native grant.
                          (let* ((arguments
                                   (owner (lambda ()
                                            (ataxia.assistant::%assistant-object
                                             "output" (ataxia.kernel:object-id (first (ataxia.world:world-outputs world)))
                                             "action" "set" "x" -2000 "y" 500 "zoom" .75d0 "rotation" .2d0
                                             "revision" (ataxia.assistant::%assistant-layout-revision controller)))))
                                 (result (ataxia.assistant::%assistant-run-tool controller "ataxia_viewport" arguments)))
                            (assert (equalp #(-2000d0 500d0 .75d0 .2d0) (getf (aref (getf result :outputs) 0) :camera)))
                            (rejects (lambda () (ataxia.assistant::%assistant-run-tool controller "ataxia_viewport" arguments)))
                            (owner (lambda ()
                                     (assert (eq (window other-id) (%canvas-seat-focused (first (%seat-states world))))))))
                          ;; Minimized windows stay out of both tilers after another layout pass.
                          (dolist (kind '(:niri :hyprland))
                            (owner (lambda ()
                                     (let ((group (first (metaworld-subworlds world))))
                                       (setf (subworld-kind group) kind)
                                       (move-object-to-subworld world (window id) group))))
                            (action id "fullscreen")
                            (owner (lambda ()
                                     (assert (eq (window other-id) (%canvas-seat-focused (first (%seat-states world)))))
                                     (assert (eq (window id) (subworld-fullscreen (object-subworld world (window id)))))))
                            (action id "minimize")
                            (sleep .3d0)
                            (owner (lambda ()
                                     (let ((group (object-subworld world (window id))))
                                       (%meta-layout world group)
                                       (assert (null (subworld-fullscreen group)))
                                       (assert (not (%window-visible-p (window id))))
                                       (assert (not (%canvas-window-input-enabled-p (window id))))
                                       (assert (not (find (window id) (%meta-visible-members group :include-floating t)
                                                          :key #'subworld-member-object))))))
                            (action id "restore")
                            (sleep .3d0)
                            (owner (lambda () (assert (%window-visible-p (window id)))))
                            (action id "maximize")
                            (action id "restore"))
                          ;; Canvas expansion restores the original geometry and clears the old state.
                          (let ((geometry nil))
                            (owner (lambda ()
                                     (move-object-to-subworld world (window id) nil)
                                     (%meta-cancel-motion world (window id) :metaworld-layout)
                                     (setf geometry (%meta-object-geometry (window id)))))
                            (assert (eq t (getf (snapshot-window (action id "maximize") id) :maximized)))
                            (let ((state (snapshot-window (action id "fullscreen") id)))
                              (assert (eq t (getf state :fullscreen)))
                              (assert (eq :false (getf state :maximized))))
                            (action id "restore")
                            (owner (lambda () (assert (equalp geometry (%meta-object-geometry (window id)))))))
                          ;; Window controls invalidate a previously reviewed layout plan.
                          (let ((plan (owner (lambda ()
                                             (ataxia.assistant::%assistant-layout-preview controller
                                               (ataxia.assistant::%assistant-object "revision" (ataxia.assistant::%assistant-layout-revision controller)
                                                 "operations" (vector (ataxia.assistant::%assistant-object "op" "configure-group"
                                                                        "group" (subworld-id (first (metaworld-subworlds world)))
                                                                        "name" "Stale arrangement"))))))))
                            (action id "minimize")
                            (rejects (lambda () (ataxia.assistant::%assistant-run-tool controller "ataxia_layout_apply"
                                                  (ataxia.assistant::%assistant-object "plan" (getf plan :plan)))))
                            (assert (eq :false (getf (snapshot-window (action id "restore") id) :minimized))))
                          ;; The close request reaches the real client, which exits normally.
                          (let ((result (action id "close")))
                            (assert (equal "close-requested" (getf result :status))))
                          (loop repeat 100 until (owner (lambda () (null (window id)))) do (sleep .05d0)
                                finally (owner (lambda () (assert (null (window id))))))
                          (assert (not (uiop:process-alive-p (ataxia.assistant::assistant-preview-process preview))))
                          (assert (uiop:process-alive-p (ataxia.assistant::assistant-preview-process other)))
                          (rejects (lambda () (action id "close")))
                          (assert (uiop:process-alive-p (ataxia.assistant::assistant-preview-process other)))
                          (format t "PASS: native window controls, viewport tool and revisions, both tilers, focus preservation, scopes and stale plans/IDs.~%")
                          (setf done t))
                      (error (cause) (setf failure cause done t))))
                  :name "Assistant window controls test"))
           (ataxia.kernel:run-kernel kernel :run-for 18d0)
           (assert done)
           (when failure (error failure)))
      (when controller (ataxia.assistant::%assistant-disable world))
      (when control (ataxia.sly-control:stop-sly-control control))
      (ataxia.kernel:destroy-kernel kernel :assistant-window-test-complete)
      (when (and worker (sb-thread:thread-alive-p worker)) (sb-thread:terminate-thread worker))
      (uiop:delete-directory-tree project :validate t :if-does-not-exist :ignore))))
