(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-assistant/metaworld")
(in-package #:ataxia.infinite-world)
(let* ((source (format nil "## Desktop updated~%~%Removed **Studio**. Your apps are still open.~%~%- Windows moved to the canvas~%- Use `Undo layout` to restore them~%~%```lisp~%(remove-subworld world studio)~%```~%"))
       (rml (ataxia.assistant::%assistant-markdown-rml source))
       (messages (list (list :role :you :text "Delete the Studio sub-world.") (list :role :assistant :text source))))
  (dolist (part '("md-h2" "md-strong" "md-code" "md-list-row" "md-code-block")) (assert (search part rml)))
  (assert (not (search "**Studio**" rml)))
  (assert (not (search "```" rml)))
  (with-open-file (out (asdf:system-relative-pathname "ataxia-assistant" "build/assistant-formatted-transcript.rml") :direction :output :if-exists :supersede)
    (write-string (ataxia.assistant::%assistant-transcript-rml messages) out)))
(let ((rml (ataxia.assistant::%assistant-markdown-rml (format nil "| Group | Result |~%| --- | --- |~%| **Studio** | Removed |~%~%> Apps remain open.~%~%1. Inspect~%2. Apply~%  - [x] Verified~%"))))
  (dolist (part '("md-table-heading" "md-table-cell" "md-strong" "md-quote" "1." "2." "☑" "margin-left:12dp")) (assert (search part rml))))
(dolist (source '("<b>Literal markup</b> & text" "`<widget/>`" "{{message}}" "[Guide](https://example.com/a?x=1&y=2)" "An unfinished **stream" "```" "`"))
  (let ((rml (ataxia.assistant::%assistant-markdown-rml source)))
    (assert (not (search "<widget" rml)))
    (assert (not (search "<b>" rml)))
    (assert (not (search "{{" rml)))
    (assert (not (search "href=" rml)))))
(assert (search "snake_case_identifier" (ataxia.assistant::%assistant-markdown-rml "snake_case_identifier")))
(assert (search "&lt;b&gt;" (ataxia.assistant::%assistant-transcript-rml (list (list :role :you :text "<b>raw</b> **raw**")))))
(assert (search "<br/>" (ataxia.assistant::%assistant-markdown-rml (format nil "First  ~%second"))))
(assert (search "md-em" (ataxia.assistant::%assistant-markdown-rml "*Emphasis*")))
(format t "PASS: formatted paragraphs, headings, lists, emphasis, code, tables, quoted text, escaped markup and incomplete streaming.~%")
