(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-assistant/metaworld")
(in-package #:ataxia.infinite-world)
(let* ((source (format nil "## Desktop updated~%~%Removed **Studio**. Your apps are still open.~%~%- Windows moved to the canvas~%- Check `getWorld` for their placement~%~%```lisp~%(remove-subworld world studio)~%```~%"))
       (html (ataxia.assistant::%assistant-markdown-html source)))
  (dolist (part '("md-h2" "md-strong" "md-code" "md-list-row" "md-code-block")) (assert (search part html)))
  (assert (not (search "**Studio**" html)))
  (assert (not (search "```" html))))
(let ((html (ataxia.assistant::%assistant-markdown-html (format nil "| Group | Result |~%| --- | --- |~%| **Studio** | Removed |~%~%> Apps remain open.~%~%1. Inspect~%2. Apply~%  - [x] Verified~%"))))
  (dolist (part '("md-table-heading" "md-table-cell" "md-strong" "md-quote" "1." "2." "☑" "margin-left:12dp")) (assert (search part html))))
(dolist (source '("<b>Literal markup</b> & text" "`<widget/>`" "{{message}}" "[Guide](https://example.com/a?x=1&y=2)" "An unfinished **stream" "```" "`"))
  (let ((html (ataxia.assistant::%assistant-markdown-html source)))
    (assert (not (search "<widget" html)))
    (assert (not (search "<b>" html)))
    (assert (not (search "{{" html)))
    (assert (not (search "href=" html)))))
(assert (search "snake_case_identifier" (ataxia.assistant::%assistant-markdown-html "snake_case_identifier")))
(assert (search "&lt;b&gt;" (ataxia.assistant::%assistant-transcript-html (list (list :role :you :text "<b>raw</b> **raw**")))))
(assert (search "<br/>" (ataxia.assistant::%assistant-markdown-html (format nil "First  ~%second"))))
(assert (search "md-em" (ataxia.assistant::%assistant-markdown-html "*Emphasis*")))
(format t "PASS: formatted paragraphs, headings, lists, emphasis, code, tables, quoted text, escaped markup and incomplete streaming.~%")
