(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-computer-use/metaworld")
(in-package #:ataxia.infinite-world)
(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (runtime (ataxia.kernel:kernel-runtime kernel)) (human (first (ataxia.kernel:kernel-seats kernel)))
       (human-keyboard nil) (human-device nil) (client nil) (session nil) (ticket nil) (phase 0)
       (log #P"/tmp/ataxia-agent-client.log"))
  (labels ((send (op &rest args)
             (ataxia.computer-use:request-on-owner world (append (list :op op :token (ataxia.computer-use::computer-session-token session) :sequence (1+ (ataxia.computer-use::computer-session-sequence session))) args))))
    (unwind-protect
         (progn
           (ataxia.kernel:start-kernel kernel)
           (setf human-keyboard (ataxia.world.synthetic-input:create-synthetic-input runtime :keyboard "Test human keyboard")
                 human-device (ataxia.kernel:register-input-device kernel human-keyboard :seat human))
           (ataxia.computer-use:enable world)
           (setf client (uiop:launch-program (list "env" (format nil "WAYLAND_DISPLAY=~A" (ataxia.runtime:runtime-socket-name runtime))
                                                 (namestring (asdf:system-relative-pathname "ataxia-computer-use" "build/computer-use-client")) (namestring log))
                                            :output "/tmp/ataxia-agent-client-stdout.log" :error-output :output))
           (let ((timer (ataxia.runtime:add-event-loop-timer runtime
                         (lambda (source)
                           (case phase
                             (0
                              (assert (%world-stacking world))
                              (ataxia.computer-use:request-on-owner world '(:op "connect" :mode "desktop" :name "Atlas" :purpose "Test real application control"))
                              (setf session (first (ataxia.computer-use::computer-controller-sessions (ataxia.computer-use::%computer-controller world))))
                              (assert (getf (send "observe") :ok))
                              (assert (eq :active (ataxia.computer-use::computer-session-state session)))
                              (assert (= 3 (ataxia.kernel:seat-capabilities (ataxia.computer-use::computer-session-seat session))))
                              (assert (eq human (ataxia.kernel:input-seat human-device)))
                              (assert (eq human-keyboard (ataxia.kernel::%seat-keyboard human)))
                              (let* ((window (first (%world-stacking world)))
                                     (entry (aref (ataxia.computer-use::%computer-windows session) 0)))
                                (send "focus" :window (ataxia.kernel:object-id (canvas-window-application window)))
                                (send "move" :x (max 5d0 (+ (getf entry :x) 40d0)) :y (max 5d0 (+ (getf entry :y) 40d0)) :duration .2d0))
                              (setf phase 1) (ataxia.runtime:update-event-loop-timer source 500))
                             (1
                              (assert (null (ataxia.computer-use::computer-session-action session)))
                              (send "button")
                              (send "key" :key "a" :modifiers '("Control_L"))
                              (send "type" :text "Hello λ 🙂")
                              (setf phase 2) (ataxia.runtime:update-event-loop-timer source 700))
                             (2
                              (assert (null (ataxia.computer-use::computer-session-action session)))
                              (send "scroll" :y 30)
                              (setf ticket (send "capture"))
                              (setf phase 3) (ataxia.runtime:update-event-loop-timer source 500))
                             (3
                              (assert (ataxia.computer-use::computer-capture-pixels ticket))
                              (assert (null (ataxia.computer-use::computer-capture-error ticket)))
                              (ataxia.computer-use::%computer-write-png ticket)
                              (uiop:copy-file (ataxia.computer-use::computer-capture-path ticket) (asdf:system-relative-pathname "ataxia-computer-use" "build/agent-capture.png"))
                              (delete-file (ataxia.computer-use::computer-capture-path ticket))
                              (setf (ataxia.computer-use::computer-session-capture session) nil)
                              (let ((events (uiop:read-file-string log)))
                                (assert (search "focus agent-1" events))
                                (assert (search "button agent-1 272 1" events))
                                (assert (search "button agent-1 272 0" events))
                                (assert (search "λ" events)) (assert (search "🙂" events)))
                              (send "button" :state "down")
                              (send "key" :key "Shift_L" :state "down")
                              (ataxia.computer-use:pause-session session)
                              (assert (zerop (hash-table-count (ataxia.computer-use::computer-input-state-buttons (ataxia.computer-use::%computer-seat-state session)))))
                              (assert (null (ataxia.computer-use::computer-session-keys session)))
                              (assert (handler-case (progn (send "move" :x 5 :y 5) nil) (ataxia.computer-use::computer-use-rejected () t)))
                              (ataxia.computer-use:activate-session session)
                              (let ((window (first (%world-stacking world))))
                                ;; Ordinary map/focus policy cannot steal an agent's focus.
                                (ataxia.world:focus-world-target world (ataxia.computer-use::computer-session-seat session) window)
                                (assert (null (ataxia.computer-use::computer-input-state-focused (ataxia.computer-use::%computer-seat-state session))))
                                (send "focus" :window (ataxia.kernel:object-id (canvas-window-application window)))
                                (assert (handler-case
                                            (progn (ataxia.computer-use:request-on-owner world (list :op "key" :token (ataxia.computer-use::computer-session-token session)
                                                                                 :sequence (ataxia.computer-use::computer-session-sequence session) :key "b")) nil)
                                          (ataxia.computer-use::computer-use-rejected () t)))
                                (assert (handler-case (progn (send "key" :key "Shift_L" :modifiers '("Shift_L")) nil)
                                          (ataxia.computer-use::computer-use-rejected () t)))
                                ;; Actual physical-seat keyboard traffic takes control.
                                (%focus-target world (gethash human (%world-seats world)) window)
                                (ataxia.world.synthetic-input:synthetic-key human-keyboard 30 t (ataxia.computer-use::%computer-time))
                                (ataxia.world.synthetic-input:synthetic-key human-keyboard 30 nil (ataxia.computer-use::%computer-time))
                                (assert (eq :paused (ataxia.computer-use::computer-session-state session)))
                                (ataxia.computer-use:activate-session session)
                                (send "focus" :window (ataxia.kernel:object-id (canvas-window-application window)))
                                (send "key" :key "Control_L" :state "down")
                                (setf (ataxia.computer-use::computer-session-held-since session) (- (%now) 6d0))
                                (ataxia.computer-use::%computer-tick (ataxia.computer-use::%computer-controller world))
                                (assert (eq :paused (ataxia.computer-use::computer-session-state session)))
                                (assert (null (ataxia.computer-use::computer-session-keys session))))
                              ;; Multiple agents have distinct native seats and keyboards.
                              (ataxia.computer-use:request-on-owner world '(:op "connect" :name "Nova" :purpose "Test a second independent seat"))
                              (let ((second (second (ataxia.computer-use::computer-controller-sessions (ataxia.computer-use::%computer-controller world)))))
                                (ataxia.computer-use:activate-session second) (ataxia.computer-use:activate-session session)
                                (assert (= 3 (length (ataxia.kernel:kernel-seats kernel))))
                                (assert (not (eq (ataxia.computer-use::computer-session-keyboard session) (ataxia.computer-use::computer-session-keyboard second))))
                                (ataxia.kernel:world-key-event world human
                                  (ataxia.kernel:make-key-input :device human-device :keycode 1 :state :pressed
                                    :keysyms #("Escape") :modifiers '(:control :alt) :time-msec (ataxia.computer-use::%computer-time)))
                                (assert (eq :paused (ataxia.computer-use::computer-session-state session)))
                                (assert (eq :paused (ataxia.computer-use::computer-session-state second)))
                                (ataxia.computer-use:close-session second))
                              (ataxia.computer-use:close-session session)
                              (assert (= 1 (length (ataxia.kernel:kernel-seats kernel))))
                              (assert (eq human-keyboard (ataxia.kernel::%seat-keyboard human)))
                              (ataxia.computer-use:disable world)
                              (setf phase 4) (ataxia.runtime:update-event-loop-timer source 0)))
                           0))))
             (ataxia.runtime:update-event-loop-timer timer 1000))
           (ataxia.kernel:run-kernel kernel :run-for 4d0)
           (assert (= phase 4))
           (assert (eq :running (ataxia.kernel:kernel-world-status kernel)))
           (format t "PASS: automatic activation, independent seat/keyboard, Wayland focus/buttons/chords/Unicode, capture, pause releases and disconnect cleanup.~%"))
      (when (gethash human (%world-seats world))
        (%focus-target world (gethash human (%world-seats world)) nil))
      (when client (ignore-errors (uiop:terminate-process client)))
      (ignore-errors (ataxia.computer-use:disable world))
      (when human-keyboard (ataxia.world.synthetic-input:destroy-synthetic-input human-keyboard))
      (ataxia.kernel:destroy-kernel kernel :computer-use-test-complete))))
