(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-computer-use/metaworld")
(in-package #:ataxia.infinite-world)
(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (runtime (ataxia.kernel:kernel-runtime kernel))
       (directory (merge-pathnames (format nil "ataxia-api-test-~A/" (ataxia.computer-use:random-token)) (uiop:temporary-directory)))
       (client nil) (checks nil) (control nil) (frames 0) (baseline nil)
       (original (symbol-function 'ataxia.kernel::%render-output-frame)))
  (labels ((path (relative) (namestring (merge-pathnames relative directory)))
           (source (relative) (namestring (asdf:system-relative-pathname "ataxia-computer-use" relative)))
           (ui-action (action)
             (let* ((panel (first (ataxia.computer-use::computer-controller-panels (ataxia.computer-use::%computer-controller world))))
                    (component (canvas-overlay-component panel)))
               (funcall (gethash action (ataxia.world.web::%callbacks component)) component ""))))
    (unwind-protect
         (progn
           (sb-posix:mkdir directory #o700)
           (setf (symbol-function 'ataxia.kernel::%render-output-frame)
                 (lambda (output) (incf frames) (funcall original output)))
           (ataxia.kernel:start-kernel kernel)
           (setf control (ataxia.sly-control:start-sly-control kernel :port 4007))
           ;; The listener uses the owner queue in-process; it needs no SLY TCP server.
           (slynk:stop-server 4007)
           (ataxia.computer-use:enable world :socket (path "computer-use.sock"))
           (setf client (uiop:launch-program (list "env" (format nil "WAYLAND_DISPLAY=~A" (ataxia.runtime:runtime-socket-name runtime))
                                                   (source "build/computer-use-client") (path "client.log"))
                                             :output (path "client-stdout.log") :error-output :output))
           (let ((timer (ataxia.runtime:add-event-loop-timer runtime
							     (lambda (timer)
							       (unless checks
								 (when (%world-stacking world)
								   (setf checks (uiop:launch-program (list "sbcl" "--noinform" "--disable-debugger" "--script"
													   (source "tests/computer-use-api-client.lisp") (namestring directory))
												     :output (path "checks.log") :error-output :output))))
							       (dolist (action '(("resume" . "resume0") ("pause" . "pause0")))
								 (when (probe-file (path (car action)))
								   (delete-file (path (car action))) (ui-action (cdr action))))
                                                       (when (and (probe-file (path "restart"))
                                                                  (ataxia.computer-use::computer-server-clients (ataxia.computer-use::computer-controller-server (ataxia.computer-use::%computer-controller world))))
                                                         (delete-file (path "restart"))
                                                         (let ((old (ataxia.computer-use::computer-controller-server (ataxia.computer-use::%computer-controller world))))
                                                           (ataxia.computer-use::%computer-stop-server (ataxia.computer-use::%computer-controller world))
                                                           (ataxia.computer-use::%computer-start-server world (path "computer-use.sock"))
                                                           (sb-thread:make-thread
                                                            (lambda ()
                                                              (let ((reply (ataxia.computer-use::%request '(:op "outputs") :expected-server old)))
                                                                (with-open-file (out (path "restarted") :direction :output :if-exists :supersede)
                                                                  (write-string (if (equal "disabled" (getf reply :error)) "PASS" "FAIL") out)))))))
							       (when (and checks (not (uiop:process-alive-p checks)))
								 (if baseline
								     (progn (assert (= frames baseline)) (ataxia.kernel:request-kernel-stop kernel :checks-complete))
								     (setf baseline frames)))
							       (ataxia.runtime:update-event-loop-timer timer (if baseline 300 100))
							       0))))
             (ataxia.runtime:update-event-loop-timer timer 500))
           (ataxia.kernel:run-kernel kernel :run-for 25d0)
           (assert checks)
           (write-string (uiop:read-file-string (path "checks.log")))
           (assert (not (uiop:process-alive-p checks)))
           (assert (zerop (uiop:wait-process checks)))
           (assert baseline)
           (assert (eq :running (ataxia.kernel:kernel-world-status kernel)))
           (format t "PASS: no settled agent UI frames; compositor stays healthy.~%"))
      (setf (symbol-function 'ataxia.kernel::%render-output-frame) original)
      (ataxia.computer-use:disable world)
      (dolist (state (%seat-states world)) (%focus-target world state nil))
      (when control (ataxia.sly-control:stop-sly-control control))
      (dolist (process (list checks client)) (when process (ignore-errors (uiop:terminate-process process))))
      (ataxia.kernel:destroy-kernel kernel :computer-use-api-test-complete)
      (uiop:delete-directory-tree directory :validate t :if-does-not-exist :ignore))))
