(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-computer-use/metaworld")
(in-package #:ataxia.infinite-world)

(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (runtime (ataxia.kernel:kernel-runtime kernel)) (clients nil)
       (session nil) (ticket nil) (target nil) (human nil) (stack nil) (phase 0)
       (original-read (symbol-function 'ataxia.computer-use::%computer-read-window)) (state-checks 0)
       (log #P"/tmp/ataxia-window-client.log"))
  (labels ((send (op &rest args)
             (ataxia.computer-use:request-on-owner world (append (list :op op :token (ataxia.computer-use::computer-session-token session)
                                                    :sequence (1+ (ataxia.computer-use::computer-session-sequence session))) args)))
           (rejects (code function)
             (assert (handler-case (progn (funcall function) nil)
                       (ataxia.computer-use::computer-use-rejected (cause) (equal code (ataxia.computer-use::%computer-error-code cause))))))
           (take-image (width height &optional color (x 45) (y 55))
             (assert ticket)
             (when (ataxia.computer-use::computer-capture-error ticket) (error "Capture: ~A" (ataxia.computer-use::computer-capture-error ticket)))
             (assert (= width (ataxia.computer-use::computer-capture-width ticket)))
             (assert (= height (ataxia.computer-use::computer-capture-height ticket)))
             (assert (ataxia.computer-use::computer-capture-pixels ticket))
             (when color
               (let ((offset (* 4 (+ x (* width y)))))
                 (loop for expected in color for index from offset do
                       (assert (<= (abs (- expected (aref (ataxia.computer-use::computer-capture-pixels ticket) index))) 1)))))
             (when (eq :window (ataxia.computer-use::computer-capture-mode ticket))
               (ataxia.computer-use::%computer-set-basis session (ataxia.computer-use::computer-capture-bounds ticket) (ataxia.computer-use::computer-capture-root-bounds ticket)))
             (ataxia.computer-use::%computer-write-png ticket)
             (delete-file (ataxia.computer-use::computer-capture-path ticket))
             (setf ticket nil (ataxia.computer-use::computer-session-capture session) nil)))
    (unwind-protect
         (progn
           (setf (symbol-function 'ataxia.computer-use::%computer-read-window)
                 (lambda (ticket world)
                   (cffi:with-foreign-object (value :int)
                     (let ((parameters '(#x0D02 #x0D04 #x0D03)) (old nil)
                           (discard (cffi:foreign-funcall "glIsEnabled" :uint #x8C89 :uchar)))
                       (dolist (parameter parameters)
                         (cffi:foreign-funcall "glGetIntegerv" :uint parameter :pointer value :void)
                         (push (cffi:mem-ref value :int) old))
                       (unwind-protect
                            (progn
                              (loop for parameter in parameters for n in '(31 2 3) do
                                    (cffi:foreign-funcall "glPixelStorei" :uint parameter :int n :void))
                              (cffi:foreign-funcall "glEnable" :uint #x8C89 :void)
                              (funcall original-read ticket world)
                              (loop for parameter in parameters for n in '(31 2 3) do
                                    (cffi:foreign-funcall "glGetIntegerv" :uint parameter :pointer value :void)
                                    (assert (= n (cffi:mem-ref value :int))))
                              (assert (= 1 (cffi:foreign-funcall "glIsEnabled" :uint #x8C89 :uchar)))
                              (incf state-checks))
                         (loop for parameter in parameters for n in (nreverse old) do
                               (cffi:foreign-funcall "glPixelStorei" :uint parameter :int n :void))
                         (when (zerop discard) (cffi:foreign-funcall "glDisable" :uint #x8C89 :void)))))))
           (ataxia.kernel:start-kernel kernel)
           (ataxia.computer-use:enable world)
           (dotimes (i 2)
             (push (uiop:launch-program
                    (list "env" (format nil "WAYLAND_DISPLAY=~A" (ataxia.runtime:runtime-socket-name runtime))
                          (if (zerop i) "ATAXIA_TEST_TITLE=Window target" "ATAXIA_TEST_TITLE=Window cover")
                          (namestring (asdf:system-relative-pathname "ataxia-computer-use" "build/computer-use-client"))
                          (if (zerop i) (namestring log) "/tmp/ataxia-window-cover.log"))
                    :output "/tmp/ataxia-window-client-stdout.log" :error-output :output) clients))
           (let ((timer
                  (ataxia.runtime:add-event-loop-timer
                   runtime
                   (lambda (source)
                     (format t "Window capture phase ~D~%" phase)
                     (case phase
                       (0
                        (assert (= 2 (length (%world-stacking world))))
                        (setf target (find "Window target" (%world-stacking world)
                                           :key (lambda (w) (ataxia.kernel:application-title (canvas-window-application w))) :test #'equal)
                              stack (list target (find-if (lambda (w) (not (eq w target))) (%world-stacking world)))
                              (%world-stacking world) (copy-list stack)
                              human (first (%seat-states world)))
                        (dolist (window stack)
                          (setf (canvas-window-x window) 120d0 (canvas-window-y window) 150d0
                                (canvas-window-width window) 600d0 (canvas-window-height window) 360d0
                                (canvas-window-scale window) 1d0))
                        (%focus-target world human (second stack))
                        (ataxia.computer-use:request-on-owner world '(:op "connect" :name "Window agent" :purpose "Verify isolated application control"))
                        (setf session (first (ataxia.computer-use::computer-controller-sessions (ataxia.computer-use::%computer-controller world))))
                        (assert (ataxia.computer-use::%computer-window-view-p session))
                        (ataxia.computer-use:activate-session session)
                        (rejects "window-required" (lambda () (send "capture")))
                        (send "focus" :window (ataxia.kernel:object-id (canvas-window-application target)))
                        (assert (equal stack (%world-stacking world)))
                        (assert (eq (second stack) (%canvas-seat-focused human)))
                        (setf ticket (send "capture")))
                       (1
                        (take-image 600 360 '(239 96 72 255))
                        (assert (null (ataxia.computer-use::computer-view-visible-p (ataxia.computer-use::computer-session-view session))))
                        (send "move" :x 45 :y 55 :duration .016d0))
                       (2
                        (send "button") (send "scroll" :y 15)
                        (assert (equal stack (%world-stacking world)))
                        (assert (eq (second stack) (%canvas-seat-focused human)))
                        (setf (canvas-window-x target) -5000d0 (canvas-window-y target) -5000d0)
                        (%full-damage world (%first-output-state world)))
                       (3 (send "key" :key "F5"))
                       (4
                        (let ((events (uiop:read-file-string log)))
                          (assert (search "pointer-enter agent-1 45.0 55.0" events))
                          (assert (search "button agent-1 272 1" events))
                          (assert (not (search "frame-painted" events))))
                        (assert (not (ataxia.computer-use::%computer-window-on-output-p session target)))
                        (assert (ataxia.computer-use::%computer-window-allowed-p session target))
                        (setf ticket (send "capture")))
                       (5
                        (take-image 600 360 '(72 207 96 255))
                        (assert (search "frame-painted" (uiop:read-file-string log)))
                        (send "button")
                        (send "key" :key "F6"))
                       (6
                        (rejects "window-resized" (lambda () (send "move" :x 45 :y 55)))
                        (setf ticket (send "capture")))
                       (7
                        (take-image 640 400 '(239 96 72 255))
                        (send "key" :key "F7"))
                       (8 (setf ticket (send "capture")))
                       (9
                        (format t "Bounds ~S surfaces ~S~%" (ataxia.computer-use::computer-capture-bounds ticket)
                                (loop for surface across (ataxia.kernel:drawable-surfaces (canvas-window-application target)) collect
                                      (list (ataxia.kernel:drawable-surface-local-x surface) (ataxia.kernel:drawable-surface-local-y surface)
                                            (ataxia.kernel:drawable-surface-width surface) (ataxia.kernel:drawable-surface-height surface))))
                        (take-image 670 400 '(255 208 64 255) 10 60)
                        (send "move" :x 10 :y 60 :duration .016d0))
                       (10 (send "key" :key "F8"))
                       (11 (setf ticket (send "capture")))
                       (12
                        ;; This corner lies outside the unconfigured popup's
                        ;; original position, so stale placement cannot pass.
                        (take-image 670 400 '(191 96 239 255) 100 100)
                        (send "move" :x 100 :y 100 :duration .016d0))
                       (13
                        (send "button" :state "down")
                        (rejects "input-held" (lambda () (send "view" :mode "desktop")))
                        (send "button" :state "up")
                        (send "view" :mode "desktop")
                        (assert (not (ataxia.computer-use::%computer-window-view-p session)))
                        (setf ticket (send "capture")))
                       (14
                        (take-image 1100 800)
                        (assert (search "pointer-enter agent-1 10.0 20.0" (uiop:read-file-string log)))
                        (assert (search "pointer-enter agent-1 75.0 70.0" (uiop:read-file-string log)))
                        (assert (search "button-surface agent-1 popup 1" (uiop:read-file-string log)))
                        (assert (search "button-surface agent-1 popup 0" (uiop:read-file-string log)))
                        (send "move" :x 760 :y 55 :duration .016d0))
                       (15
                        (rejects "target-blocked" (lambda () (send "button")))
                        (send "view" :mode "window")
                        (setf ticket (send "capture"))
                        (ataxia.computer-use:pause-session session)
                        (assert (ataxia.computer-use::computer-capture-error ticket))
                        (rejects "not-active" (lambda () (send "capture")))
                        (ataxia.computer-use:close-session session)
                        (ataxia.kernel:request-kernel-stop kernel :checks-complete)))
                     (incf phase)
                     (ataxia.runtime:update-event-loop-timer source 300)
                     0))))
             (ataxia.runtime:update-event-loop-timer timer 500))
           (ataxia.kernel:run-kernel kernel :run-for 8d0)
           (assert (= phase 16))
           (assert (= state-checks 5))
           (assert (eq :running (ataxia.kernel:kernel-world-status kernel)))
           (format t "PASS: covered/offscreen capture and input, preserved human focus, frame callbacks, resize guard, outside subsurface, popup rendering, desktop mode, pause cancellation.~%"))
      (setf (symbol-function 'ataxia.computer-use::%computer-read-window) original-read)
      (ignore-errors (ataxia.computer-use:disable world))
      (dolist (state (%seat-states world)) (%focus-target world state nil))
      (dolist (client clients) (ignore-errors (uiop:terminate-process client)))
      (ataxia.kernel:destroy-kernel kernel :computer-use-window-test-complete))))
