;;;; Four native API workers retain independent input, images, and pause state.
(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-computer-use/metaworld")
(in-package #:ataxia.infinite-world)

(defun concurrent-png-pixel (path x y)
  (labels ((u32 (bytes offset)
             (loop for i from offset below (+ offset 4)
                   for n = (aref bytes i) then (+ (* n 256) (aref bytes i)) finally (return n))))
    (let* ((bytes (with-open-file (in path :element-type '(unsigned-byte 8))
                    (let ((bytes (make-array (file-length in) :element-type '(unsigned-byte 8)))) (read-sequence bytes in) bytes)))
           (width (u32 bytes 16)) (height (u32 bytes 20)) (offset 8) (parts nil))
      (assert (= width 600)) (assert (= height 360))
      (loop while (< offset (length bytes)) for size = (u32 bytes offset) do
            (when (equalp #(73 68 65 84) (subseq bytes (+ offset 4) (+ offset 8)))
              (push (subseq bytes (+ offset 8) (+ offset 8 size)) parts))
            (incf offset (+ size 12)))
      (let ((input (apply #'concatenate '(simple-array (unsigned-byte 8) (*)) (nreverse parts)))
            (rows (make-array (* height (1+ (* width 4))) :element-type '(unsigned-byte 8))))
        (cffi:with-foreign-object (size :ulong)
          (setf (cffi:mem-ref size :ulong) (length rows))
          (sb-sys:with-pinned-objects (input rows)
            (assert (zerop (cffi:foreign-funcall "uncompress" :pointer (sb-sys:vector-sap rows) :pointer size
                                                :pointer (sb-sys:vector-sap input) :ulong (length input) :int)))))
        (let ((start (+ 1 (* y (1+ (* width 4))) (* x 4))))
          (coerce (subseq rows start (+ start 4)) 'list))))))

(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (runtime (ataxia.kernel:kernel-runtime kernel))
       (directory (merge-pathnames (format nil "ataxia-concurrent-~A/" (ataxia.computer-use:random-token)) (uiop:temporary-directory)))
       (socket-path (namestring (merge-pathnames "api.sock" directory)))
       (clients nil) (driver nil) (failure nil) (complete nil) (control nil)
       (sessions #()) (windows #()) (workers (make-array 4 :initial-element nil))
       (replies (make-array 4 :initial-element nil)) (sequences (make-array 4 :initial-element 0))
       (human (first (ataxia.kernel:kernel-seats kernel))) (human-keyboard nil)
       (colors '((239 96 72 255) (72 207 96 255) (36 99 235 255) (191 96 239 255))))
  (labels ((owner-call (function)
             (ataxia.sly-control:agent-inspect
              (lambda (k w) (declare (ignore k w)) (funcall function)) :timeout 3d0))
           (field (object &rest names) (reduce (lambda (v n) (gethash n v)) names :initial-value object))
           (wait-for (function)
             (loop repeat 150 when (owner-call function) return t do (sleep .02d0)
                   finally (error "Concurrent condition timed out")))
           (request (index op &rest fields)
             (let ((socket (make-instance 'sb-bsd-sockets:local-socket :type :stream :protocol 0)))
               (unwind-protect
                    (progn
                      (sb-bsd-sockets:socket-connect socket socket-path)
                      (with-open-stream (stream (sb-bsd-sockets:socket-make-stream socket :input t :output t
                                                                                 :element-type '(unsigned-byte 8) :buffering :full :timeout 10))
                        (ataxia.world.wire:write-line-bytes
                         stream (ataxia.world.wire:encode
                                 (append (list :op op :token (ataxia.computer-use::computer-session-token (aref sessions index))
                                               :sequence (1+ (aref sequences index))) fields)))
                        (let ((reply (ataxia.world.wire:decode (ataxia.world.wire:read-line-bytes stream 262144))))
                          (when (field reply "session") (setf (aref sequences index) (field reply "session" "sequence")))
                          reply)))
                 (ignore-errors (sb-bsd-sockets:socket-close socket)))))
           (run-batch (index)
             (request index "batch" :actions
                      (vector (list :op "focus" :window (aref windows index))
                              '(:op "move" :x 45 :y 55 :duration .1d0) '(:op "button")
                              '(:op "key" :key "a" :modifiers #("Control_L"))
                              (list :op "type" :text (format nil "Agent ~D λ🙂 ~A" index (make-string 140 :initial-element (char "abcd" index))))
                              '(:op "key" :key "Return")
                              (list :op "wait-window" :window (aref windows index) :title "Batch complete" :timeout 2d0))))
           (check-image (index reply)
             (assert (eq t (field reply "ok")) () "~A" (ataxia.world.wire:encode reply))
             (assert (= 7 (field reply "completed")))
             (assert (= (aref windows index) (field reply "image" "window")))
             (assert (equal (nth index colors) (concurrent-png-pixel (field reply "image" "path") 45 55)))))
    (unwind-protect
         (progn
           (sb-posix:mkdir directory #o700)
           (ataxia.kernel:start-kernel kernel)
           (setf human-keyboard (ataxia.world.synthetic-input:create-synthetic-input runtime :keyboard "Concurrent human"))
           (ataxia.kernel:register-input-device kernel human-keyboard :seat human)
           (setf control (ataxia.sly-control:start-sly-control kernel :port 4007))
           (slynk:stop-server 4007)
           (ataxia.computer-use:enable world :socket socket-path)
           (dotimes (i 4)
             (ataxia.computer-use:request-on-owner world (list :op "connect" :name (format nil "Concurrent agent ~D" i) :purpose "Verify independent concurrent input")))
           (setf sessions (coerce (ataxia.computer-use::computer-controller-sessions (ataxia.computer-use::%computer-controller world)) 'vector))
           (map nil #'ataxia.computer-use:activate-session sessions)
           (loop for color in '("ffef6048" "ff48cf60" "ff2463eb" "ffbf60ef") for i from 0 do
                 (push (uiop:launch-program
                        (list "env" (format nil "WAYLAND_DISPLAY=~A" (ataxia.runtime:runtime-socket-name runtime))
                              (format nil "ATAXIA_TEST_TITLE=Concurrent ~D" i) (format nil "ATAXIA_TEST_COLOR=~A" color)
                              (namestring (asdf:system-relative-pathname "ataxia-computer-use" "build/computer-use-client"))
                              (namestring (merge-pathnames (format nil "client-~D.log" i) directory)))
                        :output :interactive :error-output :interactive) clients))
           (setf driver
                 (sb-thread:make-thread
                  (lambda ()
                    (handler-case
                        (progn
                          (wait-for (lambda () (and (= 4 (length (%world-stacking world)))
                                                   (every #'%window-visible-p (%world-stacking world)))))
                          (owner-call
                           (lambda ()
                             (setf windows
                                   (map 'vector (lambda (i)
                                                  (let ((window (find (format nil "Concurrent ~D" i) (%world-stacking world)
                                                                      :key (lambda (w) (ataxia.kernel:application-title (canvas-window-application w))) :test #'equal)))
                                                    (set-window-position world window 120d0 150d0)
                                                    (ataxia.kernel:object-id (canvas-window-application window)))) #(0 1 2 3)))
                             (%focus-target world (gethash human (%world-seats world))
                                            (find (aref windows 1) (%world-stacking world)
                                                  :key (lambda (w) (ataxia.kernel:object-id (canvas-window-application w)))))))
                          (dotimes (i 4)
                            (let ((index i))
                              (setf (aref workers i) (sb-thread:make-thread
                                                     (lambda () (setf (aref replies index) (run-batch index)))
                                                     :name (format nil "Concurrent agent ~D" i)))))
                          (wait-for (lambda () (every (lambda (s) (eq :text (getf (ataxia.computer-use::computer-session-action s) :kind))) sessions)))
                          (sleep .15d0)
                          (owner-call (lambda ()
                                        (assert (= (aref windows 1)
                                                   (ataxia.kernel:object-id
                                                    (canvas-window-application (%canvas-seat-focused (gethash human (%world-seats world)))))))
                                        (ataxia.world.synthetic-input:synthetic-key human-keyboard 30 t (ataxia.computer-use::%computer-time))
                                        (ataxia.world.synthetic-input:synthetic-key human-keyboard 30 nil (ataxia.computer-use::%computer-time))
                                        (assert (equal '(:active :paused :active :active)
                                                       (map 'list #'ataxia.computer-use::computer-session-state sessions)))))
                          (dotimes (i 4)
                            (assert (not (eq :timeout (sb-thread:join-thread (aref workers i) :timeout 8d0 :default :timeout)))))
                          (dotimes (i 4)
                            (if (= i 1)
                                (progn
                                  (assert (equal "batch-interrupted" (field (aref replies i) "error"))
                                          () "Unexpected pause result: ~A" (ataxia.world.wire:encode (aref replies i)))
                                  (assert (= 4 (field (aref replies i) "completed")))
                                  (assert (equal "paused" (field (aref replies i) "session" "state"))))
                                (check-image i (aref replies i))))
                          (assert (= 3 (length (remove-duplicates
                                               (loop for i in '(0 2 3) collect (field (aref replies i) "image" "path")) :test #'equal))))
                          (dotimes (i 4)
                            (let ((keys (remove-if-not (lambda (line) (uiop:string-prefix-p "key agent-" line))
                                                       (uiop:read-file-lines (merge-pathnames (format nil "client-~D.log" i) directory)))))
                              (assert keys)
                              (assert (every (lambda (line) (uiop:string-prefix-p (format nil "key agent-~D " (1+ i)) line)) keys))))
                          ;; Only explicit fixture approval resumes the interrupted seat.
                          (owner-call (lambda () (ataxia.computer-use:activate-session (aref sessions 1))))
                          (setf (aref replies 1) (run-batch 1))
                          (check-image 1 (aref replies 1))
                          (dotimes (i 4) (assert (eq t (field (request i "disconnect") "ok"))))
                          (wait-for (lambda () (null (ataxia.computer-use::computer-server-clients (ataxia.computer-use::computer-controller-server (ataxia.computer-use::%computer-controller world))))))
                          (owner-call (lambda ()
                                        (assert (= 1 (length (ataxia.kernel:kernel-seats kernel))))
                                        (assert (eq human-keyboard (ataxia.kernel::%seat-keyboard human)))))
                          (dotimes (i 4) (assert (not (probe-file (field (aref replies i) "image" "path")))))
                          (setf complete t))
                      (error (cause) (setf failure cause)))
                    (ignore-errors (owner-call (lambda () (ataxia.kernel:request-kernel-stop kernel :checks-complete)))))
                  :name "Concurrent computer-use checks"))
           (ataxia.kernel:run-kernel kernel :run-for 18d0)
           (when failure (error failure))
           (assert complete)
           (assert (eq :running (ataxia.kernel:kernel-world-status kernel)))
           (format t "PASS: four concurrent socket batches isolate input and pixels; human takeover pauses only its target, explicit resume and disconnect clean up.~%"))
      (ignore-errors (ataxia.computer-use:disable world))
      (dolist (state (%seat-states world)) (%focus-target world state nil))
      (when control (ataxia.sly-control:stop-sly-control control))
      (dolist (worker (cons driver (coerce workers 'list)))
        (when (and worker (sb-thread:thread-alive-p worker))
          (ignore-errors (sb-thread:terminate-thread worker))))
      (dolist (client clients) (ignore-errors (uiop:terminate-process client)))
      (ataxia.kernel:destroy-kernel kernel :concurrent-complete)
      (uiop:delete-directory-tree directory :validate t :if-does-not-exist :ignore))))
