;;;; Real client closure must permit an explicit next target without redirecting input.
(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-computer-use/metaworld")
(in-package #:ataxia.infinite-world)

(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (runtime (ataxia.kernel:kernel-runtime kernel))
       (directory (merge-pathnames (format nil "ataxia-lifecycle-~A/" (ataxia.computer-use:random-token)) (uiop:temporary-directory)))
       (clients nil) (driver nil) (failure nil) (complete nil) (session nil) (sequence 0) (control nil))
  (labels ((owner-call (function)
             (ataxia.sly-control:agent-inspect
              (lambda (k w) (declare (ignore k w)) (funcall function)) :timeout 3d0))
           (launch (title &optional option)
             (let ((client (uiop:launch-program
                            (append (list "env") (when option (list option))
                             (list (format nil "WAYLAND_DISPLAY=~A" (ataxia.runtime:runtime-socket-name runtime))
                                  (format nil "ATAXIA_TEST_TITLE=~A" title)
                                  (namestring (asdf:system-relative-pathname "ataxia-computer-use" "build/computer-use-client"))
                                  (namestring (merge-pathnames (format nil "~A.log" title) directory))))
                            :output :interactive :error-output :interactive)))
               (push client clients) client))
           (request (op &rest fields)
             (let ((reply (ataxia.computer-use::%request
                           (append (list :op op :token (ataxia.computer-use::computer-session-token session) :sequence (1+ sequence)) fields))))
               (when (getf reply :session) (setf sequence (getf (getf reply :session) :sequence)))
               reply))
           (ok (reply)
             (assert (eq t (getf reply :ok)) () "~S" reply) reply)
           (parent-keys ()
             (remove-if-not (lambda (line) (uiop:string-prefix-p "key " line))
                            (uiop:read-file-lines (merge-pathnames "Editor.log" directory))))
           (window (title)
             (loop repeat 100
                   for match = (owner-call (lambda () (find-if
                                                       (lambda (w)
                                                         (and (ataxia.computer-use::%computer-window-allowed-p session w)
                                                              (equal title (ataxia.kernel:application-title (canvas-window-application w)))))
                                                       (%world-stacking world))))
                   when match return (ataxia.kernel:object-id (canvas-window-application match))
                   do (sleep .025d0) finally (error "No window ~A" title)))
           (wait-for (function)
             (loop repeat 100 when (owner-call function) return t do (sleep .025d0)
                   finally (error "Lifecycle condition timed out"))))
    (unwind-protect
         (progn
           (sb-posix:mkdir directory #o700)
           (ataxia.kernel:start-kernel kernel)
           (setf control (ataxia.sly-control:start-sly-control kernel :port 4007))
           (slynk:stop-server 4007)
           (ataxia.computer-use:enable world)
           (ataxia.computer-use:request-on-owner world '(:op "connect" :name "Lifecycle agent" :purpose "Verify ordinary dialog closure"))
           (setf session (first (ataxia.computer-use::computer-controller-sessions (ataxia.computer-use::%computer-controller world))))
           (ataxia.computer-use:activate-session session)
           (launch "Editor") (launch "Dialog")
           (setf driver
                 (sb-thread:make-thread
                  (lambda ()
                    (handler-case
                        (let* ((parent (window "Editor")) (dialog (window "Dialog"))
                               (reply (ok (request "batch" :actions (vector (list :op "focus" :window dialog)))))
                               (old-image (getf (getf reply :image) :path)))
                          ;; Closing alone clears focus and image, retaining approval.
                          (ok (request "key" :key "F2"))
                          (wait-for (lambda () (null (ataxia.computer-use::computer-view-window (ataxia.computer-use::computer-session-view session)))))
                          (assert (equal "active" (getf (getf (ok (request "status")) :session) :state)))
                          (assert (not (probe-file old-image)))
                          (assert (equal "window-required" (getf (request "capture") :error)))
                          (assert (equal "no-focus" (getf (request "key" :key "a") :error)))
                          (assert (equal "target-blocked" (getf (request "focus" :window dialog) :error)))
                          ;; Unsupported resources must not produce false success.
                          (let* ((client (launch "No input" "ATAXIA_TEST_IGNORE_INPUT=1"))
                                 (target (window "No input")))
                            (ok (request "focus" :window target))
                            (let* ((reply (ok (request "observe")))
                                   (entry (find target (getf reply :windows) :key (lambda (w) (getf w :id)))))
                              (assert (eq :false (getf (getf entry :input) :keyboard)))
                              (assert (eq :false (getf (getf entry :input) :pointer))))
                            (let ((before sequence))
                              (dolist (action '(("key" :key "a") ("type" :text "FORBIDDEN")
                                                ("move" :x 45 :y 55) ("button") ("scroll" :y 15)))
                                (assert (equal "input-not-ready" (getf (apply #'request action) :error)))
                                (assert (= before sequence))))
                            (ok (request "capture"))
                            (let* ((started (%now))
                                   (reply (request "batch" :capture :false :actions
                                                   (vector (list :op "focus" :window target)
                                                           '(:op "key" :key "Return")
                                                           '(:op "type" :text "FORBIDDEN")))))
                              (assert (equal "input-not-ready" (getf reply :error)))
                              (assert (= 1 (getf reply :completed)))
                              (assert (= 2 (getf reply :failed-action)))
                              (assert (<= 1d0 (- (%now) started) 1.5d0)))
                            (assert (notany (lambda (line) (uiop:string-prefix-p "key " line))
                                            (uiop:read-file-lines (merge-pathnames "No input.log" directory))))
                            (uiop:terminate-process client)
                            (wait-for (lambda () (null (ataxia.computer-use::computer-view-window (ataxia.computer-use::computer-session-view session))))))
                          ;; A client which binds late receives the first key once.
                          (launch "Delayed input" "ATAXIA_TEST_BIND_DELAY_MS=700")
                          (let* ((target (window "Delayed input")) (started (%now))
                                 (reply (ok (request "batch" :actions
                                                     (vector (list :op "focus" :window target)
                                                             '(:op "key" :key "Return")
                                                             (list :op "wait-window" :window target :title "Batch complete" :timeout 2d0))))))
                            (assert (>= (- (%now) started) .35d0))
                            (assert (= 3 (getf reply :completed)))
                            (let* ((entry (find target (getf reply :windows) :key (lambda (w) (getf w :id)))))
                              (assert (eq t (getf (getf entry :input) :keyboard)))
                              (assert (eq t (getf (getf entry :input) :pointer)))))
                          (format t "PASS: missing input resources reject without sending; batches wait for delayed bindings and report bounded failure.~%")
                          ;; A whole dialog-to-editor transition uses one request.
                          (launch "Second dialog")
                          (let* ((second (window "Second dialog"))
                                 (reply (ok (request "batch" :actions
                                                     (vector (list :op "focus" :window second)
                                                             '(:op "key" :key "F2")
                                                             (list :op "wait-stable" :window parent :settle .2d0)
                                                             (list :op "focus" :window parent)
                                                             '(:op "type" :text "After dialog")
                                                             '(:op "key" :key "Return"))))))
                            (assert (= 6 (getf reply :completed)))
                            (assert (= parent (getf (getf reply :image) :window)))
                            (assert (equal "active" (getf (getf reply :session) :state))))
                          ;; Closing during a text stream cancels it and pauses.
                          (let* ((client (launch "Closing during input"))
                                 (target (window "Closing during input")) (reply nil)
                                 (batch-thread (sb-thread:make-thread
                                                (lambda ()
                                                  (setf reply (request "batch" :capture :false :actions
                                                                       (vector (list :op "focus" :window target)
                                                                               (list :op "type" :text (make-string 200 :initial-element #\x))
                                                                               (list :op "focus" :window parent)
                                                                               '(:op "type" :text "FORBIDDEN"))))))))
                            (wait-for (lambda () (eq :text (getf (ataxia.computer-use::computer-session-action session) :kind))))
                            (let ((parent-events (parent-keys)))
                              (uiop:terminate-process client)
                              (sb-thread:join-thread batch-thread)
                              (assert (equal parent-events (parent-keys))))
                            (assert (equal "batch-interrupted" (getf reply :error)))
                            (assert (= 1 (getf reply :completed))))
                          (assert (equal "paused" (getf (getf (ok (request "status")) :session) :state)))
                          (assert (equal "not-active" (getf (request "key" :key "a") :error)))
                          (ok (request "disconnect"))
                          (setf complete t))
                      (error (cause) (setf failure cause)))
                    (ignore-errors (owner-call (lambda () (ataxia.kernel:request-kernel-stop kernel :checks-complete)))))
                  :name "Computer-use lifecycle checks"))
           (ataxia.kernel:run-kernel kernel :run-for 18d0)
           (when failure (error failure))
           (assert complete)
           (assert (eq :running (ataxia.kernel:kernel-world-status kernel)))
           (format t "PASS: dialog closure retains the session, clears target and image, supports an explicit next target, and pauses interrupted typing.~%"))
      (when (and driver (sb-thread:thread-alive-p driver))
        (sb-thread:join-thread driver :timeout 1d0 :default nil)
        (when (sb-thread:thread-alive-p driver) (ignore-errors (sb-thread:terminate-thread driver))))
      (ignore-errors (ataxia.computer-use:disable world))
      (dolist (state (%seat-states world)) (%focus-target world state nil))
      (when control (ataxia.sly-control:stop-sly-control control))
      (dolist (client clients) (ignore-errors (uiop:terminate-process client)))
      (ataxia.kernel:destroy-kernel kernel :lifecycle-complete)
      (uiop:delete-directory-tree directory :validate t :if-does-not-exist :ignore))))
