;;;; Real Unix socket integration; resume markers are private to the test fixture.
(require :asdf)
(require :sb-posix)
(require :sb-bsd-sockets)
(asdf:load-system "cffi")
(load (merge-pathnames "../src/world/computer-use/json.lisp" *load-truename*))

(defun field (object &rest names)
  (reduce (lambda (value name) (gethash name value)) names :initial-value object))
(defun be32 (bytes offset)
  (loop for i from offset below (+ offset 4) for value = (aref bytes i) then (+ (* value 256) (aref bytes i))
        finally (return value)))
(defun check-png (path &optional (width 1100) (height 800) sample)
  (cffi:load-foreign-library "libz.so.1")
  (let ((bytes (with-open-file (stream path :element-type '(unsigned-byte 8))
                 (let ((data (make-array (file-length stream) :element-type '(unsigned-byte 8))))
                   (read-sequence data stream) data)))
        (offset 8) (compressed nil))
    (assert (equalp #(137 80 78 71 13 10 26 10) (subseq bytes 0 8)))
    (assert (= width (be32 bytes 16))) (assert (= height (be32 bytes 20)))
    (loop while (< offset (length bytes)) do
	  (let* ((size (be32 bytes offset)) (body (subseq bytes (+ offset 4) (+ offset 8 size))))
            (sb-sys:with-pinned-objects (body)
              (assert (= (be32 bytes (+ offset 8 size))
			 (cffi:foreign-funcall "crc32" :ulong 0 :pointer (sb-sys:vector-sap body) :uint (length body) :ulong))))
            (when (equalp #(73 68 65 84) (subseq body 0 4)) (push (subseq body 4) compressed))
            (incf offset (+ size 12))))
    (let ((source (apply #'concatenate '(simple-array (unsigned-byte 8) (*)) (nreverse compressed)))
          (rows (make-array (* height (1+ (* width 4))) :element-type '(unsigned-byte 8))))
      (cffi:with-foreign-object (size :ulong)
        (setf (cffi:mem-ref size :ulong) (length rows))
        (sb-sys:with-pinned-objects (source rows)
          (assert (zerop (cffi:foreign-funcall "uncompress" :pointer (sb-sys:vector-sap rows) :pointer size
                                               :pointer (sb-sys:vector-sap source) :ulong (length source) :int))))
        (assert (= (length rows) (cffi:mem-ref size :ulong))))
      (when sample
        (destructuring-bind (x y &rest rgba) sample
          (let ((start (+ 1 (* y (1+ (* width 4))) (* x 4))))
            (assert (zerop (aref rows (* y (1+ (* width 4))))))
            (assert (equalp (coerce rgba 'vector) (subseq rows start (+ start 4))))))))
    bytes))

(let* ((directory (pathname (second sb-ext:*posix-argv*)))
       (socket-path (namestring (merge-pathnames "computer-use.sock" directory)))
       (root (merge-pathnames "../" (uiop:pathname-directory-pathname *load-truename*)))
       (token nil) (sequence 0))
  (labels
      ((raw (text)
         (let ((socket (make-instance 'sb-bsd-sockets:local-socket :type :stream :protocol 0)))
           (unwind-protect
                (progn
                  (sb-bsd-sockets:socket-connect socket socket-path)
                  (with-open-stream (stream (sb-bsd-sockets:socket-make-stream socket :input t :output t
									       :element-type '(unsigned-byte 8) :buffering :full :timeout 40))
                    (ataxia.computer-use.wire:write-line-bytes stream text)
                    (ataxia.computer-use.wire:decode (ataxia.computer-use.wire:read-line-bytes stream 262144))))
             (ignore-errors (sb-bsd-sockets:socket-close socket)))))
       (request (data) (raw (ataxia.computer-use.wire:encode data)))
       (send (op &rest fields)
         (let ((reply (request (append (list :op op :token token :sequence (1+ sequence)) fields))))
           (when (field reply "session") (setf sequence (field reply "session" "sequence"))) reply))
       (ok (reply) (assert (eq t (field reply "ok")) () "~A" (ataxia.computer-use.wire:encode reply)) reply)
       (mark (name) (with-open-file (out (merge-pathnames name directory) :direction :output :if-exists :supersede)))
       (wait-state (state)
         (loop repeat 100 for reply = (send "status")
               when (equal state (field reply "session" "state")) return reply do (sleep .025)
               finally (error "Session did not reach ~A" state)))
       (events () (uiop:read-file-string (merge-pathnames "client.log" directory)))
       (typed-events ()
         (with-output-to-string (out)
           (dolist (line (uiop:split-string (events) :separator '(#\Newline)))
             (when (and (<= 12 (length line)) (string= "key agent-1 " line :end2 12))
               (let* ((code-end (position #\Space line :start 12))
                      (state-end (position #\Space line :start (1+ code-end)))
                      (sym-end (position #\Space line :start (1+ state-end))))
                 (when (string= "1" line :start2 (1+ code-end) :end2 state-end)
                   (write-string line out :start (1+ sym-end)))))))))
    (assert (= #o600 (logand #o777 (sb-posix:stat-mode (sb-posix:stat socket-path)))))
    (dolist (text '("{\"op\":\"approve\"}" "{\"op\":\"outputs\",\"form\":\"(+ 1 2)\"}"
                    "{\"op\":\"move\",\"x\":NaN}" "{\"op\":\"outputs\",\"op\":\"connect\"}"
                    "{\"op\":\"connect\",\"name\":\"\\uD800\"}"))
      (assert (eq :false (field (raw text) "ok"))))
    (let ((reply (ataxia.computer-use.wire:decode
                  (uiop:run-program (list (namestring (merge-pathnames "scripts/ataxia-computer-use" root))
                                          "--socket" socket-path "request" "{\"op\":\"outputs\"}") :output :string))))
      (ok reply) (assert (= 1100 (field (aref (field reply "outputs") 0) "width"))))
    (let* ((name "Test \" #.(error 'not-evaluated) \\ λ")
           (reply (ok (request (list :op "connect" :mode "desktop" :name name :purpose "Verify native Lisp batching")))))
      (setf token (field reply "token"))
      (assert (equal name (field reply "session" "name")))
      (assert (equal "active" (field reply "session" "state"))))
    (ok (send "observe"))
    (let* ((window (aref (field (ok (send "observe")) "windows") 0))
           (id (field window "id"))
           (typed (format nil "~{~A~}" (make-list 14 :initial-element "Ab9 λ🙂!? ")))
           (started (get-internal-real-time))
           (reply (ok (send "batch" :actions
                            (vector (list :op "focus" :window id)
                                    (list :op "move" :x (max 5 (+ 40 (field window "x")))
                                          :y (max 5 (+ 40 (field window "y"))) :duration .2d0)
                                    '(:op "button") '(:op "key" :key "a" :modifiers #("Control_L"))
                                    (list :op "type" :text typed) '(:op "key" :key "Return")
                                    (list :op "wait-window" :window id :title "Batch complete" :timeout 3d0)))))
           (png (field reply "image" "path")))
      (assert (= sequence 1)) (assert (= (field reply "completed") 7))
      (assert (eq :false (field reply "session" "busy")))
      (assert (search typed (typed-events)))
      (format t "PASS: seven ordered actions, condition wait and screenshot in one call (~,3Fs), one sequence.~%"
              (/ (- (get-internal-real-time) started) internal-time-units-per-second))
      (with-open-file (out (merge-pathnames "build/agent-api-capture.png" root) :direction :output
                           :element-type '(unsigned-byte 8) :if-exists :supersede)
        (write-sequence (check-png png) out))
      (assert (equal "sequence-mismatch" (field (request (list :op "key" :token token :sequence sequence :key "a")) "error")))
      (assert (equal "invalid-batch" (field (send "batch" :actions #((:op "type" :text "FORBIDDEN") (:op "approve"))) "error")))
      (assert (= sequence 1))
      (let ((failed (send "batch" :capture :false :actions
                          #((:op "wait-window" :title "never-a-window-title" :timeout .1d0) (:op "type" :text "FORBIDDEN")))))
        (assert (equal "wait-timeout" (field failed "error")))
        (assert (zerop (field failed "completed"))) (assert (= sequence 2)))
      (let ((failed (send "batch" :capture :false :actions
                          (vector (list :op "focus" :window id) '(:op "move" :x 760 :y 55 :duration .016d0)
                                  '(:op "button") '(:op "type" :text "FORBIDDEN")))))
        (assert (equal "target-blocked" (field failed "error")))
        (assert (= 2 (field failed "completed"))) (assert (= 3 (field failed "failed-action"))))
      ;; Human pause interrupts an in-flight batch and releases its held key.
      (let* ((next (1+ sequence)) (interrupted nil)
             (thread (sb-thread:make-thread
                      (lambda ()
                        (setf interrupted (request (list :op "batch" :token token :sequence next :capture :false
                                                         :actions (vector (list :op "focus" :window id)
                                                                          '(:op "key" :key "Shift_L" :state "down")
                                                                          '(:op "move" :x 50 :y 50 :duration 2d0)
                                                                          '(:op "type" :text "FORBIDDEN")))))))))
        (loop repeat 100 for state = (send "status")
              when (equal "Moving cursor" (field state "session" "message")) return t do (sleep .025)
              finally (error "The batch never reached movement."))
        (assert (equal "busy" (field (send "key" :key "a") "error")))
        (mark "pause") (wait-state "paused")
        (sb-thread:join-thread thread)
        (assert (equal "batch-interrupted" (field interrupted "error")))
        (assert (= 2 (field interrupted "completed")))
        (assert (eq :false (field interrupted "session" "busy"))))
      (assert (not (probe-file png)))
      (assert (null (search "FORBIDDEN" (typed-events))))
      (assert (search " 0 65505 " (events)))
      (assert (equal "not-active" (field (send "observe") "error")))
      (assert (equal "not-active" (field (send "key" :key "a") "error")))
      (assert (equal "closed" (field (ok (send "disconnect")) "session" "state"))))
    (let ((reply (ok (request '(:op "connect" :name "Window agent" :purpose "Verify the default window view")))))
      (setf token (field reply "token") sequence 0)
      (assert (equal "window" (field reply "session" "view"))))
    (mark "resume") (wait-state "active")
    (assert (equal "window-required" (field (send "capture") "error")))
    (let* ((window (aref (field (ok (send "observe")) "windows") 0))
           (id (field window "id"))
           (reply (ok (send "batch" :actions (vector (list :op "focus" :window id)
                                                     '(:op "move" :x 45 :y 55 :duration .016d0)
                                                     '(:op "button")))))
           (png (field reply "image" "path")))
      (assert (equal "window" (field reply "image" "view")))
      (assert (= id (field reply "image" "window")))
      (assert (= 45 (field reply "session" "x")))
      (assert (= 55 (field reply "session" "y")))
      (check-png png 600 360)
      (let ((reply (ok (send "batch" :actions #((:op "key" :key "F12"))))))
        (assert (eq t (field reply "image" "settled")))
        (assert (>= (field reply "image" "wait-seconds") .2d0))
        (check-png (field reply "image" "path") 600 360 '(45 55 72 207 96 255)))
      (let ((reply (ok (send "batch" :settle 0 :actions #((:op "key" :key "F12"))))))
        (assert (eq :false (field reply "image" "settled")))
        (assert (zerop (field reply "image" "wait-seconds"))))
      (let ((reply (ok (send "batch" :actions #((:op "wait-stable" :settle .15d0 :timeout 2d0))))))
        (assert (= 1 (field reply "completed")))
        (check-png (field reply "image" "path") 600 360 '(45 55 72 207 96 255)))
      (assert (equal "invalid-wait"
                     (field (send "batch" :actions #((:op "type" :text "FORBIDDEN")
                                                       (:op "wait-stable" :settle .5d0 :timeout .1d0))) "error")))
      (ok (send "batch" :capture :false :actions #((:op "key" :key "F4"))))
      (let ((reply (send "batch" :actions #((:op "wait-stable" :settle .1d0 :timeout .2d0)
                                             (:op "type" :text "FORBIDDEN")))))
        (assert (equal "wait-timeout" (field reply "error")))
        (assert (zerop (field reply "completed"))))
      (let ((reply (ok (send "batch" :actions (vector (list :op "focus" :window id))))))
        (assert (eq :false (field reply "image" "settled")))
        (assert (<= 2d0 (field reply "image" "wait-seconds") 2.3d0)))
      (ok (send "batch" :capture :false :actions #((:op "key" :key "F4"))))
      (format t "PASS: settled batch capture follows delayed updates; explicit waits, opt-out, animation timeout and prevalidation work.~%")
      (let ((reply (ok (send "batch" :actions #((:op "view" :mode "desktop"))))))
        (assert (equal "desktop" (field reply "image" "view")))
        (check-png (field reply "image" "path")))
      (assert (not (probe-file png)))
      (ok (send "disconnect")))
    (format t "PASS: default window selection, local input and PNG, explicit desktop view over the native socket.~%")
    ;; A partly written request belongs to the listener which accepted it.
    ;; It must be closed, not admitted after that listener is replaced.
    (let ((socket (make-instance 'sb-bsd-sockets:local-socket :type :stream :protocol 0)))
      (unwind-protect
           (progn
             (sb-bsd-sockets:socket-connect socket socket-path)
             (with-open-stream (stream (sb-bsd-sockets:socket-make-stream socket :input t :output t
                                                                        :element-type '(unsigned-byte 8) :buffering :full :timeout 1))
               (write-sequence (sb-ext:string-to-octets
                                "{\"op\":\"connect\",\"name\":\"Stale request\",\"purpose\":\"Must not cross listener replacement\"}"
                                :external-format :utf-8) stream)
               (finish-output stream)
               (mark "restart")
               (loop repeat 100 until (probe-file (merge-pathnames "restarted" directory)) do (sleep .025d0)
                     finally (assert (probe-file (merge-pathnames "restarted" directory))))
               (assert (equal "PASS" (uiop:read-file-string (merge-pathnames "restarted" directory))))
               (let ((sent (handler-case (progn (write-byte 10 stream) (finish-output stream) t)
                             (sb-int:broken-pipe () nil))))
                 (when sent (assert (null (read-byte stream nil nil)) () "Old listener accepted a late request.")))
               (close stream :abort t)))
        (ignore-errors (sb-bsd-sockets:socket-close socket :abort t))))
    (ok (request '(:op "outputs")))
    (format t "PASS: listener replacement shuts down partial requests and the new listener remains usable.~%")
    (format t "PASS: native Lisp socket and CLI, quoted JSON, automatic activation, PNG, partial failure, sequence/replay, human interruption and disconnect.~%")))
