;;;; Camera geometry and per-output isolation on a plain Infinite World.
(load (merge-pathnames "system-support.lisp" *load-truename*))
(asdf:load-system "ataxia-computer-use/infinite-world")
(in-package #:ataxia.infinite-world)
(defclass viewport-test-world (infinite-world) ())
(defmethod ataxia.world:world-output-work-area ((world viewport-test-world) output)
  (multiple-value-bind (w h) (ataxia.world:output-logical-size output)
    (values 20d0 44d0 (- w 50d0) (- h 64d0))))
(let* ((world (make-instance 'viewport-test-world))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1000 :headless-height 700))
       (runtime (ataxia.kernel:kernel-runtime kernel)))
  (unwind-protect
       (progn
         (ataxia.kernel:start-kernel kernel)
         (ataxia.runtime.raw:%wlr-headless-add-output
          (ataxia.runtime::%object-pointer (ataxia.runtime:runtime-backend runtime)) 700 900)
         (let* ((outputs (ataxia.world:world-outputs world))
                (output (second outputs)) (state (gethash output (%world-outputs world)))
                (untouched (%desktop-viewport-camera world (gethash (first outputs) (%world-outputs world)))))
           (flet ((navigate (action &rest args) (apply #'ataxia.world:navigate-world-viewport world output action args))
                  (camera () (%desktop-viewport-camera world state)))
             (navigate :set :x -300d0 :y 120d0 :zoom .5d0 :rotation .2d0)
             (assert (equalp (camera) '(-300d0 120d0 .5d0 .2d0)))
             (navigate :pan :dx 100d0 :dy -50d0)
             (assert (equalp (camera) '(-200d0 70d0 .5d0 .2d0)))
             (multiple-value-bind (w h) (%output-logical-size state)
               (let ((center (multiple-value-list (%screen-to-world state (/ w 2d0) (/ h 2d0)))))
                 (navigate :set :zoom 2d0)
                 (assert (equalp center (multiple-value-list (%screen-to-world state (/ w 2d0) (/ h 2d0)))))))
             (dolist (angle (list 0d0 (/ pi 3d0) (- (/ pi 2d0))))
               (navigate :frame-region :x -900d0 :y 1200d0 :width 640d0 :height 480d0 :rotation angle :padding 30d0)
               (multiple-value-bind (wx wy ww wh) (%canvas-work-area world state)
                 (dolist (point '((-900d0 1200d0) (-260d0 1200d0) (-900d0 1680d0) (-260d0 1680d0)))
                   (multiple-value-bind (cx cy) (%world-to-canvas state (first point) (second point))
                     (multiple-value-bind (sx sy) (%canvas-to-screen state cx cy)
                       (assert (<= (- (+ wx 30d0) 1d-6) sx (+ (- (+ wx ww) 30d0) 1d-6)))
                       (assert (<= (- (+ wy 30d0) 1d-6) sy (+ (- (+ wy wh) 30d0) 1d-6))))))))
             (let ((before (camera)))
               (dolist (args '((:set :zoom 0) (:frame-region :x 0 :y 0 :width 100 :height -1)
                               (:frame-region :x 0 :y 0 :width 100 :height 100 :padding 10000)
                               (:frame-region :x 0 :y 0 :width 1000000000 :height 1000000000)))
                 (assert (handler-case (progn (apply #'navigate args) nil) (error () t)))
                 (assert (equalp before (camera)))))
             (let ((seat (%make-canvas-seat :human)) (before (camera)))
               (setf (gethash :human (%world-seats world)) seat
                     (gethash seat *canvas-gestures*) t)
               (unwind-protect
                    (progn
                      (assert (handler-case (progn (navigate :pan :dx 10 :dy 0) nil) (error () t)))
                      (assert (equalp before (camera))))
                 (remhash seat *canvas-gestures*) (remhash :human (%world-seats world))))
             (assert (equalp untouched (%desktop-viewport-camera world (gethash (first outputs) (%world-outputs world)))))
             (assert (ataxia.world:world-supports-p world :viewport-navigation))
             (assert (not (ataxia.world:world-supports-p world :shell-navigation)))
             (format t "PASS: independent output cameras, world pan, centered zoom, rotated region framing within reserved work areas, and validation before mutation.~%"))))
    (ataxia.kernel:destroy-kernel kernel :viewport-test-complete)))
