;;;; Separate Wayland and D-Bus environment for the Codex-compatible native adapter.
(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-computer-use/metaworld")
(in-package #:ataxia.infinite-world)
(defclass cua-test-world (metaworld)
  ((fail-next-layout :initform nil :accessor fail-next-layout)))
(defmethod ataxia.world:apply-world-layout :after ((world cua-test-world) operations ids)
  (declare (ignore operations ids))
  (when (fail-next-layout world)
    (setf (fail-next-layout world) nil)
    (error "Injected layout failure")))

(let* ((world (make-instance 'cua-test-world :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1000 :headless-height 760))
       (runtime (ataxia.kernel:kernel-runtime kernel))
       (directory (merge-pathnames (format nil "ataxia-cua-test-~A/" (ataxia.computer-use:random-token)) (uiop:temporary-directory)))
       (client nil) (checks nil) (control nil))
  (labels ((path (name) (namestring (merge-pathnames name directory)))
           (source (name) (namestring (asdf:system-relative-pathname "ataxia-computer-use" name)))
           (ui-action (name)
             (let* ((panel (first (ataxia.computer-use::computer-controller-panels (ataxia.computer-use::%computer-controller world))))
                    (component (overlay-component panel)))
               (assert (overlay-visible-p panel))
               (funcall (gethash name (ataxia.world.rmlui::%component-callbacks component)) component "")
               (assert (eql (overlay-visible-p panel) (not (equal name "stop0")))))))
    (unwind-protect
         (progn
           (sb-posix:mkdir directory #o700)
           (format t "CUA fixture directory: ~A~%" directory)
           (ataxia.kernel:start-kernel kernel)
           (setf control (ataxia.sly-control:start-sly-control kernel :port 4007))
           (slynk:stop-server 4007)
           (ataxia.computer-use:enable world :socket (path "computer-use.sock"))
           (setf checks (uiop:launch-program
                         (list (or (uiop:getenv "ATAXIA_CUA_NODE") "node") (source "tests/cua-native-client.mjs") (namestring directory))
                         :output (path "checks.log") :error-output :output))
           (let ((timer (ataxia.runtime:add-event-loop-timer runtime
                          (lambda (timer)
                            (dolist (action '(("resume" . "resume0") ("pause" . "pause0") ("pause-all" . "pause-all") ("stop" . "stop0")))
                              (when (probe-file (path (car action))) (delete-file (path (car action))) (ui-action (cdr action))))
                            (when (probe-file (path "fail-layout"))
                              (delete-file (path "fail-layout"))
                              (setf (fail-next-layout world) t)
                              (with-open-file (out (path "fail-layout-ready") :direction :output)
                                (write-line "ready" out)))
                            (when (probe-file (path "launch"))
                              (delete-file (path "launch"))
                              (setf client (uiop:launch-program
                                            (list "env" (format nil "WAYLAND_DISPLAY=~A" (ataxia.runtime:runtime-socket-name runtime))
                                                  "GDK_BACKEND=wayland" "GTK_MODULES=gail:atk-bridge" "NO_AT_BRIDGE=0" "GIO_USE_VFS=local"
                                                  "python3" (source "tests/cua-atspi-fixture.py") (path "ui.json"))
                                            :output (path "client.log") :error-output :output)))
                            (when (not (uiop:process-alive-p checks)) (ataxia.kernel:request-kernel-stop kernel :checks-complete))
                            (ataxia.runtime:update-event-loop-timer timer 50) 0))))
             (ataxia.runtime:update-event-loop-timer timer 50))
           (ataxia.kernel:run-kernel kernel :run-for 60d0)
           (write-string (uiop:read-file-string (path "checks.log")))
           (when (probe-file (path "client.log")) (write-string (uiop:read-file-string (path "client.log"))))
           (assert (not (uiop:process-alive-p checks)))
           (assert (zerop (uiop:wait-process checks)))
           (assert (eq :running (ataxia.kernel:kernel-world-status kernel)))
           (when (probe-file (path "native.png")) (uiop:copy-file (path "native.png") (source "build/cua-native.png"))))
      (ataxia.computer-use:disable world)
      (dolist (state (%seat-states world)) (%focus-target world state nil))
      (when control (ataxia.sly-control:stop-sly-control control))
      (dolist (process (list checks client)) (when process (ignore-errors (uiop:terminate-process process))))
      (ataxia.kernel:destroy-kernel kernel :cua-test-complete))))
