;;;; Connections survive World replacement, but never native pointer reuse.
(load (merge-pathnames "system-support.lisp" *load-truename*))
(asdf:load-system "ataxia-kernel")
(in-package #:ataxia.kernel)
(setf (uiop:getenv "WLR_RENDERER") "gles2")
(defclass client-test-world (world)
  ((kernel :initform nil :accessor world-kernel)))
(defmethod world-attached ((world client-test-world) kernel) (setf (world-kernel world) kernel))
(defmethod world-detached ((world client-test-world) kernel)
  (declare (ignore kernel)) (setf (world-kernel world) nil))
(defmethod world-quiescing ((world client-test-world) reason) (declare (ignore reason)))
(defmethod world-output-added ((world client-test-world) output) (declare (ignore output)))
(defmethod world-output-removing ((world client-test-world) output) (declare (ignore output)))
(defmethod world-seat-added ((world client-test-world) seat) (declare (ignore seat)))
(defmethod world-seat-removing ((world client-test-world) seat) (declare (ignore seat)))
(let* ((kernel (create-kernel (make-instance 'client-test-world) :backend :headless :socket-p nil))
       (runtime (kernel-runtime kernel))
       (native nil) (peer nil) (identities nil)
       (listeners (hash-table-count ataxia.runtime::*subscription-registry*)))
  (labels ((connect-client ()
             (cffi:with-foreign-object (fds :int 2)
               (assert (zerop (cffi:foreign-funcall "socketpair" :int 1 :int 1 :int 0 :pointer fds :int)))
               (setf peer (cffi:mem-aref fds :int 1)
                     native (cffi:foreign-funcall "wl_client_create"
                              :pointer (ataxia.runtime::%object-pointer (ataxia.runtime:runtime-display runtime))
                              :int (cffi:mem-aref fds :int 0) :pointer)))
             (assert (not (cffi:null-pointer-p native)))
             (ataxia.runtime::%adopt-client runtime native))
           (disconnect-client ()
             (when native (cffi:foreign-funcall "wl_client_destroy" :pointer native :void) (setf native nil))
             (when peer (cffi:foreign-funcall "close" :int peer :int) (setf peer nil))))
    (unwind-protect
         (progn
           (ataxia.runtime::%load-client-library)
           (dotimes (iteration 12)
             (let* ((wrapper (connect-client))
                    (identity (%ensure-wayland-client kernel wrapper)))
               (assert (typep wrapper 'ataxia.runtime:wl-client))
               (assert (typep identity 'wayland-client))
               (assert (not (typep identity 'ataxia.runtime::native-object)))
               (assert (eq wrapper (ataxia.runtime::%adopt-client runtime native)))
               (assert (eq identity (find-kernel-object kernel (object-id identity))))
               (assert (eq identity (%ensure-wayland-client kernel wrapper)))
               (when (zerop iteration)
                 (install-world kernel (make-instance 'client-test-world))
                 (assert (eq identity (%ensure-wayland-client kernel wrapper))))
               (assert (not (member (object-id identity) identities)))
               (push (object-id identity) identities)
               (disconnect-client)
               (assert (not (ataxia.runtime:native-object-live-p wrapper)))
               (assert (eq :retired (object-state identity)))
               (assert (null (find-kernel-object kernel (object-id identity))))
               (assert (null (%find-runtime-object kernel wrapper)))
               (assert (zerop (hash-table-count (ataxia.runtime::%runtime-client-table runtime)))))
             (assert (= listeners (hash-table-count ataxia.runtime::*subscription-registry*))))
           ;; Failed listener allocation must not leave a subscription behind.
           (assert (handler-case
                       (progn
                         (ataxia.runtime::%attach-listener runtime :allocation-test #'identity
                           (lambda (&rest args) (declare (ignore args)) (cffi:null-pointer))
                           (lambda (cell) (declare (ignore cell)) (error "Unexpected destroy")))
                         nil)
                     (ataxia.runtime:native-call-failed () t)))
           (assert (= listeners (hash-table-count ataxia.runtime::*subscription-registry*)))
           ;; Teardown also retires live connection tokens and their wrappers.
           (let* ((wrapper (connect-client)) (identity (%ensure-wayland-client kernel wrapper)))
             (destroy-kernel kernel :test)
             (setf native nil)
             (assert (eq :retired (object-state identity)))
             (assert (not (ataxia.runtime:native-object-live-p wrapper)))
             (assert (zerop (hash-table-count ataxia.runtime::*subscription-registry*))))
           (format t "PASS: Kernel-owned connection identity, World replacement, disconnect/reconnect, listener rollback and teardown.~%"))
      (disconnect-client)
      (when (kernel-runtime kernel) (destroy-kernel kernel :test)))))
