(load (merge-pathnames "support.lisp" *load-truename*))
(in-package #:ataxia.kernel)

(flet ((rectangle (damage)
         (list (frame-damage-rectangle-x damage) (frame-damage-rectangle-y damage)
               (frame-damage-rectangle-width damage) (frame-damage-rectangle-height damage))))
  (let* ((root (make-instance 'surface-node :id 1 :state :live :mapped-p t :width 600 :height 360))
         (popup (make-instance 'surface-node :id 2 :state :live :mapped-p t :width 80 :height 40))
         (nested (make-instance 'surface-node :id 3 :state :live :mapped-p t :width 10 :height 10))
         (app (make-instance 'wayland-application :id 4 :state :live :root-surface root)))
    (setf (%surface-application root) app)
    (dolist (surface (list root popup nested))
      (setf (%surface-render-source surface) (make-instance 'render-source)
            (%surface-source-box surface) #(0d0 0d0 1d0 1d0)))
    (%attach-surface-child root popup 25d0 -3.5d0)
    (%attach-surface-child popup nested -2.25d0 1d0)
    (setf (%surface-damage root) (list (make-frame-damage-rectangle 0 0 600 360))
          (%surface-damage popup) (list (make-frame-damage-rectangle 0 0 80 40))
          (%surface-damage nested) (list (make-frame-damage-rectangle 1 2 3 4)))
    (let ((damage (mapcar #'rectangle (%rebuild-application-drawables app)))
          (surfaces (drawable-surfaces app)))
      (dolist (expected '((0 0 600 360) (25 -4 80 41) (23 -1 4 5)))
        (assert (member expected damage :test #'equal)))
      (assert (every (lambda (r) (every #'integerp r)) damage))
      ;; Drawable placement keeps precision; only pixel coverage is rounded.
      (assert (= 25d0 (drawable-surface-local-x (aref surfaces 1))))
      (assert (= -3.5d0 (drawable-surface-local-y (aref surfaces 1))))
      (assert (= 22.75d0 (drawable-surface-local-x (aref surfaces 2))))))
  (assert (equal '((25 -4 80 41))
                 (mapcar #'rectangle
                         (%runtime-damage-rectangles
                          (list (ataxia.runtime:make-damage-rectangle 0 0 80 40)) 25d0 -3.5d0)))))
(format t "PASS: popup and nested-popup damage accepts floating positions, covers fractional edges, and preserves drawable coordinates.~%")
