(load (merge-pathnames "support.lisp" *load-truename*))
(in-package #:ataxia.kernel)

(labels ((surface (id x y width height)
           (let ((node (make-instance 'surface-node :id id :state :live :mapped-p t
                                      :local-x x :local-y y :width width :height height)))
             (setf (%surface-render-source node) (make-instance 'render-source)
                   (%surface-source-box node) #(0d0 0d0 1d0 1d0)
                   (%surface-protocol-token node)
                   (make-instance 'surface-protocol-token :surface node :generation 0))
             node))
         (covers (damage x y)
           (some (lambda (r)
                   (and (<= (frame-damage-rectangle-x r) x)
                        (< x (+ (frame-damage-rectangle-x r) (frame-damage-rectangle-width r)))
                        (<= (frame-damage-rectangle-y r) y)
                        (< y (+ (frame-damage-rectangle-y r) (frame-damage-rectangle-height r)))))
                 damage)))
  (let* ((root (surface 1 0 0 200 100))
         (child (surface 2 10 20 20 20))
         (app (make-instance 'wayland-application :id 3 :state :live :root-surface root)))
    (%attach-surface-child root child 10 20)
    (let ((damage (%rebuild-application-drawables app)))
      (assert (covers damage 0 0))
      (assert (covers damage 199 99)))
    (assert (null (%rebuild-application-drawables app)))
    ;; Losing an opacity guarantee must repaint layers previously skipped.
    (setf (%surface-opaque-region child) (list (make-frame-damage-rectangle 0 0 20 20)))
    (assert (covers (%rebuild-application-drawables app) 15 25))
    (assert (null (%rebuild-application-drawables app)))
    (setf (%surface-opaque-region child) nil)
    (assert (covers (%rebuild-application-drawables app) 15 25))
    (setf (surface-local-x child) 220)
    (let ((damage (%rebuild-application-drawables app)))
      (assert (covers damage 10 20))
      (assert (covers damage 239 39))
      (assert (not (covers damage 0 0))))
    (assert (null (%rebuild-application-drawables app)))
    (setf (surface-mapped-p child) nil)
    (let ((damage (%rebuild-application-drawables app)))
      (assert (= 1 (length (drawable-surfaces app))))
      (assert (covers damage 239 39)))
    (setf (surface-mapped-p child) t (surface-width child) 35)
    (assert (covers (%rebuild-application-drawables app) 254 39))
    (setf (surface-local-x child) -2.5d0 (surface-local-y child) -1.25d0)
    (let ((damage (%rebuild-application-drawables app)))
      (assert (covers damage -3 -2))
      (assert (covers damage 32 18))
      (assert (covers damage 254 39)))
    (setf (surface-children root) nil)
    (assert (covers (%rebuild-application-drawables app) -3 -2))
    (assert (null (%rebuild-application-drawables app)))
    (let ((other (surface 4 10 20 20 20)))
      (setf (surface-local-x child) 10 (surface-local-y child) 20
            (surface-children root) (list child other))
      (%rebuild-application-drawables app)
      (setf (surface-children root) (list other child))
      (let ((damage (%rebuild-application-drawables app)))
        (assert (covers damage 10 20))
        (assert (not (covers damage 0 0))))
      (assert (null (%rebuild-application-drawables app))))))
(format t "PASS: surface map, move, unmap, removal and stacking damage old/new coverage without client buffer damage; unchanged layouts remain idle.~%")
