;;;; Installed application discovery, without a compositor or user files.
(load (merge-pathnames "support.lisp" *load-truename*))
(in-package #:ataxia.infinite-world)
(let* ((root (merge-pathnames (format nil "ataxia-catalog-~D-~D/" (sb-posix:getpid) (get-universal-time))
                             (uiop:temporary-directory)))
       (user-data (merge-pathnames "user/" root))
       (system-data (merge-pathnames "system/" root))
       (export-data (merge-pathnames "snap-export/" root)))
  (labels ((entry (directory id name &optional extra)
             (let ((path (merge-pathnames (format nil "applications/~A.desktop" id) directory)))
               (ensure-directories-exist path)
               (with-open-file (out path :direction :output :if-exists :supersede)
                 (format out "[Desktop Entry]~%Type=Application~%Name=~A~%Exec=/bin/true~%~A" name (or extra "")))
               path)))
    (unwind-protect
         (progn
           (entry system-data "calculator" "System calculator")
           (entry user-data "calculator" "User calculator")
           (entry system-data "hidden" "System hidden")
           (entry user-data "hidden" "Hidden override" "Hidden=true")
           (entry system-data "nodisplay" "System display")
           (entry user-data "nodisplay" "NoDisplay override" "NoDisplay=true")
           (entry export-data "firefox_firefox" "Firefox")
           (entry export-data "org.example.Flatpak" "Flatpak export")
           (let* ((directories (%desktop-data-directories (namestring user-data)
                                 (format nil "~A:relative:~A::~A" system-data export-data system-data)))
                  (entries (%load-desktop-entries directories)))
             (assert (equal directories (list user-data system-data export-data)))
             (assert (= 3 (length entries)))
             (assert (find "firefox_firefox" entries :key #'%desktop-entry-id :test #'equal))
             (assert (find "org.example.Flatpak" entries :key #'%desktop-entry-id :test #'equal))
             (assert (equal "User calculator" (%desktop-entry-name (find "calculator" entries :key #'%desktop-entry-id :test #'equal)))))
           (assert (equal (rest (%desktop-data-directories "" "")) '(#P"/usr/local/share/" #P"/usr/share/")))
           (assert (equal (first (%desktop-data-directories "relative" ""))
                          (merge-pathnames #P".local/share/" (user-homedir-pathname))))
           (format t "PASS: XDG app discovery, exported Firefox/Flatpak entries, user precedence, hidden masks and invalid/default paths.~%"))
      (uiop:delete-directory-tree root :validate t :if-does-not-exist :ignore))))
