;;;; Run: sbcl --script tests/metaworld-motion.lisp
(require :asdf)
(let ((root (uiop:pathname-parent-directory-pathname
             (uiop:pathname-directory-pathname *load-truename*))))
  (asdf:initialize-source-registry
   `(:source-registry (:tree ,root)
     (:tree ,(merge-pathnames "fun/ataxia-deps/common-lisp/" (user-homedir-pathname)))
     :inherit-configuration))
  (asdf:load-system "ataxia-metaworld"))
(in-package #:ataxia.infinite-world)

(defvar *test-clock* 0d0)
(defvar *test-configures* 0)
(defun test-window (world x y)
  (let* ((application (make-instance 'ataxia.kernel:wayland-application))
         (window (make-instance 'canvas-window :application application
                                :x x :y y :width 200d0 :height 100d0)))
    (setf (gethash application (%world-windows world)) window
          (%canvas-window-mapped-p window) t)
    window))
(defun step-motion (world time)
  (setf *test-clock* time)
  (ataxia.world:advance-animations (%world-animator world) time))
(defun close-geometry-p (a b)
  (every (lambda (x y) (< (abs (- x y)) 0.00001d0)) a b))

;; Stub only the external display/configuration boundary. Exercise the real
;; layout, animator, drop planner and geometry setters with a deterministic clock.
(let* ((names '(%now %damage-window %update-window-membership %request-all-frames %request-output-state-frame
                %meta-changed %screen-to-world %meta-set-camera
                ataxia.kernel:request-object-configuration))
       (saved (mapcar #'symbol-function names)))
  (unwind-protect
       (progn
         (setf (symbol-function '%now) (lambda () *test-clock*)
               (symbol-function '%damage-window) (lambda (&rest args) (declare (ignore args)))
               (symbol-function '%update-window-membership) (lambda (&rest args) (declare (ignore args)))
               (symbol-function '%request-all-frames) (lambda (&rest args) (declare (ignore args)))
               (symbol-function '%request-output-state-frame) (lambda (&rest args) (declare (ignore args)))
               (symbol-function '%meta-changed) #'identity
               (symbol-function '%screen-to-world) (lambda (state x y) (declare (ignore state)) (values x y))
               (symbol-function '%meta-set-camera)
               (lambda (world state camera)
                 (declare (ignore world))
                 (setf (%canvas-output-camera-x state) (first camera)
                       (%canvas-output-camera-y state) (second camera)
                       (%canvas-output-zoom state) (third camera)
                       (%canvas-output-rotation state) (fourth camera)))
               (symbol-function 'ataxia.kernel:request-object-configuration)
               (lambda (&rest args) (declare (ignore args)) (incf *test-configures*)))
         (let* ((world (make-metaworld :state-file nil)) (window (test-window world 10d0 20d0))
                (*meta-layout-motion* t) (*test-clock* 0d0) (*test-configures* 0)
                (origin (%meta-object-geometry window)))
           (%meta-place world window 400d0 500d0 600d0 700d0)
           (%meta-place world window 900d0 800d0 600d0 700d0)
           (assert (equal origin (%meta-object-geometry window)))
           (assert (= 1 *test-configures*))
           (step-motion world .08d0)
           (let ((displayed (%meta-object-geometry window))
                 (motion (gethash window (%meta-motions world))))
             ;; An unchanged plan neither restarts nor teleports an animation.
             (%meta-place world window 900d0 800d0 600d0 700d0)
             (assert (eq motion (gethash window (%meta-motions world))))
             (%meta-place world window 1200d0 900d0 700d0 800d0)
             (assert (equal displayed (%meta-object-geometry window)))
             (assert (plusp (first (%meta-trajectory-velocity (gethash window (%meta-motions world)))))))
           (step-motion world .5d0)
           (assert (close-geometry-p (%meta-object-geometry window) '(1200d0 900d0 700d0 800d0)))
           (assert (zerop (hash-table-count (%meta-motions world))))
           ;; A direct pointer move cancels any old trajectory permanently.
           (%meta-place world window 100d0 200d0 700d0 800d0)
           (let ((*meta-layout-motion* nil)) (%meta-place world window 42d0 57d0 700d0 800d0))
           (step-motion world 1d0)
           (assert (= 42d0 (canvas-window-x window)))
           (assert (= 57d0 (canvas-window-y window))))
         (let* ((world (make-metaworld :state-file nil)) (*test-clock* 0d0)
                (window (test-window world 0d0 0d0)) (*meta-layout-motion* t))
           (%meta-place world window 300d0 400d0 200d0 100d0)
           (step-motion world .08d0)
           (let ((before (%meta-object-geometry window))
                 (motion (gethash window (%meta-motions world))))
             (%meta-translate-object world window 50d0 -30d0)
             (assert (eq motion (gethash window (%meta-motions world))))
             (assert (= (+ 50d0 (first before)) (canvas-window-x window)))
             (assert (= (- (second before) 30d0) (canvas-window-y window))))
           (step-motion world .5d0)
           (assert (close-geometry-p (%meta-object-geometry window) '(350d0 370d0 200d0 100d0))))
         (format t "PASS: moving groups carry in-flight child trajectories without freezing or snapping.~%")
         (format t "PASS: repeated layout, retarget continuity, size interpolation, bounded configures, direct grab cancellation.~%")
         (let* ((world (make-metaworld :state-file nil)) (*test-clock* 0d0)
                (a (test-window world 16d0 52d0)) (b (test-window world 230d0 52d0))
                (group (%make-subworld :id 1 :kind :niri :next-column 2))
                (ma (%make-subworld-member :object a :column 1 :width 200d0))
                (mb (%make-subworld-member :object b :column 2 :width 200d0))
                (seat (%make-canvas-seat :test)))
           (setf (metaworld-subworlds world) (list group)
                 (subworld-members group) (list ma mb)
                 (gethash a (%meta-owners world)) group (gethash b (%meta-owners world)) group
                 (gethash :test (%world-seats world)) seat
                 (%canvas-seat-operation seat) (%make-canvas-operation :kind :move :window a)
                 (%canvas-seat-x seat) 300d0 (%canvas-seat-y seat) 60d0
                 (canvas-window-x a) 280d0 (canvas-window-y a) 40d0)
           (%meta-drop-object world a seat)
           (assert (equalp (%meta-object-geometry a) '(280d0 40d0 200d0 100d0)))
           (assert (= (subworld-member-column ma) (subworld-member-column mb)))
           (assert (gethash b (%meta-motions world)))
           (let ((motion (gethash b (%meta-motions world))) (column (subworld-next-column group)))
             (%meta-drop-object world a seat)
             (assert (= column (subworld-next-column group)))
             (assert (eq motion (gethash b (%meta-motions world)))))
           (step-motion world .08d0)
           ;; Release retains the shown preview and begins at the actual grab.
           (setf (%canvas-seat-operation seat) nil)
           (%meta-drop-object world a seat)
           (assert (equalp (%meta-object-geometry a) '(280d0 40d0 200d0 100d0)))
           (assert (gethash a (%meta-motions world)))
           (step-motion world .5d0)
           (assert (= 0d0 (canvas-window-x a)))
           (assert (= 0d0 (canvas-window-y a)))
           (assert (> (canvas-window-y b) (canvas-window-y a))))
         (format t "PASS: live reflow, grabbed window isolation, stable insertion, release from displayed position.~%")
         (let* ((world (make-metaworld :state-file nil)) (*test-clock* 0d0)
                (state (%make-canvas-output nil)) (origin (%meta-camera state)))
           (%meta-set-camera world state '(500d0 700d0 0.5d0 0d0))
           (%meta-transition-camera world state origin)
           (assert (equalp origin (%meta-camera state)))
           (step-motion world .08d0)
           (let ((shown (%meta-camera state)))
             (%meta-set-camera world state '(1000d0 1400d0 0.25d0 0d0))
             (%meta-transition-camera world state shown)
             (assert (equalp shown (%meta-camera state))))
           (%meta-cancel-motion world state :metaworld-camera)
           (let ((shown (%meta-camera state)))
             (step-motion world 1d0)
             (assert (equalp shown (%meta-camera state)))))
         (format t "PASS: interrupted camera continuity and direct-input cancellation.~%")
         (let* ((world (make-metaworld :state-file nil)) (*test-clock* 0d0)
                (group (%make-subworld :id 1 :kind :niri :next-column 2))
                (windows (loop repeat 4 collect (test-window world 0d0 0d0)))
                (members (loop for w in windows for ws in '(1 1 2 2) for col in '(1 2 1 2)
                               for width in '(300d0 400d0 500d0 700d0)
                               collect (%make-subworld-member :object w :workspace ws :column col :width width))))
           (setf (metaworld-subworlds world) (list group) (subworld-members group) members)
           (loop for w in windows do (setf (gethash w (%meta-owners world)) group))
           (%meta-layout world group)
           (step-motion world .5d0)
           (%meta-resize-tile world (first windows) :right)
           (assert (= 380d0 (subworld-member-width (first members))))
           (assert (= 500d0 (subworld-member-width (third members))))
           (assert (= 700d0 (subworld-member-width (fourth members))))
           (%meta-cancel-motion world (first windows) :metaworld-layout)
           (setf (canvas-window-width (first windows)) 333d0)
           (%meta-drop-object world (first windows) nil t)
           (assert (= 333d0 (subworld-member-width (first members))))
           (assert (= 500d0 (subworld-member-width (third members))))
           (%meta-reorder world (first windows) :right group)
           (assert (equal (list (third members) (fourth members)) (%meta-workspace-members group 2)))
           ;; Plan several intermediate widths; clients see only the final one.
           (let ((*test-configures* 0))
             (%with-meta-layout-batch (world)
               (setf (subworld-member-width (first members)) 600d0)
               (%meta-layout world group)
               (setf (subworld-member-width (first members)) 800d0)
               (%meta-layout world group))
             (assert (= *test-configures* 1))))
         (format t "PASS: reused column IDs remain workspace-local for keyboard resize, drag resize and reordering; batched layouts configure once.~%")
         (dolist (output-scale '(1d0 1.25d0 2d0))
           (dolist (zoom '(0.25d0 0.75d0 1d0 1.5d0 3d0))
             (let ((scale (%overlay-raster-scale 320d0 180d0 (* zoom 320d0) (* zoom 180d0)
                                                  output-scale 1d0 16384)))
               (assert (>= scale (* 2d0 output-scale zoom)))
               (assert (= scale (%overlay-raster-scale 320d0 180d0 (* zoom 320d0) (* zoom 180d0)
                                                       output-scale scale 16384))))))
         (let ((scale (%overlay-raster-scale 1000d0 500d0 100000d0 50000d0 2d0 1d0 4096)))
           (assert (<= (* 1000d0 scale) 4096d0))
           (assert (<= (* 1000d0 500d0 scale scale) 16777216d0)))
         (assert (= 4d0 (%overlay-raster-scale 320d0 180d0 480d0 270d0 1d0 4d0 16384)))
         (format t "PASS: display-density rasterization, fractional scale, stable zoom buckets and texture limits.~%")
         ;; Hermite bounds protect resize dimensions and zoom during reversals.
         (loop for p from 0d0 to 1d0 by .01d0 do
           (multiple-value-bind (position velocity)
               (%meta-motion-sample '(100d0) '(1d0) '(-297d0) 1d0 p)
             (declare (ignore velocity))
             (assert (<= .99999d0 (first position) 100.00001d0))))
         (format t "PASS: monotonic bounded motion.~%"))
    (loop for name in names for function in saved do (setf (symbol-function name) function))))

;; Every world point follows a straight screen-space segment while zooming.
(dolist (pair '(((100d0 -200d0 0.2d0 0d0) (1400d0 900d0 1.2d0 0d0))
                ((1400d0 900d0 1.2d0 0d0) (100d0 -200d0 0.2d0 0d0))))
  (destructuring-bind (origin destination) pair
    (loop for i from 0 to 100 for p = (/ i 100d0)
          for camera = (%meta-camera-sample origin destination p)
          do (dolist (point '((0d0 0d0) (1800d0 1300d0) (-900d0 600d0)))
               (loop for axis below 2
                     for start = (* (- (nth axis point) (nth axis origin)) (third origin))
                     for end = (* (- (nth axis point) (nth axis destination)) (third destination))
                     for actual = (* (- (nth axis point) (nth axis camera)) (third camera))
                     do (assert (< (abs (- actual (+ start (* p (- end start))))) 0.000001d0)))))))
(assert (< (abs (- pi (fourth (%meta-camera-sample '(0d0 0d0 1d0 3d0)
                                                               '(0d0 0d0 1d0 -3d0) 0.5d0))))
           0.000001d0))
(format t "PASS: zoom-in/out screen paths remain straight; rotations take the short arc.~%")
