;;;; Run: sbcl --script tests/metaworld-chrome.lisp
(load (merge-pathnames "support.lisp" *load-truename*))
(in-package #:ataxia.infinite-world)

(defclass test-chrome-drawable (ataxia.kernel:drawable ataxia.kernel:interactable) ())
(let* ((clock 0d0) (handler nil) (command nil)
       (names '(%now %output-logical-size %damage-overlay %request-all-frames
                %request-output-state-frame %schedule-component-timer %meta-property
                %window-canvas-geometry %screen-to-canvas %canvas-to-screen
                %meta-reposition-ui %meta-ui-widget bind-agent-widget-event %meta-focus %meta-command enter-subworld leave-subworld))
       (saved (mapcar #'symbol-function names)))
  (unwind-protect
       (progn
         (setf (symbol-function '%now) (lambda () clock)
               (symbol-function '%output-logical-size) (lambda (state) (declare (ignore state)) (values 1000d0 700d0)))
         (dolist (name '(%damage-overlay %request-all-frames %request-output-state-frame
                         %schedule-component-timer %meta-property))
           (setf (symbol-function name) (lambda (&rest args) (declare (ignore args)))))
         (setf (symbol-function '%meta-focus) (lambda (&rest args) (declare (ignore args)))
               (symbol-function '%meta-command) (lambda (world seat action) (declare (ignore world seat)) (setf command action)))
         (setf (symbol-function '%window-canvas-geometry)
               (lambda (state w) (declare (ignore state))
                 (values (canvas-window-x w) (canvas-window-y w) (canvas-window-width w) (canvas-window-height w)))
               (symbol-function '%screen-to-canvas) (lambda (state x y) (declare (ignore state)) (values x y))
               (symbol-function '%canvas-to-screen) (lambda (state x y) (declare (ignore state)) (values x y))
               (symbol-function '%meta-reposition-ui)
               (lambda (world w x y width height) (declare (ignore world))
                 (setf (canvas-overlay-x w) x (canvas-overlay-y w) y
                       (canvas-overlay-width w) width (canvas-overlay-height w) height))
               (symbol-function 'bind-agent-widget-event)
               (lambda (widget name function) (declare (ignore widget name)) (setf handler function))
               (symbol-function '%meta-ui-widget)
               (lambda (world name component state width height &key layer)
                 (declare (ignore name component layer))
                 (let ((widget (make-instance 'meta-chrome-widget :id 1 :world world
                                             :component (make-instance 'test-chrome-drawable)
                                             :output (%canvas-output-output state) :x 0d0 :y 0d0
                                             :width width :height height :visible-p nil :opacity 0d0)))
                   (push widget (world-overlays world)) widget)))
         (let* ((world (make-metaworld :state-file nil)) (state (%make-canvas-output nil))
                (seat (%make-canvas-seat :test)) (view (%meta-view-for-state world state)))
           (setf (gethash :test (%world-seats world)) seat (%canvas-seat-output seat) state
                 (%canvas-seat-x seat) 100d0 (%canvas-seat-y seat) 2d0)
           (%meta-update-toolbar-intent world state)
           (assert (zerop (%meta-view-panel-until view)))
           (setf (%canvas-seat-x seat) 500d0)
           (%meta-update-toolbar-intent world state)
           (setf clock .2d0) (%meta-update-toolbar-intent world state)
           (assert (zerop (%meta-view-panel-until view)))
           (setf clock .36d0) (%meta-update-toolbar-intent world state)
           (assert (> (%meta-view-panel-until view) clock))
           (setf (%canvas-seat-operation seat) (%make-canvas-operation :kind :pan))
           (%meta-update-toolbar-intent world state)
           (assert (zerop (%meta-view-panel-until view))))
         (format t "PASS: toolbar ignores incidental edge crossings, requires deliberate dwell and yields to dragging.~%")
         (let* ((world (make-metaworld :state-file nil)) (state (%make-canvas-output nil))
                (group (first (metaworld-subworlds world))) (view (%meta-view-for-state world state))
                (route nil) (header (%meta-header world state group)))
           (setf (symbol-function 'enter-subworld) (lambda (&rest args) (declare (ignore args)) (setf route :enter))
                 (symbol-function 'leave-subworld) (lambda (&rest args) (declare (ignore args)) (setf route :leave)))
           (funcall handler header nil) (assert (eq route :enter))
           (setf (%meta-view-active view) group)
           (funcall handler header nil) (assert (eq route :leave))
           (setf (%meta-standalone world) :niri)
           (funcall handler header nil) (assert (equal command "mode-canvas")))
         (format t "PASS: overview headers enter; active breadcrumbs leave; standalone breadcrumbs return to canvas.~%")
         (let* ((world (make-metaworld :state-file nil)) (state (%make-canvas-output nil))
                (seat (%make-canvas-seat :test)) (view (%meta-view-for-state world state))
                (window (make-instance 'canvas-window :application (make-instance 'ataxia.kernel:wayland-application)
                                       :x 50d0 :y 100d0 :width 400d0 :height 300d0)))
           (setf clock 0d0 (%canvas-window-mapped-p window) t
                 (gethash :test (%world-seats world)) seat (%canvas-seat-output seat) state
                 (%canvas-seat-focused seat) window (%canvas-seat-x seat) 440d0 (%canvas-seat-y seat) 105d0)
           (%meta-sync-object-controls world state)
           (setf clock .2d0) (%meta-sync-object-controls world state)
           (assert (null (%meta-view-window-controls view)))
           (setf clock .5d0) (%meta-sync-object-controls world state)
           (let ((panel (%meta-view-window-controls view)))
             (assert panel) (assert (= 48d0 (canvas-overlay-width panel)))
             (assert (= 64d0 (canvas-overlay-height panel)))
             (assert (zerop (canvas-overlay-opacity panel)))
             (ataxia.world:advance-animations (%world-animator world) .7d0)
             (assert (= 1d0 (canvas-overlay-opacity panel)))
             (assert (%meta-transient-ui-active-p world))
             ;; An icon invokes its action directly, with no expanded menu.
             (setf clock .7d0)
             (funcall handler panel (ataxia.world::%make-agent-widget-event 1 "action" "close" clock))
             (assert (equal command "close"))
             (%meta-sync-object-controls world state)
             (assert (not (overlay-input-enabled-p panel)))
             (assert (canvas-overlay-visible-p panel))
             (ataxia.world:advance-animations (%world-animator world) 2.2d0)
             (assert (not (canvas-overlay-visible-p panel)))
             ;; Reversing a fade never flashes to its old endpoint.
             (setf clock 3d0) (%meta-present-ui world panel t)
             (ataxia.world:advance-animations (%world-animator world) 3.08d0)
             (let ((opacity (canvas-overlay-opacity panel)))
               (setf clock 3.08d0) (%meta-present-ui world panel nil)
               (assert (= opacity (canvas-overlay-opacity panel))))
             (setf clock 3.08d0) (%meta-present-ui world panel t)
             (ataxia.world:advance-animations (%world-animator world) 3.5d0)
             (assert (= 1d0 (canvas-overlay-opacity panel)))))
         (format t "PASS: focused-corner dwell, direct icon actions, fade continuity and immediate click-through on dismissal.~%"))
    (loop for name in names for function in saved do (setf (symbol-function name) function))))
