;;;; Run: sbcl --script tests/metaworld-idle.lisp
(load (merge-pathnames "support.lisp" *load-truename*))
(in-package #:ataxia.infinite-world)

;;;; Deadline scheduling must not poll idle UI or disabled persistence.
(let* ((world (make-metaworld :state-file nil))
       (state (%make-canvas-output nil))
       (seat (%make-canvas-seat :test))
       (view (%meta-view-for-state world state))
       (chrome (%meta-chrome-for-state world state))
       (clock 10d0) (original (symbol-function '%now)))
  (unwind-protect
       (progn
         (setf (symbol-function '%now) (lambda () clock)
               (gethash :test (%world-outputs world)) state
               (gethash :test (%world-seats world)) seat
               (%canvas-seat-output seat) state)
         (assert (zerop (%meta-maintenance-delay world)))
         (setf (%meta-save-needed-p world) t)
         (assert (zerop (%meta-maintenance-delay world)))
         (setf (%meta-chrome-edge-since chrome) clock)
         (assert (<= 350 (%meta-maintenance-delay world) 351))
         (setf clock 11d0 (%meta-view-panel-until view) 11.6d0)
         (assert (zerop (%meta-maintenance-delay world)))
         (setf (%meta-chrome-edge-since chrome) nil)
         (assert (<= 600 (%meta-maintenance-delay world) 601))
         (setf clock 12d0)
         (assert (zerop (%meta-maintenance-delay world)))
         (setf clock 13d0)
         (setf (slot-value world 'state-file) #P"/tmp/ataxia-idle-test.sexp"
               (%meta-last-save world) 12.8d0)
         (assert (<= 300 (%meta-maintenance-delay world) 301))
         (setf clock 14d0)
         (assert (<= 1 (%meta-maintenance-delay world) 2))
         (setf (%meta-save-needed-p world) nil)
         (assert (zerop (%meta-maintenance-delay world)))
         (format t "PASS: idle disarm, hover dwell/expiry/hold and deferred save deadlines.~%"))
    (setf (symbol-function '%now) original)))
(defclass idle-test-ui (ataxia.kernel:drawable)
  ((delay :initform nil :accessor idle-ui-delay)
   (active :initform nil :accessor idle-ui-active)))
(defmethod ataxia.world:ui-next-update-delay ((component idle-test-ui)) (idle-ui-delay component))
(defmethod ataxia.kernel:drawable-active-p ((component idle-test-ui)) (idle-ui-active component))
(let* ((world (make-metaworld :state-file nil))
       (first (make-instance 'idle-test-ui)) (second (make-instance 'idle-test-ui))
       (output-one (make-instance 'ataxia.kernel:kernel-output :width 320 :height 200 :scale 1d0 :transform 0))
       (output-two (make-instance 'ataxia.kernel:kernel-output :width 320 :height 200 :scale 1d0 :transform 0))
       (state-one (%make-canvas-output output-one)) (state-two (%make-canvas-output output-two))
       (one (make-canvas-overlay first output-one 0 0 100 100 :visible-p t))
       (two (make-canvas-overlay second output-two 0 0 100 100 :visible-p t))
       (timer-original (symbol-function 'ataxia.runtime:update-event-loop-timer))
       (frame-original (symbol-function '%request-output-state-frame))
       (delay nil) (frames nil))
  (unwind-protect
       (progn
         (setf (slot-value world 'overlays) (list one two)
               (gethash output-one (%world-outputs world)) state-one
               (gethash output-two (%world-outputs world)) state-two
               (%world-component-timer world) :timer
               (symbol-function 'ataxia.runtime:update-event-loop-timer)
               (lambda (source milliseconds) (declare (ignore source)) (setf delay milliseconds))
               (symbol-function '%request-output-state-frame)
               (lambda (w state) (declare (ignore w)) (push state frames)))
         (%schedule-component-timer world) (assert (zerop delay)) (assert (null frames))
         (setf (idle-ui-active first) t)
         (%schedule-component-timer world) (assert (zerop delay)) (assert (equal frames (list state-one)))
         (setf (idle-ui-active first) nil (idle-ui-delay first) 250 (idle-ui-delay second) 80 frames nil)
         (%schedule-component-timer world) (assert (= delay 80)) (assert (null frames))
         (setf (canvas-overlay-visible-p two) nil)
         (%schedule-component-timer world) (assert (= delay 250))
         (setf (idle-ui-delay first) 0)
         (%schedule-component-timer world) (assert (zerop delay)) (assert (equal frames (list state-one)))
         (setf (canvas-overlay-x one) 500d0 frames nil)
         (%schedule-component-timer world) (assert (zerop delay)) (assert (null frames))
         (setf (canvas-overlay-visible-p one) nil frames nil)
         (%schedule-component-timer world) (assert (zerop delay)) (assert (null frames))
         (format t "PASS: mixed UI deadlines, per-output animation pacing, and hidden/idle timer disarm.~%"))
    (setf (symbol-function 'ataxia.runtime:update-event-loop-timer) timer-original
          (symbol-function '%request-output-state-frame) frame-original)))
(in-package #:ataxia.runtime)
(let* ((runtime (make-instance 'runtime))
       (names '(%object-pointer ataxia.runtime.raw:%wl-display-flush-clients
                ataxia.runtime.raw:%wl-event-loop-dispatch))
       (originals (mapcar #'symbol-function names)) (events nil))
  (unwind-protect
       (progn
         (setf (%runtime-state runtime) :running
               (symbol-function '%object-pointer) #'identity
               (symbol-function 'ataxia.runtime.raw:%wl-display-flush-clients)
               (lambda (display) (declare (ignore display)) (push :flush events))
               (symbol-function 'ataxia.runtime.raw:%wl-event-loop-dispatch)
               (lambda (loop timeout)
                 (declare (ignore loop))
                 (assert (= -1 timeout))
                 (assert (eq :flush (first events)))
                 (push :dispatch events)
                 (%defer-runtime-action runtime (lambda () (push :safe-point events)))
                 (request-runtime-stop runtime :test)
                 0))
         (run-runtime runtime)
         (assert (equal '(:safe-point :dispatch :flush) events))
         (format t "PASS: runtime flushes before blocking, drains deferred actions and stops without polling.~%"))
    (loop for name in names for original in originals do (setf (symbol-function name) original))))

;;;; Offscreen commits must not wake outputs; visible changes retain repainting.
(in-package #:ataxia.infinite-world)
(defclass idle-test-application (ataxia.kernel:wayland-application) ())
(defmethod ataxia.kernel:drawable-local-bounds ((app idle-test-application))
  (values 0 0 100 100))
(let* ((world (make-infinite-world))
       (app (make-instance 'idle-test-application))
       (window (make-instance 'canvas-window :application app :x 100d0 :y 20d0 :width 100d0 :height 100d0))
       (states (loop for camera in '(0d0 400d0)
                     for output = (make-instance 'ataxia.kernel:kernel-output :width 320 :height 200 :scale 1d0 :transform 0)
                     for state = (%make-canvas-output output)
                     do (setf (%canvas-output-buffer-width state) 320 (%canvas-output-buffer-height state) 200
                              (%canvas-output-camera-x state) camera
                              (gethash output (%world-outputs world)) state)
                     collect state))
       (names '(%update-window-membership %request-output-state-frame))
       (originals (mapcar #'symbol-function names)) (requested nil))
  (unwind-protect
       (progn
         (setf (%canvas-window-mapped-p window) t (gethash app (%world-windows world)) window
               (symbol-function '%update-window-membership) (lambda (&rest args) (declare (ignore args)))
               (symbol-function '%request-output-state-frame)
               (lambda (w state) (assert (eq w world)) (push state requested)))
         (labels ((commit (&optional (damage (list (ataxia.kernel:make-frame-damage-rectangle 0 0 100 100)))
                                    (callback (null damage)))
                    (setf requested nil (slot-value world 'damage) (ataxia.world:make-damage-tracker))
                    (setf (ataxia.kernel::%application-drawable-surfaces app)
                          (vector (make-instance 'ataxia.kernel::wayland-drawable-surface
                                                 :local-x 0 :local-y 0 :width 100 :height 100
                                                 :frame-callback-p callback :presentation-token :callback)))
                    (ataxia.kernel:world-object-invalidated world app (ataxia.kernel:make-drawable-invalidation 1 damage))))
           (commit)
           (assert (equal requested (list (first states))))
           (setf (canvas-window-x window) 500d0) (commit)
           (assert (equal requested (list (second states))))
           (setf (canvas-window-x window) 900d0) (commit)
           (assert (null requested))
           (assert (every (lambda (state) (not (ataxia.world:damage-pending-p (%world-damage world) (%canvas-output-output state)))) states))
           (setf (canvas-window-x window) 100d0 (%canvas-window-hidden-p window) t) (commit)
           (assert (null requested))
           (setf (%canvas-window-hidden-p window) nil) (commit nil)
           (assert (equal requested (list (first states))))
           ;; A partially visible window's damage can still be fully offscreen.
           (setf (canvas-window-x window) 300d0)
           (commit (list (ataxia.kernel:make-frame-damage-rectangle 50 0 50 100)))
           (assert (null requested))
           (let* ((cover-app (make-instance 'idle-test-application))
                  (cover (make-instance 'canvas-window :application cover-app :x 80d0 :y 0d0 :width 160d0 :height 150d0)))
             (setf (%canvas-window-mapped-p cover) t (canvas-window-x window) 100d0
                   (slot-value world 'stacking) (list window cover)
                   (ataxia.kernel::%application-drawable-surfaces cover-app)
                   (vector (make-instance 'ataxia.kernel::wayland-drawable-surface
                              :local-x 0 :local-y 0 :width 100 :height 100 :presentation-token nil
                              :opaque-region (list (ataxia.kernel:make-frame-damage-rectangle 0 0 100 100))
                              :render-source (make-instance 'ataxia.kernel::wayland-render-source :has-alpha-p nil))))
             (commit) (assert (null requested))
             (commit nil) (assert (null requested))
             (setf (canvas-window-x cover) 150d0)
             (commit) (assert (equal requested (list (first states))))
             ;; Changed pixels are covered, but visible client callbacks progress.
             (commit (list (ataxia.kernel:make-frame-damage-rectangle 60 0 40 100)))
             (assert (null requested))
             (commit (list (ataxia.kernel:make-frame-damage-rectangle 60 0 40 100)) t)
             (assert (equal requested (list (first states))))))
         (format t "PASS: client damage wakes only affected outputs; hidden/offscreen commits sleep; visible callback-only commits remain scheduled.~%"))
    (loop for name in names for original in originals do (setf (symbol-function name) original))))

;;;; Buffer-only commits avoid a duplicate atomic test; failures still propagate.
(in-package #:ataxia.kernel)
(let* ((kernel (make-instance 'kernel :world (make-instance 'world)))
       (output (make-instance 'kernel-output :kernel kernel :runtime-object :output))
       (result (make-instance 'world-frame-result :damage nil))
       (names '(ataxia.runtime:create-output-state ataxia.runtime:output-state-set-buffer
                ataxia.runtime:output-state-set-damage ataxia.runtime:output-test-state
                ataxia.runtime:output-commit-state ataxia.runtime:destroy-output-state
                %refresh-output-object %notify-presented-surfaces %guard-kernel-operation))
       (originals (mapcar #'symbol-function names)) (success t) (events nil))
  (unwind-protect
       (progn
         (dolist (name names)
           (setf (symbol-function name) (lambda (&rest args) (declare (ignore args)))))
         (setf (symbol-function 'ataxia.runtime:create-output-state)
               (lambda (out) (assert (eq out :output)) :state)
               (symbol-function 'ataxia.runtime:output-test-state)
               (lambda (&rest args) (declare (ignore args)) (error "Buffer commit must not issue a duplicate test."))
               (symbol-function 'ataxia.runtime:output-commit-state)
               (lambda (out state) (assert (eq out :output)) (assert (eq state :state)) (push :commit events) success)
               (symbol-function 'ataxia.runtime:destroy-output-state)
               (lambda (state) (assert (eq state :state)) (push :destroy events))
               (symbol-function '%notify-presented-surfaces)
               (lambda (&rest args) (declare (ignore args)) (push :presented events))
               (symbol-function '%guard-kernel-operation)
               (lambda (k world operation thunk)
                 (declare (ignore world thunk)) (assert (eq k kernel)) (push operation events)))
         (assert (%commit-world-frame output :buffer result))
         (assert (equal (reverse events) '(:commit world-frame-committed :presented :destroy)))
         (setf success nil events nil)
         (assert (null (%commit-world-frame output :buffer result)))
         (assert (equal (reverse events) '(:commit world-frame-failed :destroy)))
         (format t "PASS: one native commit per frame; failure notification and native-state cleanup remain intact.~%"))
    (loop for name in names for original in originals do (setf (symbol-function name) original))))
