;;;; Run: sbcl --script tests/metaworld-hyprland.lisp
(load (merge-pathnames "support.lisp" *load-truename*))
(in-package #:ataxia.infinite-world)

(defun hypr-window (world group column &optional (workspace 1))
  (let* ((application (make-instance 'ataxia.kernel:wayland-application))
         (window (make-instance 'canvas-window :application application
                                :x 0d0 :y 0d0 :width 200d0 :height 100d0))
         (member (%make-subworld-member :object window :column column :workspace workspace)))
    (setf (%canvas-window-mapped-p window) t
          (gethash application (%world-windows world)) window
          (gethash window (%meta-owners world)) group
          (subworld-members group) (append (subworld-members group) (list member)))
    window))

(let* ((world (make-hyprland-world :state-file nil))
       (group (%make-subworld :id 1 :name "Hyprland" :kind :hyprland))
       (names '(%now %damage-window %update-window-membership %request-all-frames %meta-changed
                ataxia.kernel:request-object-configuration))
       (saved (mapcar #'symbol-function names)) (clock 0d0))
  (unwind-protect
       (progn
         (dolist (name (rest names))
           (setf (symbol-function name) (lambda (&rest args) (declare (ignore args)))))
         (setf (symbol-function '%now) (lambda () clock)
               (metaworld-subworlds world) (list group) (%meta-restoring-p world) t)
         (let* ((a (hypr-window world group 1)) (b (hypr-window world group 2)))
           (%meta-layout world group)
           (let ((geometry-a (%meta-object-geometry a)) (geometry-b (%meta-object-geometry b)))
             (setf (gethash group (%meta-group-focus world)) b)
             (let ((c (hypr-window world group 3)))
               (%meta-layout world group)
               (assert (equal geometry-a (%meta-object-geometry a)))
               (assert (= (canvas-window-width b) (canvas-window-width c)))
               (assert (< (canvas-window-y b) (canvas-window-y c)))
               ;; Vertical resize changes B/C's split and leaves A unchanged.
               (let ((before (canvas-window-height b)))
                 (%meta-resize-tile world b :down)
                 (assert (> (canvas-window-height b) before))
                 (assert (equal geometry-a (%meta-object-geometry a))))
               (let ((wanted (+ 40d0 (canvas-window-height b))))
                 (%meta-hypr-resize-to group (%meta-member group b)
                                       (list (canvas-window-x b) (canvas-window-y b)
                                             (canvas-window-width b) wanted))
                 (%meta-layout world group)
                 (assert (< (abs (- wanted (canvas-window-height b))) 1d-6))
                 (assert (equal geometry-a (%meta-object-geometry a))))
               ;; Swap operates on leaves without reconstructing the branches.
               (let ((before-b (%meta-object-geometry b)) (before-c (%meta-object-geometry c)))
                 (%meta-hypr-swap group (%meta-member group b) (%meta-member group c))
                 (%meta-layout world group)
                 (assert (equal before-b (%meta-object-geometry c)))
                 (assert (equal before-c (%meta-object-geometry b))))
               ;; Saved trees preserve orientation, ratios and leaf identity.
               (let* ((record (%meta-group-record group)) (copy (%meta-load-group record)))
                 (assert (equal (%meta-hypr-tree group 1) (%meta-hypr-tree copy 1)))
                 (setf (third (%meta-hypr-tree copy 1)) .2d0)
                 (assert (/= (third (%meta-hypr-tree copy 1)) (third (%meta-hypr-tree group 1)))))
               (setf (subworld-members group) (remove c (subworld-members group) :key #'subworld-member-object))
               (%meta-layout world group)
               (assert (equal geometry-a (%meta-object-geometry a)))
               (assert (equal geometry-b (%meta-object-geometry b))))
             ;; Explicit split rotation, not an accidental aspect-ratio change.
             (%meta-hypr-toggle-split world b)
             (assert (= (canvas-window-x a) (canvas-window-x b)))
             (assert (/= (canvas-window-y a) (canvas-window-y b)))
             (%meta-hypr-toggle-split world b))
           ;; A drop selects a local split direction, including above/below.
           (%meta-hypr-drop group (%meta-member group b) (%meta-member group a) :above)
           (%meta-layout world group)
           (assert (< (canvas-window-y b) (canvas-window-y a)))
           ;; Fullscreen covers the entire subworld without reserved margins.
           (setf (subworld-fullscreen group) b)
           (%meta-layout world group)
           (assert (equalp (%meta-object-geometry b) '(0d0 0d0 1400d0 800d0)))
           (assert (not (%canvas-window-input-enabled-p a)))
           (setf (subworld-fullscreen group) nil)
           (%meta-layout world group)
           ;; Switching workspaces keeps outgoing content for the fade while
           ;; routing input exclusively to the new workspace, even on reversal.
           (let ((c (hypr-window world group 4 2)))
             (%meta-layout world group)
             (setf (%meta-restoring-p world) nil (subworld-workspace group) 2)
             (%meta-layout world group)
             (assert (%window-visible-p a))
             (assert (not (%target-visible-p a)))
             (assert (%canvas-window-input-enabled-p c))
             (setf clock .08d0)
             (ataxia.world:advance-animations (%world-animator world) clock)
             (assert (< 0d0 (%window-opacity a) 1d0))
             (let ((shown (%window-opacity a)))
               (setf (subworld-workspace group) 1)
               (%meta-layout world group)
               (assert (= shown (%window-opacity a)))
               (assert (not (%canvas-window-input-enabled-p c))))
             (ataxia.world:advance-animations (%world-animator world) 1d0)
             (assert (= 1d0 (%window-opacity a)))
             (assert (%canvas-window-hidden-p c)))
           ;; Shadow lift must not displace a grabbed window's content.
           (let ((state (%make-canvas-output nil)))
             (setf (%canvas-window-lift-offset b) 0d0 (canvas-window-elevation b) 0d0)
             (let ((before (multiple-value-list (%window-canvas-geometry state b))))
               (setf (canvas-window-elevation b) 1d0)
               (assert (equal before (multiple-value-list (%window-canvas-geometry state b)))))))
         (format t "PASS: stable focused splits, local resize/swap/drop, split rotation, saved trees, fullscreen, reversible workspace fades and stationary grabs.~%"))
    (loop for name in names for original in saved do (setf (symbol-function name) original))))
