;;;; Run: sbcl --script tests/metaworld-minification.lisp
(load (merge-pathnames "support.lisp" *load-truename*))
(in-package #:ataxia.infinite-world)
(let ((uv '((0d0 . 0d0) (1d0 . 0d0) (0d0 . 1d0) (1d0 . 1d0)))
      (quad '((-1d0 . -1d0) (1d0 . -1d0) (-1d0 . 1d0) (1d0 . 1d0))))
  (multiple-value-bind (vectors counts) (%surface-minification-filter quad uv 800 600 800 600)
    (assert (equal counts '(1 1)))
    (assert (every (lambda (v) (and (zerop (car v)) (zerop (cdr v)))) vectors)))
  (multiple-value-bind (vectors counts) (%surface-minification-filter quad uv 800 600 400 300)
    (declare (ignore vectors)) (assert (equal counts '(1 1))))
  (multiple-value-bind (vectors counts) (%surface-minification-filter quad uv 100 75 800 600)
    (assert (equal counts '(8 8)))
    (assert (< (abs (- (caar vectors) (/ (sqrt 63d0) 800d0))) 1d-12))
    (assert (< (abs (- (cdadr vectors) (/ (sqrt 63d0) 600d0))) 1d-12)))
  ;; Cropping and rotated/flipped buffer UVs preserve the physical footprint.
  (multiple-value-bind (vectors counts)
      (%surface-minification-filter quad '((0.75d0 . 1d0) (0.75d0 . 0d0) (0.25d0 . 1d0) (0.25d0 . 0d0))
                                    150 100 800 600)
    (assert (equal counts '(4 4)))
    (assert (minusp (cdar vectors))) (assert (minusp (caadr vectors))))
  ;; Tiny windows have a finite sample budget, and zero-area quads stay finite.
  (dolist (size '(0 1 7))
    (multiple-value-bind (vectors counts) (%surface-minification-filter quad uv size size 8192 8192)
      (assert (equal counts '(16 16)))
      (assert (every (lambda (v) (and (<= 0d0 (car v)) (<= 0d0 (cdr v)))) vectors)))))
(let ((directory (uiop:getenv "ATAXIA_SHADER_TEST_DIR")))
  (when directory
    (ensure-directories-exist (uiop:ensure-directory-pathname directory))
    (dolist (entry (list (cons "canvas.vert" +canvas-vertex-shader+)
                        (cons "texture.frag" (%texture-fragment-shader nil))
                        (cons "external.frag" (%texture-fragment-shader t))))
      (with-open-file (out (merge-pathnames (car entry) (uiop:ensure-directory-pathname directory))
                           :direction :output :if-exists :supersede)
        (write-string (cdr entry) out)))))
(format t "PASS: physical-pixel minification, 1:1/magnification, crops, transforms and sample bounds.~%")
