;;;; Portable services attach to opaque window handles in an unrelated World.
(load (merge-pathnames "system-support.lisp" *load-truename*))
(asdf:load-system "ataxia-assistant")

(defpackage #:ataxia.test.portable-desktop
  (:use #:cl #:ataxia.world)
  (:local-nicknames (#:cu #:ataxia.computer-use) (#:assistant #:ataxia.assistant)))
(in-package #:ataxia.test.portable-desktop)

(dolist (package '(:ataxia.infinite-world :ataxia.metaworld :ataxia.atlas :ataxia.world.slint))
  (assert (not (find-package package))))

(defclass fixture-world (ataxia.kernel:world)
  ((outputs :initarg :outputs :reader world-outputs)
   (windows :initarg :windows :accessor world-windows)
   (focus :initform nil :accessor fixture-focus)
   (capture-count :initform 0 :accessor capture-count)))
(defstruct fixture-window application x y)
(defclass fixture-application (ataxia.kernel:wayland-application) ())
(defmethod window-application ((window fixture-window)) (fixture-window-application window))
(defmethod ataxia.kernel:drawable-local-bounds ((app fixture-application))
  (values 0d0 0d0 80d0 60d0))
(defmethod ataxia.kernel:drawable-surfaces ((app fixture-application)) (values #() 1))
(defmethod world-supports-p ((world fixture-world) capability)
  (member capability '(:desktop :window-capture)))
(defmethod world-window-visible-p ((world fixture-world) window &optional output)
  (and (member window (world-windows world))
       (or (null output) (member output (world-outputs world)))))
(defmethod window-output-bounds ((world fixture-world) window output)
  (declare (ignore output))
  (values (fixture-window-x window) (fixture-window-y window) 160d0 120d0))
(defmethod window-local-to-output ((world fixture-world) window output x y)
  (declare (ignore output))
  (values (+ (fixture-window-x window) (* 2 x)) (+ (fixture-window-y window) (* 2 y))))
(defmethod output-to-window-local ((world fixture-world) window output x y)
  (declare (ignore output))
  (values (/ (- x (fixture-window-x window)) 2d0) (/ (- y (fixture-window-y window)) 2d0)))
(defmethod world-target-at ((world fixture-world) output x y)
  (declare (ignore output))
  (find-if (lambda (window)
             (and (<= (fixture-window-x window) x (+ 160 (fixture-window-x window)))
                  (<= (fixture-window-y window) y (+ 120 (fixture-window-y window)))))
           (world-windows world)))
(defmethod focus-world-target ((world fixture-world) seat target &key remember)
  (declare (ignore seat remember)) (setf (fixture-focus world) target))
(defmethod capture-window-pixels ((world fixture-world) window bounds width height pixels)
  (declare (ignore window bounds))
  (assert (= (* width height 4) (length pixels)))
  (incf (capture-count world))
  (fill pixels 127))

(let* ((output (make-instance 'ataxia.kernel:kernel-output :id 1 :name "Fixture"
                              :width 900 :height 600 :scale 1d0 :transform 0))
       (app (make-instance 'fixture-application :id 42 :title "Opaque window"
                           :app-id "fixture" :mapped-p t :state :live :root-surface nil))
       (window (make-fixture-window :application app :x 30d0 :y 50d0))
       (world (make-instance 'fixture-world :outputs (list output) :windows (list window)))
       (controller (cu::%make-computer-controller :world world))
       (session (cu::%make-computer-session :world world :output output :id 1 :token "fixture"
                                           :state :active :expires (+ (monotonic-time) 120d0)
                                           :input-state (cu::make-computer-input-state)))
       (seat (make-instance 'cu::computer-seat :session session))
       (input-capabilities (symbol-function 'ataxia.computer-use::application-seat-input-capabilities)))
  (setf (cu::computer-session-seat session) seat
        (cu::computer-controller-sessions controller) (list session))
  (attach-world-service world :computer-use controller)
  (unwind-protect
       (progn
         ;; The only native boundary in these data observations is the query
         ;; for a client's bound wl_seat resources. Native suites cover it.
         (setf (symbol-function 'ataxia.computer-use::application-seat-input-capabilities)
               (lambda (application target-seat)
                 (assert (eq app application)) (assert (eq seat target-seat))
                 '(:keyboard :pointer)))
         (assert (eq window (find-world-window world 42)))
         (assert (not (world-window-visible-p world (make-fixture-window :application app))))
         (let* ((reply (cu:request-on-owner world '(:op "observe" :token "fixture")))
                (entry (aref (getf reply :windows) 0)))
           (assert (= 42 (getf entry :id)))
           (assert (= 80d0 (getf entry :width))))
         (cu:request-on-owner world '(:op "focus" :token "fixture" :sequence 1 :window 42))
         (assert (eq window (fixture-focus world)))
         (assert (= 110d0 (cu::computer-input-state-x (cu::computer-session-input-state session))))
         (assert (= 110d0 (cu::computer-input-state-y (cu::computer-session-input-state session))))
         (let ((capture (cu::make-computer-capture :session session :window window :mode :window
                                                  :semaphore (sb-thread:make-semaphore :count 0))))
           (cu::%computer-read-window capture world)
           (assert (null (cu::computer-capture-error capture)))
           (assert (= 1 (capture-count world)))
           (assert (= 80 (cu::computer-capture-width capture)))
           (assert (every (lambda (byte) (= byte 127)) (cu::computer-capture-pixels capture))))
         (let* ((assistant (assistant::%make-assistant-controller :world world))
                (snapshot (assistant::%assistant-layout-snapshot assistant))
                (tools (assistant::%assistant-tool-specs world)))
           (assert (= 42 (getf (aref (getf snapshot :windows) 0) :id)))
           (assert (= 6 (length tools)))
           (assert (notany (lambda (tool) (search "layout" (gethash "name" tool))) tools))
           (let* ((act (find "ataxia_act" tools :key (lambda (tool) (gethash "name" tool)) :test #'equal))
                  (operations (loop for action across (assistant::%assistant-field act "inputSchema" "properties" "actions" "items" "anyOf")
                                    collect (aref (assistant::%assistant-field action "properties" "op" "enum") 0))))
             (assert (not (find "launch" operations :test #'equal))))
           (assert (handler-case
                       (progn (assistant::%assistant-layout-preview assistant (make-hash-table)) nil)
                     (error () t))))
         ;; Desktop observations use the host's output-space placement.
         (setf (cu::computer-view-mode (cu:computer-session-view session)) :desktop)
         (let ((entry (aref (cu::%computer-windows session) 0)))
           (assert (= 30d0 (getf entry :x)))
           (assert (= 160d0 (getf entry :width)))))
    (setf (symbol-function 'ataxia.computer-use::application-seat-input-capabilities) input-capabilities)
    (detach-world-service world :computer-use)))

(format t "PASS: standalone service loading, opaque windows, host projection/capture, observations and capability-filtered tools.~%")
