(load (merge-pathnames "system-support.lisp" *load-truename*))
(asdf:load-system "ataxia-rmlui/status-bar")
(in-package #:ataxia.world.shell)
(assert (= 60000 (%bar-maintenance-delay 0 nil)))
(assert (= 59000 (%bar-maintenance-delay 1 nil)))
(assert (= 30000 (%bar-maintenance-delay 0 t)))
(assert (= 29000 (%bar-maintenance-delay 31 t)))
(dolist (open '(nil t))
  (assert (= 1000 (%bar-maintenance-delay 59 open)))
  (assert (= (if open 120 60)
             (loop for now = 0 then (+ now (/ (%bar-maintenance-delay now open) 1000))
                   while (< now 3600) count t))))
(let* ((root (merge-pathnames (format nil "ataxia-battery-test-~D/" (random 1000000000)) (uiop:temporary-directory)))
       (battery (merge-pathnames "BAT0/" root)) (ac (merge-pathnames "AC/" root)))
  (labels ((put (directory name value)
             (ensure-directories-exist directory)
             (with-open-file (stream (merge-pathnames name directory) :direction :output :if-exists :supersede)
               (princ value stream))))
    (unwind-protect
         (progn
           (put battery "type" "Battery") (put battery "present" 1)
           (put battery "capacity" 18) (put battery "status" "Discharging")
           (put battery "charge_now" 1800000) (put battery "current_now" 900000)
           (put battery "charge_full" 3000000) (put battery "charge_full_design" 4000000)
           (put battery "cycle_count" 120) (put ac "online" 0)
           (let ((power (%bar-power root)))
             (assert (eq :low (%bar-power-tone power)))
             (assert (= 120 (getf power :minutes)))
             (assert (= 75 (getf power :health)))
             (assert (search "remaining" (%bar-power-estimate power))))
           (put battery "capacity" 8)
           (assert (eq :critical (%bar-power-tone (%bar-power root))))
           (put battery "status" "Charging") (put ac "online" 1)
           (let ((power (%bar-power root)))
             (assert (eq :normal (%bar-power-tone power)))
             (assert (= 80 (getf power :minutes)))
             (assert (search "until full" (%bar-power-estimate power))))
           (put battery "status" "Not charging") (put battery "capacity" 100)
           (assert (eq :full (getf (%bar-power root) :status)))
           (put battery "status" "Discharging") (put battery "current_now" 0)
           (assert (null (getf (%bar-power root) :minutes)))
           (put battery "present" 0)
           (assert (eq :ac (getf (%bar-power root) :status)))
           (format t "PASS: battery charge/discharge estimates, low/critical states, plugged-in full, health, absent battery, and unavailable rate.~%"))
      (uiop:delete-directory-tree root :validate t :if-does-not-exist :ignore))))
