(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-rmlui/status-bar")
(in-package #:ataxia.infinite-world)
(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (stem (format nil "ataxia-launch-test-~D" (random 1000000000)))
       (desktop (merge-pathnames (concatenate 'string stem ".desktop") (uiop:temporary-directory)))
       (marker (merge-pathnames (concatenate 'string stem ".launched") (uiop:temporary-directory)))
       (bar nil) (seat nil) (phase 0))
  (labels ((key (symbol)
             (dolist (state '(:pressed :released))
               (ataxia.kernel:world-key-event world seat
                 (ataxia.kernel:make-key-input :keycode 0 :keysyms (vector (ataxia.runtime:keysym-name symbol)) :modifiers nil :state state)))))
    (unwind-protect
         (progn
           (with-open-file (stream desktop :direction :output :if-exists :supersede)
             (format stream "[Desktop Entry]~%Type=Application~%Name=Ataxia Launcher Test~%Exec=/usr/bin/touch ~A~%" (namestring marker)))
           (ataxia.kernel:start-kernel kernel)
           (enable-rmlui-status-bar world)
           (setf bar (find-if (lambda (x) (typep x 'rmlui-status-bar)) (world-overlays world))
                 seat (%canvas-seat-seat (first (%seat-states world))))
           (%bar-action world bar :menu)
           (let ((timer (ataxia.runtime:add-event-loop-timer
                         (ataxia.kernel:kernel-runtime kernel)
                         (lambda (source)
                           (case phase
                             (0
                              (assert (%bar-popup bar))
                              (assert (%shell-popup-entries (%bar-popup bar)))
                              (setf (%shell-popup-entries (%bar-popup bar)) (list (%read-desktop-entry desktop)))
                              (loop for character across "Ataxia" do (key (char-code character)))
                              (let ((popup (%bar-popup bar)))
                                (assert (equal "Ataxia" (ataxia.world.rmlui:rmlui-model-value (canvas-overlay-component popup) "query")))
                                (assert (%shell-popup-matches popup))
                                (assert (every (lambda (entry) (search "Ataxia" (%desktop-entry-name entry) :test #'char-equal)) (%shell-popup-matches popup))))
                              (key #xff1b)
                              (assert (null (%bar-popup bar)))
                              (%bar-action world bar :power)
                              (assert (eq :power (%shell-popup-kind (%bar-popup bar))))
                              (let ((seat-state (gethash seat (%world-seats world))))
                                (setf (%canvas-seat-x seat-state) 0d0 (%canvas-seat-y seat-state) 0d0)
                                (dolist (state '(:pressed :released))
                                  (ataxia.kernel:world-cursor-button world seat
                                    (ataxia.kernel:make-cursor-button-input :code 272 :state state))))
                              (assert (null (%bar-popup bar)))
                              (%bar-action world bar :menu)
                              (let ((popup (%bar-popup bar)))
                                (setf (%shell-popup-entries popup) (list (%read-desktop-entry desktop)))
                                (%shell-search popup "Ataxia"))
                              (key #xff0d)
                              (assert (null (%bar-popup bar)))
                              (setf phase 1)
                              (ataxia.runtime:update-event-loop-timer source 1000))
                             (1
                              (assert (probe-file marker))
                              (assert (eq :running (ataxia.kernel:kernel-world-status kernel)))
                              (%bar-action world bar :menu)
                              (disable-rmlui-status-bar world)
                              (assert (notany (lambda (widget) (typep widget 'rmlui-shell-widget)) (world-overlays world)))
                              (setf phase 2)
                              (ataxia.runtime:update-event-loop-timer source 0)))
                           0))))
             (ataxia.runtime:update-event-loop-timer timer 700))
           (ataxia.kernel:run-kernel kernel :run-for 2.5d0)
           (assert (= phase 2))
           (format t "PASS: real menu typing/search, Escape, outside click, power panel, Enter launches a desktop entry, and popup cleanup.~%"))
      (ataxia.kernel:destroy-kernel kernel :shell-test-complete)
      (when (probe-file desktop) (delete-file desktop))
      (when (probe-file marker) (delete-file marker)))))
