(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-rmlui/status-bar")
(in-package #:ataxia.infinite-world)
(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 700))
       (original (symbol-function 'ataxia.kernel::%render-output-frame))
       (frames 0) (baseline 0) (phase 0) (bar nil) (group nil))
  (unwind-protect
       (progn
         (setf (symbol-function 'ataxia.kernel::%render-output-frame)
               (lambda (output) (incf frames) (funcall original output)))
         (ataxia.kernel:start-kernel kernel)
         (setf group (first (metaworld-subworlds world)))
         (ataxia.world.shell::enable-rmlui-status-bar world)
         (ataxia.world.shell::enable-rmlui-status-bar world)
         (let ((bars (remove-if-not (lambda (x) (typep x 'ataxia.world.shell::rmlui-status-bar)) (world-overlays world))))
           (assert (= (length bars) 1))
           (setf bar (first bars)))
         (let ((timer
                 (ataxia.runtime:add-event-loop-timer
                  (ataxia.kernel:kernel-runtime kernel)
                  (lambda (source)
                    (case phase
                      (0
                       (assert (plusp frames))
                       (assert (not (ataxia.kernel:drawable-active-p (canvas-overlay-component bar))))
                       (assert (= 1100d0 (canvas-overlay-width bar)))
                       (assert (= 656d0 (canvas-overlay-y bar)))
                       (setf baseline frames phase 1)
                       (ataxia.runtime:update-event-loop-timer source 300))
                      (1
                       (assert (= baseline frames))
                       (ataxia.world.shell::%bar-action world bar :workspace 1)
                       (assert (eq group (%meta-current world)))
                       (ataxia.world.shell::%bar-action world bar :workspace 2)
                       (assert (= 2 (subworld-workspace group)))
                       (setf phase 2)
                       (ataxia.runtime:update-event-loop-timer source 1000))
                      (2
                       (assert (not (ataxia.kernel:drawable-active-p (canvas-overlay-component bar))))
                       (let* ((state (%first-output-state world))
                              (old-width (ataxia.kernel:output-width (%canvas-output-output state))))
                         (setf (ataxia.kernel:output-width (%canvas-output-output state)) 320)
                         (ataxia.world.shell::%bar-sync world bar (%canvas-output-output state))
                         (assert (= (canvas-overlay-width bar) 320d0))
                         (assert (gethash '(:class "tiny") (ataxia.world.rmlui:widget-cache bar)))
                         (setf (ataxia.kernel:output-width (%canvas-output-output state)) old-width)
                         (ataxia.world.shell::%bar-sync world bar (%canvas-output-output state)))
                       (ataxia.world.shell::disable-rmlui-status-bar world)
                       (assert (not (ataxia.world:world-service world :shell)))
                       (assert (not (member bar (world-overlays world))))
                       (setf phase 3)
                       (ataxia.runtime:update-event-loop-timer source 0)))
                    0))))
           (ataxia.runtime:update-event-loop-timer timer 1200))
         (ataxia.kernel:run-kernel kernel :run-for 3d0)
         (assert (= phase 3))
         (assert (eq :running (ataxia.kernel:kernel-world-status kernel)))
         (ataxia.world.shell::enable-rmlui-status-bar world)
         (ataxia.kernel:world-quiescing world :test)
         (assert (not (ataxia.world:world-service world :shell)))
         (format t "PASS: real Metaworld status bar, repeated enable, workspace commands, responsive resize, zero settled frames, removal and quiesce cleanup.~%"))
    (setf (symbol-function 'ataxia.kernel::%render-output-frame) original)
    (ataxia.kernel:destroy-kernel kernel :status-bar-test-complete)))
