(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-rmlui/status-bar")
(in-package #:ataxia.infinite-world)
(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (stem (format nil "ataxia-launch-test-~D" (random 1000000000)))
       (desktop (merge-pathnames (concatenate 'string stem ".desktop") (uiop:temporary-directory)))
       (marker (merge-pathnames (concatenate 'string stem ".launched") (uiop:temporary-directory)))
       (bar nil) (seat nil) (phase 0))
  (labels ((key (symbol)
             (dolist (state '(:pressed :released))
               (ataxia.kernel:world-key-event world seat
                 (ataxia.kernel:make-key-input :keycode 0 :keysyms (vector (ataxia.runtime:keysym-name symbol)) :modifiers nil :state state)))))
    (unwind-protect
         (progn
           (with-open-file (stream desktop :direction :output :if-exists :supersede)
             (format stream "[Desktop Entry]~%Type=Application~%Name=Ataxia Launcher Test~%Exec=/usr/bin/touch ~A~%" (namestring marker)))
           (ataxia.kernel:start-kernel kernel)
           (setf (%launcher-desktop-entries (%launcher-for-output world (%canvas-output-output (%first-output-state world))))
                 (list (%read-desktop-entry desktop)))
           (ataxia.world.shell::enable-rmlui-status-bar world)
           (setf bar (find-if (lambda (x) (typep x 'ataxia.world.shell::rmlui-status-bar)) (world-overlays world))
                 seat (%canvas-seat-seat (first (%seat-states world))))
           (let ((timer (ataxia.runtime:add-event-loop-timer
                         (ataxia.kernel:kernel-runtime kernel)
                         (lambda (source)
                           (case phase
                             (0
                              ;; Open Apps through the same World pointer route
                              ;; as a human click, after the first rendered frame.
                              (let ((seat-state (gethash seat (%world-seats world))))
                                (ataxia.kernel:world-cursor-motion world seat
                                  (ataxia.kernel:make-cursor-motion-input
                                    :delta-x (- 35d0 (%canvas-seat-x seat-state))
                                    :delta-y (- (+ (overlay-y bar) 20d0) (%canvas-seat-y seat-state))))
                                (dolist (state '(:pressed :released))
                                  (ataxia.kernel:world-cursor-button world seat
                                    (ataxia.kernel:make-cursor-button-input :code 272 :state state))))
                              (assert (ataxia.world.shell::%bar-popup bar))
                              (assert (ataxia.world.shell::%shell-popup-entries (ataxia.world.shell::%bar-popup bar)))
                              (setf (ataxia.world.shell::%shell-popup-entries (ataxia.world.shell::%bar-popup bar)) (ataxia.world:world-application-catalog world (overlay-output bar)))
                              (loop for character across "Ataxia" do (key (char-code character)))
                              (let ((popup (ataxia.world.shell::%bar-popup bar)))
                                (assert (equal "Ataxia" (ataxia.world.rmlui:rmlui-model-value (canvas-overlay-component popup) "query")))
                                (assert (ataxia.world.shell::%shell-popup-matches popup))
                                (assert (every (lambda (entry) (search "Ataxia" (getf entry :name) :test #'char-equal)) (ataxia.world.shell::%shell-popup-matches popup))))
                              (key #xff1b)
                              (assert (null (ataxia.world.shell::%bar-popup bar)))
                              (ataxia.world.shell::%bar-action world bar :power)
                              (assert (eq :power (ataxia.world.shell::%shell-popup-kind (ataxia.world.shell::%bar-popup bar))))
                              (let ((seat-state (gethash seat (%world-seats world))))
                                (setf (%canvas-seat-x seat-state) 0d0 (%canvas-seat-y seat-state) 0d0)
                                (dolist (state '(:pressed :released))
                                  (ataxia.kernel:world-cursor-button world seat
                                    (ataxia.kernel:make-cursor-button-input :code 272 :state state))))
                              (assert (null (ataxia.world.shell::%bar-popup bar)))
                              (ataxia.world.shell::%bar-action world bar :menu)
                              (let ((popup (ataxia.world.shell::%bar-popup bar)))
                                (setf (ataxia.world.shell::%shell-popup-entries popup) (ataxia.world:world-application-catalog world (overlay-output bar)))
                                (ataxia.world.shell::%shell-search popup "Ataxia"))
                              (key #xff0d)
                              (assert (null (ataxia.world.shell::%bar-popup bar)))
                              (setf phase 1)
                              (ataxia.runtime:update-event-loop-timer source 1000))
                             (1
                              (assert (probe-file marker))
                              (assert (eq :running (ataxia.kernel:kernel-world-status kernel)))
                              (ataxia.world.shell::%bar-action world bar :menu)
                              (ataxia.world.shell::disable-rmlui-status-bar world)
                              (assert (notany (lambda (widget) (typep widget 'ataxia.world.rmlui:rmlui-widget)) (world-overlays world)))
                              (setf phase 2)
                              (ataxia.runtime:update-event-loop-timer source 0)))
                           0))))
             (ataxia.runtime:update-event-loop-timer timer 700))
           (ataxia.kernel:run-kernel kernel :run-for 2.5d0)
           (assert (= phase 2))
           (format t "PASS: real menu typing/search, Escape, outside click, power panel, Enter launches a desktop entry, and popup cleanup.~%"))
      (ataxia.kernel:destroy-kernel kernel :shell-test-complete)
      (when (probe-file desktop) (delete-file desktop))
      (when (probe-file marker) (delete-file marker)))))
