;;;; XWayland transport works without loading Kernel or any World.
(load (merge-pathnames "system-support.lisp" *load-truename*))
(asdf:load-system "ataxia-runtime/xwayland")
(in-package #:ataxia.runtime)
(assert (null (find-package "ATAXIA.KERNEL")))
(defclass transport-test-sink (runtime-sink)
  ((surfaces :initform nil :accessor test-surfaces)
   (requests :initform nil :accessor test-requests)
   (seat :initform nil :accessor test-seat)))
(defmethod xwayland-ready ((sink transport-test-sink) server)
  (xwayland-set-seat server (test-seat sink)))
(defmethod xwayland-new-surface ((sink transport-test-sink) server surface)
  (assert (eq server (xwayland-surface-server surface)))
  (push surface (test-surfaces sink)))
(defmethod xwayland-surface-associated ((sink transport-test-sink) surface)
  (assert (typep (xwayland-surface-surface surface) 'wlr-surface))
  (xwayland-surface-consider-map surface))
(defmethod xwayland-surface-request-configure ((sink transport-test-sink) surface request)
  (push request (test-requests sink))
  (xwayland-surface-configure surface (xwayland-configure-x request) (xwayland-configure-y request)
                             (max 1 (xwayland-configure-width request)) (max 1 (xwayland-configure-height request))))

(let* ((sink (make-instance 'transport-test-sink))
       (runtime (create-runtime :sink sink :backend :headless))
       (server nil) (client nil) (surfaces nil))
  (unwind-protect
       (progn
         (start-runtime runtime)
         (setf (test-seat sink) (create-seat runtime "transport-test")
               server (create-xwayland runtime))
         (setf client (uiop:launch-program
                       (list "env" (format nil "DISPLAY=~A" (xwayland-display-name server))
                             "ATAXIA_TEST_X11_CONFIGURE=1" "build/xwayland-client")
                       :output "/tmp/ataxia-xwayland-transport.log" :error-output :output))
         (run-runtime runtime :run-for 1.5d0)
         (setf surfaces (test-surfaces sink))
         (assert (>= (length surfaces) 2))
         (assert (every (lambda (surface) (typep surface 'wlr-xwayland-surface)) surfaces))
         (assert (some (lambda (surface) (equal "XWayland fixture" (xwayland-surface-title surface))) surfaces))
         (assert (null (runtime-last-fault runtime)))
         (let ((request (find 500 (test-requests sink) :key #'xwayland-configure-width)))
           (assert request)
           ;; Event storage is long gone: retained values must be Lisp copies.
           (assert (= 50 (xwayland-configure-x request)))
           (assert (= 60 (xwayland-configure-y request)))
           (assert (= 340 (xwayland-configure-height request)))
           (assert (= 15 (logand 15 (xwayland-configure-mask request)))))
         (destroy-runtime runtime :test)
         (assert (not (native-object-live-p server)))
         (assert (every (lambda (surface) (not (native-object-live-p surface))) surfaces))
         (assert (zerop (hash-table-count *subscription-registry*)))
         (assert (null (find-package "ATAXIA.KERNEL")))
         (format t "PASS: independent typed XWayland transport, native callbacks and complete listener cleanup without Kernel/World.~%"))
    (when (and client (uiop:process-alive-p client)) (uiop:terminate-process client))
    (destroy-runtime runtime :test)))
