(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-screencast")
(in-package #:ataxia.infinite-world)
(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1000 :headless-height 700))
       (runtime (ataxia.kernel:kernel-runtime kernel)) (app nil) (portal nil) (controller nil) (chosen 0) (seen nil)
       (capture (symbol-function '%render-window-capture-pixels))
       (tick (symbol-function '%share-tick))
       (render (symbol-function 'ataxia.kernel::%render-output-frame))
       (captures 0) (idle-ticks 0) (idle-frames 0) (idle-start nil) (idle-cpu nil))
  (unwind-protect
       (progn
         (setf (symbol-function '%render-window-capture-pixels)
               (lambda (&rest args) (incf captures) (apply capture args))
               (symbol-function '%share-tick)
               (lambda (controller) (when idle-start (incf idle-ticks)) (funcall tick controller))
               (symbol-function 'ataxia.kernel::%render-output-frame)
               (lambda (output) (when idle-start (incf idle-frames)) (funcall render output)))
         (ataxia.kernel:start-kernel kernel)
         (setf controller (enable-screen-sharing world)
               app (uiop:launch-program (list "env" (format nil "WAYLAND_DISPLAY=~A" (ataxia.runtime:runtime-socket-name runtime))
                                              "ATAXIA_TEST_REPAINT_SIGNAL=1" "build/computer-use-client" "/tmp/ataxia-share-app-events.log")
                                        :output "/tmp/ataxia-share-app.log" :error-output :output)
               portal (uiop:launch-program (list "/usr/bin/python3" "tests/screencast-client.py" (princ-to-string (uiop:process-info-pid app)))
                                           :output "/tmp/ataxia-share-client.log" :error-output :output))
         (let ((timer (ataxia.runtime:add-event-loop-timer runtime
                        (lambda (source)
                          (let ((session (share-controller-current controller))
                                (window (find-if #'%window-visible-p (%world-stacking world))))
                            (when (and session window (eq session seen))
                              (assert (typep (overlay-component (share-controller-picker controller)) 'ataxia.world.rmlui:rmlui-component))
                              (case (share-session-types session)
                                (2
                                 ;; Use World input to click the actual source row.
                                 ;; Directly calling selection policy cannot catch
                                 ;; a rendered row with a broken hit-test box.
                                 (let* ((picker (share-controller-picker controller))
                                        (seat (share-controller-seat controller))
                                        (x (+ (overlay-x picker) 100d0))
                                        (y (+ (overlay-y picker) 112d0)))
                                   (ataxia.kernel:world-cursor-motion world (%canvas-seat-seat seat)
                                     (ataxia.kernel:make-cursor-motion-input
                                       :delta-x (- x (%canvas-seat-x seat)) :delta-y (- y (%canvas-seat-y seat))))
                                   (dolist (state '(:pressed :released))
                                     (ataxia.kernel:world-cursor-button world (%canvas-seat-seat seat)
                                       (ataxia.kernel:make-cursor-button-input :code 272 :state state))))
                                 (assert (eq window (share-session-window session))))
                                (1
                                 (let ((state (%first-output-state world)))
                                   (setf (%canvas-output-camera-x state) (canvas-window-x window)
                                         (%canvas-output-camera-y state) (canvas-window-y window)
                                         (%canvas-output-zoom state) 1d0)
                                   (%share-begin-region controller)
                                   (let ((component (overlay-component (share-controller-region controller))))
                                     (ataxia.kernel:interactable-pointer-button component world nil 20d0 20d0
                                       (ataxia.kernel:make-cursor-button-input :code 272 :state :pressed))
                                     (ataxia.kernel:interactable-pointer-motion component world nil 320d0 220d0
                                       (ataxia.kernel:make-cursor-motion-input))
                                     (ataxia.kernel:interactable-pointer-button component world nil 320d0 220d0
                                       (ataxia.kernel:make-cursor-button-input :code 272 :state :released)))
                                   (assert (= 300d0 (third (share-session-bounds session))))
                                   ;; Move the physical viewport away. The region
                                   ;; still has to produce the application's pixels.
                                   (setf (%canvas-output-camera-x state) 90000d0 (%canvas-output-zoom state) .2d0)))
                                (3 (%share-close controller session)))
                              (unless (= 3 (share-session-types session))
                                (assert (not (share-session-active-p session)))
                                (%share-accept controller session)
                                (let ((pixels (share-session-pixels session)))
                                  (%share-accept controller session)
                                  (assert (eq pixels (share-session-pixels session))))
                                (assert (share-controller-indicators controller)))
                              (incf chosen))
                            (setf seen session))
                          (when (< chosen 3) (ataxia.runtime:update-event-loop-timer source 100))
                          0))))
           (ataxia.runtime:update-event-loop-timer timer 200))
         (let ((timer (ataxia.runtime:add-event-loop-timer runtime
                        (lambda (source)
                          (declare (ignore source))
                          (assert (= 3 chosen))
                          (assert (null (share-controller-sessions controller)))
                          (setf idle-start (%now) idle-cpu (get-internal-run-time))
                          0))))
           (ataxia.runtime:update-event-loop-timer timer 6000))
         (ataxia.kernel:run-kernel kernel :run-for 8d0)
         (assert idle-start)
         (assert (zerop idle-ticks))
         (assert (zerop idle-frames))
         (assert (= captures 2))
         (format t "SHARE-CACHE: window readbacks=~D (initial pixels + changed client buffer).~%" captures)
         (format t "SHARE-STOP-IDLE: seconds=~,3F frames=~D ticks=~D cpu-ms=~,3F~%"
                 (- (%now) idle-start) idle-frames idle-ticks
                 (* 1000d0 (/ (- (get-internal-run-time) idle-cpu) internal-time-units-per-second)))
         (assert (= 3 chosen))
         (assert (not (uiop:process-alive-p portal)))
         (assert (zerop (uiop:wait-process portal)))
         (assert (null (share-controller-sessions controller)))
         (assert (eq :running (ataxia.kernel:kernel-world-status kernel)))
         (format t "~A" (uiop:read-file-string "/tmp/ataxia-share-client.log"))
         (let ((replacement (make-metaworld :state-file nil)))
           (ataxia.kernel:install-world kernel replacement)
           (assert (null (ataxia.world:world-service world :screen-sharing)))
           (assert (ataxia.world:world-service replacement :screen-sharing))
           (assert (not (eq controller (ataxia.world:world-service replacement :screen-sharing)))))
         (format t "PASS: chooser, explicit consent, stop, service cleanup and World replacement.~%"))
    (setf (symbol-function '%render-window-capture-pixels) capture
          (symbol-function '%share-tick) tick
          (symbol-function 'ataxia.kernel::%render-output-frame) render)
    (when (and portal (uiop:process-alive-p portal)) (uiop:terminate-process portal))
    (when (and app (uiop:process-alive-p app)) (uiop:terminate-process app))
    (ataxia.kernel:destroy-kernel kernel :test)))
