;;;; Native controls and hardware keys against a fake backend in a real World.
(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-rmlui/status-bar")
(defpackage #:ataxia.test.shell-power
  (:use #:cl #:ataxia.world)
  (:local-nicknames (#:shell #:ataxia.world.shell)))
(in-package #:ataxia.test.shell-power)

(let* ((world (ataxia.metaworld:make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (owner sb-thread:*current-thread*)
       (power-reader (symbol-function 'shell::%bar-power))
       (percentage 0) (sleep-count 0) (brightness-count 0)
       (fail-brightness nil) (block-brightness nil)
       (release (sb-thread:make-semaphore :count 0))
       (service nil) (controller nil) (bar nil) (seat nil) (phase -1) (ticks 0) (before nil))
  (labels ((backend (kind value)
             (assert (not (eq owner sb-thread:*current-thread*)))
             (ecase kind
               (:refresh (list :backlight (list :percent percentage) :suspend-state :yes))
               (:brightness
                (incf brightness-count)
                (when block-brightness (sb-thread:wait-on-semaphore release))
                (when fail-brightness (error "Backlight permission denied"))
                (setf percentage value)
                (list :backlight (list :percent percentage) :brightness-error nil))
               (:suspend (incf sleep-count) (list :suspend-error nil))))
           (view () (shell::%power-view controller))
           (ready () (and (not (getf (view) :brightness-pending))
                          (not (getf (view) :suspend-pending))))
           (key (name state)
             (ataxia.kernel:world-key-event world seat
               (ataxia.kernel:make-key-input :keycode 0 :keysyms (vector name) :modifiers nil :state state)))
           (tap (name) (key name :pressed) (key name :released))
           (click (x y)
             (dolist (state '(:pressed :released))
               (ataxia.kernel:interactable-pointer-button
                (overlay-component (shell::%bar-popup bar)) world seat x y
                (ataxia.kernel:make-cursor-button-input :code 272 :state state))))
           (shown (id) (gethash id (ataxia.world.rmlui:widget-cache (shell::%bar-popup bar)))))
    (unwind-protect
         (progn
           (setf (symbol-function 'shell::%bar-power)
                 (lambda (&optional root) (declare (ignore root))
                   '(:capacity 100 :status :full :online t :health 90 :cycles 100)))
           (ataxia.kernel:start-kernel kernel)
           (shell:enable-rmlui-status-bar world :power-backend #'backend)
           (setf service (world-service world :shell) controller (shell::shell-service-power service)
                 bar (first (shell:status-bars world)) seat (world-seat-on-output world (overlay-output bar)))
           (shell::%bar-action world bar :power)
           (let ((timer
                   (ataxia.runtime:add-event-loop-timer
                    (ataxia.kernel:kernel-runtime kernel)
                    (lambda (source)
                      (incf ticks)
                      (assert (< ticks 80))
                      (case phase
                        (-1 (when (eq :yes (getf (view) :suspend-state))
                              ;; Opening the panel must not raise a zero backlight
                              ;; to the slider's minimum without user input.
                              (assert (= 0 brightness-count))
                              (assert (equal "0%" (shown "brightness-value")))
                              (setf percentage 40 phase 0)
                              (shell::%power-queue controller :refresh)))
                        (0 (when (eql 40 (getf (getf (view) :backlight) :percent))
                             (assert (= 0 brightness-count))
                             (assert (equal "40%" (shown "brightness-value")))
                             (click 323d0 106d0)
                             (setf phase 1)))
                        (1 (when (ready)
                             (assert (= percentage 45))
                             (assert (= 1 brightness-count))
                             (assert (equal "45%" (shown "brightness-value")))
                             (tap "XF86MonBrightnessDown")
                             (setf phase 2)))
                        (2 (when (ready)
                             (assert (= percentage 40))
                             ;; Native slider produces a real two-way model edit.
                             (click 190d0 106d0)
                             (setf phase 3)))
                        (3 (when (ready)
                             (assert (< 50 percentage 70))
                             (assert (equal (format nil "~D%" percentage) (shown "brightness-value")))
                             (setf fail-brightness t before percentage)
                             (tap "XF86MonBrightnessUp")
                             (setf phase 4)))
                        (4 (when (ready)
                             (assert (= before percentage))
                             (assert (search "permission denied" (shown "brightness-note")))
                             (assert (equal (format nil "~D%" before) (shown "brightness-value")))
                             (setf fail-brightness nil)
                             (click 25d0 139d0)
                             (setf phase 5)))
                        (5 (when (ready)
                             (assert (= 1 sleep-count))
                             (key "XF86Sleep" :pressed)
                             (setf phase 6)))
                        (6 (when (ready)
                             (assert (= 2 sleep-count))
                             ;; A held key cannot suspend again after wakeup.
                             (key "XF86Sleep" :pressed)
                             (assert (not (getf (view) :suspend-pending)))
                             (key "XF86Sleep" :released)
                             (setf block-brightness t)
                             (tap "XF86MonBrightnessUp")
                             (setf phase 7)))
                        (7
                         ;; This owner callback runs while the backend is blocked.
                         (assert (getf (view) :brightness-pending))
                         (tap "XF86Sleep")
                         (assert (getf (view) :suspend-pending))
                         (shell:disable-rmlui-status-bar world)
                         (assert (null (shell::power-controller-source controller)))
                         (assert (null (shell::power-controller-fd controller)))
                         (assert (null (world-service world :shell)))
                         (setf (symbol-function 'shell::%bar-power) power-reader)
      (sb-thread:signal-semaphore release)
                         (setf phase 8))
                        (8 (unless (sb-thread:thread-alive-p (shell::power-controller-thread controller))
                             (assert (= 2 sleep-count))
                             (assert (notany (lambda (widget)
                                               (typep widget '(or shell:rmlui-status-bar shell::rmlui-shell-popup)))
                                             (world-overlays world)))
                             (setf phase 9))))
                      (when (< phase 9) (ataxia.runtime:update-event-loop-timer source 70))
                      0))))
             (ataxia.runtime:update-event-loop-timer timer 200))
           (ataxia.kernel:run-kernel kernel :run-for 6d0)
           (assert (= phase 9))
           (assert (eq :running (ataxia.kernel:kernel-world-status kernel)))
           (format t "PASS: real brightness buttons/slider/keys, asynchronous readback, permission errors, Sleep button/key, held-key suppression, responsive owner, and shell teardown discards queued sleep.~%"))
      (setf (symbol-function 'shell::%bar-power) power-reader)
      (sb-thread:signal-semaphore release)
      (ataxia.kernel:destroy-kernel kernel :power-test-complete))))
