;;;; Hardware-free backend and asynchronous lifecycle regression tests.
(load (merge-pathnames "system-support.lisp" *load-truename*))
(asdf:load-system "ataxia-shell")
(in-package #:ataxia.world.shell)

(let ((arguments '("busctl" "--system" "call" "fixture")))
  (assert (equal arguments (%power-command arguments '("0::/user.slice/user-1000.slice/app.slice/ataxia.service"))))
  (assert (equal (append '("systemd-run" "--user" "--quiet" "--wait" "--collect" "--pipe" "--service-type=exec")
                         arguments)
                 (%power-command arguments '("0::/system.slice/ataxia-direct.service")))))

(let* ((root (merge-pathnames (format nil "ataxia-backlight-~D/" (random 1000000000)) (uiop:temporary-directory)))
       (display (merge-pathnames "test_panel/" root))
       (calls nil) (capability "s \"yes\""))
  (labels ((put (name value)
             (with-open-file (stream (merge-pathnames name display) :direction :output :if-exists :supersede)
               (princ value stream)))
           (call (&rest arguments)
             (push arguments calls)
             (cond ((equal (third arguments) "CanSuspend") capability)
                   ((equal (third arguments) "SetBrightness") (put "brightness" (car (last arguments))) "")
                   (t "")))
           (action (kind &optional value) (%system-power-action kind value :root root :call #'call)))
    (unwind-protect
         (progn
           (ensure-directories-exist display)
           (put "max_brightness" 1000) (put "brightness" 400)
           (assert (= 40 (getf (%display-backlight root) :percent)))
           (assert (eq :yes (getf (action :refresh) :suspend-state)))
           (assert (not (find "Suspend" calls :key #'third :test #'equal)))
           (assert (= 1 (getf (getf (action :brightness -200) :backlight) :percent)))
           (assert (equal (first calls) '("/org/freedesktop/login1/session/auto" "org.freedesktop.login1.Session"
                                         "SetBrightness" "ssu" "backlight" "test_panel" "10")))
           (assert (= 100 (getf (getf (action :brightness 200) :backlight) :percent)))
           (action :suspend)
           (assert (equal (first calls) '("/org/freedesktop/login1" "org.freedesktop.login1.Manager" "Suspend" "b" "false")))
           (dolist (state '("s \"no\"" "s \"challenge\"" "s \"na\"" "invalid"))
             (setf capability state calls nil)
             (assert (handler-case (progn (action :suspend) nil) (error () t)))
             (assert (not (find "Suspend" calls :key #'third :test #'equal))))
           (put "max_brightness" 0)
           (assert (null (%display-backlight root)))
           (assert (handler-case (progn (action :brightness 50) nil) (error () t))))
      (uiop:delete-directory-tree root :validate t :if-does-not-exist :ignore))))

;; Hold one request in flight. A burst retains only the newest brightness,
;; rejects repeated sleep, and shutdown discards every queued command.
(let* ((started (sb-thread:make-semaphore :count 0))
       (release (sb-thread:make-semaphore :count 0))
       (calls nil)
       (controller (make-power-controller
                    :backend (lambda (kind value)
                               (push (cons kind value) calls)
                               (sb-thread:signal-semaphore started)
                               (sb-thread:wait-on-semaphore release)
                               (list :backlight (list :percent 40))))))
  (unwind-protect
       (progn
         (setf (power-controller-thread controller)
               (sb-thread:make-thread (lambda () (%power-worker controller))))
         (%power-queue controller :refresh)
         (assert (sb-thread:wait-on-semaphore started :timeout 2))
         (loop for target from 1 to 100 do (%power-queue controller :brightness target))
         (assert (%power-queue controller :suspend))
         (assert (not (%power-queue controller :suspend)))
         (assert (equal (power-controller-queue controller) '((:brightness . 100) (:suspend))))
         (assert (getf (%power-view controller) :brightness-pending))
         (%stop-power-controller controller)
         (assert (not (%power-queue controller :brightness 50)))
         (sb-thread:signal-semaphore release)
         (sb-thread:join-thread (power-controller-thread controller) :timeout 2)
         (assert (equal calls '((:refresh))))
         (assert (null (getf (%power-view controller) :backlight))))
    (%stop-power-controller controller)
    (sb-thread:signal-semaphore release)))
(format t "PASS: backlight discovery/clamping, logind arguments, sleep capability checks, bounded queue, duplicate sleep, and cancellation of queued actions.~%")

;; Simulated time makes cadence, continuity and cancellation deterministic.
(let ((now 0d0) (samples nil) (targets 0))
  (flet ((clock () now)
         (wait (seconds) (incf now seconds))
         (write-value (value) (push (cons now value) samples)))
    (%fade-brightness 100 1000 90 #'write-value :clock #'clock :wait #'wait)
    (let ((values (mapcar #'cdr (reverse samples))))
      (assert (> (length values) 10))
      (assert (= 900 (car (last values))))
      (assert (every #'< (cons 100 (butlast values)) values))
      (assert (< (reduce #'max (mapcar #'- values (cons 100 (butlast values)))) 100)))
    (setf now 0d0 samples nil)
    (%fade-brightness 100 1000 90 #'write-value :clock #'clock :wait #'wait
                     :retarget (lambda (target)
                                 (if (and (> now .1d0) (zerop targets))
                                     (progn (incf targets) (values 20 nil))
                                     (values target nil))))
    (let ((values (mapcar #'cdr (reverse samples))))
      (assert (= targets 1))
      (assert (= 200 (car (last values))))
      (assert (< (reduce #'max values) 900))
      (assert (< (reduce #'max (mapcar (lambda (a b) (abs (- a b))) values (cons 100 (butlast values)))) 100)))
    (setf now 0d0 samples nil)
    (let ((last (%fade-brightness 100 1000 90 #'write-value :clock #'clock :wait #'wait
                                  :retarget (lambda (target) (values target (> now .08d0))))))
      (assert (< 100 last 900))
      (assert (< now .12d0)))))
(let ((controller (make-power-controller)))
  (%power-queue controller :brightness 80)
  (assert (= 80 (%power-fade-target controller 40)))
  (assert (null (power-controller-queue controller)))
  (%power-queue controller :suspend)
  (assert (nth-value 1 (%power-fade-target controller 80))))
(format t "PASS: smooth fade cadence, exact endpoint, continuous retargeting, cancellation and pending-target coalescing.~%")

;; Retarget the actual worker while its fade is running. It must consume the new
;; target within that fade, not finish an obsolete transition and start another.
(let* ((started (sb-thread:make-semaphore :count 0))
       (first-write t) (raw 100) (calls 0)
       (controller (make-power-controller
                    :backend (lambda (kind target)
                               (assert (eq kind :brightness))
                               (incf calls)
                               (%fade-brightness raw 1000 target
                                                 (lambda (value)
                                                   (setf raw value)
                                                   (when first-write
                                                     (setf first-write nil)
                                                     (sb-thread:signal-semaphore started))))
                               (list :backlight (list :percent (round raw 10)))))))
  (unwind-protect
       (progn
         (setf (power-controller-thread controller)
               (sb-thread:make-thread (lambda () (%power-worker controller))))
         (%power-queue controller :brightness 90)
         (assert (sb-thread:wait-on-semaphore started :timeout 2))
         (%power-queue controller :brightness 20)
         (loop repeat 100 while (getf (%power-view controller) :brightness-pending) do (sleep .01))
         (assert (not (getf (%power-view controller) :brightness-pending)))
         (assert (= calls 1))
         (assert (= 20 (getf (getf (%power-view controller) :backlight) :percent))))
    (%stop-power-controller controller)
    (sb-thread:join-thread (power-controller-thread controller) :timeout 2)))
(format t "PASS: a running worker fade accepts the newest target without replaying an obsolete transition.~%")
