;;;; Real client offers must be recorded, even after selecting a history item.
(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-rmlui/status-bar")
(asdf:load-system "ataxia-world/synthetic-input")
(defpackage #:ataxia.test.shell-clipboard-client
  (:use #:cl #:ataxia.world)
  (:local-nicknames (#:shell #:ataxia.world.shell) (#:rml #:ataxia.world.rmlui)))
(in-package #:ataxia.test.shell-clipboard-client)

(let* ((world (ataxia.metaworld:make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless
                                            :headless-width 1100 :headless-height 800))
       (runtime (ataxia.kernel:kernel-runtime kernel))
       (log (merge-pathnames (format nil "ataxia-shell-clipboard-~D.log" (sb-posix:getpid))
                            (uiop:temporary-directory)))
       (keyboard nil) (client nil) (seat nil) (service nil) (bar nil) (app nil)
       (phase 0) (ticks 0) (failure nil)
       (text "Clipboard from Clipboard history fixture on seat0 · λ🙂"))
  (labels ((state () (shell::%clipboard-seat service seat))
           (owned-p () (ataxia.runtime:seat-clipboard-owned-p (ataxia.kernel:seat-runtime-object seat)))
           (copy-in-client ()
             (let ((code (ataxia.world.synthetic-input:synthetic-keycode keyboard "F1")))
               (ataxia.runtime:seat-keyboard-notify-key (ataxia.kernel:seat-runtime-object seat) 0 code :pressed)
               (ataxia.runtime:seat-keyboard-notify-key (ataxia.kernel:seat-runtime-object seat) 1 code :released)))
           (check-history ()
             (assert (equal (list text) (shell::clipboard-seat-history (state))))
             (shell::%bar-action world bar :clipboard)
             (let ((popup (shell::%bar-popup bar)))
               (assert (equal (list text) (shell::%shell-popup-matches popup)))
               (assert (equal text (gethash "app0" (rml:widget-cache popup)))))
             (shell::%bar-close-popup world bar)))
    (unwind-protect
         (progn
           (ataxia.kernel:start-kernel kernel)
           (setf seat (first (world-seats world))
                 keyboard (ataxia.world.synthetic-input:create-synthetic-input runtime :keyboard "Clipboard test keyboard"))
           (ataxia.kernel:register-input-device kernel keyboard :seat seat)
           (shell:enable-rmlui-status-bar world :system-controls-p nil
             :power-backend (lambda (kind value) (declare (ignore kind value)) (list :backlight (list :percent 50))))
           (setf service (world-service world :shell) bar (first (shell:status-bars world))
                 (shell::shell-service-clipboard service) (make-hash-table :test #'eq)
                 (shell::shell-service-audio service) (shell::make-system-controller)
                 (shell::shell-service-media service) (shell::make-system-controller))
           (assert (not (owned-p)))
           (setf client (uiop:launch-program
                          (list "env" (format nil "WAYLAND_DISPLAY=~A" (ataxia.runtime:runtime-socket-name runtime))
                                "ATAXIA_TEST_TITLE=Clipboard history fixture"
                                (namestring (asdf:system-relative-pathname "ataxia-runtime" "build/computer-use-client"))
                                (namestring log))
                          :output :interactive :error-output :interactive))
           (let ((timer (ataxia.runtime:add-event-loop-timer runtime
                          (lambda (source)
                            (handler-case
                                (progn
                                  (incf ticks)
                                  (assert (< ticks 100) () "Clipboard history stalled in phase ~D." phase)
                                  (case phase
                                    (0 (setf app (first (ataxia.kernel:kernel-applications kernel)))
                                       (when (and app (ataxia.kernel:application-mapped-p app))
                                         (ataxia.kernel:interactable-focus app world seat :keyboard)
                                         (setf phase 1)))
                                    (1 (copy-in-client) (setf phase 2))
                                    (2 (when (shell::clipboard-seat-history (state))
                                         ;; C's false must stay false across the FFI boundary.
                                         (assert (not (owned-p)))
                                         (check-history)
                                         (shell::%bar-action world bar :clipboard)
                                         (shell::%choose-clipboard world (shell::%bar-popup bar) 0)
                                         (assert (owned-p))
                                         (ataxia.kernel:interactable-focus app world seat :keyboard)
                                         (setf phase 3)))
                                    (3 (copy-in-client) (setf phase 4))
                                    (4 (when (and (not (owned-p)) (shell::clipboard-seat-ready (state)))
                                         (check-history)
                                         (uiop:terminate-process client)
                                         (setf phase 5)))
                                    (5 (when (null (ataxia.kernel:kernel-applications kernel))
                                         (assert (null (ataxia.runtime:seat-selection-mime-types
                                                        (ataxia.kernel:seat-runtime-object seat))))
                                         ;; The entry remains visible after the source app closes.
                                         (check-history)
                                         (shell:disable-rmlui-status-bar world)
                                         (ataxia.world.synthetic-input:destroy-synthetic-input keyboard)
                                         (setf keyboard nil phase 6)
                                         (ataxia.kernel:request-kernel-stop kernel :checks-complete))))
                                  (when (< phase 6) (ataxia.runtime:update-event-loop-timer source 50)))
                              (error (cause)
                                (setf failure cause)
                                (ataxia.kernel:request-kernel-stop kernel :checks-failed))) 0))))
             (ataxia.runtime:update-event-loop-timer timer 50))
           (ataxia.kernel:run-kernel kernel :run-for 6d0)
           (when failure (error failure))
           (assert (= phase 6))
           (assert (eq :running (ataxia.kernel:kernel-world-status kernel)))
           (format t "PASS: real Wayland copy, Unicode history rows, clipboard ownership, repeat-copy deduplication and history after source exit.~%"))
      (when client (ignore-errors (uiop:terminate-process client)))
      (when keyboard (ignore-errors (ataxia.world.synthetic-input:destroy-synthetic-input keyboard)))
      (ataxia.kernel:destroy-kernel kernel :clipboard-test-complete)
      (when (probe-file log) (delete-file log)))))
