;;;; System UI behavior, asynchronous clipboard reads and native editor bridging.
(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-rmlui/status-bar")
(defpackage #:ataxia.test.shell-controls
  (:use #:cl #:ataxia.world)
  (:local-nicknames (#:shell #:ataxia.world.shell) (#:rml #:ataxia.world.rmlui)))
(in-package #:ataxia.test.shell-controls)
(let* ((world (ataxia.metaworld:make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (runtime (ataxia.kernel:kernel-runtime kernel)) (service nil) (bar nil) (seat nil)
       (audio (shell::make-system-controller)) (media (shell::make-system-controller))
       (editor nil) (editor-widget nil) (phase -1) (ticks 0) (captured nil) (transfer-text "Wayland → native · λ🙂")
       (second-seat nil))
  (labels ((key (name &optional (state :pressed) modifiers)
             (ataxia.kernel:world-key-event world seat
               (ataxia.kernel:make-key-input :keycode 0 :keysyms (vector name) :modifiers modifiers :state state)))
           (edit-key (name modifiers)
             (dolist (state '(:pressed :released))
               (ataxia.kernel:interactable-key-event editor world seat
                 (ataxia.kernel:make-key-input :keycode 0 :keysyms (vector name) :modifiers modifiers :state state))))
           (state () (shell::%clipboard-seat service seat))
           (start-read (text callback)
             (ataxia.runtime:seat-set-clipboard-text (ataxia.kernel:seat-runtime-object seat) text)
             (setf (shell::clipboard-seat-ready (state)) nil)
             (shell::%clipboard-begin world service seat (state) callback)))
    (unwind-protect
         (progn
           (ataxia.kernel:start-kernel kernel)
           (shell:enable-rmlui-status-bar world :system-controls-p nil
             :power-backend (lambda (kind value) (declare (ignore kind value)) (list :backlight (list :percent 50))))
           (setf service (world-service world :shell) bar (first (shell:status-bars world))
                 seat (world-seat-on-output world (overlay-output bar))
                 (shell::shell-service-audio service) audio (shell::shell-service-media service) media
                 (shell::shell-service-clipboard service) (make-hash-table :test #'eq))
           (shell::%system-publish audio :available t :volume 40 :muted nil :device "Test output")
           (shell::%system-publish media :available t)
           (shell::%sync-system-controls world service)
           (shell::%bar-action world bar :spaces)
           (let* ((popup (shell::%bar-popup bar))
                  (groups (getf (world-shell-state world (overlay-output bar)) :groups)))
             (assert groups)
             (assert (search "You are" (gethash "location" (rml:widget-cache popup))))
             (assert (equal "block" (gethash '("workspace-card1" "display") (rml:widget-cache popup))))
             (loop for number from 2 to 9 do
               (assert (equal "none" (gethash (list (format nil "workspace-card~D" number) "display")
                                              (rml:widget-cache popup)))))
             (assert (equal "block" (gethash '("workspace-new" "display") (rml:widget-cache popup))))
             (shell::%new-workspace world popup)
             (assert (= 2 (getf (world-shell-state world (overlay-output bar)) :selected))))
           (shell::%bar-action world bar :spaces)
           (let ((popup (shell::%bar-popup bar)))
             (assert (equal "block" (gethash '("workspace-card1" "display") (rml:widget-cache popup))))
             (assert (equal "block" (gethash '("workspace-card2" "display") (rml:widget-cache popup))))
             ;; Direct workspace shortcuts still reach an unused destination.
             (key "3")
             (assert (= 3 (getf (world-shell-state world (overlay-output bar)) :selected))))
           ;; Visited empty pages remain accessible after returning to page one.
           (world-shell-action world (overlay-output bar) seat :workspace 1)
           (shell::%bar-action world bar :spaces)
           (let ((popup (shell::%bar-popup bar)))
             (loop for number from 1 to 3 do
               (assert (equal "block" (gethash (list (format nil "workspace-card~D" number) "display")
                                              (rml:widget-cache popup)))))
             (assert (= 4 (shell::%next-empty-workspace
                           (first (getf (world-shell-state world (overlay-output bar)) :groups)))))
             (key "Escape"))
           (shell::%bar-action world bar :media)
           (let ((popup (shell::%bar-popup bar)))
             (assert (equal "40%" (gethash "volume-value" (rml:widget-cache popup))))
             (key "XF86AudioRaiseVolume") (key "XF86AudioRaiseVolume")
             (assert (= 50 (shell::%audio-percent (shell::%system-view audio))))
             (assert (eq popup (world-seat-focus world seat)))
             (assert (not (overlay-input-enabled-p (gethash (overlay-output bar) (shell::shell-service-osds service)))))
             (key "XF86AudioMute") (key "XF86AudioMute")
             (assert (shell::%audio-muted (shell::%system-view audio)))
             (key "XF86AudioMute" :released) (key "XF86AudioMute")
             (assert (not (shell::%audio-muted (shell::%system-view audio))))
             (key "Escape"))
           (setf second-seat (ataxia.kernel:create-logical-seat kernel "clipboard-second"))
           (assert (set-clipboard-text world seat "native copy · λ🙂"))
           (request-clipboard-text world second-seat (lambda (text) (assert (null text))))
           (dotimes (i 25) (set-clipboard-text world seat (format nil "history ~D" i)))
           (assert (= 20 (length (shell::clipboard-seat-history (state)))))
           (set-clipboard-text world seat "history 20")
           (assert (equal "history 20" (first (shell::clipboard-seat-history (state)))))
           (key "v" :pressed '(:logo :control))
           (assert (eq :clipboard (shell::%shell-popup-kind (shell::%bar-popup bar))))
           (key "v" :pressed '(:logo :control))
           (assert (eq :clipboard (shell::%shell-popup-kind (shell::%bar-popup bar))))
           (key "v" :released nil)
           (shell::%choose-clipboard world (shell::%bar-popup bar) 1)
           (assert (null (shell::%bar-popup bar)))
           (setf editor-widget (create-agent-widget 'rml:rmlui-widget world
                                 "<rml><head><style>body { font-family:DejaVu Sans; } input { width:450dp; height:32dp; }</style></head><body data-model='state'><input id='edit' type='text' data-value='text' autofocus='autofocus'/></body></rml>"
                                 :component-factory #'rml:make-rmlui-component :output (overlay-output bar)
                                 :width 500d0 :height 80d0 :layer 1400)
                 editor (overlay-component editor-widget))
           (rml:set-rmlui-model editor "text" "Native editor → apps · λ🙂")
           (focus-world-target world seat editor-widget)
           (let ((timer (ataxia.runtime:add-event-loop-timer runtime
                          (lambda (source)
                            (incf ticks) (assert (< ticks 80))
                            (case phase
                              (-1
                               (edit-key "a" '(:control)) (edit-key "c" '(:control))
                               (assert (equal "Native editor → apps · λ🙂" (shell::clipboard-seat-text (state))))
                               (rml:set-rmlui-model editor "text" "")
                               (start-read transfer-text (lambda (text) (setf captured text)))
                               (edit-key "v" '(:control))
                               (setf phase 0))
                              (0 (when captured
                                   (assert (equal captured transfer-text))
                                   (assert (equal transfer-text (rml:rmlui-model-value editor "text")))
                                   ;; A stale asynchronous paste cannot land after focus moved.
                                   (rml:set-rmlui-model editor "text" "")
                                   (setf captured nil)
                                   (start-read "stale paste" (lambda (text) (setf captured text)))
                                   (edit-key "v" '(:control))
                                   (ataxia.kernel:interactable-focus editor world seat :none)
                                   (setf phase 1)))
                              (1 (when captured
                                   (assert (equal "" (rml:rmlui-model-value editor "text")))
                                   (setf captured nil)
                                   (start-read (make-string 180000 :initial-element #\x) (lambda (text) (setf captured text)))
                                   (setf phase 2)))
                              (2 (when captured
                                   (assert (= 180000 (length captured)))
                                   (setf phase 3)))
                              (3 (when (zerop (hash-table-count (shell::shell-service-osds service)))
                                   (assert (notany (lambda (x) (typep x 'shell::shell-osd)) (world-overlays world)))
                                   (shell:disable-rmlui-status-bar world)
                                   (assert (null (shell::shell-service-osd-timer service)))
                                   (assert (null (shell::shell-service-clipboard service)))
                                   (setf phase 4))))
                            (when (< phase 4) (ataxia.runtime:update-event-loop-timer source 50)) 0))))
             (ataxia.runtime:update-event-loop-timer timer 50))
           (ataxia.kernel:run-kernel kernel :run-for 4.5d0)
           (assert (= phase 4))
           (assert (eq :running (ataxia.kernel:kernel-world-status kernel)))
           (format t "PASS: named workspaces, volume/mute keys, OSD focus/expiry, clipboard history bounds/selection, seat isolation, native editor copy/paste, stale-focus cancellation, large asynchronous transfer and cleanup.~%"))
      (when editor-widget (remove-agent-widget world editor-widget))
      (ataxia.kernel:destroy-kernel kernel :shell-controls-complete))))
