;;;; Run with dbus-run-session so transport tests only reach our fixture.
(load (merge-pathnames "system-support.lisp" *load-truename*))
(asdf:load-system "ataxia-rmlui/status-bar")
(in-package #:ataxia.world.shell)
(let* ((controller (make-system-controller :wake-fd (%eventfd)))
       (failure nil) (fixture nil)
       (thread (sb-thread:make-thread (lambda () (handler-case (%run-media controller)
                                                   (error (cause) (setf failure cause)))))))
  (labels ((wait-for (test)
             (loop repeat 120 for view = (%system-view controller)
                   when failure do (error failure)
                   when (funcall test view) return view do (sleep .025d0)
                   finally (error "MPRIS state did not arrive: ~S" (%system-view controller))))
           (player-is (key value) (lambda (view) (equal value (getf (getf view :player) key))))
           (fixture-call (method)
             (let ((bus (%open-media-bus)))
               (unwind-protect (%bus-call bus "org.mpris.MediaPlayer2.ataxia_fixture" "/org/mpris/MediaPlayer2" "org.ataxia.Test" method)
                 (cffi:foreign-funcall "sd_bus_flush_close_unref" :pointer bus :pointer)))))
    (unwind-protect
         (progn
           (wait-for (lambda (view) (getf view :available)))
           (assert (null (getf (%system-view controller) :players)))
           (setf fixture (uiop:launch-program (list "/usr/bin/python3" (namestring (merge-pathnames "shell-mpris-fixture.py" *load-truename*)))
                                              :output :stream :error-output :interactive))
           (assert (equal "READY" (read-line (uiop:process-info-output fixture))))
           (wait-for (player-is :title "First track"))
           (assert (equal "Test artist · λ" (getf (getf (%system-view controller) :player) :artist)))
           (%system-queue controller :play-pause)
           (wait-for (player-is :status "Playing"))
           (%system-queue controller :next)
           (wait-for (player-is :title "Next track"))
           (fixture-call "Update")
           (wait-for (player-is :title "Externally changed"))
           (assert (not (getf (getf (%system-view controller) :player) :can-next)))
           (%system-queue controller :next)
           (sleep .15d0)
           (assert (equal "Externally changed" (getf (getf (%system-view controller) :player) :title)))
           (%system-queue controller :previous)
           (wait-for (lambda (view) (getf view :error)))
           (%system-queue controller :stop)
           (wait-for (player-is :status "Stopped"))
           (fixture-call "Quit")
           (wait-for (lambda (view) (null (getf view :players))))
           (format t "PASS: MPRIS appearance/disappearance, Unicode metadata, external PropertiesChanged, play/next/stop, capability gating, and transport errors over private D-Bus.~%"))
      (%stop-system-controller controller)
      (sb-thread:join-thread thread :timeout 2d0)
      (cffi:foreign-funcall "close" :int (system-controller-wake-fd controller) :int)
      (when fixture (uiop:terminate-process fixture)))))
