;;;; Two clients of an isolated Pulse protocol server test real subscriptions.
(load (merge-pathnames "system-support.lisp" *load-truename*))
(asdf:load-system "ataxia-rmlui/status-bar")
(in-package #:ataxia.world.shell)
(assert (search "ataxia-audio-test-" (or (uiop:getenv "PULSE_SERVER") "")))
(let* ((observer (make-system-controller :wake-fd (%eventfd)))
       (writer (make-system-controller :wake-fd (%eventfd)))
       (failure nil)
       (threads (loop for controller in (list observer writer) collect
                  (let ((controller controller))
                    (sb-thread:make-thread (lambda () (handler-case (%run-audio controller)
                                                       (error (cause) (setf failure cause)))))))))
  (labels ((wait-for (test)
             (loop repeat 150 for view = (%system-view observer)
                   when failure do (error failure)
                   when (funcall test view) return view do (sleep .02d0)
                   finally (error "Audio state did not arrive: ~S" (%system-view observer)))))
    (unwind-protect
         (progn
           (wait-for (lambda (view) (and (getf view :available) (getf (%system-view writer) :available))))
           (%system-queue writer :volume 43)
           (wait-for (lambda (view) (= 43 (getf view :volume))))
           (%system-queue writer :mute t)
           (wait-for (lambda (view) (getf view :muted)))
           (%system-queue observer :mute nil)
           (wait-for (lambda (view) (not (getf view :muted))))
           (loop for volume from 44 to 75 do (%system-queue observer :volume volume))
           (wait-for (lambda (view) (and (= 75 (getf view :volume)) (null (getf view :volume-target)))))
           (%system-queue writer :volume 0)
           (wait-for (lambda (view) (zerop (getf view :volume))))
           (%system-queue writer :volume 35)
           (wait-for (lambda (view) (= 35 (getf view :volume))))
           (format t "PASS: native Pulse subscriptions, external volume/mute changes, command readback, burst coalescing, zero-volume recovery and worker shutdown.~%"))
      (dolist (controller (list observer writer)) (%stop-system-controller controller))
      (dolist (thread threads) (sb-thread:join-thread thread :timeout 2d0))
      (dolist (controller (list observer writer))
        (cffi:foreign-funcall "close" :int (system-controller-wake-fd controller) :int)))))
