;;;; Real windows and notes survive menu removal; workspaces fit above the bar.
(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-web/status-bar")
(in-package #:ataxia.infinite-world)

(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 700))
       (runtime (ataxia.kernel:kernel-runtime kernel)) (clients nil) (logs nil)
       (phase 0) (ticks 0) (failure nil) (notes nil) (bar nil) (seat nil) (output nil))
  (labels ((launch (name)
             (let ((log (merge-pathnames (format nil "ataxia-workspaces-~D-~A.log" (sb-posix:getpid) name)
                                        (uiop:temporary-directory))))
               (push log logs)
               (push (uiop:launch-program
                      (list "env" (format nil "WAYLAND_DISPLAY=~A" (ataxia.runtime:runtime-socket-name runtime))
                            (format nil "ATAXIA_TEST_TITLE=~A" name)
                            (namestring (asdf:system-relative-pathname "ataxia-runtime" "build/computer-use-client"))
                            (namestring log)) :output :interactive :error-output :interactive) clients)))
           (open-menu (group)
             (ataxia.world.shell::%bar-action world bar :spaces)
             (let ((popup (ataxia.world.shell::%bar-popup bar)))
               (let ((state (ataxia.world.shell::%workspace-popup-state popup)))
                 (setf (getf state :group) (subworld-id group)))
               (ataxia.world.shell::%sync-workspace-popup world popup)
               popup))
           (remove-page (group number)
             (let ((popup (open-menu group)))
               (assert (equal "block" (gethash (list (format nil "workspace-remove~D" number) "display")
                                               (ataxia.world.shell:shell-cache popup))))
               (ataxia.world.shell::%remove-workspace-destination world popup number)))
           (check-fit (group)
             (let ((state (gethash output (%world-outputs world))))
               (%meta-refit-work-area world output)
               (multiple-value-bind (x y width height) (ataxia.world:world-output-work-area world output)
                 (declare (ignore x width))
                 (let* ((zoom (%canvas-output-zoom state))
                        (top (* (- (%meta-workspace-y group) (%canvas-output-camera-y state)) zoom))
                        (bottom (+ top (* (subworld-height group) zoom))))
                   (assert (>= top (- y .00001d0)))
                   (assert (<= bottom (+ y height .00001d0)))
                   (when (eq :niri (subworld-kind group))
                     (assert (< (abs (- bottom (+ y height))) .00001d0)))))))
           (checks ()
             (let* ((windows (sort (copy-list (%world-stacking world)) #'string<
                                   :key (lambda (w) (ataxia.kernel:application-title (canvas-window-application w)))))
                    (a (first windows)) (b (second windows)) (c (third windows))
                    (group (first (metaworld-subworlds world)))
                    (hypr (second (metaworld-subworlds world)))
                    (apps (copy-list (ataxia.kernel:kernel-applications kernel)))
                    (note (%meta-new-note world group "Retained note · λ🙂"))
                    (record (list :owner (subworld-id group) :geometry (list 100d0 1700d0 400d0 300d0)
                                  :member (list :workspace 3 :column 77 :restore (list 100d0 1710d0 400d0 300d0))))
                    (pending (%make-meta-launch :expires (+ (%now) 60d0) :group-id (subworld-id group) :workspace 2)))
               (push note notes)
               (setf (%meta-restoring-p world) t)
               (%with-meta-layout-batch (world)
                 (move-object-to-subworld world a group :workspace 1)
                 (move-object-to-subworld world b group :workspace 2)
                 (move-object-to-subworld world c group :workspace 3)
                 (move-object-to-subworld world note group :workspace 2))
               (setf (subworld-member-column (%meta-member group b)) (subworld-member-column (%meta-member group a))
                     (subworld-member-column (%meta-member group note)) (subworld-member-column (%meta-member group b))
                     (gethash 3 (subworld-scrolls group)) 30d0
                     (gethash group *meta-workspace-focus*) (let ((table (make-hash-table))) (setf (gethash 3 table) c) table)
                     (%meta-hypr-tree group 3) (subworld-member-column (%meta-member group c))
                     (%meta-saved-windows world) (list record)
                     (%meta-pending-launches world) (list pending))
               (%set-window-minimized world b t)
               (enter-subworld world group seat)
               (%meta-switch-workspace world group 2 seat)
               (%meta-toggle-fullscreen world note t nil)
               (check-fit group)
               (remove-page group 2)
               (assert (equal apps (ataxia.kernel:kernel-applications kernel)))
               (assert (= 4 (length (subworld-members group))))
               (assert (null (subworld-fullscreen group)))
               (assert (%canvas-window-minimized-p b))
               (assert (equal "Retained note · λ🙂" (%meta-note-content note)))
               (assert (member note (world-overlays world)))
               (assert (equal '(1 1 2 1) (mapcar (lambda (object) (subworld-member-workspace (%meta-member group object)))
                                                (list a b c note))))
               (assert (/= (subworld-member-column (%meta-member group a)) (subworld-member-column (%meta-member group b))))
               (assert (= (subworld-member-column (%meta-member group b)) (subworld-member-column (%meta-member group note))))
               (assert (= 30d0 (gethash 2 (subworld-scrolls group))))
               (assert (eq c (gethash 2 (gethash group *meta-workspace-focus*))))
               (assert (= 2 (getf (getf record :member) :workspace)))
               (assert (= (- 1700d0 (subworld-height group)) (second (getf record :geometry))))
               (assert (= 1 (%meta-launch-workspace pending)))
               (assert (= 2 (%meta-workspace-count (%meta-load-group (%meta-group-record group)))))
               (check-fit group)
               ;; An empty current page is removable, while the remaining page stays.
               (%meta-switch-workspace world group 3 seat)
               (remove-page group 3)
               (assert (= 2 (subworld-workspace group)))
               (assert (= 2 (%meta-workspace-count group)))
               ;; Removing an empty, inactive page retains other empty pages.
               (%meta-switch-workspace world group 5 seat)
               (%meta-switch-workspace world group 1 seat)
               (remove-page group 3)
               (assert (= 4 (%meta-workspace-count group)))
               (assert (= 4 (%meta-workspace-count (%meta-load-group (%meta-group-record group)))))
               (assert (= 1 (subworld-workspace group)))
               (setf (%meta-saved-windows world) nil (%meta-pending-launches world) nil)
               (ataxia.world.shell::%remove-workspace-destination world (open-menu group))
               (assert (not (member group (metaworld-subworlds world))))
               (dolist (object (list a b c note)) (assert (null (object-subworld world object))))
               (assert (equal apps (ataxia.kernel:kernel-applications kernel)))
               (assert (member note (world-overlays world)))
               ;; Hyprland retains the destination tree and shifts later page state.
               (%set-window-minimized world b nil)
               (%with-meta-layout-batch (world)
                 (move-object-to-subworld world a hypr :workspace 1)
                 (move-object-to-subworld world b hypr :workspace 2)
                 (move-object-to-subworld world c hypr :workspace 3))
               (setf (%meta-hypr-tree hypr 3) (subworld-member-column (%meta-member hypr c)))
               (enter-subworld world hypr seat)
               (remove-page hypr 2)
               (assert (= (subworld-member-column (%meta-member hypr c)) (%meta-hypr-tree hypr 2)))
               (assert (= 1 (subworld-member-workspace (%meta-member hypr b))))
               (check-fit hypr)
               (remove-page hypr 1)
               (assert (= 1 (%meta-workspace-count hypr)))
               (assert (null (%meta-remove-workspace world hypr 1 seat)))
               (let ((popup (open-menu hypr)))
                 (assert (equal "none" (gethash '("workspace-remove1" "display") (ataxia.world.shell:shell-cache popup))))
                 (setf (%meta-standalone world) :hyprland)
                 (ataxia.world.shell::%sync-workspace-popup world popup)
                 (assert (equal "none" (gethash '("group-remove" "display") (ataxia.world.shell:shell-cache popup))))
                 (ataxia.world:world-shell-action world output seat :remove-subworld (subworld-id hypr))
                 (assert (member hypr (metaworld-subworlds world)))
                 (setf (%meta-standalone world) nil)
                 (ataxia.world.shell::%bar-close-popup world bar))
               ;; Every orientation/scale uses logical bar height; no bar means full height.
               (let ((original (list (ataxia.kernel:output-width output) (ataxia.kernel:output-height output)
                                     (ataxia.kernel:output-scale output) (ataxia.kernel:output-transform output))))
                 (unwind-protect
                      (dolist (geometry '((1100 700 1d0 0) (1920 1080 1.5d0 0) (1080 1920 1d0 0) (1920 1080 1.5d0 1)))
                        (setf (ataxia.kernel:output-width output) (first geometry)
                              (ataxia.kernel:output-height output) (second geometry)
                              (ataxia.kernel:output-scale output) (third geometry)
                              (ataxia.kernel:output-transform output) (fourth geometry))
                        (dolist (kind '(:niri :hyprland))
                          (setf (subworld-kind hypr) kind)
                          (check-fit hypr)))
                   (setf (ataxia.kernel:output-width output) (first original)
                         (ataxia.kernel:output-height output) (second original)
                         (ataxia.kernel:output-scale output) (third original)
                         (ataxia.kernel:output-transform output) (fourth original))))
               (setf (subworld-kind hypr) :niri)
               (ataxia.world.web.shell:disable-web-status-bar world)
               (check-fit hypr)
               (assert (< (abs (- (* (subworld-height hypr) (%canvas-output-zoom (gethash output (%world-outputs world)))) 700d0)) .00001d0))
               (assert (equal apps (ataxia.kernel:kernel-applications kernel)))
               (dolist (state (%seat-states world)) (%focus-target world state nil))
               (dolist (note notes) (remove-agent-widget world note))
               (setf notes nil)
               (dolist (client clients) (uiop:terminate-process client)))))
    (unwind-protect
         (progn
           (ataxia.kernel:start-kernel kernel)
           (setf output (%canvas-output-output (%first-output-state world))
                 seat (ataxia.world:world-seat-on-output world output))
           (ataxia.world.web.shell:enable-web-status-bar world :system-controls-p nil
             :power-backend (lambda (kind value) (declare (ignore kind value)) nil))
           (setf bar (first (ataxia.world.shell:status-bars world)))
           (dolist (name '("A" "B" "C")) (launch name))
           (let ((timer (ataxia.runtime:add-event-loop-timer runtime
                          (lambda (source)
                            (handler-case
                                (progn
                                  (incf ticks) (assert (< ticks 100))
                                  (case phase
                                    (0 (when (and (= 3 (length (%world-stacking world)))
                                                  (every #'%canvas-window-mapped-p (%world-stacking world)))
                                         (checks) (setf phase 1)))
                                    (1 (when (null (ataxia.kernel:kernel-applications kernel))
                                         (setf phase 2) (ataxia.kernel:request-kernel-stop kernel :checks-complete))))
                                  (when (< phase 2) (ataxia.runtime:update-event-loop-timer source 50)))
                              (error (cause) (setf failure cause) (ataxia.kernel:request-kernel-stop kernel :checks-failed))) 0))))
             (ataxia.runtime:update-event-loop-timer timer 50))
           (ataxia.kernel:run-kernel kernel :run-for 6d0)
           (when failure (error failure))
           (assert (= phase 2))
           (assert (eq :running (ataxia.kernel:kernel-world-status kernel)))
           (format t "PASS: bar work areas, scale/rotation, Niri/Hyprland menu removal, retained windows/minimized state/notes, remapped saved pages and last-workspace protection.~%"))
      (dolist (client clients) (ignore-errors (uiop:terminate-process client)))
      (ataxia.kernel:destroy-kernel kernel :workspace-test-complete)
      (dolist (log logs) (when (probe-file log) (delete-file log))))))
