;;;; System UI behavior and asynchronous clipboard reads.
(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-web/status-bar")
(defpackage #:ataxia.test.shell-controls
  (:use #:cl #:ataxia.world)
  (:local-nicknames (#:shell #:ataxia.world.shell)))
(in-package #:ataxia.test.shell-controls)
(let* ((world (ataxia.metaworld:make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (runtime (ataxia.kernel:kernel-runtime kernel)) (service nil) (bar nil) (seat nil)
       (audio (shell::make-system-controller)) (media (shell::make-system-controller))
       (phase 0) (ticks 0) (captured nil)
       (second-seat nil))
  (labels ((key (name &optional (state :pressed) modifiers)
             (ataxia.kernel:world-key-event world seat
               (ataxia.kernel:make-key-input :keycode 0 :keysyms (vector name) :modifiers modifiers :state state)))
           (state () (shell::%clipboard-seat service seat))
           (start-read (text callback)
             (ataxia.runtime:seat-set-clipboard-text (ataxia.kernel:seat-runtime-object seat) text)
             (setf (shell::clipboard-seat-ready (state)) nil)
             (shell::%clipboard-begin world service seat (state) callback)))
    (unwind-protect
         (progn
           (ataxia.kernel:start-kernel kernel)
           (ataxia.world.web.shell:enable-web-status-bar world :system-controls-p nil
             :power-backend (lambda (kind value) (declare (ignore kind value)) (list :backlight (list :percent 50))))
           (setf service (world-service world :shell) bar (first (shell:status-bars world))
                 seat (world-seat-on-output world (overlay-output bar))
                 (shell::shell-service-audio service) audio (shell::shell-service-media service) media
                 (shell::shell-service-clipboard service) (make-hash-table :test #'eq))
           (shell::%system-publish audio :available t :volume 40 :muted nil :device "Test output")
           (shell::%system-publish media :available t)
           (shell::%sync-system-controls world service)
           (shell::%bar-action world bar :spaces)
           (let* ((popup (shell::%bar-popup bar))
                  (groups (getf (world-shell-state world (overlay-output bar)) :groups)))
             (assert groups)
             (assert (search "You are" (gethash "location" (shell:shell-cache popup))))
             (assert (equal "block" (gethash '("workspace-card1" "display") (shell:shell-cache popup))))
             (loop for number from 2 to 9 do
               (assert (equal "none" (gethash (list (format nil "workspace-card~D" number) "display")
                                              (shell:shell-cache popup)))))
             (assert (equal "block" (gethash '("workspace-new" "display") (shell:shell-cache popup))))
             (shell::%new-workspace world popup)
             (assert (= 2 (getf (world-shell-state world (overlay-output bar)) :selected))))
           (shell::%bar-action world bar :spaces)
           (let ((popup (shell::%bar-popup bar)))
             (assert (equal "block" (gethash '("workspace-card1" "display") (shell:shell-cache popup))))
             (assert (equal "block" (gethash '("workspace-card2" "display") (shell:shell-cache popup))))
             ;; Direct workspace shortcuts still reach an unused destination.
             (key "3")
             (assert (= 3 (getf (world-shell-state world (overlay-output bar)) :selected))))
           ;; Visited empty pages remain accessible after returning to page one.
           (world-shell-action world (overlay-output bar) seat :workspace 1)
           (shell::%bar-action world bar :spaces)
           (let ((popup (shell::%bar-popup bar)))
             (loop for number from 1 to 3 do
               (assert (equal "block" (gethash (list (format nil "workspace-card~D" number) "display")
                                              (shell:shell-cache popup)))))
             (assert (= 4 (shell::%next-empty-workspace
                           (first (getf (world-shell-state world (overlay-output bar)) :groups)))))
             (key "Escape"))
           (shell::%bar-action world bar :media)
           (let ((popup (shell::%bar-popup bar)))
             (assert (equal "40%" (gethash "volume-value" (shell:shell-cache popup))))
             (key "XF86AudioRaiseVolume") (key "XF86AudioRaiseVolume")
             (assert (= 50 (shell::%audio-percent (shell::%system-view audio))))
             (assert (eq popup (world-seat-focus world seat)))
             (assert (not (overlay-input-enabled-p (gethash (overlay-output bar) (shell::shell-service-osds service)))))
             (key "XF86AudioMute") (key "XF86AudioMute")
             (assert (shell::%audio-muted (shell::%system-view audio)))
             (key "XF86AudioMute" :released) (key "XF86AudioMute")
             (assert (not (shell::%audio-muted (shell::%system-view audio))))
             (key "Escape"))
           (setf second-seat (ataxia.kernel:create-logical-seat kernel "clipboard-second"))
           (assert (set-clipboard-text world seat "native copy · λ🙂"))
           (request-clipboard-text world second-seat (lambda (text) (assert (null text))))
           (dotimes (i 25) (set-clipboard-text world seat (format nil "history ~D" i)))
           (assert (= 20 (length (shell::clipboard-seat-history (state)))))
           (set-clipboard-text world seat "history 20")
           (assert (equal "history 20" (first (shell::clipboard-seat-history (state)))))
           (key "v" :pressed '(:logo :control))
           (assert (eq :clipboard (shell::%shell-popup-kind (shell::%bar-popup bar))))
           (key "v" :pressed '(:logo :control))
           (assert (eq :clipboard (shell::%shell-popup-kind (shell::%bar-popup bar))))
           (key "v" :released nil)
           (let* ((popup (shell::%bar-popup bar))
                  (cache (shell:shell-cache popup))
                  (original (shell::clipboard-seat-text (state)))
                  (component (overlay-component popup)))
             (assert (equal original (gethash "preview" cache)))
             (assert (= 180d0 (gethash :preferred-height cache)))
             (key "Down")
             (assert (equal (second (shell::clipboard-seat-history (state))) (gethash "preview" cache)))
             (assert (equal original (shell::clipboard-seat-text (state))))
             (assert (gethash '(:model "prev_disabled") cache))
             (setf (shell::%shell-popup-page popup) 3)
             (shell::%clipboard-results world service popup)
             (assert (gethash '(:model "next_disabled") cache))
             (ataxia.world.web.ui:set-ui-model component "query" "no such clipboard entry")
             (shell::%clipboard-results world service popup t)
             (assert (equal "" (gethash "preview" cache)))
             (assert (search "No matches" (gethash "empty" cache)))
             (shell::%bar-position-popup world bar (overlay-output bar))
             (assert (= 100d0 (overlay-height popup)))
             (assert (not (gethash '(:model "clear_disabled") cache)))
             ;; Preview truncation never changes the text that would be copied.
             (let ((long (concatenate 'string (format nil "first line~%second line~%")
                                      (make-string 3000 :initial-element #\x))))
               (setf (shell::%shell-popup-matches popup) (list long))
               (shell::%shell-select popup 0)
               (assert (= 2048 (length (gethash "preview" cache))))
               (assert (find #\Newline (gethash "preview" cache)))
               (assert (equal long (first (shell::%shell-popup-matches popup)))))
             (ataxia.world.web.ui:set-ui-model component "query" "")
             (shell::%clipboard-results world service popup t))
           (shell::%choose-clipboard world (shell::%bar-popup bar) 1)
           (assert (null (shell::%bar-popup bar)))
           (let ((timer (ataxia.runtime:add-event-loop-timer runtime
                          (lambda (source)
                            (incf ticks) (assert (< ticks 80))
                            (case phase
                              (0 (start-read (make-string 180000 :initial-element #\x)
                                             (lambda (text) (setf captured text)))
                                 (setf phase 1))
                              (1 (when captured
                                   (assert (= 180000 (length captured)))
                                   (setf phase 2)))
                              (2 (when (zerop (hash-table-count (shell::shell-service-osds service)))
                                   (assert (notany (lambda (x) (typep x 'shell::shell-osd)) (world-overlays world)))
                                   (ataxia.world.web.shell:disable-web-status-bar world)
                                   (assert (null (shell::shell-service-osd-timer service)))
                                   (assert (null (shell::shell-service-clipboard service)))
                                   (setf phase 3))))
                            (when (< phase 3) (ataxia.runtime:update-event-loop-timer source 50)) 0))))
             (ataxia.runtime:update-event-loop-timer timer 50))
           (ataxia.kernel:run-kernel kernel :run-for 4.5d0)
           (assert (= phase 3))
           (assert (eq :running (ataxia.kernel:kernel-world-status kernel)))
           (format t "PASS: named workspaces, volume/mute keys, OSD focus/expiry, clipboard history bounds/selection, seat isolation, large asynchronous transfer and cleanup.~%"))
      (ataxia.kernel:destroy-kernel kernel :shell-controls-complete))))
