;;;; Browser shell uses the same controllers and normal drawable/input lifecycle.
(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-web/status-bar")
(in-package #:ataxia.infinite-world)
(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (stem (format nil "ataxia-web-shell-~D" (random 1000000000)))
       (desktop (merge-pathnames (concatenate 'string stem ".desktop") (uiop:temporary-directory)))
       (marker (merge-pathnames (concatenate 'string stem ".launched") (uiop:temporary-directory)))
       (bar nil) (seat nil) (phase 0) (ticks 0) (done nil) (baseline nil) (cpu 0))
  (labels ((popup () (ataxia.world.shell::%bar-popup bar))
           (component (widget) (overlay-component widget))
           (ready (widget)
             (and widget
                  (progn (assert (null (ataxia.world.web:web-component-error (component widget)))) t)
                  (plusp (length (ataxia.kernel:drawable-surfaces (component widget))))
                  (find "shell-ready" (ataxia.world:agent-widget-events widget) :test #'equal :key #'ataxia.world:agent-widget-event-name)))
           (click (widget x y)
             (ataxia.kernel:interactable-pointer-motion (component widget) world seat x y nil)
             (dolist (state '(:pressed :released))
               (ataxia.kernel:interactable-pointer-button (component widget) world seat x y
                 (ataxia.kernel:make-cursor-button-input :code 272 :state state))))
           (key (name)
             (dolist (state '(:pressed :released))
               (ataxia.kernel:world-key-event world seat
                 (ataxia.kernel:make-key-input :keycode 0 :keysyms (vector name) :state state))))
           (stats () (ataxia.world.web:web-component-stats (component bar)))
           (step-test (source)
             (incf ticks) (assert (< ticks 180))
             (let ((delay 100))
               (case phase
                 (0 (when (ready bar)
                      (unless (equal (uiop:getenv "ATAXIA_WEB_TRANSPORT") "bitmap")
                        (assert (eq :dma-buf (getf (stats) :transport)))
                        (assert (zerop (getf (stats) :uploaded-bytes))))
                      (assert (typep (component bar) 'ataxia.kernel:drawable))
                      (assert (typep (component bar) 'ataxia.kernel:interactable))
                      (click bar 12d0 9d0) (incf phase)))
                 (1 (when (ready (popup))
                      (assert (eq :apps (ataxia.world.shell::%shell-popup-kind (popup))))
                      (loop for ch across "Ataxia" do (key (string ch))) (incf phase)))
                 (2 (when (equal "Ataxia" (ataxia.world.shell::shell-model-value (component (popup)) "query"))
                      (assert (ataxia.world.shell::%shell-popup-matches (popup)))
                      (key "Return") (incf phase)))
                 (3 (when (probe-file marker)
                      (assert (null (popup)))
                      (ataxia.world.shell::%bar-action world bar :power) (incf phase)))
                 (4 (when (ready (popup))
                      (assert (gethash "health" (ataxia.world.shell:shell-cache (popup))))
                      (assert (ataxia.world.shell::shell-service-power (ataxia.world:world-service world :shell)))
                      (click (popup) 314d0 8d0) (incf phase)))
                 (5 (when (null (popup))
                      (ataxia.world.shell::%bar-action world bar :media) (incf phase)))
                 (6 (when (ready (popup))
                      (assert (gethash "volume-value" (ataxia.world.shell:shell-cache (popup))))
                      (key "Escape") (ataxia.world.shell::%bar-action world bar :clipboard) (incf phase)))
                 (7 (when (ready (popup))
                      (assert (gethash "count" (ataxia.world.shell:shell-cache (popup))))
                      (key "Escape") (ataxia.world.shell::%bar-action world bar :spaces) (incf phase)))
                 (8 (when (ready (popup))
                      (assert (eq :spaces (ataxia.world.shell::%shell-popup-kind (popup))))
                      (key "Escape") (incf phase) (setf delay 1000)))
                 (9
                  ;; Freeze only the fixture's wall clock deadline; the production
                  ;; bar uses its existing single minute-aligned timer.
                  (ataxia.runtime:update-event-loop-timer
                   (ataxia.world.shell::shell-service-timer (ataxia.world:world-service world :shell)) 0)
                  (ataxia.world.web:evaluate-web-javascript (component bar) "document.activeElement.blur()")
                  (incf phase) (setf delay 600))
                 (10 (setf baseline (stats) cpu (get-internal-run-time)) (incf phase) (setf delay 3000))
                 (11
                  (assert (= (getf baseline :paints) (getf (stats) :paints)))
                  (assert (= (getf baseline :gpu-imports) (getf (stats) :gpu-imports)))
                  (format t "WEB-SHELL-IDLE: paints=0 imports=0 compositor-cpu-ms=~,3F / 3 seconds~%"
                          (* 1000d0 (/ (- (get-internal-run-time) cpu) internal-time-units-per-second)))
                  (ataxia.world.web.shell:disable-web-status-bar world)
                  (assert (null (ataxia.world.shell:status-bars world)))
                  (incf phase))
                 (12 (when (ataxia.world.web::%destroyed (component bar)) (setf done t delay 0))))
               (ataxia.runtime:update-event-loop-timer source delay)) 0))
    (unwind-protect
         (progn
           (with-open-file (out desktop :direction :output :if-exists :supersede)
             (format out "[Desktop Entry]~%Type=Application~%Name=Ataxia Browser Shell Test~%Exec=/usr/bin/touch ~A~%" marker))
           (ataxia.kernel:start-kernel kernel)
           (setf (%launcher-desktop-entries (%launcher-for-output world (%canvas-output-output (%first-output-state world))))
                 (list (%read-desktop-entry desktop)))
           (ataxia.world.web.shell:enable-web-status-bar world :system-controls-p nil
              :power-backend (lambda (operation &rest arguments) (declare (ignore arguments))
                               (case operation (:backlight nil) (:can-suspend :no))))
           (setf bar (first (ataxia.world.shell:status-bars world))
                 seat (ataxia.world:world-seat-on-output world (overlay-output bar)))
           (let ((timer (ataxia.runtime:add-event-loop-timer (ataxia.kernel:kernel-runtime kernel) #'step-test)))
             (ataxia.runtime:update-event-loop-timer timer 100))
           (ataxia.kernel:run-kernel kernel :run-for 22d0)
           (assert done) (assert (eq :running (ataxia.kernel:kernel-world-status kernel)))
           (format t "PASS: browser status bar, native clicks/typing, application launch, power/media/clipboard/navigation menus, idle and cleanup.~%"))
      (ataxia.kernel:destroy-kernel kernel :web-shell-test)
      (when (probe-file desktop) (delete-file desktop)) (when (probe-file marker) (delete-file marker)))))
