;;;; Exercise real DOM editing across the portable document bridge, then idle.
(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-assistant/metaworld")
(asdf:load-system "ataxia-web/status-bar")
(in-package #:ataxia.infinite-world)
(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1100 :headless-height 800))
       (panel nil) (seat nil) (phase 0) (ticks 0) (done nil)
       (reply nil) (baseline nil) (cpu nil)
       (large (format nil "~{~A~}" (make-list 3000 :initial-element "λ🙂<>& text "))))
  (labels ((component () (overlay-component panel))
           (js (text) (ataxia.world.web:evaluate-web-javascript (component) text))
           (model (name) (ataxia.world.web.ui:ui-model-value (component) name))
           (key (name &optional modifiers)
             (dolist (state '(:pressed :released))
               (ataxia.kernel:world-key-event world seat
                 (ataxia.kernel:make-key-input :keysyms (vector name) :modifiers modifiers :state state))))
           (probe (expression)
             (setf reply nil) (js (format nil "ataxiaUiSend('fixture',String(~A))" expression)))
           (stats () (ataxia.world.web:web-component-stats (component)))
           (step-test (source)
             (incf ticks) (assert (< ticks 180) () "HTML UI timed out at phase ~D; model ~S; reply ~S" phase (model "message") reply)
             (assert (null (ataxia.world.web:web-component-error (component))))
             (let ((delay 100))
               (case phase
                 (0 (when (plusp (length (ataxia.kernel:drawable-surfaces (component))))
                      (js "document.getElementById('message').focus()")
                      (incf phase) (setf delay 300)))
                 (1 (key "U03BB") (incf phase))
                 (2 (when (equal "λ" (model "message"))
                      (ataxia.world:set-clipboard-text world seat large)
                      (key "v" '(:control)) (incf phase)))
                 (3 (when (equal (concatenate 'string "λ" large) (model "message"))
                      ;; Select/copy through native key events; then paste into
                      ;; another field to verify the host clipboard round trip.
                      (key "a" '(:control)) (key "c" '(:control))
                      (incf phase) (setf delay 300)))
                 (4 (js "document.getElementById('project').focus();document.getElementById('project').select()")
                    (incf phase))
                 (5 (key "v" '(:control)) (incf phase))
                 (6 (when (equal (concatenate 'string "λ" large) (model "project"))
                      (ataxia.world.web.ui:set-ui-model (component) "transcript" (format nil "<pre>~A</pre>" (ataxia.assistant::%assistant-escape-html large)))
                      (incf phase) (setf delay 300)))
                 (7 (probe "document.getElementById('transcript').textContent") (incf phase))
                 (8 (when reply
                      (assert (equal reply large))
                      ;; Native browser select popup and model bindings.
                      (ataxia.world.web.ui:set-ui-model (component) "model_options"
                        "<select id='model-select' data-value='selected_model'><option value='a'>A</option><option value='b'>B</option></select>")
                      (ataxia.world.web.ui:set-ui-style (component) "model-settings" "display" "block")
                      (incf phase) (setf delay 300)))
                 (9 (js "document.getElementById('model-select').focus()") (incf phase))
                 (10 (key "Down") (key "Return") (incf phase))
                 (11 (when (equal "b" (model "selected_model"))
                       (js "document.activeElement.blur()")
                       (incf phase) (setf delay 600)))
                 (12 (setf baseline (stats) cpu (get-internal-run-time)) (incf phase) (setf delay 3000))
                 (13 (assert (= (getf baseline :paints) (getf (stats) :paints)))
                     (assert (= (getf baseline :gpu-imports) (getf (stats) :gpu-imports)))
                     (assert (zerop (getf (stats) :uploaded-bytes)))
                     (assert (zerop (getf (stats) :dropped-events)))
                     (format t "HTML-UI-IDLE: paints=0 imports=0 compositor-cpu-ms=~,3F / 3 seconds~%"
                       (* 1000d0 (/ (- (get-internal-run-time) cpu) internal-time-units-per-second)))
                     (setf done t delay 0)))
               (ataxia.runtime:update-event-loop-timer source delay)) 0))
    (unwind-protect
         (progn
           (ataxia.kernel:start-kernel kernel)
           (ataxia.world.web.shell:enable-web-status-bar world :system-controls-p nil)
           (setf (ataxia.world.shell::shell-service-clipboard (ataxia.world:world-service world :shell)) (make-hash-table :test #'eq))
           (ataxia.runtime:update-event-loop-timer (ataxia.world.shell::shell-service-timer (ataxia.world:world-service world :shell)) 0)
           (setf panel (ataxia.world.web.ui:make-ui-widget 'ataxia.world.web.ui:document-widget world
                         (asdf:system-relative-pathname "ataxia-assistant" "src/world/assistant/panel.html")
                         :width 480d0 :height 760d0)
                 seat (first (ataxia.world:world-seats world)))
           (ataxia.world:focus-world-target world seat panel)
           (ataxia.world:ui-set-callback (component) "fixture" (lambda (component value) (declare (ignore component)) (setf reply value)))
           (let ((timer (ataxia.runtime:add-event-loop-timer (ataxia.kernel:kernel-runtime kernel) #'step-test)))
             (ataxia.runtime:update-event-loop-timer timer 100))
           (ataxia.kernel:run-kernel kernel :run-for 24d0)
           (assert done)
           (format t "PASS: native Unicode editing, large clipboard copy/paste, large escaped transcript, native select, finite animation and DMA-BUF idle.~%"))
      (ataxia.kernel:destroy-kernel kernel :html-ui-test))))
