;;;; Actual Chromium UI, native input, local persistence, lifecycle and idle checks.
(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-web/notes")
(in-package #:ataxia.infinite-world)

(defun run-notebook-fixture (path reload-p)
  (let* ((world (make-metaworld :state-file nil))
         (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1200 :headless-height 900))
         (widget nil) (service nil) (seat nil) (phase 0) (ticks 0) (reply nil) (done nil)
         (baseline nil) (cpu nil) (first-id nil))
    (labels ((component () (overlay-component widget))
             (js (source) (ataxia.world.web:evaluate-web-javascript (component) source))
             (probe (expression) (setf reply nil) (js (format nil "ataxiaUiSend('fixture',String(~A))" expression)))
             (key (name &optional modifiers)
               (dolist (state '(:pressed :released))
                 (ataxia.kernel:world-key-event world seat
                   (ataxia.kernel:make-key-input :keysyms (vector name) :modifiers modifiers :state state))))
             (click (x y)
               (ataxia.kernel:interactable-pointer-motion (component) world seat x y (ataxia.kernel:make-cursor-motion-input))
               (dolist (state '(:pressed :released))
                 (ataxia.kernel:interactable-pointer-button (component) world seat x y
                   (ataxia.kernel:make-cursor-button-input :code 272 :state state))))
             (stats () (ataxia.world.web:web-component-stats (component)))
             (step-test (source)
               (incf ticks) (assert (< ticks 200) () "Commonplace timeout phase ~D reply ~S error ~S" phase reply (ataxia.world.web.notes::notebook-service-error service))
               (assert (null (ataxia.world.web:web-component-error (component))))
               (let ((delay 100))
                 (case phase
                   (0 (when (ataxia.world.web.notes::notebook-service-document-sent service)
                        (probe "document.querySelectorAll('.card').length") (incf phase)))
                   (1 (when (equal reply "6")
                        (if reload-p
                            (progn (probe "Array.from(document.querySelectorAll('.card-title')).some(n=>n.textContent==='λ')") (setf phase 15))
                            (progn (js "document.querySelector('.card-title').click()") (incf phase)))))
                   (2 (probe "document.querySelector('.task-toggle').getAttribute('aria-checked')") (incf phase))
                   (3 (when reply (assert (equal reply "false"))
                        ;; Native pointer coordinates are obtained from this document's layout.
                        (probe "(()=>{const r=document.querySelector('.task-toggle').getBoundingClientRect();return Math.round(r.x+r.width/2)+','+Math.round(r.y+r.height/2)})()")
                        (incf phase)))
                   (4 (when reply
                        (let ((split (position #\, reply)))
                          (click (coerce (parse-integer reply :end split) 'double-float)
                                 (coerce (parse-integer reply :start (1+ split)) 'double-float)))
                        (incf phase)))
                   (5 (probe "document.getElementById('body').value.includes('- [x] Open a card')") (incf phase))
                   (6 (when reply (assert (equal reply "true"))
                        (js "document.querySelector('.wiki-link').click()") (incf phase)))
                   (7 (probe "document.getElementById('title').value") (incf phase))
                   (8 (when reply (assert (equal reply "Loose threads"))
                        (js "document.getElementById('title').focus();document.getElementById('title').select()") (incf phase)))
                   (9 (key "U03BB") (incf phase) (setf delay 600))
                   (10 (probe "document.getElementById('title').value+'|'+document.getElementById('save-state').textContent") (incf phase))
                   (11 (when (equal reply "λ|Saved locally")
                         (js "document.getElementById('back').click()") (incf phase)))
                   (12 (probe "document.querySelector('.card').dataset.id") (incf phase))
                   (13 (when reply
                         (setf first-id reply)
                         (js "document.querySelector('.card-move').focus()") (key "Right") (incf phase) (setf delay 600)))
                   (14 (probe "document.querySelector('.card').dataset.id") (incf phase))
                   (15 (when reply
                         (if reload-p (assert (equal reply "true")) (assert (not (equal reply first-id))))
                         (ataxia.world.web.notes:close-notebook world) (incf phase)))
                   (16 (unless (overlay-visible-p widget)
                         (assert (eq widget (ataxia.world.web.notes:open-notebook world :path path)))
                         (js "document.activeElement.blur()") (incf phase) (setf delay 600)))
                   (17 (setf baseline (stats) cpu (get-internal-run-time)) (incf phase) (setf delay 2000))
                   (18 (assert (= (getf baseline :paints) (getf (stats) :paints)))
                       (assert (= (getf baseline :gpu-imports) (getf (stats) :gpu-imports)))
                       (assert (zerop (getf (stats) :uploaded-bytes)))
                       (assert (eq :dma-buf (getf (stats) :transport)))
                       (assert (zerop (getf (stats) :dropped-events)))
                       (format t "NOTES-IDLE: reload=~S paints=0 uploads=0 cpu-ms=~,3F / 2 seconds~%" reload-p
                         (* 1000d0 (/ (- (get-internal-run-time) cpu) internal-time-units-per-second)))
                       (setf done t delay 0)))
                 (ataxia.runtime:update-event-loop-timer source delay)) 0))
      (unwind-protect
           (progn
             (ataxia.kernel:start-kernel kernel)
             (setf widget (ataxia.world.web.notes:open-notebook world :path path)
                   service (ataxia.world:world-service world :commonplace)
                   seat (first (world-seats world)))
             (ataxia.world:ui-set-callback (component) "fixture" (lambda (component value) (declare (ignore component)) (setf reply value)))
             (let ((timer (ataxia.runtime:add-event-loop-timer (ataxia.kernel:kernel-runtime kernel) #'step-test)))
               (ataxia.runtime:update-event-loop-timer timer 100))
             (ataxia.kernel:run-kernel kernel :run-for (if reload-p 7d0 10d0))
             (assert done))
        (ataxia.kernel:destroy-kernel kernel :notes-test)
        ;; The fixture runs outside an owner dispatch now; ensure storage actually exits.
        (when service
          (sb-thread:join-thread (ataxia.world.web.notes::notebook-service-thread service) :timeout 3)
          (assert (null (ataxia.world.web.notes::notebook-service-fd service))))))))

(let* ((directory (merge-pathnames (format nil "ataxia-notes-test-~D/" (sb-posix:getpid)) (uiop:temporary-directory)))
       (path (merge-pathnames "notes.json" directory)))
  (unwind-protect
       (progn
         (run-notebook-fixture path nil)
         (let ((data (ataxia.world.web.notes::%read-document path)))
           (assert (search "λ" data)) (assert (search "- [x] Open a card" data)))
         (run-notebook-fixture path t)
         (format t "PASS: notebook DOM, native checklist click/Unicode edit/reorder, autosave, close/reopen, disk reload, DMA-BUF idle and worker teardown.~%"))
    (when (probe-file directory) (uiop:delete-directory-tree directory :validate t :if-does-not-exist :ignore))))
