;;;; A UI host with no canvas, layout engine, or concrete World package loaded.
(load (merge-pathnames "system-support.lisp" *load-truename*))
(asdf:load-system "ataxia-world")

(defpackage #:ataxia.test.ui-host
  (:use #:cl #:ataxia.world))
(in-package #:ataxia.test.ui-host)

(defclass test-host (ui-host ataxia.kernel:world)
  ((kernel :initform nil :accessor ataxia.kernel:world-kernel)
   (outputs :initarg :outputs :reader world-outputs)
   (overlays :initform nil :accessor world-overlays)
   (damage :initform nil :accessor recorded-damage)
   (updates :initform 0 :accessor requested-updates)))

(defmethod ataxia.kernel:world-detached ((world test-host) kernel)
  (when (eq kernel (ataxia.kernel:world-kernel world))
    (setf (ataxia.kernel:world-kernel world) nil)))

(defclass test-component (ataxia.kernel:drawable)
  ((invalidator :initform nil :accessor invalidator)
   (callbacks :initform (make-hash-table :test #'equal) :reader callbacks)
   (size :initform nil :accessor component-size)
   (destroyed :initform nil :accessor destroyed-p)))

(defmethod ui-set-invalidator ((component test-component) function)
  (setf (invalidator component) function))
(defmethod ui-set-callback ((component test-component) name function)
  (setf (gethash name (callbacks component)) function))
(defmethod ui-resize ((component test-component) width height &key scale)
  (declare (ignore scale))
  (setf (component-size component) (list width height)))
(defmethod ui-destroy ((component test-component))
  (setf (destroyed-p component) t))
(defmethod damage-overlay ((world test-host) overlay)
  (push (list (overlay-x overlay) (overlay-y overlay)
              (overlay-width overlay) (overlay-height overlay))
        (recorded-damage world)))
(defmethod request-overlay-update ((world test-host) overlay)
  (declare (ignore overlay))
  (incf (requested-updates world)))
(defmethod add-overlay ((world test-host) overlay)
  (push overlay (world-overlays world))
  overlay)
(defmethod remove-overlay ((world test-host) overlay)
  (setf (world-overlays world) (remove overlay (world-overlays world)))
  (destroy-overlay overlay))
(defmethod show-overlay ((world test-host) overlay)
  (setf (overlay-visible-p overlay) t))
(defmethod hide-overlay ((world test-host) overlay)
  (setf (overlay-visible-p overlay) nil))

(defun make-test-component (&rest options)
  (declare (ignore options))
  (make-instance 'test-component))

(assert (not (find-package :ataxia.infinite-world)))
(assert (not (find-package :ataxia.world.slint)))
(let* ((output (make-instance 'ataxia.kernel:kernel-output
                             :width 1600 :height 1000 :scale 2d0 :transform 1))
       (world (make-instance 'test-host :outputs (list output)))
       (other (make-instance 'test-host :outputs (list output)))
       (widget (create-agent-widget 'agent-widget world "test"
                                    :component-factory #'make-test-component
                                    :x 10d0 :y 20d0 :width 100d0 :height 60d0
                                    :callbacks '("clicked")))
       (component (overlay-component widget)))
  (assert (equal '(500d0 800d0) (multiple-value-list (output-logical-size output))))
  (assert (eq widget (find-agent-widget world (agent-widget-id widget))))
  (assert (null (find-agent-widget other (agent-widget-id widget))))
  (assert (handler-case (progn (remove-agent-widget other widget) nil) (error () t)))
  (configure-agent-widget world widget :x 30d0 :width 120d0)
  (assert (equal '((30d0 20d0 120d0 60d0) (10d0 20d0 100d0 60d0))
                 (recorded-damage world)))
  (assert (equal '(120d0 60d0) (component-size component)))
  (let ((count (requested-updates world)))
    (funcall (invalidator component) component)
    (assert (= (1+ count) (requested-updates world))))
  (dotimes (i 70)
    (funcall (gethash "clicked" (callbacks component)) component i))
  (let ((events (agent-widget-events widget)))
    (assert (= 64 (length events)))
    (assert (= 7 (agent-widget-event-sequence (first events))))
    (assert (= 69 (agent-widget-event-value (car (last events))))))
  (let ((batch (wait-agent-events (world-agent-event-stream world) :after 68 :timeout 0)))
    (assert (= 2 (length (getf batch :events)))))
  (remove-agent-widget world widget)
  (assert (null (world-overlays world)))
  (assert (null (invalidator component)))
  (assert (destroyed-p component))
  (ataxia.kernel:world-detached world nil)
  (let ((batch (wait-agent-events (world-agent-event-stream world) :after 70 :timeout 0)))
    (assert (eq :closed (getf batch :status)))
    (assert (eq :world-replaced (getf batch :reason)))))

(format t "PASS: UI hosting, geometry, event bounds and disposal without a concrete World or Slint.~%")
