(load (merge-pathnames "support.lisp" *load-truename*))
(in-package #:ataxia.world)

(defun damage-test-contains (region x y)
  (some (lambda (r) (and (<= (rectangle-x r) x) (< x (rectangle-right r))
                        (<= (rectangle-y r) y) (< y (rectangle-bottom r)))) region))

;; Many small, separated updates stay bounded and never lose a damaged pixel.
(let* ((input (loop for i below 3000 collect (make-rectangle (mod (* i 37) 1024) (mod (* i 61) 768) 2 3)))
       (start (get-internal-run-time))
       (result (coalesce-damage-region input :width 1024 :height 768)))
  (assert (<= (length result) 32))
  (dolist (r input)
    (loop for x from (rectangle-x r) below (min 1024 (rectangle-right r)) do
      (loop for y from (rectangle-y r) below (min 768 (rectangle-bottom r)) do
        (assert (damage-test-contains result (+ x .5d0) (+ y .5d0))))))
  (format t "DAMAGE-BUDGET: 3000 inputs -> ~D rectangles, ~,3F ms CPU~%" (length result)
          (* 1000d0 (/ (- (get-internal-run-time) start) internal-time-units-per-second))))
(assert (= 1 (length (coalesce-damage-region (list (make-rectangle 0 0 10 10) (make-rectangle 15 0 10 10))))))
(assert (= 2 (length (coalesce-damage-region (list (make-rectangle 0 0 10 10) (make-rectangle 900 600 10 10))))))
(let ((result (coalesce-damage-region
               (loop for x from 0 below 100 by 3 collect (make-rectangle x 0 1 100)) :width 100 :height 100)))
  (assert (= 1 (length result)))
  (assert (= 10000 (rectangle-area (first result)))))
(let ((result (coalesce-damage-region (list (make-rectangle -2.5d0 -1.5d0 5d0 4d0)) :width 10 :height 10)))
  (assert (equalp result (list (make-rectangle 0 0 3 3)))))

;; Exact subtraction preserves holes. Its budget fallback draws more, never less.
(let* ((region (list (make-rectangle 0 0 32 24)))
       (cuts (list (make-rectangle 3 4 8 8) (make-rectangle 7 7 18 6) (make-rectangle 20 1 2 20)))
       (result (subtract-region region cuts :rectangle-limit nil)))
  (dotimes (x 32)
    (dotimes (y 24)
      (assert (eql (not (null (damage-test-contains result (+ x .5) (+ y .5))))
                   (not (damage-test-contains cuts (+ x .5) (+ y .5)))))))
  (multiple-value-bind (fallback exact) (subtract-region region cuts :rectangle-limit 1)
    (assert (not exact)) (assert (eq region fallback))))

;; Reused targets need changes since their last commit, including current damage.
(let ((tracker (make-damage-tracker :history-limit 2)) (output :output) (a :a) (b :b))
  (labels ((begin (target) (damage-begin-frame tracker output target 1 1000 800))
           (commit (target) (damage-commit-frame tracker (nth-value 1 (begin target)))))
    (commit a) (commit b)
    (damage-add-region tracker output (list (make-rectangle 20 20 4 4)))
    (commit a)
    (damage-add-region tracker output (list (make-rectangle 900 700 4 4)))
    (multiple-value-bind (region frame) (begin b)
      (assert (damage-test-contains region 21 21))
      (assert (damage-test-contains region 901 701))
      ;; A failed commit retains damage for its retry.
      (damage-fail-frame tracker frame)
      (assert (damage-pending-p tracker output)))
    (commit b)
    (multiple-value-bind (region frame) (begin b)
      (assert (null region))
      ;; Work arriving while a frame is staged must survive its completion.
      (damage-add-region tracker output (list (make-rectangle 400 300 4 4)))
      (damage-commit-frame tracker frame)
      (assert (damage-pending-p tracker output)))
    (commit b)
    (damage-full-output tracker output)
    (let ((frame (nth-value 1 (begin b))))
      (damage-full-output tracker output)
      (damage-commit-frame tracker frame)
      (assert (damage-pending-p tracker output)))
    (commit b)
    (commit b)
    (multiple-value-bind (region frame) (begin a)
      (assert (= 800000 (rectangle-area (first region))))
      (damage-commit-frame tracker frame))))
(format t "PASS: bounded conservative damage, cost-based merging, pixel coverage, exact opaque subtraction, buffer age, failed and concurrent frame damage.~%")
