(load (merge-pathnames "support.lisp" *load-truename*))
(in-package #:ataxia.infinite-world)
(let* ((names '(%output-logical-size %update-cursor-membership %request-output-state-frame))
       (saved (mapcar #'symbol-function names)))
  (unwind-protect
       (progn
         (setf (symbol-function '%output-logical-size)
               (lambda (s) (if (eq (%canvas-output-output s) :portrait) (values 600d0 900d0) (values 1000d0 700d0))))
         (dolist (name (rest names)) (setf (symbol-function name) (lambda (&rest args) (declare (ignore args)))))
         (let* ((world (make-infinite-world)) (left (%make-canvas-output :left)) (right (%make-canvas-output :portrait))
                (seat (%make-canvas-seat :human)))
           (setf (gethash :left (%world-outputs world)) left (gethash :portrait (%world-outputs world)) right
                 (%canvas-output-camera-x left) -300d0 (%canvas-output-zoom left) .5d0)
           (%initialize-output-viewport world right)
           (assert (= 1000d0 (%canvas-output-layout-x right)))
           (assert (= 1700d0 (%canvas-output-camera-x right)))
           (setf (%canvas-output-camera-x right) 9000d0 (%canvas-output-zoom right) 2d0
                 (%canvas-seat-world seat) world (%canvas-seat-output seat) left
                 (%canvas-seat-x seat) 995d0 (%canvas-seat-y seat) 250d0)
           (%update-seat-position seat (ataxia.kernel:make-cursor-motion-input :delta-x 25d0))
           (assert (eq right (%canvas-seat-output seat)))
           (assert (= 20d0 (%canvas-seat-x seat)))
           (assert (= 250d0 (%canvas-seat-y seat)))
           (assert (= -300d0 (%canvas-output-camera-x left)))
           (assert (= 9000d0 (%canvas-output-camera-x right)))
           (set-output-position world :portrait 0d0 -900d0)
           (setf (%canvas-seat-output seat) left (%canvas-seat-x seat) 200d0 (%canvas-seat-y seat) 2d0)
           (%update-seat-position seat (ataxia.kernel:make-cursor-motion-input :delta-y -12d0))
           (assert (eq right (%canvas-seat-output seat)))
           (assert (= 890d0 (%canvas-seat-y seat)))
           (remhash :portrait (%world-outputs world))
           (setf (%canvas-seat-output seat) left (%canvas-seat-x seat) 1200d0)
           (%route-seat-output seat)
           (assert (< (%canvas-seat-x seat) 1000d0))
           (assert (= 9000d0 (%canvas-output-camera-x right)))
           (format t "PASS: independent cameras, unequal monitor sizes, horizontal/vertical crossing, and disconnected-edge clamping.~%")))
    (loop for name in names for function in saved do (setf (symbol-function name) function))))
