;;;; Services compose on an unrelated World, including teardown during dispatch.
(load (merge-pathnames "system-support.lisp" *load-truename*))
(asdf:load-system "ataxia-world")

(defpackage #:ataxia.test.services (:use #:cl #:ataxia.world))
(in-package #:ataxia.test.services)
(defclass test-world (ataxia.kernel:world)
  ((events :initform nil :accessor events)))
(defstruct test-service key consume-key)
(defun record-event (world event) (push event (events world)))

(defmethod ataxia.kernel:world-output-added ((world test-world) output)
  (declare (ignore output)) (record-event world :output))
(defmethod ataxia.kernel:world-render ((world test-world) lease)
  (declare (ignore lease)) (record-event world :render) :frame)
(defmethod ataxia.kernel:world-key-event
    ((world test-world) (seat ataxia.kernel:logical-seat) input)
  (declare (ignore seat input)) (record-event world :key))
(defmethod ataxia.kernel:world-quiescing ((world test-world) reason)
  (declare (ignore reason)) (record-event world :quiesce))
(defmethod service-output-added ((service test-service) world output)
  (declare (ignore output)) (record-event world (test-service-key service)))
(defmethod service-before-render ((service test-service) world lease)
  (declare (ignore lease)) (record-event world (list :before (test-service-key service))))
(defmethod service-after-render ((service test-service) world lease)
  (declare (ignore lease)) (record-event world (list :after (test-service-key service))))
(defmethod service-key-event ((service test-service) world seat input)
  (declare (ignore seat input))
  (record-event world (test-service-key service)) (test-service-consume-key service))
(defmethod service-quiescing ((service test-service) world reason)
  (declare (ignore reason))
  (record-event world (test-service-key service))
  (detach-world-service world (test-service-key service)))

(let* ((world (make-instance 'test-world))
       (other (make-instance 'test-world))
       (seat (make-instance 'ataxia.kernel:logical-seat))
       (first (make-test-service :key :first))
       (second (make-test-service :key :second)))
  (attach-world-service world :first first)
  (attach-world-service world :second second)
  (assert (eq first (world-service world :first)))
  (assert (null (world-service other :first)))
  (assert (handler-case (progn (attach-world-service world :first second) nil) (error () t)))
  (ataxia.kernel:world-output-added world nil)
  (assert (equal '(:output :first :second) (reverse (events world))))
  (setf (events world) nil)
  (assert (eq :frame (ataxia.kernel:world-render world nil)))
  (assert (equal '((:before :first) (:before :second) :render (:after :first) (:after :second))
                 (reverse (events world))))
  (setf (events world) nil)
  (ataxia.kernel:world-key-event world seat nil)
  (assert (equal '(:first :second :key) (reverse (events world))))
  (setf (test-service-consume-key first) t (events world) nil)
  (ataxia.kernel:world-key-event world seat nil)
  (assert (equal '(:first) (events world)))
  (setf (events world) nil)
  (ataxia.kernel:world-quiescing world :test)
  (assert (equal '(:first :second :quiesce) (reverse (events world))))
  (assert (null (world-service world :first)))
  (assert (null (world-service world :second))))

(format t "PASS: isolated, ordered service events, input handling and self-detaching cleanup.~%")

(defstruct inset-service output (left 0d0) (top 0d0) (right 0d0) (bottom 0d0))
(defmethod service-output-insets ((service inset-service) world output)
  (declare (ignore world))
  (if (eq output (inset-service-output service))
      (values (inset-service-left service) (inset-service-top service)
              (inset-service-right service) (inset-service-bottom service))
      (values 0d0 0d0 0d0 0d0)))
(let* ((world (make-instance 'test-world))
       (output (make-instance 'ataxia.kernel:kernel-output :width 1920 :height 1080 :scale 1.5d0 :transform 0))
       (other (make-instance 'ataxia.kernel:kernel-output :width 800 :height 600 :scale 1d0 :transform 0)))
  (attach-world-service world :bar (make-inset-service :output output :bottom 44d0))
  (attach-world-service world :dock (make-inset-service :output output :bottom 24d0 :left 30d0))
  (assert (equalp '(30d0 0d0 1250d0 676d0) (multiple-value-list (world-output-work-area world output))))
  (assert (equalp '(0d0 0d0 800d0 600d0) (multiple-value-list (world-output-work-area world other))))
  (setf (ataxia.kernel:output-transform output) 1)
  (assert (equalp '(30d0 0d0 690d0 1236d0) (multiple-value-list (world-output-work-area world output))))
  (detach-world-service world :bar) (detach-world-service world :dock)
  (assert (equalp '(0d0 0d0 720d0 1280d0) (multiple-value-list (world-output-work-area world output)))))
(format t "PASS: per-output work areas compose edge reservations, honor scale/rotation and release their space on detach.~%")
