(load (merge-pathnames "support.lisp" *load-truename*))
(asdf:load-system "ataxia-infinite-world/capture")
(in-package #:ataxia.infinite-world)
(let* ((world (make-metaworld :state-file nil))
       (kernel (ataxia.kernel:create-kernel world :backend :headless :headless-width 1000 :headless-height 700))
       (runtime (ataxia.kernel:kernel-runtime kernel)) (client nil) (checked nil))
  (unwind-protect
       (progn
         (ataxia.kernel:start-kernel kernel)
         (ataxia.kernel:enable-xwayland kernel)
         (setf client (uiop:launch-program (list "env" (format nil "DISPLAY=~A" (ataxia.kernel:xwayland-display-name kernel))
                                                "build/xwayland-client") :output "/tmp/ataxia-xwayland-client.log" :error-output :output))
         (let ((timer (ataxia.runtime:add-event-loop-timer runtime
                        (lambda (source)
                          (declare (ignore source))
                          (assert (= 1 (length (%world-stacking world))))
                          (assert (= 1 (count-if #'%window-visible-p (%world-stacking world))))
                          (let* ((window (find-if #'%window-visible-p (%world-stacking world))) (app (canvas-window-application window)))
                            (assert (typep app 'ataxia.kernel:xwayland-application))
                            (assert (equal "XWayland fixture" (ataxia.kernel:application-title app)))
                            (assert (ataxia.kernel:application-mapped-p app))
                            (assert (>= (length (ataxia.kernel:drawable-surfaces app)) 2))
                            (ataxia.kernel:request-object-configuration app world
                              (make-instance 'ataxia.kernel:toplevel-configuration :width 600 :height 400))
                            (setf checked t))
                          0))))
           (ataxia.runtime:update-event-loop-timer timer 1800))
         (ataxia.kernel:run-kernel kernel :run-for 2.5d0)
         (assert checked)
         (assert (search "size 600 400" (uiop:read-file-string "/tmp/ataxia-xwayland-client.log")))
         (format t "PASS: real XWayland mapping, title, popup tree and resize.~%"))
    (when (and client (uiop:process-alive-p client)) (uiop:terminate-process client))
    (ataxia.kernel:destroy-kernel kernel :test)))
