;;;; Bounded Markdown presentation. Only our own tags/classes enter RmlUi;
;;;; message HTML, URLs, and code remain escaped text, never active RML.
(in-package #:ataxia.assistant)

(defun %assistant-escape-rml (text)
  (with-output-to-string (out)
    (loop for char across text do
      (write-string (case char (#\& "&amp;") (#\< "&lt;") (#\> "&gt;")
                          (#\" "&quot;") (#\' "&#39;")
                          (#\{ "&#123;") (#\} "&#125;")
                          (t (string char))) out))))
(defun %assistant-md-inline (text &optional (depth 0))
  (when (>= depth 6) (return-from %assistant-md-inline (%assistant-escape-rml text)))
  (with-output-to-string (out)
    (loop with size = (length text) for i from 0 below size do
      (let ((char (char text i)))
        (cond
          ((and (char= char #\\) (< (1+ i) size) (find (char text (1+ i)) "\\`*_{}[]()#+-.!|>"))
           (write-string (%assistant-escape-rml (string (char text (incf i)))) out))
          ((char= char #\`)
           (let* ((end (or (position-if-not (lambda (c) (char= c #\`)) text :start i) size))
                  (marker (subseq text i end)) (close (search marker text :start2 end)))
             (if close
                 (progn (format out "<span class=\"md-code\">~A</span>"
                                (%assistant-escape-rml (substitute #\Space #\Newline (subseq text end close))))
                        (setf i (1- (+ close (length marker)))))
                 (progn (write-string marker out) (setf i (1- end))))))
          ((and (find char "*_")
                (not (and (char= char #\_) (plusp i) (< (1+ i) size)
                          (alphanumericp (char text (1- i))) (alphanumericp (char text (1+ i))))))
           (let* ((double (and (< (1+ i) size) (char= char (char text (1+ i)))))
                  (marker (make-string (if double 2 1) :initial-element char))
                  (start (+ i (length marker))) (close (search marker text :start2 start)))
             (if (and close (> close start))
                 (progn (format out "<span class=\"~A\">~A</span>" (if double "md-strong" "md-em")
                                (%assistant-md-inline (subseq text start close) (1+ depth)))
                        (setf i (1- (+ close (length marker)))))
                 (write-char char out))))
          ((char= char #\[)
           (let* ((label-end (position #\] text :start (1+ i)))
                  (url-start (and label-end (< (1+ label-end) size) (char= #\( (char text (1+ label-end))) (+ label-end 2)))
                  (url-end (and url-start (position #\) text :start url-start))))
             (if url-end
                 (progn
                   (format out "<span class=\"md-link-label\">~A</span><span class=\"md-link-target\"> (~A)</span>"
                           (%assistant-md-inline (subseq text (1+ i) label-end) (1+ depth))
                           (%assistant-escape-rml (subseq text url-start url-end)))
                   (setf i url-end))
                 (write-char char out))))
          (t (write-string (%assistant-escape-rml (string char)) out)))))))
(defun %assistant-md-list-item (line)
  (let* ((trimmed (string-left-trim '(#\Space #\Tab) line))
         (indent (- (length line) (length trimmed)))
         (digits (position-if-not #'digit-char-p trimmed)))
    (cond
      ((and (> (length trimmed) 1) (find (char trimmed 0) "-*+") (char= (char trimmed 1) #\Space))
       (values (subseq trimmed 2) "•" indent))
      ((and digits (<= 1 digits 9) (< (1+ digits) (length trimmed))
            (find (char trimmed digits) ".)") (char= (char trimmed (1+ digits)) #\Space))
       (values (subseq trimmed (+ digits 2)) (concatenate 'string (subseq trimmed 0 digits) ".") indent)))))
(defun %assistant-md-cells (line)
  (let ((cells (mapcar (lambda (cell) (string-trim '(#\Space #\Tab) cell)) (uiop:split-string line :separator '(#\|)))))
    (when (and cells (equal (first cells) "")) (pop cells))
    (when (and cells (equal (car (last cells)) "")) (setf cells (butlast cells)))
    cells))
(defun %assistant-md-table-rule-p (line)
  (let ((cells (%assistant-md-cells line)))
    (and (find #\| line) cells (<= (length cells) 8)
         (every (lambda (cell) (and (>= (count #\- cell) 3) (every (lambda (c) (find c "-: ")) cell))) cells))))
(defun %assistant-markdown-rml (text)
  (let* ((lines (coerce (uiop:split-string (%assistant-text text) :separator '(#\Newline)) 'vector))
         (count (min 1024 (length lines))) (paragraph nil) (code nil) (fence nil) (language ""))
    (with-output-to-string (out)
      (labels ((flush-paragraph ()
                 (when paragraph
                   (write-string "<div class=\"md-paragraph\">" out)
                   (loop for line in (nreverse paragraph) for first = t then nil do
                     (unless first (write-char #\Space out))
                     (write-string (%assistant-md-inline (string-trim '(#\Space #\Tab #\Return) line)) out)
                     (when (uiop:string-suffix-p line "  ") (write-string "<br/>" out)))
                   (write-string "</div>" out) (setf paragraph nil)))
               (flush-code ()
                 (write-string "<div class=\"md-code-block\">" out)
                 (unless (equal language "") (format out "<div class=\"md-code-label\">~A</div>" (%assistant-escape-rml (%assistant-text language 40))))
                 (format out "<div class=\"md-pre\">~A</div></div>"
                         (%assistant-escape-rml (format nil "~{~A~^~%~}" (nreverse code))))
                 (setf code nil fence nil language ""))
               (table-row (cells heading)
                 (format out "<div class=\"md-table-row~A\">" (if heading " md-table-heading" ""))
                 (loop for cell in cells repeat 8 do (format out "<div class=\"md-table-cell\">~A</div>" (%assistant-md-inline cell)))
                 (write-string "</div>" out)))
        (loop for i from 0 below count for line = (aref lines i)
              for trimmed = (string-trim '(#\Space #\Tab #\Return) line) do
          (multiple-value-bind (list-body marker indent) (%assistant-md-list-item line)
            (let ((hashes (position-if-not (lambda (c) (char= c #\#)) trimmed)))
              (cond
                (fence (if (uiop:string-prefix-p fence trimmed) (flush-code) (push line code)))
                ((or (uiop:string-prefix-p "```" trimmed) (uiop:string-prefix-p "~~~" trimmed))
                 (flush-paragraph)
                 (let ((end (or (position-if-not (lambda (c) (char= c (char trimmed 0))) trimmed) (length trimmed))))
                   (setf fence (subseq trimmed 0 end) language (string-trim '(#\Space) (subseq trimmed end)))))
                ((equal trimmed "") (flush-paragraph))
                ((and (< (1+ i) count) (find #\| line) (%assistant-md-table-rule-p (aref lines (1+ i))))
                 (flush-paragraph) (write-string "<div class=\"md-table\">" out)
                 (table-row (%assistant-md-cells line) t) (incf i)
                 (loop while (and (< (1+ i) count) (find #\| (aref lines (1+ i)))) do
                   (table-row (%assistant-md-cells (aref lines (incf i))) nil))
                 (write-string "</div>" out))
                ((and hashes (<= 1 hashes 6) (< hashes (length trimmed)) (char= #\Space (char trimmed hashes)))
                 (flush-paragraph)
                 (format out "<div class=\"md-heading md-h~D\">~A</div>" (min hashes 3)
                         (%assistant-md-inline (string-right-trim '(#\Space #\#) (subseq trimmed (1+ hashes))))))
                ((and (>= (count #\- trimmed) 3) (every (lambda (c) (find c "- ")) trimmed))
                 (flush-paragraph) (write-string "<div class=\"md-rule\"/>" out))
                (list-body
                 (flush-paragraph)
                 (when (and (>= (length list-body) 4) (member (subseq list-body 0 4) '("[ ] " "[x] " "[X] ") :test #'equal))
                   (setf marker (if (char= (char list-body 1) #\Space) "☐" "☑") list-body (subseq list-body 4)))
                 (format out "<div class=\"md-list-row\" style=\"margin-left:~Ddp\"><span class=\"md-marker\">~A</span><div class=\"md-list-body\">~A</div></div>"
                         (min 36 (* 6 indent)) marker (%assistant-md-inline list-body)))
                ((uiop:string-prefix-p ">" trimmed)
                 (flush-paragraph)
                 (format out "<div class=\"md-quote\">~A</div>" (%assistant-md-inline (string-left-trim '(#\Space) (subseq trimmed 1)))))
                (t (push line paragraph))))))
        (flush-paragraph)
        (when fence (flush-code))
        (when (< count (length lines)) (write-string "<div class=\"md-muted\">Long response truncated.</div>" out))))))

(defun %assistant-visible-messages (controller)
  (let ((remaining 65536) (messages nil))
    (dolist (message (reverse (last (assistant-controller-messages controller) 20)))
      (let ((text (%assistant-text (getf message :text) remaining)))
        (unless (plusp remaining) (return))
        (push (list :role (getf message :role) :text text) messages)
        (decf remaining (length text))))
    messages))
(defun %assistant-transcript-rml (messages)
  (if (null messages) ""
      (with-output-to-string (out)
        (dolist (message messages)
          (let ((human (eq :you (getf message :role))))
            (format out "<div class=\"chat-message ~A\"><div class=\"chat-role\">~A</div><div class=\"chat-content\">~A</div></div>"
                    (if human "chat-user" "chat-assistant") (if human "You" "Assistant")
                    (if human (format nil "<div class=\"chat-user-text\">~A</div>" (%assistant-escape-rml (getf message :text)))
                        (%assistant-markdown-rml (getf message :text)))))))))
