;;;; Authorization and revision-checked transactions over the optional World layout service.
(in-package #:ataxia.assistant)

(defun %assistant-layout-revision (controller)
  ;; Target geometry makes a transaction stable while its presentation animates.
  (let* ((state (ataxia.world:world-desktop-state (assistant-controller-world controller)))
         (semantic (copy-tree state)))
    ;; Client titles and transient presentation do not invalidate placement.
    (setf (getf semantic :windows)
          (map 'vector (lambda (window)
                         (let ((copy (copy-list window)))
                           (dolist (field '(:title :visible :available :on-outputs)) (remf copy field))
                           copy))
               (getf state :windows)))
    (let ((fingerprint (ataxia.computer-use.wire:encode semantic)))
    (unless (equal fingerprint (assistant-controller-fingerprint controller))
      (incf (assistant-controller-revision controller))
      (setf (assistant-controller-fingerprint controller) fingerprint))
    (values (assistant-controller-revision controller) state))))
(defun %assistant-layout-snapshot (controller)
  (multiple-value-bind (revision state) (%assistant-layout-revision controller)
    (list* :ok t :revision revision :scope "Desktop windows and layout" state)))
(defun %assistant-layout-idle (controller)
  (when (ataxia.world:world-active-operation-p (assistant-controller-world controller))
    (error "A human is moving the desktop. Observe again after the drag ends.")))
(defun %assistant-layout-permit (controller)
  (unless (and (getf (assistant-controller-grant controller) :layout)
               (not (assistant-controller-blocked controller)))
    (error "Start a task with Desktop scope to change the layout."))
  (ataxia.world:require-world-capabilities (assistant-controller-world controller) :layout)
  (%assistant-layout-idle controller))
(defun %assistant-layout-preview (controller arguments)
  (%assistant-layout-permit controller)
  (unless (eql (gethash "revision" arguments) (%assistant-layout-revision controller))
    (error "The desktop changed. Take another snapshot before proposing a plan."))
  (let* ((operations (ataxia.world:validate-world-layout
                      (assistant-controller-world controller) (gethash "operations" arguments)
                      (getf (assistant-controller-grant controller) :windows)))
         (id (cu:random-token)))
    (when (>= (hash-table-count (assistant-controller-plans controller)) 8)
      (clrhash (assistant-controller-plans controller)))
    (setf (gethash id (assistant-controller-plans controller))
          (list :revision (assistant-controller-revision controller) :operations operations :expires (+ (monotonic-time) 120d0)))
    (list :ok t :plan id :revision (assistant-controller-revision controller)
          :summary "Validated arrangement; no changes applied" :operations operations)))

(defun %assistant-layout-apply (controller arguments)
  (%assistant-layout-permit controller)
  (let* ((id (gethash "plan" arguments)) (plan (gethash id (assistant-controller-plans controller)))
         (world (assistant-controller-world controller)))
    (when (getf plan :result) (return-from %assistant-layout-apply (getf plan :result)))
    (unless (and plan (< (monotonic-time) (getf plan :expires))) (error "This layout plan expired or was already applied."))
    (unless (= (getf plan :revision) (%assistant-layout-revision controller)) (error "The desktop changed since this preview."))
    (ataxia.world:validate-world-layout world (getf plan :operations)
                                        (getf (assistant-controller-grant controller) :windows))
    (let ((saved (ataxia.world:capture-world-layout world)))
      (remhash id (assistant-controller-plans controller))
      (handler-case
          (progn
            (ataxia.world:apply-world-layout world (getf plan :operations)
                                             (getf (assistant-controller-grant controller) :windows))
            (let ((token (cu:random-token)))
              (setf (assistant-controller-undo controller) (list :token token :revision (%assistant-layout-revision controller) :saved saved))
              (%assistant-refresh controller)
              (let ((result (list :ok t :undo token :snapshot (%assistant-layout-snapshot controller))))
                (setf (getf plan :result) result (gethash id (assistant-controller-plans controller)) plan)
                result)))
        (error (cause) (ataxia.world:restore-world-layout world saved) (error cause))))))
(defun %assistant-layout-undo (controller token &optional human)
  (unless human (%assistant-layout-permit controller))
  (%assistant-layout-idle controller)
  (let ((undo (assistant-controller-undo controller)))
    (unless (and undo (equal token (getf undo :token))) (error "No matching layout Undo is available."))
    (unless (= (getf undo :revision) (%assistant-layout-revision controller))
      (error "The desktop changed after this arrangement. Undo would overwrite those changes."))
    (ataxia.world:restore-world-layout (assistant-controller-world controller) (getf undo :saved))
    (setf (assistant-controller-undo controller) nil)
    (%assistant-refresh controller)
    (%assistant-layout-snapshot controller)))
