;;;; Shared CUA desktop state and direct World operations, on the owner thread.
(in-package #:ataxia.assistant)

(defun %assistant-layout-snapshot (controller)
  (%assistant-require-task controller)
  (list* :ok t (cu::%computer-desktop-snapshot (assistant-controller-session controller))))
(defun %assistant-layout-revision (controller)
  (getf (%assistant-layout-snapshot controller) :revision))
(defun %assistant-desktop-action (controller op arguments)
  (%assistant-require-task controller)
  (let* ((session (assistant-controller-session controller))
         (request (cu:decode-request arguments)))
    (setf (getf request :op) op
          (getf request :token) (cu:computer-session-token session)
          (getf request :sequence) (1+ (cu:computer-session-sequence session)))
    (when (equal op "window")
      (setf (getf request :revision) (%assistant-layout-revision controller)))
    (let ((result (cu:request-on-owner (assistant-controller-world controller) request)))
      (%assistant-refresh controller)
      result)))
