;;;; Task sessions, conversation resets and user questions.
;;;; World attachment and resource teardown live in service.lisp.
(in-package #:ataxia.assistant)

(defun %assistant-refresh-tools (controller)
  "Reload tool schemas at an idle boundary while retaining the public conversation."
  (when (or (assistant-controller-turn-id controller) (assistant-controller-starting-turn controller)
            (assistant-controller-voice-active controller) (assistant-controller-request controller))
    (error "Wait for the active assistant turn to finish before updating its tools."))
  (let ((context (with-output-to-string (out)
                   (dolist (message (last (assistant-controller-messages controller) 8))
                     (format out "~A: ~A~%~%" (if (eq :you (getf message :role)) "User" "Assistant")
                             (%assistant-text (getf message :text) 2048))))))
    (%assistant-reset-conversation controller)
    (when (plusp (length context)) (setf (assistant-controller-refresh-context controller) context)))
  (setf (assistant-controller-activity controller) "Tools updated. Ready for your next request.")
  (%assistant-refresh controller t))

(defun %assistant-reset-conversation (controller)
  (setf (assistant-controller-refresh-context controller) nil)
  (%assistant-audio-stop-now controller)
  (incf (assistant-controller-epoch controller))
  (sb-thread:signal-semaphore (assistant-controller-wake controller))
  (when (assistant-controller-process controller)
    (ignore-errors (uiop:terminate-process (assistant-controller-process controller))))
  (when (assistant-controller-session controller) (cu:close-session (assistant-controller-session controller) "Assistant conversation reset"))
  (setf (assistant-controller-worker controller) nil (assistant-controller-reader controller) nil
        (assistant-controller-process controller) nil (assistant-controller-thread-id controller) nil
        (assistant-controller-turn-id controller) nil (assistant-controller-starting-turn controller) nil
        (assistant-controller-connection controller) :offline (assistant-controller-task controller) :idle
        (assistant-controller-session controller) nil
        (assistant-controller-blocked controller) t (assistant-controller-voice-active controller) nil
        (assistant-controller-request controller) nil (assistant-controller-deferred controller) nil
        (assistant-controller-voice-stopping-p controller) nil (assistant-controller-login-url controller) nil)
  (clrhash (assistant-controller-pending controller))
  (clrhash (assistant-controller-seen-calls controller)))
(defun %assistant-ensure-session (controller)
  "Create native input resources only when a tool first needs them. Owner only."
  (%assistant-require-task controller)
  (let* ((world (assistant-controller-world controller))
         (seat (assistant-controller-seat controller))
         (session (assistant-controller-session controller)))
    (unless session
      (let* ((current (and seat (world-seat-focus world seat)))
             (focused (if (typep current 'assistant-panel)
                          (world-seat-previous-focus world seat) current))
             ;; An output may disappear between task start and first app input.
             (output (or (find (assistant-controller-output controller) (world-outputs world))
                         (and seat (world-seat-output world seat))
                         (first (world-outputs world)))))
        (setf (assistant-controller-output controller) output)
        (setf session (cu:connect-session world "Ataxia assistant" "Your assistant task"
                                         output)
              (assistant-controller-session controller) session)
        (cu:activate-session session)
        (when (window-application focused)
          (cu:change-session-view session :window
                                  (ataxia.kernel:object-id (window-application focused))))))
    ;; Tool calls may not reactivate a session paused by human takeover.
    (unless (eq :active (cu:computer-session-state session))
      (error "The native input session is paused. Wait for the user to Send or Resume."))
    session))

(defun %assistant-start-task (controller)
  (let* ((world (assistant-controller-world controller))
         (seat (assistant-controller-seat controller))
         (panel (assistant-controller-panel controller))
         (project (if panel
                      (ataxia.world.web.ui:ui-model-value (overlay-component panel) "project")
                      (assistant-controller-project controller))))
    (unless (and (stringp project) (uiop:directory-exists-p project))
      (error "Enter an existing working directory."))
    (setf project (namestring (truename (uiop:ensure-directory-pathname project))))
    (unless (equal project (assistant-controller-project controller))
      (when (or (assistant-controller-turn-id controller) (assistant-controller-starting-turn controller)
                (assistant-controller-voice-active controller))
        (error "Stop the current task before changing the working directory."))
      (%assistant-reset-conversation controller)
      (setf (assistant-controller-project controller) project))
    (when (and (assistant-controller-session controller)
               (eq :closed (cu:computer-session-state (assistant-controller-session controller))))
      (setf (assistant-controller-session controller) nil))
    (unless (assistant-controller-session controller)
      (setf (assistant-controller-output controller)
            (or (and seat (world-seat-output world seat)) (first (world-outputs world)))))
    ;; A new human request resumes an existing seat, but Lisp, file and voice
    ;; tasks need no seat, cursor, capture state or native-session deadlines.
    (when (assistant-controller-session controller)
      (cu:activate-session (assistant-controller-session controller)))
    (setf (assistant-controller-blocked controller) nil
          (assistant-controller-started controller) (monotonic-time))))
(defun %assistant-submit (controller text)
  (setf text (string-trim '(#\Space #\Tab #\Newline #\Return) (cu:bounded-string text 32768 "message")))
  (when (zerop (length text)) (error "Enter a task first."))
  (when (assistant-controller-request controller) (return-from %assistant-submit (%assistant-answer controller text)))
  (%assistant-start-task controller)
  (%assistant-add-message controller :you text)
  (setf (assistant-controller-task controller) :working (assistant-controller-activity controller) "Starting your task")
  (%assistant-connect controller)
  (let* ((context (assistant-controller-refresh-context controller))
         (input (if context
                    (format nil "Previous conversation for context only. Do not repeat completed actions:~%~A~%Current user request:~%~A" context text)
                    text)))
    (%assistant-queue controller :submit input (length input))
    (setf (assistant-controller-refresh-context controller) nil))
  (%assistant-refresh controller t))
(defun %assistant-pause (controller &optional (reason "Paused by you"))
  (setf (assistant-controller-blocked controller) t (assistant-controller-task controller) :paused
        (assistant-controller-activity controller) reason)
  (when (assistant-controller-session controller) (cu:pause-session (assistant-controller-session controller) reason))
  (%assistant-audio-stop-now controller)
  (when (assistant-controller-request controller) (%assistant-answer controller :deny))
  (ignore-errors (%assistant-queue controller :interrupt nil))
  (%assistant-refresh controller t))
(defun %assistant-stop (controller)
  (%assistant-pause controller "Stopped")
  (when (assistant-controller-session controller) (cu:close-session (assistant-controller-session controller) "Stopped by you"))
  (%assistant-refresh controller t))
(defun %assistant-toggle-talk (controller)
  (when (assistant-controller-voice-stopping-p controller) (error "Voice is closing. Try Talk again in a moment."))
  (if (or (not (eq :off (assistant-controller-microphone controller))) (assistant-controller-voice-active controller))
      (progn (%assistant-audio-stop-now controller) (%assistant-queue controller :voice-stop nil))
      (progn
        (%assistant-start-task controller)
        (%assistant-connect controller)
        (setf (assistant-controller-microphone controller) :starting)
        (%assistant-queue controller :voice nil)))
  (%assistant-refresh controller t))
(defun %assistant-answer (controller answer)
  (let* ((request (assistant-controller-request controller))
         (method (getf request :method))
         (id (getf request :id)) (result nil))
    (unless request (error "There is no question waiting for an answer."))
    (cond
      ((equal method "item/tool/requestUserInput")
       (let* ((question (%assistant-question request))
              (answers (or (getf request :answers) (setf (getf request :answers) (%assistant-object)))))
         (if (eq answer :deny)
             (setf result (%assistant-object "answers" answers))
             (progn
               (unless (and question (stringp answer) (plusp (length answer))) (error "Enter an answer or choose an option."))
               (setf (gethash (%assistant-field question "id") answers) (%assistant-object "answers" (vector (%assistant-text answer 4096))))
               (incf (getf request :index 0))
               (if (%assistant-question request)
                   (progn (%assistant-refresh controller t) (return-from %assistant-answer nil))
                   (setf result (%assistant-object "answers" answers)))))))
      (t (error "Unsupported question type.")))
    (%assistant-queue controller :response (list id result))
    (setf (assistant-controller-request controller) nil)
    (unless (assistant-controller-blocked controller)
      (setf (assistant-controller-task controller) :working (assistant-controller-activity controller) "Continuing"))
    (%assistant-refresh controller t)))
