(in-package #:ataxia.assistant)

(defun %assistant-picker-models (controller)
  (remove-if-not
   (lambda (entry)
     (let ((model (%assistant-field entry "model")))
       (and (stringp model) (plusp (length model)) (<= (length model) 256)
            (not (eq t (%assistant-field entry "hidden"))))))
   (assistant-controller-models controller)))
(defun %assistant-model-entry (controller model)
  (find model (%assistant-picker-models controller) :key (lambda (entry) (%assistant-field entry "model")) :test #'equal))
(defun %assistant-model-name (controller model)
  (or (%assistant-field (%assistant-model-entry controller model) "displayName") model "Codex default"))
(defun %assistant-selected-model (controller)
  (let ((state (assistant-controller-model-selection controller)))
    (or (assistant-model-selection-selected state) (assistant-model-selection-default state))))
(defun %assistant-supported-efforts (controller)
  (loop for entry across (or (%assistant-field (%assistant-model-entry controller (%assistant-selected-model controller))
                                              "supportedReasoningEfforts") #())
        for effort = (%assistant-field entry "reasoningEffort")
        when (and (stringp effort) (<= (length effort) 32)) collect effort))
(defun %assistant-effort-name (effort)
  (cond ((null effort) "Default") ((equal effort "xhigh") "Extra high")
        (t (string-capitalize effort))))
(defun %assistant-fast-tier (controller)
  (let* ((entry (%assistant-model-entry controller (%assistant-selected-model controller)))
         (tier (find-if (lambda (tier)
                          (or (member (%assistant-field tier "id") '("priority" "fast") :test #'equal)
                              (equalp "Fast" (%assistant-field tier "name"))))
                        (or (%assistant-field entry "serviceTiers") #()))))
    (or (%assistant-field tier "id")
        (and (find "fast" (or (%assistant-field entry "additionalSpeedTiers") #()) :test #'equal) "fast"))))
(defun %assistant-effective-tier (controller)
  (let* ((settings (assistant-controller-generation-settings controller))
         (fast (assistant-generation-settings-fast settings))
         (default (assistant-generation-settings-default-tier settings))
         (tier (%assistant-fast-tier controller)))
    (cond ((eq fast :on) (or tier "default"))
          ((eq fast :off) "default")
          ((member default '("fast" "priority") :test #'equal) (or tier "default"))
          (t (or default "default")))))
(defun %assistant-select-effort (controller value)
  (let ((effort (and (stringp value) (plusp (length value)) value)))
    (when (and effort (not (member effort (%assistant-supported-efforts controller) :test #'equal)))
      (error "Choose an effort supported by this model."))
    (setf (assistant-generation-settings-effort (assistant-controller-generation-settings controller)) effort)))
(defun %assistant-toggle-fast (controller)
  (unless (%assistant-fast-tier controller) (error "Fast mode is not available for this model."))
  (setf (assistant-generation-settings-fast (assistant-controller-generation-settings controller))
        (if (equal "default" (%assistant-effective-tier controller)) :on :off)))
(defun %assistant-select-model (controller value)
  (let ((selected (and (stringp value) (plusp (length value)) value)))
    (when (and selected (not (%assistant-model-entry controller selected)))
      (error "That model is no longer available. Reload the model list."))
    (setf (assistant-model-selection-selected (assistant-controller-model-selection controller)) selected)
    (let ((settings (assistant-controller-generation-settings controller)))
      (unless (member (assistant-generation-settings-effort settings) (%assistant-supported-efforts controller) :test #'equal)
        (setf (assistant-generation-settings-effort settings) nil)))))
(defun %assistant-model-turn-settings (controller)
  "Owner-thread snapshot; steering never changes a running turn's model."
  (let* ((state (assistant-controller-model-selection controller))
         (selected (assistant-model-selection-selected state))
         (model (or selected (assistant-model-selection-default state)))
         (entry (and selected (%assistant-model-entry controller selected)))
         (settings (assistant-controller-generation-settings controller))
         (effort (assistant-generation-settings-effort settings)))
    (when (and selected (not entry)) (error "The selected model is unavailable. Choose another model."))
    (when (and effort (not (member effort (%assistant-supported-efforts controller) :test #'equal)))
      (error "The selected effort is unavailable. Choose another effort."))
    (values model
            (or effort (if selected (%assistant-field entry "defaultReasoningEffort")
                           (assistant-model-selection-default-effort state)))
            (not (equal model (assistant-model-selection-active state)))
            (%assistant-effective-tier controller))))
