(in-package #:ataxia.assistant)
(defparameter *assistant-preview-error-output* "/dev/null")

(defun %assistant-project-file (controller path)
  (unless (and (eq :project (assistant-controller-scope controller))
               (getf (assistant-controller-grant controller) :project))
    (error "Choose Project scope and a directory before opening an app preview."))
  (cu:bounded-string path 2048 "path")
  (unless (and (uiop:relative-pathname-p path)
               (notany (lambda (c) (find c '(#\Newline #\Return #\Tab))) path))
    (error "Use a project-relative RML path."))
  (let* ((root (uiop:ensure-directory-pathname (truename (assistant-controller-project controller))))
         (resolved (truename (merge-pathnames path root))))
    (unless (and (uiop:subpathp resolved root) (equalp (pathname-type resolved) "rml"))
      (error "Preview documents must be RML files inside the selected project."))
    (namestring resolved)))
(defun %assistant-preview-command (preview path)
  (let* ((process (assistant-preview-process preview)) (input (uiop:process-info-input process))
         (output (uiop:process-info-output process)))
    (unless (uiop:process-alive-p process) (error "This preview window has closed. Open a new preview."))
    (ataxia.computer-use.wire:write-line-bytes input (concatenate 'string "LOAD" (string #\Tab) path))
    (unless (sb-sys:wait-until-fd-usable (sb-sys:fd-stream-fd output) :input 15d0)
      (ignore-errors (uiop:terminate-process process))
      (error "The preview renderer timed out."))
    (let ((reply (ataxia.computer-use.wire:read-line-bytes output 4096)))
      (unless (equal reply "OK") (error "~A" (if (> (length reply) 6) (subseq reply 6) reply))))))
(defun %assistant-preview-image (controller preview)
  (let* ((result (%assistant-cu-call controller
                  (list :op "batch" :actions
                    (vector (list :op "wait-window" :app-id (assistant-preview-app-id preview) :timeout 10d0 :focus t)
                            (list :op "wait-stable" :timeout 3d0 :settle .2d0)) :capture t)))
         (window (getf (getf result :session) :window)))
    (list :ok t :preview (assistant-preview-id preview) :revision (assistant-preview-revision preview)
          :pid (uiop:process-info-pid (assistant-preview-process preview))
          :window window :image (getf result :image)
          :events "Built-in IDs: increment/decrement/reset update counter; input copies text to result; submit sets status. Form controls also have native input behavior.")))
(defun %assistant-preview (controller arguments)
  (let* ((path (%assistant-project-file controller (gethash "path" arguments)))
         (width (cu:bounded-number (gethash "width" arguments 800) 96 1920 "width"))
         (height (cu:bounded-number (gethash "height" arguments 600) 64 1200 "height"))
         (id (cu:random-token)) (app-id (concatenate 'string "ataxia.preview." id))
         (binary (asdf:system-relative-pathname "ataxia-assistant" "build/ataxia-rmlui-preview"))
         (focuses nil)
         (socket (%assistant-owner controller
                   (lambda () (%assistant-require-task controller)
                     (setf focuses (loop for seat in (world-seats (assistant-controller-world controller))
                                         unless (agent-seat-p seat)
                                         collect (cons seat (world-seat-focus (assistant-controller-world controller) seat))))
                     (maphash (lambda (key preview)
                                (unless (uiop:process-alive-p (assistant-preview-process preview))
                                  (remhash key (assistant-controller-previews controller))))
                              (assistant-controller-previews controller))
                     (when (>= (hash-table-count (assistant-controller-previews controller)) 4)
                       (error "Close an existing preview before opening another (maximum four)."))
                     (ataxia.runtime:runtime-socket-name
                      (ataxia.kernel:kernel-runtime (ataxia.kernel:world-kernel (assistant-controller-world controller)))))))
         (preview (make-assistant-preview :id id :app-id app-id :path path)) (accepted nil))
    (unless (probe-file binary) (error "Build the preview host with make assistant."))
    (unwind-protect
         (progn
           (setf (assistant-preview-process preview)
                 (uiop:launch-program
                  (list "env" "EGL_PLATFORM=wayland" (concatenate 'string "WAYLAND_DISPLAY=" socket) (namestring binary)
                        (assistant-controller-project controller) app-id (princ-to-string (round width)) (princ-to-string (round height)))
                  :directory (assistant-controller-project controller) :input :stream :output :stream
                  :error-output *assistant-preview-error-output* :if-error-output-exists :append :element-type '(unsigned-byte 8)))
           (%assistant-preview-command preview path)
           (%assistant-owner controller
             (lambda () (%assistant-require-task controller)
               (setf (gethash id (assistant-controller-previews controller)) preview)))
           (setf accepted t)
           (let ((result (%assistant-preview-image controller preview)))
             (%assistant-owner controller
               (lambda ()
                 (dolist (entry focuses)
                   (let* ((world (assistant-controller-world controller))
                          (current (world-seat-focus world (car entry))) (previous (cdr entry)))
                     (when (and (window-application current)
                                (equal app-id (ataxia.kernel:application-app-id (window-application current)))
                                (or (null previous) (member previous (world-windows world)) (member previous (world-overlays world))))
                       (focus-world-target world (car entry) previous))))))
             result))
      (unless accepted
        (when (assistant-preview-process preview) (ignore-errors (uiop:terminate-process (assistant-preview-process preview))))))))
(defun %assistant-preview-update (controller arguments)
  (let* ((path (%assistant-project-file controller (gethash "path" arguments)))
         (preview (%assistant-owner controller
                    (lambda () (%assistant-require-task controller)
                      (or (gethash (gethash "preview" arguments) (assistant-controller-previews controller))
                          (error "Unknown preview."))))))
    (%assistant-preview-command preview path)
    (incf (assistant-preview-revision preview))
    (setf (assistant-preview-path preview) path)
    (%assistant-preview-image controller preview)))
(defun %assistant-close-previews (controller)
  (maphash (lambda (id preview)
             (declare (ignore id))
             (ignore-errors (uiop:terminate-process (assistant-preview-process preview))))
           (assistant-controller-previews controller))
  (clrhash (assistant-controller-previews controller)))
