(in-package #:ataxia.assistant)

(defun %assistant-write (controller message)
  (when (and *assistant-operation-epoch* (/= *assistant-operation-epoch* (assistant-controller-epoch controller)))
    (error "The assistant connection was replaced."))
  (let ((text (ataxia.computer-use.wire:encode message)))
    (when (> (length text) +assistant-frame-limit+) (error "Assistant message exceeds 8 MiB."))
    (ataxia.computer-use.wire:write-line-bytes
     (uiop:process-info-input (or *assistant-operation-process* (assistant-controller-process controller))) text)))
(defun %assistant-rpc (controller method params callback)
  (let ((id (incf (assistant-controller-next-id controller))))
    (setf (gethash id (assistant-controller-pending controller))
          (list callback (+ (monotonic-time) 60d0) method))
    (%assistant-write controller (%assistant-object "id" id "method" method "params" params))
    id))
(defun %assistant-result (controller id result)
  (%assistant-write controller (%assistant-object "id" id "result" result)))
(defun %assistant-rpc-error (controller id message)
  (%assistant-write controller (%assistant-object "id" id "error"
                                                  (%assistant-object "code" -32602 "message" (%assistant-text message 1024)))))
(defun %assistant-check-result (result error)
  (when error (error "~A" (or (%assistant-field error "message") "Codex request failed."))) result)

(defun %assistant-developer-instructions (controller)
  (format nil "~A~%~%Current task scope: ~A.~%Selected project directory: ~A~%Ataxia source directory (reference examples): ~A~%"
          (uiop:read-file-string (asdf:system-relative-pathname "ataxia-assistant" "src/world/assistant/instructions.md"))
          (ecase (assistant-controller-scope controller)
            (:desktop "Desktop") (:application "Selected app") (:project "Project"))
          (assistant-controller-project controller)
          (namestring (asdf:system-source-directory "ataxia-assistant"))))

(defun %assistant-start-thread (controller)
  (%assistant-rpc controller "thread/start"
      (%assistant-object "ephemeral" t "cwd" (assistant-controller-project controller)
                         "sandbox" (if (eq :project (assistant-controller-scope controller)) "workspace-write" "read-only")
                         "approvalPolicy" "on-request" "dynamicTools" (%assistant-owner controller (lambda () (%assistant-tool-specs (assistant-controller-world controller))))
                         "developerInstructions"
                         (%assistant-developer-instructions controller))
    (lambda (result error)
      (%assistant-check-result result error)
      (setf (assistant-controller-thread-id controller) (%assistant-field result "thread" "id"))
      (unless (assistant-controller-thread-id controller) (error "Codex returned no thread ID."))
      (%assistant-owner controller
        (lambda ()
          (let ((state (assistant-controller-model-selection controller)))
            (setf (assistant-model-selection-default state) (%assistant-field result "model")
                  (assistant-model-selection-default-effort state) (%assistant-field result "reasoningEffort")
                  (assistant-model-selection-active state) (%assistant-field result "model")))
          (let ((settings (assistant-controller-generation-settings controller)))
            (setf (assistant-generation-settings-default-tier settings) (%assistant-field result "serviceTier")
                  (assistant-generation-settings-active-tier settings) (or (%assistant-field result "serviceTier") "default")
                  (assistant-generation-settings-active-effort settings) (%assistant-field result "reasoningEffort")))))
      (%assistant-state controller :connection :ready :activity "Connected to Codex")
      (let ((deferred (shiftf (assistant-controller-deferred controller) nil)))
        (when deferred (%assistant-send-task controller deferred)))
      (when (eq :starting (assistant-controller-microphone controller)) (%assistant-voice-start controller)))))
(defun %assistant-account (controller)
  (%assistant-rpc controller "account/read" (%assistant-object "refreshToken" :false)
    (lambda (account failure)
      (%assistant-check-result account failure)
      (if (and (eq t (%assistant-field account "requiresOpenaiAuth")) (null (%assistant-field account "account")))
          (%assistant-state controller :connection :error :task :needs-input
                            :activity "Sign in to Codex, or use Retry after signing in elsewhere. Your task is retained.")
          (%assistant-list-models controller
                                  (lambda ()
                                    (unless (assistant-controller-thread-id controller) (%assistant-start-thread controller))))))))
(defun %assistant-list-models (controller continuation &optional cursor (entries nil) (pages 0))
  (let ((params (%assistant-object "limit" 100 "includeHidden" :false)))
    (when cursor (setf (gethash "cursor" params) cursor))
    (%assistant-rpc controller "model/list" params
      (lambda (result failure)
        (%assistant-check-result result failure)
        (let* ((all (append entries (coerce (or (%assistant-field result "data") #()) 'list)))
               (next (%assistant-field result "nextCursor")))
          (if (and (stringp next) (plusp (length next)) (< pages 7))
              (%assistant-list-models controller continuation next all (1+ pages))
              (progn
                (%assistant-owner controller
                  (lambda ()
                    (setf (assistant-controller-models controller) (coerce all 'vector))
                    (%assistant-refresh controller)))
                (funcall continuation))))))))
(defun %assistant-login (controller)
  (if (assistant-controller-login-url controller)
      (uiop:launch-program (list "xdg-open" (assistant-controller-login-url controller))
                           :input "/dev/null" :output "/dev/null" :if-output-exists :append
                           :error-output "/dev/null" :if-error-output-exists :append)
      (%assistant-rpc controller "account/login/start" (%assistant-object "type" "chatgpt")
        (lambda (result failure)
          (%assistant-check-result result failure)
          (let ((url (%assistant-field result "authUrl")))
            (unless (and (stringp url) (uiop:string-prefix-p "https://" url)) (error "Codex returned no secure sign-in URL."))
            (setf (assistant-controller-login-url controller) url
                  (assistant-controller-login-id controller) (%assistant-field result "loginId"))
            (%assistant-state controller :activity "Select Open sign-in to continue in your browser."))))))
(defun %assistant-handshake (controller)
  (%assistant-rpc controller "initialize"
      (%assistant-object "clientInfo" (%assistant-object "name" "ataxia_assistant" "version" "0.1.0")
                         "capabilities" (%assistant-object "experimentalApi" t))
    (lambda (result error)
      (%assistant-check-result result error)
      (%assistant-write controller (%assistant-object "method" "initialized"))
      (%assistant-account controller))))

(defun %assistant-journal (controller event &rest fields)
  "Worker-only metadata log: no prompts, transcripts, audio, credentials or images."
  (handler-case
      (let* ((root (merge-pathnames "ataxia/assistant/" (uiop:ensure-directory-pathname (or (uiop:getenv "XDG_STATE_HOME") (merge-pathnames ".local/state/" (user-homedir-pathname))))))
             (path (or (assistant-controller-journal-path controller)
                       (setf (assistant-controller-journal-path controller) (merge-pathnames "operations.jsonl" root)))))
        (ensure-directories-exist root)
        (sb-posix:chmod (namestring root) #o700)
        (with-open-file (stream path :direction :output :if-exists :append :if-does-not-exist :create)
          (sb-posix:chmod (namestring path) #o600)
          (when (> (file-length stream) (* 1024 1024))
            (close stream)
            (with-open-file (clear path :direction :output :if-exists :supersede) (declare (ignorable clear)))
            (return-from %assistant-journal nil))
          (write-line (ataxia.computer-use.wire:encode
                       (apply #'%assistant-object "time" (get-universal-time) "event" event
                              "epoch" (assistant-controller-epoch controller) "thread" (assistant-controller-thread-id controller) fields)) stream)))
    (error () nil)))

(defun %assistant-send-task (controller text)
  (unless (assistant-controller-thread-id controller)
    (setf (assistant-controller-deferred controller) text)
    (return-from %assistant-send-task nil))
  (when (assistant-controller-starting-turn controller)
    ;; A correction arriving during turn/start is sent after its turn ID is known.
    (setf (assistant-controller-deferred controller) text)
    (return-from %assistant-send-task nil))
  (let* ((turn (assistant-controller-turn-id controller))
         (settings (unless turn
                     (%assistant-owner controller
                       (lambda () (multiple-value-list (%assistant-model-turn-settings controller))))))
         (params (%assistant-object "threadId" (assistant-controller-thread-id controller)
                                    "input" (vector (%assistant-object "type" "text" "text" text)))))
    (when (first settings) (setf (gethash "model" params) (first settings)))
    (when (stringp (second settings))
      (setf (gethash "effort" params) (second settings)))
    (when (fourth settings) (setf (gethash "serviceTierForTurn" params) (fourth settings)))
    (if turn (setf (gethash "expectedTurnId" params) turn)
        (progn
          (setf (assistant-controller-starting-turn controller) t)
          (incf (assistant-controller-turn-count controller))
          (setf (assistant-controller-tool-count controller) 0)))
    (%assistant-rpc controller (if turn "turn/steer" "turn/start") params
      (lambda (result failure)
        (setf (assistant-controller-starting-turn controller) nil)
        (cond
          ((and failure turn)
           ;; Do not replay uncertain steering as a fresh task.
           (%assistant-state controller :task :needs-input
                             :activity "The turn ended before your correction arrived. Send it again to start a new turn."))
          (failure (%assistant-check-result result failure))
          (t
           (unless turn (setf (assistant-controller-turn-id controller) (%assistant-field result "turn" "id")))
           (when (and (not turn) (first settings))
             (%assistant-owner controller
               (lambda ()
                 (setf (assistant-model-selection-active (assistant-controller-model-selection controller)) (first settings))
                 (setf (assistant-generation-settings-active-effort (assistant-controller-generation-settings controller)) (second settings)
                       (assistant-generation-settings-active-tier (assistant-controller-generation-settings controller)) (fourth settings))
                 (%assistant-refresh controller))))
           (when (assistant-controller-blocked controller) (%assistant-interrupt controller))
           (let ((deferred (shiftf (assistant-controller-deferred controller) nil)))
             (when deferred (%assistant-send-task controller deferred)))))))))
(defun %assistant-interrupt-turn (controller)
  (when (and (assistant-controller-thread-id controller) (assistant-controller-turn-id controller))
    (%assistant-rpc controller "turn/interrupt"
        (%assistant-object "threadId" (assistant-controller-thread-id controller)
                           "turnId" (assistant-controller-turn-id controller))
      (lambda (result failure) (declare (ignore result failure))))))
(defun %assistant-interrupt (controller)
  (setf (assistant-controller-deferred controller) nil)
  (%assistant-interrupt-turn controller)
  (%assistant-voice-close controller))

(defun %assistant-cache-result (result)
  ;; Keep replay metadata, not megabytes of PNG data for each screenshot.
  ;; A duplicate receives the completed result and can explicitly observe again.
  (let ((items nil) (remaining 32768))
    (loop for item across (gethash "contentItems" result #()) do
          (when (equal "inputText" (gethash "type" item))
            (let ((text (gethash "text" item "")))
              (if (<= (length text) remaining)
                  (progn (push item items) (decf remaining (length text)))
                  (push (%assistant-object "type" "inputText" "text" "This call already completed. Its large result is not retained; observe again to check the current state.") items)))))
    (%assistant-object "success" (gethash "success" result) "contentItems" (coerce (nreverse items) 'vector))))

(defun %assistant-current-event-p (controller params)
  (and (or (null (%assistant-field params "threadId"))
           (equal (assistant-controller-thread-id controller) (%assistant-field params "threadId")))
       (or (null (%assistant-field params "turnId"))
           (equal (assistant-controller-turn-id controller) (%assistant-field params "turnId")))))
(defun %assistant-notification (controller method params)
  (when (and (string= method "turn/started")
             (equal (assistant-controller-thread-id controller) (%assistant-field params "threadId")))
    (unless (equal (assistant-controller-turn-id controller) (%assistant-field params "turn" "id"))
      (setf (assistant-controller-tool-count controller) 0)
      (clrhash (assistant-controller-seen-calls controller)))
    (setf (assistant-controller-turn-id controller) (%assistant-field params "turn" "id")))
  (unless (%assistant-current-event-p controller params) (return-from %assistant-notification nil))
  (cond
    ((string= method "account/login/completed")
     (when (equal (assistant-controller-login-id controller) (%assistant-field params "loginId"))
       (setf (assistant-controller-login-url controller) nil)
       (if (eq t (%assistant-field params "success")) (%assistant-account controller)
           (%assistant-state controller :activity (or (%assistant-field params "error") "Sign-in failed. Try again.")))))
    ((string= method "turn/started")
     (when (and (assistant-controller-voice-active controller)
                (member (assistant-controller-microphone controller) '(:starting :listening)))
       (%assistant-owner controller
         (lambda ()
           (when (and (assistant-controller-grant controller)
                      (member (assistant-controller-microphone controller) '(:starting :listening)))
             (setf (assistant-controller-voice-resume-p controller) nil (assistant-controller-blocked controller) nil)
             (when (assistant-controller-session controller) (cu:activate-session (assistant-controller-session controller)))))))
     (if (assistant-controller-blocked controller) (%assistant-interrupt controller)
         (%assistant-state controller :task :working :activity "Working")))
    ((string= method "item/agentMessage/delta")
     (let ((id (%assistant-field params "itemId")) (delta (%assistant-text (%assistant-field params "delta"))))
       (%assistant-owner controller
         (lambda ()
           (let* ((entry (find id (assistant-controller-messages controller) :key (lambda (m) (getf m :id)) :test #'equal))
                  (old (getf entry :text "")))
             (%assistant-add-message controller :assistant (concatenate 'string old delta) id)
             (%assistant-refresh controller))))))
    ((string= method "turn/plan/updated")
     (%assistant-state controller :plan (%assistant-field params "plan")))
    ((member method '("item/started" "item/completed") :test #'equal)
     (let* ((item (%assistant-field params "item")) (type (%assistant-field item "type")))
       (cond
         ((and (equal type "agentMessage") (equal method "item/completed"))
          (%assistant-owner controller
            (lambda () (%assistant-add-message controller :assistant (%assistant-field item "text") (%assistant-field item "id"))
              (%assistant-refresh controller))))
         ((equal method "item/started")
          (let ((label (cdr (assoc type '(("commandExecution" . "Running a project command")
                                          ("fileChange" . "Editing project files")
                                          ("dynamicToolCall" . "Using a desktop tool")) :test #'equal))))
            (when label (%assistant-state controller :activity label)))))))
    ((string= method "turn/completed")
     (when (equal (%assistant-field params "turn" "id") (assistant-controller-turn-id controller))
       (setf (assistant-controller-turn-id controller) nil (assistant-controller-starting-turn controller) nil)
       (let ((status (%assistant-field params "turn" "status")))
         (%assistant-owner controller
           (lambda ()
             (setf (assistant-controller-task controller)
                   (cond ((assistant-controller-blocked controller) :paused)
                         ((equal status "completed") :done) ((equal status "interrupted") :paused) (t :failed))
                   (assistant-controller-activity controller)
                   (cond ((equal status "completed") "Done") ((equal status "interrupted") "Stopped")
                         (t (%assistant-text (or (%assistant-field params "turn" "error" "message") "Task failed")))))
             ;; Completed tasks keep no input capability active between user turns.
             (when (assistant-controller-session controller)
               (cu:pause-session (assistant-controller-session controller) "Assistant is waiting for you"))
             (%assistant-refresh controller))))))
    ((and (>= (length method) 16) (string= "thread/realtime/" method :end2 16))
     (handler-case (%assistant-voice-event controller method params)
       (error (cause) (%assistant-voice-close controller)
              (%assistant-state controller :activity (format nil "Voice stopped: ~A. You can keep typing." cause)))))
    ((string= method "error")
     (%assistant-state controller :activity (or (%assistant-field params "error" "message") "Codex reported an error")))))

(defun %assistant-server-request (controller id method params)
  (unless (%assistant-current-event-p controller params)
    (%assistant-rpc-error controller id "Stale conversation or turn.")
    (return-from %assistant-server-request nil))
  (cond
    ((equal method "item/tool/call") (%assistant-dispatch-tool controller id params))
    ((member method '("item/commandExecution/requestApproval" "item/fileChange/requestApproval"
                      "item/permissions/requestApproval" "item/tool/requestUserInput") :test #'equal)
     (%assistant-owner controller
       (lambda ()
         (when (assistant-controller-request controller) (error "Concurrent user requests are not supported."))
         (setf (assistant-controller-request controller) (list :id id :method method :params params)
               (assistant-controller-task controller) :needs-input
               (assistant-controller-activity controller) "Needs your answer")
         (%assistant-refresh controller))))
    (t (%assistant-rpc-error controller id "This app-server request is not supported by Ataxia."))))
(defun %assistant-receive (controller message)
  (let ((id (gethash "id" message)) (method (gethash "method" message)))
    (cond
      ((and method id)
       (handler-case (%assistant-server-request controller id method (gethash "params" message))
         (error (cause) (%assistant-rpc-error controller id (princ-to-string cause)))))
      (method (%assistant-notification controller method (gethash "params" message)))
      (id (let ((pending (gethash id (assistant-controller-pending controller))))
            (when pending
              (remhash id (assistant-controller-pending controller))
              (funcall (first pending) (gethash "result" message) (gethash "error" message))))))))
