(in-package #:ataxia.assistant)
(defclass assistant-panel (rmlui-widget) ())
(defclass assistant-settings-dialog (rmlui-widget) ())
(defun %assistant-position-settings (controller)
  (let* ((dialog (assistant-controller-settings-dialog controller))
         (world (assistant-controller-world controller))
         (output (and dialog (find (overlay-output dialog) (world-outputs world)))))
    (when output
      (multiple-value-bind (width height) (output-logical-size output)
        (position-widget world dialog 0d0 0d0 width height)
        (cache-widget-value dialog :small (< width 400d0)
          (lambda (component) (ataxia.world.rmlui:set-rmlui-class component "dialog" "small" (< width 400d0))))))))
(defun %assistant-close-settings (controller)
  (let* ((dialog (assistant-controller-settings-dialog controller))
         (world (assistant-controller-world controller))
         (seat (find (assistant-controller-seat controller) (world-seats world)))
         (focused (and seat (eq dialog (world-seat-focus world seat)))))
    (when dialog
      (setf (assistant-controller-settings-dialog controller) nil)
      (hide-overlay world dialog)
      (remove-agent-widget world dialog)
      (when (and focused (assistant-controller-panel controller)
                 (overlay-visible-p (assistant-controller-panel controller)))
        (focus-world-target world seat (assistant-controller-panel controller))))))
(defun %assistant-open-settings (controller)
  (let* ((world (assistant-controller-world controller))
         (panel (assistant-controller-panel controller))
         (seat (find (assistant-controller-seat controller) (world-seats world)))
         (dialog (assistant-controller-settings-dialog controller)))
    (unless (and panel seat) (error "Open the assistant before changing settings."))
    (unless dialog
      (let ((path (asdf:system-relative-pathname "ataxia-assistant" "src/world/assistant/settings.rml")))
        (setf dialog (create-agent-widget 'assistant-settings-dialog world (uiop:read-file-string path)
                       :component-factory #'ataxia.world.rmlui:make-shell-rmlui-component :source-path (namestring path)
                       :output (overlay-output panel) :width 420d0 :height 420d0 :layer 1500)
              (assistant-controller-settings-dialog controller) dialog))
      (%assistant-bind-model-picker controller dialog)
      (dolist (id '("settings-close" "settings-done" "settings-backdrop"))
        (bind-agent-widget-event dialog id
          (lambda (widget event) (declare (ignore widget event)) (%assistant-close-settings controller)))))
    (setf (overlay-output dialog) (overlay-output panel))
    (%assistant-position-settings controller)
    (%assistant-render-models controller dialog)
    (show-overlay world dialog)
    (focus-world-target world seat dialog)
    dialog))
(defun %assistant-dismiss (controller)
  (if (assistant-controller-settings-dialog controller) (%assistant-close-settings controller)
      (%assistant-close-panel controller)))
(defun %assistant-install-dismiss-shortcut (controller)
  (let ((world (assistant-controller-world controller)))
    (ataxia.world:add-shortcut (assistant-controller-shortcuts controller)
      (ataxia.world:make-shortcut-binding :id :assistant-dismiss :priority 100 :key '(:keysym "Escape") :modifiers nil
        :predicate (lambda (target seat input)
                     (declare (ignore target input))
                     (let ((focused (world-seat-focus world seat)))
                       (and (assistant-controller-panel controller)
                            (member focused
                                    (list (assistant-controller-panel controller) (assistant-controller-settings-dialog controller))))))
        :press-handler (lambda (target seat input) (declare (ignore target seat input)) (%assistant-dismiss controller)))
      :if-exists :replace)))
(defvar *assistant-fonts-loaded* nil)
(defun %assistant-load-fonts ()
  (unless *assistant-fonts-loaded*
    (dolist (name '("dejavu/DejaVuSans-Bold.ttf" "dejavu/DejaVuSansMono.ttf" "liberation/LiberationSans-Italic.ttf"))
      (let ((path (merge-pathnames name #P"/usr/share/fonts/truetype/")))
        (when (probe-file path) (ataxia.world.rmlui:load-rmlui-font path))))
    (setf *assistant-fonts-loaded* t)))

(defun %assistant-label (controller)
  (cond ((eq :listening (assistant-controller-microphone controller)) "Listening")
        ((eq :starting (assistant-controller-microphone controller)) "Starting mic")
        ((eq :connecting (assistant-controller-connection controller)) "Connecting")
        (t (case (assistant-controller-task controller)
             (:working "Working") (:needs-input "Needs you") (:paused "Paused")
             (:done "Assistant") (:failed "Needs attention") (t "Assistant")))))
(defun %assistant-position (controller)
  (let* ((panel (assistant-controller-panel controller)) (world (assistant-controller-world controller))
         (state (and panel (find (overlay-output panel) (world-outputs world)))))
    (when state
      (multiple-value-bind (ow oh) (output-logical-size state)
        (let ((width (max 1d0 (min 480d0 (- ow 24d0)))) (height (max 1d0 (min 760d0 (- oh 76d0)))))
          (position-widget world panel (max 0d0 (- ow width 8d0)) (max 0d0 (- oh height 52d0)) width height)
          (cache-widget-value panel :small (< width 360d0)
            (lambda (component) (ataxia.world.rmlui:set-rmlui-class component "panel" "small" (< width 360d0)))))))))
(defun %assistant-question (request)
  (let* ((params (getf request :params)) (questions (%assistant-field params "questions"))
         (index (getf request :index 0)))
    (when (and (vectorp questions) (not (stringp questions)) (< index (length questions))) (aref questions index))))
(defun %assistant-render-request (controller panel)
  (let* ((request (assistant-controller-request controller))
         (question (and request (%assistant-question request)))
         (choices (and question (%assistant-field question "options"))))
    (set-widget-style panel "request" "display" (if request "block" "none"))
    (when request
      (set-widget-text panel "question"
        (if question
            (format nil "~A~%~A" (or (%assistant-field question "header") "Your answer") (%assistant-field question "question"))
            (%assistant-text (ataxia.computer-use.wire:encode (getf request :params)) 8192)))
      (set-widget-style panel "approval-actions" "display" (if question "none" "flex")))
    (dotimes (i 6)
      (let ((choice (and (vectorp choices) (< i (length choices)) (aref choices i))) (id (format nil "choice~D" i)))
        (set-widget-style panel id "display" (if choice "block" "none"))
        (when choice (set-widget-text panel id (format nil "~A — ~A" (%assistant-field choice "label") (or (%assistant-field choice "description") ""))))))))
(defun %assistant-render (controller)
  (let ((world (assistant-controller-world controller)) (panel (assistant-controller-panel controller)))
    (dolist (bar (world-overlays world))
      (when (typep bar 'rmlui-status-bar)
        (set-widget-style bar "assistant" "display" "block")
        (set-widget-text bar "assistant" (%assistant-label controller))))
    (when panel
      (%assistant-position controller)
      (when (assistant-controller-settings-dialog controller)
        (%assistant-position-settings controller)
        (%assistant-render-models controller (assistant-controller-settings-dialog controller)))
      (let* ((task (assistant-controller-task controller))
             (working (member task '(:working :paused :needs-input)))
             (details (assistant-generation-settings-details (assistant-controller-generation-settings controller))))
        (set-widget-style panel "empty" "display" (if (or (assistant-controller-messages controller) working) "none" "block"))
        (set-widget-style panel "controls" "display" (if (or working (assistant-controller-undo controller)) "flex" "none"))
        (set-widget-style panel "pause" "display" (if working "block" "none"))
        (set-widget-style panel "stop" "display" (if working "block" "none"))
        (set-widget-style panel "plan" "display" (if (or working details) "block" "none"))
        (set-widget-style panel "activity" "display" (if (or working details (eq task :failed)
                                                     (member (assistant-controller-connection controller) '(:error :connecting))
                                                     (not (eq :off (assistant-controller-microphone controller)))) "block" "none"))
        (set-widget-style panel "limits" "display" (if details "block" "none"))
        (set-widget-text panel "details" (if details "Hide details" "Details")))
      (set-widget-style panel "connection-actions" "display" (if (eq :error (assistant-controller-connection controller)) "flex" "none"))
      (set-widget-text panel "login" (if (assistant-controller-login-url controller) "Open sign-in" "Sign in"))
      (set-widget-text panel "limits"
        (if (eq :working (assistant-controller-task controller))
            (let ((elapsed (max 0 (floor (- (monotonic-time) (assistant-controller-started controller))))))
              (format nil "~D:~2,'0D elapsed · ~D/~D calls · ~D min limit" (floor elapsed 60) (mod elapsed 60)
                      (assistant-controller-tool-count controller) *assistant-tool-limit* (round (/ *assistant-time-limit* 60))))
            (format nil "Task limits: ~D minutes · ~D tool calls" (round (/ *assistant-time-limit* 60)) *assistant-tool-limit*)))
      (set-widget-text panel "state" (let ((label (%assistant-label controller))) (if (equal label "Assistant") "Ready" label)))
      (set-widget-text panel "scope" (ecase (assistant-controller-scope controller) (:desktop "Desktop") (:application "Selected app") (:project "Project")))
      (set-widget-text panel "scope-note" (ecase (assistant-controller-scope controller)
                                     (:desktop "Windows and layout") (:application "Only the selected window") (:project "Files and app previews")))
      (set-widget-style panel "project" "display" (if (eq :project (assistant-controller-scope controller)) "block" "none"))
      (cache-widget-value panel :transcript (%assistant-visible-messages controller)
        (lambda (component)
          (ataxia.world.rmlui:set-rmlui-model component "transcript"
            (%assistant-transcript-rml (%assistant-visible-messages controller)))))
      (set-widget-text panel "plan"
        (with-output-to-string (out)
          (loop for step across (or (assistant-controller-plan controller) #()) do
            (format out "~A  ~A~%" (cond ((equal (%assistant-field step "status") "completed") "✓")
                                       ((equal (%assistant-field step "status") "inProgress") "→") (t "·"))
                    (%assistant-text (%assistant-field step "step") 256)))))
      (set-widget-text panel "activity" (assistant-controller-activity controller))
      (set-widget-text panel "pause" (if (eq :paused (assistant-controller-task controller)) "Resume" "Pause"))
      (set-widget-style panel "undo" "display" (if (assistant-controller-undo controller) "block" "none"))
      (set-widget-text panel "send" (if (assistant-controller-request controller) "Answer" "Send"))
      (set-widget-text panel "talk" (if (eq :off (assistant-controller-microphone controller)) "Voice" "Mic on · End"))
      (set-widget-text panel "mic-status" (case (assistant-controller-microphone controller)
                                     (:listening "Microphone on") (:starting "Starting microphone") (t "Microphone off")))
      (%assistant-render-request controller panel))))
(defun %assistant-refresh (controller &optional force)
  (when (assistant-controller-alive controller)
    (if (or force (>= (- (monotonic-time) (assistant-controller-last-render controller)) .05d0))
        (progn
          (setf (assistant-controller-last-render controller) (monotonic-time))
          (%assistant-render controller)
          (when (assistant-controller-timer controller)
            (ataxia.runtime:update-event-loop-timer (assistant-controller-timer controller)
              (if (and (assistant-controller-panel controller) (eq :working (assistant-controller-task controller))) 1000 0))))
        (when (assistant-controller-timer controller)
          (ataxia.runtime:update-event-loop-timer (assistant-controller-timer controller) 50)))))
(defun %assistant-ui-call (controller function)
  (handler-case (funcall function)
    (error (cause)
      (setf (assistant-controller-activity controller) (%assistant-text (princ-to-string cause) 1024)
            (assistant-generation-settings-details (assistant-controller-generation-settings controller)) t)))
  (%assistant-refresh controller t))
(defun %assistant-render-models (controller panel)
  (let* ((state (assistant-controller-model-selection controller))
         (selected (assistant-model-selection-selected state))
         (active (assistant-model-selection-active state))
         (default (assistant-model-selection-default state))
         (settings (assistant-controller-generation-settings controller))
         (effort (assistant-generation-settings-effort settings))
         (default-effort (if selected (%assistant-field (%assistant-model-entry controller selected) "defaultReasoningEffort")
                             (assistant-model-selection-default-effort state)))
         (effective-effort (or effort default-effort))
         (fast-available (%assistant-fast-tier controller))
         (fast-on (not (equal "default" (%assistant-effective-tier controller))))
         (effort-options (with-output-to-string (out)
                           (write-string "<select id=\"effort-select\" data-value=\"selected_effort\">" out)
                           (format out "<option value=\"\">Auto~A</option>"
                                   (%assistant-escape-rml (if default-effort (format nil " · ~A" (if (equal default-effort "xhigh") "X-high" (%assistant-effort-name default-effort))) "")))
                           (dolist (value (%assistant-supported-efforts controller))
                             (format out "<option value=\"~A\">~A</option>" (%assistant-escape-rml value)
                                     (%assistant-escape-rml (%assistant-effort-name value))))
                           (write-string "</select><div id=\"effort-chevron\">▾</div>" out)))
         (models (%assistant-picker-models controller))
         (options (with-output-to-string (out)
                    (write-string "<select id=\"model-select\" data-value=\"selected_model\">" out)
                    (format out "<option value=\"\">~A</option>"
                            (%assistant-escape-rml (if default (%assistant-model-name controller default) "Codex default")))
                    (loop for entry across models for model = (%assistant-field entry "model") do
                      (format out "<option value=\"~A\">~A</option>" (%assistant-escape-rml model)
                              (%assistant-escape-rml (%assistant-model-name controller model))))
                    (write-string "</select><div id=\"model-chevron\">▾</div>" out))))
    (cache-widget-value panel :model-options options
      (lambda (component)
        (ataxia.world.rmlui:set-rmlui-model component "model_options" options)))
    ;; Set only on a change; this leaves a keyboard-open dropdown undisturbed.
    (cache-widget-value panel :selected-model (list selected options)
      (lambda (component) (ataxia.world.rmlui:set-rmlui-model component "selected_model" (or selected ""))))
    (cache-widget-value panel :effort-options effort-options
      (lambda (component) (ataxia.world.rmlui:set-rmlui-model component "effort_options" effort-options)))
    (cache-widget-value panel :selected-effort (list effort effort-options)
      (lambda (component) (ataxia.world.rmlui:set-rmlui-model component "selected_effort" (or effort ""))))
    (set-widget-text panel "fast" (cond ((not fast-available) "Fast unavailable") (fast-on "Fast on") (t "Fast off")))
    (cache-widget-value panel :fast-style (list (not (null fast-available)) fast-on)
      (lambda (component)
        (ataxia.world.rmlui:set-rmlui-class component "fast" "enabled" (and fast-available fast-on))
        (ataxia.world.rmlui:set-rmlui-class component "fast" "unavailable" (not fast-available))))
    (set-widget-style panel "models-load" "display" (if (plusp (length models)) "none" "block"))
    (set-widget-text panel "models-load" (if (eq :connecting (assistant-controller-connection controller)) "…" "Connect"))
    (set-widget-style panel "effort-setting" "display" (if (plusp (length models)) "block" "none"))
    (set-widget-style panel "model-note" "display"
      (if (or (and selected (not (%assistant-model-entry controller selected)))
              (and (or (assistant-controller-turn-id controller) (assistant-controller-starting-turn controller))
                   (or (not (equal active (or selected default)))
                       (not (equal effective-effort (assistant-generation-settings-active-effort settings)))
                       (not (equal (%assistant-effective-tier controller) (assistant-generation-settings-active-tier settings))))))
          "block" "none"))
    (set-widget-text panel "model-note"
      (cond ((and selected (not (%assistant-model-entry controller selected))) "Selected model unavailable; choose another")
            (t "New settings will apply to your next task")))))
(defun %assistant-bind-model-picker (controller panel)
  ;; Listen on the stable parent: rebuilding choices replaces the select.
  (bind-agent-widget-event panel "model-field:change"
    (lambda (widget event)
      (declare (ignore widget))
      (%assistant-ui-call controller
        (lambda () (%assistant-select-model controller (agent-widget-event-value event))))))
  (bind-agent-widget-event panel "effort-field:change"
    (lambda (widget event)
      (declare (ignore widget))
      (%assistant-ui-call controller
        (lambda () (%assistant-select-effort controller (agent-widget-event-value event))))))
  (bind-agent-widget-event panel "fast"
    (lambda (widget event)
      (declare (ignore widget event))
      (%assistant-ui-call controller (lambda () (%assistant-toggle-fast controller)))))
  (bind-agent-widget-event panel "models-load"
    (lambda (widget event)
      (declare (ignore widget event))
      (%assistant-ui-call controller
        (lambda ()
          (unless (eq :connecting (assistant-controller-connection controller))
            (if (and (assistant-controller-worker controller) (sb-thread:thread-alive-p (assistant-controller-worker controller)))
                (%assistant-queue controller :retry nil)
                (%assistant-connect controller))))))))
(defun %assistant-bind-panel-settings (controller panel)
  (bind-agent-widget-event panel "settings-open"
    (lambda (widget event) (declare (ignore widget event))
      (%assistant-ui-call controller (lambda () (%assistant-open-settings controller)))))
  (bind-agent-widget-event panel "details"
    (lambda (widget event)
      (declare (ignore widget event))
      (%assistant-ui-call controller
        (lambda ()
          (let ((settings (assistant-controller-generation-settings controller)))
            (setf (assistant-generation-settings-details settings) (not (assistant-generation-settings-details settings)))))))))
(defun %assistant-close-panel (controller)
  (%assistant-close-settings controller)
  (%assistant-audio-stop-now controller)
  (ignore-errors (%assistant-queue controller :voice-stop nil))
  (let ((panel (shiftf (assistant-controller-panel controller) nil)))
    (when panel
      (hide-overlay (assistant-controller-world controller) panel)
      (remove-agent-widget (assistant-controller-world controller) panel)))
  (%assistant-refresh controller t))
(defun %assistant-read-composer (controller)
  (let ((panel (assistant-controller-panel controller)))
    (if panel (or (ataxia.world.rmlui:rmlui-model-value (overlay-component panel) "message") "") "")))
(defun %assistant-clear-composer (controller)
  (when (assistant-controller-panel controller)
    (ataxia.world.rmlui:set-rmlui-model (overlay-component (assistant-controller-panel controller)) "message" "")))
(defun %assistant-open (controller &optional seat)
  (let* ((world (assistant-controller-world controller)) (seat (or seat (assistant-controller-seat controller)
                                                                 (find-if-not #'agent-seat-p (world-seats world))))
         (output (and seat (world-seat-output world seat))))
    (unless output (error "No desktop output is available."))
    (when (agent-seat-p seat) (error "Only a human seat may open the assistant."))
    (setf (assistant-controller-seat controller) seat)
    (unless (assistant-controller-grant controller) (setf (assistant-controller-output controller) output))
    (let ((panel (assistant-controller-panel controller))
          (new-panel-p (null (assistant-controller-panel controller))))
      (unless panel
        (%assistant-load-fonts)
        (let ((path (asdf:system-relative-pathname "ataxia-assistant" "src/world/assistant/panel.rml")))
          (setf panel (create-agent-widget 'assistant-panel world (uiop:read-file-string path)
                      :component-factory #'ataxia.world.rmlui:make-shell-rmlui-component :source-path (namestring path)
                      :output output :width 480d0 :height 760d0 :layer 1400)
                (assistant-controller-panel controller) panel))
        (ataxia.world.rmlui:set-rmlui-model (overlay-component panel) "message" "")
        (ataxia.world.rmlui:set-rmlui-model (overlay-component panel) "project" (assistant-controller-project controller))
        (%assistant-bind-panel-settings controller panel)
        (labels ((bind (id function)
                   (bind-agent-widget-event panel id (lambda (widget event) (declare (ignore widget event))
                                                       (%assistant-ui-call controller function)))))
          (bind "retry" (lambda ()
                          (if (and (assistant-controller-worker controller) (sb-thread:thread-alive-p (assistant-controller-worker controller)))
                              (%assistant-queue controller :retry nil) (%assistant-connect controller))))
          (bind "login" (lambda ()
                          (if (and (assistant-controller-worker controller) (sb-thread:thread-alive-p (assistant-controller-worker controller)))
                              (%assistant-queue controller :login nil) (%assistant-connect controller))))
          (bind "close" (lambda () (%assistant-close-panel controller)))
          (bind "send" (lambda ()
                         (let ((text (%assistant-read-composer controller)))
                           (if (assistant-controller-request controller) (%assistant-answer controller text)
                               (%assistant-submit controller text))
                           (%assistant-clear-composer controller))))
          (bind "pause" (lambda () (if (eq :paused (assistant-controller-task controller))
                                      (%assistant-submit controller "Continue the current task.")
                                      (%assistant-pause controller))))
          (bind "stop" (lambda () (%assistant-stop controller)))
          (bind "talk" (lambda () (%assistant-toggle-talk controller)))
          (bind "undo" (lambda () (%assistant-layout-undo controller (getf (assistant-controller-undo controller) :token) t)))
          (bind "scope" (lambda ()
                          (when (or (assistant-controller-turn-id controller) (assistant-controller-starting-turn controller)
                                    (assistant-controller-voice-active controller))
                            (error "Stop the current task before changing scope."))
                          (%assistant-reset-conversation controller)
                          (setf (assistant-controller-scope controller)
                                (ecase (assistant-controller-scope controller) (:desktop :application) (:application :project) (:project :desktop)))))
          (bind "allow" (lambda () (%assistant-answer controller :allow)))
          (bind "deny" (lambda () (%assistant-answer controller :deny)))
          (dotimes (i 6)
            (let ((index i))
              (bind (format nil "choice~D" i)
                    (lambda ()
                      (let* ((request (assistant-controller-request controller))
                             (question (and request (%assistant-question request)))
                             (options (and question (%assistant-field question "options"))))
                        (when (and options (< index (length options)))
                          (%assistant-answer controller (%assistant-field (aref options index) "label"))))))))))
      (setf (overlay-output panel) output)
      (when (assistant-controller-settings-dialog controller)
        (setf (overlay-output (assistant-controller-settings-dialog controller)) output))
      (show-overlay world panel)
      (focus-world-target world seat (or (assistant-controller-settings-dialog controller) panel) :remember new-panel-p)
      (%assistant-refresh controller t)
      panel)))
