import { MetaButton } from "controls.slint";

export component CanvasCreation inherits Window {
    background: transparent;
    callback action(string);
    Rectangle { border-width: 1px; border-color: #d4d8dc; border-radius: 0px; background: #ffffff; }
    VerticalLayout {
        padding: 6px; spacing: 5px;
        MetaButton { align-left: true; label: "Niri world"; activate => { root.action("new-niri"); } }
        MetaButton { align-left: true; label: "Hyprland world"; activate => { root.action("new-hyprland"); } }
        MetaButton { align-left: true; label: "Note"; activate => { root.action("note"); } }
    }
}
