import { MetaButton } from "controls.slint";

export component CanvasCreation inherits Window {
    background: transparent;
    callback action(string);
    Rectangle { border-width: 1px; border-color: #c7c7c7; border-radius: 8px; background: #ffffff; }
    VerticalLayout {
        padding: 6px; spacing: 5px;
        MetaButton { label: "Niri world"; activate => { root.action("new-niri"); } }
        MetaButton { label: "Hyprland world"; activate => { root.action("new-hyprland"); } }
        MetaButton { label: "Note"; activate => { root.action("note"); } }
    }
}
