;;;; Metaworld layout adapter. Plans are data; grants are stable application IDs.
(in-package #:ataxia.infinite-world)

(defun %desktop-group-position (world group)
  (let ((motion (%meta-motion world group :subworld-push)))
    (if motion (%meta-trajectory-destination motion) (list (subworld-x group) (subworld-y group)))))
(defun %desktop-object-geometry (world object)
  (let* ((geometry (copy-list (%meta-target-geometry world object)))
         (group (object-subworld world object)))
    (when group
      (let ((position (%desktop-group-position world group)))
        (incf (first geometry) (- (first position) (subworld-x group)))
        (incf (second geometry) (- (second position) (subworld-y group)))))
    ;; Translating an animated group can introduce insignificant float roundoff.
    (mapcar (lambda (n) (/ (round (* n 10000d0)) 10000d0)) geometry)))
(defun %desktop-camera (world state)
  (let ((motion (%meta-motion world state :metaworld-camera)))
    (if motion (destructuring-bind (x y zoom rotation) (%meta-trajectory-destination motion)
                 (list (/ x zoom) (/ y zoom) zoom rotation))
        (%meta-camera state))))

(defmethod ataxia.world:world-desktop-state ((world metaworld))
  (let ((groups (metaworld-subworlds world)))
    (list :coordinate-space "world" :groups
          (coerce (loop for group in groups collect
            (list :id (subworld-id group) :name (subworld-name group)
                  :policy (if (eq :niri (subworld-kind group)) "niri" (string-downcase (symbol-name (subworld-layout group))))
                  :workspace (subworld-workspace group) :workspace-count (%meta-workspace-count group)
                  :x (first (%desktop-group-position world group)) :y (second (%desktop-group-position world group))
                  :width (subworld-width group) :height (subworld-height group)
                  :ratio (subworld-ratio group)
                  :fullscreen (let ((object (subworld-fullscreen group)))
                                (typecase object (canvas-window (ataxia.kernel:object-id (canvas-window-application object)))
                                                 (agent-widget (list :widget (agent-widget-id object)))))
                  :members (coerce (loop for member in (subworld-members group)
                    for window = (subworld-member-object member) when (typep window 'canvas-window) collect
                    (list :window (ataxia.kernel:object-id (canvas-window-application window))
                          :workspace (subworld-member-workspace member) :column (subworld-member-column member)
                          :width (subworld-member-width member) :weight (subworld-member-weight member)
                          :floating (if (subworld-member-floating-p member) t :false))) 'vector))) 'vector)
          :windows
          (coerce (loop for window in (sort (copy-list (%world-stacking world)) #'<
                                          :key (lambda (w) (ataxia.kernel:object-id (canvas-window-application w))))
                        for app = (canvas-window-application window)
                        for group = (object-subworld world window)
                        for member = (and group (%meta-member group window)) collect
            (list :id (ataxia.kernel:object-id app) :title (or (ataxia.kernel:application-title app) "")
                  :app-id (or (ataxia.kernel:application-app-id app) "")
                  :group (and group (subworld-id group))
                  :workspace (and member (subworld-member-workspace member))
                  :floating (if (and member (subworld-member-floating-p member)) t :false)
                  :column (and member (subworld-member-column member))
                  :geometry (coerce (%desktop-object-geometry world window) 'vector)
                  :minimized (if (%canvas-window-minimized-p window) t :false)
                  :fullscreen (if (or (and group (eq window (subworld-fullscreen group)))
                                      (eq :fullscreen (%canvas-window-expanded-state window))) t :false)
                  :maximized (if (eq :maximized (%canvas-window-expanded-state window)) t :false)
                  :available (if (ataxia.world:world-window-visible-p world window) t :false)
                  :on-outputs (coerce (loop for output in (ataxia.world:world-outputs world)
                                           when (ataxia.world:world-window-visible-p world window output)
                                             collect (ataxia.kernel:object-id output)) 'vector)
                  :visible (if (and (%canvas-window-mapped-p window)
                                    (not (%canvas-window-minimized-p window))
                                    (%canvas-window-input-enabled-p window)) t :false))) 'vector)
          :widgets
          (coerce (loop for widget in (sort (loop for w being the hash-keys of (%meta-spatial-widgets world) collect w) #'< :key #'agent-widget-id)
                        for group = (object-subworld world widget)
                        for member = (and group (%meta-member group widget)) collect
                    (list :id (agent-widget-id widget) :group (and group (subworld-id group))
                          :workspace (and member (subworld-member-workspace member))
                          :column (and member (subworld-member-column member))
                          :geometry (coerce (%desktop-object-geometry world widget) 'vector))) 'vector)
          :outputs
          (coerce (loop for state in (%output-states world)
                        for motion = (%meta-motion world state :metaworld-camera)
                        for view = (%meta-view-for-state world state) collect
            (list :id (ataxia.kernel:object-id (%canvas-output-output state))
                  :name (ataxia.kernel:output-name (%canvas-output-output state))
                  :position (vector (%canvas-output-layout-x state) (%canvas-output-layout-y state))
                  :size (coerce (multiple-value-list (%output-logical-size state)) 'vector)
                  :group (and (%meta-view-active view) (subworld-id (%meta-view-active view)))
                  :camera (coerce (if motion
                                     (destructuring-bind (x y zoom rotation) (%meta-trajectory-destination motion)
                                       (list (/ x zoom) (/ y zoom) zoom rotation))
                                     (%meta-camera state)) 'vector)
                  :transform (%canvas-output-transform state))) 'vector))))
(defun %desktop-layout-id (world id)
  (or (find id (metaworld-subworlds world) :key #'subworld-id :test #'equal)
      (error "Unknown group ~A. Observe the desktop again." id)))
(defun %desktop-layout-window (world id)
  (or (find id (%world-stacking world)
            :key (lambda (w) (ataxia.kernel:object-id (canvas-window-application w))))
      (error "Window ~A is no longer present." id)))
(defun %desktop-layout-policy (value)
  (or (cdr (assoc value '(("niri" . :niri) ("dwindle" . :dwindle) ("master" . :master)) :test #'equal))
      (error "Policy must be niri, dwindle, or master.")))
(defmethod ataxia.world:validate-world-layout ((world metaworld) operations)
  (unless (and (vectorp operations) (not (stringp operations)) (<= 1 (length operations) 64))
    (error "A layout plan must contain 1–64 operations."))
  (let ((aliases (make-hash-table :test #'equal)) (removed (make-hash-table :test #'equal)))
    (loop for operation across operations do
      (unless (and (hash-table-p operation) (<= (hash-table-count operation) 12)) (error "Invalid layout operation."))
      (maphash (lambda (key value) (declare (ignore value))
                 (unless (member key '("op" "ref" "group" "window" "workspace" "name" "policy" "x" "y" "width" "height" "floating") :test #'equal)
                   (error "Unknown layout field ~A." key))) operation)
      (let ((op (gethash "op" operation)))
        (unless (member op '("create-group" "configure-group" "remove-group" "place-window") :test #'equal) (error "Unknown layout operation."))
        (when (equal op "create-group")
          (when (%meta-standalone world) (error "This World cannot contain additional groups."))
          (let ((ref (%layout-string (gethash "ref" operation) 40 "ref")))
            (when (gethash ref aliases) (error "Duplicate group reference."))
            (setf (gethash ref aliases) t))
          (%layout-string (gethash "name" operation) 80 "name")
          (%desktop-layout-policy (gethash "policy" operation)))
        (when (equal op "remove-group")
          (when (%meta-standalone world) (error "A standalone world's only sub-world cannot be removed."))
          (maphash (lambda (key value) (declare (ignore value))
                     (unless (member key '("op" "group") :test #'equal)
                       (error "remove-group accepts only op and group."))) operation))
        (unless (equal op "create-group")
          (let ((group (gethash "group" operation)))
            (when (gethash group removed) (error "Group ~A was already removed earlier in this plan." group))
            (when (or group (member op '("configure-group" "remove-group") :test #'equal))
              (unless (gethash group aliases) (%desktop-layout-id world group)))))
        (when (equal op "remove-group") (setf (gethash (gethash "group" operation) removed) t))
        (when (equal op "place-window")
          (%desktop-layout-window world (gethash "window" operation))
          (when (and (gethash "workspace" operation) (null (gethash "group" operation)))
            (error "A workspace destination needs a group."))
          (when (gethash "workspace" operation) (%layout-number (gethash "workspace" operation) 1 9 "workspace")
                (unless (integerp (gethash "workspace" operation)) (error "Workspace must be an integer."))))
        (dolist (key '("x" "y"))
          (when (gethash key operation) (%layout-number (gethash key operation) -100000 100000 key)))
        (dolist (key '("width" "height"))
          (when (gethash key operation) (%layout-number (gethash key operation) 96 8192 key)))
        (when (gethash "name" operation) (%layout-string (gethash "name" operation) 80 "name"))
        (when (gethash "policy" operation) (%desktop-layout-policy (gethash "policy" operation)))
        (when (nth-value 1 (gethash "floating" operation))
          (unless (member (gethash "floating" operation) '(t :false)) (error "Floating must be a boolean."))))))
  operations)
(defun %desktop-capture-layout (world)
  (list :groups (mapcar (lambda (group)
                         (let ((copy (copy-subworld group)))
                           (setf (subworld-x copy) (first (%desktop-group-position world group))
                                 (subworld-y copy) (second (%desktop-group-position world group))
                                 (subworld-members copy) (mapcar #'copy-subworld-member (subworld-members group))
                                 (subworld-scrolls copy) (alexandria:copy-hash-table (subworld-scrolls group)))
                           (cons group copy))) (metaworld-subworlds world))
        :windows (mapcar (lambda (window) (list window (%desktop-object-geometry world window)
                                               (not (%canvas-window-input-enabled-p window)) (%canvas-window-input-enabled-p window)
                                               (%canvas-window-restore-geometry window))) (%world-stacking world))
        :widgets (loop for widget being the hash-keys of (%meta-spatial-widgets world)
                       collect (list widget (%desktop-object-geometry world widget) (overlay-visible-p widget)))
        :workspace-counts (loop for group in (metaworld-subworlds world) collect (cons group (%meta-workspace-count group)))
        :views (loop for state in (%output-states world) collect
                 (list state (copy-%meta-view (%meta-view-for-state world state)) (%desktop-camera world state)))
        :focus (loop for state in (%seat-states world) collect (list state (%canvas-seat-focused state)))
        :group-focus (alexandria:copy-hash-table (%meta-group-focus world))))
(defun %desktop-restore-layout (world saved)
  (let ((old-restoring (%meta-restoring-p world))
        (current-fullscreens (remove nil (mapcar #'subworld-fullscreen (metaworld-subworlds world))))
        (saved-fullscreens (remove nil (mapcar (lambda (entry) (subworld-fullscreen (cdr entry))) (getf saved :groups)))))
    (unwind-protect
         (progn
           (dolist (group (metaworld-subworlds world)) (%meta-cancel-motion world group :subworld-push))
           (setf (%meta-restoring-p world) t
                 (metaworld-subworlds world) (mapcar #'car (getf saved :groups)))
           (clrhash (%meta-owners world))
           (dolist (entry (getf saved :groups))
             (let ((group (car entry)) (copy (cdr entry)))
               (setf (subworld-name group) (subworld-name copy) (subworld-kind group) (subworld-kind copy)
                     (subworld-layout group) (subworld-layout copy) (subworld-x group) (subworld-x copy)
                     (subworld-y group) (subworld-y copy) (subworld-width group) (subworld-width copy)
                     (subworld-height group) (subworld-height copy) (subworld-workspace group) (subworld-workspace copy)
                     (subworld-ratio group) (subworld-ratio copy) (subworld-next-column group) (subworld-next-column copy)
                     (subworld-members group) (subworld-members copy) (subworld-scrolls group) (subworld-scrolls copy)
                     (subworld-fullscreen group) (subworld-fullscreen copy))
               (dolist (member (subworld-members group)) (setf (gethash (subworld-member-object member) (%meta-owners world)) group))))
           (dolist (window (union current-fullscreens saved-fullscreens))
             (when (and (typep window 'canvas-window)
                        (not (eq (not (null (member window current-fullscreens))) (not (null (member window saved-fullscreens))))))
               (ataxia.kernel:request-object-state (canvas-window-application window) world :fullscreen
                                                  (not (null (member window saved-fullscreens))))))
           (dolist (entry (getf saved :workspace-counts)) (setf (gethash (car entry) *meta-workspace-counts*) (cdr entry)))
           (dolist (entry (getf saved :widgets))
             (destructuring-bind (widget geometry visible) entry
               (%meta-cancel-motion world widget :metaworld-layout)
               (apply #'%meta-place world widget geometry)
               (setf (overlay-visible-p widget) visible)))
           (setf (%meta-packing-signature world)
                 (loop for group in (metaworld-subworlds world) collect (list group (%meta-footprint-width group) (%meta-footprint-height group))))
           (dolist (entry (getf saved :windows))
             (destructuring-bind (window geometry hidden input restore) entry
               (%meta-cancel-motion world window :metaworld-layout)
               (%meta-cancel-motion world window :visibility)
               (setf (%canvas-window-visibility-opacity window) (if hidden 0d0 1d0))
               (apply #'%meta-place world window geometry)
               (setf (%canvas-window-hidden-p window) hidden (%canvas-window-input-enabled-p window) input
                     (%canvas-window-restore-geometry window) restore)))
           (dolist (entry (getf saved :views))
             (destructuring-bind (state view camera) entry
               (setf (%meta-view-active (%meta-view-for-state world state)) (%meta-view-active view)
                     (%meta-view-parent-camera (%meta-view-for-state world state)) (%meta-view-parent-camera view))
               (%meta-cancel-motion world state :metaworld-camera)
               (%meta-set-camera world state camera)))
           (clrhash (%meta-group-focus world))
           (maphash (lambda (key value) (setf (gethash key (%meta-group-focus world)) value)) (getf saved :group-focus))
           (%meta-changed world))
      (setf (%meta-restoring-p world) old-restoring))))
(defun %desktop-apply-operation (world operation aliases)
  (let* ((op (gethash "op" operation))
         (ref (gethash "group" operation))
         (group (and ref (or (gethash ref aliases) (%desktop-layout-id world ref)))))
    (cond
      ((equal op "create-group")
       (let* ((policy (%desktop-layout-policy (gethash "policy" operation)))
              (created (create-subworld world (if (eq policy :niri) :niri :hyprland)
                        :name (gethash "name" operation) :x (gethash "x" operation) :y (gethash "y" operation))))
         (unless (eq policy :niri) (setf (subworld-layout created) policy))
         (setf (gethash (gethash "ref" operation) aliases) created)))
      ((equal op "remove-group")
       (dolist (state (%output-states world))
         (when (eq group (%meta-view-active (%meta-view-for-state world state)))
           (%meta-cancel-motion world state :metaworld-camera)))
       (remove-subworld world group)
       ;; Batched moves enqueue their previous group; it no longer needs layout.
       (setf *meta-layout-pending* (remove group *meta-layout-pending*)))
      ((equal op "configure-group")
       (when (gethash "name" operation) (setf (subworld-name group) (gethash "name" operation)))
       (when (gethash "policy" operation)
         (let ((policy (%desktop-layout-policy (gethash "policy" operation))))
           (setf (subworld-kind group) (if (eq policy :niri) :niri :hyprland))
           (unless (eq policy :niri) (setf (subworld-layout group) policy))))
       (when (or (gethash "x" operation) (gethash "y" operation))
         (move-subworld world group (gethash "x" operation (subworld-x group)) (gethash "y" operation (subworld-y group))))
       (%meta-layout world group))
      ((equal op "place-window")
       (let ((window (%desktop-layout-window world (gethash "window" operation))))
         (move-object-to-subworld world window group :workspace (gethash "workspace" operation))
         (let ((member (and group (%meta-member group window))))
           (when member
             (when (nth-value 1 (gethash "floating" operation))
               (setf (subworld-member-floating-p member) (eq t (gethash "floating" operation))))
             (when (gethash "width" operation) (setf (subworld-member-width member) (gethash "width" operation)))
             (%meta-layout world group))
           (when (or (null group) (and member (subworld-member-floating-p member)))
             (destructuring-bind (x y width height) (%meta-target-geometry world window)
               (%meta-place world window (gethash "x" operation x) (gethash "y" operation y)
                            (gethash "width" operation width) (gethash "height" operation height))))))))))

(defun %layout-string (value maximum field)
  (unless (and (stringp value) (<= 1 (length value) maximum))
    (error "~A must be a nonempty string of at most ~D characters." field maximum))
  value)
(defun %layout-number (value minimum maximum field)
  (unless (and (realp value) (<= minimum value maximum))
    (error "~A is outside its allowed range." field))
  value)

(defmethod ataxia.world:apply-world-layout :around ((world metaworld) operations)
  (ataxia.world:validate-world-layout world operations)
  (let ((saved (%desktop-capture-layout world)))
    (handler-case (call-next-method)
      (error (cause)
        (%desktop-restore-layout world saved)
        (error cause)))))

(defmethod ataxia.world:apply-world-layout ((world metaworld) operations)
  (let ((aliases (make-hash-table :test #'equal)))
    (%with-meta-layout-batch (world)
      (loop for operation across operations do
        (%desktop-apply-operation world operation aliases)))
    (%meta-changed world)))

(defmethod ataxia.world:world-layout-schema ((world metaworld))
  (flet ((object (&rest entries) (alexandria:plist-hash-table entries :test #'equal)))
    (let ((string (object "type" "string")) (integer (object "type" "integer"))
          (number (object "type" "number")) (boolean (object "type" "boolean")))
      (values
       (object "type" "object" "required" #("op") "additionalProperties" :false
               "properties"
               (object "op" (object "type" "string" "enum" #("create-group" "configure-group" "remove-group" "place-window"))
                       "ref" string "group" (object "oneOf" (vector integer string (object "type" "null")))
                       "window" integer "name" string
                       "policy" (object "type" "string" "enum" #("niri" "dwindle" "master"))
                       "workspace" (object "type" "integer" "minimum" 1 "maximum" 9)
                       "x" number "y" number "width" number "height" number "floating" boolean))
       "create-group needs ref, name and policy; later operations can use that ref as group. configure-group changes an existing group. remove-group returns its windows and widgets to the shared canvas without closing them; use place-window first to move members elsewhere. place-window assigns a window to a group/workspace, or group null for the canvas. Free geometry applies only to canvas or floating windows."))))
