(in-package #:ataxia.infinite-world)

;; Each workspace owns a persistent split tree. Leaves are stable member column
;; IDs; branches are (:split axis ratio first second). Layout never rewrites the
;; tree merely because an animated rectangle changes its aspect ratio.
(defvar *meta-hypr-trees* (make-hash-table :test #'eq :weakness :key))

(defun %meta-hypr-tree (group workspace)
  (let ((table (gethash group *meta-hypr-trees*)))
    (when table (gethash workspace table))))

(defun (setf %meta-hypr-tree) (tree group workspace)
  (let ((table (or (gethash group *meta-hypr-trees*)
                   (setf (gethash group *meta-hypr-trees*) (make-hash-table)))))
    (setf (gethash workspace table) tree)))

(defun %meta-hypr-leaves (tree)
  (if (consp tree)
      (append (%meta-hypr-leaves (fourth tree)) (%meta-hypr-leaves (fifth tree)))
      (when tree (list tree))))

(defun %meta-hypr-prune (tree ids)
  (if (consp tree)
      (let ((a (%meta-hypr-prune (fourth tree) ids))
            (b (%meta-hypr-prune (fifth tree) ids)))
        (cond ((null a) b) ((null b) a)
              (t (setf (fourth tree) a (fifth tree) b) tree)))
      (when (member tree ids) tree)))

(defun %meta-hypr-replace (tree id replacement)
  (cond ((eql tree id) replacement)
        ((consp tree)
         (setf (fourth tree) (%meta-hypr-replace (fourth tree) id replacement)
               (fifth tree) (%meta-hypr-replace (fifth tree) id replacement))
         tree)
        (t tree)))

(defun %meta-hypr-content (group)
  (list (+ (subworld-x group) 16d0) (+ (subworld-y group) 16d0)
        (- (subworld-width group) 32d0) (- (subworld-height group) 32d0)))

(defun %meta-hypr-minimum (tree)
  (if (atom tree) (values 96d0 64d0)
      (multiple-value-bind (aw ah) (%meta-hypr-minimum (fourth tree))
        (multiple-value-bind (bw bh) (%meta-hypr-minimum (fifth tree))
          (if (eq :horizontal (second tree))
              (values (+ aw bw 14d0) (max ah bh))
              (values (max aw bw) (+ ah bh 14d0)))))))

(defun %meta-hypr-boxes (tree box &optional include-branches)
  (if (atom tree) (when tree (list (cons tree box)))
      (destructuring-bind (x y width height) box
        (multiple-value-bind (aw ah) (%meta-hypr-minimum (fourth tree))
          (multiple-value-bind (bw bh) (%meta-hypr-minimum (fifth tree))
            (let* ((horizontal (eq :horizontal (second tree)))
                   (span (- (if horizontal width height) 14d0))
                   (minimum (if horizontal aw ah))
                   (maximum (- span (if horizontal bw bh)))
                   (size (max minimum (min maximum (* span (third tree))))))
              (append
               (when include-branches (list (cons tree box)))
               (%meta-hypr-boxes (fourth tree) (if horizontal (list x y size height) (list x y width size))
                                 include-branches)
               (%meta-hypr-boxes (fifth tree)
                                 (if horizontal (list (+ x size 14d0) y (- span size) height)
                                     (list x (+ y size 14d0) width (- span size))) include-branches))))))))

(defun %meta-hypr-pending-ids (world group workspace)
  ;; Saved applications can reattach in any order. Keep their leaves until
  ;; adoption consumes the pending record instead of discarding their layout.
  (loop for record in (append (%meta-saved-windows world) (%meta-saved-notes world))
        for member = (getf record :member)
        when (and (eql (getf record :owner) (subworld-id group))
                  (eql (getf member :workspace) workspace))
          collect (getf member :column)))

(defun %meta-hypr-sync-tree (world group members)
  (let* ((workspace (subworld-workspace group)) (seen nil)
         (focus (and world (%meta-member group (gethash group (%meta-group-focus world))))))
    ;; Legacy state may reuse column IDs. Hyprland leaves require unique IDs.
    (dolist (member (subworld-members group))
      (when (or (not (plusp (subworld-member-column member)))
                (member (subworld-member-column member) seen))
        (setf (subworld-member-column member) (incf (subworld-next-column group))))
      (setf (subworld-next-column group) (max (subworld-next-column group) (subworld-member-column member)))
      (push (subworld-member-column member) seen))
    (let* ((ids (mapcar #'subworld-member-column members))
           (tree (%meta-hypr-prune (%meta-hypr-tree group workspace)
                                  (append (mapcar #'subworld-member-column (%meta-workspace-members group workspace))
                                          (and world (%meta-hypr-pending-ids world group workspace))))))
      (dolist (member members)
        (let ((id (subworld-member-column member)))
          (unless (member id (%meta-hypr-leaves tree))
            (let* ((leaves (%meta-hypr-leaves tree))
                   (target (or (and focus (member (subworld-member-column focus) ids)
                                    (member (subworld-member-column focus) leaves)
                                    (subworld-member-column focus)) (car (last leaves))))
                   (box (or (cdr (assoc target (%meta-hypr-boxes tree (%meta-hypr-content group))))
                            (%meta-hypr-content group))))
              (setf tree
                    (if target
                        (%meta-hypr-replace tree target
                                           (list :split (if (>= (third box) (fourth box)) :horizontal :vertical)
                                                 .5d0 target id))
                        id))))))
      (setf (%meta-hypr-tree group workspace) tree)
      ;; Layout only attached tiles; preserve pending leaves in the saved tree.
      (%meta-hypr-prune (copy-tree tree) ids))))

(defun %meta-hypr-layout (world group members)
  (let ((tree (%meta-hypr-sync-tree world group members)) (box (%meta-hypr-content group)))
    (when tree
      (multiple-value-bind (width height) (%meta-hypr-minimum tree)
        (if (or (> width (third box)) (> height (fourth box)))
            (apply #'%meta-grid-rectangles world members box)
            (dolist (entry (%meta-hypr-boxes tree box))
              (let ((member (find (car entry) members :key #'subworld-member-column)))
                (apply #'%meta-place world (subworld-member-object member) (cdr entry)))))))))

(defun %meta-hypr-path (tree id)
  (when (consp tree)
    (cond ((member id (%meta-hypr-leaves (fourth tree)))
           (cons (cons tree :first) (%meta-hypr-path (fourth tree) id)))
          ((member id (%meta-hypr-leaves (fifth tree)))
           (cons (cons tree :second) (%meta-hypr-path (fifth tree) id))))))

(defun %meta-hypr-resize (group member direction &optional (amount .04d0))
  (let* ((axis (if (member direction '(:left :right)) :horizontal :vertical))
         (path (%meta-hypr-path (%meta-hypr-tree group (subworld-member-workspace member))
                                (subworld-member-column member)))
         (entry (find axis (reverse path) :key (lambda (entry) (second (car entry))))))
    (when entry
      (let* ((node (car entry))
             (sign (* (if (member direction '(:right :down)) 1d0 -1d0)
                      (if (eq :first (cdr entry)) 1d0 -1d0))))
        (setf (third node) (max .1d0 (min .9d0 (+ (third node) (* sign amount)))))))))

(defun %meta-hypr-swap (group a b)
  (let* ((workspace (subworld-member-workspace a)) (tree (%meta-hypr-tree group workspace))
         (left (subworld-member-column a)) (right (subworld-member-column b)))
    (labels ((swap (node)
               (cond ((eql node left) right) ((eql node right) left)
                     ((consp node) (setf (fourth node) (swap (fourth node))
                                         (fifth node) (swap (fifth node))) node)
                     (t node))))
      (setf (%meta-hypr-tree group workspace) (swap tree)))))

(defun %meta-hypr-drop (group member target side)
  (let* ((workspace (subworld-member-workspace member))
         (id (subworld-member-column member)) (other (subworld-member-column target))
         (root (%meta-hypr-tree group workspace))
         (tree (%meta-hypr-prune root (remove id (%meta-hypr-leaves root))))
         (before (member side '(:left :above))))
    (when (member other (%meta-hypr-leaves tree))
      (setf (%meta-hypr-tree group workspace)
            (%meta-hypr-replace tree other
                                (list :split (if (member side '(:above :below)) :vertical :horizontal)
                                      .5d0 (if before id other) (if before other id)))))))

(defun %meta-hypr-toggle-split (world object)
  (let* ((group (object-subworld world object)) (member (and group (%meta-member group object)))
         (entry (and member (eq :hyprland (subworld-kind group))
                     (car (last (%meta-hypr-path (%meta-hypr-tree group (subworld-member-workspace member))
                                                (subworld-member-column member)))))))
    (when entry
      (setf (second (car entry)) (if (eq :horizontal (second (car entry))) :vertical :horizontal))
      (%meta-layout world group))))

(defun %meta-hypr-set-visible (world window visible-p)
  ;; Outgoing windows remain drawable while fading, but stop accepting input
  ;; immediately. Visibility multiplies presence instead of racing its channel.
  (let* ((wanted (not (null visible-p))) (destination (if wanted 1d0 0d0))
         (origin (%canvas-window-visibility-opacity window)))
    (setf (%canvas-window-input-enabled-p window) wanted)
    (when wanted (setf (%canvas-window-hidden-p window) nil))
    (flet ((present (subject values)
             (setf (%canvas-window-visibility-opacity subject) (first values))
             (when (and (zerop (first values)) (not (%canvas-window-input-enabled-p subject)))
               (setf (%canvas-window-hidden-p subject) t))
             (%update-window-membership world subject)))
      (if (or (%meta-restoring-p world) (not (%canvas-window-mapped-p window)) (= origin destination))
          (progn (%meta-cancel-motion world window :visibility)
                 (present window (list destination)))
          (%meta-animate-to world window :visibility (list origin) (list destination)
                            (if wanted .20d0 .16d0) #'present :bounds '((0d0 1d0))))))
  window)

(defun %meta-hypr-valid-tree-p (tree &optional (depth 0))
  (and (< depth 64)
       (or (null tree) (typep tree '(integer 1 1000000))
           (and (listp tree) (= 5 (length tree)) (eq :split (first tree))
                (member (second tree) '(:horizontal :vertical))
                (realp (third tree)) (<= .1d0 (third tree) .9d0)
                (%meta-hypr-valid-tree-p (fourth tree) (1+ depth))
                (%meta-hypr-valid-tree-p (fifth tree) (1+ depth))))))

(defun %meta-hypr-resize-to (group member geometry)
  (let* ((tree (%meta-hypr-tree group (subworld-member-workspace member)))
         (boxes (%meta-hypr-boxes tree (%meta-hypr-content group) t))
         (origin (cdr (assoc (subworld-member-column member) boxes)))
         (path (reverse (%meta-hypr-path tree (subworld-member-column member)))))
    (when origin
      (loop for axis in '(:horizontal :vertical) for index in '(2 3)
            for entry = (find axis path :key (lambda (entry) (second (car entry))))
            when entry do
              (let* ((node (car entry)) (box (cdr (assoc node boxes)))
                     (span (- (nth index box) 14d0))
                     (delta (- (nth index geometry) (nth index origin)))
                     (sign (if (eq :first (cdr entry)) 1d0 -1d0)))
                (when (plusp span)
                  (setf (third node) (max .1d0 (min .9d0 (+ (third node) (/ (* sign delta) span)))))))))))
