(in-package #:ataxia.infinite-world)

(defun %meta-object-geometry (object)
  (etypecase object
    (canvas-window
     (list (canvas-window-x object) (canvas-window-y object)
           (canvas-window-width object) (canvas-window-height object)))
    (agent-widget
     (or (gethash object (%meta-spatial-widgets (%agent-widget-world object)))
         (list (canvas-overlay-x object) (canvas-overlay-y object)
               (canvas-overlay-width object) (canvas-overlay-height object))))))

(defun %meta-place (world object x y width height)
  (let ((width (max 96d0 (coerce width 'double-float)))
        (height (max 64d0 (coerce height 'double-float))))
    (etypecase object
      (canvas-window
       (%damage-window world object)
       (let ((origin-x (canvas-window-x object))
             (origin-y (canvas-window-y object))
             (size-changed
               (or (/= (round width) (round (canvas-window-width object)))
                   (/= (round height) (round (canvas-window-height object))))))
         (setf (canvas-window-x object) (coerce x 'double-float)
               (canvas-window-y object) (coerce y 'double-float)
               (canvas-window-width object) width
               (canvas-window-height object) height)
         (when size-changed
           (ataxia.kernel:request-object-configuration
            (canvas-window-application object) world
            (make-instance 'ataxia.kernel:toplevel-configuration
                           :width (round width) :height (round height))))
         (when (and *meta-layout-motion* (not (%meta-restoring-p world))
                    (not (%meta-dragged-p world object))
                    (%window-visible-p object)
                    (> (+ (abs (- x origin-x)) (abs (- y origin-y))) 1d0))
           (animate-window
            world object :metaworld-layout 0.18d0
            (lambda (window progress)
              (setf (canvas-window-x window) (+ origin-x (* progress (- x origin-x)))
                    (canvas-window-y window) (+ origin-y (* progress (- y origin-y)))))
            :easing #'ataxia.world:ease-out-cubic)))
       (%damage-window world object)
       (%update-window-membership world object))
      (agent-widget
       (setf (gethash object (%meta-spatial-widgets world))
             (list (coerce x 'double-float) (coerce y 'double-float) width height))
       (let ((component (canvas-overlay-component object)))
         (unless (and (= width (ataxia.world.slint:slint-component-width component))
                      (= height (ataxia.world.slint:slint-component-height component)))
           (ataxia.world.slint:resize-slint-component component width height)))))))

(defun %meta-set-visible (world object visible-p)
  (etypecase object
    (canvas-window
     (unless (eq (not visible-p) (%canvas-window-hidden-p object))
       (%damage-window world object)
       (setf (%canvas-window-hidden-p object) (not visible-p))
       (%damage-window world object)
       (%update-window-membership world object)))
    (agent-widget
     (when (member object (world-overlays world))
       (if visible-p (show-overlay world object) (hide-overlay world object))))))

(defun %meta-stack-rectangles (world members x y width height)
  (let* ((gap 14d0)
         (usable (max 64d0 (- height (* gap (1- (length members))))))
         (total (reduce #'+ members :key #'subworld-member-weight :initial-value 0d0))
         (top y))
    (dolist (member members)
      (let ((tile-height (* usable (/ (subworld-member-weight member) total))))
        (%meta-place world (subworld-member-object member) x top width tile-height)
        (incf top (+ tile-height gap))))))

(defun %meta-layout-niri (world group members)
  (let ((left (+ (subworld-x group) 16d0))
        (top (+ (subworld-y group) 52d0))
        (height (- (subworld-height group) 68d0)))
    (dolist (column (%meta-columns group))
      (let* ((rows (remove-if-not
                    (lambda (member) (= column (subworld-member-column member)))
                    members))
             (width (subworld-member-width (first rows))))
        (dolist (member rows) (setf (subworld-member-width member) width))
        (%meta-stack-rectangles world rows left top width height)
        (incf left (+ width 14d0))))))

(defun %meta-layout-dwindle (world group members)
  (labels ((split (remaining x y width height)
             (when remaining
               (if (null (rest remaining))
                   (%meta-place world (subworld-member-object (first remaining))
                                x y width height)
                   (let ((ratio (subworld-ratio group)))
                     (if (>= width height)
                         (let ((first-width (* (- width 14d0) ratio)))
                           (%meta-place world (subworld-member-object (first remaining))
                                        x y first-width height)
                           (split (rest remaining) (+ x first-width 14d0) y
                                  (- width first-width 14d0) height))
                         (let ((first-height (* (- height 14d0) ratio)))
                           (%meta-place world (subworld-member-object (first remaining))
                                        x y width first-height)
                           (split (rest remaining) x (+ y first-height 14d0)
                                  width (- height first-height 14d0)))))))))
    (split members (+ (subworld-x group) 16d0) (+ (subworld-y group) 52d0)
           (- (subworld-width group) 32d0) (- (subworld-height group) 68d0))))

(defun %meta-layout-master (world group members)
  (when members
    (let* ((left (+ (subworld-x group) 16d0))
           (top (+ (subworld-y group) 52d0))
           (width (- (subworld-width group) 32d0))
           (height (- (subworld-height group) 68d0))
           (master-width (if (rest members) (* (- width 14d0) (subworld-ratio group))
                             width)))
      (%meta-place world (subworld-member-object (first members))
                   left top master-width height)
      (when (rest members)
        (%meta-stack-rectangles world (rest members)
                                (+ left master-width 14d0) top
                                (- width master-width 14d0) height)))))

(defun %meta-layout (world group)
  (let ((*meta-layout-motion* (not (%meta-group-drag world))))
   (when group
    (dolist (member (copy-list (subworld-members group)))
      (let ((object (subworld-member-object member)))
        (when (and (typep object 'agent-widget) (not (member object (world-overlays world))))
          (setf (subworld-members group) (remove member (subworld-members group)))
          (remhash object (%meta-owners world))
          (remhash object (%meta-spatial-widgets world)))))
    (let ((fullscreen (subworld-fullscreen group)))
      (dolist (member (subworld-members group))
        (%meta-set-visible
         world (subworld-member-object member)
         (and (= (subworld-workspace group) (subworld-member-workspace member))
              (or (null fullscreen) (eq fullscreen (subworld-member-object member))))))
      (if fullscreen
          (%meta-place world fullscreen
                       (+ (subworld-x group) 8d0) (+ (subworld-y group) 40d0)
                       (- (subworld-width group) 16d0) (- (subworld-height group) 48d0))
          (let ((members (%meta-visible-members group)))
            (case (subworld-kind group)
              (:niri (%meta-layout-niri world group members))
              (:hyprland
               (if (eq (subworld-layout group) :master)
                   (%meta-layout-master world group members)
                   (%meta-layout-dwindle world group members)))))))
    (%meta-changed world))))

(defun move-object-to-subworld (world object group &key workspace)
  (check-type world metaworld)
  (check-type object (or canvas-window agent-widget))
  (unless (or (null group) (member group (metaworld-subworlds world) :test #'eq))
    (error "Destination does not belong to this metaworld."))
  (unless (etypecase object
            (canvas-window (eq object (find-canvas-window
                                      world (canvas-window-application object))))
            (agent-widget (member object (world-overlays world))))
    (error "Object does not belong to this metaworld."))
  (let* ((previous (object-subworld world object))
         (member (and previous (%meta-member previous object))))
    (when (and (typep object 'agent-widget)
               (not (gethash object (%meta-spatial-widgets world))))
      (let ((state (gethash (canvas-overlay-output object) (%world-outputs world))))
        (multiple-value-bind (x y)
            (%screen-to-world state (canvas-overlay-x object) (canvas-overlay-y object))
          (setf (gethash object (%meta-spatial-widgets world))
                (list x y (/ (canvas-overlay-width object) (%canvas-output-zoom state))
                      (/ (canvas-overlay-height object) (%canvas-output-zoom state)))))))
    (when (eq previous group)
      (when (and member workspace)
        (setf (subworld-member-workspace member) workspace)
        (%meta-layout world group))
      (return-from move-object-to-subworld object))
    (when previous
      (setf (subworld-members previous)
            (remove member (subworld-members previous)))
      (when (eq (subworld-fullscreen previous) object)
        (setf (subworld-fullscreen previous) nil)
        (when (typep object 'canvas-window)
          (ataxia.kernel:request-object-state (canvas-window-application object) world :fullscreen nil)))
      (remhash object (%meta-owners world)))
    (%meta-set-visible world object t)
    (when group
        (let ((entry (%make-subworld-member
                      :object object :workspace (or workspace (subworld-workspace group))
                      :column (incf (subworld-next-column group))
                      :width (* 0.48d0 (- (subworld-width group) 32d0))
                      :restore-geometry (if member (subworld-member-restore-geometry member)
                                            (%meta-object-geometry object)))))
          (setf (gethash object (%meta-owners world)) group
                (subworld-members group) (append (subworld-members group) (list entry)))))
    (%meta-layout world previous)
    (%meta-layout world group)
    (%meta-changed world)
    object))

(defun %meta-fit-group (world state group &key overview-p)
  (multiple-value-bind (width height) (%output-logical-size state)
    (let* ((group-width (if overview-p (%meta-footprint-width group) (subworld-width group)))
           (margin (if (%meta-standalone world) 0d0 80d0))
           (zoom (max 0.08d0 (min 1.5d0 (/ (- width margin) group-width)
                                  (/ (- height (if (%meta-standalone world) 0d0 100d0))
                                     (subworld-height group)))))
           (scroll (if overview-p 0d0
                       (gethash (subworld-workspace group) (subworld-scrolls group) 0d0))))
      (%meta-set-camera
       world state
       (list (- (+ (subworld-x group) scroll) (/ (- width (* group-width zoom)) (* 2d0 zoom)))
             (- (subworld-y group) (/ (- height (* (subworld-height group) zoom)) (* 2d0 zoom)))
             zoom 0d0)))))

(defun %meta-focus (world object &optional seat (animate-p t))
  (let ((seat-state (%meta-seat world seat)))
    (when seat-state
      (%focus-target world seat-state object)
      (let ((group (and object (object-subworld world object)))
            (state (%canvas-seat-output seat-state)))
        (when (and group state (eq group (%meta-current world seat))
                   (eq :niri (subworld-kind group)))
          (multiple-value-bind (width height) (%output-logical-size state)
            (declare (ignore height))
            (let* ((object-x (first (%meta-object-geometry object)))
                   (object-width (third (%meta-object-geometry object)))
                   (camera-x (%canvas-output-camera-x state))
                   (visible-width (/ width (%canvas-output-zoom state)))
                   (margin (/ 34d0 (%canvas-output-zoom state)))
                   (origin (%meta-camera state)))
              (when (or (< object-x (+ camera-x margin))
                        (> (+ object-x object-width) (- (+ camera-x visible-width) margin)))
                (set-output-camera
                 world (%canvas-output-output state)
                 (- (+ object-x (/ object-width 2d0)) (/ visible-width 2d0))
                 (%canvas-output-camera-y state) (%canvas-output-zoom state)))
              (setf (gethash (subworld-workspace group) (subworld-scrolls group))
                    (max 0d0 (+ (- (%canvas-output-camera-x state) (subworld-x group))
                                (/ (- visible-width (subworld-width group)) 2d0))))
              (when animate-p (%meta-transition-camera world state origin))))))))
  (%meta-changed world)
  object)

(defun enter-subworld (world group &optional seat)
  (unless (member group (metaworld-subworlds world) :test #'eq)
    (error "Subworld does not belong to this world."))
  (let* ((seat-state (%meta-seat world seat))
         (state (if seat-state (%canvas-seat-output seat-state) (%first-output-state world)))
         (view (%meta-view-for-state world state))
         (origin (and state (%meta-camera state))))
    (when view
      (unless (%meta-view-active view)
        (setf (%meta-view-parent-camera view) (%meta-camera state)))
      (setf (%meta-view-active view) group
            (%meta-view-panel-until view) (+ (%now) 2d0))
      (%meta-fit-group world state group)
      (%meta-focus world
                   (some (lambda (member)
                           (let ((object (subworld-member-object member)))
                             (when (%target-visible-p object) object)))
                         (%meta-visible-members group :include-floating t)) seat nil)
      (%meta-transition-camera world state origin)))
  (%meta-changed world)
  group)

(defun leave-subworld (world &optional seat)
  (let* ((seat-state (%meta-seat world seat))
         (state (if seat-state (%canvas-seat-output seat-state) (%first-output-state world)))
         (view (%meta-view-for-state world state))
         (origin (and state (%meta-camera state))))
    (when (and view (%meta-view-active view))
      (setf (%meta-view-active view) nil)
      (when (%meta-view-parent-camera view)
        (%meta-set-camera world state (%meta-view-parent-camera view))
        (%meta-transition-camera world state origin))
      (setf (%meta-view-panel-until view) (+ (%now) 2d0))))
  (%meta-changed world))

(defun remove-subworld (world group)
  (when (%meta-standalone world)
    (error "A standalone world's only layout cannot be removed."))
  (dolist (state (%output-states world))
    (let ((view (%meta-view-for-state world state)))
      (when (eq group (%meta-view-active view))
        (setf (%meta-view-active view) nil)
        (when (%meta-view-parent-camera view)
          (%meta-set-camera world state (%meta-view-parent-camera view))))))
  (dolist (member (copy-list (subworld-members group)))
    (move-object-to-subworld world (subworld-member-object member) nil))
  (setf (metaworld-subworlds world) (remove group (metaworld-subworlds world)))
  (%meta-changed world))
