(in-package #:ataxia.infinite-world)

(defun %meta-window-key (window)
  (let ((application (canvas-window-application window)))
    (list (or (ataxia.kernel:application-app-id application) "")
          (or (ataxia.kernel:application-title application) ""))))

(defun %meta-member-record (member)
  (list :workspace (subworld-member-workspace member)
        :column (subworld-member-column member)
        :width (subworld-member-width member)
        :weight (subworld-member-weight member)
        :floating (subworld-member-floating-p member)
        :restore (subworld-member-restore-geometry member)))

(defun %meta-group-record (group)
  (list :id (subworld-id group) :name (subworld-name group)
        :kind (subworld-kind group) :layout (subworld-layout group)
        :x (subworld-x group) :y (subworld-y group)
        :width (subworld-width group) :height (subworld-height group)
        :workspace (subworld-workspace group) :ratio (subworld-ratio group)
        :next-column (subworld-next-column group)
        :scrolls (loop for workspace being the hash-keys of (subworld-scrolls group)
                      using (hash-value scroll) collect (list workspace scroll))))

(defun %meta-snapshot (world)
  (list
   :version 1
   :groups (mapcar #'%meta-group-record (metaworld-subworlds world))
   :windows
   (append
    (loop for window in (%world-stacking world)
          for group = (object-subworld world window)
          for member = (and group (%meta-member group window))
          collect (list :key (%meta-window-key window)
                        :geometry (%meta-object-geometry window)
                        :owner (and group (subworld-id group))
                        :order (and member (position member (subworld-members group)))
                        :member (and member (%meta-member-record member))))
    (%meta-saved-windows world))
   :notes
   (loop for object being the hash-keys of (%meta-spatial-widgets world)
         for group = (object-subworld world object)
         for member = (and group (%meta-member group object))
         when (typep object 'meta-note)
           collect (list :content (%meta-note-content object)
                         :geometry (%meta-object-geometry object)
                         :owner (and group (subworld-id group))
                         :order (and member (position member (subworld-members group)))
                         :member (and member (%meta-member-record member))))
   :cameras
   (loop for state in (%output-states world)
         for view = (%meta-view-for-state world state)
         collect
         (list :output (ataxia.kernel:output-name (%canvas-output-output state))
               :camera (%meta-camera state)
               :parent (%meta-view-parent-camera view)
               :active (and (%meta-view-active view)
                            (subworld-id (%meta-view-active view)))))))

(defun save-metaworld (world)
  (let ((path (%meta-state-file world)))
    (when (and path (not (%meta-state-error world)))
      (handler-case
          (let ((temporary (make-pathname :type "sexp.pending" :defaults path)))
            (ensure-directories-exist path)
            (with-open-file (stream temporary :direction :output
                                   :if-exists :supersede :if-does-not-exist :create)
              (with-standard-io-syntax
                (let ((*print-readably* t) (*print-pretty* t))
                  (write (%meta-snapshot world) :stream stream)
                  (terpri stream))))
            (uiop:rename-file-overwriting-target temporary path)
            (setf (%meta-save-needed-p world) nil
                  (%meta-last-save world) (%now)))
        (serious-condition (cause)
          (format *error-output* "[metaworld] State save failed: ~A~%" cause)))))
  world)

(defun %meta-valid-number-p (value &optional (minimum -10000000d0) (maximum 10000000d0))
  (and (realp value) (<= minimum value maximum)))

(defun %meta-valid-geometry-p (value)
  (and (listp value) (= 4 (length value))
       (every #'%meta-valid-number-p value)
       (%meta-valid-number-p (third value) 1 100000)
       (%meta-valid-number-p (fourth value) 1 100000)))

(defun %meta-load-group (data)
  (unless (and (integerp (getf data :id)) (plusp (getf data :id))
               (stringp (getf data :name)) (<= (length (getf data :name)) 200)
               (member (getf data :kind) '(:niri :hyprland))
               (member (getf data :layout) '(:dwindle :master))
               (%meta-valid-geometry-p
                (list (getf data :x) (getf data :y) (getf data :width) (getf data :height)))
               (typep (getf data :workspace) '(integer 1 9))
               (%meta-valid-number-p (getf data :ratio) 0.15d0 0.85d0)
               (typep (getf data :next-column) '(integer 0 1000000)))
    (error "Invalid saved subworld."))
  (let ((group
          (%make-subworld
           :id (getf data :id) :name (getf data :name) :kind (getf data :kind)
           :layout (getf data :layout) :x (coerce (getf data :x) 'double-float)
           :y (coerce (getf data :y) 'double-float)
           :width (coerce (getf data :width) 'double-float)
           :height (coerce (getf data :height) 'double-float)
           :workspace (getf data :workspace) :ratio (getf data :ratio)
           :next-column (getf data :next-column))))
    (dolist (entry (getf data :scrolls))
      (when (and (typep (first entry) '(integer 1 9))
                 (%meta-valid-number-p (second entry) 0 10000000))
        (setf (gethash (first entry) (subworld-scrolls group)) (second entry))))
    group))

(defun %meta-load-state (world)
  (let ((path (%meta-state-file world)))
    (when (and path (probe-file path))
      (handler-case
          (with-open-file (stream path)
            (when (> (file-length stream) 1048576)
              (error "State file exceeds one megabyte."))
            (let* ((*read-eval* nil)
                   (data (read stream nil nil))
                   (groups (and (eql 1 (getf data :version))
                                (mapcar #'%meta-load-group (getf data :groups)))))
              (unless (eql 1 (getf data :version)) (error "Unknown state version."))
              (when (/= (length groups)
                        (length (remove-duplicates groups :key #'subworld-id)))
                (error "Duplicate subworld identifiers."))
              (when (and (%meta-standalone world)
                         (or (/= 1 (length groups))
                             (not (eq (%meta-standalone world) (subworld-kind (first groups))))))
                (error "Saved state does not match the standalone policy."))
              (setf (metaworld-subworlds world) groups
                    (%meta-state-loaded-p world) t
                    (%meta-next-id world) (reduce #'max groups :key #'subworld-id :initial-value 0)
                    (%meta-saved-windows world) (getf data :windows)
                    (%meta-saved-notes world) (getf data :notes)
                    (%meta-saved-cameras world) (getf data :cameras))))
        (serious-condition (cause)
          (setf (%meta-state-error world) (princ-to-string cause))
          (format *error-output* "[metaworld] Preserving unreadable state ~A: ~A~%" path cause)))))
  world)

(defun %meta-restore-window (world window)
  (let* ((key (%meta-window-key window))
         (records (%meta-saved-windows world))
         (record
           (or (find key records :key (lambda (entry) (getf entry :key)) :test #'equal)
               (find (first key) records
                     :key (lambda (entry) (first (getf entry :key))) :test #'equal))))
    (when record
      (let* ((group (find (getf record :owner) (metaworld-subworlds world)
                          :key #'subworld-id))
             (geometry (getf record :geometry))
             (data (getf record :member)))
        (when (%meta-valid-geometry-p geometry)
          (apply #'%meta-place world window geometry))
        (when group
          (move-object-to-subworld world window group)
          (let ((member (%meta-member group window)))
            (when (typep (getf record :order) '(integer 0 1000000))
              (setf (subworld-member-order member) (getf record :order)))
            (when (typep (getf data :workspace) '(integer 1 9))
              (setf (subworld-member-workspace member) (getf data :workspace)))
            (when (typep (getf data :column) '(integer 0 1000000))
              (setf (subworld-member-column member) (getf data :column)))
            (when (%meta-valid-number-p (getf data :width) 96 100000)
              (setf (subworld-member-width member) (getf data :width)))
            (when (%meta-valid-number-p (getf data :weight) 0.1d0 100d0)
              (setf (subworld-member-weight member) (getf data :weight)))
            (setf (subworld-member-floating-p member) (not (null (getf data :floating))))
            (when (%meta-valid-geometry-p (getf data :restore))
              (setf (subworld-member-restore-geometry member) (getf data :restore)))
            (when (and (subworld-member-floating-p member) (%meta-valid-geometry-p geometry))
              (apply #'%meta-place world window geometry)))
          (setf (subworld-members group)
                (stable-sort (subworld-members group) #'< :key #'subworld-member-order))
          (%meta-layout world group))
        (setf (%meta-saved-windows world) (remove record records :count 1))
        t))))

(defun %meta-restore-camera (world state)
  (let* ((record (find (ataxia.kernel:output-name (%canvas-output-output state))
                       (%meta-saved-cameras world)
                       :key (lambda (entry) (getf entry :output)) :test #'equal))
         (view (%meta-view-for-state world state)))
    (when record
      (labels ((valid-camera-p (camera)
                 (and (listp camera) (= 4 (length camera))
                      (every #'%meta-valid-number-p camera)
                      (%meta-valid-number-p (third camera) 0.05d0 6d0))))
        (when (valid-camera-p (getf record :camera))
          (%meta-set-camera world state (getf record :camera)))
        (when (valid-camera-p (getf record :parent))
          (setf (%meta-view-parent-camera view) (getf record :parent)))
        (setf (%meta-view-active view)
              (find (getf record :active) (metaworld-subworlds world) :key #'subworld-id))))
    record))
