(in-package #:ataxia.infinite-world)

(defvar *meta-kernel-sessions* (make-hash-table :test #'eq :weakness :key))

(defun %meta-window-identity (world window)
  (let* ((kernel (ataxia.kernel:world-kernel world))
         (session (or (gethash kernel *meta-kernel-sessions*)
                      (setf (gethash kernel *meta-kernel-sessions*)
                            (format nil "~D-~36R" (get-universal-time)
                                    (random (expt 2 64) (make-random-state t)))))))
    (list session (ataxia.kernel:object-id (canvas-window-application window)))))

(defun %meta-window-key (window)
  (let ((application (canvas-window-application window)))
    (list (let ((id (or (ataxia.kernel:application-app-id application) "")))
            (if (uiop:string-prefix-p "foot.ataxia." id) "foot" id))
          (or (ataxia.kernel:application-title application) ""))))

(defun %meta-member-record (member)
  (list :workspace (subworld-member-workspace member)
        :column (subworld-member-column member)
        :width (subworld-member-width member)
        :weight (subworld-member-weight member)
        :floating (subworld-member-floating-p member)
        :restore (subworld-member-restore-geometry member)))

(defun %meta-group-record (group)
  (list :id (subworld-id group) :name (subworld-name group)
        :kind (subworld-kind group) :layout (subworld-layout group)
        :x (subworld-x group) :y (subworld-y group)
        :width (subworld-width group) :height (subworld-height group)
        :workspace (subworld-workspace group) :workspace-count (%meta-workspace-count group) :ratio (subworld-ratio group)
        :next-column (subworld-next-column group)
        :splits (let ((table (gethash group *meta-hypr-trees*)))
                  (when table (loop for workspace being the hash-keys of table using (hash-value tree)
                                    collect (list workspace (copy-tree tree)))))
        :scrolls (loop for workspace being the hash-keys of (subworld-scrolls group)
                      using (hash-value scroll) collect (list workspace scroll))))

(defun %meta-snapshot (world)
  (list
   :version 1
   :groups (mapcar #'%meta-group-record (metaworld-subworlds world))
   :windows
   (append
    (loop for window in (%world-stacking world)
          for group = (object-subworld world window)
          for member = (and group (%meta-member group window))
          collect (list :key (%meta-window-key window)
                        :identity (%meta-window-identity world window)
                        :geometry (%meta-object-geometry window)
                        :owner (and group (subworld-id group))
                        :order (and member (position member (subworld-members group)))
                        :member (and member (%meta-member-record member))))
    (%meta-saved-windows world))
   :notes
   (loop for object being the hash-keys of (%meta-spatial-widgets world)
         for group = (object-subworld world object)
         for member = (and group (%meta-member group object))
         when (typep object 'meta-note)
           collect (list :content (%meta-note-content object)
                         :geometry (%meta-object-geometry object)
                         :owner (and group (subworld-id group))
                         :order (and member (position member (subworld-members group)))
                         :member (and member (%meta-member-record member))))
   :cameras
   (loop for state in (%output-states world)
         for view = (%meta-view-for-state world state)
         collect
         (list :output (ataxia.kernel:output-name (%canvas-output-output state))
               :camera (%meta-camera state)
               :position (list (%canvas-output-layout-x state) (%canvas-output-layout-y state))
               :parent (%meta-view-parent-camera view)
               :active (and (%meta-view-active view)
                            (subworld-id (%meta-view-active view)))))))

(defvar *meta-save-mailbox* nil)
(defvar *meta-save-wakeup* (sb-thread:make-semaphore :count 0))
(defvar *meta-save-worker* nil)
(defvar *meta-save-busy-p* nil)
;; Owner-thread cache makes mode switches see the latest queued snapshot even
;; when the disk writer has not committed it yet. Never accessed by the worker.
(defvar *meta-save-snapshots* (make-hash-table :test #'equal))

(defun %meta-copy-snapshot (value)
  (typecase value
    (cons (cons (%meta-copy-snapshot (car value)) (%meta-copy-snapshot (cdr value))))
    (string (copy-seq value))
    (t value)))

(defun %meta-write-snapshot (path snapshot)
  (let ((temporary (make-pathname :type "sexp.pending" :defaults path)))
    (ensure-directories-exist path)
    (with-open-file (stream temporary :direction :output
                           :if-exists :supersede :if-does-not-exist :create)
      (with-standard-io-syntax
        (let ((*print-readably* t) (*print-pretty* t))
          (write snapshot :stream stream)
          (terpri stream))))
    (uiop:rename-file-overwriting-target temporary path)))

(defun %meta-queue-save (path snapshot)
  ;; Immutable latest-value mailbox: one pending snapshot per path. Neither
  ;; filesystem work nor waiting for the writer happens on the owner thread.
  (loop for old = *meta-save-mailbox*
        for new = (acons path snapshot (remove path old :key #'car :test #'equal))
        when (eq old (sb-ext:compare-and-swap *meta-save-mailbox* old new))
          do (when (null old) (sb-thread:signal-semaphore *meta-save-wakeup*))
             (return snapshot)))

(defun %meta-save-worker-loop ()
  (loop
    (sb-thread:wait-on-semaphore *meta-save-wakeup*)
    (setf *meta-save-busy-p* t)
    (unwind-protect
         (let ((batch (loop for old = *meta-save-mailbox*
                            when (eq old (sb-ext:compare-and-swap *meta-save-mailbox* old nil))
                              return old)))
           (dolist (entry batch)
             (handler-case (%meta-write-snapshot (car entry) (cdr entry))
               (serious-condition (cause)
                 (format *error-output* "[metaworld] State save failed: ~A~%" cause)))))
      (setf *meta-save-busy-p* nil))))

(defun %meta-flush-saves ()
  "Drain saves only after the compositor event loop and Kernel have stopped."
  (loop while (or *meta-save-mailbox* *meta-save-busy-p*) do (sleep 0.01)))

;; One process-lifetime writer serializes saves across World replacements.
;; It retains copied data only, and never calls World, Wayland or GLES.
(unless (and *meta-save-worker* (sb-thread:thread-alive-p *meta-save-worker*))
  (setf *meta-save-worker*
        (sb-thread:make-thread #'%meta-save-worker-loop :name "Ataxia state writer")))

(defun save-metaworld (world)
  "Queue a copied state snapshot; completion of the disk write is asynchronous."
  (let ((path (%meta-state-file world)))
    (when (and path (not (%meta-state-error world)))
      (let* ((key (namestring path))
             (snapshot (%meta-copy-snapshot (%meta-snapshot world))))
        (setf (gethash key *meta-save-snapshots*) snapshot)
        (%meta-queue-save key snapshot)
        (setf (%meta-save-needed-p world) nil
              (%meta-last-save world) (%now)))))
  world)

(defun %meta-read-state (path)
  (or (%meta-copy-snapshot (gethash (namestring path) *meta-save-snapshots*))
      (with-open-file (stream path)
        (when (> (file-length stream) 1048576)
          (error "State file exceeds one megabyte."))
        (let ((*read-eval* nil)) (read stream nil nil)))))

(defun %meta-valid-number-p (value &optional (minimum -10000000d0) (maximum 10000000d0))
  (and (realp value) (<= minimum value maximum)))

(defun %meta-valid-geometry-p (value)
  (and (listp value) (= 4 (length value))
       (every #'%meta-valid-number-p value)
       (%meta-valid-number-p (third value) 1 100000)
       (%meta-valid-number-p (fourth value) 1 100000)))

(defun %meta-load-group (data)
  (unless (and (integerp (getf data :id)) (plusp (getf data :id))
               (stringp (getf data :name)) (<= (length (getf data :name)) 200)
               (member (getf data :kind) '(:niri :hyprland))
               (member (getf data :layout) '(:dwindle :master))
               (%meta-valid-geometry-p
                (list (getf data :x) (getf data :y) (getf data :width) (getf data :height)))
               (typep (getf data :workspace) '(integer 1 9))
               (%meta-valid-number-p (getf data :ratio) 0.15d0 0.85d0)
               (typep (getf data :next-column) '(integer 0 1000000)))
    (error "Invalid saved subworld."))
  (let ((group
          (%make-subworld
           :id (getf data :id) :name (getf data :name) :kind (getf data :kind)
           :layout (getf data :layout) :x (coerce (getf data :x) 'double-float)
           :y (coerce (getf data :y) 'double-float)
           :width (coerce (getf data :width) 'double-float)
           :height (coerce (getf data :height) 'double-float)
           :workspace (getf data :workspace) :ratio (getf data :ratio)
           :next-column (getf data :next-column))))
    (let ((count (getf data :workspace-count (subworld-workspace group))))
      (unless (typep count '(integer 1 9)) (error "Invalid workspace count."))
      (setf (gethash group *meta-workspace-counts*) count))
    (dolist (entry (getf data :splits))
      (unless (and (listp entry) (= 2 (length entry))
                   (typep (first entry) '(integer 1 9)) (%meta-hypr-valid-tree-p (second entry))
                   (= (length (%meta-hypr-leaves (second entry)))
                      (length (remove-duplicates (%meta-hypr-leaves (second entry))))))
        (error "Invalid saved Hyprland split tree."))
      (setf (%meta-hypr-tree group (first entry)) (copy-tree (second entry))))
    (dolist (entry (getf data :scrolls))
      (when (and (typep (first entry) '(integer 1 9))
                 (%meta-valid-number-p (second entry) 0 10000000))
        (setf (gethash (first entry) (subworld-scrolls group)) (second entry))))
    group))

(defun %meta-migrate-workspace-pages (data groups)
  ;; Older state files placed all workspaces at the same Y. Translate their
  ;; geometry and active camera once when adopting the vertical-page layout.
  (dolist (group groups)
    (let ((record (find (subworld-id group) (getf data :groups)
                        :key (lambda (entry) (getf entry :id)))))
      (when (and (eq :niri (subworld-kind group)) (not (getf record :workspace-count)))
        (dolist (object (append (getf data :windows) (getf data :notes)))
          (let* ((member (getf object :member)) (workspace (getf member :workspace)))
            (when (and (eql (subworld-id group) (getf object :owner))
                       (typep workspace '(integer 1 9)))
              (let ((offset (- (%meta-workspace-y group workspace) (subworld-y group))))
                (dolist (geometry (list (getf object :geometry) (getf member :restore)))
                  (when (%meta-valid-geometry-p geometry) (incf (second geometry) offset)))))))
        (dolist (view (getf data :cameras))
          (let ((camera (getf view :camera)))
            (when (and (eql (getf view :active) (subworld-id group))
                       (listp camera) (= 4 (length camera)) (%meta-valid-number-p (second camera)))
              (incf (second camera) (- (%meta-workspace-y group) (subworld-y group))))))
        (nconc record (list :workspace-count (%meta-workspace-count group))))))
  data)

(defun %meta-load-state (world)
  (let ((path (%meta-state-file world)))
    (when (and path (or (gethash (namestring path) *meta-save-snapshots*)
                        (probe-file path)))
      (handler-case
          (let* ((data (%meta-read-state path))
                 (groups (and (eql 1 (getf data :version))
                              (mapcar #'%meta-load-group (getf data :groups)))))
            (unless (eql 1 (getf data :version)) (error "Unknown state version."))
            (when (/= (length groups)
                      (length (remove-duplicates groups :key #'subworld-id)))
              (error "Duplicate subworld identifiers."))
            (when (and (%meta-standalone world)
                       (or (/= 1 (length groups))
                           (not (eq (%meta-standalone world) (subworld-kind (first groups))))))
              (error "Saved state does not match the standalone policy."))
            (%meta-migrate-workspace-pages data groups)
            (setf (metaworld-subworlds world) groups
                  (%meta-state-loaded-p world) t
                  (%meta-next-id world) (reduce #'max groups :key #'subworld-id :initial-value 0)
                  (%meta-saved-windows world) (getf data :windows)
                  (%meta-saved-notes world) (getf data :notes)
                  (%meta-saved-cameras world) (getf data :cameras)))
        (serious-condition (cause)
          (setf (%meta-state-error world) (princ-to-string cause))
          (format *error-output* "[metaworld] Preserving unreadable state ~A: ~A~%" path cause)))))
  world)

(defun %meta-restore-window (world window)
  (let* ((key (%meta-window-key window))
         (identity (%meta-window-identity world window))
         (records (%meta-saved-windows world))
         (record
           (or (find identity records :key (lambda (entry) (getf entry :identity)) :test #'equal)
               (find key records :key (lambda (entry) (getf entry :key)) :test #'equal)
               (find (first key) records
                     :key (lambda (entry) (first (getf entry :key))) :test #'equal))))
    (when record
      (let* ((group (find (getf record :owner) (metaworld-subworlds world)
                          :key #'subworld-id))
             (geometry (getf record :geometry))
             (data (getf record :member)))
        (when (%meta-valid-geometry-p geometry)
          (apply #'%meta-place world window geometry))
        (when group
          (move-object-to-subworld world window group)
          (let ((member (%meta-member group window)))
            (when (typep (getf record :order) '(integer 0 1000000))
              (setf (subworld-member-order member) (getf record :order)))
            (when (typep (getf data :workspace) '(integer 1 9))
              (setf (subworld-member-workspace member) (getf data :workspace)))
            (when (typep (getf data :column) '(integer 0 1000000))
              (setf (subworld-member-column member) (getf data :column)))
            (when (%meta-valid-number-p (getf data :width) 96 100000)
              (setf (subworld-member-width member) (getf data :width)))
            (when (%meta-valid-number-p (getf data :weight) 0.1d0 100d0)
              (setf (subworld-member-weight member) (getf data :weight)))
            (setf (subworld-member-floating-p member) (not (null (getf data :floating))))
            (when (%meta-valid-geometry-p (getf data :restore))
              (setf (subworld-member-restore-geometry member) (getf data :restore)))
            (when (and (subworld-member-floating-p member) (%meta-valid-geometry-p geometry))
              (apply #'%meta-place world window geometry)))
          (setf (subworld-members group)
                (stable-sort (subworld-members group) #'< :key #'subworld-member-order))
          (%meta-layout world group))
        (setf (%meta-saved-windows world) (remove record records :count 1))
        t))))

(defun %meta-restore-camera (world state)
  (let* ((record (find (ataxia.kernel:output-name (%canvas-output-output state))
                       (%meta-saved-cameras world)
                       :key (lambda (entry) (getf entry :output)) :test #'equal))
         (view (%meta-view-for-state world state)))
    (when record
      (let ((position (getf record :position)))
        (when (and (listp position) (= 2 (length position))
                   (every (lambda (n) (%meta-valid-number-p n -100000 100000)) position))
          (set-output-position world (%canvas-output-output state) (first position) (second position))))
      (labels ((valid-camera-p (camera)
                 (and (listp camera) (= 4 (length camera))
                      (every #'%meta-valid-number-p camera)
                      (%meta-valid-number-p (third camera) 0.08d0 8d0))))
        (when (valid-camera-p (getf record :camera))
          (%meta-set-camera world state (getf record :camera)))
        (when (valid-camera-p (getf record :parent))
          (setf (%meta-view-parent-camera view) (getf record :parent)))
        (setf (%meta-view-active view)
              (find (getf record :active) (metaworld-subworlds world) :key #'subworld-id))))
    record))
