(in-package #:ataxia.infinite-world)

(defvar *meta-property-cache* (make-hash-table :test #'eq :weakness :key))

(defclass meta-chrome-widget (ataxia.world.web.ui:document-widget)
  ((present-p :initform nil :accessor %meta-chrome-present-p)))

(defclass meta-title-widget (meta-chrome-widget) ())
(defmethod %overlay-below-windows-p ((widget meta-title-widget)) t)

(defstruct (%meta-chrome (:constructor %make-meta-chrome))
  edge-since)

(defun %meta-chrome-for-state (world state)
  (or (gethash state (%meta-chrome-states world))
      (setf (gethash state (%meta-chrome-states world)) (%make-meta-chrome))))

(defmethod overlay-input-enabled-p ((widget meta-chrome-widget))
  (%meta-chrome-present-p widget))

(defmethod destroy-overlay :before ((widget agent-widget))
  (let ((world (agent-widget-world widget)))
    (when (typep world 'metaworld)
      (ataxia.world:cancel-subject-animations (%world-animator world) widget)
      (remhash widget (%meta-motions world)))))

(defun %meta-ui-widget (world name component state width height &key (layer 1200))
  (ataxia.world:create-agent-widget
   (if (string= name "header") 'meta-title-widget 'meta-chrome-widget) world ""
   :component-factory (lambda (&rest args) (apply #'ataxia.world.web.ui:make-ui-component :world world args))
   :source-path (namestring (asdf:system-relative-pathname "ataxia-metaworld" (format nil "src/worlds/metaworld/~A.html" name))) :component-name component
   :output (%canvas-output-output state) :width width :height height :layer layer
   :visible-p nil :opacity 0d0))

(defun %meta-present-ui (world widget wanted &optional (opacity 1d0))
  (when widget
    (setf (%meta-chrome-present-p widget) (not (null wanted)))
    (when wanted (show-overlay world widget))
    (unless wanted
      (dolist (seat (%seat-states world))
        (when (eq widget (%canvas-seat-focused seat))
          (let ((previous (%canvas-seat-previous-focus seat)))
            (%focus-target world seat (when (%target-visible-p previous) previous))))))
    (let ((destination (if wanted opacity 0d0)))
      (when (= destination (overlay-opacity widget))
        (%meta-cancel-motion world widget :chrome)
        (unless wanted (hide-overlay world widget)))
      (unless (= destination (overlay-opacity widget))
        (%meta-animate-to
         world widget :chrome (list (overlay-opacity widget)) (list destination)
         (if wanted 0.16d0 0.12d0)
         (lambda (target value)
           (%damage-overlay world target)
           (setf (overlay-opacity target) (first value))
           (when (and (zerop (first value)) (not (%meta-chrome-present-p target)))
             (hide-overlay world target))
           (%damage-overlay world target))
         :bounds '((0d0 1d0)))))
    widget))

(defun %meta-pointer-in-ui-p (seat widget)
  (and seat widget (overlay-input-enabled-p widget) (overlay-visible-p widget)
       (<= (overlay-x widget) (%canvas-seat-x seat)
           (+ (overlay-x widget) (overlay-width widget)))
       (<= (overlay-y widget) (%canvas-seat-y seat)
           (+ (overlay-y widget) (overlay-height widget)))))

(defvar *meta-dismissed-chrome* (make-hash-table :test #'eq :weakness :key))

(defun %meta-suppress-hover (world state)
  (let ((seat (find state (%seat-states world) :key #'%canvas-seat-output)))
    (when seat
      (setf (gethash state *meta-dismissed-chrome*)
            (list seat (%canvas-seat-x seat) (%canvas-seat-y seat))))))

(defun %meta-hover-suppressed-p (world state)
  (let* ((saved (gethash state *meta-dismissed-chrome*))
         (seat (find state (%seat-states world) :key #'%canvas-seat-output)))
    (when saved
      (if (and (eq seat (first saved))
               (< (+ (abs (- (%canvas-seat-x seat) (second saved)))
                     (abs (- (%canvas-seat-y seat) (third saved)))) 4d0))
          t
          (progn (remhash state *meta-dismissed-chrome*) nil)))))

(defun %meta-update-toolbar-intent (world state)
  (let* ((chrome (%meta-chrome-for-state world state))
         (view (%meta-view-for-state world state))
         (seat (find state (%seat-states world) :key #'%canvas-seat-output))
         (now (%now)))
    (multiple-value-bind (width height) (%output-logical-size state)
      (declare (ignore height))
      (cond
        ((or (null seat) (%meta-hover-suppressed-p world state)
             (%canvas-seat-operation seat) (%meta-group-drag world)
             (< now (%meta-view-hover-after view)))
         (setf (%meta-chrome-edge-since chrome) nil (%meta-view-panel-until view) 0d0))
        ((%meta-pointer-in-ui-p seat (%meta-view-panel view))
         (setf (%meta-view-panel-until view) (+ now 0.6d0)))
        ((and (<= (%canvas-seat-y seat) 8d0)
              (<= (abs (- (%canvas-seat-x seat) (/ width 2d0))) 90d0))
         (unless (%meta-chrome-edge-since chrome) (setf (%meta-chrome-edge-since chrome) now))
         (when (>= (- now (%meta-chrome-edge-since chrome)) 0.35d0)
           (setf (%meta-view-panel-until view) (+ now 0.6d0))))
        (t (setf (%meta-chrome-edge-since chrome) nil)))))
  world)

(defun %meta-property (widget name value)
  (let* ((component (overlay-component widget))
         (cache (or (gethash component *meta-property-cache*)
                    (setf (gethash component *meta-property-cache*)
                          (make-hash-table :test #'equal)))))
    (unless (equal (gethash name cache :absent) value)
      (setf (gethash name cache) value)
      (set-agent-widget-property widget name value))))

(defun %meta-reposition-ui (world widget x y width height)
  (ataxia.world:position-widget world widget x y width height))

(defun %meta-focused-object (world &optional seat)
  (let* ((state (%meta-seat world seat))
         (focused (and state (%canvas-seat-focused state)))
         (previous (and state (%canvas-seat-previous-focus state))))
    (flet ((object-p (object)
             (and (%target-visible-p object)
                  (or (typep object 'canvas-window)
                      (and (typep object 'agent-widget)
                           (gethash object (%meta-spatial-widgets world)))))))
      (cond ((object-p focused) focused)
            ((and (typep focused 'ui-overlay) (object-p previous)) previous)
            (t nil)))))

(defun %meta-header (world state group)
  (let* ((view (%meta-view-for-state world state))
         (headers (%meta-view-headers view)))
    (or (gethash group headers)
        (let ((widget (%meta-ui-widget world "header" "SubworldHeader" state 330d0 16d0 :layer 100)))
          (bind-agent-widget-event
           widget "enter"
           (lambda (source event)
             (declare (ignore event))
             (let ((*meta-action-seat* (ataxia.world.web.ui:input-seat (overlay-component source))))
             (if (eq group (%meta-view-active view))
                 (if (%meta-standalone world)
                     (%meta-command world *meta-action-seat* "mode-canvas")
                     (leave-subworld world *meta-action-seat*))
                 (enter-subworld world group *meta-action-seat*)))))
          (setf (gethash group headers) widget)))))

(defun %meta-toolbar (world state)
  (let ((view (%meta-view-for-state world state)))
    (or (%meta-view-panel view)
        (let ((widget (%meta-ui-widget world "toolbar" "MetaworldToolbar" state 760d0 18d0)))
          (bind-agent-widget-event
           widget "action"
           (lambda (source event)
             (%meta-command world (ataxia.world.web.ui:input-seat (overlay-component source)) (agent-widget-event-value event))))
          (setf (%meta-view-panel view) widget)))))

(defun %meta-prune-widgets (world)
  (let ((overlays (world-overlays world)))
    (dolist (widget (loop for widget being the hash-keys of (%meta-spatial-widgets world)
                         unless (member widget overlays) collect widget))
      (let ((group (object-subworld world widget)))
        (remhash widget (%meta-spatial-widgets world))
        (remhash widget (%meta-owners world))
        (when (eq widget (getf (%meta-group-drag world) :subject))
          (setf (%meta-group-drag world) nil))
        (dolist (seat-state (%seat-states world))
          (when (eq widget (%canvas-seat-previous-focus seat-state))
            (setf (%canvas-seat-previous-focus seat-state) nil)))
        (when group
          (setf (subworld-members group)
                (remove widget (subworld-members group) :key #'subworld-member-object))
          (when (eq widget (subworld-fullscreen group)) (setf (subworld-fullscreen group) nil))
          (when (eq widget (gethash group (%meta-group-focus world)))
            (remhash group (%meta-group-focus world)))
          (%meta-layout world group))))
    (loop for view being the hash-values of (%meta-views world)
          do (when (and (%meta-view-panel view) (not (member (%meta-view-panel view) overlays)))
               (setf (%meta-view-panel view) nil))
             (dolist (group (loop for group being the hash-keys of (%meta-view-headers view)
                                 using (hash-value widget)
                                 unless (member widget overlays) collect group))
               (remhash group (%meta-view-headers view)))))
  world)

(defun %meta-sync-ui (world state)
  (%meta-prune-widgets world)
  (%meta-update-toolbar-intent world state)
  (let* ((view (%meta-view-for-state world state))
         (active (%meta-view-active view))
         (panel (or (%meta-view-panel view)
                    (when (> (%meta-view-panel-until view) (%now)) (%meta-toolbar world state)))))
    (when panel
    (multiple-value-bind (width height) (%output-logical-size state)
      (declare (ignore height))
      (let ((panel-width (min (if active 480d0 340d0) (- width 24d0))))
        (%meta-reposition-ui world panel (/ (- width panel-width) 2d0) 8d0 panel-width 18d0)))
    (%meta-property panel "caption"
                    (if active (subworld-name active) "Canvas"))
    (%meta-property panel "active" (not (null active)))
    (%meta-property panel "standalone" (not (null (%meta-standalone world))))
    (%meta-property panel "workspace" (if active (subworld-workspace active) 1))
    (%meta-present-ui world panel (> (%meta-view-panel-until view) (%now))))
    (dolist (group (metaworld-subworlds world))
      (let ((header (%meta-header world state group)))
        (if (eq group active)
            ;; Keep the breadcrumb reachable when the canvas header is offscreen.
            (multiple-value-bind (width height) (%output-logical-size state)
              (declare (ignore height))
              (%meta-reposition-ui world header 12d0 8d0 (max 96d0 (min 248d0 (- width 24d0))) 16d0))
            (multiple-value-bind (canvas-x canvas-y)
                (%world-to-canvas state (subworld-x group) (subworld-y group))
              (multiple-value-bind (x y) (%canvas-to-screen state canvas-x canvas-y)
                (%meta-reposition-ui world header x (- y 16d0)
                                     (min 280d0 (max 100d0 (* (%canvas-output-zoom state)
                                                             (%meta-footprint-width group)))) 16d0))))
        (%meta-property header "caption"
                        (subworld-name group))
        (%meta-property header "active" (eq group active))
        (%meta-present-ui world header
                          (if (eq group active)
                              (not (and panel (overlay-input-enabled-p panel)))
                              (not (%meta-standalone world)))
                          (if (eq group active) 1d0 0.8d0))))
    (dolist (group (loop for group being the hash-keys of (%meta-view-headers view)
                        unless (member group (metaworld-subworlds world)) collect group))
      (remove-agent-widget world (gethash group (%meta-view-headers view)))
      (remhash group (%meta-view-headers view)))
    (maphash
     (lambda (widget geometry)
       (when (eq (overlay-output widget) (%canvas-output-output state))
         (destructuring-bind (x y width height) geometry
           (multiple-value-bind (canvas-x canvas-y) (%world-to-canvas state x y)
             (multiple-value-bind (screen-x screen-y) (%canvas-to-screen state canvas-x canvas-y)
               (let ((zoom (%canvas-output-zoom state)))
                 (unless (and (= screen-x (overlay-x widget))
                              (= screen-y (overlay-y widget))
                              (= (* zoom width) (overlay-width widget))
                              (= (* zoom height) (overlay-height widget)))
                   (%damage-overlay world widget)
                   (setf (overlay-x widget) screen-x
                         (overlay-y widget) screen-y
                         (overlay-width widget) (* zoom width)
                         (overlay-height widget) (* zoom height))
                   (%damage-overlay world widget))))))))
     (%meta-spatial-widgets world)))
  (%meta-schedule-maintenance world)
  world)

(defun %meta-transient-ui-active-p (world)
  (loop for view being the hash-values of (%meta-views world)
        thereis (and (%meta-view-panel view) (overlay-input-enabled-p (%meta-view-panel view)))))

(defun %meta-dismiss-transient-ui (world)
  (maphash (lambda (state chrome)
             (declare (ignore chrome))
             (let ((view (%meta-view-for-state world state)))
               (%meta-suppress-hover world state)
               (setf (%meta-view-panel-until view) 0d0)
               (%meta-present-ui world (%meta-view-panel view) nil)))
           (%meta-chrome-states world))
  world)

(defun %meta-new-note (world &optional group content geometry)
  (let* ((seat-state (%meta-seat world *meta-action-seat*))
         (state (or (and seat-state (%canvas-seat-output seat-state)) (%first-output-state world)))
         (widget (ataxia.world:create-agent-widget
                  'meta-note world ""
                  :component-factory (lambda (&rest args) (apply #'ataxia.world.web.ui:make-ui-component :world world args))
                  :source-path (namestring (asdf:system-relative-pathname "ataxia-metaworld" "src/worlds/metaworld/note.html"))
                  :component-name "MetaworldNote" :output (%canvas-output-output state)
                  :width 430d0 :height 320d0 :layer 20)))
    (setf (%meta-note-content widget)
          (or content ""))
    (%meta-property widget "content" (%meta-note-content widget))
    (bind-agent-widget-event
     widget "edited"
     (lambda (source event)
       (setf (%meta-note-content source) (agent-widget-event-value event))
       (%meta-changed world)))
    (bind-agent-widget-event
     widget "close"
     (lambda (source event)
       (declare (ignore event))
       (let ((seat (ataxia.world.web.ui:input-seat (overlay-component source))))
         (%meta-focus world source seat)
         (%meta-command world seat "close"))))
    (setf (gethash widget (%meta-spatial-widgets world))
          (or geometry (list (+ (%canvas-output-camera-x state) 120d0)
                             (+ (%canvas-output-camera-y state) 150d0) 430d0 320d0)))
    (when group (move-object-to-subworld world widget group))
    (%meta-changed world)
    widget))

(defmethod %map-region-widgets ((world metaworld) function)
  (maphash (lambda (widget geometry)
             (when (and (overlay-visible-p widget) (overlay-input-enabled-p widget))
               (apply function (overlay-component widget) geometry)))
           (%meta-spatial-widgets world)))
