(in-package #:ataxia.infinite-world)

(defvar *meta-property-cache* (make-hash-table :test #'eq :weakness :key))

(defclass meta-chrome-widget (agent-widget)
  ((present-p :initform nil :accessor %meta-chrome-present-p)))

(defclass meta-title-widget (meta-chrome-widget) ())
(defmethod %overlay-below-windows-p ((widget meta-title-widget)) t)

(defstruct (%meta-chrome (:constructor %make-meta-chrome))
  edge-since window-since candidate)

(defun %meta-chrome-for-state (world state)
  (or (gethash state (%meta-chrome-states world))
      (setf (gethash state (%meta-chrome-states world)) (%make-meta-chrome))))

(defmethod overlay-input-enabled-p ((widget meta-chrome-widget))
  (%meta-chrome-present-p widget))

(defmethod destroy-overlay :before ((widget agent-widget))
  (let ((world (agent-widget-world widget)))
    (when (typep world 'metaworld)
      (ataxia.world:cancel-subject-animations (%world-animator world) widget)
      (remhash widget (%meta-motions world)))))

(defun %meta-ui-widget (world name component state width height &key (layer 1200))
  (ataxia.world:create-agent-widget
   (if (string= name "header") 'meta-title-widget 'meta-chrome-widget) world ""
   :component-factory #'ataxia.world.slint:make-slint-component
   :source-path (format nil "ataxia-builtin:~A" name) :component-name component
   :output (%canvas-output-output state) :width width :height height :layer layer
   :visible-p nil :opacity 0d0))

(defun %meta-present-ui (world widget wanted &optional (opacity 1d0))
  (when widget
    (setf (%meta-chrome-present-p widget) (not (null wanted)))
    (when wanted (show-overlay world widget))
    (unless wanted
      (dolist (seat (%seat-states world))
        (when (eq widget (%canvas-seat-focused seat))
          (let ((previous (%canvas-seat-previous-focus seat)))
            (%focus-target world seat (when (%target-visible-p previous) previous))))))
    (let ((destination (if wanted opacity 0d0)))
      (when (= destination (overlay-opacity widget))
        (%meta-cancel-motion world widget :chrome)
        (unless wanted (hide-overlay world widget)))
      (unless (= destination (overlay-opacity widget))
        (%meta-animate-to
         world widget :chrome (list (overlay-opacity widget)) (list destination)
         (if wanted 0.16d0 0.12d0)
         (lambda (target value)
           (%damage-overlay world target)
           (setf (overlay-opacity target) (first value))
           (when (and (zerop (first value)) (not (%meta-chrome-present-p target)))
             (hide-overlay world target))
           (%damage-overlay world target))
         :bounds '((0d0 1d0)))))
    widget))

(defun %meta-pointer-in-ui-p (seat widget)
  (and seat widget (overlay-input-enabled-p widget) (overlay-visible-p widget)
       (<= (overlay-x widget) (%canvas-seat-x seat)
           (+ (overlay-x widget) (overlay-width widget)))
       (<= (overlay-y widget) (%canvas-seat-y seat)
           (+ (overlay-y widget) (overlay-height widget)))))

(defvar *meta-dismissed-chrome* (make-hash-table :test #'eq :weakness :key))

(defun %meta-suppress-hover (world state)
  (let ((seat (find state (%seat-states world) :key #'%canvas-seat-output)))
    (when seat
      (setf (gethash state *meta-dismissed-chrome*)
            (list seat (%canvas-seat-x seat) (%canvas-seat-y seat))))))

(defun %meta-hover-suppressed-p (world state)
  (let* ((saved (gethash state *meta-dismissed-chrome*))
         (seat (find state (%seat-states world) :key #'%canvas-seat-output)))
    (when saved
      (if (and (eq seat (first saved))
               (< (+ (abs (- (%canvas-seat-x seat) (second saved)))
                     (abs (- (%canvas-seat-y seat) (third saved)))) 4d0))
          t
          (progn (remhash state *meta-dismissed-chrome*) nil)))))

(defun %meta-update-toolbar-intent (world state)
  (let* ((chrome (%meta-chrome-for-state world state))
         (view (%meta-view-for-state world state))
         (seat (find state (%seat-states world) :key #'%canvas-seat-output))
         (now (%now)))
    (multiple-value-bind (width height) (%output-logical-size state)
      (declare (ignore height))
      (cond
        ((or (null seat) (%meta-hover-suppressed-p world state)
             (%canvas-seat-operation seat) (%meta-group-drag world)
             (and (%meta-menu world) (overlay-input-enabled-p (%meta-menu world)))
             (< now (%meta-view-hover-after view)))
         (setf (%meta-chrome-edge-since chrome) nil (%meta-view-panel-until view) 0d0))
        ((%meta-pointer-in-ui-p seat (%meta-view-panel view))
         (setf (%meta-view-panel-until view) (+ now 0.6d0)))
        ((and (<= (%canvas-seat-y seat) 8d0)
              (<= (abs (- (%canvas-seat-x seat) (/ width 2d0))) 90d0))
         (unless (%meta-chrome-edge-since chrome) (setf (%meta-chrome-edge-since chrome) now))
         (when (>= (- now (%meta-chrome-edge-since chrome)) 0.35d0)
           (setf (%meta-view-panel-until view) (+ now 0.6d0))))
        (t (setf (%meta-chrome-edge-since chrome) nil)))))
  world)

(defun %meta-property (widget name value)
  (let* ((component (overlay-component widget))
         (cache (or (gethash component *meta-property-cache*)
                    (setf (gethash component *meta-property-cache*)
                          (make-hash-table :test #'equal)))))
    (unless (equal (gethash name cache :absent) value)
      (setf (gethash name cache) value)
      (set-agent-widget-property widget name value))))

(defun %meta-reposition-ui (world widget x y width height)
  (ataxia.world:position-widget world widget x y width height))

(defun %meta-focused-object (world &optional seat)
  (let* ((state (%meta-seat world seat))
         (focused (and state (%canvas-seat-focused state)))
         (previous (and state (%canvas-seat-previous-focus state))))
    (flet ((object-p (object)
             (and (%target-visible-p object)
                  (or (typep object 'canvas-window)
                      (and (typep object 'agent-widget)
                           (gethash object (%meta-spatial-widgets world)))))))
      (cond ((object-p focused) focused)
            ((and (typep focused 'ui-overlay) (object-p previous)) previous)
            (t nil)))))

(defun %meta-header (world state group)
  (let* ((view (%meta-view-for-state world state))
         (headers (%meta-view-headers view)))
    (or (gethash group headers)
        (let ((widget (%meta-ui-widget world "header" "SubworldHeader" state 330d0 30d0 :layer 100)))
          (bind-agent-widget-event
           widget "enter"
           (lambda (source event)
             (declare (ignore source event))
             (if (eq group (%meta-view-active view))
                 (if (%meta-standalone world)
                     (%meta-command world *meta-action-seat* "mode-canvas")
                     (leave-subworld world *meta-action-seat*))
                 (enter-subworld world group *meta-action-seat*))))
          (setf (gethash group headers) widget)))))

(defun %meta-toolbar (world state)
  (let ((view (%meta-view-for-state world state)))
    (or (%meta-view-panel view)
        (let ((widget (%meta-ui-widget world "toolbar" "MetaworldToolbar" state 760d0 48d0)))
          (bind-agent-widget-event
           widget "action"
           (lambda (source event)
             (declare (ignore source))
             (%meta-command world *meta-action-seat* (agent-widget-event-value event))))
          (setf (%meta-view-panel view) widget)))))

(defun %meta-prune-widgets (world)
  (let ((overlays (world-overlays world)))
    (dolist (widget (loop for widget being the hash-keys of (%meta-spatial-widgets world)
                         unless (member widget overlays) collect widget))
      (let ((group (object-subworld world widget)))
        (remhash widget (%meta-spatial-widgets world))
        (remhash widget (%meta-owners world))
        (when (eq widget (%meta-menu-target world)) (setf (%meta-menu-target world) nil))
        (when (eq widget (getf (%meta-group-drag world) :subject))
          (setf (%meta-group-drag world) nil))
        (dolist (seat-state (%seat-states world))
          (when (eq widget (%canvas-seat-previous-focus seat-state))
            (setf (%canvas-seat-previous-focus seat-state) nil)))
        (when group
          (setf (subworld-members group)
                (remove widget (subworld-members group) :key #'subworld-member-object))
          (when (eq widget (subworld-fullscreen group)) (setf (subworld-fullscreen group) nil))
          (when (eq widget (gethash group (%meta-group-focus world)))
            (remhash group (%meta-group-focus world)))
          (%meta-layout world group))))
    (when (and (%meta-menu world) (not (member (%meta-menu world) overlays)))
      (setf (%meta-menu world) nil))
    (loop for view being the hash-values of (%meta-views world)
          do (when (and (%meta-view-panel view) (not (member (%meta-view-panel view) overlays)))
               (setf (%meta-view-panel view) nil))
             (when (and (%meta-view-window-controls view)
                        (not (member (%meta-view-window-controls view) overlays)))
               (setf (%meta-view-window-controls view) nil))
             (dolist (group (loop for group being the hash-keys of (%meta-view-headers view)
                                 using (hash-value widget)
                                 unless (member widget overlays) collect group))
               (remhash group (%meta-view-headers view)))))
  world)

(defun %meta-sync-ui (world state)
  (%meta-prune-widgets world)
  (%meta-update-toolbar-intent world state)
  (let* ((view (%meta-view-for-state world state))
         (active (%meta-view-active view))
         (panel (or (%meta-view-panel view)
                    (when (> (%meta-view-panel-until view) (%now)) (%meta-toolbar world state)))))
    (when panel
    (multiple-value-bind (width height) (%output-logical-size state)
      (declare (ignore height))
      (let ((panel-width (min (if active 480d0 340d0) (- width 24d0))))
        (%meta-reposition-ui world panel (/ (- width panel-width) 2d0) 8d0 panel-width 44d0)))
    (%meta-property panel "caption"
                    (if active (subworld-name active) "Canvas"))
    (%meta-property panel "active" (not (null active)))
    (%meta-property panel "standalone" (not (null (%meta-standalone world))))
    (%meta-property panel "workspace" (if active (subworld-workspace active) 1))
    (%meta-present-ui world panel (> (%meta-view-panel-until view) (%now))))
    (dolist (group (metaworld-subworlds world))
      (let ((header (%meta-header world state group)))
        (if (eq group active)
            ;; Keep the breadcrumb reachable when the canvas header is offscreen.
            (multiple-value-bind (width height) (%output-logical-size state)
              (declare (ignore height))
              (%meta-reposition-ui world header 12d0 8d0 (max 96d0 (min 248d0 (- width 24d0))) 30d0))
            (multiple-value-bind (canvas-x canvas-y)
                (%world-to-canvas state (subworld-x group) (subworld-y group))
              (multiple-value-bind (x y) (%canvas-to-screen state canvas-x canvas-y)
                (%meta-reposition-ui world header x (- y 32d0)
                                     (min 280d0 (max 100d0 (* (%canvas-output-zoom state)
                                                             (%meta-footprint-width group)))) 30d0))))
        (%meta-property header "caption"
                        (subworld-name group))
        (%meta-property header "active" (eq group active))
        (%meta-present-ui world header
                          (if (eq group active)
                              (not (and panel (overlay-input-enabled-p panel)))
                              (not (%meta-standalone world)))
                          (if (eq group active) 1d0 0.8d0))))
    (dolist (group (loop for group being the hash-keys of (%meta-view-headers view)
                        unless (member group (metaworld-subworlds world)) collect group))
      (remove-agent-widget world (gethash group (%meta-view-headers view)))
      (remhash group (%meta-view-headers view)))
    (maphash
     (lambda (widget geometry)
       (when (eq (overlay-output widget) (%canvas-output-output state))
         (destructuring-bind (x y width height) geometry
           (multiple-value-bind (canvas-x canvas-y) (%world-to-canvas state x y)
             (multiple-value-bind (screen-x screen-y) (%canvas-to-screen state canvas-x canvas-y)
               (let ((zoom (%canvas-output-zoom state)))
                 (unless (and (= screen-x (overlay-x widget))
                              (= screen-y (overlay-y widget))
                              (= (* zoom width) (overlay-width widget))
                              (= (* zoom height) (overlay-height widget)))
                   (%damage-overlay world widget)
                   (setf (overlay-x widget) screen-x
                         (overlay-y widget) screen-y
                         (overlay-width widget) (* zoom width)
                         (overlay-height widget) (* zoom height))
                   (%damage-overlay world widget))))))))
     (%meta-spatial-widgets world))
    (%meta-sync-object-controls world state)
    (%meta-position-context world state))
  (%meta-schedule-maintenance world)
  world)

(defun %meta-refresh-menu (world)
  (let ((widget (%meta-menu world))
        (group (%meta-menu-group world)))
    (when (and widget group (eq :group (%meta-menu-kind world)))
      (%meta-property widget "world-name" (subworld-name group))
      (%meta-property widget "policy"
                      (string-downcase (symbol-name (if (eq :niri (subworld-kind group))
                                                       :niri (subworld-layout group)))))
      (%meta-property widget "standalone" (not (null (%meta-standalone world)))))))

(defun %meta-transient-ui-active-p (world)
  (or (and (%meta-menu world) (overlay-input-enabled-p (%meta-menu world)))
      (loop for view being the hash-values of (%meta-views world)
            thereis (or (and (%meta-view-panel view) (overlay-input-enabled-p (%meta-view-panel view)))
                        (and (%meta-view-window-controls view)
                             (overlay-input-enabled-p (%meta-view-window-controls view)))))))

(defun %meta-dismiss-transient-ui (world)
  (%meta-dismiss-menu world)
  (maphash (lambda (state chrome)
             (declare (ignore chrome))
             (let ((view (%meta-view-for-state world state)))
               (%meta-suppress-hover world state)
               (setf (%meta-view-window-controls-until view) 0d0
                     (%meta-view-panel-until view) 0d0)
               (%meta-present-ui world (%meta-view-window-controls view) nil)
               (%meta-present-ui world (%meta-view-panel view) nil)))
           (%meta-chrome-states world))
  world)

(defun %meta-dismiss-menu (world)
  (when (%meta-menu world)
    (%meta-present-ui world (%meta-menu world) nil)
    (dolist (seat-state (%seat-states world))
      (when (eq (%canvas-seat-focused seat-state) (%meta-menu world))
        (%focus-target world seat-state
                       (when (%target-visible-p (%meta-menu-target world))
                         (%meta-menu-target world))))))
  world)

(defun %meta-open-menu (world &optional seat (group (%meta-current world seat)))
  (let* ((seat-state (%meta-seat world seat))
         (state (if seat-state (%canvas-seat-output seat-state) (%first-output-state world)))
         (reuse-p (and state (%meta-menu world)
                       (eq (%meta-menu-kind world) (if group :group :canvas))
                       (eq (overlay-output (%meta-menu world)) (%canvas-output-output state)))))
    (when state
      (setf (%meta-menu-target world) (%meta-focused-object world seat)
            (%meta-menu-group world) group)
      (when (%meta-menu world)
        (%meta-dismiss-menu world)
        (unless reuse-p (remove-agent-widget world (%meta-menu world))))
      (unless reuse-p
       (let ((widget (%meta-ui-widget world (if group "group-controls" "canvas-menu")
                                     (if group "SubworldControls" "CanvasCreation")
                                     state (if group 330d0 220d0) (if group 164d0 120d0) :layer 2000)))
        (setf (%meta-menu world) widget
              (%meta-menu-kind world) (if group :group :canvas))
        (when group
          (bind-agent-widget-event
           widget "rename"
           (lambda (source event)
             (declare (ignore source))
             (let ((name (agent-widget-event-value event)) (group (%meta-menu-group world)))
               (when (and group (<= 1 (length name) 200))
                 (setf (subworld-name group) name)
                 (%meta-changed world))))))
        (bind-agent-widget-event
         widget "action"
         (lambda (source event)
           (declare (ignore source))
           (%meta-menu-action world (agent-widget-event-value event) *meta-action-seat*)))))
      (multiple-value-bind (x y)
          (%screen-to-world state (if seat-state (%canvas-seat-x seat-state) 40d0)
                            (if seat-state (%canvas-seat-y seat-state) 40d0))
        (setf (%meta-menu-anchor world) (list x y)))
      (when group (%meta-property (%meta-menu world) "confirming" nil))
      (%meta-refresh-menu world)
      (%meta-present-ui world (%meta-menu world) t)
      (%meta-position-context world state)
      (when seat-state
        (setf (%canvas-seat-previous-focus seat-state) (%meta-menu-target world))
        (%focus-target world seat-state (%meta-menu world)))))
  world)

(defun %meta-position-context (world state)
  (let ((widget (%meta-menu world)))
    (when (and widget (overlay-visible-p widget)
               (eq (overlay-output widget) (%canvas-output-output state)))
      (multiple-value-bind (canvas-x canvas-y)
          (%world-to-canvas state
                            (first (%meta-menu-anchor world))
                            (second (%meta-menu-anchor world)))
        (multiple-value-bind (x y) (%canvas-to-screen state canvas-x canvas-y)
          (multiple-value-bind (width height) (%output-logical-size state)
            (let ((menu-width (max 1d0 (min (if (eq (%meta-menu-kind world) :group) 330d0 220d0)
                                              (- width 16d0))))
                  (menu-height (max 1d0 (min (if (eq (%meta-menu-kind world) :group) 164d0 120d0)
                                               (- height 16d0)))))
              (%meta-reposition-ui
               world widget
               (max 8d0 (min (- width menu-width 8d0) x))
               (max 8d0 (min (- height menu-height 8d0) y))
               menu-width menu-height))))))))

(defun %meta-sync-object-controls (world state)
  (let* ((view (%meta-view-for-state world state))
         (chrome (%meta-chrome-for-state world state))
         (seat (find state (%seat-states world) :key #'%canvas-seat-output))
         (panel (%meta-view-window-controls view))
         (focused (%meta-focused-object world (and seat (%canvas-seat-seat seat))))
         (now (%now))
         (blocked (or (null seat) (%meta-hover-suppressed-p world state) (%meta-group-drag world)
                      (and (%meta-menu world) (overlay-input-enabled-p (%meta-menu world)))
                      (and seat (%canvas-seat-operation seat))
                      (< now (%meta-view-hover-after view))))
         (candidate
           (when (and (not blocked) (typep focused 'canvas-window))
             (multiple-value-bind (x y width height) (%window-canvas-geometry state focused)
               (declare (ignore height))
               (multiple-value-bind (px py) (%screen-to-canvas state (%canvas-seat-x seat) (%canvas-seat-y seat))
                 (when (and (<= (- (+ x width) 40d0) px (+ x width)) (<= y py (+ y 24d0)))
                   focused))))))
    (cond
      (blocked
       (setf (%meta-chrome-candidate chrome) nil (%meta-chrome-window-since chrome) nil
             (%meta-view-window-controls-until view) 0d0))
      ((%meta-pointer-in-ui-p seat panel)
       (setf (%meta-view-window-controls-until view) (+ now 0.55d0)))
      (candidate
       (unless (eq candidate (%meta-chrome-candidate chrome))
         (setf (%meta-chrome-candidate chrome) candidate (%meta-chrome-window-since chrome) now))
       (when (>= (- now (%meta-chrome-window-since chrome)) 0.45d0)
         (setf (%meta-view-window-target view) candidate)
         (setf (%meta-view-window-controls-until view) (+ now 0.55d0))))
      (t (setf (%meta-chrome-candidate chrome) nil (%meta-chrome-window-since chrome) nil)))
    (let* ((target (%meta-view-window-target view))
           (show (and (not blocked) (%target-visible-p target)
                      (> (%meta-view-window-controls-until view) now))))
      (when show
        (unless panel
          (setf panel (%meta-ui-widget world "window-controls" "ObjectControls" state 36d0 30d0 :layer 1500)
                (%meta-view-window-controls view) panel)
          (bind-agent-widget-event
           panel "action"
           (lambda (widget event)
             (let ((action (agent-widget-event-value event)))
               (%meta-suppress-hover world state)
               (setf (%meta-view-window-controls-until view) 0d0)
               (%meta-present-ui world widget nil)
               (let ((object (%meta-view-window-target view)))
                 (when (%target-visible-p object)
                   (%meta-focus world object *meta-action-seat*)
                   (%meta-command world *meta-action-seat* action)))))))
        (let* ((group (object-subworld world target))
               (member (and group (%meta-member group target)))
               (detachable (and group (not (%meta-standalone world))))
               (niri (and group (eq :niri (subworld-kind group))))
               (panel-width (+ 14d0 (* 34d0 (+ 1 (if group 2 0) (if niri 3 0) (if detachable 1 0)))))
               (panel-height 64d0))
          (%meta-property panel "owned" (not (null group)))
          (%meta-property panel "detachable" (not (null detachable)))
          (%meta-property panel "niri" (not (null niri)))
          (%meta-property panel "floating" (and member (subworld-member-floating-p member)))
          (multiple-value-bind (x y width height) (%window-canvas-geometry state target)
            (declare (ignore height))
            (multiple-value-bind (screen-x screen-y) (%canvas-to-screen state (+ x width) y)
              (multiple-value-bind (output-width output-height) (%output-logical-size state)
                (%meta-reposition-ui world panel
                 (max 8d0 (min (- screen-x panel-width 4d0) (- output-width panel-width 8d0)))
                 (max 8d0 (min (+ screen-y 4d0) (- output-height panel-height 8d0)))
                 panel-width panel-height))))))
      (%meta-present-ui world panel show))))

(defun %meta-new-note (world &optional group content geometry)
  (let* ((seat-state (%meta-seat world *meta-action-seat*))
         (state (or (and seat-state (%canvas-seat-output seat-state)) (%first-output-state world)))
         (widget (ataxia.world:create-agent-widget
                  'meta-note world ""
                  :component-factory #'ataxia.world.slint:make-slint-component
                  :source-path "ataxia-builtin:note"
                  :component-name "MetaworldNote" :output (%canvas-output-output state)
                  :width 430d0 :height 320d0 :layer 20)))
    (setf (%meta-note-content widget)
          (or content ""))
    (%meta-property widget "content" (%meta-note-content widget))
    (bind-agent-widget-event
     widget "edited"
     (lambda (source event)
       (setf (%meta-note-content source) (agent-widget-event-value event))
       (%meta-changed world)))
    (bind-agent-widget-event
     widget "close"
     (lambda (source event)
       (declare (ignore event))
       (%meta-focus world source *meta-action-seat*)
       (%meta-command world *meta-action-seat* "close")))
    (setf (gethash widget (%meta-spatial-widgets world))
          (or geometry (list (+ (%canvas-output-camera-x state) 120d0)
                             (+ (%canvas-output-camera-y state) 150d0) 430d0 320d0)))
    (when group (move-object-to-subworld world widget group))
    (%meta-changed world)
    widget))
