;;;; Workspace removal preserves applications and compacts subsequent page numbers.
(in-package #:ataxia.infinite-world)

(defun %meta-workspace-numbers (group)
  (loop for number from 1 to (%meta-workspace-count group) collect number))

(defun %meta-remove-workspace-key (table number)
  (when table
    (remhash number table)
    (loop for old from (1+ number) to 9 do
      (multiple-value-bind (value present-p) (gethash old table)
        (when present-p (setf (gethash (1- old) table) value)))
      (remhash old table))))

(defun %meta-remove-workspace (world group number &optional seat)
  (unless (and (member group (metaworld-subworlds world))
               (typep number '(integer 1 9)))
    (return-from %meta-remove-workspace nil))
  (let* ((numbers (%meta-workspace-numbers group))
         (remaining (remove number numbers))
         (destination (or (car (last (remove-if-not (lambda (n) (< n number)) remaining)))
                          (first remaining)))
         (columns (make-hash-table)))
    ;; Every subworld retains one workspace. A stale menu cannot remove it.
    (unless (and destination (member number numbers))
      (return-from %meta-remove-workspace nil))
    (when (subworld-fullscreen group)
      (%meta-toggle-fullscreen world (subworld-fullscreen group) nil nil))
    (setf (subworld-next-column group)
          (reduce #'max (subworld-members group) :key #'subworld-member-column
                  :initial-value (subworld-next-column group)))
    (labels ((renumber (old)
               (let ((next (if (= old number) destination old)))
                 (if (> next number) (1- next) next)))
             (new-column (old)
               ;; Preserve stacks from the removed page without merging their
               ;; column IDs with an existing stack in the destination.
               (or (gethash old columns)
                   (setf (gethash old columns) (incf (subworld-next-column group)))))
             (shift-y (old)
               (if (eq :niri (subworld-kind group))
                   (* (- (renumber old) old) (subworld-height group)) 0d0))
             (translate-record (record)
               (when (eql (getf record :owner) (subworld-id group))
                 (let* ((data (getf record :member)) (old (getf data :workspace 1))
                        (dy (shift-y old)))
                   (setf (getf data :workspace) (renumber old))
                   (when (= old number) (setf (getf data :column) (new-column (getf data :column))))
                   (dolist (geometry (list (getf record :geometry) (getf data :restore)))
                     (when geometry (incf (second geometry) dy)))
                   (setf (getf record :member) data)))))
      (dolist (member (subworld-members group))
        (let* ((old (subworld-member-workspace member)) (next (renumber old))
               (dy (shift-y old)))
          (when (= old number)
            (setf (subworld-member-column member) (new-column (subworld-member-column member))))
          (setf (subworld-member-workspace member) next)
          (unless (zerop dy)
            (%meta-translate-object world (subworld-member-object member) 0d0 dy)
            (when (subworld-member-restore-geometry member)
              (incf (second (subworld-member-restore-geometry member)) dy)))))
      (dolist (record (append (%meta-saved-windows world) (%meta-saved-notes world)))
        (translate-record record))
      (dolist (launch (%meta-pending-launches world))
        (when (and (eql (%meta-launch-group-id launch) (subworld-id group))
                   (%meta-launch-workspace launch))
          (setf (%meta-launch-workspace launch) (renumber (%meta-launch-workspace launch)))))
      (dolist (table (list (subworld-scrolls group) (gethash group *meta-workspace-focus*)
                          (gethash group *meta-hypr-trees*)))
        (%meta-remove-workspace-key table number))
      (setf (subworld-workspace group) (renumber (subworld-workspace group)))
      ;; Remove exactly one page, retaining other created or visited empty pages.
      (setf (gethash group *meta-workspace-counts*) (1- (length numbers)))
      (%meta-layout world group)
      (dolist (state (%output-states world))
        (when (eq group (%meta-view-active (%meta-view-for-state world state)))
          (%meta-cancel-motion world state :metaworld-camera)
          (%meta-fit-group world state group)))
      (when (eq group (%meta-current world seat))
        (let* ((members (%meta-visible-members group :include-floating t))
               (focused (%meta-focused-object world seat))
               (target (or (and (find focused members :key #'subworld-member-object) focused)
                           (and members (subworld-member-object (first members))))))
          (%meta-focus world target seat nil)))
      (%meta-changed world)
      (renumber destination))))
