(in-package #:ataxia.infinite-world)

(defun %meta-overview (world &optional seat output-state)
  (let* ((seat-state (%meta-seat world seat))
         (state (or output-state (and seat-state (%canvas-seat-output seat-state))
                    (%first-output-state world)))
         (rectangles
           (append
            (loop for group in (metaworld-subworlds world)
                  collect (list (subworld-x group) (- (subworld-y group) 90d0)
                                (%meta-footprint-width group) (+ (subworld-height group) 90d0)))
            (loop for window in (%world-stacking world)
                  when (and (%window-visible-p window) (not (object-subworld world window)))
                    collect (%meta-object-geometry window))
            (loop for widget being the hash-keys of (%meta-spatial-widgets world)
                  when (and (%target-visible-p widget) (not (object-subworld world widget)))
                    collect (%meta-object-geometry widget)))))
    (when (and state rectangles)
      (let* ((left (reduce #'min rectangles :key #'first))
             (top (reduce #'min rectangles :key #'second))
             (right (reduce #'max rectangles :key (lambda (geometry) (+ (first geometry) (third geometry)))))
             (bottom (reduce #'max rectangles :key (lambda (geometry) (+ (second geometry) (fourth geometry)))))
             (origin (%meta-camera state)))
        (multiple-value-bind (width height) (%output-logical-size state)
          (let ((zoom (max 0.08d0 (min 1d0 (/ (- width 100d0) (max 1d0 (- right left)))
                                         (/ (- height 120d0) (max 1d0 (- bottom top)))))))
            (setf (%meta-view-active (%meta-view-for-state world state)) nil)
            (%meta-set-camera world state
                              (list (- (/ (+ left right) 2d0) (/ width (* 2d0 zoom)))
                                    (- (/ (+ top bottom) 2d0) (/ height (* 2d0 zoom))) zoom 0d0))
            (%meta-transition-camera world state origin))))))
  (%meta-changed world))

(defun %meta-command-group (world seat)
  (let ((object (%meta-focused-object world seat)))
    (if object (object-subworld world object) (%meta-current world seat))))

(defun %meta-switch-workspace (world group number &optional seat)
  (when group
    (let ((fullscreen (subworld-fullscreen group)))
      (when fullscreen (%meta-toggle-fullscreen world fullscreen nil)))
    (setf (subworld-fullscreen group) nil
          (subworld-workspace group) (max 1 (min 9 number)))
    (%meta-layout world group)
    (let* ((seat-state (%meta-seat world seat))
           (state (and seat-state (%canvas-seat-output seat-state))))
      (when (and state (eq group (%meta-current world seat)))
        (%meta-fit-group world state group)))
    (%meta-focus world
                 (let ((member (first (%meta-visible-members group :include-floating t))))
                   (and member (subworld-member-object member))) seat)))

(defun %meta-toggle-fullscreen (world object &optional (value nil supplied-p))
  (let ((group (and object (object-subworld world object))))
    (when group
      (let* ((old (subworld-fullscreen group))
             (enabled (if supplied-p value (not (eq old object))))
             (member (%meta-member group object)))
        (when (and enabled (not (eq old object)) (subworld-member-floating-p member))
          (setf (subworld-member-restore-geometry member) (%meta-object-geometry object)))
        (when (and old (or (not enabled) (not (eq old object))))
          (let ((old-member (%meta-member group old)))
            (when (and (subworld-member-floating-p old-member)
                       (subworld-member-restore-geometry old-member))
              (apply #'%meta-place world old (subworld-member-restore-geometry old-member)))))
        (when (and old (not (eq old object)) (typep old 'canvas-window))
          (ataxia.kernel:request-object-state (canvas-window-application old) world :fullscreen nil))
        (setf (subworld-fullscreen group) (and enabled object))
        (when (typep object 'canvas-window)
          (ataxia.kernel:request-object-state
           (canvas-window-application object) world :fullscreen (not (null enabled))))
        (%meta-layout world group)
        (%meta-focus world object)))))

(defun %meta-toggle-floating (world object)
  (let* ((group (and object (object-subworld world object)))
         (member (and group (%meta-member group object))))
    (when member
      (when (subworld-fullscreen group)
        (%meta-toggle-fullscreen world (subworld-fullscreen group) nil))
      (setf (subworld-member-floating-p member) (not (subworld-member-floating-p member)))
      (when (subworld-member-floating-p member)
        (%meta-place world object (+ (subworld-x group) 110d0) (+ (subworld-y group) 110d0)
                     (* 0.60d0 (subworld-width group)) (* 0.65d0 (subworld-height group))))
      (%meta-layout world group)
      (%meta-focus world object))))

(defun %meta-navigation-objects (world group)
  (if group
      (mapcar #'subworld-member-object (%meta-visible-members group :include-floating t))
      (append (remove-if-not #'%window-visible-p (%world-stacking world))
              (loop for widget being the hash-keys of (%meta-spatial-widgets world)
                    when (%target-visible-p widget) collect widget))))

(defun %meta-neighbor (world object direction group)
  (let* ((objects (%meta-navigation-objects world group))
         (geometry (and object (%meta-object-geometry object))))
    (if (null geometry)
        (first objects)
        (destructuring-bind (x y width height) geometry
          (let ((center-x (+ x (/ width 2d0)))
                (center-y (+ y (/ height 2d0)))
                (best nil) (best-distance most-positive-double-float))
            (dolist (candidate objects)
              (unless (eq candidate object)
                (destructuring-bind (candidate-x candidate-y candidate-width candidate-height)
                    (%meta-object-geometry candidate)
                  (let* ((delta-x (- (+ candidate-x (/ candidate-width 2d0)) center-x))
                         (delta-y (- (+ candidate-y (/ candidate-height 2d0)) center-y))
                         (forward (ecase direction (:left (- delta-x)) (:right delta-x)
                                           (:up (- delta-y)) (:down delta-y)))
                         (cross (if (member direction '(:left :right)) delta-y delta-x))
                         (distance (+ (abs forward) (* 3d0 (abs cross)))))
                    (when (and (> forward 1d0) (< distance best-distance))
                      (setf best candidate best-distance distance))))))
            best)))))

(defun %meta-reorder (world object direction group)
  (when (and group object)
    (let* ((member (%meta-member group object))
           (neighbor (%meta-neighbor world object direction group))
           (other (and neighbor (%meta-member group neighbor))))
      (when (and member other)
        (if (and (eq :niri (subworld-kind group)) (member direction '(:left :right)))
            (let* ((columns (%meta-columns group))
                   (position (position (subworld-member-column member) columns))
                   (destination (position (subworld-member-column other) columns)))
              (rotatef (nth position columns) (nth destination columns))
              (setf (subworld-members group)
                    (stable-sort (copy-list (subworld-members group)) #'<
                                 :key (lambda (entry)
                                        (or (position (subworld-member-column entry) columns)
                                            (length columns))))))
            (let ((members (copy-list (subworld-members group))))
              (rotatef (nth (position member members) members)
                       (nth (position other members) members))
              (setf (subworld-members group) members)))
        (%meta-layout world group)
        (%meta-focus world object)))))

(defun %meta-stack-column (world object expel-p)
  (let* ((group (and object (object-subworld world object)))
         (member (and group (%meta-member group object))))
    (when (and member (eq :niri (subworld-kind group)))
      (if expel-p
          (setf (subworld-member-column member) (incf (subworld-next-column group)))
          (let* ((columns (%meta-columns group))
                 (position (position (subworld-member-column member) columns))
                 (destination (and position (nth (if (plusp position) (1- position) 1) columns))))
            (when destination
              (setf (subworld-member-column member) destination))))
      (%meta-layout world group)
      (%meta-focus world object))))

(defun %meta-resize-tile (world object direction)
  (let* ((group (and object (object-subworld world object)))
         (member (and group (%meta-member group object))))
    (when member
      (let ((increase-p (member direction '(:right :down))))
        (cond
          ((subworld-member-floating-p member)
           (destructuring-bind (x y width height) (%meta-object-geometry object)
             (%meta-place world object x y
                          (+ width (case direction (:left -60d0) (:right 60d0) (t 0d0)))
                          (+ height (case direction (:up -60d0) (:down 60d0) (t 0d0))))))
          ((eq :hyprland (subworld-kind group))
           (setf (subworld-ratio group)
                 (max 0.2d0 (min 0.8d0 (+ (subworld-ratio group) (if increase-p 0.04d0 -0.04d0))))))
          ((member direction '(:left :right))
           (let ((width (max 220d0 (min (* 1.5d0 (subworld-width group))
                                       (+ (subworld-member-width member) (if increase-p 80d0 -80d0))))))
             (dolist (entry (subworld-members group))
               (when (= (subworld-member-column entry) (subworld-member-column member))
                 (setf (subworld-member-width entry) width)))))
          (t
           (setf (subworld-member-weight member)
                 (max 0.2d0 (min 5d0 (+ (subworld-member-weight member) (if increase-p 0.2d0 -0.2d0))))))))
      (%meta-layout world group)
      (%meta-focus world object))))

(defun %meta-launch-terminal (world)
  (let ((display (ataxia.runtime:runtime-socket-name
                  (ataxia.kernel:kernel-runtime (ataxia.kernel:world-kernel world)))))
    (handler-case
        (progn
          (uiop:launch-program
           (list "env" (format nil "WAYLAND_DISPLAY=~A" display) "foot")
           :input #P"/dev/null" :output #P"/dev/null" :error-output #P"/dev/null" :wait nil)
          (setf (%meta-pending-launches world)
                (append (%meta-pending-launches world)
                        (list (cons (+ (%now) 10d0) (%meta-current world))))))
      (serious-condition (cause)
        (show-notification world (format nil "Could not launch Foot: ~A" cause)
                           :title "TERMINAL")))))

(defun %meta-switch-mode (world mode &optional layout)
  (save-metaworld world)
  (setf (gethash (%meta-standalone world) (%meta-state-paths world)) (%meta-state-file world))
  (let* ((kernel (ataxia.kernel:world-kernel world))
         (generation (ataxia.kernel:kernel-world-generation kernel)))
    (ataxia.runtime:add-event-loop-idle
     (ataxia.kernel:kernel-runtime kernel)
     (lambda (source)
       (declare (ignore source))
       (when (= generation (ataxia.kernel:kernel-world-generation kernel))
         (let ((replacement (make-metaworld
                             :standalone mode
                             :state-file (and (%meta-state-file world)
                                              (gethash mode (%meta-state-paths world)
                                                       (%meta-state-path mode))))))
           (setf (%meta-state-paths replacement) (%meta-state-paths world))
           (when (and layout (first (metaworld-subworlds replacement)))
             (setf (subworld-layout (first (metaworld-subworlds replacement))) layout))
           (ataxia.kernel:install-world kernel replacement)))
       0))))

(defun %meta-command (world seat action &optional argument)
  (let* ((object (%meta-focused-object world seat))
         (group (%meta-command-group world seat)))
    (cond
      ((string= action "controls")
       (if (and (%meta-menu world) (canvas-overlay-visible-p (%meta-menu world)))
           (%meta-dismiss-menu world) (%meta-open-menu world seat)))
      ((string= action "mode-canvas") (%meta-switch-mode world nil))
      ((string= action "terminal") (%meta-dismiss-menu world) (%meta-launch-terminal world))
      ((string= action "overview")
       (%meta-dismiss-menu world)
       (if (%meta-current world seat) (leave-subworld world seat) (%meta-overview world seat)))
      ((string= action "switch-group")
       (let* ((groups (metaworld-subworlds world))
              (position (position (%meta-current world seat) groups)))
         (when groups
           (%meta-dismiss-menu world)
           (enter-subworld world
                           (nth (mod (+ (or position (if (plusp argument) -1 0)) argument)
                                     (length groups)) groups) seat))))
      ((string= action "enter")
       (let* ((seat-state (%meta-seat world seat))
              (state (and seat-state (%canvas-seat-output seat-state)))
              (under-pointer
                (when state
                  (multiple-value-bind (x y)
                      (%screen-to-world state (%canvas-seat-x seat-state) (%canvas-seat-y seat-state))
                    (%meta-group-at world x y)))))
         (when (or under-pointer group)
           (enter-subworld world (or under-pointer group) seat))))
      ((string= action "fullscreen") (%meta-toggle-fullscreen world object))
      ((string= action "floating") (%meta-toggle-floating world object))
      ((string= action "close")
       (typecase object
         (canvas-window (ataxia.kernel:request-object-state
                         (canvas-window-application object) world :close t))
         (agent-widget
          (when group (move-object-to-subworld world object nil))
          (remhash object (%meta-spatial-widgets world))
          (remove-agent-widget world object))))
      ((string= action "focus")
       (when (and group (subworld-fullscreen group))
         (%meta-toggle-fullscreen world (subworld-fullscreen group) nil))
       (let ((neighbor (%meta-neighbor world object argument group)))
         (when neighbor (%meta-focus world neighbor seat))))
      ((string= action "move") (%meta-reorder world object argument group))
      ((string= action "resize") (%meta-resize-tile world object argument))
      ((string= action "consume") (%meta-stack-column world object nil))
      ((string= action "expel") (%meta-stack-column world object t))
      ((string= action "workspace") (%meta-switch-workspace world group argument seat))
      ((string= action "send-workspace")
       (when (and group object)
         (setf (subworld-member-workspace (%meta-member group object)) argument)
         (%meta-switch-workspace world group argument seat)
         (%meta-focus world object seat)))
      ((string= action "previous-workspace")
       (when group (%meta-switch-workspace world group (1- (subworld-workspace group)) seat)))
      ((string= action "next-workspace")
       (when group (%meta-switch-workspace world group (1+ (subworld-workspace group)) seat)))
      ((string= action "pull-out")
       (when (and object (not (%meta-standalone world)))
         (move-object-to-subworld world object nil)
         (when group
           (destructuring-bind (x y width height) (%meta-object-geometry object)
             (declare (ignore x))
             (%meta-place world object (+ (subworld-x group) (%meta-footprint-width group) 90d0)
                          y width height)))
         (leave-subworld world seat)
         (%meta-overview world seat)
         (%meta-focus world object seat)))
      ((string= action "cycle")
       (when (and group (subworld-fullscreen group))
         (%meta-toggle-fullscreen world (subworld-fullscreen group) nil))
       (let* ((objects (%meta-navigation-objects world group))
              (position (position object objects)))
         (when objects
           (%meta-focus world (nth (mod (1+ (or position -1)) (length objects)) objects) seat))))))
  (%meta-changed world))

(defun %meta-menu-action (world action seat)
  (let ((group (%meta-menu-group world)))
    (cond
      ((string= action "dismiss") (%meta-dismiss-menu world))
      ((member action '("new-niri" "new-hyprland") :test #'string=)
       (unless (%meta-standalone world)
         (let* ((anchor (apply #'%meta-vacant-position world (%meta-menu-anchor world)))
                (created (create-subworld world (if (string= action "new-niri") :niri :hyprland)
                                          :x (first anchor) :y (second anchor))))
           (%meta-dismiss-menu world)
           (enter-subworld world created seat))))
      ((member action '("policy-niri" "policy-dwindle" "policy-master") :test #'string=)
       (when group
         (let ((kind (if (string= action "policy-niri") :niri :hyprland)))
           (if (and (%meta-standalone world) (not (eq kind (%meta-standalone world))))
               (%meta-switch-mode world kind (if (string= action "policy-master") :master :dwindle))
               (progn
                 (setf (subworld-kind group) kind
                       (subworld-layout group) (if (string= action "policy-master") :master :dwindle))
                 (%meta-layout world group)
                 (%meta-dismiss-menu world))))))
      ((string= action "dissolve")
       (when (and group (not (%meta-standalone world)))
         (let* ((widget (%meta-menu world))
                (cache (gethash (canvas-overlay-component widget) *meta-property-cache*)))
           (if (gethash "confirming" cache)
               (progn
                 (%meta-dismiss-menu world)
                 (remove-subworld world group)
                 (setf (%meta-menu-group world) nil))
               (%meta-property widget "confirming" t)))))
      ((string= action "note")
       (%meta-dismiss-menu world)
       (let ((anchor (%meta-menu-anchor world)))
         (%meta-focus world (%meta-new-note world group nil
                                           (when (and anchor (not group))
                                             (append anchor (list 430d0 320d0)))) seat)))
      ((string= action "standalone")
       (when group (%meta-switch-mode world (subworld-kind group) (subworld-layout group))))
      ((string= action "mode-canvas") (%meta-switch-mode world nil))
      ((string= action "mode-niri") (%meta-switch-mode world :niri))
      ((string= action "mode-hyprland") (%meta-switch-mode world :hyprland))))
  (%meta-refresh-menu world)
  (%meta-changed world))

(defun %meta-install-shortcuts (world)
  (let ((controller (ataxia.world:world-shortcut-controller world)))
    (labels ((bind-command (id key modifiers action &optional argument)
               (ataxia.world:add-shortcut
                controller
                (ataxia.world:make-shortcut-binding
                 :id id :key key :modifiers modifiers
                 :repeat-p (not (null (member action '("focus" "move" "resize") :test #'string=)))
                 :press-handler
                 (lambda (target seat input)
                   (declare (ignore input))
                   (%meta-command target seat action argument)))
                :if-exists :replace)))
      (dolist (binding '((:meta-worlds "m" "overview") (:meta-controls "comma" "controls")
                         (:meta-terminal "Return" "terminal")
                         (:meta-overview "Escape" "overview") (:meta-enter "e" "enter")
                         (:meta-fullscreen "f" "fullscreen") (:meta-floating "v" "floating")
                         (:meta-close "q" "close") (:meta-cycle "Tab" "cycle")
                         (:meta-consume "bracketleft" "consume") (:meta-expel "bracketright" "expel")))
        (destructuring-bind (id key action) binding
          (bind-command id (list :keysym key) '(:logo) action)))
      (bind-command :meta-pull-out '(:keysym "E") '(:logo :shift) "pull-out")
      (bind-command :meta-next-group '(:keysym "Next") '(:logo) "switch-group" 1)
      (bind-command :meta-previous-group '(:keysym "Prior") '(:logo) "switch-group" -1)
      (dolist (direction '(:left :right :up :down))
        (bind-command (list :focus direction) (list :keysym direction) '(:logo) "focus" direction)
        (bind-command (list :move direction) (list :keysym direction) '(:logo :shift) "move" direction)
        (bind-command (list :resize direction) (list :keysym direction) '(:logo :control) "resize" direction))
      (loop for number from 1 to 9
            do (bind-command (list :workspace number) (list :keysym (princ-to-string number))
                             '(:logo) "workspace" number)
               (bind-command (list :send-workspace number) (list :physical (1+ number))
                             '(:logo :shift) "send-workspace" number)))
    (ataxia.world:add-shortcut
     controller
     (ataxia.world:make-shortcut-binding
      :id :meta-dismiss :key '(:keysym "Escape") :modifiers nil
      :predicate (lambda (target seat input)
                   (declare (ignore seat input))
                   (and (%meta-menu target) (canvas-overlay-visible-p (%meta-menu target))))
      :press-handler (lambda (target seat input)
                       (declare (ignore seat input))
                       (%meta-dismiss-menu target)))
     :if-exists :replace)))

(defmethod initialize-instance :after ((world metaworld) &key)
  (%meta-load-state world)
  (unless (%meta-state-loaded-p world)
    (if (%meta-standalone world)
        (create-subworld world (%meta-standalone world)
                         :name (if (eq :niri (%meta-standalone world)) "Niri" "Hyprland"))
        (progn
          (create-subworld world :niri :name "Development")
          (create-subworld world :hyprland :name "Studio"))))
  (%meta-install-shortcuts world))

(defun %meta-dragged-p (world object)
  (or (eq object (getf (%meta-group-drag world) :subject))
      (some (lambda (state)
              (let ((operation (%canvas-seat-operation state)))
                (and operation (eq object (%canvas-operation-window operation)))))
            (%seat-states world))))

(defun %meta-drop-object (world object state &optional resize-p)
  (let ((previous (object-subworld world object)))
    (if resize-p
        (let ((member (and previous (%meta-member previous object))))
          (when (and member (not (subworld-member-floating-p member)))
            (if (eq :niri (subworld-kind previous))
                (let ((width (third (%meta-object-geometry object))))
                  (dolist (entry (subworld-members previous))
                    (when (= (subworld-member-column entry) (subworld-member-column member))
                      (setf (subworld-member-width entry) width))))
                (setf (subworld-ratio previous)
                      (max 0.2d0 (min 0.8d0 (/ (third (%meta-object-geometry object))
                                               (subworld-width previous))))))
            (%meta-layout world previous)))
        (multiple-value-bind (x y)
            (%screen-to-world (%canvas-seat-output state) (%canvas-seat-x state) (%canvas-seat-y state))
          (let* ((destination (if (%meta-standalone world) (first (metaworld-subworlds world))
                                  (%meta-group-at world x y)))
                 (other
                   (and destination
                        (find-if
                         (lambda (entry)
                           (and (not (eq object (subworld-member-object entry)))
                                (destructuring-bind (left top width height)
                                    (%meta-object-geometry (subworld-member-object entry))
                                  (and (<= left x (+ left width)) (<= top y (+ top height))))))
                         (%meta-visible-members destination)))))
            (unless (eq previous destination)
              (move-object-to-subworld world object destination))
            (when destination
              (let ((member (%meta-member destination object)))
                (when (and other (not (subworld-member-floating-p member)))
                  (let ((members (remove member (subworld-members destination))))
                    (setf (subworld-members destination)
                          (loop for entry in members
                                when (eq entry other) collect member
                                collect entry)))
                  (when (eq :niri (subworld-kind destination))
                    (setf (subworld-member-column member)
                          (if (member :control (gethash (%canvas-seat-seat state) (%meta-modifiers world)))
                              (subworld-member-column other)
                              (incf (subworld-next-column destination)))))))
              (%meta-layout world destination)))))
    (%meta-changed world)))

(defun %meta-header-group (world state target)
  (let ((view (%meta-view-for-state world state)))
    (when view
      (loop for group being the hash-keys of (%meta-view-headers view)
            using (hash-value header) when (eq header target) return group))))

(defun %meta-begin-drag (world seat-state subject &optional resize-p)
  (ataxia.world:cancel-animation (%world-animator world) (%canvas-seat-output seat-state) :metaworld-camera)
  (when (typep subject 'subworld)
    (dolist (member (subworld-members subject))
      (ataxia.world:cancel-animation (%world-animator world) (subworld-member-object member) :metaworld-layout)))
  (multiple-value-bind (x y)
      (%screen-to-world (%canvas-seat-output seat-state)
                        (%canvas-seat-x seat-state) (%canvas-seat-y seat-state))
    (setf (%meta-group-drag world)
          (list :seat (%canvas-seat-seat seat-state) :subject subject
                :pointer-x x :pointer-y y :moved nil :resize-p resize-p
                :geometry (if (typep subject 'subworld)
                              (list (subworld-x subject) (subworld-y subject)
                                    (subworld-width subject) (subworld-height subject))
                              (%meta-object-geometry subject))))))

(defun %meta-apply-drag (world seat-state)
  (let* ((drag (%meta-group-drag world))
         (subject (getf drag :subject)))
    (multiple-value-bind (x y)
        (%screen-to-world (%canvas-seat-output seat-state)
                          (%canvas-seat-x seat-state) (%canvas-seat-y seat-state))
      (let ((delta-x (- x (getf drag :pointer-x)))
            (delta-y (- y (getf drag :pointer-y))))
        (when (> (* (%canvas-output-zoom (%canvas-seat-output seat-state))
                    (+ (abs delta-x) (abs delta-y))) 6d0)
          (setf (getf (%meta-group-drag world) :moved) t))
        (when (getf (%meta-group-drag world) :moved)
          (destructuring-bind (left top width height) (getf drag :geometry)
            (cond
              ((getf drag :resize-p)
               (setf (subworld-width subject) (max 480d0 (+ width delta-x))
                     (subworld-height subject) (max 320d0 (+ height delta-y)))
               (%meta-layout world subject))
              ((typep subject 'subworld)
               (move-subworld world subject (+ left delta-x) (+ top delta-y)))
              (t (%meta-place world subject (+ left delta-x) (+ top delta-y) width height))))
          (%meta-changed world))))))

(defmethod ataxia.kernel:world-cursor-motion :around ((world metaworld) seat input)
  (let* ((seat-state (%meta-seat world seat))
         (drag (%meta-group-drag world)))
    (if (and seat-state drag (eq seat (getf drag :seat)))
        (progn
          (%damage-cursor world seat-state)
          (%update-seat-position seat-state input)
          (%meta-apply-drag world seat-state)
          (%damage-cursor world seat-state)
          (%request-all-frames world))
        (call-next-method))
    (when seat-state
      (let* ((state (%canvas-seat-output seat-state))
             (view (%meta-view-for-state world state))
             (panel (and view (%meta-view-panel view))))
        (when (and view
                   (or (< (%canvas-seat-y seat-state) 10d0)
                       (and panel (canvas-overlay-visible-p panel)
                            (< (%canvas-seat-y seat-state) 66d0))))
          (setf (%meta-view-panel-until view) (+ (%now) 1.1d0))
          (%request-output-state-frame world state)))))
  input)

(defmethod ataxia.kernel:world-cursor-button :around ((world metaworld) seat input)
  (let* ((*meta-action-seat* seat)
         (seat-state (%meta-seat world seat))
         (state (and seat-state (%canvas-seat-output seat-state)))
         (pressed-p (eq :pressed (ataxia.kernel:cursor-button-input-state input)))
         (code (ataxia.kernel:cursor-button-input-code input))
         (target (and state (%target-at-screen-point world state
                                                    (%canvas-seat-x seat-state) (%canvas-seat-y seat-state))))
         (group (and state (%meta-header-group world state target)))
         (operation (and seat-state (%canvas-seat-operation seat-state)))
         (drag (%meta-group-drag world))
         (logo-p (member :logo (gethash seat (%meta-modifiers world)))))
    (when (and pressed-p (%meta-menu world) (canvas-overlay-visible-p (%meta-menu world))
               (not (eq target (%meta-menu world))))
      (%meta-dismiss-menu world))
    (cond
      ((and drag (eq seat (getf drag :seat)) (not pressed-p)
            (= code (if (getf drag :resize-p) 273 +button-left+)))
       (setf (%meta-group-drag world) nil)
       (let ((subject (getf drag :subject)))
         (if (typep subject 'subworld)
             (unless (getf drag :moved)
               (if (eq subject (%meta-current world seat))
                   (leave-subworld world seat) (enter-subworld world subject seat)))
             (%meta-drop-object world subject seat-state)))
       (remhash code (%canvas-seat-buttons seat-state))
       (%meta-changed world))
      ((and pressed-p logo-p (null target) state (not (%meta-standalone world))
            (member code '(272 273))
            (multiple-value-bind (x y)
                (%screen-to-world state (%canvas-seat-x seat-state) (%canvas-seat-y seat-state))
              (let ((under-pointer (%meta-group-at world x y)))
                (when under-pointer
                  (%meta-begin-drag world seat-state under-pointer (= code 273))
                  t))))
       (setf (gethash code (%canvas-seat-buttons seat-state)) :world))
      ((and pressed-p group
            (or (= code 273)
                (and (= code +button-left+)
                     (> (%canvas-seat-x seat-state)
                        (- (+ (canvas-overlay-x target) (canvas-overlay-width target)) 42d0)))))
       (%meta-open-menu world seat group)
       (setf (gethash code (%canvas-seat-buttons seat-state)) :world))
      ((and pressed-p (= code 273) (null target))
       (multiple-value-bind (x y)
           (%screen-to-world state (%canvas-seat-x seat-state) (%canvas-seat-y seat-state))
         (%meta-open-menu world seat (%meta-group-at world x y)))
       (setf (gethash code (%canvas-seat-buttons seat-state)) :world))
      ((and pressed-p (= code +button-left+) group)
       (%meta-begin-drag world seat-state group)
       (setf (gethash code (%canvas-seat-buttons seat-state)) :world))
      ((and pressed-p logo-p (member code '(272 273)) (typep target 'canvas-window))
       (ataxia.world:cancel-animation (%world-animator world) target :metaworld-layout)
       (ataxia.world:cancel-animation (%world-animator world) state :metaworld-camera)
       (%begin-window-operation world seat-state target (if (= code 273) :resize :move)
                                :edges (logior +resize-right+ +resize-bottom+))
       (setf (%canvas-operation-button (%canvas-seat-operation seat-state)) code
             (gethash code (%canvas-seat-buttons seat-state)) :world))
      ((and pressed-p (= code +button-left+) (typep target 'agent-widget)
            (gethash target (%meta-spatial-widgets world))
            (or logo-p
                (and (< (%canvas-seat-y seat-state) (+ (canvas-overlay-y target) 24d0))
                     (< (%canvas-seat-x seat-state)
                        (- (+ (canvas-overlay-x target) (canvas-overlay-width target)) 30d0)))))
       (%meta-begin-drag world seat-state target)
       (%focus-target world seat-state target)
       (setf (gethash code (%canvas-seat-buttons seat-state)) :world))
      (t
       (when (and pressed-p (typep target 'canvas-overlay) seat-state
                  (not (gethash target (%meta-spatial-widgets world))))
         (let ((object (%meta-focused-object world seat)))
           (when object (setf (%canvas-seat-previous-focus seat-state) object))))
       (call-next-method)
       (when (and operation (not pressed-p) (= code (%canvas-operation-button operation))
                  (%canvas-operation-window operation))
         (%meta-drop-object world (%canvas-operation-window operation) seat-state
                            (eq :resize (%canvas-operation-kind operation))))))
    (when (and pressed-p (typep target 'canvas-window))
      (let ((owner (object-subworld world target)))
        (when (and owner (eq owner (%meta-current world seat)))
          (%meta-focus world target seat)))))
  input)

(defmethod ataxia.kernel:world-cursor-axis :around ((world metaworld) seat input)
  (let* ((seat-state (%meta-seat world seat))
         (state (and seat-state (%canvas-seat-output seat-state)))
         (modifiers (gethash seat (%meta-modifiers world)))
         (group (%meta-current world seat))
         (delta (ataxia.kernel:cursor-axis-input-delta input)))
    (when state (ataxia.world:cancel-animation (%world-animator world) state :metaworld-camera))
    (cond
      ((and state (member :logo modifiers))
       (zoom-output-camera world (%canvas-output-output state) (exp (* -0.0025d0 delta))
                           :anchor-x (%canvas-seat-x seat-state) :anchor-y (%canvas-seat-y seat-state)))
      ((and state group (eq :niri (subworld-kind group))
            (or (member :shift modifiers)
                (not (%target-at-screen-point world state (%canvas-seat-x seat-state) (%canvas-seat-y seat-state)))))
       (pan-output-camera world (%canvas-output-output state)
                          (/ (* delta 2d0) (%canvas-output-zoom state)) 0d0)
       (setf (gethash (subworld-workspace group) (subworld-scrolls group))
             (max 0d0 (- (%canvas-output-camera-x state) (subworld-x group)))))
      (t (call-next-method)))
    (setf (%meta-save-needed-p world) t))
  input)

(defmethod ataxia.kernel:world-key-event ((world metaworld) seat input)
  (let* ((seat-state (%meta-seat world seat))
         (target (and seat-state (%canvas-seat-focused seat-state))))
    (when (typep input 'ataxia.kernel:modifiers-input)
      (let ((names (ataxia.kernel:modifiers-input-names input)))
        (setf (gethash seat (%meta-modifiers world)) names)
        (when seat-state
          (if (every (lambda (modifier) (member modifier names)) '(:logo :shift :control))
              (%begin-view-shift world seat seat-state)
              (%end-view-shift world seat)))))
    (when (typep input 'ataxia.kernel:key-input)
      (setf (gethash seat (%meta-modifiers world)) (ataxia.kernel:key-input-modifiers input)))
    (when (and seat-state
            (eq :forward (ataxia.world:handle-shortcut-input
                          (ataxia.world:world-shortcut-controller world) world seat input))
            (%target-visible-p target))
      (ataxia.kernel:interactable-key-event (%target-component target) world seat input)))
  input)

(defmethod ataxia.kernel:world-client-request :around
    ((world metaworld) (application ataxia.kernel:wayland-application) request)
  (let* ((window (find-canvas-window world application))
         (group (and window (object-subworld world window))))
    (when (and window (typep request '(or ataxia.kernel:move-client-request
                                         ataxia.kernel:resize-client-request)))
      (ataxia.world:cancel-animation (%world-animator world) window :metaworld-layout)
      (let ((seat-state (%meta-seat world (ataxia.kernel:client-request-seat request))))
        (when seat-state
          (ataxia.world:cancel-animation (%world-animator world)
                                        (%canvas-seat-output seat-state) :metaworld-camera))))
    (cond
      ((and group (typep request 'ataxia.kernel:fullscreen-client-request))
       (%meta-toggle-fullscreen world window (ataxia.kernel:state-client-request-value request)))
      ((and group (typep request 'ataxia.kernel:state-client-request)
            (eq :maximized (ataxia.kernel:state-client-request-name request)))
       (%meta-toggle-fullscreen world window (ataxia.kernel:state-client-request-value request)))
      ((and group (typep request 'ataxia.kernel:state-client-request)
            (eq :activation (ataxia.kernel:state-client-request-name request)))
       (let ((member (%meta-member group window)))
         (%meta-switch-workspace world group (subworld-member-workspace member))
         (enter-subworld world group)
         (%meta-focus world window)))
      (t (call-next-method))))
  request)

(defun %meta-adopt-window (world window)
  (when (and window (%canvas-window-mapped-p window)
             (not (gethash window (%meta-initialized-windows world))))
    (setf (gethash window (%meta-initialized-windows world)) t)
    (setf (%meta-pending-launches world)
          (remove-if (lambda (entry) (< (car entry) (%now))) (%meta-pending-launches world)))
    (let ((pending (and (string= "foot" (first (%meta-window-key window)))
                        (pop (%meta-pending-launches world)))))
      (if pending
          (when (member (cdr pending) (metaworld-subworlds world))
            (move-object-to-subworld world window (cdr pending)))
          (unless (%meta-restore-window world window)
        (let ((group (or (%meta-current world)
                         (and (%meta-standalone world) (first (metaworld-subworlds world))))))
          (when (and group (not (object-subworld world window)))
            (move-object-to-subworld world window group))))))
    (%meta-focus world window)))

(defmethod ataxia.kernel:world-register-object :after
    ((world metaworld) (application ataxia.kernel:wayland-application))
  (let ((window (find-canvas-window world application)))
    (when window
      (ataxia.world:cancel-animation (%world-animator world) window :presence)
      (setf (canvas-window-effect window) 0d0
            (canvas-window-scale window) 1d0
            (canvas-window-opacity window) 1d0)
      (set-window-animation-hook
       window :visible
       (lambda (target subject timestamp)
         (setf (canvas-window-opacity subject) 0d0
               (canvas-window-scale subject) 1d0
               (canvas-window-effect subject) 0d0)
         (animate-window target subject :presence 0.14d0
                         (lambda (object progress) (setf (canvas-window-opacity object) progress))
                         :start-time timestamp :easing #'ataxia.world:ease-out-cubic)))
      (%meta-adopt-window world window))))

(defmethod ataxia.kernel:world-object-changed :after ((world metaworld) object change)
  (when (typep object 'ataxia.kernel:wayland-application)
    (let ((window (find-canvas-window world object)))
      (when window
        (when (eq :mapped (ataxia.kernel:object-change-kind change))
          (%meta-adopt-window world window)
          (%meta-layout world (object-subworld world window)))
        (%meta-changed world)))))

(defmethod ataxia.kernel:world-object-invalidated :around ((world metaworld) object invalidation)
  (let* ((window (and (typep object 'ataxia.kernel:wayland-application) (find-canvas-window world object)))
         (geometry (and window (object-subworld world window) (%meta-object-geometry window))))
    (call-next-method)
    (when geometry
      (unless (equal geometry (%meta-object-geometry window))
        (%damage-window world window)
        (setf (canvas-window-x window) (first geometry)
              (canvas-window-y window) (second geometry)
              (canvas-window-width window) (third geometry)
              (canvas-window-height window) (fourth geometry))
        (%damage-window world window)
        (%update-window-membership world window))))
  object)

(defmethod ataxia.kernel:world-unregister-object :before
    ((world metaworld) (application ataxia.kernel:wayland-application) reason)
  (declare (ignore reason))
  (let* ((window (find-canvas-window world application))
         (group (and window (object-subworld world window))))
    (when group
      (setf (subworld-members group)
            (remove window (subworld-members group) :key #'subworld-member-object))
      (when (eq window (subworld-fullscreen group)) (setf (subworld-fullscreen group) nil))
      (remhash window (%meta-owners world))
      (when (eq window (gethash group (%meta-group-focus world)))
        (remhash group (%meta-group-focus world)))
      (%meta-layout world group))
    (when (eq window (%meta-menu-target world)) (setf (%meta-menu-target world) nil))
    (dolist (state (%output-states world))
      (let ((view (%meta-view-for-state world state)))
        (when (eq window (%meta-view-window-target view))
          (setf (%meta-view-window-target view) nil
                (%meta-view-window-controls-until view) 0d0)
          (when (%meta-view-window-controls view)
            (hide-overlay world (%meta-view-window-controls view))))))
    (remhash window (%meta-initialized-windows world))
    (%meta-changed world)))

(defmethod ataxia.kernel:world-output-added :after ((world metaworld) output)
  (let* ((state (gethash output (%world-outputs world)))
         (view (%meta-view-for-state world state)))
    (unless (%meta-restore-camera world state)
      (if (%meta-standalone world)
          (let ((group (first (metaworld-subworlds world))))
            (setf (%meta-view-active view) group)
            (when (= 1 (hash-table-count (%world-outputs world)))
              (multiple-value-bind (width height) (%output-logical-size state)
                (setf (subworld-width group) width (subworld-height group) height)))
            (%meta-fit-group world state group))
          (%meta-overview world nil state)))
    (setf (%meta-view-panel-until view) (+ (%now) 4d0))
    (%meta-sync-ui world state)
    (dolist (record (%meta-saved-notes world))
      (when (and (stringp (getf record :content)) (%meta-valid-geometry-p (getf record :geometry)))
        (let* ((group (find (getf record :owner) (metaworld-subworlds world) :key #'subworld-id))
               (widget (%meta-new-note world group (getf record :content) (getf record :geometry)))
               (member (and group (%meta-member group widget)))
               (data (getf record :member)))
          (when member
            (when (typep (getf data :workspace) '(integer 1 9))
              (setf (subworld-member-workspace member) (getf data :workspace)))
            (when (typep (getf data :column) '(integer 0 1000000))
              (setf (subworld-member-column member) (getf data :column)))
            (when (typep (getf record :order) '(integer 0 1000000))
              (setf (subworld-member-order member) (getf record :order)))
            (when (%meta-valid-number-p (getf data :width) 96 100000)
              (setf (subworld-member-width member) (getf data :width)))
            (when (%meta-valid-number-p (getf data :weight) 0.1d0 100d0)
              (setf (subworld-member-weight member) (getf data :weight)))
            (when (%meta-valid-geometry-p (getf data :restore))
              (setf (subworld-member-restore-geometry member) (getf data :restore)))
            (setf (subworld-member-floating-p member) (not (null (getf data :floating))))
            (when (subworld-member-floating-p member)
              (apply #'%meta-place world widget (getf record :geometry)))
            (setf (subworld-members group)
                  (stable-sort (subworld-members group) #'< :key #'subworld-member-order))
            (%meta-layout world group)))))
    (setf (%meta-saved-notes world) nil)))

(defmethod ataxia.kernel:world-output-changed :after ((world metaworld) output change)
  (unless (eq :backend-damage (ataxia.kernel:object-change-kind change))
    (let* ((state (gethash output (%world-outputs world)))
           (group (and state (%meta-view-active (%meta-view-for-state world state)))))
      (when (and group (%meta-standalone world))
        (multiple-value-bind (width height) (%output-logical-size state)
          (setf (subworld-width group) width (subworld-height group) height))
        (%meta-layout world group))
      (when group (%meta-fit-group world state group))
      (when state (%meta-sync-ui world state)))))

(defmethod ataxia.kernel:world-output-removing :before ((world metaworld) output)
  (let ((state (gethash output (%world-outputs world))))
    (when state (remhash state (%meta-views world))))
  (when (and (%meta-menu world) (eq output (canvas-overlay-output (%meta-menu world))))
    (setf (%meta-menu world) nil)))

(defmethod ataxia.kernel:world-seat-removing :before ((world metaworld) seat)
  (remhash seat (%meta-modifiers world))
  (when (eq seat (getf (%meta-group-drag world) :seat))
    (setf (%meta-group-drag world) nil)))

(defmethod ataxia.kernel:world-attached :after ((world metaworld) kernel)
  (unless (%meta-timer world)
    (setf (%meta-timer world)
          (ataxia.runtime:add-event-loop-timer
           (ataxia.kernel:kernel-runtime kernel)
           (lambda (source)
             (unless (%world-quiescing-p world)
               (ataxia.kernel:call-with-current-world
                kernel
                (lambda (current)
                  (when (eq current world)
                    (dolist (state (%output-states world))
                      (let ((view (%meta-view-for-state world state)))
                        (when (and (%meta-view-panel view)
                                   (canvas-overlay-visible-p (%meta-view-panel view))
                                   (< (%meta-view-panel-until view) (%now)))
                          (hide-overlay world (%meta-view-panel view)))
                        (when (and (%meta-view-window-controls view)
                                   (< (%meta-view-window-controls-until view) (%now)))
                          (hide-overlay world (%meta-view-window-controls view)))))
                    (when (%meta-save-needed-p world) (save-metaworld world))))
                :operation :metaworld-maintenance)
               (ataxia.runtime:update-event-loop-timer source 500))
             0))))
  (ataxia.runtime:update-event-loop-timer (%meta-timer world) 500))

(defmethod ataxia.kernel:world-quiescing :before ((world metaworld) reason)
  (declare (ignore reason))
  (save-metaworld world)
  (when (%meta-timer world)
    (ataxia.runtime:remove-event-loop-source (%meta-timer world))
    (setf (%meta-timer world) nil)))

(defmethod ataxia.kernel:world-render :before ((world metaworld) lease)
  (let* ((state (gethash (ataxia.kernel:frame-output lease) (%world-outputs world)))
         (view (%meta-view-for-state world state))
         (camera (%meta-camera state)))
    (unless (equal camera (%meta-view-last-camera view))
      (setf (%meta-view-last-camera view) camera (%meta-save-needed-p world) t))
    (%meta-sync-ui world state)))

(defmethod %draw-world-background ((world metaworld) renderer state)
  (let* ((view (%meta-view-for-state world state))
         (active (%meta-view-active view))
         (seat-state (find state (%seat-states world) :key #'%canvas-seat-output))
         (drop-target
           (when (and seat-state (or (%canvas-seat-operation seat-state) (%meta-group-drag world)))
             (multiple-value-bind (x y)
                 (%screen-to-world state (%canvas-seat-x seat-state) (%canvas-seat-y seat-state))
               (%meta-group-at world x y)))))
    (dolist (group (metaworld-subworlds world))
      (multiple-value-bind (x y) (%world-to-canvas state (subworld-x group) (subworld-y group))
        (let* ((zoom (%canvas-output-zoom state))
               (width (* zoom (%meta-footprint-width group)))
               (height (* zoom (subworld-height group)))
               (color (if (or (eq group drop-target) (eq group active))
                          '(0.25d0 0.25d0 0.25d0 0.70d0)
                          '(0.58d0 0.58d0 0.58d0 0.55d0))))
          (unless (%meta-standalone world)
            (%draw-solid renderer state x y width height '(1d0 1d0 1d0 0.30d0))
            (%meta-dashed-rectangle renderer state x y width height color)))))))
