;;;; Optional World-owned devices. Runtime only adopts and dispatches their events.
(in-package #:ataxia.world.synthetic-input)
(cffi:defcfun ("ataxia_synthetic_create" %synthetic-create) :pointer (keyboard :boolean) (name :string))
(cffi:defcfun ("ataxia_synthetic_destroy" %synthetic-destroy) :void (object :pointer) (keyboard :boolean))
(cffi:defcfun ("ataxia_synthetic_key" %synthetic-key) :void (keyboard :pointer) (code :uint32) (pressed :boolean) (time :uint32))
(cffi:defcfun ("ataxia_synthetic_keycode" %synthetic-keycode) :int (keyboard :pointer) (name :string))
(cffi:defcfun ("ataxia_synthetic_keymap" %synthetic-keymap) :boolean (keyboard :pointer) (text :string))
(defvar *synthetic-input-library* nil)
(defvar *synthetic-inputs* (make-hash-table :test #'eq))
(defun %ensure-synthetic-input-library ()
  (or *synthetic-input-library*
      (setf *synthetic-input-library*
            (cffi:load-foreign-library (asdf:system-relative-pathname "ataxia-world" "build/libataxia-synthetic-input.so")))))
(defun create-synthetic-input (runtime kind name)
  "Create an unregistered pointer or keyboard; register it on the intended seat."
  (ataxia.runtime::%assert-runtime-live runtime :create-synthetic-input)
  (check-type kind (member :pointer :keyboard))
  (check-type name string)
  (%ensure-synthetic-input-library)
  (let ((pointer (ataxia.runtime::%require-pointer (%synthetic-create (eq kind :keyboard) name) :synthetic-create)))
    (let ((device (ataxia.runtime:adopt-input-device runtime pointer)))
      (setf (gethash device *synthetic-inputs*) t)
      device)))
(defun destroy-synthetic-input (device)
  (when (gethash device *synthetic-inputs*)
    (ataxia.runtime::%assert-owner-thread (ataxia.runtime::%native-runtime device) :destroy-synthetic-input)
    (remhash device *synthetic-inputs*)
    (when (ataxia.runtime:native-object-live-p device)
      (%synthetic-destroy (ataxia.runtime::%object-pointer device) (typep device 'ataxia.runtime:wlr-keyboard))))
  nil)
(defun synthetic-key (keyboard code pressed time)
  (ataxia.runtime::%assert-runtime-live (ataxia.runtime::%native-runtime keyboard) :synthetic-key)
  (unless (and (typep keyboard 'ataxia.runtime:wlr-keyboard) (gethash keyboard *synthetic-inputs*))
    (error "Not an owned synthetic keyboard."))
  (check-type code (integer 0 247))
  (%synthetic-key (ataxia.runtime::%object-pointer keyboard) code pressed time))
(defun synthetic-keycode (keyboard name)
  (ataxia.runtime::%assert-runtime-live (ataxia.runtime::%native-runtime keyboard) :synthetic-keycode)
  (%synthetic-keycode (ataxia.runtime::%object-pointer keyboard) name))
(defun set-keyboard-keymap-from-string (keyboard text)
  (ataxia.runtime::%assert-runtime-live (ataxia.runtime::%native-runtime keyboard) :set-keyboard-keymap-from-string)
  (unless (%synthetic-keymap (ataxia.runtime::%object-pointer keyboard) text)
    (error "Invalid synthetic keyboard keymap."))
  keyboard)
(defmethod ataxia.runtime:runtime-stopping :after ((sink ataxia.runtime:runtime-sink) runtime reason)
  (declare (ignore sink reason))
  (dolist (device (loop for device being the hash-keys of *synthetic-inputs*
                        when (eq runtime (ataxia.runtime::%native-runtime device)) collect device))
    (destroy-synthetic-input device)))
