;;;; Shared options for the interactive World entrypoints.
(in-package #:ataxia.world)

(defun %number-option (text integer-p name)
  (let ((*read-eval* nil))
    (multiple-value-bind (value consumed) (read-from-string text nil nil)
      (unless (and value (= consumed (length text)) (plusp value)
                   (if integer-p (integerp value) (realp value)))
        (error "Invalid ~A value: ~A" name text))
      value)))

(defun parse-compositor-options (arguments)
  "Return a fresh option plist, or :HELP. Used by Atlas, Infinite and Tiling."
  (let ((options (list :backend :auto :width 1280 :height 720
                       :run-for nil :debug-p nil :damage-debug-p nil
                       :sly-port 4005)))
    (labels ((value-after (name)
               (or (pop arguments) (error "Missing value after ~A." name))))
      (loop while arguments
            for option = (pop arguments)
            do (cond
                 ((string= option "--backend")
                  (let ((value (value-after option)))
                    (setf (getf options :backend)
                          (cond ((string= value "auto") :auto)
                                ((string= value "headless") :headless)
                                (t (error "Unknown backend: ~A" value))))))
                 ((string= option "--width")
                  (setf (getf options :width)
                        (%number-option (value-after option) t option)))
                 ((string= option "--height")
                  (setf (getf options :height)
                        (%number-option (value-after option) t option)))
                 ((string= option "--run-for")
                  (setf (getf options :run-for)
                        (%number-option (value-after option) nil option)))
                 ((string= option "--debug")
                  (setf (getf options :debug-p) t))
                 ((string= option "--damage-debug")
                  (setf (getf options :damage-debug-p) t))
                 ((string= option "--sly-port")
                  (let ((port (%number-option (value-after option) t option)))
                    (unless (<= port 65535)
                      (error "Invalid ~A value: ~A" option port))
                    (setf (getf options :sly-port) port)))
                 ((string= option "--no-sly")
                  (setf (getf options :sly-port) nil))
                 ((string= option "--help")
                  (return-from parse-compositor-options :help))
                 (t (error "Unknown option: ~A" option)))))
    options))
