;;;; Desktop services consume this protocol, never a World's private scene state.
;;;; Window handles are opaque World attachments. Kernel applications and outputs
;;;; retain their stable identities across observations and World replacement.
(in-package #:ataxia.world)

(defgeneric world-supports-p (world capability)
  (:documentation "Advertised service capabilities: :UI, :DESKTOP, :WINDOW-CAPTURE, :LAYOUT, :LAUNCHER, :SHELL-NAVIGATION, :VIEWPORT-NAVIGATION. Unsupported optional tools must not be advertised.")
  (:method (world capability) (declare (ignore world capability)) nil))

(defun require-world-capabilities (world &rest capabilities)
  (dolist (capability capabilities)
    (unless (world-supports-p world capability)
      (error "~S does not provide the ~S World service." world capability)))
  world)

(defgeneric world-windows (world)
  (:documentation "Ordered window handles, including mapped but minimized windows."))
(defgeneric window-application (window)
  (:documentation "The Kernel application behind WINDOW, or NIL for a non-window target.")
  (:method ((window application-binding)) (binding-application window))
  (:method ((window ataxia.kernel:wayland-application)) window)
  (:method (window) (declare (ignore window)) nil))
(defun find-world-window (world id)
  (find id (world-windows world)
        :key (lambda (window) (ataxia.kernel:object-id (window-application window)))))
(defgeneric world-window-visible-p (world window &optional output)
  (:documentation "True for an input-visible window, intersecting OUTPUT when supplied. Must reject stale handles and non-windows."))
(defgeneric window-output-bounds (world window output)
  (:documentation "Four values: output-local bounding x, y, width, height."))
(defgeneric window-local-to-output (world window output x y)
  (:documentation "Map application-local coordinates to output-local coordinates."))
(defgeneric output-to-window-local (world window output x y)
  (:documentation "Inverse application placement, including view rotation and scaling."))
(defgeneric world-target-at (world output x y)
  (:documentation "Top input target (window or UI overlay) at an output-local point."))

(defgeneric world-seats (world)
  (:method ((world ataxia.kernel:world))
    (ataxia.kernel:kernel-seats (ataxia.kernel:world-kernel world))))
(defgeneric world-seat-output (world seat))
(defgeneric world-seat-focus (world seat))
(defgeneric world-seat-previous-focus (world seat))
(defgeneric focus-world-target (world seat target &key remember)
  (:documentation "Focus an opaque window or overlay. REMEMBER saves current focus for restoration when UI is hidden."))
(defgeneric world-pointer-position (world seat))
(defgeneric world-active-operation-p (world)
  (:documentation "True while a human is directly manipulating desktop layout."))
(defgeneric world-output-work-area (world output)
  (:documentation "Four values: output-local x, y, width and height available for desktop layout, in logical pixels.")
  (:method (world output)
    (declare (ignore world))
    (multiple-value-bind (width height) (output-logical-size output)
      (values 0d0 0d0 width height))))
(defgeneric world-output-work-area-changed (world output)
  (:documentation "Refit desktop layout after an output's service reservations change.")
  (:method (world output) (declare (ignore world output))))
(defgeneric agent-seat-p (seat)
  (:method (seat) (declare (ignore seat)) nil))
(defgeneric seat-focus-allowed-p (seat target)
  (:method (seat target) (declare (ignore seat target)) t))
(defgeneric seat-raises-focused-window-p (seat)
  (:method (seat) (declare (ignore seat)) t))
(defgeneric present-agent-cursor (world seat output x y tint)
  (:documentation "Move/recolor an agent cursor, damaging old and new coverage. NIL tint removes its customization. Offscreen coordinates hide the cursor."))

(defun world-seat-on-output (world output)
  (find-if (lambda (seat)
             (and (not (agent-seat-p seat))
                  (eq output (world-seat-output world seat))))
           (world-seats world)))

(defgeneric request-world-capture (world output)
  (:documentation "Schedule a fully repainted output frame for a pending capture."))
(defgeneric capture-window-pixels (world window bounds width height pixels)
  (:documentation "Render the application's own surfaces to RGBA PIXELS under the current frame lease; restore all graphics state before returning."))
(defgeneric control-world-window (world window action output)
  (:documentation "Apply :CLOSE, :MINIMIZE, :RESTORE, :MAXIMIZE or :FULLSCREEN according to World policy."))

(defgeneric world-application-catalog (world output)
  (:documentation "Installed launchable applications as plists with :ID, :NAME, :DETAIL. No command is accepted from an agent.")
  (:method (world output) (declare (ignore world output)) nil))
(defgeneric launch-world-application (world output id)
  (:documentation "Launch a trusted catalog entry by ID; return its display name."))

(defgeneric world-shell-state (world output)
  (:documentation "Shell navigation data: :NAME, :SELECTED workspace, :COUNT, :ACTIVE, :GROUP id and :GROUPS (id/name/workspaces with number/count/titles). Destinations use stable group ids.")
  (:method (world output)
    (declare (ignore world output))
    (list :name "Desktop" :selected 0 :count 0 :active nil)))
(defgeneric world-shell-action (world output seat action &optional destination)
  (:documentation "Handle :OVERVIEW, :PREVIOUS, :NEXT, :WORKSPACE, :SELECT-WORKSPACE or :REMOVE-WORKSPACE (group-id workspace-number), and :REMOVE-SUBWORLD (group-id). Removal retains applications; the World chooses their destination."))

(defgeneric navigate-world-viewport (world output action &key x y dx dy zoom rotation width height window padding)
  (:documentation "Validate then change only OUTPUT's camera: :SET, :PAN, :FRAME-WINDOW or :FRAME-REGION. X/Y are world camera origins; DX/DY are world deltas; ROTATION is radians; PADDING is output logical pixels. WINDOW is a stable application ID. Framing never changes window placement, visibility policy or human focus. Reject before mutation.")
  (:method (world output action &key x y dx dy zoom rotation width height window padding)
    (declare (ignore world output action x y dx dy zoom rotation width height window padding))
    (error "This World does not implement viewport navigation.")))

(defgeneric request-clipboard-text (world seat callback)
  (:documentation "Return true if an asynchronous seat-local clipboard read was accepted. Invoke CALLBACK with copied text or NIL on the owner thread.")
  (:method (world seat callback) (declare (ignore world seat callback)) nil))
(defgeneric set-clipboard-text (world seat text)
  (:documentation "Own the UTF-8 clipboard text for this seat; return true when supported.")
  (:method (world seat text) (declare (ignore world seat text)) nil))

(defgeneric world-desktop-state (world)
  (:documentation "A copied data-only desktop observation. Include :WINDOWS with stable :ID entries and :OUTPUTS; Worlds may add layout-specific fields."))

(defun %desktop-window-state (world window)
  (let ((app (window-application window)))
    (list :id (ataxia.kernel:object-id app)
          :title (or (ataxia.kernel:application-title app) "")
          :app-id (or (ataxia.kernel:application-app-id app) "")
          :visible (if (world-window-visible-p world window) t :false)
          :available (if (world-window-visible-p world window) t :false)
          :on-outputs (coerce (loop for output in (world-outputs world)
                                   when (world-window-visible-p world window output)
                                     collect (ataxia.kernel:object-id output)) 'vector)
          :outputs
          (coerce
           (loop for output in (world-outputs world)
                 when (world-window-visible-p world window output)
                   collect (list :output (ataxia.kernel:object-id output)
                                 :geometry
                                 (coerce (multiple-value-list
                                          (window-output-bounds world window output))
                                         'vector)))
           'vector))))

(defun %desktop-output-state (output)
  (multiple-value-bind (width height) (output-logical-size output)
    (list :id (ataxia.kernel:object-id output)
          :name (ataxia.kernel:output-name output)
          :width width :height height
          :transform (ataxia.kernel:output-transform output))))

(defmethod world-desktop-state ((world ataxia.kernel:world))
  (list :windows
        (map 'vector (lambda (window) (%desktop-window-state world window))
             (world-windows world))
        :outputs
        (map 'vector #'%desktop-output-state (world-outputs world))))

(defgeneric world-layout-schema (world)
  (:documentation "Two values: a data-only JSON schema for one layout operation and its description. NIL means layout tools are unavailable.")
  (:method (world) (declare (ignore world)) nil))
(defgeneric validate-world-layout (world operations allowed-window-ids)
  (:documentation "Validate the complete plan without mutation. Reject every affected window outside ALLOWED-WINDOW-IDS, including indirect group members."))
(defgeneric capture-world-layout (world)
  (:documentation "Return an opaque undo snapshot on the owner thread."))
(defgeneric restore-world-layout (world snapshot)
  (:documentation "Restore a previously captured snapshot after the caller checks its desktop revision."))
(defgeneric apply-world-layout (world operations allowed-window-ids)
  (:documentation "Apply a validated plan with World-specific batching. The caller owns rollback, authorization and revision checks."))
