;;;; Packages for reusable World-side mechanisms.
;;;;
;;;; These packages provide protocols and optional services. Concrete Worlds
;;;; retain scene, rendering, and input policy ownership.

(defpackage #:ataxia.world
  (:use #:cl)
  (:export
   #:attach-world-service #:detach-world-service #:world-service
   #:service-quiescing #:service-output-added #:service-output-changed
   #:service-output-removing #:service-object-removing #:service-object-changed
   #:service-seat-removing
   #:service-before-render #:service-after-render
   #:service-pointer-button #:service-key-event
   #:world-supports-p
   #:require-world-capabilities
   #:world-windows
   #:window-application
   #:find-world-window
   #:world-window-visible-p
   #:window-output-bounds
   #:window-local-to-output
   #:output-to-window-local
   #:world-target-at
   #:world-seats
   #:world-seat-output
   #:world-seat-focus
   #:world-seat-previous-focus
   #:focus-world-target
   #:world-pointer-position
   #:world-active-operation-p
   #:agent-seat-p
   #:seat-focus-allowed-p
   #:seat-raises-focused-window-p
   #:present-agent-cursor
   #:world-seat-on-output
   #:request-world-capture
   #:capture-window-pixels
   #:control-world-window
   #:world-application-catalog
   #:launch-world-application
   #:world-shell-state
   #:world-shell-action
   #:navigate-world-viewport
   #:world-output-work-area #:world-output-work-area-changed #:service-output-insets
   #:service-selection-changed #:request-clipboard-text #:set-clipboard-text
   #:world-desktop-state #:world-layout-schema #:validate-world-layout
   #:capture-world-layout #:restore-world-layout #:apply-world-layout
   #:ui-host
   #:ui-overlay
   #:make-overlay
   #:overlay-component
   #:overlay-output
   #:overlay-x
   #:overlay-y
   #:overlay-width
   #:overlay-height
   #:overlay-layer
   #:overlay-visible-p
   #:overlay-opacity
   #:overlay-visibility-changed
   #:overlay-output-changed
   #:destroy-overlay
   #:overlay-input-enabled-p
   #:world-outputs
   #:world-overlays
   #:add-overlay
   #:remove-overlay
   #:show-overlay
   #:hide-overlay
   #:damage-overlay
   #:request-overlay-update
   #:monotonic-time
   #:output-logical-size
   #:require-world-output
   #:create-agent-widget
   #:position-widget
   #:expire-agent-widget
   #:agent-widget
   #:agent-widget-world
   #:agent-widget-id
   #:agent-widget-event
   #:agent-widget-event-sequence
   #:agent-widget-event-name
   #:agent-widget-event-value
   #:agent-widget-event-timestamp
   #:find-agent-widget
   #:list-agent-widgets
   #:remove-agent-widget
   #:configure-agent-widget
   #:set-agent-widget-property
   #:bind-agent-widget-event
   #:agent-widget-events
   #:parse-compositor-options
   #:ui-raster-scale
   #:ui-resize
   #:ui-destroy
   #:ui-set-invalidator
   #:ui-set-property
   #:ui-set-callback
   #:ui-service-key
   #:ui-service
   #:ui-dispatch-callbacks
   #:ui-next-update-delay
   #:transform-normalized-point
   #:rectangle
   #:make-rectangle
   #:rectangle-x
   #:rectangle-y
   #:rectangle-width
   #:rectangle-height
   #:rectangle-right
   #:rectangle-bottom
   #:rectangle-pixel-bounds
   #:rectangle-empty-p
   #:rectangle-area
   #:rectangle-intersection
   #:rectangle-union
   #:normalize-region
   #:clip-region
   #:region-intersects-p
   #:subtract-region
   #:coalesce-damage-region
   #:region-to-frame-damage
   #:frame-damage-to-region
   #:application-binding
   #:binding-application
   #:shortcut-binding
   #:make-shortcut-binding
   #:shortcut-binding-id
   #:shortcut-binding-key-kind
   #:shortcut-binding-key
   #:shortcut-binding-modifiers
   #:shortcut-binding-exact-modifiers-p
   #:shortcut-binding-priority
   #:shortcut-binding-press-handler
   #:shortcut-binding-release-handler
   #:shortcut-binding-repeat-p
   #:shortcut-binding-predicate
   #:shortcut-binding-consume-p
   #:shortcut-binding-enabled-p
   #:shortcut-controller
   #:make-shortcut-controller
   #:shortcut-controller-revision
   #:add-shortcut
   #:remove-shortcut
   #:replace-shortcut
   #:replace-shortcuts
   #:find-shortcut
   #:list-shortcuts
   #:enable-shortcut
   #:disable-shortcut
   #:clear-shortcuts
   #:update-shortcuts
   #:define-shortcuts
   #:shortcut-ambiguity
   #:shortcut-ambiguity-bindings
   #:shortcut-ambiguity-input
   #:world-shortcut-controller
   #:handle-shortcut-input
   #:forget-shortcut-seat
   #:animator
   #:make-animator
   #:start-animation
   #:cancel-animation
   #:cancel-subject-animations
   #:advance-animations
   #:animations-active-p
   #:animation-subjects
   #:linear-easing
   #:ease-in-cubic
   #:ease-out-cubic
   #:ease-in-out-cubic
   #:damage-tracker
   #:make-damage-tracker
   #:damage-add-region
   #:damage-full-output
   #:damage-reset-output
   #:damage-forget-output
   #:damage-pending-p
   #:damage-begin-frame
   #:damage-commit-frame
   #:damage-fail-frame
   #:damage-frame-region
   #:damage-debug-mode-p
   #:set-damage-debug-mode
   #:refresh-world
   #:world-operation-rejected
   #:world-operation-rejected-cause
   #:agent-event
   #:agent-event-sequence
   #:agent-event-source
   #:agent-event-name
   #:agent-event-value
   #:agent-event-timestamp
   #:agent-event-stream
   #:make-agent-event-stream
   #:world-agent-event-stream
   #:publish-agent-event
   #:wait-agent-events
   #:close-agent-event-stream
   #:interaction-delivered-p
   #:rescue-world
   #:make-rescue-world))

(defpackage #:ataxia.world.gles
  (:use #:cl)
  (:export
   #:+texture-2d+
   #:+texture-external-oes+
   #:gles-program
   #:make-gles-program
   #:destroy-gles-program
   #:gles-program-handle
   #:gles-use-program
   #:gles-uniform-location
   #:gles-uniform-1f
   #:gles-uniform-1i
   #:gles-uniform-2f
   #:gles-uniform-4f
   #:gles-create-buffer
   #:gles-destroy-buffer
   #:gles-upload-floats
   #:gles-enable-attribute
   #:gles-disable-attribute
   #:gles-bind-texture
   #:call-with-gles-linear-filter
   #:gles-clear
   #:gles-set-scissor
   #:gles-set-scissor-enabled
   #:gles-set-blending-enabled
   #:gles-reset-state
   #:gles-draw-triangles
   #:gles-flush
   #:gles-check-error))
