;;;; Optional services compose without replacing one another's Kernel methods.
(in-package #:ataxia.world)

(defvar *world-services* (make-hash-table :test #'eq :weakness :key))

(defun attach-world-service (world key service)
  "Attach SERVICE under KEY. A key has at most one owner in each World."
  (let ((entry (assoc key (gethash world *world-services*))))
    (when (and entry (not (eq service (cdr entry))))
      (error "World service ~S is already attached." key))
    (unless entry
      (setf (gethash world *world-services*)
            (append (gethash world *world-services*) (list (cons key service))))))
  service)

(defun detach-world-service (world key)
  (let ((remaining (remove key (gethash world *world-services*) :key #'car)))
    (if remaining (setf (gethash world *world-services*) remaining)
        (remhash world *world-services*)))
  world)

(defun world-service (world key)
  (cdr (assoc key (gethash world *world-services*))))

(defgeneric service-quiescing (service world reason)
  (:method (service world reason) (declare (ignore service world reason))))
(defgeneric service-output-added (service world output)
  (:method (service world output) (declare (ignore service world output))))
(defgeneric service-output-changed (service world output change)
  (:method (service world output change) (declare (ignore service world output change))))
(defgeneric service-output-removing (service world output)
  (:method (service world output) (declare (ignore service world output))))
(defgeneric service-output-insets (service world output)
  (:documentation "Four logical-pixel reservations: left, top, right, bottom. Reservations on the same edge combine by maximum.")
  (:method (service world output)
    (declare (ignore service world output)) (values 0d0 0d0 0d0 0d0)))

(defmethod world-output-work-area :around ((world ataxia.kernel:world) output)
  (multiple-value-bind (x y width height) (call-next-method)
    (let ((left 0d0) (top 0d0) (right 0d0) (bottom 0d0))
      (dolist (entry (gethash world *world-services*))
        (multiple-value-bind (l u r b) (service-output-insets (cdr entry) world output)
          (setf left (max left l) top (max top u) right (max right r) bottom (max bottom b))))
      (setf left (min left (max 0d0 (1- width)))
            top (min top (max 0d0 (1- height))))
      (values (+ x left) (+ y top) (max 1d0 (- width left right)) (max 1d0 (- height top bottom))))))
(defgeneric service-object-removing (service world object reason)
  (:method (service world object reason) (declare (ignore service world object reason))))
(defgeneric service-object-changed (service world object change)
  (:method (service world object change) (declare (ignore service world object change))))
(defgeneric service-seat-removing (service world seat)
  (:method (service world seat) (declare (ignore service world seat))))
(defgeneric service-selection-changed (service world seat)
  (:method (service world seat) (declare (ignore service world seat))))
(defgeneric service-before-render (service world lease)
  (:method (service world lease) (declare (ignore service world lease))))
(defgeneric service-after-render (service world lease)
  (:method (service world lease) (declare (ignore service world lease))))
(defgeneric service-pointer-button (service world seat input)
  (:documentation "Observe a human button event before World policy handles it.")
  (:method (service world seat input) (declare (ignore service world seat input))))
(defgeneric service-key-event (service world seat input)
  (:documentation "Return true to consume a service shortcut before World policy.")
  (:method (service world seat input) (declare (ignore service world seat input)) nil))

(defun %dispatch-services (world function &rest arguments)
  ;; Snapshot the list: callbacks may detach themselves during cleanup.
  (dolist (entry (copy-list (gethash world *world-services*)))
    (apply function (cdr entry) world arguments)))

(defmethod ataxia.kernel:world-quiescing :before ((world ataxia.kernel:world) reason)
  (%dispatch-services world #'service-quiescing reason))
(defmethod ataxia.kernel:world-output-added :after ((world ataxia.kernel:world) output)
  (%dispatch-services world #'service-output-added output))
(defmethod ataxia.kernel:world-output-changed :after ((world ataxia.kernel:world) output change)
  (%dispatch-services world #'service-output-changed output change))
(defmethod ataxia.kernel:world-output-removing :before ((world ataxia.kernel:world) output)
  (%dispatch-services world #'service-output-removing output))
(defmethod ataxia.kernel:world-unregister-object :before ((world ataxia.kernel:world) object reason)
  (%dispatch-services world #'service-object-removing object reason))
(defmethod ataxia.kernel:world-object-changed :before ((world ataxia.kernel:world) object change)
  (%dispatch-services world #'service-object-changed object change))
(defmethod ataxia.kernel:world-seat-removing :before ((world ataxia.kernel:world) seat)
  (%dispatch-services world #'service-seat-removing seat))
(defmethod ataxia.kernel:world-seat-selection-changed :after ((world ataxia.kernel:world) seat)
  (%dispatch-services world #'service-selection-changed seat))
(defmethod ataxia.kernel:world-render :around ((world ataxia.kernel:world) lease)
  (%dispatch-services world #'service-before-render lease)
  (prog1 (call-next-method)
    (%dispatch-services world #'service-after-render lease)))
(defmethod ataxia.kernel:world-cursor-button :around
    ((world ataxia.kernel:world) (seat ataxia.kernel:logical-seat) input)
  (unless (agent-seat-p seat)
    (%dispatch-services world #'service-pointer-button seat input))
  (call-next-method))
(defmethod ataxia.kernel:world-key-event :around
    ((world ataxia.kernel:world) (seat ataxia.kernel:logical-seat) input)
  (if (and (not (agent-seat-p seat))
           (some (lambda (entry) (service-key-event (cdr entry) world seat input))
                 (copy-list (gethash world *world-services*))))
      input
      (call-next-method)))
