;;;; A World-owned native UI application uses the same scene binding and input
;;;; contracts as a client window. No Wayland object or Kernel registration is faked.
(in-package #:ataxia.world)

(defvar *next-ui-application-id* #x100000000)
(defvar *ui-application-errors* (make-hash-table :test #'eq :weakness :key))
(defclass ui-application (ataxia.kernel:drawable ataxia.kernel:interactable)
  ((component :initarg :component :reader ui-application-component)
   (world :initarg :world :reader %ui-application-world)
   (id :initform (incf *next-ui-application-id*) :reader ataxia.kernel:object-id)
   (title :initarg :title :reader ataxia.kernel:application-title)
   (app-id :initarg :app-id :reader ataxia.kernel:application-app-id)
   (mapped :initform t :accessor ataxia.kernel:application-mapped-p)
   (close :initarg :close :reader %ui-application-close)
   (destroyed :initform nil :accessor %ui-application-destroyed)
   (revision :initform 0 :accessor %ui-application-revision)))

(defclass ui-application-service ()
  ((applications :initform nil :accessor %ui-applications)
   (retired :initform nil :accessor %ui-retired)
   (stopped :initform nil :accessor %ui-stopped)))

(defun %ui-application-window (application)
  (find application (world-windows (%ui-application-world application)) :key #'window-application))
(defun %ui-application-visible-p (application)
  (let* ((world (%ui-application-world application)) (window (%ui-application-window application)))
    (and window (ataxia.kernel:application-mapped-p application)
         (some (lambda (output) (world-window-visible-p world window output)) (world-outputs world)))))
(defun %invalidate-ui-application (application)
  (unless (%ui-application-destroyed application)
    (let* ((world (%ui-application-world application))
           (service (world-service world :ui-applications)))
      (when (and service (not (%ui-stopped service)))
        (multiple-value-bind (x y width height)
            (ataxia.kernel:drawable-local-bounds application)
          (ataxia.kernel:world-object-invalidated world application
            (ataxia.kernel:make-drawable-invalidation
             (incf (%ui-application-revision application))
             (region-to-frame-damage (list (make-rectangle x y width height))
                                    (ceiling width) (ceiling height)))))))))

(defun make-ui-application (world component &key (title "Untitled") (app-id "ataxia.ui") close)
  "Give a drawable/interactable UI component ordinary World window lifetime.
CLOSE can save asynchronously and then call HIDE-UI-APPLICATION."
  (require-world-capabilities world :ui-windows)
  (check-type component (and ataxia.kernel:drawable ataxia.kernel:interactable))
  (let* ((service (or (world-service world :ui-applications)
                      (attach-world-service world :ui-applications (make-instance 'ui-application-service))))
         (application (make-instance 'ui-application :world world :component component
                                    :title title :app-id app-id :close close)))
    (push application (%ui-applications service))
    (ui-set-invalidator component
      (lambda (ignored)
        (declare (ignore ignored))
        ;; Engine notifications arrive through an event FD, outside a World
        ;; render dispatch. An application error must not unwind the event loop.
        (handler-case (%invalidate-ui-application application)
          (error (cause)
            (setf (gethash application *ui-application-errors*) cause)
            (ui-set-invalidator component nil)
            (warn "UI application ~A stopped updating: ~A" title cause)))))
    (handler-case
        (progn
          (ataxia.kernel:world-register-object world application)
          (unless (%ui-application-window application)
            (error "World did not attach its UI application window."))
          (%invalidate-ui-application application)
          application)
      (error (cause)
        (ui-set-invalidator component nil)
        (when (%ui-application-window application)
          (ataxia.kernel:world-unregister-object world application :creation-failed))
        (setf (%ui-applications service) (remove application (%ui-applications service))
              (%ui-application-destroyed application) t)
        (push application (%ui-retired service))
        (refresh-world world)
        (error cause)))))

(defun show-ui-application (application)
  (unless (ataxia.kernel:application-mapped-p application)
    (setf (ataxia.kernel:application-mapped-p application) t)
    (ataxia.kernel:world-object-changed (%ui-application-world application) application
      (ataxia.kernel:make-object-change :mapped t)))
  (let* ((world (%ui-application-world application)) (window (%ui-application-window application))
         (seat (find-if-not #'agent-seat-p (world-seats world))))
    (when window
      (control-world-window world window :restore (first (world-outputs world)))
      (when seat (focus-world-target world seat window))))
  (%invalidate-ui-application application)
  application)
(defun hide-ui-application (application)
  (when (ataxia.kernel:application-mapped-p application)
    (setf (ataxia.kernel:application-mapped-p application) nil)
    (ataxia.kernel:request-object-state (ui-application-component application) (%ui-application-world application) :visible nil)
    (ataxia.kernel:world-object-changed (%ui-application-world application) application
      (ataxia.kernel:make-object-change :mapped nil)))
  application)
(defun remove-ui-application (application)
  (unless (%ui-application-destroyed application)
    (let* ((world (%ui-application-world application)) (service (world-service world :ui-applications)))
      (hide-ui-application application)
      (ui-set-invalidator (ui-application-component application) nil)
      (ataxia.kernel:world-unregister-object world application :closed)
      (setf (%ui-applications service) (remove application (%ui-applications service))
            (%ui-application-destroyed application) t)
      (push application (%ui-retired service))
      (refresh-world world)))
  nil)
(defun %reap-ui-applications (service)
  (dolist (app (%ui-retired service))
    (ataxia.kernel:drawable-detach-graphics (ui-application-component app))
    (ui-destroy (ui-application-component app)))
  (setf (%ui-retired service) nil))

(defmethod service-before-render ((service ui-application-service) world lease)
  (declare (ignore lease))
  (%reap-ui-applications service)
  (unless (%ui-stopped service)
    (dolist (app (%ui-applications service))
      (let* ((component (ui-application-component app)) (visible (%ui-application-visible-p app)))
        (ataxia.kernel:request-object-state component world :visible (not (null visible)))
        (when visible
          (multiple-value-bind (damage active) (ataxia.kernel:drawable-prepare-frame app)
            (when damage (%invalidate-ui-application app))
            (when active (%invalidate-ui-application app))))))))
(defmethod service-quiescing ((service ui-application-service) world reason)
  (declare (ignore world reason))
  (setf (%ui-stopped service) t)
  (dolist (app (%ui-applications service))
    (ui-set-invalidator (ui-application-component app) nil)))
(defmethod ataxia.kernel:world-graphics-detaching :before ((world ataxia.kernel:world) context reason)
  (declare (ignore context reason))
  (let ((service (world-service world :ui-applications)))
    (when service
      (dolist (app (%ui-applications service))
        (ataxia.kernel:drawable-detach-graphics app)
        (when (%ui-stopped service) (ui-destroy (ui-application-component app))))
      (%reap-ui-applications service)
      (when (%ui-stopped service) (detach-world-service world :ui-applications)))))

(defmacro %delegate-ui-drawable (name)
  `(defmethod ,name ((application ui-application))
     (,name (ui-application-component application))))
(%delegate-ui-drawable ataxia.kernel:drawable-local-bounds)
(%delegate-ui-drawable ataxia.kernel:drawable-surfaces)
(%delegate-ui-drawable ataxia.kernel:drawable-active-p)
(%delegate-ui-drawable ataxia.kernel:drawable-attach-graphics)
(%delegate-ui-drawable ataxia.kernel:drawable-detach-graphics)
(%delegate-ui-drawable ataxia.kernel:drawable-prepare-frame)
(defmacro %delegate-ui-input (name arguments)
  `(defmethod ,name ((application ui-application) ,@arguments)
     (,name (ui-application-component application) ,@arguments)))
(%delegate-ui-input ataxia.kernel:interactable-hit-test (world x y))
(%delegate-ui-input ataxia.kernel:interactable-pointer-motion (world seat x y input))
(%delegate-ui-input ataxia.kernel:interactable-pointer-button (world seat x y input))
(%delegate-ui-input ataxia.kernel:interactable-pointer-axis (world seat x y input))
(%delegate-ui-input ataxia.kernel:interactable-pointer-leave (world seat))
(%delegate-ui-input ataxia.kernel:interactable-key-event (world seat input))
(%delegate-ui-input ataxia.kernel:interactable-focus (world seat kind))
(defmethod ataxia.kernel:request-object-configuration ((app ui-application) world configuration)
  (declare (ignore world))
  (multiple-value-bind (x y width height) (ataxia.kernel:drawable-local-bounds app)
    (declare (ignore x y))
    (let ((w (ataxia.kernel:configuration-width configuration)) (h (ataxia.kernel:configuration-height configuration)))
      (ui-resize (ui-application-component app) (if (eq w :unchanged) width (max 1 w))
                 (if (eq h :unchanged) height (max 1 h)))))
  (%invalidate-ui-application app)
  app)
(defmethod ataxia.kernel:request-object-state ((app ui-application) world state value)
  (declare (ignore world))
  (when (and (eq state :close) value)
    (if (%ui-application-close app) (funcall (%ui-application-close app) app) (remove-ui-application app)))
  app)
