;;;; Optional native UI operations, owned and scheduled by Worlds.
(in-package #:ataxia.world)
(defgeneric ui-raster-scale (component)
  (:method (component) (declare (ignore component)) nil))
(defgeneric ui-resize (component width height &key scale))
(defgeneric ui-destroy (component))
(defgeneric ui-set-invalidator (component function))
(defgeneric ui-set-property (component name value))
(defgeneric ui-set-callback (component name function))
(defgeneric ui-service-key (component)
  (:method (component) (declare (ignore component)) nil))
(defgeneric ui-service (component)
  (:method (component) (declare (ignore component)) nil))
(defgeneric ui-next-update-delay (component)
  (:documentation "Milliseconds until work is due, or NIL. Zero is paced by output frames.")
  (:method (component) (declare (ignore component)) nil))
