;;;; Bounded JSON data codec for local line-oriented World protocols.
;;;; No input is passed to the Lisp reader, evaluator, or package interner.
;;;; The file stands alone so command-line clients can load it without ASDF.
(defpackage #:ataxia.world.wire
  (:use #:cl)
  (:export #:decode #:encode #:read-line-bytes #:write-line-bytes))
(in-package #:ataxia.world.wire)

(defun read-line-bytes (stream &optional (maximum 65536))
  (let ((bytes (make-array 256 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
    (loop for byte = (read-byte stream nil nil) do
	  (unless byte (error "The JSON line ended before its newline."))
	  (when (= byte 10) (return (sb-ext:octets-to-string bytes :external-format :utf-8)))
	  (when (>= (length bytes) maximum) (error "JSON line exceeds the size limit."))
	  (vector-push-extend byte bytes))))

(defun write-line-bytes (stream text)
  (write-sequence (sb-ext:string-to-octets text :external-format :utf-8) stream)
  (write-byte 10 stream)
  (finish-output stream))

(defun decode (text &key (max-string 4096) (max-nodes 4096) (max-depth 8))
  (let ((position 0) (nodes 0) (size (length text)))
    (labels
        ((peek () (when (< position size) (char text position)))
         (take () (or (prog1 (peek) (incf position)) (error "Incomplete JSON value.")))
         (skip-space () (loop while (member (peek) '(#\Space #\Tab #\Newline #\Return)) do (incf position)))
         (expect (character) (unless (eql (take) character) (error "Unexpected JSON character.")))
         (hex4 () (let ((number 0))
                    (dotimes (i 4 number)
                      (let ((digit (digit-char-p (take) 16)))
                        (unless digit (error "Invalid JSON Unicode escape."))
                        (setf number (+ (* number 16) digit))))))
         (string-value ()
           (expect #\")
           (with-output-to-string (out)
             (loop for count from 0 for character = (take) do
		   (when (eql character #\") (return))
		   (when (>= count max-string) (error "JSON string is too long."))
		   (when (< (char-code character) 32) (error "Unescaped JSON control character."))
		   (when (eql character #\\)
                     (setf character
			   (case (take)
                             (#\" #\") (#\\ #\\) (#\/ #\/) (#\b #\Backspace)
                             (#\f #\Page) (#\n #\Newline) (#\r #\Return) (#\t #\Tab)
                             (#\u
                              (let ((code (hex4)))
				(cond
				  ((<= #xd800 code #xdbff)
				   (expect #\\) (expect #\u)
				   (let ((low (hex4)))
                                     (unless (<= #xdc00 low #xdfff) (error "Invalid Unicode surrogate pair."))
                                     (setf code (+ #x10000 (* (- code #xd800) 1024) (- low #xdc00)))))
				  ((<= #xdc00 code #xdfff) (error "Unexpected low Unicode surrogate.")))
				(or (code-char code) (error "Invalid Unicode character."))))
                             (otherwise (error "Unknown JSON escape.")))))
		   (write-char character out))))
         (digits ()
           (let ((start position))
             (loop while (and (peek) (digit-char-p (peek) 10)) do (incf position))
             (when (= start position) (error "Expected JSON number digits."))
             (when (> (- position start) 32) (error "JSON number is too long."))
             (values (parse-integer text :start start :end position) (- position start))))
         (number-value ()
           (let ((sign 1) (fraction 0d0) (exponent 0) (floating nil))
             (when (eql (peek) #\-) (setf sign -1) (take))
             (let ((whole (if (eql (peek) #\0) (progn (take) 0) (digits))))
               (when (eql (peek) #\.)
                 (take) (setf floating t)
                 (multiple-value-bind (part count) (digits) (setf fraction (/ part (expt 10d0 count)))))
               (when (member (peek) '(#\e #\E))
                 (take) (setf floating t)
                 (let ((exponent-sign 1))
                   (when (member (peek) '(#\+ #\-)) (when (eql (take) #\-) (setf exponent-sign -1)))
                   (let ((magnitude (digits)))
                     (when (> magnitude 308) (error "JSON exponent is out of range."))
                     (setf exponent (* exponent-sign magnitude)))))
               (let ((value (if floating (* sign (+ whole fraction) (expt 10d0 exponent)) (* sign whole))))
                 (unless (<= (abs value) (expt 2 53)) (error "JSON number is out of range."))
                 value))))
         (literal (word value)
           (loop for character across word do (expect character)) value)
         (array-value (depth)
           (expect #\[) (skip-space)
           (when (eql (peek) #\]) (take) (return-from array-value #()))
           (let ((values nil))
             (loop
              (push (value (1+ depth)) values) (skip-space)
              (case (take)
                (#\] (return (coerce (nreverse values) 'vector)))
                (#\, (skip-space))
                (otherwise (error "Invalid JSON array separator."))))))
         (object-value (depth)
           (expect #\{) (skip-space)
           (let ((object (make-hash-table :test #'equal)))
             (when (eql (peek) #\}) (take) (return-from object-value object))
             (loop
              (let ((key (string-value)))
                (when (nth-value 1 (gethash key object)) (error "Duplicate JSON object key."))
                (skip-space) (expect #\:) (skip-space)
                (setf (gethash key object) (value (1+ depth))))
              (skip-space)
              (case (take)
                (#\} (return object))
                (#\, (skip-space))
                (otherwise (error "Invalid JSON object separator."))))))
         (value (depth)
           (when (or (> depth max-depth) (> (incf nodes) max-nodes)) (error "JSON structure exceeds its bounds."))
           (skip-space)
           (case (peek)
             (#\" (string-value)) (#\{ (object-value depth)) (#\[ (array-value depth))
             (#\t (literal "true" t)) (#\f (literal "false" :false)) (#\n (literal "null" nil))
             (otherwise
              (if (or (eql (peek) #\-) (and (peek) (digit-char-p (peek) 10)))
                  (number-value) (error "Invalid JSON value."))))))
      (let ((result (value 0)))
        (skip-space)
        (unless (= position size) (error "Unexpected data after JSON value."))
        result))))

(defun encode (value)
  (with-output-to-string (stream)
    (labels ((emit (x)
               (cond ((eq x t) (write-string "true" stream))
                     ((eq x :false) (write-string "false" stream))
                     ((null x) (write-string "null" stream))
                     ((stringp x)
                      ;; Line and paragraph separators are escaped too, so the
                      ;; output is also a valid JavaScript string literal.
                      (write-char #\" stream)
                      (loop for c across x for code = (char-code c) do
                            (case c
                              (#\" (write-string "\\\"" stream)) (#\\ (write-string "\\\\" stream))
                              (otherwise (if (or (< code 32) (= code #x2028) (= code #x2029))
                                             (format stream "\\u~4,'0X" code)
                                             (write-char c stream)))))
                      (write-char #\" stream))
                     ((numberp x)
                      (if (integerp x) (princ x stream) (format stream "~,6F" (coerce x 'double-float))))
                     ((hash-table-p x)
                      (write-char #\{ stream)
                      (let ((first t))
                        (maphash (lambda (key item)
                                   (unless first (write-char #\, stream)) (setf first nil)
                                   (emit key) (write-char #\: stream) (emit item)) x))
                      (write-char #\} stream))
                     ((vectorp x)
                      (write-char #\[ stream)
                      (loop for item across x for i from 0 do
                            (when (> i 0) (write-char #\, stream)) (emit item))
                      (write-char #\] stream))
                     ((listp x)
                      (write-char #\{ stream)
                      (loop for (key item) on x by #'cddr for i from 0 do
                            (when (> i 0) (write-char #\, stream))
                            (emit (string-downcase (symbol-name key))) (write-char #\: stream) (emit item))
                      (write-char #\} stream))
                     (t (error "Cannot encode JSON value.")))))
      (emit value))))
