(in-package #:ataxia.world.slint)
(defmethod ataxia.world:ui-raster-scale ((component slint-component))
  (slint-component-scale component))
(defmethod ataxia.world:ui-resize ((component slint-component) width height
                                  &key (scale (slint-component-scale component)))
  (resize-slint-component component width height :scale scale))
(defmethod ataxia.world:ui-destroy ((component slint-component))
  (destroy-slint-component component))
(defmethod ataxia.world:ui-set-invalidator ((component slint-component) function)
  (set-slint-component-invalidator component function))
(defmethod ataxia.world:ui-set-property ((component slint-component) name value)
  (set-slint-property component name value))
(defmethod ataxia.world:ui-set-callback ((component slint-component) name function)
  (set-slint-callback component name function))
(defmethod ataxia.world:ui-service-key ((component slint-component)) :slint)
(defmethod ataxia.world:ui-service ((component slint-component)) (update-slint-timers))
(defmethod ataxia.world:ui-next-update-delay ((component slint-component))
  (let ((delay (slint-next-timer-milliseconds)))
    (unless (= delay #xffffffffffffffff) delay)))
