;;;; Layer 1 package boundaries.
;;;;
;;;; ATAXIA.LAYER1.RAW is private ABI surface. ATAXIA.LAYER1 exports typed
;;;; wrappers, exact callback generics, and runtime lifecycle operations.

(defpackage #:ataxia.layer1.raw
  (:use #:cl #:cffi)
  (:export
   #:+expected-glue-abi+
   #:+expected-wlroots-version+
   #:load-native-libraries
   #:verify-native-abi
   #:null-pointer
   #:null-pointer-p
   #:pointer-address
   #:foreign-string-to-lisp
   #:%wl-display-create
   #:%wl-display-destroy
   #:%wl-display-destroy-clients
   #:%wl-display-get-event-loop
   #:%wl-display-add-socket-auto
   #:%wl-display-flush-clients
   #:%wl-event-loop-dispatch
   #:%wlr-log-init
   #:%wlr-backend-autocreate
   #:%wlr-headless-backend-create
   #:%wlr-headless-add-output
   #:%wlr-backend-start
   #:%wlr-backend-destroy
   #:%wlr-renderer-autocreate
   #:%wlr-renderer-init-wl-display
   #:%wlr-renderer-destroy
   #:%wlr-allocator-autocreate
   #:%wlr-allocator-destroy
   #:%wlr-compositor-create
   #:%wlr-subcompositor-create
   #:%wlr-seat-create
   #:%wlr-seat-destroy
   #:%wlr-seat-set-capabilities
   #:%wlr-seat-set-name
   #:%glue-listener-create
   #:%glue-listener-attach
   #:%glue-listener-detach
   #:%glue-listener-destroy
   #:%backend-event-destroy
   #:%backend-event-new-input
   #:%backend-event-new-output
   #:%renderer-event-destroy
   #:%renderer-event-lost
   #:%allocator-event-destroy
   #:%compositor-event-new-surface
   #:%compositor-event-destroy
   #:%output-event-frame
   #:%output-event-destroy
   #:%output-name
   #:%output-description
   #:%output-width
   #:%output-height
   #:%output-enabled
   #:%input-device-event-destroy
   #:%input-device-name
   #:%input-device-type
   #:%surface-event-commit
   #:%surface-event-map
   #:%surface-event-unmap
   #:%surface-event-new-subsurface
   #:%surface-event-destroy
   #:%surface-current-committed
   #:%surface-current-sequence
   #:%surface-current-width
   #:%surface-current-height
   #:%surface-current-buffer-width
   #:%surface-current-buffer-height
   #:%surface-mapped
   #:%listener-dispatch-pointer))

(defpackage #:ataxia.layer1
  (:use #:cl)
  (:export
   #:layer1-error
   #:native-call-failed
   #:native-call-name
   #:native-call-detail
   #:native-abi-mismatch
   #:dead-native-object
   #:wrong-owner-thread
   #:callback-fault
   #:callback-fault-signal
   #:callback-fault-cause
   #:native-object
   #:native-object-live-p
   #:native-object-address
   #:wlr-output
   #:output-name
   #:output-description
   #:output-width
   #:output-height
   #:output-enabled-p
   #:wlr-input-device
   #:input-device-name
   #:input-device-type
   #:wlr-surface
   #:surface-mapped-p
   #:surface-commit-event
   #:surface-commit-sequence
   #:surface-commit-fields
   #:surface-commit-width
   #:surface-commit-height
   #:surface-commit-buffer-width
   #:surface-commit-buffer-height
   #:surface-commit-mapped-p
   #:wlr-seat
   #:layer1-sink
   #:diagnostic-sink
   #:layer1-runtime
   #:runtime-state
   #:runtime-socket-name
   #:runtime-backend-kind
   #:runtime-outputs
   #:runtime-input-devices
   #:runtime-surfaces
   #:runtime-last-fault
   #:runtime-started
   #:runtime-stopping
   #:backend-new-output
   #:backend-new-input
   #:backend-destroying
   #:renderer-lost
   #:compositor-new-surface
   #:output-frame
   #:output-destroying
   #:input-device-destroying
   #:surface-committed
   #:surface-mapped
   #:surface-unmapped
   #:surface-new-subsurface
   #:surface-destroying
   #:create-layer1-runtime
   #:start-layer1-runtime
   #:run-layer1-runtime
   #:request-layer1-stop
   #:destroy-layer1-runtime
   #:call-with-layer1-runtime
   #:create-seat
   #:set-seat-capabilities
   #:set-seat-name
   #:destroy-seat
   #:main))
