;;;; PulseAudio's public client ABI also controls PipeWire's pulse server.
;;;; One Lisp worker owns the context and mainloop; callbacks never touch UI.
(in-package #:ataxia.world.shell)
(cffi:define-foreign-library shell-pulse (:unix "libpulse.so.0"))
(defvar *audio-controller* nil)
(defvar *audio-state* nil)
(cffi:defcstruct pa-sample-spec (format :int) (rate :uint32) (channels :uint8))
(cffi:defcstruct pa-channel-map (channels :uint8) (map :int :count 32))
(cffi:defcstruct pa-cvolume (channels :uint8) (values :uint32 :count 32))
;; Only the stable, documented prefixes are inspected. No private server data.
(cffi:defcstruct pa-sink-info
  (name :pointer) (index :uint32) (description :pointer)
  (sample-spec (:struct pa-sample-spec)) (channel-map (:struct pa-channel-map))
  (owner-module :uint32) (volume (:struct pa-cvolume)) (mute :int))
(cffi:defcstruct pa-server-info
  (user-name :pointer) (host-name :pointer) (server-version :pointer) (server-name :pointer)
  (sample-spec (:struct pa-sample-spec)) (default-sink-name :pointer))
(cffi:defcfun ("pa_mainloop_new" %pa-mainloop-new) :pointer)
(cffi:defcfun ("pa_mainloop_free" %pa-mainloop-free) :void (mainloop :pointer))
(cffi:defcfun ("pa_mainloop_get_api" %pa-mainloop-api) :pointer (mainloop :pointer))
(cffi:defcfun ("pa_mainloop_iterate" %pa-mainloop-iterate) :int (mainloop :pointer) (block :int) (retval :pointer))
(cffi:defcfun ("pa_mainloop_wakeup" %pa-mainloop-wakeup) :void (mainloop :pointer))
(cffi:defcfun ("pa_context_new" %pa-context-new) :pointer (api :pointer) (name :string))
(cffi:defcfun ("pa_context_connect" %pa-context-connect) :int (context :pointer) (server :pointer) (flags :int) (spawn :pointer))
(cffi:defcfun ("pa_context_disconnect" %pa-context-disconnect) :void (context :pointer))
(cffi:defcfun ("pa_context_unref" %pa-context-unref) :void (context :pointer))
(cffi:defcfun ("pa_context_get_state" %pa-context-state) :int (context :pointer))
(cffi:defcfun ("pa_context_errno" %pa-context-errno) :int (context :pointer))
(cffi:defcfun ("pa_strerror" %pa-strerror) :string (error :int))
(cffi:defcfun ("pa_context_set_state_callback" %pa-state-callback) :void (context :pointer) (callback :pointer) (data :pointer))
(cffi:defcfun ("pa_context_set_subscribe_callback" %pa-subscribe-callback) :void (context :pointer) (callback :pointer) (data :pointer))
(cffi:defcfun ("pa_context_subscribe" %pa-subscribe) :pointer (context :pointer) (mask :int) (callback :pointer) (data :pointer))
(cffi:defcfun ("pa_context_get_server_info" %pa-server-info) :pointer (context :pointer) (callback :pointer) (data :pointer))
(cffi:defcfun ("pa_context_get_sink_info_by_name" %pa-sink-info) :pointer (context :pointer) (name :string) (callback :pointer) (data :pointer))
(cffi:defcfun ("pa_context_set_sink_volume_by_index" %pa-set-volume) :pointer (context :pointer) (index :uint32) (volume :pointer) (callback :pointer) (data :pointer))
(cffi:defcfun ("pa_context_set_sink_mute_by_index" %pa-set-mute) :pointer (context :pointer) (index :uint32) (mute :int) (callback :pointer) (data :pointer))
(cffi:defcfun ("pa_cvolume_scale" %pa-volume-scale) :pointer (volume :pointer) (maximum :uint32))
(cffi:defcfun ("pa_operation_unref" %pa-operation-unref) :void (operation :pointer))

(defun %audio-string (pointer) (unless (cffi:null-pointer-p pointer) (cffi:foreign-string-to-lisp pointer)))
(defun %audio-operation (operation)
  (when (cffi:null-pointer-p operation) (error "The audio server rejected the request."))
  (%pa-operation-unref operation))
(defmacro %audio-callback (&body body)
  `(handler-case (progn ,@body)
     (serious-condition (cause) (setf (getf *audio-state* :failure) cause))))

(cffi:defcallback %audio-sink :void ((context :pointer) (info :pointer) (eol :int) (data :pointer))
  (declare (ignore context data))
  (%audio-callback
    (when (minusp eol) (%system-publish *audio-controller* :available nil :error "The selected audio output is unavailable."))
    (when (and (zerop eol) (not (cffi:null-pointer-p info)))
      (let* ((name (%audio-string (cffi:foreign-slot-value info '(:struct pa-sink-info) 'name)))
             (volume (cffi:foreign-slot-pointer info '(:struct pa-sink-info) 'volume))
             (channels (cffi:foreign-slot-value volume '(:struct pa-cvolume) 'channels)))
        (when (equal name (getf *audio-state* :sink-name))
          (unless (<= 1 channels 32) (error "Unsupported audio channel count."))
          (let* ((values (loop for i below channels collect
                          (cffi:mem-aref (cffi:foreign-slot-pointer volume '(:struct pa-cvolume) 'values) :uint32 i)))
                 (percent (round (* 100 (/ (reduce #'max values) 65536))))
                 (muted (not (zerop (cffi:foreign-slot-value info '(:struct pa-sink-info) 'mute)))))
            (setf (getf *audio-state* :sink-index) (cffi:foreign-slot-value info '(:struct pa-sink-info) 'index)
                  (getf *audio-state* :volumes) values)
            (apply #'%system-publish *audio-controller*
                   (append (list :available t :volume percent :muted muted :error nil
                                 :device (%audio-string (cffi:foreign-slot-value info '(:struct pa-sink-info) 'description)))
                           (let ((view (%system-view *audio-controller*)))
                             (append (when (eql percent (first (getf view :volume-target)))
                                       (list :volume-target nil))
                                     (when (and (getf view :mute-target)
                                                (eql muted (first (getf view :mute-target))))
                                       (list :mute-target nil))))))))))))
(defun %audio-request-sink (context)
  (let ((name (getf *audio-state* :sink-name)))
    (if name (%audio-operation (%pa-sink-info context name (cffi:callback %audio-sink) (cffi:null-pointer)))
        (%system-publish *audio-controller* :available nil :error "No default audio output."))))
(cffi:defcallback %audio-server :void ((context :pointer) (info :pointer) (data :pointer))
  (declare (ignore data))
  (%audio-callback
    (unless (cffi:null-pointer-p info)
      (setf (getf *audio-state* :sink-name)
            (%audio-string (cffi:foreign-slot-value info '(:struct pa-server-info) 'default-sink-name)))
      (%audio-request-sink context))))
(defun %audio-request-server (context)
  (%audio-operation (%pa-server-info context (cffi:callback %audio-server) (cffi:null-pointer))))
(cffi:defcallback %audio-event :void ((context :pointer) (event :int) (index :uint32) (data :pointer))
  (declare (ignore data))
  (%audio-callback
    (cond ((= 7 (logand event 15)) (%audio-request-server context))
          ((and (zerop (logand event 15)) (eql index (getf *audio-state* :sink-index)))
           (if (= #x20 (logand event #x30)) (%audio-request-server context) (%audio-request-sink context))))))
(cffi:defcallback %audio-ready :void ((context :pointer) (data :pointer))
  (declare (ignore data))
  (%audio-callback
    (when (= 4 (%pa-context-state context))
      (%pa-subscribe-callback context (cffi:callback %audio-event) (cffi:null-pointer))
      (%audio-operation (%pa-subscribe context #x81 (cffi:null-pointer) (cffi:null-pointer)))
      (%audio-request-server context))))
(cffi:defcallback %audio-success :void ((context :pointer) (success :int) (data :pointer))
  (declare (ignore data))
  (%audio-callback
    (if (zerop success)
        (%system-publish *audio-controller* :volume-target nil :mute-target nil :error (%pa-strerror (%pa-context-errno context)))
        (%audio-request-server context))))
(defun %audio-command (context command)
  (destructuring-bind (kind . value) command
    (if (eq kind :refresh) (%audio-request-server context)
        (let ((index (getf *audio-state* :sink-index)) (volumes (getf *audio-state* :volumes)))
          (unless (and index volumes) (error "No audio output is ready."))
          (ecase kind
            (:volume
             (cffi:with-foreign-object (volume '(:struct pa-cvolume))
               (setf (cffi:foreign-slot-value volume '(:struct pa-cvolume) 'channels) (length volumes))
               (loop for level in volumes for i from 0 do
                 (setf (cffi:mem-aref (cffi:foreign-slot-pointer volume '(:struct pa-cvolume) 'values) :uint32 i) level))
               (%pa-volume-scale volume (round (* 65536 (/ (max 0 (min 100 value)) 100))))
               (%audio-operation (%pa-set-volume context index volume (cffi:callback %audio-success) (cffi:null-pointer)))))
            (:mute (%audio-operation (%pa-set-mute context index (if value 1 0) (cffi:callback %audio-success) (cffi:null-pointer)))))))))
(defun %run-audio (controller)
  (cffi:use-foreign-library shell-pulse)
  (let* ((*audio-controller* controller) (*audio-state* nil)
         (mainloop (%pa-mainloop-new)) (context (cffi:null-pointer)))
    (when (cffi:null-pointer-p mainloop) (error "Could not create the audio connection."))
    (unwind-protect
         (progn
           (setf context (%pa-context-new (%pa-mainloop-api mainloop) "Ataxia volume controls"))
           (when (cffi:null-pointer-p context) (error "Could not create the audio context."))
           (%pa-state-callback context (cffi:callback %audio-ready) (cffi:null-pointer))
           (when (minusp (%pa-context-connect context (cffi:null-pointer) 1 (cffi:null-pointer)))
             (error "~A" (%pa-strerror (%pa-context-errno context))))
           (sb-thread:with-mutex ((system-controller-lock controller))
             (setf (system-controller-native-wake controller) (lambda () (%pa-mainloop-wakeup mainloop))))
           (loop until (%system-stopped-p controller) do
             (when (getf *audio-state* :failure) (error (getf *audio-state* :failure)))
             (when (member (%pa-context-state context) '(5 6)) (error "~A" (%pa-strerror (%pa-context-errno context))))
             (when (= 4 (%pa-context-state context))
               (dolist (command (%system-commands controller)) (%audio-command context command)))
             (unless (%system-stopped-p controller)
               (when (minusp (%pa-mainloop-iterate mainloop 1 (cffi:null-pointer))) (error "Audio connection closed.")))))
      (sb-thread:with-mutex ((system-controller-lock controller)) (setf (system-controller-native-wake controller) nil))
      (unless (cffi:null-pointer-p context) (%pa-context-disconnect context) (%pa-context-unref context))
      (%pa-mainloop-free mainloop))))
