(in-package #:ataxia.world.shell)

(defclass shell-popup (shell-widget)
  ((kind :initform :apps :accessor %shell-popup-kind)
   (bar :initform nil :accessor %shell-popup-bar)
   (entries :initform nil :accessor %shell-popup-entries)
   (matches :initform nil :accessor %shell-popup-matches)
   (page :initform 0 :accessor %shell-popup-page)
   (selected :initform 0 :accessor %shell-popup-selected)
   (search-focused-p :initform t :accessor %shell-search-focused-p)))

(defun %shell-class (popup name value)
  (cache-shell-value popup (list :class name) value
               (lambda (component) (set-shell-class component "panel" name value))))
(defun %bar-close-popup (world bar)
  (let ((popup (%bar-popup bar)))
    (when popup
      (setf (%bar-popup bar) nil)
      ;; Hide restores the displaced application's keyboard focus before retirement.
      (hide-overlay world popup)
      (remove-agent-widget world popup)
      (%bar-schedule-maintenance world)))
  bar)
(defun %bar-position-popup (world bar output)
  (let ((popup (%bar-popup bar)))
    (when popup
      (multiple-value-bind (ow oh) (output-logical-size output)
        (let* ((kind (%shell-popup-kind popup))
               (size (ecase kind (:apps '(400d0 180d0)) (:power '(340d0 132d0))
                               (:spaces '(560d0 260d0)) (:media '(380d0 84d0)) (:clipboard '(560d0 180d0))))
               (width (max 1d0 (min (first size) (- ow 16d0))))
               (preferred (gethash :preferred-height (shell-cache popup) (second size)))
               (height (max 1d0 (min (+ preferred (if (and (eq kind :clipboard) (< width 480d0)
                                                                          (%shell-popup-matches popup)) 48d0 0d0))
                                     (- oh 18d0))))
               (anchor (if (member kind '(:apps :spaces)) (overlay-x bar)
                           (- (+ (overlay-x bar) (overlay-width bar)) width))))
          (position-widget world popup (max 0d0 (min (- ow width) anchor))
                               (max 0d0 (- (overlay-y bar) height)) width height)
          (%shell-class popup "small" (< width 480d0)))))))
(defun %bar-update-power-popup (popup power)
  (let ((capacity (getf power :capacity)) (health (getf power :health))
        (cycles (getf power :cycles)) (tone (%bar-power-tone power)))
    (set-shell-text popup "percent" (if capacity (format nil "~D%" capacity) (if (eq :ac (getf power :status)) "AC" "—")))
    (set-shell-text popup "state" (case (getf power :status)
                                     (:full "Fully charged") (:paused "Not charging")
                                     (t (%bar-power-status power))))
    (set-shell-text popup "estimate" (if (getf power :minutes) (%bar-power-estimate power) ""))
    (set-shell-style popup "estimate" "display" (if (getf power :minutes) "block" "none"))
    (set-shell-text popup "health" (if health (format nil "~D% of design" health) "Unavailable"))
    (set-shell-text popup "cycles" (if cycles (princ-to-string cycles) "Unavailable"))
    (set-shell-text popup "source" (if (or (getf power :online) (eq :ac (getf power :status))) "AC adapter" "Battery"))
    (set-shell-text popup "note" (case tone (:critical "Battery is very low. Connect your charger soon.")
                                 (:low "Battery is running low.")
                                 (t "")))
    (set-shell-style popup "note" "display" (if (member tone '(:low :critical)) "block" "none"))
    (%shell-class popup "low" (eq tone :low))
    (%shell-class popup "critical" (eq tone :critical))
    (%power-popup-height popup)))

(defun %shell-app-priority (entry)
  (or (position (getf entry :id)
                '("firefox" "org.mozilla.firefox" "chromium" "org.gnome.Epiphany"
                  "wezterm" "foot" "emacs" "org.gnome.Nautilus"
                  "org.gnome.Calculator" "org.gnome.TextEditor") :test #'string-equal) 100))
(defun %shell-apps (world output)
  (stable-sort (copy-list (world-application-catalog world output)) #'< :key #'%shell-app-priority))
(defun %shell-select (popup index)
  (let ((count (min 6 (max 0 (- (length (%shell-popup-matches popup)) (* 6 (%shell-popup-page popup)))))))
    (setf (%shell-popup-selected popup) (max 0 (min (1- count) index)))
    (loop for i below 6 do
      (cache-shell-value popup (list :selected i) (= i (%shell-popup-selected popup))
                   (lambda (component) (set-shell-class component (format nil "app~D" i) "selected" (= i (%shell-popup-selected popup))))))
    (when (eq :clipboard (%shell-popup-kind popup))
      (let ((entry (nth (+ (* 6 (%shell-popup-page popup)) (%shell-popup-selected popup))
                        (%shell-popup-matches popup))))
        ;; Bound layout work while retaining line breaks; copying uses the full entry.
        (set-shell-text popup "preview" (if entry (short-ui-text entry 2048) ""))))))
(defun %shell-results (popup)
  (let* ((matches (%shell-popup-matches popup)) (count (length matches))
         (pages (max 1 (ceiling count 6)))
         (page (max 0 (min (1- pages) (%shell-popup-page popup)))))
    (setf (%shell-popup-page popup) page)
    (set-shell-text popup "count" (format nil "~D application~:P" count))
    (set-shell-text popup "page" (format nil "~D / ~D" (1+ page) pages))
    (set-shell-style popup "empty" "display" (if (zerop count) "block" "none"))
    (loop for i below 6 for entry = (nth (+ (* page 6) i) matches) do
      (set-shell-style popup (format nil "app~D" i) "display" (if entry "flex" "none"))
      (when entry
        (set-shell-text popup (format nil "name~D" i) (getf entry :name))))
    (%shell-select popup 0)))
(defun %shell-search (popup query)
  (let ((query (string-trim '(#\Space #\Tab) query)))
    (setf (%shell-popup-matches popup)
          (remove-if-not (lambda (entry)
                           (or (search query (getf entry :name) :test #'char-equal)
                               (search query (getf entry :detail) :test #'char-equal)
                               (search query (getf entry :id) :test #'char-equal)))
                         (%shell-popup-entries popup))
          (%shell-popup-page popup) 0)
    (%shell-results popup)))
(defun %shell-launch (world popup index)
  (when (<= 0 index 5)
    (let ((entry (nth (+ (* 6 (%shell-popup-page popup)) index) (%shell-popup-matches popup))))
      (when entry
        (%bar-close-popup world (%shell-popup-bar popup))
        (launch-world-application world (overlay-output popup) (getf entry :id))))))
(defun %bar-toggle-popup (world bar kind)
  (let ((existing (%bar-popup bar)))
    (%bar-close-popup world bar)
    (when (and existing (eq kind (%shell-popup-kind existing))) (return-from %bar-toggle-popup nil)))
  (let* ((output (overlay-output bar))
         (seat (world-seat-on-output world output))
         (popup (make-shell-widget (world-service world :shell) world kind
                                   :output output :width 400d0 :height 180d0 :layer 1300)))
    (setf (%shell-popup-kind popup) kind (%shell-popup-bar popup) bar (%bar-popup bar) popup)
    (handler-case
        (progn
          (%bar-position-popup world bar output)
          (bind-agent-widget-event popup "close" (lambda (widget event) (declare (ignore widget event)) (%bar-close-popup world bar)))
          (cond ((eq kind :power)
                (%bar-update-power-popup popup (%bar-power))
                (%bar-schedule-maintenance world)
                (%bind-power-controls world popup))
                ((member kind '(:spaces :media :clipboard)) (%initialize-extra-popup world popup))
                (t
                (setf (%shell-popup-entries popup) (%shell-apps world (overlay-output bar)))
                (set-shell-model (overlay-component popup) "query" "")
                (bind-agent-widget-event popup "model:query"
                                         (lambda (widget event) (%shell-search widget (agent-widget-event-value event))))
                (bind-agent-widget-event popup "search:focus"
                                         (lambda (widget event) (declare (ignore event)) (setf (%shell-search-focused-p widget) t)))
                (bind-agent-widget-event popup "search:blur"
                                         (lambda (widget event) (declare (ignore event)) (setf (%shell-search-focused-p widget) nil)))
                (%shell-search popup "")
                (loop for i below 6 do
                  (let ((index i)) (bind-agent-widget-event popup (format nil "app~D" i)
                                    (lambda (widget event) (declare (ignore event)) (%shell-launch world widget index)))))
                (dolist (entry '(("prev" . -1) ("next" . 1)))
                  (let ((direction (cdr entry)))
                    (bind-agent-widget-event popup (car entry)
                                             (lambda (widget event) (declare (ignore event))
                                               (incf (%shell-popup-page widget) direction) (%shell-results widget)))))
                (bind-agent-widget-event popup "power" (lambda (widget event) (declare (ignore widget event)) (%bar-toggle-popup world bar :power)))
                (bind-agent-widget-event popup "overview" (lambda (widget event) (declare (ignore widget event))
                                                            (%bar-close-popup world bar) (%bar-action world bar :overview)))))
          (when seat (focus-world-target world seat popup :remember t))
          popup)
      (error (cause) (%bar-close-popup world bar) (error cause)))))

(defun %shell-popup-on-seat (world seat)
  (let ((output (world-seat-output world seat)))
    (find-if (lambda (widget)
               (and (typep widget 'shell-popup) (eq output (overlay-output widget))))
             (world-overlays world))))
(defun %shell-pointer-inside-p (world seat widget)
  (multiple-value-bind (x y) (world-pointer-position world seat)
    (and x y (<= (overlay-x widget) x (+ (overlay-x widget) (overlay-width widget)))
         (<= (overlay-y widget) y (+ (overlay-y widget) (overlay-height widget))))))
(defmethod service-pointer-button ((service shell-service) world seat input)
  (when (eq :pressed (ataxia.kernel:cursor-button-input-state input))
    (let ((popup (%shell-popup-on-seat world seat)))
      (when (and popup (not (%shell-pointer-inside-p world seat popup))
                 (not (%shell-pointer-inside-p world seat (%shell-popup-bar popup))))
        (%bar-close-popup world (%shell-popup-bar popup))))))
(defmethod service-key-event ((service shell-service) world seat input)
  (when (or (%power-key-event world service seat input)
            (%controls-key-event world service seat input))
    (return-from service-key-event t))
  (let* ((popup (%shell-popup-on-seat world seat))
         (key (when (and popup (typep input 'ataxia.kernel:key-input)
                         (eq :pressed (ataxia.kernel:key-input-state input)))
                (find-if (lambda (symbol)
                           (member symbol '("Escape" "Return" "Up" "Down" "Prior" "Next") :test #'equal))
                         (ataxia.kernel:key-input-keysyms input)))))
    (when (and popup key (eq popup (world-seat-focus world seat))
               (or (equal key "Escape")
                   (and (eq :apps (%shell-popup-kind popup)) (%shell-search-focused-p popup)))
               (not (intersection '(:logo :control :alt) (ataxia.kernel:key-input-modifiers input))))
      (cond
        ((equal key "Escape") (%bar-close-popup world (%shell-popup-bar popup)))
        ((equal key "Return") (%shell-launch world popup (%shell-popup-selected popup)))
        ((equal key "Up") (%shell-select popup (1- (%shell-popup-selected popup))))
        ((equal key "Down") (%shell-select popup (1+ (%shell-popup-selected popup))))
        ((equal key "Prior") (decf (%shell-popup-page popup)) (%shell-results popup))
        ((equal key "Next") (incf (%shell-popup-page popup)) (%shell-results popup)))
      t)))
