(in-package #:ataxia.world.shell)

(defun %bar-read-line (path)
  (ignore-errors (with-open-file (stream path) (read-line stream nil nil))))
(defun %bar-power-number (path name)
  (ignore-errors (parse-integer (%bar-read-line (merge-pathnames name path)))))
(defun %bar-power (&optional (root #P"/sys/class/power_supply/"))
  "A snapshot of the first present system battery; never invent missing estimates."
  (let* ((supplies (ignore-errors (uiop:subdirectories root)))
         (battery (find-if (lambda (path)
                             (and (equal "Battery" (%bar-read-line (merge-pathnames "type" path)))
                                  (not (eql 0 (%bar-power-number path "present"))))) supplies))
         (online (some (lambda (path) (eql 1 (%bar-power-number path "online"))) supplies)))
    (if (null battery) (list :status :ac :online online)
        (let* ((capacity (%bar-power-number battery "capacity"))
               (status (%bar-read-line (merge-pathnames "status" battery)))
               (state (cond ((equal status "Charging") :charging)
                            ((equal status "Discharging") :discharging)
                            ((or (equal status "Full") (and capacity (>= capacity 99))) :full)
                            ((equal status "Not charging") :paused)
                            (t :unknown)))
               ;; Keep units matched: energy / power or charge / current gives hours.
               (energy (%bar-power-number battery "energy_now"))
               (amount (or energy (%bar-power-number battery "charge_now")))
               (full (%bar-power-number battery (if energy "energy_full" "charge_full")))
               (design (%bar-power-number battery (if energy "energy_full_design" "charge_full_design")))
               (rate (%bar-power-number battery (if energy "power_now" "current_now")))
               (hours (when (and amount rate (plusp rate))
                        (case state
                          (:discharging (/ amount rate))
                          (:charging (when full (/ (max 0 (- full amount)) rate)))))))
          (list :status state :capacity (and capacity (max 0 (min 100 capacity)))
                :online (or online (eq state :charging))
                :minutes (when (and hours (plusp hours) (< hours 168)) (max 1 (round (* 60 hours))))
                :health (when (and full design (plusp design)) (min 100 (round (* 100 (/ full design)))))
                :cycles (%bar-power-number battery "cycle_count")
                :name (or (%bar-read-line (merge-pathnames "model_name" battery)) "Battery"))))))
(defun %bar-power-status (power)
  (case (getf power :status)
    (:charging "Charging") (:discharging "On battery")
    (:full (if (getf power :online) "Fully charged · plugged in" "Fully charged"))
    (:paused (if (getf power :online) "Plugged in · not charging" "Not charging"))
    (:ac "AC power") (t "Status unavailable")))
(defun %bar-power-estimate (power)
  (let ((minutes (getf power :minutes)))
    (if minutes
        (format nil "About ~@[~Dh ~]~Dm ~A" (when (>= minutes 60) (floor minutes 60)) (mod minutes 60)
                (if (eq :charging (getf power :status)) "until full" "remaining"))
        (case (getf power :status)
          (:full "Ready when you are") (:paused "Charging is currently paused")
          (:ac "Connected to external power") (t "Time estimate unavailable")))))
(defun %bar-power-tone (power)
  (let ((capacity (getf power :capacity)))
    (cond ((or (getf power :online) (eq :charging (getf power :status))) :normal)
          ((and capacity (<= capacity 10)) :critical)
          ((and capacity (<= capacity 25)) :low) (t :normal))))
(defun %bar-clock (bar now power)
  (multiple-value-bind (second minute hour date month year day) (decode-universal-time now)
    (declare (ignore second year))
    (set-shell-text bar "clock" (format nil "~2,'0D:~2,'0D" hour minute))
    (set-shell-text bar "date" (format nil "~A, ~A ~D" (nth day '("MON" "TUE" "WED" "THU" "FRI" "SAT" "SUN"))
                                 (nth (1- month) '("JAN" "FEB" "MAR" "APR" "MAY" "JUN" "JUL" "AUG" "SEP" "OCT" "NOV" "DEC")) date)))
  (let ((capacity (getf power :capacity)) (tone (%bar-power-tone power)))
    (set-shell-text bar "power-text" (if capacity (format nil "~D%" capacity) (if (eq :ac (getf power :status)) "AC" "—")))
    (set-shell-text bar "power-note" (case (getf power :status) (:charging "Charging") (:full "Full") (:paused "Paused") (:ac "Plugged in") (t "Battery")))
    (set-shell-text bar "power-symbol" (cond ((eq :charging (getf power :status)) "ϟ")
                                      ((or (getf power :online) (eq :ac (getf power :status))) "↯")
                                      ((member tone '(:low :critical)) "!") (t "")))
    (set-shell-style bar "battery" "display" (if capacity "block" "none"))
    (set-shell-style bar "charge" "width" (format nil "~D%" (or capacity 0)))
    (set-bar-class bar "low" (eq tone :low))
    (set-bar-class bar "critical" (eq tone :critical))
    (set-bar-class bar "charging" (eq (getf power :status) :charging))
    (set-bar-class bar "plugged" (not (null (getf power :online))))
    (setf (gethash :power (shell-cache bar)) power)
    (when (and (%bar-popup bar) (eq :power (%shell-popup-kind (%bar-popup bar))))
      (%bar-update-power-popup (%bar-popup bar) power))))
