(in-package #:ataxia.world.shell)
(defclass shell-widget (agent-widget)
  ((cache :initform (make-hash-table :test #'equal) :reader shell-cache)))
(defgeneric make-shell-widget (service world kind &rest options))
(defgeneric set-shell-class (component id name enabled))
(defgeneric set-shell-model (component name value))
(defgeneric shell-model-value (component name))
(defgeneric set-shell-element-style (component id property value))
(defun cache-shell-value (widget key value function)
  (unless (equal (gethash key (shell-cache widget) :absent) value)
    (funcall function (overlay-component widget))
    (setf (gethash key (shell-cache widget)) value)))
(defun set-shell-text (widget id value)
  (cache-shell-value widget id value (lambda (component) (ui-set-property component id value))))
(defun set-shell-style (widget id property value)
  (cache-shell-value widget (list id property) value
    (lambda (component) (set-shell-element-style component id property value))))
(defun short-ui-text (text limit)
  (if (> (length text) limit) (concatenate 'string (subseq text 0 (1- limit)) "…") text))
