;;;; Named groups and stable workspace destinations; numbers always mean workspaces.
(in-package #:ataxia.world.shell)
(defvar *workspace-popup-state* (make-hash-table :test #'eq :weakness :key))

(defun %workspace-popup-state (popup)
  (or (gethash popup *workspace-popup-state*)
      (setf (gethash popup *workspace-popup-state*) (list :group nil :page 0))))

(defun %visible-workspace-numbers (group)
  (mapcar (lambda (entry) (getf entry :number)) (getf group :workspaces)))

(defun %next-empty-workspace (group)
  (when group
    (let ((visible (%visible-workspace-numbers group)))
      (loop for number from 1 to 9 unless (member number visible) return number))))

(defun %sync-workspace-popup (world popup)
  (let* ((navigation (world-shell-state world (overlay-output popup)))
         (groups (getf navigation :groups)) (state (%workspace-popup-state popup))
         (selected (or (find (getf state :group) groups :key (lambda (x) (getf x :id)) :test #'eql)
                       (find-if (lambda (x) (getf x :selected)) groups) (first groups)))
         (visible (%visible-workspace-numbers selected))
         (pages (max 1 (ceiling (length groups) 6)))
         (page (max 0 (min (1- pages) (getf state :page)))))
    (setf (getf state :group) (getf selected :id) (getf state :page) page)
    (set-shell-text popup "location" (if (getf navigation :active)
                                        (format nil "You are in ~A / Workspace ~D" (getf navigation :name) (getf navigation :selected))
                                        "You are in the overview"))
    (set-shell-text popup "group-title" (or (getf selected :name) "No workspace groups"))
    (set-shell-style popup "group-remove" "display" (if (getf selected :removable) "block" "none"))
    (set-shell-text popup "group-page" (format nil "~D / ~D" (1+ page) pages))
    (set-shell-style popup "group-paging" "display" (if (> pages 1) "flex" "none"))
    (dotimes (i 6)
      (let ((entry (nth (+ (* page 6) i) groups)) (id (format nil "group~D" i)))
        (set-shell-style popup id "display" (if entry "block" "none"))
        (when entry
          (set-shell-text popup id (short-ui-text (getf entry :name) 23))
          (cache-shell-value popup (list :group i) (eql (getf entry :id) (getf selected :id))
            (lambda (component) (set-shell-class component id "selected"
                                 (eql (getf entry :id) (getf selected :id))))))))
    (loop for number from 1 to 9
          for entry = (find number (getf selected :workspaces) :key (lambda (x) (getf x :number)))
          for count = (getf entry :count 0)
          for current = (and (eql (getf selected :id) (getf navigation :group)) (= number (getf navigation :selected 0))) do
      (set-shell-style popup (format nil "workspace-card~D" number) "display"
                        (if (member number visible) "block" "none"))
      (set-shell-style popup (format nil "workspace-remove~D" number) "display"
                        (if (and (member number visible) (getf entry :removable)) "block" "none"))
      (set-shell-text popup (format nil "workspace-name~D" number) (format nil "Workspace ~D" number))
      (set-shell-text popup (format nil "workspace-detail~D" number)
                       (if current "Current workspace" (if (zerop count) "Empty" (format nil "~D item~:P" count))))
      (set-shell-text popup (format nil "workspace-preview~D" number)
                       (short-ui-text (or (first (getf entry :titles)) "") 24))
      (cache-shell-value popup (list :workspace number) (list (not (null selected)) current)
        (lambda (component)
          (set-shell-class component (format nil "workspace~D" number) "selected" current))))
    (set-shell-style popup "workspace-grid" "display" (if selected "flex" "none"))
    (set-shell-style popup "workspace-new" "display" (if (%next-empty-workspace selected) "block" "none"))))

(defun %choose-workspace (world popup number)
  (let* ((state (%workspace-popup-state popup)) (output (overlay-output popup))
         (seat (world-seat-on-output world output)) (group (getf state :group)))
    (when (and seat group)
      (%bar-close-popup world (%shell-popup-bar popup))
      (world-shell-action world output seat :select-workspace (list group number)))))

(defun %new-workspace (world popup)
  (let* ((groups (getf (world-shell-state world (overlay-output popup)) :groups))
         (group (find (getf (%workspace-popup-state popup) :group) groups
                      :key (lambda (entry) (getf entry :id)) :test #'eql))
         (number (%next-empty-workspace group)))
    (when number (%choose-workspace world popup number))))

(defun %remove-workspace-destination (world popup &optional number)
  (let* ((output (overlay-output popup)) (seat (world-seat-on-output world output))
         (id (getf (%workspace-popup-state popup) :group))
         (group (find id (getf (world-shell-state world output) :groups)
                      :key (lambda (entry) (getf entry :id)) :test #'eql))
         (entry (and number (find number (getf group :workspaces)
                                 :key (lambda (entry) (getf entry :number))))))
    (when (and seat (if number (getf entry :removable) (getf group :removable)))
      (%bar-close-popup world (%shell-popup-bar popup))
      (world-shell-action world output seat (if number :remove-workspace :remove-subworld)
                          (if number (list id number) id)))))

(defun %initialize-workspace-popup (world popup)
  (dotimes (i 6)
    (let ((index i))
      (bind-agent-widget-event popup (format nil "group~D" index)
        (lambda (widget event)
          (declare (ignore event))
          (let* ((state (%workspace-popup-state widget))
                 (groups (getf (world-shell-state world (overlay-output widget)) :groups))
                 (entry (nth (+ (* 6 (getf state :page)) index) groups)))
            (when entry (setf (getf state :group) (getf entry :id)) (%sync-workspace-popup world widget)))))))
  (loop for number from 1 to 9 do
    (let ((number number))
      (bind-agent-widget-event popup (format nil "workspace~D" number)
        (lambda (widget event) (declare (ignore event)) (%choose-workspace world widget number)))
      (bind-agent-widget-event popup (format nil "workspace-remove~D" number)
        (lambda (widget event) (declare (ignore event)) (%remove-workspace-destination world widget number)))))
  (bind-agent-widget-event popup "workspace-new"
    (lambda (widget event) (declare (ignore event)) (%new-workspace world widget)))
  (bind-agent-widget-event popup "group-remove"
    (lambda (widget event) (declare (ignore event)) (%remove-workspace-destination world widget)))
  (dolist (entry '(("group-prev" . -1) ("group-next" . 1)))
    (let ((delta (cdr entry)))
      (bind-agent-widget-event popup (car entry)
        (lambda (widget event) (declare (ignore event))
          (let ((state (%workspace-popup-state widget))) (incf (getf state :page) delta))
          (%sync-workspace-popup world widget)))))
  (bind-agent-widget-event popup "overview"
    (lambda (widget event) (declare (ignore event)) (%bar-action world (%shell-popup-bar widget) :overview)))
  (%sync-workspace-popup world popup))
