;;;; Compositor package boundary.
;;;;
;;;; ATAXIA.COMPOSITOR exports policy-facing objects and operations. Raw GLES
;;;; entrypoints remain private implementation details of the graphics module.

(defpackage #:ataxia.compositor
  (:use #:cl)
  (:export
   #:compositor-error
   #:invalid-compositor-state
   #:hook-vetoed
   #:control-request-rejected
   #:graphics-failure
   #:compositor-component
   #:component-compositor
   #:component-state
   #:attach-component
   #:detach-component
   #:validate-component
   #:compositor
   #:compositor-runtime
   #:compositor-outputs
   #:compositor-surfaces
   #:compositor-desktop
   #:compositor-interaction
   #:compositor-behavior-policy
   #:compositor-presentation
   #:compositor-graphics
   #:compositor-extensions
   #:compositor-control
   #:compositor-state
   #:make-compositor-component
   #:construct-compositor-components
   #:operation-descriptor
   #:operation-subject
   #:operation-animation-override
   #:visibility-transition
   #:visibility-old-state
   #:visibility-new-state
   #:placement-transition
   #:placement-old-value
   #:placement-new-value
   #:interaction-transition
   #:interaction-old-state
   #:interaction-new-state
   #:content-transition
   #:component-replacement
   #:replacement-role
   #:replacement-old-component
   #:replacement-new-component
   #:view-configuration-decision
   #:configuration-width
   #:configuration-height
   #:pointer-button-decision
   #:pointer-decision-focus-target
   #:pointer-decision-operation-kind
   #:pointer-decision-resize-edges
   #:pointer-decision-deliver-p
   #:pointer-axis-input
   #:pointer-axis-input-time
   #:pointer-axis-input-orientation
   #:pointer-axis-input-delta
   #:pointer-axis-input-discrete-delta
   #:pointer-axis-input-source
   #:pointer-axis-input-relative-direction
   #:pointer-axis-decision
   #:pointer-axis-decision-deliver-p
   #:keyboard-key-input
   #:keyboard-input-time
   #:keyboard-input-keycode
   #:keyboard-input-state
   #:keyboard-input-depressed-modifiers
   #:keyboard-input-latched-modifiers
   #:keyboard-input-locked-modifiers
   #:keyboard-input-layout-group
   #:keyboard-key-decision
   #:keyboard-decision-deliver-p
   #:apply-view-configuration-decision
   #:operation-context
   #:context-subject
   #:context-operation
   #:context-old-state
   #:context-new-state
   #:context-cause
   #:context-provenance
   #:context-timestamp
   #:context-phase
   #:context-metadata
   #:provenance
   #:provenance-kind
   #:provenance-identity
   #:make-local-provenance
   #:extension-system
   #:extension-hooks
   #:hook-registry
   #:hook-context
   #:register-hook
   #:unregister-hook
   #:run-hook
   #:surface-system
   #:surface-record
   #:surface-record-native
   #:surface-record-buffer
   #:surface-record-texture
   #:surface-record-width
   #:surface-record-height
   #:surface-record-mapped-p
   #:application
   #:application-id
   #:application-app-id
   #:application-views
   #:view
   #:view-id
   #:view-native
   #:view-surface
   #:view-application
   #:view-behavior-state
   #:view-placement
   #:view-width
   #:view-height
   #:view-title
   #:view-decoration-mode
   #:view-server-decorated-p
   #:view-initialized-p
   #:view-mapped-p
   #:view-presentable-p
   #:view-maximized-p
   #:view-fullscreen-p
   #:view-minimized-p
   #:view-animation-policy
   #:view-shader-program-name
   #:view-presentation-state
   #:behavior-view-state
   #:behavior-state-placement
   #:behavior-state-restore-state
   #:behavior-state-animation-policy
   #:behavior-state-shader-program-name
   #:behavior-state-presentation-state
   #:popup-view
   #:popup-native
   #:popup-surface
   #:popup-parent
   #:popup-parent-view
   #:popup-x
   #:popup-y
   #:popup-mapped-p
   #:desktop-system
   #:desktop-views
   #:desktop-applications
   #:desktop-stacking-order
   #:desktop-find-view
   #:desktop-raise-view
   #:behavior-policy
   #:behavior-policy-active-p
   #:behavior-policy-revision
   #:planar-behavior-policy
   #:planar-behavior-state
   #:spherical-behavior-policy
   #:spherical-behavior-state
   #:spherical-placement
   #:spherical-longitude
   #:spherical-latitude
   #:spherical-angular-width
   #:spherical-angular-height
   #:spherical-depth
   #:spherical-camera
   #:camera-longitude
   #:camera-latitude
   #:camera-field-of-view
   #:spherical-mesh-columns
   #:spherical-mesh-rows
   #:behavior-portable-state
   #:portable-state-source-policy
   #:portable-state-view-states
   #:portable-state-output-states
   #:behavior-installation
   #:installation-view-states
   #:installation-output-states
   #:activate-behavior-policy
   #:quiesce-behavior-policy
   #:behavior-view-created
   #:behavior-view-committed
   #:behavior-view-mapped
   #:behavior-view-unmapped
   #:behavior-view-destroying
   #:behavior-view-identity-changed
   #:behavior-output-added
   #:behavior-output-removing
   #:behavior-recommend-initial-size
   #:behavior-set-view-size
   #:behavior-place-view
   #:behavior-update-placement
   #:behavior-project-view
   #:behavior-unproject-point
   #:copy-behavior-placement
   #:copy-behavior-view-state
   #:copy-behavior-output-state
   #:migrate-behavior-view-state
   #:migrate-behavior-output-state
   #:behavior-export-state
   #:behavior-import-state
   #:behavior-build-scene
   #:behavior-build-view-items
   #:behavior-build-popup-items
   #:behavior-begin-operation
   #:behavior-update-operation
   #:behavior-configure-view-for-output
   #:behavior-restore-view
   #:behavior-pan-output
   #:behavior-zoom-output
   #:behavior-move-view
   #:behavior-focus-changed
   #:behavior-handle-pointer-button
   #:behavior-handle-pointer-axis
   #:behavior-handle-keyboard-key
   #:behavior-observe-output
   #:behavior-observe-view
   #:behavior-resolve-animation
   #:behavior-set-view-animation-definition
   #:behavior-placement
   #:planar-placement
   #:placement-x
   #:placement-y
   #:placement-width
   #:placement-height
   #:placement-z
   #:placement-request
   #:requested-placement-x
   #:requested-placement-y
   #:requested-placement-width
   #:requested-placement-height
   #:viewport
   #:viewport-camera-x
   #:viewport-camera-y
   #:viewport-scale
   #:pan-viewport
   #:zoom-viewport
   #:replace-behavior-policy
   #:presentation-state
   #:presentation-opacity
   #:presentation-scale
   #:presentation-offset-x
   #:presentation-offset-y
   #:presentation-effect-parameters
   #:presentation-shader-uniforms
   #:animation-policy
   #:animation-policy-fallback
   #:animation-track
   #:animation-track-property
   #:animation-track-from
   #:animation-track-to
   #:animation-track-interpolator
   #:animation-property-key
   #:shader-uniform-binding
   #:shader-uniform-binding-name
   #:animation-definition
   #:animation-definition-duration
   #:animation-definition-tracks
   #:animation-definition-name
   #:animation-instance
   #:animation-instance-subject
   #:animation-instance-descriptor
   #:animation-instance-definition
   #:animation-instance-context
   #:animation-instance-started-at
   #:animation-instance-state
   #:animation-engine
   #:animation-engine-active
   #:set-animation-policy-definition
   #:resolve-animation
   #:start-transition
   #:sample-animations
   #:active-animations-p
   #:direct-gles-renderer
   #:renderer-begin-frame
   #:renderer-draw-item
   #:renderer-draw-material
   #:renderer-end-frame
   #:renderer-abort-frame
   #:shader-program-descriptor
   #:program-vertex-source
   #:program-fragment-source
   #:program-descriptor-kind
   #:program-uniform-names
   #:shader-program
   #:shader-native-program
   #:shader-uniforms
   #:shader-program-state
   #:compile-shader-program
   #:make-material-program-descriptor
   #:replace-shader-program
   #:shader-program-installed-p
   #:set-view-shader-program
   #:set-view-shader-uniform
   #:presentation-system
   #:presentation-animation-engine
   #:presentation-panel-height
   #:presentation-titlebar-height
   #:presentation-snapshot
   #:snapshot-output
   #:snapshot-timestamp
   #:snapshot-revision
   #:snapshot-items
   #:presentation-material
   #:solid-color-material
   #:surface-texture-material
   #:shader-material
   #:material-color
   #:material-texture
   #:material-opacity
   #:material-program-name
   #:material-uniforms
   #:presentation-item
   #:presentation-geometry
   #:mesh-geometry
   #:mesh-geometry-vertices
   #:mesh-geometry-vertex-count
   #:make-mesh-geometry
   #:mesh-geometry-bounds
   #:presentation-item-material
   #:presentation-item-owner
   #:presentation-item-surface
   #:presentation-item-x
   #:presentation-item-y
   #:presentation-item-width
   #:presentation-item-height
   #:presentation-item-geometry
   #:presentation-item-mapping
   #:presentation-item-interactive-p
   #:presentation-item-hit-kind
   #:presentation-item-source-width
   #:presentation-item-source-height
   #:make-solid-item
   #:make-surface-item
   #:make-shader-item
   #:soft-shadow-style
   #:soft-shadow-enabled-p
   #:soft-shadow-color
   #:soft-shadow-inset
   #:soft-shadow-corner-radius
   #:soft-shadow-blur-radius
   #:soft-shadow-lifted-blur-radius
   #:soft-shadow-rest-offset-x
   #:soft-shadow-rest-offset-y
   #:soft-shadow-lifted-offset-x
   #:soft-shadow-lifted-offset-y
   #:soft-shadow-ambient-color
   #:soft-shadow-ambient-blur-radius
   #:behavior-shadow-style
   #:behavior-background-color
   #:effect-parameter-binding
   #:effect-parameter-binding-name
   #:view-effect-parameter
   #:behavior-default-animation-definition
   #:presentation-hit
   #:presentation-hit-item
   #:presentation-hit-owner
   #:presentation-hit-surface
   #:presentation-hit-surface-x
   #:presentation-hit-surface-y
   #:presentation-hit-kind
   #:make-presentation-hit
   #:build-presentation-snapshot
   #:presentation-hit-test
   #:render-presentation-frame
   #:present-output
   #:schedule-presentation
   #:frame-context
   #:frame-context-output
   #:frame-context-snapshot
   #:frame-context-state
   #:frame-context-buffer
   #:frame-context-framebuffer
   #:frame-context-width
   #:frame-context-height
   #:output-system
   #:compositor-output
   #:output-native
   #:output-behavior-state
   #:output-viewport
   #:output-last-snapshot
   #:output-commit-pending-p
   #:output-redraw-pending-p
   #:output-refresh-seconds
   #:arm-output-frame
   #:request-output-frame-now
   #:queue-output-presentation
   #:interaction-system
   #:interaction-seats
   #:logical-seat
   #:seat-name
   #:seat-native
   #:seat-pointer-x
   #:seat-pointer-y
   #:seat-focused-view
   #:seat-cursor-mode
   #:seat-devices
   #:seat-keyboards
   #:seat-active-keyboard
   #:seat-operation
   #:create-logical-seat
   #:destroy-logical-seat
   #:assign-input-device
   #:unassign-input-device
   #:focus-view
   #:interactive-operation
   #:interactive-operation-kind
   #:interactive-operation-seat
   #:interactive-operation-view
   #:interactive-operation-edges
   #:interactive-operation-button
   #:interactive-operation-start-x
   #:interactive-operation-start-y
   #:interactive-operation-original-width
   #:interactive-operation-original-height
   #:interactive-operation-original-placement
   #:begin-interactive-operation
   #:begin-interactive-move
   #:begin-interactive-resize
   #:cancel-interactive-operation
   #:control-system
   #:control-local-principal
   #:control-principal
   #:control-action
   #:submit-control-action
   #:execute-control-action
   #:observe-compositor
   #:focus-view-action
   #:move-view-action
   #:place-view-action
   #:create-seat-action
   #:destroy-seat-action
   #:assign-input-device-action
   #:replace-behavior-policy-action
   #:pan-viewport-action
   #:zoom-viewport-action
   #:launch-application-action
   #:set-view-animation-action
   #:install-shader-program-action
   #:configure-view-shader-action
   #:create-compositor
   #:start-compositor
   #:run-compositor
   #:request-compositor-stop
   #:destroy-compositor
   #:launch-application
   #:main))
