;;;; Compositor package boundary.
;;;;
;;;; ATAXIA.COMPOSITOR exports policy-facing objects and operations. Raw GLES
;;;; entrypoints remain private implementation details of the graphics module.

(defpackage #:ataxia.compositor
  (:use #:cl)
  (:export
   #:compositor-error
   #:invalid-compositor-state
   #:hook-vetoed
   #:control-request-rejected
   #:graphics-failure
   #:compositor-component
   #:component-compositor
   #:component-state
   #:attach-component
   #:detach-component
   #:validate-component
   #:compositor
   #:compositor-runtime
   #:compositor-outputs
   #:compositor-surfaces
   #:compositor-desktop
   #:compositor-interaction
   #:compositor-world
   #:compositor-presentation
   #:compositor-graphics
   #:compositor-extensions
   #:compositor-control
   #:compositor-state
   #:operation-descriptor
   #:operation-subject
   #:operation-animation-override
   #:visibility-transition
   #:visibility-old-state
   #:visibility-new-state
   #:placement-transition
   #:placement-old-value
   #:placement-new-value
   #:interaction-transition
   #:interaction-old-state
   #:interaction-new-state
   #:content-transition
   #:operation-context
   #:context-subject
   #:context-operation
   #:context-old-state
   #:context-new-state
   #:context-cause
   #:context-provenance
   #:context-timestamp
   #:context-phase
   #:context-metadata
   #:provenance
   #:provenance-kind
   #:provenance-identity
   #:make-local-provenance
   #:extension-system
   #:extension-hooks
   #:hook-registry
   #:hook-context
   #:register-hook
   #:unregister-hook
   #:run-hook
   #:surface-system
   #:surface-record
   #:surface-record-native
   #:surface-record-buffer
   #:surface-record-texture
   #:surface-record-width
   #:surface-record-height
   #:surface-record-mapped-p
   #:application
   #:application-id
   #:application-app-id
   #:application-views
   #:view
   #:view-id
   #:view-native
   #:view-surface
   #:view-application
   #:view-placement
   #:view-width
   #:view-height
   #:view-title
   #:view-mapped-p
   #:view-presentable-p
   #:view-maximized-p
   #:view-fullscreen-p
   #:view-minimized-p
   #:view-animation-policy
   #:view-shader-program-name
   #:view-presentation-state
   #:popup-view
   #:desktop-system
   #:desktop-views
   #:desktop-applications
   #:desktop-stacking-order
   #:desktop-find-view
   #:desktop-raise-view
   #:world
   #:planar-world
   #:world-placement
   #:planar-placement
   #:placement-x
   #:placement-y
   #:placement-width
   #:placement-height
   #:placement-z
   #:placement-request
   #:viewport
   #:viewport-camera-x
   #:viewport-camera-y
   #:viewport-scale
   #:world-place-view
   #:world-update-placement
   #:world-project
   #:world-unproject
   #:world-hit-test
   #:pan-viewport
   #:zoom-viewport
   #:replace-world
   #:presentation-state
   #:presentation-opacity
   #:presentation-scale
   #:presentation-offset-x
   #:presentation-offset-y
   #:presentation-shader-uniforms
   #:animation-policy
   #:animation-policy-fallback
   #:animation-track
   #:animation-track-property
   #:animation-track-from
   #:animation-track-to
   #:animation-track-interpolator
   #:shader-uniform-binding
   #:shader-uniform-binding-name
   #:animation-definition
   #:animation-definition-duration
   #:animation-definition-tracks
   #:animation-definition-name
   #:animation-instance
   #:animation-instance-subject
   #:animation-instance-descriptor
   #:animation-instance-definition
   #:animation-instance-context
   #:animation-instance-started-at
   #:animation-instance-state
   #:animation-engine
   #:animation-engine-active
   #:set-animation-policy-definition
   #:resolve-animation
   #:start-transition
   #:sample-animations
   #:active-animations-p
   #:direct-gles-renderer
   #:renderer-begin-frame
   #:renderer-draw-item
   #:renderer-end-frame
   #:renderer-abort-frame
   #:shader-program-descriptor
   #:program-descriptor-kind
   #:shader-program
   #:compile-shader-program
   #:replace-shader-program
   #:set-view-shader-program
   #:set-view-shader-uniform
   #:presentation-system
   #:presentation-snapshot
   #:presentation-item
   #:presentation-item-shader-program-name
   #:presentation-item-shader-uniforms
   #:presentation-hit
   #:build-presentation-snapshot
   #:presentation-hit-test
   #:schedule-presentation
   #:output-system
   #:compositor-output
   #:output-native
   #:output-viewport
   #:output-last-snapshot
   #:interaction-system
   #:logical-seat
   #:seat-name
   #:seat-native
   #:seat-pointer-x
   #:seat-pointer-y
   #:seat-focused-view
   #:seat-cursor-mode
   #:create-logical-seat
   #:destroy-logical-seat
   #:focus-view
   #:interactive-operation
   #:interactive-operation-button
   #:begin-interactive-move
   #:begin-interactive-resize
   #:cancel-interactive-operation
   #:control-system
   #:control-principal
   #:control-action
   #:submit-control-action
   #:execute-control-action
   #:observe-compositor
   #:focus-view-action
   #:move-view-action
   #:create-seat-action
   #:set-view-animation-action
   #:install-shader-program-action
   #:configure-view-shader-action
   #:create-compositor
   #:start-compositor
   #:run-compositor
   #:request-compositor-stop
   #:destroy-compositor
   #:launch-application
   #:main))
