;;;; Reusable HTML document presentation, independent of shell or concrete World policy.
(defpackage #:ataxia.world.web.ui
  (:use #:cl)
  (:export #:document-component #:document-widget #:make-ui-component #:make-ui-widget
           #:set-ui-class #:set-ui-style #:set-ui-attribute #:set-ui-model #:ui-model-value
           #:document-overlay #:show-notification #:input-seat
           #:widget-cache #:cache-widget-value #:set-widget-text #:set-widget-style))
(in-package #:ataxia.world.web.ui)
(defclass document-overlay (ataxia.world:ui-overlay) ())
(defmethod ataxia.world:destroy-overlay ((overlay document-overlay))
  (let ((component (ataxia.world:overlay-component overlay)))
    (ataxia.world:ui-set-invalidator component nil)
    (ataxia.kernel:drawable-detach-graphics component)
    (ataxia.world:ui-destroy component)))
(defclass document-widget (ataxia.world.web:web-widget)
  ((cache :initform (make-hash-table :test #'equal) :reader widget-cache)))
(defun cache-widget-value (widget key value function)
  (unless (equal (gethash key (widget-cache widget) :absent) value)
    (funcall function (ataxia.world:overlay-component widget))
    (setf (gethash key (widget-cache widget)) value)))
(defun set-widget-text (widget id value)
  (cache-widget-value widget id value
    (lambda (component) (ataxia.world:ui-set-property component id value))))
(defun set-widget-style (widget id property value)
  (cache-widget-value widget (list id property) value
    (lambda (component) (set-ui-style component id property value))))
(defgeneric set-ui-class (component id name enabled))
(defgeneric set-ui-style (component id property value))
(defgeneric set-ui-model (component name value))
(defgeneric ui-model-value (component name))
(defclass document-component (ataxia.world.web:web-component)
  ((input-seat :initform nil :accessor input-seat)
   (focus-token :initform nil :accessor %focus-token)
   (updates :initform nil :accessor %updates)
   (idle :initform nil :accessor %idle)
   (incoming :initform (make-hash-table :test #'equal) :reader %incoming)
   (models :initform (make-hash-table :test #'equal) :reader %models)))
(defun %scalar (value)
  (etypecase value
    (string (ataxia.world.wire:encode value))
    (boolean (if value "true" "false"))
    (real (format nil "~F" (coerce value 'double-float)))))
(defun %flush (component)
  (setf (%idle component) nil)
  (let ((updates (nreverse (shiftf (%updates component) nil))))
    (when (and updates (not (ataxia.world.web::%destroyed component))
               (not (ataxia.world.web::%engine-stopped (ataxia.world.web::%engine component))))
      ;; Bound each IPC command, including UTF-8 and the JavaScript string escape.
      ;; Large transcripts are assembled in the page before a single DOM update.
      (let ((batch nil) (size 0))
        (labels ((send-batch ()
                   (when batch
                     (ataxia.world.web:post-web-message component "ui" (format nil "[~{~A~^,~}]" (nreverse batch)))
                     (setf batch nil size 0)))
                 (entry (item)
                   (let ((json (format nil "[~{~A~^,~}]" (mapcar #'%scalar item))))
                     (when (> (+ size (length json)) 12000) (send-batch))
                     (push json batch) (incf size (1+ (length json))))))
          (dolist (item updates)
            (destructuring-bind (op id key value) item
              (if (and (stringp value) (> (length value) 2048))
                  (progn
                    (entry (list "string-start" id op key))
                    (loop for start from 0 below (length value) by 2048 do
                      (entry (list "string-part" id op (subseq value start (min (length value) (+ start 2048))))))
                    (entry (list "string-end" id op "")))
                  (entry item))))
          (send-batch))))))
(defun %update (component op id key value)
  (push (list op id key value) (%updates component))
  (unless (%idle component)
    (setf (%idle component)
          (ataxia.runtime:add-event-loop-idle
           (ataxia.kernel:kernel-runtime
            (ataxia.kernel:world-kernel (ataxia.world.web::%engine-world (ataxia.world.web::%engine component))))
           (lambda (source) (declare (ignore source)) (%flush component) 0))))
  value)
(defmethod ataxia.world:ui-destroy :before ((component document-component))
  (when (%idle component) (ataxia.runtime:remove-event-loop-source (%idle component)))
  (setf (%idle component) nil (%updates component) nil))
(defmethod ataxia.world:ui-set-property ((component document-component) name value)
  (set-ui-model component name value))
(defmethod set-ui-class ((component document-component) id name enabled)
  (%update component "class" id name (not (null enabled))))
(defmethod set-ui-style ((component document-component) id property value)
  (%update component "style" id property value))
(defmethod set-ui-model ((component document-component) name value)
  (unless (equal value (gethash name (%models component) :absent))
    (setf (gethash name (%models component)) value)
    (%update component "model" name "" value)))
(defmethod ui-model-value ((component document-component) name)
  (gethash name (%models component)))
(defmethod ataxia.world.web::%dispatch-event :around ((component document-component) name json)
  (%update component "input-ack" name "" "")
  ;; Shell models send JSON strings; page data never reaches the Lisp reader.
  (let ((value (if (and (plusp (length json)) (char= (char json 0) #\"))
                   (ataxia.world.wire:decode json :max-string (length json))
                   json)))
    (cond
      ((uiop:string-prefix-p "__start:" name)
       (setf (gethash (subseq name 8) (%incoming component)) (list 0))
       (return-from ataxia.world.web::%dispatch-event nil))
      ((uiop:string-prefix-p "__part:" name)
       (let ((parts (gethash (subseq name 7) (%incoming component))))
         (when parts
           (when (> (incf (car parts) (length value)) 1048576)
             (remhash (subseq name 7) (%incoming component))
             (return-from ataxia.world.web::%dispatch-event nil))
           (push value (cdr parts))))
       (return-from ataxia.world.web::%dispatch-event nil))
      ((uiop:string-prefix-p "__end:" name)
       (setf name (subseq name 6))
       (let ((parts (gethash name (%incoming component))))
         (unless parts (return-from ataxia.world.web::%dispatch-event nil))
         (setf value (format nil "~{~A~}" (nreverse (cdr parts))))
         (remhash name (%incoming component)))))
    (when (uiop:string-prefix-p "model:" name)
      (setf (gethash (subseq name 6) (%models component)) value))
    (let* ((world (ataxia.world.web::%engine-world (ataxia.world.web::%engine component)))
           (seat (input-seat component)))
      (cond
        ((and seat (equal name "clipboard:copy")) (ataxia.world:set-clipboard-text world seat value))
        ((and seat (equal name "clipboard:paste"))
         (let ((focus (%focus-token component)))
           (ataxia.world:request-clipboard-text world seat
             (lambda (text)
               (when (and text (not (ataxia.world.web::%destroyed component))
                          (eq focus (%focus-token component)) (eq seat (input-seat component)))
                 (%update component "paste" value "" text))))))))
    (call-next-method component name value)))

(defun set-ui-attribute (component id name value)
  (%update component "attribute" id name (or value nil)))
(defun make-ui-component (&key world source source-path component-name
                              (width 640d0) (height 360d0) (scale 1d0)
                              (component-class 'document-component))
  (declare (ignore source component-name))
  (let* ((root (asdf:system-relative-pathname "ataxia-web" "src/"))
         (path (truename source-path)))
    (unless (uiop:subpathp path root) (error "Built-in UI document is outside its asset root: ~A" path))
    (ataxia.world.web:make-web-component :world world :asset-root root
      :url (format nil "ataxia://ui/~A" (enough-namestring path root))
      :width width :height height :scale scale :component-class component-class)))
(defun make-ui-widget (class world path &rest options)
  (apply #'ataxia.world:create-agent-widget class world ""
    :source-path (namestring path)
    :component-factory (lambda (&rest args) (apply #'make-ui-component :world world args)) options))

(defmethod ataxia.kernel:interactable-pointer-button :before ((component document-component) world seat x y input)
  (declare (ignore world x y input)) (setf (input-seat component) seat))
(defmethod ataxia.kernel:interactable-focus :before ((component document-component) world seat kind)
  (declare (ignore world))
  (setf (input-seat component) (and (eq kind :keyboard) seat) (%focus-token component) (list kind)))
