;;;; Seat-local Wayland text transfers and bounded, memory-only history.
(in-package #:ataxia.world.shell)
(defstruct clipboard-seat text ready private history transfer)
(defstruct clipboard-transfer fd source timer callbacks
  (bytes (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
(defconstant +clipboard-transfer-limit+ (* 4 1024 1024))
(defconstant +clipboard-history-entry-limit+ (* 256 1024))
(defun %clipboard-seat (service seat)
  (when (shell-service-clipboard service)
    (or (gethash seat (shell-service-clipboard service))
        (setf (gethash seat (shell-service-clipboard service)) (make-clipboard-seat)))))
(defun %clipboard-remember (state text)
  (when (and text (plusp (length text)) (not (clipboard-seat-private state))
             (<= (length (babel:string-to-octets text :encoding :utf-8)) +clipboard-history-entry-limit+))
    (let ((entries (cons text (remove text (clipboard-seat-history state) :test #'equal))) (total 0))
      (setf (clipboard-seat-history state)
            (loop for entry in entries for i below 20
                  for size = (length (babel:string-to-octets entry :encoding :utf-8))
                  while (<= (incf total size) (* 2 1024 1024)) collect entry)))))
(defun %clipboard-finish (world service state job text)
  (when (eq job (clipboard-seat-transfer state))
    (setf (clipboard-seat-transfer state) nil)
    (dolist (source (list (clipboard-transfer-source job) (clipboard-transfer-timer job)))
      (when source (ataxia.runtime:remove-event-loop-source source)))
    (when (clipboard-transfer-fd job)
      (cffi:foreign-funcall "close" :int (clipboard-transfer-fd job) :int)
      (setf (clipboard-transfer-fd job) nil))
    (setf (clipboard-seat-text state) text (clipboard-seat-ready state) t)
    (%clipboard-remember state text)
    (when (eq service (world-service world :shell)) (%sync-clipboard-popups world service))
    (dolist (callback (clipboard-transfer-callbacks job)) (funcall callback text))))
(defun %clipboard-read-ready (world service state job)
  (when (eq job (clipboard-seat-transfer state))
    (handler-case
        (cffi:with-foreign-object (buffer :uint8 16384)
          ;; Bound work per event; an unfinished pipe remains readable.
          (loop repeat 4 for count = (cffi:foreign-funcall "read" :int (clipboard-transfer-fd job)
                                      :pointer buffer :size 16384 :long) do
            (cond ((plusp count)
                   (when (> (+ count (length (clipboard-transfer-bytes job))) +clipboard-transfer-limit+)
                     (%clipboard-finish world service state job nil) (return))
                   (dotimes (i count) (vector-push-extend (cffi:mem-aref buffer :uint8 i) (clipboard-transfer-bytes job))))
                  ((zerop count)
                   (%clipboard-finish world service state job
                     (babel:octets-to-string (clipboard-transfer-bytes job) :encoding :utf-8)) (return))
                  ((member (cffi:mem-ref (cffi:foreign-funcall "__errno_location" :pointer) :int) '(4 11)) (return))
                  (t (%clipboard-finish world service state job nil) (return)))))
      (error () (%clipboard-finish world service state job nil)))))
(defun %clipboard-begin (world service seat state &optional callback)
  (let* ((runtime-seat (ataxia.kernel:seat-runtime-object seat))
         (types (ataxia.runtime:seat-selection-mime-types runtime-seat))
         (mime (find-if (lambda (x) (member x types :test #'equal))
                       '("text/plain;charset=utf-8" "text/plain;charset=UTF-8" "UTF8_STRING" "text/plain"))))
    (setf (clipboard-seat-private state)
          (some (lambda (x) (member x '("x-kde-passwordManagerHint" "application/x-keepassxc"
                                        "application/x-kde-passwordManagerHint") :test #'equal)) types))
    (unless mime
      (setf (clipboard-seat-text state) nil (clipboard-seat-ready state) t)
      (when callback (funcall callback nil)) (return-from %clipboard-begin t))
    (let ((job (make-clipboard-transfer :callbacks (when callback (list callback))))
          (runtime (ataxia.kernel:kernel-runtime (ataxia.kernel:world-kernel world))) (write-fd nil))
      (setf (clipboard-seat-transfer state) job (clipboard-seat-ready state) nil)
      (handler-case
          (cffi:with-foreign-object (fds :int 2)
            (unless (zerop (cffi:foreign-funcall "pipe2" :pointer fds :int #x80000 :int))
              (error "Cannot open clipboard transfer."))
            (setf (clipboard-transfer-fd job) (cffi:mem-aref fds :int 0) write-fd (cffi:mem-aref fds :int 1))
            (unless (zerop (cffi:foreign-funcall "fcntl" :int (clipboard-transfer-fd job) :int 4 :int #x800 :int))
              (error "Cannot make clipboard reader nonblocking."))
            (setf (clipboard-transfer-source job)
                  (ataxia.runtime:add-event-loop-fd runtime (clipboard-transfer-fd job) ataxia.runtime:+event-readable+
                    (lambda (source fd mask) (declare (ignore source fd mask))
                      (%clipboard-read-ready world service state job) 0))
                  (clipboard-transfer-timer job)
                  (ataxia.runtime:add-event-loop-timer runtime
                    (lambda (source) (declare (ignore source)) (%clipboard-finish world service state job nil) 0)))
            (ataxia.runtime:update-event-loop-timer (clipboard-transfer-timer job) 2000)
            ;; Native receive always consumes the write descriptor.
            (let ((fd write-fd)) (setf write-fd nil)
              (unless (ataxia.runtime:seat-selection-receive runtime-seat mime fd)
                (%clipboard-finish world service state job nil))))
        (error ()
          (when write-fd (cffi:foreign-funcall "close" :int write-fd :int))
          (%clipboard-finish world service state job nil)))
      t)))
(defmethod service-selection-changed ((service shell-service) world seat)
  (when (and (shell-service-clipboard service) (not (agent-seat-p seat)))
    (let ((state (%clipboard-seat service seat)))
      (when (clipboard-seat-transfer state)
        (%clipboard-finish world service state (clipboard-seat-transfer state) nil))
      (unless (ataxia.runtime:seat-clipboard-owned-p (ataxia.kernel:seat-runtime-object seat))
        (setf (clipboard-seat-text state) nil (clipboard-seat-ready state) nil)
        (%clipboard-begin world service seat state)))))
(defmethod request-clipboard-text ((world ataxia.kernel:world) seat callback)
  (let ((service (world-service world :shell)))
    (when (and service (shell-service-clipboard service))
      ;; Native UI's process-local fallback must not expose another seat's data.
      (when (agent-seat-p seat) (funcall callback nil) (return-from request-clipboard-text t))
      (let* ((state (%clipboard-seat service seat)) (job (clipboard-seat-transfer state)))
        (cond (job (push callback (clipboard-transfer-callbacks job)))
              ((clipboard-seat-ready state) (funcall callback (clipboard-seat-text state)))
              (t (%clipboard-begin world service seat state callback))) t))))
(defmethod set-clipboard-text ((world ataxia.kernel:world) seat text)
  (let ((service (world-service world :shell)))
    (when (and service (shell-service-clipboard service) (not (agent-seat-p seat)))
      (let ((state (%clipboard-seat service seat)))
        (when (clipboard-seat-transfer state)
          (%clipboard-finish world service state (clipboard-seat-transfer state) nil))
        (ataxia.runtime:seat-set-clipboard-text (ataxia.kernel:seat-runtime-object seat) text)
        (setf (clipboard-seat-text state) text (clipboard-seat-ready state) t (clipboard-seat-private state) nil)
        (%clipboard-remember state text) (%sync-clipboard-popups world service) t))))
(defun %stop-clipboard-seat (world service seat)
  (let ((state (gethash seat (shell-service-clipboard service))))
    (when (and state (clipboard-seat-transfer state))
      (%clipboard-finish world service state (clipboard-seat-transfer state) nil))
    (remhash seat (shell-service-clipboard service))))
(defmethod service-seat-removing ((service shell-service) world seat)
  (when (shell-service-clipboard service) (%stop-clipboard-seat world service seat))
  (maphash (lambda (key value) (declare (ignore value))
             (when (eq (first key) seat) (remhash key (shell-service-sleep-keys service))))
           (shell-service-sleep-keys service)))
