;;;; System controls shared by the bar, popups and hardware keys.
(in-package #:ataxia.world.shell)
(defun %audio-percent (view) (or (first (getf view :volume-target)) (getf view :volume)))
(defun %audio-muted (view) (if (getf view :mute-target) (first (getf view :mute-target)) (getf view :muted)))
(defun %update-media-popup (popup audio media)
  (let* ((volume (%audio-percent audio)) (muted (%audio-muted audio))
         (player (getf media :player)) (playing (equal (getf player :status) "Playing"))
         (enabled (getf player :can-control)))
    (%shell-class popup "has-player" (not (null player)))
    (setf (gethash :preferred-height (widget-cache popup))
          (if player (+ 132d0 (if (and (getf player :artist) (plusp (length (getf player :artist)))) 16d0 0d0)) 84d0))
    (set-widget-style popup "artist" "display" (if (and (getf player :artist) (plusp (length (getf player :artist)))) "block" "none"))
    (set-widget-text popup "empty" (or (getf media :error)
                                     (if (getf media :available) "No media playing" "Media service unavailable")))
    (%power-model popup "audio_disabled" (not (getf audio :available)))
    (%power-model popup "previous_disabled" (not (and enabled (getf player :can-previous))))
    (%power-model popup "next_disabled" (not (and enabled (getf player :can-next))))
    (%power-model popup "play_disabled" (not (and enabled (getf player (if playing :can-pause :can-play)))))
    (%power-model popup "player_disabled" (< (length (getf media :players)) 2))
    (let ((value (princ-to-string (or volume 0))))
      (unless (equal value (ataxia.world.rmlui:rmlui-model-value (overlay-component popup) "volume"))
        (ataxia.world.rmlui:set-rmlui-model (overlay-component popup) "volume" value)))
    (set-widget-text popup "volume-value" (if volume (format nil "~D%~A" volume (if muted " · muted" "")) "Unavailable"))
    (set-widget-text popup "mute" (if muted "Unmute" "Mute"))
    (set-widget-text popup "device" (or (getf audio :error) (getf audio :device) "No audio output available"))
    (set-widget-text popup "player" (or (getf player :identity) "No media player"))
    (set-widget-text popup "track" (or (getf player :title) "Nothing playing"))
    (set-widget-text popup "artist" (or (getf player :artist) ""))
    (set-widget-text popup "play" (if playing "Pause" "Play"))
    (set-widget-text popup "playback" (or (getf media :error) (getf player :status)
                                         (if (getf media :available) "Waiting for a player" "Media service unavailable")))))
(defun %sync-system-controls (world service)
  (let ((audio (%system-view (shell-service-audio service))) (media (%system-view (shell-service-media service))))
    (dolist (bar (status-bars world))
      (set-widget-text bar "audio" (if (getf audio :available) (if (%audio-muted audio) "Mute" (format nil "♪ ~D%" (%audio-percent audio))) "♪ —"))
      (set-widget-text bar "media" (short-ui-text (or (getf (getf media :player) :title) "Media") 23))
      (set-bar-class bar "has-media" (not (null (getf media :player))))
      (let ((popup (%bar-popup bar)))
        (when (and popup (eq :media (%shell-popup-kind popup))) (%update-media-popup popup audio media))))
    (maphash (lambda (output osd) (declare (ignore output))
               (case (%osd-kind osd)
                 (:volume (%paint-osd osd :volume (%audio-percent audio)
                             (or (getf audio :error) (getf audio :device) "Audio output unavailable")
                             :muted (%audio-muted audio) :error (or (getf audio :error) (not (getf audio :available)))))
                 (:media (let ((player (getf media :player)))
                           (%paint-osd osd :media (or (getf player :status) "Media")
                             (or (getf media :error) (getf player :title) "No media player") :error (getf media :error))))))
             (shell-service-osds service))))
(defun %request-volume (world service value &key relative mute output)
  (let* ((controller (shell-service-audio service)) (view (%system-view controller))
         (current (%audio-percent view)))
    (setf (shell-service-feedback-output service) output)
    (when (and current (getf view :available))
      (if mute (%system-queue controller :mute (not (%audio-muted view)))
          (progn (%system-queue controller :volume (max 0 (min 100 (if relative (+ current value) value))))
                 (when (%audio-muted view) (%system-queue controller :mute nil)))))
    (let ((new (%system-view controller)))
      (%show-osd world service :volume (%audio-percent new)
        (or (getf new :device) "Audio output unavailable") :muted (%audio-muted new) :output output
        :error (not (getf new :available))))
    (%sync-system-controls world service)))
(defun %request-media (world service command output)
  (setf (shell-service-feedback-output service) output)
  (%system-queue (shell-service-media service) command)
  (let ((player (getf (%system-view (shell-service-media service)) :player)))
    (%show-osd world service :media (or (getf player :identity) "Media")
      (or (getf player :title) "No media player") :output output)))
(defun %initialize-media-popup (world popup)
  (let ((service (world-service world :shell)))
    (ataxia.world.rmlui:set-rmlui-model (overlay-component popup) "volume" "0")
    (bind-agent-widget-event popup "model:volume"
      (lambda (widget event)
        (let ((value (ignore-errors (parse-integer (agent-widget-event-value event)))))
          (when value (%request-volume world service value :output (overlay-output widget))))))
    (bind-agent-widget-event popup "mute"
      (lambda (widget event) (declare (ignore event)) (%request-volume world service 0 :mute t :output (overlay-output widget))))
    (dolist (entry '(("previous" . :previous) ("play" . :play-pause) ("next" . :next)))
      (let ((command (cdr entry)))
        (bind-agent-widget-event popup (car entry)
          (lambda (widget event) (declare (ignore event)) (%request-media world service command (overlay-output widget))))))
    (bind-agent-widget-event popup "player"
      (lambda (widget event) (declare (ignore widget event))
        (let* ((controller (shell-service-media service)) (view (%system-view controller))
               (players (getf view :players))
               (index (position (getf (getf view :player) :name) players :test #'equal :key (lambda (x) (getf x :name)))))
          (when players (%system-queue controller :player (getf (nth (mod (1+ (or index -1)) (length players)) players) :name))))))
    (%sync-system-controls world service)))

(defun %clipboard-popup-history (world service popup)
  (let* ((seat (world-seat-on-output world (overlay-output popup)))
         (state (and seat (%clipboard-seat service seat))))
    (and state (clipboard-seat-history state))))
(defun %clipboard-results (world service popup &optional (reset nil))
  (let* ((query (or (ataxia.world.rmlui:rmlui-model-value (overlay-component popup) "query") ""))
         (history (%clipboard-popup-history world service popup))
         (entries (remove-if-not (lambda (text) (search query text :test #'char-equal))
                                history))
         (pages (max 1 (ceiling (length entries) 6)))
         (page (if reset 0 (max 0 (min (1- pages) (%shell-popup-page popup))))))
    (setf (%shell-popup-page popup) page (%shell-popup-matches popup) entries)
    (%shell-class popup "empty-results" (null entries))
    (setf (gethash :preferred-height (widget-cache popup)) (if entries 180d0 100d0))
    (set-widget-text popup "count" (if (plusp (length query))
                                       (format nil "~D match~:P" (length entries))
                                       (format nil "~D item~:P" (length entries))))
    (%power-model popup "prev_disabled" (zerop page))
    (%power-model popup "next_disabled" (= page (1- pages)))
    (%power-model popup "clear_disabled" (null history))
    (set-widget-text popup "empty" (if history "No matches. Try another search." "No copied text yet."))
    (set-widget-style popup "preview" "display" (if entries "block" "none"))
    (set-widget-text popup "page" (format nil "~D / ~D" (1+ page) pages))
    (set-widget-style popup "empty" "display" (if entries "none" "block"))
    (dotimes (i 6)
      (let ((entry (nth (+ (* page 6) i) entries)))
        (set-widget-style popup (format nil "app~D" i) "display" (if entry "block" "none"))
        (when entry (set-widget-text popup (format nil "app~D" i)
                     (short-ui-text (substitute #\Space #\Newline (substitute #\Space #\Tab entry)) 100)))))
    (%shell-select popup (if reset 0 (%shell-popup-selected popup)))))
(defun %sync-clipboard-popups (world service)
  (dolist (bar (status-bars world))
    (let ((popup (%bar-popup bar)))
      (when (and popup (eq :clipboard (%shell-popup-kind popup))) (%clipboard-results world service popup)))))
(defun %choose-clipboard (world popup index)
  (let ((text (nth (+ (* 6 (%shell-popup-page popup)) index) (%shell-popup-matches popup)))
        (seat (world-seat-on-output world (overlay-output popup))))
    (when (and text seat (set-clipboard-text world seat text)) (%bar-close-popup world (%shell-popup-bar popup)))))
(defun %initialize-clipboard-popup (world popup)
  (let ((service (world-service world :shell)))
    (ataxia.world.rmlui:set-rmlui-model (overlay-component popup) "query" "")
    (bind-agent-widget-event popup "model:query"
      (lambda (widget event) (declare (ignore event)) (%clipboard-results world service widget t)))
    (dolist (entry '(("search:focus" . t) ("search:blur" . nil)))
      (let ((focused (cdr entry)))
        (bind-agent-widget-event popup (car entry)
          (lambda (widget event) (declare (ignore event)) (setf (%shell-search-focused-p widget) focused)))))
    (dotimes (i 6) (let ((index i))
                    (bind-agent-widget-event popup (format nil "app~D" index)
                      (lambda (widget event) (declare (ignore event)) (%choose-clipboard world widget index)))))
    (dolist (entry '(("prev" . -1) ("next" . 1)))
      (let ((delta (cdr entry)))
        (bind-agent-widget-event popup (car entry)
          (lambda (widget event) (declare (ignore event)) (incf (%shell-popup-page widget) delta)
            (%clipboard-results world service widget)))))
    (bind-agent-widget-event popup "clear"
      (lambda (widget event) (declare (ignore event))
        (let* ((seat (world-seat-on-output world (overlay-output widget))) (state (and seat (%clipboard-seat service seat))))
          (when state (setf (clipboard-seat-history state) nil)) (%sync-clipboard-popups world service))))
    (%clipboard-results world service popup)))
(defun %initialize-extra-popup (world popup)
  (ecase (%shell-popup-kind popup)
    (:spaces (%initialize-workspace-popup world popup))
    (:media (%initialize-media-popup world popup))
    (:clipboard (%initialize-clipboard-popup world popup))))

(defun %controls-key-event (world service seat input)
  (when (typep input 'ataxia.kernel:key-input)
    (let* ((modifiers (ataxia.kernel:key-input-modifiers input))
           (pressed (eq :pressed (ataxia.kernel:key-input-state input)))
           (symbols (ataxia.kernel:key-input-keysyms input))
           (output (world-seat-output world seat))
           (popup (%shell-popup-on-seat world seat)))
      (let ((token (list seat (ataxia.kernel:key-input-device input) :clipboard
                         (ataxia.kernel:key-input-keycode input))))
        (when (and (not pressed) (gethash token (shell-service-sleep-keys service)))
          (remhash token (shell-service-sleep-keys service))
          (return-from %controls-key-event t))
        (when (and (member :logo modifiers) (member :control modifiers) (not (member :alt modifiers))
                   (find "v" symbols :test #'string-equal))
          (when (and pressed (not (gethash token (shell-service-sleep-keys service))))
            (setf (gethash token (shell-service-sleep-keys service)) t)
            (let ((bar (find output (status-bars world) :key #'overlay-output)))
              (when bar (%bar-toggle-popup world bar :clipboard))))
          (return-from %controls-key-event t)))
      (when (intersection '(:logo :control :alt) modifiers) (return-from %controls-key-event nil))
      (let ((key (find-if (lambda (x) (member x '("XF86AudioRaiseVolume" "XF86AudioLowerVolume" "XF86AudioMute"
                                                "XF86AudioPlay" "XF86AudioPause" "XF86AudioNext" "XF86AudioPrev" "XF86AudioStop") :test #'equal)) symbols)))
        (when key
          (let* ((repeatable (member key '("XF86AudioRaiseVolume" "XF86AudioLowerVolume") :test #'equal))
                 (token (list seat (ataxia.kernel:key-input-device input) key)))
            (cond ((not pressed) (remhash token (shell-service-sleep-keys service)))
                  ((or repeatable (not (gethash token (shell-service-sleep-keys service))))
                   (setf (gethash token (shell-service-sleep-keys service)) t)
                   (cond (repeatable (%request-volume world service (if (equal key "XF86AudioRaiseVolume") 5 -5) :relative t :output output))
                         ((equal key "XF86AudioMute") (%request-volume world service 0 :mute t :output output))
                         (t (%request-media world service
                              (cond ((equal key "XF86AudioNext") :next) ((equal key "XF86AudioPrev") :previous)
                                    ((equal key "XF86AudioStop") :stop) (t :play-pause)) output))))))
          (return-from %controls-key-event t)))
      (when (and popup pressed (eq popup (world-seat-focus world seat)))
        (case (%shell-popup-kind popup)
          (:spaces (let ((number (find-if (lambda (s) (and (= 1 (length s)) (find (char s 0) "123456789"))) symbols)))
                     (when number (%choose-workspace world popup (parse-integer number)) t)))
          (:clipboard
           (when (%shell-search-focused-p popup)
             (let ((key (find-if (lambda (x) (member x '("Return" "Up" "Down" "Prior" "Next") :test #'equal)) symbols)))
               (when key
                 (cond ((equal key "Return") (%choose-clipboard world popup (%shell-popup-selected popup)))
                       ((equal key "Up") (%shell-select popup (1- (%shell-popup-selected popup))))
                       ((equal key "Down") (%shell-select popup (1+ (%shell-popup-selected popup))))
                       (t (incf (%shell-popup-page popup) (if (equal key "Next") 1 -1))
                          (%clipboard-results world service popup))) t)))))))))
(defun %start-shell-controls (world service)
  (setf (shell-service-clipboard service) (make-hash-table :test #'eq)
        (shell-service-audio service) (%start-system-controller world service :audio #'%run-audio)
        (shell-service-media service) (%start-system-controller world service :media #'%run-media))
  (dolist (seat (world-seats world)) (service-selection-changed service world seat))
  (%sync-system-controls world service))
(defun %stop-shell-controls (world service)
  (%stop-system-controller (shell-service-audio service))
  (%stop-system-controller (shell-service-media service))
  (when (shell-service-clipboard service)
    (dolist (seat (loop for seat being the hash-keys of (shell-service-clipboard service) collect seat))
      (%stop-clipboard-seat world service seat))
    (setf (shell-service-clipboard service) nil))
  (when (shell-service-osd-timer service)
    (ataxia.runtime:remove-event-loop-source (shell-service-osd-timer service))
    (setf (shell-service-osd-timer service) nil))
  (maphash (lambda (output osd) (declare (ignore output)) (remove-agent-widget world osd)) (shell-service-osds service))
  (clrhash (shell-service-osds service)))
(defmethod service-output-removing ((service shell-service) world output)
  (let ((osd (gethash output (shell-service-osds service))))
    (when osd (remhash output (shell-service-osds service)) (remove-agent-widget world osd) (%schedule-osd world service)))
  (dolist (bar (status-bars world))
    (when (eq output (overlay-output bar)) (%bar-close-popup world bar) (remove-agent-widget world bar))))
(defmethod service-output-changed ((service shell-service) world output change)
  (declare (ignore change))
  (let ((osd (gethash output (shell-service-osds service)))) (when osd (%position-osd world osd))))
