;;;; Event-driven system workers publish copied state through an owner eventfd.
(in-package #:ataxia.world.shell)

(defstruct system-controller kind
  (lock (sb-thread:make-mutex :name "Shell system state"))
  (queue nil) (state nil) stopped thread owner-fd wake-fd source native-wake)
(cffi:defcstruct shell-pollfd (fd :int) (events :short) (revents :short))

(defun %eventfd ()
  (let ((fd (cffi:foreign-funcall "eventfd" :uint 0 :int #x80800 :int)))
    (when (minusp fd) (error "Could not create a system event descriptor.")) fd))
(defun %signal-fd (fd)
  (when fd (cffi:with-foreign-object (value :uint64)
             (setf (cffi:mem-ref value :uint64) 1)
             (cffi:foreign-funcall "write" :int fd :pointer value :size 8 :long))))
(defun %drain-fd (fd)
  (when fd (cffi:with-foreign-object (value :uint64)
             (cffi:foreign-funcall "read" :int fd :pointer value :size 8 :long))))
(defun %system-view (controller)
  (when controller
    (sb-thread:with-mutex ((system-controller-lock controller))
      (copy-tree (system-controller-state controller)))))
(defun %system-publish (controller &rest properties)
  (sb-thread:with-mutex ((system-controller-lock controller))
    (unless (system-controller-stopped controller)
      (let ((changed nil))
        (loop for (key value) on properties by #'cddr do
          (unless (equalp value (getf (system-controller-state controller) key))
            (setf (getf (system-controller-state controller) key) value changed t)))
        (when changed (%signal-fd (system-controller-owner-fd controller)))))))
(defun %system-queue (controller command &optional value)
  (when controller
    (sb-thread:with-mutex ((system-controller-lock controller))
      (unless (system-controller-stopped controller)
        (let ((existing (and (member command '(:volume :mute :refresh :player))
                             (assoc command (system-controller-queue controller)))))
          (cond (existing (setf (cdr existing) value))
                ((< (length (system-controller-queue controller)) 16)
                 (setf (system-controller-queue controller)
                       (nconc (system-controller-queue controller) (list (cons command value)))))
                (t (return-from %system-queue nil))))
        (when (member command '(:volume :mute))
          (setf (getf (system-controller-state controller) (if (eq command :volume) :volume-target :mute-target))
                (list value)))
        (%signal-fd (system-controller-wake-fd controller))
        (when (system-controller-native-wake controller) (funcall (system-controller-native-wake controller)))
        t))))
(defun %system-commands (controller)
  (sb-thread:with-mutex ((system-controller-lock controller))
    (%drain-fd (system-controller-wake-fd controller))
    (prog1 (system-controller-queue controller) (setf (system-controller-queue controller) nil))))
(defun %system-stopped-p (controller)
  (sb-thread:with-mutex ((system-controller-lock controller)) (system-controller-stopped controller)))
(defun %system-wait (controller timeout &optional descriptor (events 1))
  (cffi:with-foreign-objects ((fds '(:struct shell-pollfd) 2))
    (loop for fd in (list (system-controller-wake-fd controller) descriptor) for i from 0 do
      (let ((entry (cffi:mem-aptr fds '(:struct shell-pollfd) i)))
        (setf (cffi:foreign-slot-value entry '(:struct shell-pollfd) 'fd) (or fd -1)
              (cffi:foreign-slot-value entry '(:struct shell-pollfd) 'events) (if (zerop i) 1 events))))
    (cffi:foreign-funcall "poll" :pointer fds :ulong 2 :int timeout :int)))
(defun %stop-system-controller (controller)
  (when controller
    (when (system-controller-source controller)
      (ataxia.runtime:remove-event-loop-source (system-controller-source controller))
      (setf (system-controller-source controller) nil))
    (sb-thread:with-mutex ((system-controller-lock controller))
      (setf (system-controller-stopped controller) t (system-controller-queue controller) nil)
      (%signal-fd (system-controller-wake-fd controller))
      (when (system-controller-native-wake controller) (funcall (system-controller-native-wake controller)))
      (when (system-controller-owner-fd controller)
        (cffi:foreign-funcall "close" :int (system-controller-owner-fd controller) :int)
        (setf (system-controller-owner-fd controller) nil)))))
(defun %start-system-controller (world service kind runner)
  (let* ((controller (make-system-controller :kind kind))
         (kernel (ataxia.kernel:world-kernel world))
         (generation (ataxia.kernel:kernel-world-generation kernel)))
    (handler-case
        (progn
          (setf (system-controller-owner-fd controller) (%eventfd)
                (system-controller-wake-fd controller) (%eventfd)
                (system-controller-source controller)
                (ataxia.runtime:add-event-loop-fd
                 (ataxia.kernel:kernel-runtime kernel) (system-controller-owner-fd controller)
                 ataxia.runtime:+event-readable+
                 (lambda (source fd mask)
                   (declare (ignore source mask)) (%drain-fd fd)
                   (when (and (= generation (ataxia.kernel:kernel-world-generation kernel))
                              (eq service (world-service world :shell)))
                     (%sync-system-controls world service)) 0))
                (system-controller-thread controller)
                (sb-thread:make-thread
                 (lambda ()
                   (unwind-protect
                        (loop with failures = 0 until (%system-stopped-p controller) do
                          (handler-case (progn (funcall runner controller) (setf failures 0))
                            (error (cause)
                              (%system-publish controller :available nil :volume-target nil :mute-target nil :error (short-ui-text (princ-to-string cause) 140))
                              (incf failures)))
                          ;; Only a disconnected service retries. Connected workers
                          ;; block on subscriptions and never run a polling timer.
                          (unless (%system-stopped-p controller)
                            (%system-wait controller (* 1000 (min 30 (expt 2 (min 5 failures)))))
                            (%drain-fd (system-controller-wake-fd controller))))
                     (sb-thread:with-mutex ((system-controller-lock controller))
                       (setf (system-controller-native-wake controller) nil)
                       (when (system-controller-wake-fd controller)
                         (cffi:foreign-funcall "close" :int (system-controller-wake-fd controller) :int)
                         (setf (system-controller-wake-fd controller) nil)))))
                 :name (format nil "Shell ~A events" kind)))
          controller)
      (error (cause)
        (%stop-system-controller controller)
        (when (and (null (system-controller-thread controller)) (system-controller-wake-fd controller))
          (cffi:foreign-funcall "close" :int (system-controller-wake-fd controller) :int))
        (error cause)))))

(defclass shell-osd (rmlui-widget)
  ((kind :initarg :kind :accessor %osd-kind) (deadline :initform 0d0 :accessor %osd-deadline)))
(defmethod overlay-input-enabled-p ((overlay shell-osd)) nil)
(defun %position-osd (world osd)
  (multiple-value-bind (width height) (output-logical-size (overlay-output osd))
    (let ((ow (min 340d0 (max 1d0 (- width 24d0)))) (oh (min 106d0 (max 1d0 (- height 60d0)))))
      (position-widget world osd (/ (- width ow) 2d0) (max 0d0 (- height 64d0 oh)) ow oh))))
(defun %schedule-osd (world service)
  (unless (shell-service-osd-timer service)
    (setf (shell-service-osd-timer service)
          (ataxia.runtime:add-event-loop-timer
           (ataxia.kernel:kernel-runtime (ataxia.kernel:world-kernel world))
           (lambda (source)
             (declare (ignore source))
             (when (eq service (world-service world :shell))
               (let ((now (monotonic-time)))
                 (maphash (lambda (output osd)
                            (when (<= (%osd-deadline osd) now)
                              (remhash output (shell-service-osds service)) (remove-agent-widget world osd)))
                          (shell-service-osds service)))
               (%schedule-osd world service)) 0))))
  (let ((next nil))
    (maphash (lambda (output osd) (declare (ignore output))
               (setf next (if next (min next (%osd-deadline osd)) (%osd-deadline osd))))
             (shell-service-osds service))
    (ataxia.runtime:update-event-loop-timer
     (shell-service-osd-timer service) (if next (max 1 (ceiling (* 1000 (- next (monotonic-time))))) 0))))
(defun %paint-osd (osd kind value detail &key muted error)
  (setf (%osd-kind osd) kind)
  (set-widget-text osd "icon" (ecase kind (:brightness "☀") (:volume (if muted "×" "♪")) (:media "▶")))
  (set-widget-text osd "label" (ecase kind (:brightness "Brightness") (:volume (if muted "Muted" "Volume")) (:media value)))
  (set-widget-text osd "value" (if (eq kind :media) "" (if value (format nil "~D%" value) "—")))
  (set-widget-text osd "detail" (or detail ""))
  (when (numberp value) (set-widget-style osd "fill" "width" (format nil "~D%" (max 0 (min 100 value)))))
  (dolist (entry (list (cons "muted" muted) (cons "error" error) (cons "media" (eq kind :media))))
    (let ((name (car entry)) (enabled (not (null (cdr entry)))))
      (cache-widget-value osd (list :class name) enabled
        (lambda (component) (ataxia.world.rmlui:set-rmlui-class component "panel" name enabled))))))
(defun %show-osd (world service kind value detail &key output muted error)
  (let* ((output (or output (shell-service-feedback-output service) (first (world-outputs world))))
         (existing (gethash output (shell-service-osds service))))
    (when (and output (member output (world-outputs world)))
      (let* ((path (asdf:system-relative-pathname "ataxia-rmlui" "src/world/rmlui/status-bar/osd.rml"))
             (osd (or existing
                      (setf (gethash output (shell-service-osds service))
                            (create-agent-widget 'shell-osd world (uiop:read-file-string path)
                              :component-factory #'ataxia.world.rmlui:make-shell-rmlui-component
                              :source-path (namestring path) :output output :width 340d0 :height 106d0 :layer 1400)))))
        (%paint-osd osd kind value detail :muted muted :error error)
        (setf (%osd-deadline osd) (+ (monotonic-time) 1.6d0))
        (%position-osd world osd) (%schedule-osd world service) osd))))
(defun %update-brightness-osd (world service view)
  (declare (ignore world))
  (maphash (lambda (output osd)
             (declare (ignore output))
             (when (eq :brightness (%osd-kind osd))
               (%paint-osd osd :brightness (or (shell-service-brightness-target service)
                                              (getf (getf view :backlight) :percent))
                           (or (getf view :brightness-error) "Display backlight") :error (getf view :brightness-error))))
           (shell-service-osds service)))
