;;;; MPRIS discovery, metadata and transport over a private sd-bus connection.
(in-package #:ataxia.world.shell)
(cffi:define-foreign-library shell-systemd (:unix "libsystemd.so.0"))
(cffi:defcstruct shell-timespec (seconds :long) (nanoseconds :long))
(defun %bus-check (status)
  (when (minusp status) (error "D-Bus: ~A" (cffi:foreign-funcall "strerror" :int (- status) :string))) status)
(defun %bus-text (pointer)
  (unless (cffi:null-pointer-p pointer)
    (let ((length (cffi:foreign-funcall "strnlen" :pointer pointer :size 65537 :size)))
      (when (> length 65536) (error "Media metadata exceeds the text limit."))
      (cffi:foreign-string-to-lisp pointer :count length))))
(defun %session-bus-address ()
  ;; A login environment can outlive its bus GUID. Keep the selected transport
  ;; and socket, allowing the current broker to provide its own identity.
  (let* ((runtime (or (uiop:getenv "XDG_RUNTIME_DIR")
                      (format nil "/run/user/~D" (cffi:foreign-funcall "getuid" :uint))))
         (address (or (uiop:getenv "DBUS_SESSION_BUS_ADDRESS") (format nil "unix:path=~A/bus" runtime))))
    (format nil "~{~A~^;~}"
            (mapcar (lambda (transport)
                      (format nil "~{~A~^,~}" (remove-if (lambda (part) (uiop:string-prefix-p "guid=" part))
                                                         (uiop:split-string transport :separator '(#\,)))))
                    (uiop:split-string address :separator '(#\;))))))
(defun %open-media-bus ()
  (cffi:use-foreign-library shell-systemd)
  (cffi:with-foreign-object (out :pointer)
    (%bus-check (cffi:foreign-funcall "sd_bus_new" :pointer out :int))
    (let ((bus (cffi:mem-ref out :pointer)))
      (handler-case
          (progn
            (%bus-check (cffi:foreign-funcall "sd_bus_set_address" :pointer bus :string (%session-bus-address) :int))
            (%bus-check (cffi:foreign-funcall "sd_bus_set_bus_client" :pointer bus :int 1 :int))
            (%bus-check (cffi:foreign-funcall "sd_bus_set_method_call_timeout" :pointer bus :uint64 700000 :int))
            (%bus-check (cffi:foreign-funcall "sd_bus_start" :pointer bus :int)) bus)
        (error (cause) (cffi:foreign-funcall "sd_bus_unref" :pointer bus :pointer) (error cause))))))
(defun %bus-read (message &optional (depth 0))
  (when (> depth 10) (error "Media metadata nesting exceeds the limit."))
  (cffi:with-foreign-objects ((type :char) (contents :pointer) (value :uint64))
    (when (zerop (%bus-check (cffi:foreign-funcall "sd_bus_message_peek_type"
                              :pointer message :pointer type :pointer contents :int)))
      (return-from %bus-read (values nil nil)))
    (let* ((code (cffi:mem-ref type :char)) (character (code-char code)))
      (values
       (cond
         ((find character "sog")
          (%bus-check (cffi:foreign-funcall "sd_bus_message_read_basic" :pointer message :char code :pointer value :int))
          (%bus-text (cffi:mem-ref value :pointer)))
         ((find character "abyqniuxthdrve")
          (if (find character "arve")
              (let ((signature (%bus-text (cffi:mem-ref contents :pointer))) (items nil))
                (%bus-check (cffi:foreign-funcall "sd_bus_message_enter_container"
                              :pointer message :char code :string signature :int))
                (loop for count from 0 do
                  (multiple-value-bind (item present) (%bus-read message (1+ depth))
                    (unless present (return))
                    (when (>= count 1024) (error "Media metadata array exceeds the limit."))
                    (push item items)))
                (%bus-check (cffi:foreign-funcall "sd_bus_message_exit_container" :pointer message :int))
                (setf items (nreverse items))
                (case character (#\v (first items)) (#\e (cons (first items) (second items))) (otherwise items)))
              (progn
                (%bus-check (cffi:foreign-funcall "sd_bus_message_read_basic" :pointer message :char code :pointer value :int))
                (case character
                  (#\b (not (zerop (cffi:mem-ref value :int))))
                  (#\d (cffi:mem-ref value :double))
                  (#\x (cffi:mem-ref value :int64)) (#\t (cffi:mem-ref value :uint64))
                  (#\i (cffi:mem-ref value :int32)) (#\u (cffi:mem-ref value :uint32))
                  (#\n (cffi:mem-ref value :int16)) (#\q (cffi:mem-ref value :uint16))
                  (#\y (cffi:mem-ref value :uint8)) (otherwise nil)))))
         (t (error "Unsupported media metadata type ~A." character)))
       t))))
(defun %bus-call (bus destination path interface method &optional argument)
  (cffi:with-foreign-object (reply :pointer)
    (setf (cffi:mem-ref reply :pointer) (cffi:null-pointer))
    (unwind-protect
         (progn
           (%bus-check
            (if argument
                (cffi:foreign-funcall "sd_bus_call_method" :pointer bus :string destination :string path
                  :string interface :string method :pointer (cffi:null-pointer) :pointer reply :string "s" :string argument :int)
                (cffi:foreign-funcall "sd_bus_call_method" :pointer bus :string destination :string path
                  :string interface :string method :pointer (cffi:null-pointer) :pointer reply :string "" :int)))
           (%bus-read (cffi:mem-ref reply :pointer)))
      (cffi:foreign-funcall "sd_bus_message_unref" :pointer (cffi:mem-ref reply :pointer) :pointer))))
(cffi:defcallback %media-match :int ((message :pointer) (data :pointer) (error :pointer))
  (declare (ignore message data error)) 0)
(defun %media-match-rule (bus rule)
  (%bus-check (cffi:foreign-funcall "sd_bus_add_match" :pointer bus :pointer (cffi:null-pointer) :string rule
                :pointer (cffi:callback %media-match) :pointer (cffi:null-pointer) :int)))
(defun %media-value (properties key) (cdr (assoc key properties :test #'equal)))
(defun %media-player-view (name record)
  (let* ((props (getf record :properties)) (meta (%media-value props "Metadata"))
         (artists (%media-value meta "xesam:artist")))
    (list :name name :identity (or (getf record :identity) (subseq name (length "org.mpris.MediaPlayer2.")))
          :title (let ((title (%media-value meta "xesam:title"))) (if (and (stringp title) (plusp (length title))) title "No track information"))
          :artist (if (and (listp artists) (every #'stringp artists)) (format nil "~{~A~^, ~}" artists) "")
          :status (%media-value props "PlaybackStatus")
          :can-control (%media-value props "CanControl") :can-play (%media-value props "CanPlay")
          :can-pause (%media-value props "CanPause") :can-next (%media-value props "CanGoNext")
          :can-previous (%media-value props "CanGoPrevious"))))
(defun %publish-media (controller players chosen)
  (let* ((views (loop for name being the hash-keys of players using (hash-value record)
                     collect (%media-player-view name record)))
         (ordered (stable-sort (sort views #'string< :key (lambda (x) (getf x :name)))
                               (lambda (a b) (and (equal (getf a :status) "Playing") (not (equal (getf b :status) "Playing"))))))
         (selected (or (find chosen ordered :key (lambda (x) (getf x :name)) :test #'equal) (first ordered))))
    (%system-publish controller :available t :players ordered :player selected)))
(defun %query-media-player (bus name players)
  (handler-case
      (let* ((owner (%bus-call bus "org.freedesktop.DBus" "/org/freedesktop/DBus" "org.freedesktop.DBus" "GetNameOwner" name))
             (root (%bus-call bus name "/org/mpris/MediaPlayer2" "org.freedesktop.DBus.Properties" "GetAll" "org.mpris.MediaPlayer2"))
             (props (%bus-call bus name "/org/mpris/MediaPlayer2" "org.freedesktop.DBus.Properties" "GetAll" "org.mpris.MediaPlayer2.Player")))
        (setf (gethash name players) (list :owner owner :identity (%media-value root "Identity") :properties props)))
    (error () (remhash name players))))
(defun %media-message (bus message players)
  (cond
    ((plusp (cffi:foreign-funcall "sd_bus_message_is_signal" :pointer message :string "org.freedesktop.DBus" :string "NameOwnerChanged" :int))
     (let ((name (%bus-read message)) (old (%bus-read message)) (owner (%bus-read message)))
       (declare (ignore old))
       (when (uiop:string-prefix-p "org.mpris.MediaPlayer2." name)
         (if (zerop (length owner)) (remhash name players)
             (when (or (gethash name players) (< (hash-table-count players) 32))
               (%query-media-player bus name players))))))
    ((plusp (cffi:foreign-funcall "sd_bus_message_is_signal" :pointer message :string "org.freedesktop.DBus.Properties" :string "PropertiesChanged" :int))
     (let ((interface (%bus-read message)) (changed (%bus-read message)) (invalidated (%bus-read message))
           (sender (cffi:foreign-funcall "sd_bus_message_get_sender" :pointer message :string)))
       (when (member interface '("org.mpris.MediaPlayer2.Player" "org.mpris.MediaPlayer2") :test #'equal)
         (maphash (lambda (name record)
                    (when (equal sender (getf record :owner))
                      (if invalidated (%query-media-player bus name players)
                          (if (equal interface "org.mpris.MediaPlayer2")
                              (when (assoc "Identity" changed :test #'equal) (setf (getf record :identity) (%media-value changed "Identity")))
                              (dolist (pair changed)
                                (setf (getf record :properties)
                                      (acons (car pair) (cdr pair) (remove (car pair) (getf record :properties) :key #'car :test #'equal))))))))
                  players))))))
(defun %media-poll-timeout (bus)
  (cffi:with-foreign-objects ((timeout :uint64) (now '(:struct shell-timespec)))
    (%bus-check (cffi:foreign-funcall "sd_bus_get_timeout" :pointer bus :pointer timeout :int))
    (let ((deadline (cffi:mem-ref timeout :uint64)))
      (if (= deadline #xffffffffffffffff) -1
          (progn
            (cffi:foreign-funcall "clock_gettime" :int 1 :pointer now :int)
            (let* ((current (+ (* 1000000 (cffi:foreign-slot-value now '(:struct shell-timespec) 'seconds))
                               (floor (cffi:foreign-slot-value now '(:struct shell-timespec) 'nanoseconds) 1000)))
                   (remaining (- deadline current)))
              (max 0 (min 2147483647 (ceiling remaining 1000)))))))))
(defun %run-media (controller)
  (let ((bus (%open-media-bus)) (players (make-hash-table :test #'equal)) (chosen nil))
    (unwind-protect
         (progn
           (%media-match-rule bus "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0namespace='org.mpris.MediaPlayer2'")
           (%media-match-rule bus "type='signal',path='/org/mpris/MediaPlayer2',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged'")
           (dolist (name (%bus-call bus "org.freedesktop.DBus" "/org/freedesktop/DBus" "org.freedesktop.DBus" "ListNames"))
             (when (and (uiop:string-prefix-p "org.mpris.MediaPlayer2." name) (< (hash-table-count players) 32))
               (%query-media-player bus name players)))
           (%publish-media controller players chosen)
           (loop until (%system-stopped-p controller) do
             (dolist (command (%system-commands controller))
               (%system-publish controller :error nil)
               (handler-case
                   (case (car command)
                     (:player (when (gethash (cdr command) players) (setf chosen (cdr command))))
                     (:refresh (maphash (lambda (name record) (declare (ignore record)) (%query-media-player bus name players)) players))
                     (otherwise
                      (let* ((player (getf (%system-view controller) :player))
                             (method (ecase (car command) (:play-pause "PlayPause") (:next "Next") (:previous "Previous") (:stop "Stop")))
                             (capability (case (car command) (:next :can-next) (:previous :can-previous)
                                               (:play-pause (if (equal (getf player :status) "Playing") :can-pause :can-play)) (otherwise :can-control))))
                        (when (and (getf player :can-control) (getf player capability))
                          (%bus-call bus (getf player :name) "/org/mpris/MediaPlayer2" "org.mpris.MediaPlayer2.Player" method)
                          (%query-media-player bus (getf player :name) players)))))
                 (error (cause) (%system-publish controller :error (short-ui-text (princ-to-string cause) 140)))))
             (%publish-media controller players chosen)
             (cffi:with-foreign-object (message :pointer)
               (loop repeat 64 for result = (%bus-check (cffi:foreign-funcall "sd_bus_process" :pointer bus :pointer message :int))
                     while (plusp result) do
                       (unless (cffi:null-pointer-p (cffi:mem-ref message :pointer))
                         (unwind-protect (%media-message bus (cffi:mem-ref message :pointer) players)
                           (cffi:foreign-funcall "sd_bus_message_unref" :pointer (cffi:mem-ref message :pointer) :pointer)))
                       (%publish-media controller players chosen)))
             (unless (%system-stopped-p controller)
               (%system-wait controller (%media-poll-timeout bus)
                             (%bus-check (cffi:foreign-funcall "sd_bus_get_fd" :pointer bus :int))
                             (%bus-check (cffi:foreign-funcall "sd_bus_get_events" :pointer bus :int))))))
      (cffi:foreign-funcall "sd_bus_flush_close_unref" :pointer bus :pointer))))
