(in-package #:ataxia.infinite-world)

(defclass rmlui-shell-popup (rmlui-shell-widget)
  ((kind :initform :apps :accessor %shell-popup-kind)
   (bar :initform nil :accessor %shell-popup-bar)
   (entries :initform nil :accessor %shell-popup-entries)
   (matches :initform nil :accessor %shell-popup-matches)
   (page :initform 0 :accessor %shell-popup-page)
   (selected :initform 0 :accessor %shell-popup-selected)
   (search-focused-p :initform t :accessor %shell-search-focused-p)))

(defun %shell-class (popup name value)
  (%bar-cached popup (list :class name) value
               (lambda (component) (ataxia.world.rmlui:set-rmlui-class component "panel" name value))))
(defun %bar-close-popup (world bar)
  (let ((popup (%bar-popup bar)))
    (when popup
      (setf (%bar-popup bar) nil)
      ;; Hide restores the displaced application's keyboard focus before retirement.
      (hide-overlay world popup)
      (remove-agent-widget world popup)))
  bar)
(defun %bar-position-popup (world bar state)
  (let ((popup (%bar-popup bar)))
    (when popup
      (multiple-value-bind (ow oh) (%output-logical-size state)
        (let* ((apps (eq :apps (%shell-popup-kind popup)))
               (width (max 1d0 (min (if apps 590d0 390d0) (- ow 16d0))))
               (height (max 1d0 (min (if apps 630d0 410d0) (- oh 100d0))))
               (anchor (if apps (canvas-overlay-x bar)
                           (- (+ (canvas-overlay-x bar) (canvas-overlay-width bar)) width))))
          (%meta-reposition-ui world popup (max 0d0 (min (- ow width) anchor))
                               (max 0d0 (- (canvas-overlay-y bar) height -6d0)) width height)
          (%shell-class popup "small" (< width 460d0)))))))
(defun %bar-update-power-popup (popup power)
  (let ((capacity (getf power :capacity)) (health (getf power :health))
        (cycles (getf power :cycles)) (tone (%bar-power-tone power)))
    (%bar-text popup "percent" (if capacity (format nil "~D%" capacity) (if (eq :ac (getf power :status)) "AC" "—")))
    (%bar-style popup "big-battery" "display" (if capacity "block" "none"))
    (%bar-style popup "fill" "width" (format nil "~D%" (or capacity 0)))
    (%bar-text popup "state" (%bar-power-status power))
    (%bar-text popup "estimate" (%bar-power-estimate power))
    (%bar-text popup "health" (if health (format nil "~D% of design" health) "Unavailable"))
    (%bar-text popup "cycles" (if cycles (princ-to-string cycles) "Unavailable"))
    (%bar-text popup "source" (if (or (getf power :online) (eq :ac (getf power :status))) "AC adapter" "Battery"))
    (%bar-text popup "note" (case tone (:critical "Battery is very low. Connect your charger soon.")
                                 (:low "Battery is running low.")
                                 (t "Time estimates vary with your current power usage.")))
    (%shell-class popup "low" (eq tone :low))
    (%shell-class popup "critical" (eq tone :critical))))

(defun %shell-app-priority (entry)
  (or (position (%desktop-entry-id entry)
                '("firefox" "org.mozilla.firefox" "chromium" "org.gnome.Epiphany"
                  "wezterm" "foot" "emacs" "org.gnome.Nautilus"
                  "org.gnome.Calculator" "org.gnome.TextEditor") :test #'string-equal) 100))
(defun %shell-apps (world output)
  ;; Reuse the desktop catalogue already loaded by the World's launcher.
  (let ((launcher (%launcher-for-output world output)))
    (stable-sort (copy-list (and launcher (%launcher-desktop-entries launcher))) #'< :key #'%shell-app-priority)))
(defun %shell-select (popup index)
  (let ((count (min 6 (max 0 (- (length (%shell-popup-matches popup)) (* 6 (%shell-popup-page popup)))))))
    (setf (%shell-popup-selected popup) (max 0 (min (1- count) index)))
    (loop for i below 6 do
      (%bar-cached popup (list :selected i) (= i (%shell-popup-selected popup))
                   (lambda (component) (ataxia.world.rmlui:set-rmlui-class component (format nil "app~D" i) "selected" (= i (%shell-popup-selected popup))))))))
(defun %shell-results (popup)
  (let* ((matches (%shell-popup-matches popup)) (count (length matches))
         (pages (max 1 (ceiling count 6)))
         (page (max 0 (min (1- pages) (%shell-popup-page popup)))))
    (setf (%shell-popup-page popup) page)
    (%bar-text popup "count" (format nil "~D application~:P" count))
    (%bar-text popup "page" (format nil "~D / ~D" (1+ page) pages))
    (%bar-style popup "empty" "display" (if (zerop count) "block" "none"))
    (loop for i below 6 for entry = (nth (+ (* page 6) i) matches) do
      (%bar-style popup (format nil "app~D" i) "display" (if entry "flex" "none"))
      (when entry
        (%bar-text popup (format nil "name~D" i) (%bar-short-text (%desktop-entry-name entry) 22))
        (%bar-text popup (format nil "icon~D" i) (if (plusp (length (%desktop-entry-name entry))) (string-upcase (subseq (%desktop-entry-name entry) 0 1)) "?"))))
    (%shell-select popup 0)))
(defun %shell-search (popup query)
  (let ((query (string-trim '(#\Space #\Tab) query)))
    (setf (%shell-popup-matches popup)
          (remove-if-not (lambda (entry)
                           (or (search query (%desktop-entry-name entry) :test #'char-equal)
                               (search query (%desktop-entry-detail entry) :test #'char-equal)
                               (search query (%desktop-entry-id entry) :test #'char-equal)))
                         (%shell-popup-entries popup))
          (%shell-popup-page popup) 0)
    (%shell-results popup)))
(defun %shell-launch (world popup index)
  (when (<= 0 index 5)
    (let ((entry (nth (+ (* 6 (%shell-popup-page popup)) index) (%shell-popup-matches popup))))
      (when entry
        (%bar-close-popup world (%shell-popup-bar popup))
        (%launch-desktop-entry world entry)))))
(defun %bar-toggle-popup (world bar kind)
  (let ((existing (%bar-popup bar)))
    (%bar-close-popup world bar)
    (when (and existing (eq kind (%shell-popup-kind existing))) (return-from %bar-toggle-popup nil)))
  (let* ((state (gethash (canvas-overlay-output bar) (%world-outputs world)))
         (seat (%bar-seat world state))
         (seat-state (and seat (gethash seat (%world-seats world))))
         (previous (and seat (%meta-focused-object world seat)))
         (path (asdf:system-relative-pathname "ataxia-rmlui"
                 (if (eq kind :apps) "src/world/rmlui/status-bar/menu.rml" "src/world/rmlui/status-bar/power.rml")))
         (popup (%create-agent-widget 'rmlui-shell-popup world (uiop:read-file-string path)
                                      :component-factory #'ataxia.world.rmlui:make-rmlui-component
                                      :source-path (namestring path) :output (canvas-overlay-output bar)
                                      :width 590d0 :height 510d0 :layer 1300)))
    (setf (%shell-popup-kind popup) kind (%shell-popup-bar popup) bar (%bar-popup bar) popup)
    (handler-case
        (progn
          (%bar-position-popup world bar state)
          (bind-agent-widget-event popup "close" (lambda (widget event) (declare (ignore widget event)) (%bar-close-popup world bar)))
          (if (eq kind :power)
              (%bar-update-power-popup popup (%bar-power))
              (progn
                (setf (%shell-popup-entries popup) (%shell-apps world (canvas-overlay-output bar)))
                (ataxia.world.rmlui:set-rmlui-model (canvas-overlay-component popup) "query" "")
                (bind-agent-widget-event popup "model:query"
                                         (lambda (widget event) (%shell-search widget (agent-widget-event-value event))))
                (bind-agent-widget-event popup "search:focus"
                                         (lambda (widget event) (declare (ignore event)) (setf (%shell-search-focused-p widget) t)))
                (bind-agent-widget-event popup "search:blur"
                                         (lambda (widget event) (declare (ignore event)) (setf (%shell-search-focused-p widget) nil)))
                (%shell-search popup "")
                (loop for i below 6 do
                  (let ((index i)) (bind-agent-widget-event popup (format nil "app~D" i)
                                    (lambda (widget event) (declare (ignore event)) (%shell-launch world widget index)))))
                (dolist (entry '(("prev" . -1) ("next" . 1)))
                  (let ((direction (cdr entry)))
                    (bind-agent-widget-event popup (car entry)
                                             (lambda (widget event) (declare (ignore event))
                                               (incf (%shell-popup-page widget) direction) (%shell-results widget)))))
                (bind-agent-widget-event popup "power" (lambda (widget event) (declare (ignore widget event)) (%bar-toggle-popup world bar :power)))
                (bind-agent-widget-event popup "overview" (lambda (widget event) (declare (ignore widget event))
                                                            (%bar-close-popup world bar) (%bar-action world bar :overview)))))
          (when seat-state
            (setf (%canvas-seat-previous-focus seat-state) previous)
            (%focus-target world seat-state popup))
          popup)
      (error (cause) (%bar-close-popup world bar) (error cause)))))

(defun %shell-popup-on-seat (world seat)
  (let ((state (gethash seat (%world-seats world))))
    (and state (find-if (lambda (widget)
                         (and (typep widget 'rmlui-shell-popup)
                              (%overlay-on-state-p widget (%canvas-seat-output state))))
                       (world-overlays world)))))
(defmethod ataxia.kernel:world-cursor-button :before ((world metaworld) seat input)
  (when (eq :pressed (ataxia.kernel:cursor-button-input-state input))
    (let* ((popup (%shell-popup-on-seat world seat))
           (seat-state (gethash seat (%world-seats world))))
      (when (and popup (not (%meta-pointer-in-ui-p seat-state popup))
                 (not (%meta-pointer-in-ui-p seat-state (%shell-popup-bar popup))))
        (%bar-close-popup world (%shell-popup-bar popup))))))
(defmethod ataxia.kernel:world-key-event :around ((world metaworld) seat input)
  (let* ((popup (%shell-popup-on-seat world seat))
         (seat-state (gethash seat (%world-seats world)))
         (symbol (when (and popup (typep input 'ataxia.kernel:key-input)
                            (eq :pressed (ataxia.kernel:key-input-state input)))
                   (find-if (lambda (x) (member x '(#xff1b #xff0d #xff52 #xff54 #xff55 #xff56)))
                            (map 'vector #'ataxia.world.rmlui::%key-symbol-number (ataxia.kernel:key-input-keysyms input))))))
    (if (and popup symbol (eq popup (%canvas-seat-focused seat-state))
             (or (= symbol #xff1b) (and (eq :apps (%shell-popup-kind popup)) (%shell-search-focused-p popup)))
             (not (intersection '(:logo :control :alt) (ataxia.kernel:key-input-modifiers input))))
        (case symbol
          (#xff1b (%bar-close-popup world (%shell-popup-bar popup)))
          (otherwise
           (when (eq :apps (%shell-popup-kind popup))
             (case symbol
               (#xff0d (%shell-launch world popup (%shell-popup-selected popup)))
               (#xff52 (%shell-select popup (1- (%shell-popup-selected popup))))
               (#xff54 (%shell-select popup (1+ (%shell-popup-selected popup))))
               (#xff55 (decf (%shell-popup-page popup)) (%shell-results popup))
               (#xff56 (incf (%shell-popup-page popup)) (%shell-results popup))))))
        (call-next-method))))
