;;;; Power presentation and explicit human actions, shared by every desktop World.
(in-package #:ataxia.world.shell)

(defun %power-model (popup name value)
  (cache-widget-value popup (list :model name) value
    (lambda (component) (ataxia.world.rmlui:set-rmlui-model component name value))))
(defun %power-popup-height (popup)
  ;; Size from cached presentation state; never poll the backend during layout.
  (setf (gethash :preferred-height (widget-cache popup))
        (+ 132d0
           (if (equal "block" (gethash '("estimate" "display") (widget-cache popup))) 16d0 0d0)
           (if (equal "block" (gethash '("note" "display") (widget-cache popup))) 32d0 0d0)
           (if (equal "block" (gethash '("brightness-note" "display") (widget-cache popup))) 32d0 0d0)
           (if (gethash :sleep-detail (widget-cache popup)) 32d0 0d0))))
(defun %update-power-controls (popup service view)
  (let* ((backlight (getf view :backlight))
         (percent (or (shell-service-brightness-target service) (getf backlight :percent)))
         (slider-value (and percent (princ-to-string (max 1 percent))))
         (capability (getf view :suspend-state))
         (sleeping (getf view :suspend-pending)))
    (%power-model popup "brightness_disabled" (null backlight))
    (%power-model popup "sleep_disabled" (or sleeping (not (eq capability :yes))))
    ;; Always reconcile the range model: a failed request may have changed the
    ;; native value without changing our cached last confirmed percentage.
    (when (and slider-value
               (not (equal slider-value
                           (ataxia.world.rmlui:rmlui-model-value (overlay-component popup) "brightness"))))
      (ataxia.world.rmlui:set-rmlui-model (overlay-component popup) "brightness" slider-value))
    (set-widget-text popup "brightness-value" (if percent (format nil "~D%" percent) "Unavailable"))
    (set-widget-text popup "brightness-note"
                     (or (getf view :brightness-error)
                         (if backlight "" "No controllable display backlight")))
    (set-widget-style popup "brightness-note" "display"
                      (if (or (getf view :brightness-error) (null backlight)) "block" "none"))
    (setf (gethash :sleep-detail (widget-cache popup))
          (or (getf view :suspend-error) (not (eq capability :yes))))
    (set-widget-text popup "sleep" (if sleeping "Sleeping…" "Sleep"))
    (set-widget-text popup "sleep-note"
                     (or (getf view :suspend-error)
                         (case capability
                           (:yes "Suspend · power button wakes")
                           (:loading "Checking sleep availability…")
                           ((:no :challenge) "Sleep requires system authorization.")
                           (otherwise "Sleep is unavailable on this system."))))
    (%power-popup-height popup)))
(defun %sync-power-controls (world service)
  (let ((view (%power-view (shell-service-power service))))
    (unless (getf view :brightness-pending) (setf (shell-service-brightness-target service) nil))
    (%update-brightness-osd world service view)
    (dolist (bar (status-bars world))
      (let ((popup (%bar-popup bar)))
        (when (and popup (eq :power (%shell-popup-kind popup)))
          (%update-power-controls popup service view))))))
(defun %request-brightness (world service value &key relative output)
  (let* ((controller (shell-service-power service))
         (view (%power-view controller))
         (current (or (shell-service-brightness-target service)
                      (getf (getf view :backlight) :percent))))
    (when output (setf (shell-service-feedback-output service) output))
    (when current
      (let ((target (max 1 (min 100 (if relative (+ current value) value)))))
        (when (and (/= target current) (%power-queue controller :brightness target))
          (setf (shell-service-brightness-target service) target))
        (%sync-power-controls world service)
        (%show-osd world service :brightness target "Display backlight" :output output)))))
(defun %request-suspend (world service)
  (let ((controller (shell-service-power service)))
    (when (eq :yes (getf (%power-view controller) :suspend-state))
      (%power-queue controller :suspend)
      (%sync-power-controls world service))))
(defun %bind-power-controls (world popup)
  (let ((service (world-service world :shell)))
    (ataxia.world.rmlui:set-rmlui-model (overlay-component popup) "brightness" "1")
    (dolist (entry '(("brightness-down" . -5) ("brightness-up" . 5)))
      (let ((step (cdr entry)))
        (bind-agent-widget-event popup (car entry)
          (lambda (widget event)
            (declare (ignore event))
            (%request-brightness world service step :relative t :output (overlay-output widget))))))
    (bind-agent-widget-event popup "model:brightness"
      (lambda (widget event)
        (let ((value (ignore-errors (parse-integer (agent-widget-event-value event)))))
          (when value (%request-brightness world service value :output (overlay-output widget))))))
    (bind-agent-widget-event popup "sleep"
      (lambda (widget event) (declare (ignore widget event)) (%request-suspend world service)))
    (%power-queue (shell-service-power service) :refresh)
    (%sync-power-controls world service)))
(defun %power-key-event (world service seat input)
  (when (and (typep input 'ataxia.kernel:key-input)
             (not (intersection '(:logo :control :alt) (ataxia.kernel:key-input-modifiers input))))
    (let ((key (find-if (lambda (key) (member key '("XF86MonBrightnessUp" "XF86MonBrightnessDown"
                                                  "XF86Sleep" "XF86Suspend") :test #'equal))
                        (ataxia.kernel:key-input-keysyms input))))
      (when key
        (if (member key '("XF86Sleep" "XF86Suspend") :test #'equal)
            (let ((token (list seat (ataxia.kernel:key-input-device input) key)))
              (if (eq :released (ataxia.kernel:key-input-state input))
                  (remhash token (shell-service-sleep-keys service))
                  (unless (gethash token (shell-service-sleep-keys service))
                    (setf (gethash token (shell-service-sleep-keys service)) t)
                    (%request-suspend world service))))
            (when (eq :pressed (ataxia.kernel:key-input-state input))
              (%request-brightness world service (if (equal key "XF86MonBrightnessUp") 5 -5)
                                   :relative t :output (world-seat-output world seat))))
        t))))
