(in-package #:ataxia.world.shell)
(defclass rmlui-status-bar (shell-status-bar ataxia.world.rmlui:rmlui-widget) ())
(defclass rmlui-shell-popup (shell-popup ataxia.world.rmlui:rmlui-widget) ())
(defclass rmlui-shell-osd (shell-osd ataxia.world.rmlui:rmlui-widget) ())
;; Keep the existing RmlUi cache API for its presentation widgets.
(defmethod shell-cache ((widget rmlui-status-bar)) (ataxia.world.rmlui:widget-cache widget))
(defmethod shell-cache ((widget rmlui-shell-popup)) (ataxia.world.rmlui:widget-cache widget))
(defmethod shell-cache ((widget rmlui-shell-osd)) (ataxia.world.rmlui:widget-cache widget))
(defmethod set-shell-class ((component ataxia.world.rmlui:rmlui-component) id name enabled)
  (ataxia.world.rmlui:set-rmlui-class component id name enabled))
(defmethod set-shell-model ((component ataxia.world.rmlui:rmlui-component) name value)
  (ataxia.world.rmlui:set-rmlui-model component name value))
(defmethod shell-model-value ((component ataxia.world.rmlui:rmlui-component) name)
  (ataxia.world.rmlui:rmlui-model-value component name))
(defmethod set-shell-element-style ((component ataxia.world.rmlui:rmlui-component) id property value)
  (ataxia.world.rmlui:set-rmlui-style component id property value))
(defmethod make-shell-widget ((service shell-service) world kind &rest options)
  (declare (ignore service))
  (let* ((name (case kind (:apps "menu") (:spaces "workspaces") (otherwise (string-downcase kind))))
         (path (asdf:system-relative-pathname "ataxia-rmlui" (format nil "src/world/rmlui/status-bar/~A.rml" name)))
         (class (case kind (:bar 'rmlui-status-bar) (:osd 'rmlui-shell-osd) (otherwise 'rmlui-shell-popup))))
    (apply #'create-agent-widget class world (uiop:read-file-string path)
           :component-factory #'ataxia.world.rmlui:make-shell-rmlui-component
           :source-path (namestring path) options)))
(defun enable-rmlui-status-bar (world &rest options)
  (apply #'enable-status-bar world (make-shell-service) options))
(defun disable-rmlui-status-bar (world &rest options)
  (apply #'disable-status-bar world options))
