;;;; Optional shell chrome, owned and scheduled by the World.
(in-package #:ataxia.infinite-world)

(defclass rmlui-shell-widget (agent-widget)
  ((cache :initform (make-hash-table :test #'equal) :reader %bar-cache)))
(defclass rmlui-status-bar (rmlui-shell-widget)
  ((popup :initform nil :accessor %bar-popup)))
(defvar *rmlui-status-bars* (make-hash-table :test #'eq :weakness :key))

(defun %bar-cached (bar key value function)
  (unless (equal (gethash key (%bar-cache bar) :absent) value)
    (funcall function (canvas-overlay-component bar))
    (setf (gethash key (%bar-cache bar)) value)))
(defun %bar-text (bar id value)
  (%bar-cached bar id value
               (lambda (component) (ataxia.world.rmlui:set-rmlui-property component id value))))
(defun %bar-style (bar id property value)
  (%bar-cached bar (list id property) value
               (lambda (component) (ataxia.world.rmlui:set-rmlui-style component id property value))))
(defun %bar-class (bar name value)
  (%bar-cached bar (list :class name) value
               (lambda (component) (ataxia.world.rmlui:set-rmlui-class component "bar" name value))))
(defun %bar-seat (world state)
  (let ((seat (find state (%seat-states world) :key #'%canvas-seat-output)))
    (and seat (%canvas-seat-seat seat))))
(defun %bar-short-text (text limit)
  (if (> (length text) limit) (concatenate 'string (subseq text 0 (- limit 1)) "…") text))

(defun %bar-sync (world bar state)
  (multiple-value-bind (width height) (%output-logical-size state)
    (let* ((bar-width (max 1d0 (min 1320d0 (- width 16d0))))
           (tiny (< bar-width 380d0))
           (group (%meta-view-active (%meta-view-for-state world state)))
           (groups (metaworld-subworlds world))
           (selected (if group (subworld-workspace group) 0))
           (count (min 9 (max 3 (if group (%meta-workspace-count group) (length groups)))))
           (slots (if (< bar-width 680d0) 3 9))
           (first-slot (max 1 (min (- count slots -1) (- selected (floor slots 2)))))
           (seat (%bar-seat world state))
           (focused (%meta-focused-object world seat)))
      (%meta-reposition-ui world bar (/ (- width bar-width) 2d0) (max 0d0 (- height 88d0)) bar-width 80d0)
      (%bar-class bar "compact" (< bar-width 1050d0))
      (%bar-class bar "narrow" (< bar-width 680d0))
      (%bar-class bar "tiny" tiny)
      (%bar-text bar "group" (%bar-short-text (if group (subworld-name group) "Overview") 20))
      (%bar-text bar "title"
                 (%bar-short-text
                  (if (typep focused 'canvas-window)
                      (or (ataxia.kernel:application-title (canvas-window-application focused)) "Untitled")
                      (if group (format nil "~A · workspace ~D" (subworld-name group) selected)
                          "Your space, at a glance.")) 90))
      (%bar-text bar "apps" (format nil "~D apps" (length (%world-stacking world))))
      (%bar-style bar "selection" "opacity" (if group "1" "0"))
      (loop for position from 0 below 9 do
        (%bar-class bar (format nil "position-~D" position) (= position (max 0 (- selected first-slot)))))
      (loop for index from 1 to 9 for id = (format nil "ws~D" index) do
        (%bar-style bar id "display" (if (<= first-slot index (min count (+ first-slot slots -1))) "block" "none"))
        (%bar-cached bar (list :selected index) (= index selected)
                     (lambda (component) (ataxia.world.rmlui:set-rmlui-class component id "selected" (= index selected))))))))

(defun %bar-maintain (world source)
  (unless (%world-quiescing-p world)
    (let ((now (get-universal-time)))
      (let ((power (%bar-power)))
        (dolist (bar (remove-if-not (lambda (widget) (typep widget 'rmlui-status-bar)) (world-overlays world)))
          (%bar-clock bar now power)))
      (when source (ataxia.runtime:update-event-loop-timer source (* 1000 (min 30 (- 60 (mod now 60)))))))))

(defun %bar-action (world bar action &optional number)
  (let* ((state (gethash (canvas-overlay-output bar) (%world-outputs world)))
         (seat (%bar-seat world state))
         (view (%meta-view-for-state world state))
         (group (%meta-view-active view))
         (groups (metaworld-subworlds world)))
    ;; Commands require a seat on this output; never steer another output by fallback.
    (when seat
      (unless (member action '(:menu :power)) (%bar-close-popup world bar))
      (case action
        (:menu (%bar-toggle-popup world bar :apps))
        (:power (%bar-toggle-popup world bar :power))
        (:overview (%meta-overview world seat state))
        (:workspace (if group (%meta-switch-workspace world group number seat)
                        (when (nth (1- number) groups) (enter-subworld world (nth (1- number) groups) seat))))
        ((:previous :next)
         (when groups
           (enter-subworld world (nth (mod (+ (or (position group groups) (if (eq action :next) -1 0))
                                               (if (eq action :next) 1 -1)) (length groups)) groups) seat))))
      (%request-output-state-frame world state))))

(defun %bar-create (world state)
  (let* ((path (asdf:system-relative-pathname "ataxia-rmlui" "src/world/rmlui/status-bar/bar.rml"))
         (bar (%create-agent-widget 'rmlui-status-bar world (uiop:read-file-string path)
                                   :component-factory #'ataxia.world.rmlui:make-rmlui-component
                                   :source-path (namestring path) :output (%canvas-output-output state)
                                   :width 1000d0 :height 80d0 :layer 1150)))
    (dolist (entry '(("home" . :menu) ("power" . :power) ("group" . :overview) ("previous" . :previous) ("next" . :next)))
      (let ((action (cdr entry)))
        (bind-agent-widget-event bar (car entry)
                                 (lambda (widget event) (declare (ignore event)) (%bar-action world widget action)))))
    (loop for index from 1 to 9 do
      (let ((number index))
        (bind-agent-widget-event bar (format nil "ws~D" index)
                                 (lambda (widget event) (declare (ignore event)) (%bar-action world widget :workspace number)))))
    (%bar-sync world bar state)
    bar))

(defun disable-rmlui-status-bar (world)
  "Remove the bars and their maintenance timer. Call on the World owner thread."
  (let ((timer (gethash world *rmlui-status-bars*)))
    (when timer (ataxia.runtime:remove-event-loop-source timer)))
  (remhash world *rmlui-status-bars*)
  (dolist (widget (copy-list (world-overlays world)))
    (when (typep widget 'rmlui-status-bar)
      (%bar-close-popup world widget)
      (remove-agent-widget world widget)))
  world)
(defun enable-rmlui-status-bar (world)
  "Install one responsive RmlUi bar per output. Repeated calls are safe."
  (check-type world metaworld)
  (disable-rmlui-status-bar world)
  (handler-case
      (progn
        (maphash (lambda (output state) (declare (ignore output)) (%bar-create world state)) (%world-outputs world))
        (setf (gethash world *rmlui-status-bars*)
              (ataxia.runtime:add-event-loop-timer (ataxia.kernel:kernel-runtime (ataxia.kernel:world-kernel world))
                                                  (lambda (source) (%bar-maintain world source) 0)))
        (%bar-maintain world (gethash world *rmlui-status-bars*))
        world)
    (error (cause) (disable-rmlui-status-bar world) (error cause))))

(defmethod %prepare-canvas-frame :after ((world metaworld) state)
  (when (gethash world *rmlui-status-bars*)
    (dolist (widget (world-overlays world))
      (when (and (typep widget 'rmlui-status-bar) (%overlay-on-state-p widget state))
        (%bar-sync world widget state)
        (when (%bar-popup widget) (%bar-position-popup world widget state))))))
(defmethod ataxia.kernel:world-output-added :after ((world infinite-world) output)
  (when (gethash world *rmlui-status-bars*)
    (%bar-create world (gethash output (%world-outputs world)))
    (%bar-maintain world nil)))
(defmethod ataxia.kernel:world-quiescing :around ((world metaworld) reason)
  (when (gethash world *rmlui-status-bars*) (disable-rmlui-status-bar world))
  (call-next-method world reason))

(export '(enable-rmlui-status-bar disable-rmlui-status-bar) :ataxia.infinite-world)
